### ISSUE TITLE
wrong gpl license detected for a license text

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#100]
OS: windows 7 64 bit
I've updated my scancode to the latest version available.
file : [ref_array.txt](https://github.com/nexB/scancode-toolkit/files/16170/ref_array.txt)
```
scancode output : 
Path	                                         What	Start Line	End Line	Info
C:/doc/temporary/issue_files/ref_array.h	     License	12	       15		GPL
```
The above file has license text for LGPL 3.0 or later in lines 8 to 17 but GPL license is detected by scancode.

**Comment by pombredanne** [comment]
All merged. Thanks
