### ISSUE TITLE
subset of data lost in json2csv

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1002]
```
C:\Users\CYL\git\scancode-toolkit>bin\python.exe etc\scripts\json2csv.py C:\Users\CYL\Downloads\activation-1.1-info_identified.json C:\Users\CYL\Downloads\activation-1.1-info_identified.csv
```
Note that the JSON file has the Package ID result, but the converted CSV is missing these package information.
[activation-1.1-identified.zip](https://github.com/nexB/scancode-toolkit/files/1839842/activation-1.1-identified.zip)

**Comment by pombredanne** [comment]
Thanks. The issue that json2csv is
1. outdated and now handled by the csv output from scancode proper
2. it knows only about the base ABCD data that ScanCode knows about. It (the cvs ouput) could be updated to handle arbitrary ABCD data

**Comment by pombredanne** [comment]
@chinyeungli using the latest develop and `--from-json` to format a CSV should work fine now. Closing. Thanks~
