### ISSUE TITLE
Use ScanCode codebase-resource outside of ScanCode

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1004]
I would like to use the codebase-resource model from ScanCode in other projects, such as AboutCode Toolkit and other projects that deal with ABC Data.

**Comment by pombredanne** [comment]
This is closely related to #926

**Comment by pombredanne** [comment]
@JonoYang @majurg most everything is there now. The last bit will be to move resource.py to commoncode and release commoncode as a lighter-weight standalone library

**Comment by majurg** [comment]
@pombredanne This is all finished. Commoncode now has `resource.py` support and its external repo can be found here: https://github.com/nexB/commoncode
