### ISSUE TITLE
Crash when scanning

### ISSUE THREAD

**Issue by zoltanblenessygfi** [nexB/scancode-toolkit#1007]
Hello, 

I am trying to scan a somewhat complex project, I use multiple --ignore switches and others. My command looks like this: 
sudo scancode --license --license-diag --output-html-app ossreport/index.html --timeout 7200 -n 10 . --ignore "*.gif" --ignore "*.pdf" --ignore "*.rtf" --ignore "*.idx" --ignore "*.csv" --ignore "**/cvs-rlog-full.txt" --ignore "**/ChangeLog" --ignore "/ossreport" --ignore "**/test" --ignore "**/tests" --ignore "**/doc" --ignore "protractor" --verbose

Scan always crashes with the following stack: 
Traceback (most recent call last):
  File "/usr/local/bin/scancode", line 11, in <module>
    sys.exit(scancode())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/utils.py", line 79, in main
    standalone_mode=standalone_mode, **extra)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 707, in scancode
    stage='scan', kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 852, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 955, in scan_codebase
    codebase.save_resource(resource)
  File "/usr/local/lib/python2.7/dist-packages/scancode/resource.py", line 515, in save_resource
    raise UnknownResource('Not part of codebase: %(resource)r' % resource)
TypeError: format requires a mapping

OS: Ubuntu 16.04 with latest updates
Python: 2.7.12-1~16.04
ScanCode: 2.9.1

Depending on how I play with the ignores / switches, crashes may occur sooner or later. 

I am unable to share link to the source code being scanned, but I am happy to provide any extra info needed to check on this one. 

Thanks!

**Comment by pombredanne** [comment]
@zoltanblenessygfi Thanks for the report. This is a bug on two counts:
1. it should not crash scancode in anycase
2. their is also a bug in the code supposed to handle the exception making it harder to investigate.

Let me see if I can first push a small fix so you can get proper details on the error message.
Then we can start working on the error proper

**Comment by JonoYang** [comment]
@zoltanblenessygfi Just curious, why do you run ScanCode with sudo?

**Comment by JonoYang** [comment]
@zoltanblenessygfi 

I have pushed a fix to ensure that the error message is displayed properly with the path of the file that is creating the error. Please pull in the new changes in develop branch from the git repository.

If you are unsure about git usage, you can download this tarball instead: https://github.com/nexB/scancode-toolkit/archive/fd2e483e346a38ee9634538a0f05ca4dd96fb622.tar.gz

After you have the latest changes, run this command:

```
sudo scancode --info --json ossreport/index.json -n -1 . --ignore "*.gif" --ignore "*.pdf" --ignore "*.rtf" --ignore "*.idx" --ignore "*.csv" --ignore "**/cvs-rlog-full.txt" --ignore "**/ChangeLog" --ignore "/ossreport" --ignore "**/test" --ignore "**/tests" --ignore "**/doc" --ignore "protractor" --verbose
```

This should provide some more details and fail reasonably fast on the file that has a problem.

**Comment by JonoYang** [comment]
@zoltanblenessygfi 

I have tried to reproduce your error based on the ScanCode command you gave us. I created a set of directories and files that match the pattern of your ignores. Please download and extract the following zip and run ScanCode with the same command you used on your code. Let us know if you get the same error or not.

[scancode-ignore.zip](https://github.com/nexB/scancode-toolkit/files/1850088/scancode-ignore.zip)

**Comment by zoltanblenessygfi** [comment]
Hello, 

Thanks for the fast reply. 

FYI - I am running the scan with sudo because the folder structure I am scanning was created by root, so I need proper rights there.

I have retrieved your change on the .py file, re-run my original scan command and now I have a more detailed call stack as follows: 
Traceback (most recent call last):
  File "/usr/local/bin/scancode", line 11, in <module>
    sys.exit(scancode())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/utils.py", line 79, in main
    standalone_mode=standalone_mode, **extra)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 707, in scancode
    stage='scan', kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 852, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 955, in scan_codebase
    codebase.save_resource(resource)
  File "/usr/local/lib/python2.7/dist-packages/scancode/resource.py", line 515, in save_resource
    raise UnknownResource('Not part of codebase: %(resource)r' % locals())
scancode.resource.UnknownResource: Not part of codebase: ScannedResource(name='.eslintrc', path=u'node_modules/request/node_modules/qs/test/.eslintrc', rid=11428, pid=11421, is_file=True, is_filtered=False, licenses=[])

Running your exact command on the same folder structure also results in error, call stack is the following: 
Traceback (most recent call last):
  File "/usr/local/bin/scancode", line 11, in <module>
    sys.exit(scancode())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/utils.py", line 79, in main
    standalone_mode=standalone_mode, **extra)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 707, in scancode
    stage='scan', kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 852, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 955, in scan_codebase
    codebase.save_resource(resource)
  File "/usr/local/lib/python2.7/dist-packages/scancode/resource.py", line 515, in save_resource
    raise UnknownResource('Not part of codebase: %(resource)r' % locals())
scancode.resource.UnknownResource: Not part of codebase: ScannedResource(name='.eslintrc', path=u'node_modules/request/node_modules/qs/test/.eslintrc', rid=11428, pid=11421, is_file=True, is_filtered=False, date='2018-03-13', sha1='19532afcfb2ca609b9687da0d7dd20cdb4ccf7e4', md5='50f99371ef5e3040c551300e0f83db0d', mime_type=u'text/plain', file_type=u'ASCII text', programming_language='Text only', is_binary=False, is_text=True, is_archive=False, is_media=False, is_source=True, is_script=False)

Running the scan on the test folder / files you provided is successful. 

I hope the above info helps. Please let me know if you need anything else from my end.

**Comment by zoltanblenessygfi** [comment]
FYI - If I do a scan only in final folder node_modules/request/node_modules/qs/test, it runs successfully. I have observed this behavior also before. The issue is not related to a particular file, but it happens when I scan many files at once, using the --ignore switches. It did not see it reproducing if I scan a small number of files or if I do not use --ignore switches.

**Comment by pombredanne** [comment]
@zoltanblenessygfi Thanks! that gfives a clear reproducible path.
I was able to reproduce locally with this https://github.com/poornimask/angular2-form-json-demo/archive/f6414b51f44a762db4c7f8ccfabc39ec71f839eb.zip
and this command:
```
scancode --info --json ossreport/index.json -n 7 --ignore "*.gif" --ignore "*.pdf" --ignore "*.rtf" --ignore "*.idx" --ignore "*.csv" --ignore "**/cvs-rlog-full.txt" --ignore "**/ChangeLog" --ignore "/ossreport" --ignore "**/test" --ignore "**/tests" --ignore "**/doc" --ignore "protractor" .
```

**Comment by pombredanne** [comment]
I am able to reproduce this now with this simpler case and the attached zip:
`scancode --info --json-pp - -n -1 --ignore "*.gif" --max-in-memory=2 web`

That's a great find of yours and a nasty bug alright! We have all we need now to fix this.

[web.zip](https://github.com/nexB/scancode-toolkit/files/1852929/web.zip)

**Comment by zoltanblenessygfi** [comment]
I am happy to hear that you managed to reproduce the issue. Hopefully we will have one less bug in the app soon :)

About when can I expect / try out the fix please?

Thanks!

**Comment by pombredanne** [comment]
@zoltanblenessygfi this happens to be a rather thorny bug in the cache system. @JonoYang is looking at a fix and has pushed failing test for a start!

**Comment by JonoYang** [comment]
@zoltanblenessygfi @pombredanne 

The source of the bug is that the parent of the Resource we are removing from the codebase is not being saved to the disk cache after we remove the Resource. By not updating the disk cache copy of the parent Resource, ScanCode thinks that the removed Resource is still in the codebase and it attempts to get the non-existent Resource, causing a crash. We can solve this by saving the parent Resource after removing the Resource from it's child list.

**Comment by pombredanne** [comment]
@zoltanblenessygfi do you think you could give a try to the fix pushed by @JonoYang in #1013 ? You can fetch it with git or with https://github.com/nexB/scancode-toolkit/archive/1007-max-in-memory-bug.tar.gz
The `src/scancode/resource.py` seems to be the only non-test file updated.

**Comment by zoltanblenessygfi** [comment]
Sorry for the late reply, I barely got some time now to try it out. 

I am trying to run the scan on a folder with many files, it keeps doing work for some time, but then it fails with a new error: 
Setup plugin: output:html-app...
 Setup plugin: pre_scan:ignore...
 Setup plugin: scan:licenses...
Collect file inventory...
Run pre-scans...
 Run pre-scan: ignore...
ERROR: failed to run pre-scan plugin: ignore:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 801, in run_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scancode/plugin_ignore.py", line 74, in process_codebase
    remove_resource(resource)
  File "/usr/local/lib/python2.7/dist-packages/scancode/resource.py", line 599, in remove_resource
    parent.children_rids.remove(resource.rid)
ValueError: list.remove(x): x not in list

I am not sure if this is related to the fix or we are seeing some other issue here which was not seen so far, because the scan actually crashed before.

**Comment by JonoYang** [comment]
@zoltanblenessygfi 

Could you provide the ScanCode command you run and an example of the codebase you run ScanCode on that resulted in the error?

Also, does running the test from here (https://github.com/nexB/scancode-toolkit/issues/1007#issuecomment-376582785) result in an error?

**Comment by zoltanblenessygfi** [comment]
@JonoYang 
I am using the same command as before: sudo scancode --license --license-diag --output-html-app ossreport/index.html --timeout 7200 -n 10 . --ignore ".gif" --ignore ".pdf" --ignore ".rtf" --ignore ".idx" --ignore "*.csv" --ignore "/cvs-rlog-full.txt" --ignore "/ChangeLog" --ignore "/ossreport" --ignore "/test" --ignore "/tests" --ignore "**/doc" --ignore "protractor" --verbose

Executing this command on the test archive you provided before also results in the very same error as scanning my own codebase. All I am doing there is to create the empty folder ossreport so that the command does not fail. 

Please note that I have applied your previous patch simply by taking the modified resource,py file and overwrite it on the original location, which in my case is /usr/local/lib/python2.7/dist-packages/scancode.

**Comment by JonoYang** [comment]
@zoltanblenessygfi 

I think the culprit of the problem is the ignore plugin. I have changed the logic so the ignore plugin is more explicit in what it removes. Please give the new change a try and see if the error still occurs and if the plugin is correctly ignoring the proper files: https://github.com/nexB/scancode-toolkit/archive/1007-resource-removal-error.zip

**Comment by zoltanblenessygfi** [comment]
@JonoYang 

I didn't reproduce the previous issue so far, so it seems the new fix is working. 

When can I expect this to be included in a release? Since I am planning to use it on a production environment ...

Thanks!

**Comment by JonoYang** [comment]
@zoltanblenessygfi 

This fix is now in the develop branch. We are waiting for some more changes to come in before we make a new release of ScanCode, but I think it should be out soon.

**Comment by zoltanblenessygfi** [comment]
This is great, thank you!
