### ISSUE TITLE
Failure with a division by zero

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1017]
See https://ci.appveyor.com/project/nexB/scancode-toolkit/build/job/76oibjmlrmqon3h5#L553

@JonoYang this was introduced after merging your latest code.

**Comment by JonoYang** [comment]
```
       scan_time = codebase.timings.get('scan', 0.)

       ...

       if scan_size_count:
>           scan_size_speed = format_size(scan_size_count / scan_time)
E           ZeroDivisionError: float division by zero
```
It seems like `scan` isn't being added to `codebase.timings`, so `scan_time` defaults to `0`, or the `scan` is actually zero. In both cases, we divide by zero. I am not able to reproduce this on Ubuntu or on a Windows 10 VM.

**Comment by pombredanne** [comment]
thx! It could very much be that we were not reaching this before and that the bug was masked. I cannot reproduce either on my laptop. But the Ci fails consistently

**Comment by JonoYang** [comment]
I put an assertion on `scan_time` to see if it is `0`. `scan_time` is `0`, so we pass the assertion, and then attempt to divide by zero later on.  This only happens on Appveyor. The Travis CI build fails the assertion at this point on the same test because `scan_time` is a nonzero number. I'm not sure why Appveyor acts differently with regards to `scan_time`.

```
        scan_time = codebase.timings.get('scan', 0.)
        if TRACE:
            logger_debug('######## scan_time ########', scan_time)
            assert scan_time == 0
    
        scan_files_count = codebase.summary.get('scan:files_count', 0)
    
        if scan_time > 0:
            scan_file_speed = round(float(scan_files_count) / scan_time , 2)
        else:
            scan_file_speed = 0
    
        scan_size_count = codebase.summary.get('scan:size_count', 0)
    
        if scan_size_count:
>           scan_size_speed = format_size(scan_size_count / scan_time)
E           ZeroDivisionError: float division by zero
```

**Comment by pombredanne** [comment]
ah, this may because something like the time precision on Windows? 
One thing you could do as a cheat?
`scan_time = codebase.timings.get('scan', 0.0000001)`

Or test if the time is 0 and the the speed would be zero.

**Comment by JonoYang** [comment]
I'm trying out changing the default value of `scan_time` from `0` to `0.0000001` to see what happens, though I favor testing if the `scan_time` is `0`, then the `scan_size_speed` is `0` as a fix.

**Comment by JonoYang** [comment]
Setting the default value of `scan_time` to `0.0000001` still results in a `ZeroDivisionError` being raised while the test in Appveyor.

```
        scan_time = codebase.timings.get('scan', 0.0000001)

        ...

        scan_size_count = codebase.summary.get('scan:size_count', 0)
    
        if scan_size_count:
>           scan_size_speed = format_size(scan_size_count / scan_time)
E           ZeroDivisionError: float division by zero
```

I will push a fix that checks that if the time is `0`, then the `scan_size_speed` is `0`.

**Comment by pombredanne** [comment]
We still need a test if possible for this weird corner case.

**Comment by JonoYang** [comment]
@pombredanne I am thinking of testing for this case by creating a Codebase, setting the scan time to be 0, and then running `display_summary()` from `cli.py` on it. Where should this test be located? I am leaning towards putting it in `test_resource.py`, though I am not sure since we are testing the functionality of `display_summary()` and not the Codebase itself.

**Comment by pombredanne** [comment]
This has been fixed in develop

**Comment by pombredanne** [comment]
I am doing some cleanup and review as a prep for the 3.0 release... and since this is fixed in develop, I am closing this!
