### ISSUE TITLE
Output from older ScanCode versions  does not play nicely with VirtualCodebase

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#1028]
In a DeltaCode test of VirtualCodebase, using a scan generated with ScanCode `2.2.1.post73.a9083191a` results in a series of KeyErrors, e.g.,
```
        # Resource list is assumed to be in top-down order
        for res in resources:
            name, path, is_file, file_data = res_data(res)
            parent_path = parent_directory(path).rstrip('/')
>           parent = parent_by_path[parent_path]
E           KeyError: u'1_file_moved_new'

lib\site-packages\scancode\resource.py:1154: KeyError
```

**Comment by pombredanne** [comment]
@johnmhoran Thanks but I am not sure we would ever support scans from a 2.2.1 version with this. 
Also may be this is a ticket that would best live in DeltaCode than here?

**Comment by pombredanne** [comment]
I am closing this as wontfix. We will not support older 2.2.1x scan formats. Feel free to reopen if you think this deserves to be fixed
