### ISSUE TITLE
Document how to use the License Policy feature and plug-in

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1035]
Related issues #214 and #880 are Closed, indicating that scancode-toolkit now has a license policy feature, but there is no documentation about it at 
https://github.com/nexB/scancode-toolkit/wiki 

There is also no mention of how to use the feature in: 
`./scancode --help`

**Comment by DennisClark** [comment]
Perhaps the best place for examples, etc. would be the wiki page at
https://github.com/nexB/scancode-toolkit/wiki

**Comment by majurg** [comment]
Policy Plugin Documentation can be found here: https://github.com/nexB/scancode-toolkit/wiki/License-Policy-Plugin

I will go ahead and close this ticket for now. Edits and additions can be made directly on the wiki page itself.
