### ISSUE TITLE
Find actual URL for crypto-keys-redistribution license 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1038]
I think this is from http://git.savannah.gnu.org/cgit/dmidecode.git/tree/dmidecode.c?id=ee07a1b4249560d620d05194eb8ff61b40d3ce23#n21 and first showed up there circa 2008.

**Comment by DennisClark** [comment]
@pombredanne   I definitely can use http://git.savannah.gnu.org/cgit/dmidecode.git/tree/dmidecode.c?id=ee07a1b4249560d620d05194eb8ff61b40d3ce23    (slightly adjusted from your url to position at the top of the file) to document an example of the license.  Thanks, problem solved.

**Comment by pombredanne** [comment]
We have a URL... closing
