### ISSUE TITLE
Add license detection rule for "common cure rights commitment"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1039]
The exact text or text variants are TBD. 
@richardfontana if you have some pointers of usage in the wild (beyond the actual press releases and web announcements) and the actual reference text(s) that would be quite useful.

**Comment by pombredanne** [comment]
Some pointers:
- https://www.redhat.com/en/about/press-releases/technology-industry-leaders-join-forces-increase-predictability-open-source-licensing
- https://www.zdnet.com/article/big-four-linux-tech-firms-shift-open-source-licensing-policies/
- https://www.fsf.org/blogs/licensing/red-hat-leads-coalition-supporting-key-part-of-principles-of-community-oriented-gpl-enforcement

**Comment by richardfontana** [comment]
@pombredanne belated reply: Here are a couple of usages in project repositories:
https://github.com/wildfly/wildfly/blob/master/COMMITMENT
http://git.gluster.org/cgit/glusterfs.git/tree/COMMITMENT

**Comment by pombredanne** [comment]
@richardfontana See also this https://github.com/gplcc/gplcc ... I guess this is mostly the same but there is also an individual "variant" ?

**Comment by pombredanne** [comment]
So what would be the license key: ccrc-1.0  or common-cure-1.0 ?

**Comment by pombredanne** [comment]
This was first added as a `ccrc-1.0` and later updated to `gplcc-1.0` as parts of #1242 to sync with SPDX.
@richardfontana Closing this now... this is available in the latest develop for now.
Thanks!
