### ISSUE TITLE
Define approach to handle exception license records

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1044]
Historically we have handled exceptions as combo license records such as here https://github.com/nexB/scancode-toolkit/blob/fix-synclic/src/licensedcode/data/licenses/gpl-2.0-autoconf.LICENSE and https://github.com/nexB/scancode-toolkit/blob/fix-synclic/src/licensedcode/data/licenses/gpl-2.0-autoconf.yml

The license text contains the combined notice for the GPL and the exception.

Going forward to report proper exception for #74 wee need to decide how to handle these "legacy" license records. There are a few ways:

1. **Keep** the current keys and **update** them to only reference the exception text instead. This has the benefit of simplicity BUT may create havoc as some user may reference these licenses and the text and nature of these licenses will be no longer the same. I find this dangerous.

2. **Create new license keys** for the exception text only. Create new or update existing rules to detect either the exception alone or the expression when the exception is used in combo with a license notice. 
And deprecate the legacy records, but keep them around. I prefer this as this does not introduce any confusion about the meaning of an exception.

This is only a data issue and this needs to be resolved before finalizing support for license exceptions for #74 

@DennisClark I would appreciate your input there.

**Comment by DennisClark** [comment]
@pombredanne   Option 2 makes more sense as an approach (but is, of course, a non-trivial amount of work).

**Comment by DennisClark** [comment]
@pombredanne  I would also agree that it would be much better to reference two entities in a license expression when an exception is involved, that is: 
`{{license}} WITH {{exception}}` 
would be much better, and certainly more compliant with community standards, than
`{{a combined license+exception}}` 
arguing that we really do need to get to exceptions that are just the exception text and not combined with the original license text or license notice, when possible, noting that some exceptions are written and used in such a way that license and exception are stuck together.

**Comment by pombredanne** [comment]
@DennisClark Thanks. I think this is clear. I am implementing this as part of #74 then.
