### ISSUE TITLE
"license_url" appears in class Options, it should be removed

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1046]
We have "license_url" removed in the Packagedcode model, but in the model package, it appears in class Options, we should remove it.
![license_url](https://user-images.githubusercontent.com/13014965/39355248-40dbe300-4a3f-11e8-8051-ff6baff13468.png)

**Comment by pombredanne** [comment]
@linexb Thanks! that's a bug alright.

**Comment by pombredanne** [comment]
This has been fixed for quite a while now. Closing
