### ISSUE TITLE
Incorrect license: dual GPLv2/MIT detected as GPLv1, GPLv2, and MIT

### ISSUE THREAD

**Issue by liftM** [nexB/scancode-toolkit#1058]
Files in https://github.com/faisalman/ua-parser-js/commit/34f934fa551055fd5163dddc4c92bb5437848927 are being picked up as GPLv1 and GPLv2 instead of the correct GPLv2 OR MIT dual-license. As a concrete example, https://github.com/faisalman/ua-parser-js/blob/master/dist/ua-parser.min.js is picked up as only GPLv2.

**Comment by pombredanne** [comment]
@ilikebits Thank you for the report! It should be an easy fix with a few extra detection rules.

**Comment by pombredanne** [comment]
This has long been fixed. Thank you for the reporg!
