### ISSUE TITLE
Not detected COPYING file for bitstream font

### ISSUE THREAD

**Issue by pkunz** [nexB/scancode-toolkit#1063]
This file is not well detected 
https://www.x.org/releases/individual/font/font-bitstream-100dpi-1.0.3.tar.bz2/COPYING

**Comment by pombredanne** [comment]
Thanks! this is indeed not detected super well
It looks like a combo of `historical` and  `nonexclusive` with extra warranty disclaimer

**Comment by pombredanne** [comment]
I add rules and this is now detected as 
```
      "license_expressions": [
        "free-unknown",
        "historical",
        "nonexclusive",
        "free-unknown"
```
And available in develop. Closing.
