### ISSUE TITLE
OSL 3.0 recognized as BSD 3 clause

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1067]
https://raw.githubusercontent.com/engineyard/magento-ce-1.9/master/app/code/core/Mage/Tax/Model/Sales/Total/Quote/Nominal/Tax.php

is recognized as follows:

{
  "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
  "scancode_version": "2.9.2.post6.603f3c460",
  "scancode_options": {
    "input": "/tmp/test/Tax.php",
    "--json-pp": "<stdout>",
    "--license": true
  },
  "files_count": 1,
  "files": [
    {
      "path": "Tax.php",
      "type": "file",
      "licenses": [
        {
          "key": "bsd-new",
          "score": 76.92,
          "short_name": "BSD-3-Clause",
          "category": "Permissive",
          "owner": "Regents of the University of California",
          "homepage_url": "http://www.opensource.org/licenses/BSD-3-Clause",
          "text_url": "http://www.opensource.org/licenses/BSD-3-Clause",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:bsd-new",
          "spdx_license_key": "BSD-3-Clause",
          "spdx_url": "https://spdx.org/licenses/BSD-3-Clause",
          "start_line": 8,
          "end_line": 13,
          "matched_rule": {
            "identifier": "bsd-new_128.RULE",
            "license_expression": "bsd-new",
            "licenses": [
              "bsd-new"
            ]
          }
        },
        {
          "key": "osl-3.0",
          "score": 40.0,
          "short_name": "OSL 3.0",
          "category": "Copyleft",
          "owner": "Lawrence Rosen",
          "homepage_url": "http://www.opensource.org/licenses/osl-3.0.php",
          "text_url": "http://www.opensource.org/licenses/osl-3.0.php",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:osl-3.0",
          "spdx_license_key": "OSL-3.0",
          "spdx_url": "https://spdx.org/licenses/OSL-3.0",
          "start_line": 10,
          "end_line": 10,
          "matched_rule": {
            "identifier": "osl-3.0_2.RULE",
            "license_expression": "osl-3.0",
            "licenses": [
              "osl-3.0"
            ]
          }
        },
        {
          "key": "osl-3.0",
          "score": 40.0,
          "short_name": "OSL 3.0",
          "category": "Copyleft",
          "owner": "Lawrence Rosen",
          "homepage_url": "http://www.opensource.org/licenses/osl-3.0.php",
          "text_url": "http://www.opensource.org/licenses/osl-3.0.php",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:osl-3.0",
          "spdx_license_key": "OSL-3.0",
          "spdx_url": "https://spdx.org/licenses/OSL-3.0",
          "start_line": 24,
          "end_line": 24,
          "matched_rule": {
            "identifier": "osl-3.0_2.RULE",
            "license_expression": "osl-3.0",
            "licenses": [
              "osl-3.0"
            ]
          }
        }
      ],
      "license_expressions": [],
      "scan_errors": []
    }
  ]
}

As you can see BSD 3 gets a higher score than OSL 3, but there is no BSD 3 clause in that file, just OSL 3.

**Comment by pombredanne** [comment]
Closing now since this has been merged in develop.
Thanks again for the report
