### ISSUE TITLE
false positive: Philippe De Muyter License for mongodb.exe

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1068]
When scanning a binary copy of MongoDB for MS Windows (mongodb.exe) and one of the hits ScanCode came up with is this one:

https://enterprise.dejacode.com/licenses/public/philippe-de-muyter/

although there is no mention of either his name or e-mail address in the binary. I guess the "NO WARRANTY" thing in there triggers it, as these also occur in the AGPL-3 with OpenSSL exception that is included.

**Comment by armijnhemel** [comment]
{
          "key": "philippe-de-muyter",
          "score": 100.0,
          "short_name": "Philippe De Muyter License",
          "category": "Permissive",
          "owner": "Unspecified",
          "homepage_url": "",
          "text_url": "",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:philippe-de-muyter",
          "spdx_license_key": "",
          "spdx_url": "",
          "start_line": 184856,
          "end_line": 184856,
          "matched_rule": {
            "identifier": "philippe-de-muyter.LICENSE",
            "license_expression": "philippe-de-muyter",
            "licenses": [
              "philippe-de-muyter"
            ],
            "matcher": "2-aho",
            "rule_length": 29,
            "matched_length": 29,
            "match_coverage": 100.0,
            "rule_relevance": 100
          },
          "matched_text": "This program is distributed in the hope that it will be useful,\n * but WITHOUT ANY WARRANTY; without even the implied warranty of\n * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE"

**Comment by armijnhemel** [comment]
{
          "key": "philippe-de-muyter",
          "score": 100.0,
          "short_name": "Philippe De Muyter License",
          "category": "Permissive",
          "owner": "Unspecified",
          "homepage_url": "",
          "text_url": "",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:philippe-de-muyter",
          "spdx_license_key": "",
          "spdx_url": "",
          "start_line": 184959,
          "end_line": 184959,
          "matched_rule": {
            "identifier": "philippe-de-muyter.LICENSE",
            "license_expression": "philippe-de-muyter",
            "licenses": [
              "philippe-de-muyter"
            ],
            "matcher": "2-aho",
            "rule_length": 29,
            "matched_length": 29,
            "match_coverage": 100.0,
            "rule_relevance": 100
          },
          "matched_text": "This program is distributed in the hope that it will be useful,\n*    but WITHOUT ANY WARRANTY; without even the implied warranty of\n*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE"
        },

**Comment by pombredanne** [comment]
@armijnhemel Thanks for this. This has been fixed with new rules with the commit above, for now in a branch
