### ISSUE TITLE
false positve: jQuery recognized as GPL-1.0 or later

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1069]
http://code.jquery.com/jquery-1.9.1.js is MIT licensed, yet ScanCode says it is GPL-1.0 or later as well:

        {
          "key": "gpl-1.0-plus",
          "score": 15.0,
          "short_name": "GPL 1.0 or later",
          "category": "Copyleft",
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
          "text_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-1.0-plus",
          "spdx_license_key": "GPL-1.0-or-later",
          "spdx_url": "https://spdx.org/licenses/GPL-1.0-or-later",
          "start_line": 10,
          "end_line": 10,
          "matched_rule": {
            "identifier": "mit_or_gpl_5.RULE",
            "license_expression": "mit OR gpl-1.0-plus",
            "licenses": [
              "mit",
              "gpl-1.0-plus"
            ],
            "matcher": "2-aho",
            "rule_length": 3,
            "matched_length": 3,
            "match_coverage": 100.0,
            "rule_relevance": 15
          },
          "matched_text": "jquery.org/license"
        },

**Comment by DennisClark** [comment]
For what it's worth, I noticed that the file 
`/jquery-1.9.1/speed/jquery-basis.js` 
contains the text 
```
 * jQuery JavaScript Library v1.4.2
 * http://jquery.com/
 *
 * Copyright 2010, John Resig
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 * Copyright 2010, The Dojo Foundation
 * Released under the MIT, BSD, and GPL Licenses.
 *
``` 
and perhaps that accounts for the additional licenses reported by ScanCode, even though the overall project license is MIT for this version of jQuery.

**Comment by armijnhemel** [comment]
The culprit is rules/mit_or_gpl_5.RULE

**Comment by armijnhemel** [comment]
To clarify, that rule has this as its contents:

jquery.org/license

which pretty much matches with almost every version of jQuery. @pombredanne I would very strongly suggest removing this particular rule :-)

**Comment by pombredanne** [comment]
@armijnhemel thanks. FWIW, I am making rules a bit more selective, but there are cases where a bare `jquery.org/license` is all we have a license information.
I am making these URL-related rules to be  MIT (and no longer MIT or GPL)  and create a few large rules to deal with this better

**Comment by pombredanne** [comment]
This has been long fixed in develop.

**Comment by pombredanne** [comment]
And available also in the latest released tags
