### ISSUE TITLE
corrupt license cache after running scancode -l

### ISSUE THREAD

**Issue by selmf** [nexB/scancode-toolkit#1070]
Operating system: Arch Linux x64
Python version: Python 3.6.5,  2.7.15
Scancode version: 2.9.2 and latest checkout as of today

1) Run scancode -l on a code base.
2) Run scancode -l a second time on the same codebase

Expected behavior:

The second scan should run just as well as the first run.

Experienced behavior:

Scan fails with the following error message:

``Setup plugins...
ERROR: failed to setup plugin: scan:licenses:
Traceback (most recent call last):
  File "/home/herr_k/builds/scancode-toolkit/src/scancode/cli.py", line 568, in scancode
    plugin.setup(**kwargs)
  File "/home/herr_k/builds/scancode-toolkit/src/scancode/plugin_license.py", line 127, in setup
    return_value=False)
  File "/home/herr_k/builds/scancode-toolkit/src/licensedcode/cache.py", line 64, in get_index
    _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)
  File "/home/herr_k/builds/scancode-toolkit/src/licensedcode/cache.py", line 175, in get_cached_index
    return load_index(cache_file)
  File "/home/herr_k/builds/scancode-toolkit/src/licensedcode/cache.py", line 229, in load_index
    return LicenseIndex.loads(ifc.read())
  File "/home/herr_k/builds/scancode-toolkit/src/licensedcode/index.py", line 782, in loads
    idx = cPickle.loads(saved)
ValueError: binary data truncated (2)
``

Deleting ~/.cache/scancode-tk temporarily solves this issue until the cache is regenerated and it fails again.

Please note that Arch Linux is one of the few distros shipping Python3 by default, i.e. /usr/bin/python points to Python3 instead of Python2.

**Comment by pombredanne** [comment]
@selmf Thank you for the report. This definitely should not happen.

Do you mind to try the things below and report back here?

1. cd to your scancode install directory `/home/herr_k/builds/scancode-toolkit/`
2. run `source bin/actiavte`
3. run `python` and paste the results here.


Note that it is possible that this is hitting this pending bug  https://github.com/WojciechMula/pyahocorasick/issues/50 in pyahocorasick

Another thing to test specifically for this would be this:

1. cd to your scancode install directory `/home/herr_k/builds/scancode-toolkit/`
2. run `source bin/actiavte`
3. run `pip install --upgrade pyahocorasick`
4. run `rm -rf  ~/.cache/scancode-tk`
5. try again running two license scans

I would like to see if the latest pyahocorasick 1.1.8 fixes this or not.

**Comment by selmf** [comment]
Thanks for the fast reply!

After running source bin/activate running python results in a Python2 shell, version 2.7.15

Updating pyahocorasick to 1.18 and scanning twice showed no errors, so it seems the bug is indeed fixed upstream.

**Comment by pombredanne** [comment]
@WojciechMula based on @selmf tests it looks like 1.1.8 is fixing the bug https://github.com/WojciechMula/pyahocorasick/issues/50 so we likely can close this. 

@selmf I will be updating to use the latest pyahocorasick 1.18 and that should take care of this hopefully (I need to spin binary wheel builds for macOS, Windows and Linux and ensure the tests all pass everywhere)

Thank you++ for taking the time to tests things out and helping fix this report! :bowing_man:

**Comment by selmf** [comment]
You're very much welcome.

Btw, if you'd like to prevent errors like this in the future, you could always wrap the call to the cache loader in a try except block and recreate the cache upon error.

**Comment by pombredanne** [comment]
@selmf 

re: 

> Btw, if you'd like to prevent errors like this in the future, you could always wrap the call to the cache loader in a try except block and recreate the cache upon error.

I am not sure this would work out well ass this would hide the fact that there is an underlying bug or error which could be really problematic.

**Comment by selmf** [comment]
@pombredanne 

In that case you can always display what went wrong and what to do in the exception handler and just re-raise the exception after that so that the user gets the 'full crash experience' ;)

It could look roughly like this:

`try:
    load_cache
except cache_error:
    print "Cache is corrupt. Please delete the cache directory and rerun. If the problem persists please report a bug"
    raise`

**Comment by selmf** [comment]
Hmmm … sure, why not. I'll have to take a closer look at the actual source though so that could take me a few days.

**Comment by jeremiah** [comment]
Hmm, I think I'm bit by this bug too. I'll try the workaround to see.

**Comment by jeremiah** [comment]
I did the update with pip and things worked. But I was using the develop branch from the pre-release v2.9.2. Perhaps the license cache fix hasn't made it into this branch?

**Comment by pombredanne** [comment]
@selmf @jeremiah this is all fixed and merged in develop and available in the latest tags (v2.9.7 and up) Thank you for the report and contributions!. Closing this now
