### ISSUE TITLE
folders are treated as regular files in the scan output

### ISSUE THREAD

**Issue by mhow2** [nexB/scancode-toolkit#1081]
I'm using version 2.2.1

In the sample JSON output below, it seems results are returned even if the scanned path is a folder. If this is expected, how are we supposed to distinguish a folder from a file when parsing the scancode's JSON output ?

```
    {
      "path": "sympa/src/lib/Sympa",
      "scan_errors": [],
      "licenses": [],
      "copyrights": [],
      "packages": []
    },
```

**Comment by pombredanne** [comment]
@mhow2 this has been resolved in the `develop` branch: there is now a `type` attribute:

```
    {
      "path": "samples/zlib/iostream2",
      "type": "directory",
      "emails": [],
      "scan_errors": []
    },
    {
      "path": "samples/zlib/iostream2/zstream.h",
      "type": "file",
      "emails": [],
      "scan_errors": []
    },
``` 


I suggest you use either the `develop` branch or the latest `2.9.x` pre-release as we are cutting a new release pretty soon.

**Comment by mhow2** [comment]
Thanks. I searched through the existing issues before opening this one but haven't found anything related.
