### ISSUE TITLE
Incorrect copyright detected in libreoffice-langpack

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#109]
OS: Windows 8.1 (64-bit)
I've updated my scancode to the latest version available.
`RPM file`: `libreoffice-langpack-fr-4.0.4.2-9.el6.x86_64.rpm`
`file-path` : `libreoffice-langpack-fr-4.0.4.2-9.el6.x86_64.rpm/usr/lib64/libreoffice/help/fr/smath.idxl/_0.cfs`
file : `http://bay.uchicago.edu/centos-vault/6.4/cr/x86_64/Packages/libreoffice-langpack-fr-4.0.4.2-9.el6.x86_64.rpm`

when the above file is scanned for copyrights the outputs are as follows: 
`html-app` : 
![image](https://cloud.githubusercontent.com/assets/11914280/10795547/8cc6b25c-7d57-11e5-9a2d-4dccdec988a6.png)
`JSON` :

```
{
  "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.", 
  "scancode_version": "1.3.8", 
  "resource_count": 1, 
  "results": [
    {
      "location": "C:***********/_0.cfs", 
      "copyrights": [
        {
          "statements": [
            "(c) \u0002\u0001 \u0005\u0001e\u0002\u0001\u0002\u0002\u0006\u0001s\u0002\u0001\u0002\u0002\u0005\u0001s\u0002\u0001\u0002\u0002\u0002\u0003oup\u0002\u0001\u0002\u0002\u0005\u0001e\u0002/\u0003\u0003P\u0006 .serveur.com\u0002\u0001XO\u0001\u0006\u0004ment\u0002\u0012\u0002\u0001"
          ], 
          "start_line": 16157, 
          "end_line": 16162
        }
      ]
    }
  ]
}
```

The above issue might be due to writing the text `(c) \u0002\u0001 \u0005\u0001e\u0002\u0001\u0002\u0002\u0006\u0001s\u0002\u0001\u0002\u0002\u0005\u0001s\u0002\u0001\u0002\u0002\u0002\u0003oup\u0002\u0001\u0002\u0002\u0005\u0001e\u0002/\u0003\u0003P\u0006 .serveur.com\u0002\u0001XO\u0001\u0006\u0004ment\u0002\u0012\u0002\u0001` onto a HTML page.

**Comment by pombredanne** [comment]
This sounds like a unicode to string related issue on the one hand and the fact that this copyright should not be detected at all anyway.

**Comment by pombredanne** [comment]
It looks like this has been fixed in develop.
