### ISSUE TITLE
copyright has extra letters added to the beginning

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#110]
OS: Windows 8.1 (64-bit)
I've updated my `scancode` to the latest version available.
RPM file: `libreoffice-langpack-zu-4.0.4.2-9.el6.x86_64.rpm`
file-path: `libreoffice-langpack-zu-4.0.4.2-9.el6.x86_64.rpm/usr/lib64/libreoffice/program/resource/cuizu.res`
download URL: `http://bay.uchicago.edu/centos-vault/6.4/cr/x86_64/Packages/libreoffice-langpack-zu-4.0.4.2-9.el6.x86_64.rpm`

when the above file is scanned for copyrights the output is : 

```
Path                         What   Start Line  End Line        Info
C:/***********/cuizu.res    Copyright   385 390     ZCopyright 2000 - 2013 LibreOffice contributors
```

component 2 : 
`RPM`: `qt-doc-4.6.2-28.el6_5.noarch.rpm`
`download URL` : `http://mirror.centos.org/centos/6/os/x86_64/Packages/qt-doc-4.6.2-28.el6_5.noarch.rpm`
`file-path` : `qt-doc-4.6.2-28.el6_5.noarch.rpm/usr/share/doc/qt4/html/qqueue.html`
output when the above file is scanned for copyrights: 

```
Path                            What    Start Line  End Line        Info
C:/*********/qqueue.html    Copyright   83  89      left' Copyright (c) 2010 Nokia Corporation
```

`The line numbers doesn't seem to match in both the cases`.

**Comment by pombredanne** [comment]
This has been fixed in #790
Thank you!
