### ISSUE TITLE
Option to only scan specific types of files

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1104]
It would be nice to have an option that is the negation of the `--ignore` option. For the sake of example, this option could be called `--only`, where files matching the pattern following the `only` option is scanned and other files that do not match the pattern is ignored.

**Comment by pombredanne** [comment]
@chiragmp FYI this may be a feature you want

**Comment by chiragmp** [comment]
Yes, this would be great!

**Comment by pombredanne** [comment]
@JonoYang  there is a new option in the `develop` branch called  include that works this way `--include="*JGroup*" --ignore "*.S"` ... and it is also possible to enter multiple paths arguments .
Is this what you meant here?

**Comment by JonoYang** [comment]
@pombredanne The new `--include` option is what I was looking for here. Thanks!
