### ISSUE TITLE
Suggest making more use of "author" statements in scan results

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1107]
A recent scan of a package at 
https://registry.npmjs.org/@invisionag/eslint-config-ivx/-/eslint-config-ivx-0.0.2.tgz 
did not find any copyright information, and it is true that the package does not contain any "Copyright" statements, but it does contain the following line in the file package.json:

`"author": "Alexander Plavinski <alexander.plavinski@invision.de>"`

so there is some indication of package ownership that is the closest we are going to get.  It would be very useful for scancode to return that as part of a copyright holder summary or even as a copyright.

**Comment by mjherzog** [comment]
Why not promote author as it is to be a stronger clue (than say URL or email) rather than mixing with copyright which it may or may not represent.

**Comment by armijnhemel** [comment]
Indeed, authorship is not indicative of copyright ownership. I would be careful with mixing the two.

**Comment by DennisClark** [comment]
Suggestion withdrawn.

**Comment by pombredanne** [comment]
@DennisClark I still think this is a valid point of yours wrt to including authors in scan summaries for #377

**Comment by pombredanne** [comment]
I reopening for summaries inclusion

**Comment by pombredanne** [comment]
@DennisClark these authors are available in the `--package` scan as a party of role author if present (see below).
beyond this I am not sure we can do much more: we could report a summary of package parties? but that would be rather hairy quickly ...
```....
  "files": [
    {
      "path": "package.json",
      "type": "file",
      "packages": [
        {
          "type": "npm",
          "namespace": "@invisionag",
          "name": "eslint-config-ivx",
          "version": "0.0.2",
          "qualifiers": null,
          "subpath": null,
          "primary_language": "JavaScript",
          "code_type": null,
          "description": null,
          "size": null,
          "release_date": null,
          "parties": [
            {
              "type": "person",
              "role": "author",
              "name": "Alexander Plavinski",
              "email": "alexander.plavinski@invision.de",
              "url": null
            }
          ],
.....
``

**Comment by DennisClark** [comment]
detection of authors confirmed.  closing.
