### ISSUE TITLE
Deprecate apache_1.RULE and apache_2.RULE

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#1108]
These license rules are both based on an ASF attribution notice, but these are not license notices and reporting as a license is misleading. They are strong Author clues, but not clear license clues especially with apache_2.RULE referencing "other organizations".
There may be some new way to use the information that most software directly from ASF is licensed under Apache 2.0 or 1.1, and similar patterns for Eclipse (EPL 1.0 or 2.0), Spring (Apache 2.0) or even nexB (Apache 2.0), but that would be  a different feature.

**Comment by pombredanne** [comment]
Sorry for the late reply. There are a few other rules that related.
They still are a string clue that this contains code that is either under an Apache 1.1 or Apache 2.0 license.
So I would like to keep these but ensure that:
1. a low score will be returned
2. they will be treated as a "weak" license reference
3. they will return an expression of "Apache 1.1 or Apache 2.0"

**Comment by pombredanne** [comment]
This has been fixed in develop. Thank for the report!
