### ISSUE TITLE
Language "YAML" returned by a scan

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1109]
A recent scan of https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip  provided the following list of languages: 
```HTML (158)
C (86)
JavaScript (59)
Objective-C (19)
CMake (9)
CSS (5)
JavaScript+Lasso (2)
YAML (2)
Genshi (2)
CSS+Lasso (1)
```

`YAML` is certainly a file type with distinctive characteristics, but I don't think it is a programming language.

**Comment by pombredanne** [comment]
Great catch!
This is indeed buggy. We report a file as being in a "programming language" pretty liberally and we should make a clear distinction of real languages (i.e. C, C++) vs. file formats used in programming (YAML, XML, possibly HTML)...

**Comment by pombredanne** [comment]
We are now reporting this with the latest develop:
```
  "summary": {
    "programming_language": [
      {
        "value": "HTML",
        "count": 158
      },
      {
        "value": "C++",
        "count": 86
      },
      {
        "value": "JavaScript",
        "count": 59
      },
      {
        "value": null,
        "count": 39
      },
      {
        "value": "Objective-C",
        "count": 20
      },
      {
        "value": "CMake",
        "count": 14
      },
      {
        "value": "CSS",
        "count": 5
      },
      {
        "value": "ActionScript 3",
        "count": 2
      },
      {
        "value": "TypeScript",
        "count": 1
      }
    ]
  },
```

I think HTML should not be there. @DennisClark do you agree?

**Comment by pombredanne** [comment]
Now HTML should NOT be reported as a language.

**Comment by DennisClark** [comment]
Working much better now.  Closing.
