### ISSUE TITLE
False positive for license from default ansible role

### ISSUE THREAD

**Issue by lbrigmanArris** [nexB/scancode-toolkit#1111]
The scancode tool is falsely flagging the role/meta/main.yml as having multiple licenses.
This is generated boilerplate code from the ansible-galaxy tool.
Here is the section file that is causing the false positive:
```
##########################
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
##############################
```

The boilerplate code is incomplete and does need to be examined

**Comment by pombredanne** [comment]
@lbrigmanArris Thank you for the report. The galaxy template is there https://github.com/ansible/ansible/blob/1e08e9a55f3207515e32299c99fd8cd22dc6a833/lib/ansible/galaxy/data/default/meta/main.yml.j2 
The resolution will consist in declaring this as not really a license: I have a fix that I will push shortly

**Comment by pombredanne** [comment]
@lbrigmanArris I pushed a fix in this branch https://github.com/nexB/scancode-toolkit/tree/new-and-improved-licenses if you want to test this: It will be merged in develop when the CI runs are completed.
Thanks again for this report!

**Comment by pombredanne** [comment]
I am doing some cleanup and review as a prep for the 3.0 release... and since this is fixed in develop, I am closing this!
