### ISSUE TITLE
Distinguish the two Apache 2.0 notices: the regular one and the "licensed to Apache one"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1115]
We have a class of Apache 2.0 notices found in code that is also a form of ownership statement:

```
* Licensed to the Apache Software Foundation (ASF) under one or more 
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to you under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at:
*.......
```
This is more than just a license notice. We should somehow handle this.

These rules have this:
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_12.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_2.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_25_notice.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_33.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_38.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_61.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_maven.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/apache-2.0_maven2.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/cddl-1.0_or_gpl-2.0-classpath_and_apache-2.0-glassfish_2.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/cddl-1.1_or_gpl-2.0-classpath_and_apache-2.0-glassfish_2.RULE
- https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/data/rules/public-domain_and_apache.RULE

**Comment by mjherzog** [comment]
To me this is a license notice - ASF licenses the code under Apache 2.0. The statement about contributors does not change that point. In general the statement to "See the NOTICE file distributed with
* this work for additional information regarding copyright ownership." is closest to an attribution statement for authors other than ASF.

**Comment by pombredanne** [comment]
ok, thanks. I am closing this then.
