### ISSUE TITLE
Prominent copyright statement not returned (or truncated) by a scan

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1117]
A recent scan of the file at
https://github.com/vuejs/vue/archive/v2.5.16.zip 
returned the following copyright information: 
```
(c) 2014-2018 Evan (8)
Copyright (c) 2013-present, Yuxi (2)
(c) 2014-2017 Evan (1)
(c) 2014 (1)
```
but there is a copyright statement in the LICENSE file for this package 
`Copyright (c) 2013-present, Yuxi (Evan) You` 
that was apparently ignored or truncated, see 
https://github.com/vuejs/vue/blob/v2.5.16/LICENSE 

This was from one of the releases of the "vue" project at https://github.com/vuejs/vue

**Comment by pombredanne** [comment]
This a rather tough one. Do you think this form of copyright statement is frequent?

**Comment by DennisClark** [comment]
Not a material problem.  Closing this issue.
