### ISSUE TITLE
redhat logos license not detected

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#113]
OS : Windows 7 (64-bit)
I've updated my `scancode` to the latest version available.
file :  [COPYING.txt](https://github.com/nexB/scancode-toolkit/files/30267/COPYING.txt)

When i try to run scancode on the above file for licenses there were no results found. I think the license text is similar to that of the license text in this URL - `http://www.sslug.dk/~chlor/rpm3html/pack/redhat-logos.html`
The license name for this license text is not clear in this URL. please check the `license` metadata (`License: Copyright © 1999 Red Hat, Inc.  All rights reserved.`) in the above URL it looks like a `copyright `

**Comment by pombredanne** [comment]
Applied and verified. Thanks.
