### ISSUE TITLE
ScanCode detects gpl-2.0 based on generic warranty disclaimer/liability limitation language

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#1133]
ScanCode has detected the following language in `e2fsprogs-1.44.2/lib/fpopen.c` as `gpl-2.0` with a 58.79 score:
```
 * Copyright Theodore Ts'o, 1996-1999.
 *
 * Permission to use this file is granted for any purposes, as long as
 * this copyright statement is kept intact and the author is not held
 * liable for any damages resulting from the use of this program.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ALL OF
 * WHICH ARE HEREBY DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
 * USE OF THIS SOFTWARE.
 */
```
I've traced the detection to the following [RULE](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/gpl-2.0_507.RULE) by running `scancode -l --license-text --license-diag --json-pp - <path to file>`:
```
. . .
          "matched_rule": {
            "identifier": "gpl-2.0_507.RULE",
            "license_expression": "gpl-2.0",
            "licenses": [
              "gpl-2.0"
            ],
            "matcher": "3-seq",
            "rule_length": 165,
            "matched_length": 97,
            "match_coverage": 58.79,
            "rule_relevance": 100
          },
          "matched_text": "THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED\n * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\n * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, [ALL] [OF]\n * [WHICH] [ARE] [HEREBY] DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE\n * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR\n * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT\n * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR\n * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE\n * USE OF THIS SOFTWARE"
. . .
```
The matched text in the [RULE](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/gpl-2.0_507.RULE) is preceded by an express reference to the GPL 2.0 and followed by an express reference to the GPL (no version mentioned there), which I suppose is the reason for the less-than-perfect score; but I wonder whether this should be an even lower score given the lack of reference to the GPL at all in the file in question.

**Comment by pombredanne** [comment]
@johnmhoran thanks! excellent bug and well documented too. It sounds like Theodore T'so crafted a license using almost but not exactly a BSD disclaimer and some unique MIT-like working on top. Since e2fsprogs is frequent enough that is likely worthy of a new license.... and some license rules cleanup too

As a side note, while researching I found that this https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/robert-hubley.LICENSE seem to be mostly a BSD disclaimer and nothing else. May something else to look into as this `robert-hubley` may not be a proper license after all.

**Comment by pombredanne** [comment]
Fixed in develop
