### ISSUE TITLE
Show summary of licenses for a scan in html-app

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#114]
**Narrative**: I want to quickly see the number and proportion of licenses detected from a scan. This will help me estimate the primary license for a package.
**Context**: A Treemap from D3.js has been visited in the past. We may want to offer several different graphic/chart views from D3.js.
**Acceptance Criteria:** 
        - *Scenario 1:* When a user runs a scan on a codebase, a visual summary of the high level license stats would be displayed in the HTML app.

**Comment by jdaguil** [comment]
Separating the license and copyright summary into two issues: See #120

**Comment by nspsjsu** [comment]
Reviewed

**Comment by jdaguil** [comment]
@nspsjsu Thanks
