### ISSUE TITLE
Add Package URL field to top-level package output

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#1149]
Currently, `scancode-toolkit` returns all the needed details to construct a Package URL when running a scan with the `--package` option. However, a `purl` field is not present for top-level packages. 

This should be added, as all the necessary fields are present and we return `purl` values for package dependencies, so we should keep our top-level packages consistent with these dependencies.

**Comment by pombredanne** [comment]
This has been fixed and merged in develop
