### ISSUE TITLE
Linux copyright not detected: kernel/sound/drivers/ml403-ac97cr.c

### ISSUE THREAD

**Issue by ened** [nexB/scancode-toolkit#115]
Given a input file header like this:

```
/*
 * ALSA driver for Xilinx ML403 AC97 Controller Reference
 *   IP: opb_ac97_controller_ref_v1_00_a (EDK 8.1i)
 *   IP: opb_ac97_controller_ref_v1_00_a (EDK 9.1i)
 *
 *  Copyright (c) by 2007  Joachim Foerster <JOFT@gmx.de>
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
 *
 */
```

Then scancode can only detect the license like this:
![screen shot 2015-11-18 at 17 06 51](https://cloud.githubusercontent.com/assets/269860/11236804/d9d12ed6-8e16-11e5-8a64-2385f8cacd65.png)

And it won't find the correct copy right info "Copyright (c) by 2007  Joachim Foerster <JOFT@gmx.de>".

**Comment by pombredanne** [comment]
Thanks for the report!
If I run the copyright detection in debug mode, I see this parse tree:
```
 (COPY Copyright/COPY)
  (COPY (c)/COPY)
  by/BY
  (NAME3
    (YR-RANGE 2007/YR)
    (NAME2 (NAME Joachim/NNP Foerster/NNP) <JOFT@gmx.de>/EMAIL)))
```

The sequence COPY/COPY/BY/NAME3 is not caught by the grammar all right.  Let me fix this quick

**Comment by pombredanne** [comment]
Just for reference, to run the copyright in debug mode, `export SCANCODE_COPYRIGHT_DEBUG=1` as an env var and the debug logging will be activated (which is rather verbose....)

**Comment by pombredanne** [comment]
@ened you can try the fix by fetching the latest from the develop branch !

**Comment by pombredanne** [comment]
and kudos (with a cringing smille)  to Joachim Foerster for inventing a new form of copyright statement... This is rather rare these days (which is a good thing)...

**Comment by ened** [comment]
Actually, kudos to our lawyer who found this. ;-)

**Comment by pombredanne** [comment]
And note that the second detection of GPL in this file is because of the module macro "MODULE_LICENSE("GPL")"
In a near future, the kernel module module macros will be reported as structured package-like metadata

**Comment by pombredanne** [comment]
Now, it makes me think of something: I could enable a less strict reporting of copyrights (at the rrisk of more false positive) and provide some scoring for these.... Do you think it would make sense? On the other hand, I thrive to make this detection accurate in all cases rather than having a lot of statements to sort out.

**Comment by pombredanne** [comment]
Thanks again for the bug in anycase. Please close it if this works to your liking.
