### ISSUE TITLE
Deprecate html app and corresponding wiki documentation

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#1157]
The wiki documentation still has many references to the html app format and using the html app.  We need to replace the html app documentation with information about AbC Manager.
I assume that the information about custom output including HTML with Jinja2 would still apply.

**Comment by pombredanne** [comment]
Most wiki pages related to html app have been updated. And the CLI help too.

**Comment by majurg** [comment]
#1261 Merged, closing this.
