### ISSUE TITLE
Scancode is limits file scanning to 1000 files

### ISSUE THREAD

**Issue by Sohil** [nexB/scancode-toolkit#1163]
I was trying to use this tool and looks like it limits file scanning to 1000 files. Is this by design ? 

[---#----------------] 1000 Scanned: Contents.json                                      objc[57121]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[57121]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[57124]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[57124]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[57127]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[57127]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[57129]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[57129]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[57150]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[57150]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[57153]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[57153]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by majurg** [comment]
Hello, this is a known bug in MacOS not specific to `scancode-toolkit` (see: https://github.com/ansible/ansible/issues/32499#issuecomment-341578864). 

Try running this command, then re-run your scan:
```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

**Comment by pombredanne** [comment]
@majurg thanks... I wonder if we should include this in core code? in the scancode top level bash script and possibly also in the cli.py ?

**Comment by pombredanne** [comment]
@Sohil did you get to work?

**Comment by Sohil** [comment]
@pombredanne  this worked for me. I was able to run scancode and generate the scan results. Thank you. Will Close the issue. Appreciate your help
