### ISSUE TITLE
Add plugin to collect 'binary_strings'

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1166]
This is to report binary strings as extracted from binary and data files.

**Comment by pombredanne** [comment]
Can you elaborate a bit your use case?
We have internal code today that is used to extract strings from binaries such that license and copyright detection can work on binaries. (See https://github.com/nexB/scancode-toolkit/blob/develop/src/textcode/strings.py and https://github.com/nexB/scancode-toolkit/blob/develop/src/textcode/strings2.py )
This is essentially a specialized version of the binutils strings command. 


I am not sure I can see what is the value of just collecting strings from a binary as-is. binutils `strings` would be the tool to use for this.... 
So please elaborate a  specific use case.

**Comment by chinyeungli** [comment]
One of the user cases is to get binary strings from an elf to perform d2d
analysis, but your point is valid as we can use the Linux strings command
to do the job. I think this ticket can be closed.
