### ISSUE TITLE
eCos-2.0 returns "unknown SPDX"

### ISSUE THREAD

**Issue by bobgob** [nexB/scancode-toolkit#1170]
eCos-2.0 is a deprecated license in SPDX (https://spdx.org/licenses/) but it should still be identified and not return short_name "unknown SPDX", category "Unstated License".  This was done in scancode-toolkit v 2.9.2.

**Comment by pombredanne** [comment]
Thanks! This should be fixed with the commits in the #1172 PR

**Comment by pombredanne** [comment]
@bobgob this is fixed in the develop branch now.

**Comment by pombredanne** [comment]
This has been fixed in develop. Closing
