### ISSUE TITLE
license detection failed

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#118]
OS: windows 7 64 bit
I've updated my `scancode` to the latest version available.
file: [flotr2.min.js.txt](https://github.com/nexB/scancode-toolkit/files/40551/flotr2.min.js.txt)

the above file has license in the line `4` but no license is detected by `scancode`

**Comment by balusarakesh** [comment]
splitting into multiple tickets

**Comment by balusarakesh** [comment]
splitting into multiple tickets

**Comment by pombredanne** [comment]
Both ticket fixed and patches applied.
