### ISSUE TITLE
specified pefile version does not exist on PyPi

### ISSUE THREAD

**Issue by jhgoebbert** [nexB/scancode-toolkit#1183]
pefile has not version 1.2.10-132 on PyPi ( https://pypi.org/project/pefile/#history )
but this is specified in setup.py: 'pefile == 1.2.10-132',

**Comment by pombredanne** [comment]
@jhgoebbert Thanks. In fact, pefile was not on pypi for a long while and furthermore the whole SVN tag history was not migrated to Github. And also the version scheme has changed: all the more reasons why bundling packages is a good idea.
That said, with https://github.com/nexB/scancode-toolkit/commit/4fe2927e1f134640362fe8ffe2e99ed84e0943ab I bumped pefile to its latest release and updated the code to match its API changes.
You can test this soon... I am checking a few extra things for other Pypi dependencies.

BTW, I assume that you are trying to install with a `pip install -e .`  from a checkout... but I may be wrong? how do you install?

**Comment by pombredanne** [comment]
So with the code #1184 I can run a `pip install -e .` from a checkout and all deps are fetched from Pypi instead of the bundled `thirdparty` dir. All the tests pass too.

**Comment by jhgoebbert** [comment]
Hi pombredanne,
thanks a lot for your changes/updates! Great! Now I can install scancode-toolkit for all our users on the systems (as the new version supports .cache to be in $HOME).

I tried PyPi first and checked "-e" later. Both ways are fine, but I in general I would give "pip install scancode-toolkit" the first try.

**Comment by pombredanne** [comment]
@jhgoebbert thanks for testing. `pip install scancode-toolkit` will work soon when I am pushing a new release there.

**Comment by pombredanne** [comment]
For reference see  https://github.com/nexB/scancode-toolkit/issues/1214#issuecomment-431404198

**Comment by pombredanne** [comment]
This is all fixed in develop now. The latest 2.9.7 installs allright
Thank you for your patience!
