### ISSUE TITLE
Add new public-domain rule

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1186]
Add new public domain rule
```
LibTomCrypt is public domain.  As should all quality software be.
Tom St Denis
```
i.e. the current scancode return nothing for the above notice
https://android.googlesource.com/platform/external/dropbear/+/donut-release/libtomcrypt/LICENSE

**Comment by pombredanne** [comment]
Thank you for the report. This is a rare case where a negative rule is not specific enough. This is the culprit https://github.com/nexB/scancode-toolkit/blob/1cd9436acb8463441a232fb850eb1060551a0683/src/licensedcode/data/rules/not-a-license.RULE
and this likely should be instead "Public DOMAIN As String" as this is to avoid false positive in VB code such as https://github.com/dotnet/samples/blob/74d09d6d2c6973bdf54329dc624264d0b080e3f5/snippets/visualbasic/VS_Snippets_Remoting/Classic%20HttpMethodAttribute.ReturnFormatter%20Example/VB/source.vb#L32

**Comment by pombredanne** [comment]
This has been fixed in develop. Thanks!
