### ISSUE TITLE
top-level MIT License detected at only 88%

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#1188]
When running a scan on ExpressJS v 4.16.3 (from: https://registry.npmjs.org/express/-/express-4.16.3.tgz), the top level LICENSE file is certainly `mit`, yet has a score < 90. 

You can find the text here: https://raw.githubusercontent.com/expressjs/express/master/LICENSE

The resulting license detection is:
```
{
  "key": "mit",
  "score": 88.83,
  "name": "MIT License",
  "short_name": "MIT License",
  "category": "Permissive",
  "is_exception": false,
  "owner": "MIT",
  "homepage_url": "http://opensource.org/licenses/mit-license.php",
  "text_url": "http://opensource.org/licenses/mit-license.php",
  "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:mit",
  "spdx_license_key": "MIT",
  "spdx_url": "https://spdx.org/licenses/MIT",
  "start_line": 1,
  "end_line": 24,
  "matched_rule": {
    "identifier": "mit_160.RULE",
    "license_expression": "mit",
    "licenses": [
      "mit"
    ],
    "is_license_text": true,
    "is_license_notice": false,
    "is_license_reference": false,
    "is_license_tag": false
  }
}
```

Because of the low score (< 90) this is classified as a `has_top_level_declared_licenses": false` for clarity scoring metric; Perhaps this is working as intended if the LICENSE file in question is far enough from the canonical MIT license text, but IMO it is pretty identical.

**Comment by pombredanne** [comment]
The interesting thing is that the [mit_160.RULE](https://github.com/nexB/scancode-toolkit/blob/1cd9436acb8463441a232fb850eb1060551a0683/src/licensedcode/data/rules/mit_160.RULE) is detected wholly.... (100% coverage) but then the three lines of copyright between the license name and text are taken into account and [applied as a discount on the score](https://github.com/nexB/scancode-toolkit/blob/1cd9436acb8463441a232fb850eb1060551a0683/src/licensedcode/match.py#L281) which therefore ends up as 88.83.
```
      "licenses": [
        {
          "key": "mit",
          "score": 88.83,
          "name": "MIT License",
          "short_name": "MIT License",
          "category": "Permissive",
          "is_exception": false,
          "owner": "MIT",
          "homepage_url": "http://opensource.org/licenses/mit-license.php",
          "text_url": "http://opensource.org/licenses/mit-license.php",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:mit",
          "spdx_license_key": "MIT",
          "spdx_url": "https://spdx.org/licenses/MIT",
          "start_line": 1,
          "end_line": 24,
          "matched_rule": {
            "identifier": "mit_160.RULE",
            "license_expression": "mit",
            "licenses": [
              "mit"
            ],
            "is_license_text": true,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 167,
            "matched_length": 167,
            "match_coverage": 100.0,
            "rule_relevance": 100
          },
          "matched_text": "The MIT License)\n
\n
Copyright ([c]) [2009]-[2014] [TJ] [Holowaychuk] <[tj]@[vision]-[media].[ca]>\n
[Copyright] ([c]) [2013]-[2014] [Roman] [Shtylman] <[shtylman+expressjs]@[gmail].[com]>
\n[Copyright] ([c]) [2014]-[2015] [Douglas] [Christopher] [Wilson] <[doug]@[somethingdoug].[com]>\n
\n
Permission is hereby granted, free of charge, to any person obtaining\n
a copy of this software and associated documentation files (the\n
'Software'), to deal in the Software without restriction, including\n
without limitation the rights to use, copy, modify, merge, publish,\n
distribute, sublicense, and/or sell copies of the Software, and to\n
permit persons to whom the Software is furnished to do so, subject to\n
the following conditions:\n
\n
The above copyright notice and this permission notice shall be\n
included in all copies or substantial portions of the Software.\n
\n
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,\n
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\n
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\n
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\n
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE"
        }
      ],
      "license_expressions": [
        "mit"
      ],
```
... because of this we may need to reconsider using the license score as-is for the license clarity score?
  May be instead a refined combo of the coverage, relevance and text/tag/reference/notice flags?
Or we could improve the basic license scoring such that it is not discounted so much  by extra words inside an another wholly detected license.

**Comment by majurg** [comment]
Additional copyright statements ofter occur in these MIT Licenses, and IMO don't effect the "clarity" of licensing at all for a particular package (it may even add more clarity in some cases). 

What about lowering the threshold in the `--license-clarity-score` part to something like 75-80? That would (hopefully) catch most of these cases where an otherwise 100-score license text is preceded by some copyright statements. Alternatively, we could just use the license rule score in our clarity calculations, but I am not sure that is possible.

**Comment by mjherzog** [comment]
From a logical perspective, the number of copyright statements should have no effect on licensing clarity.

**Comment by pombredanne** [comment]
@mjherzog That's a good point but the license detection knows nothing about copyrights for now... May be the solution is couple the two such that license detection knows when a line of text is a copyright  as this is likely needed to fix #372 and remove some noise from copyrights (such as FSF copyrights found in the GPL)

**Comment by pombredanne** [comment]
@majurg 
> What about lowering the threshold in the --license-clarity-score part to something like 75-80? That would (hopefully) catch most of these cases where an otherwise 100-score license text is preceded by some copyright statements.

A PR is welcomed... I think 80 or 85 would work out nicely

**Comment by mjherzog** [comment]
I guess I thought that license detection would already have a way to ignore copyright statements. If not, we probably need that since the location of copyright statements relative to license text is basically arbitrary.

**Comment by pombredanne** [comment]
FYI, this exact instance of this bug is fixed with https://github.com/nexB/scancode-toolkit/commit/f6912f4300933fa39a935a781f1b9f6a3aa3dcee BUT this ticket is not solved yet.
