### ISSUE TITLE
Show summary of copyrights for a scan in html-app

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#120]
**Narrative**: I want to quickly see the number and proportion of copyrights detected from a scan. This will help me estimate the primary owner for a package.
**Context**: A Treemap from D3.js has been visited in the past. We may want to offer several different graphic/chart views from D3.js.
**Acceptance Criteria:** 
        - *Scenario 1:* When a user runs a scan on a codebase, a visual summary of the high level copyright stats would be displayed in the HTML app.

**Comment by pombredanne** [comment]
As a first step we need to collect copyright holders in the scan

**Comment by nspsjsu** [comment]
Issue resolved
