### ISSUE TITLE
ScanCode throws no error when -i or alternatives are missing

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#1205]
I inadvertently omitted the `-i` flag in running ScanCode and received no error, discovering my omission only when viewing the resulting `json` output.  It would be helpful (and save time) if ScanCode notified the user that he/she had failed to supply the necessary flag.

**Comment by pombredanne** [comment]
@johnmhoran I am closing for now as wontfix. Please reopen if you feel strongly about it . The `--info` scan is optional, so there is no way we can have both something that is optional and required.
