### ISSUE TITLE
Add "No License" to html-app license summary

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#121]
**Narrative**: I want to quickly see the number and proportion of licenses detected from a scan. This will help me estimate the primary license for a package. Representing the files that have no license detected would be beneficial to license summary distribution.
**Context**: A Treemap from D3.js has been visited in the past. Although files which have no license detected were not represented.
**Acceptance Criteria:** 
        - *Scenario 1:* When a user runs a scan on a codebase, a visual summary of the high level license stats would be displayed in the HTML app; this should include files that do not have a license detected.

**Comment by nspsjsu** [comment]
Reviewed & confirming that a "No License Found" bar  shows the total count

**Comment by jdaguil** [comment]
thanks @nspsjsu
