### ISSUE TITLE
Installing scancode-toolkit from PyPI fails due to pefile issue

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#1214]
Running `pip install --user scancode-toolkit==2.9.3` fails for me on Windows:

```
Could not find a version that satisfies the requirement pefile==1.2.10-132 (from scancode-toolkit==2.9.3) (from versions: 2016.3.28, 2017.8.1, 2017.9.3, 2017.11.5, 2018.8.8)
No matching distribution found for pefile==1.2.10-132 (from scancode-toolkit==2.9.3)
```

Indeed there seems to have [never been](https://pypi.org/project/pefile/#history) a version 1.2.10-132 of "pefile". Can we use the [latest version 2018.8.8](https://pypi.org/project/pefile/2018.8.8/) instead?

Note that this is a different issue from https://github.com/nexB/scancode-toolkit/issues/755.

**Comment by sschuberth** [comment]
I just noticed this problem is not limited to Windows as the `pefile` package seems to be also used on non-Windows platforms.

**Comment by pombredanne** [comment]
@sschuberth yes this is an issue that is not OS specific and this has been reported also by @jhgoebbert with #1183 and fixed with the PR in #1184 but this is after the 2.9.3 release. I can likely push a minor 2.9.4 later today if this helps.

**Comment by sschuberth** [comment]
Yes please, a new release would be highly appreciated!

**Comment by pombredanne** [comment]
@sschuberth I pushed a 2.9.4 tag and released this to Pypi too for you to test. @jhgoebbert if you mind testing too that would be great

**Comment by sschuberth** [comment]
I gave it a try, and while it goes a little further now, it now fails because Visual C++ 9.0 could be found:

```
  Running setup.py install for intbitset: started
    Running setup.py install for intbitset: finished with status 'error'
    Complete output from command c:\python\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\sebastian\\appdata\\local\\temp\\pip-build-vuvuz1\\intbitset\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\sebastian\appdata\local\temp\pip-z6l6eb-record\install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    copying intbitset\intbitset_helper.py -> build\lib.win32-2.7
    copying intbitset\version.py -> build\lib.win32-2.7
    running egg_info
    writing requirements to intbitset\intbitset.egg-info\requires.txt
    writing intbitset\intbitset.egg-info\PKG-INFO
    writing top-level names to intbitset\intbitset.egg-info\top_level.txt
    writing dependency_links to intbitset\intbitset.egg-info\dependency_links.txt
    reading manifest file 'intbitset\intbitset.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.css' under directory 'docs\_themes'
    warning: no files found matching '*.css_t' under directory 'docs\_themes'
    warning: no files found matching '*.conf' under directory 'docs\_themes'
    warning: no files found matching '*.html' under directory 'docs\_themes'
    warning: no files found matching 'COPYING' under directory 'docs\_themes'
    warning: no files found matching 'README' under directory 'docs\_themes'
    warning: no files found matching '*.html' under directory 'docs\_templates'
    writing manifest file 'intbitset\intbitset.egg-info\SOURCES.txt'
    running build_ext
    building 'intbitset' extension
    error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
```

Is that expected? I though when installing through PyPI it should be more or less end-user ready and not require development tools. Also, when using ScanCode from source and running `./configure` Visual C++ 9.0 is actually not required, which seems a bit odd to me.

**Comment by sschuberth** [comment]
Taking a look at this again, @pombredanne do you have any idea why there seems to be an *egg* being used for `intbitset` instead of the committed "thirdparty" *whl* which has precompiled native code?

**Comment by pombredanne** [comment]
@sschuberth what do you mean by an egg? that sounds really odd (and old) ... which OS do you see this on? and what are the files in play?

**Comment by sschuberth** [comment]
@pombredanne maybe I'm misreading the log above, but it contains `egg_info` or strings like `writing intbitset\intbitset.egg-info\PKG-INFO` several times. Sorry for my limited Python knowledge, but this sounds to me as if `intbitset` is installed via ab `egg` instead of a `whl`...

**Comment by pombredanne** [comment]
@sschuberth Sorry I had not seen the log you had pasted above before... my bad! :blush: 

The egg references are part of the internal building process that is logged here. It is not creating an egg at all, though internally Python still references the "egg" word in some parts of the build.

Now what this means though is that you are NOT using the pre-built wheel: Python decided that there was no good pre-built for your OS/arch available on Pypi and decided to build from source code instead.
For intbitset in particular, this a C library to handle low level sets of integers represented as bitsets (aka. bitmaps) and is mostly all native code:  there is only a source at https://pypi.org/project/intbitset/#files ... hence the need for pip to compile and build.

Several Pypi packages used in ScanCode do not come with pre-built wheels available on the Pypi public repository... only with a source package that needs to be built first ... When you install from Pypi you will therefore have to handle the build yourself and need to have a proper setup for this which is a tad more engaged on Windows.

(and when you install from ScanCode, the pre-built are baked so you no build is needed ;) ).

In the case of building on Windows, you need to install first the  Microsoft Visual C++ Compiler for Python 2.7  as mentioned in the log and this available at:  http://aka.ms/vcpython27 or at https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by sschuberth** [comment]
Thanks for the info, @pombredanne.

> Python decided that there was no good pre-built for your OS/arch available

Then the interesting question to me is: Why is that the case? You seem to have Python 2.7 wheels for `win32` and `win_amd64` committed, so I should be fine. Any ideas how to debug this?

**Comment by pombredanne** [comment]
@sschuberth when you do a plain `pip install scancode-toolkit` there is no checkout at play.
Everything is fetched directly from Pypi. And the ScanCode pre-built wheel does not further contain any of its prebuilt dependencies. These are fetched from Pypi instead like for any regular Python package. You are basically on your own.

In contrast, when you work from a checkout (or a released download archive) and you run `./configure` or when you run ./scancode` for the first time the whole set of deps that is installed is bundled in thirdparty.

The `configure` script actually does runs `pip install` commands but it does fetch ANYTHING from the Pypi repo: everything is taken from the local directory using the `--no-index`, the `--no-cache-dir` and `--find-links` pip [options](https://github.com/nexB/scancode-toolkit/blob/develop/etc/configure.py#L221) so everything is fully self-contained and works offline too.
And Scancode-toolkit proper is installed in "editable" [mode](https://github.com/nexB/scancode-toolkit/blob/develop/etc/conf/base.txt#L10) with a `pip -e .` which basically runs the its `setup.py` and installs in the current virtualenv fetching all the deps from the `thirdparty` dir listed in the configure root [script](https://github.com/nexB/scancode-toolkit/blob/develop/configure.bat#L9).

**Comment by pombredanne** [comment]
so in a nutshell:
1. if you work from a checkout or download, use configure and you are all take care of. All deps are pre-built and bundled.

2. if you work from a plain `pip install scancode-toolkit` you are on your own and you should manage your virtualenv, and have the proper setup to effectively build and compile if needed any of the scancode native dependencies as everything will be fetched from Pypi and may need building.

**Comment by sschuberth** [comment]
I see, thanks!

**Comment by pombredanne** [comment]
This is all fixed in now. The latest 2.9.7 installs alright
Thank you all.
