### ISSUE TITLE
Should license detection also return SPDX license expressions?

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1217]
Today we have this:
- when the output is SPDX, we return proper SPDX license expressions using SPDX license ids
- otherwise (JSON, etc) we return
  - license expressions using ScanCode own license keys
  - a list licenses and for these that are known at SPDX the corresponding SPDX license key

In this later case I wonder if it could be useful to also return license expressions using SPDX license ids.
This would be eventually a new option and would be returned under its own file-level attribute.
This could also possibly apply to a companion to the `license_expression` returned with `packages` for  a package manifest. Now, of the 1301 licenses that scancode knows, only 375 are referenced at SPDX, therefore there will be quite a few "LicenseRef" in this case. See #532 for this issue and https://github.com/nexB/scancode-toolkit/issues/532#issuecomment-431420151 in particular.

@sschuberth @mjherzog @DennisClark @armijnhemel Any feedback?

**Comment by sschuberth** [comment]
Maybe @mnonnenmacher also has an opinion about this as we were just today discussing this in some other context.

**Comment by armijnhemel** [comment]
it makes sense to me. What I would love to see is the version of the SPDX standard that is used, so I don't have to guess :-)

**Comment by pombredanne** [comment]
@armijnhemel good point! We can set the version of the SPDX license list in the scan headers.

**Comment by pombredanne** [comment]
This is going to be useful for ClearlyDefined and @dabutvin ... so this is going into 3.1 alright at the minimum.

**Comment by pombredanne** [comment]
This is being merged in develop and will be in v32.0
