### ISSUE TITLE
Add total number of files to license summary view in html-app

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#122]
**Narrative**: I want to see the total of number files that were scanned in the license summary view. 
**Context**: I want to perform a quick calculation of a license percentage based on the total number of files scanned and a specific license count.
**Acceptance Criteria:** 
        - *Scenario 1:* When a user runs a scan on a codebase, the total number files scanned would be displayed in addition to the license summary chart.

**Comment by nspsjsu** [comment]
Currently, the total number of scanned files are displayed at html-app view in addition to the license summary chart.
