### ISSUE TITLE
Normalize VCS URL vs. repository 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1226]
Today we are getting things as they come from package manifest. It would be best to normalize this to have uniform URLs there

**Comment by sschuberth** [comment]
FYI, in case we want to align on how VCS URL normalization is done, this is what we do currently in ORT: https://github.com/heremaps/oss-review-toolkit/blob/ff0645eb1e8774801b6d93bf5c8a4456aacf9410/utils/src/main/kotlin/Utils.kt#L197.

**Comment by pombredanne** [comment]
Done. and merged.
