### ISSUE TITLE
ScanCode should cleanup tempfiles

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1231]
There have been a few private reports made to me where folks ran out of disk space.
ScanCode creates eventually quite a few tempfiles and never delete these. You can set where to save these with the SCANCODE_TMP env var:

    Set the path to an existing directory where ScanCode can create temporary
    files from the value of the `SCANCODE_TMP` environment variable if
    available. If `SCANCODE_TMP` is not set, a default sub-directory in the
    system temp directory is used instead. Each scan run creates its own
    tempfile subdirectory.

We should clean these and also add details of this env var to the doc.

**Comment by pombredanne** [comment]
For reference there is another place where "temp files" are created which is cached across runs: SCANCODE_CACHE

    Set the path to an existing directory where ScanCode can cache files
    available across runs from the value of the `SCANCODE_CACHE` environment
    variable. If `SCANCODE_CACHE` is not set, a default sub-directory in the
    user home directory is used instead.

**Comment by mjherzog** [comment]
Isn't this usually handled by OS "housekeeping". Are we talking about a new ScanCode feature or documentation?

**Comment by pombredanne** [comment]
This has been merged in develop.
