### ISSUE TITLE
Bad copyright returned from a scan of the-platform-0.4.0.zip

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1234]
Bad copyright returned from a scan of this package: 
https://github.com/palmerhq/the-platform/archive/v0.4.0.zip

```
Copyright (c) Facebook, Inc. 18
(c) null c&&oc(c.type) b b.value 2
Copyright (c) The Palmer Group 1
```

The Holders also returned this: 
```
Facebook, Inc. 18
null c&&oc(c.type) b b.value 2
The Palmer Group 1
``

**Comment by pombredanne** [comment]
Thanks! I think the reason is that `null` should not be treated as a possible name part

**Comment by pombredanne** [comment]
Thank you for the report: this is fixed and merged in develop
