### ISSUE TITLE
Add option to have a fully "flat" csv output

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1236]
I find it conveient at times to have a CSV with a single row for each file with data  compressed in single cells rather than multiple cells across rows. The CSV output from ScanCode for any Scan other than -info  is no longer well structured and may exceed the limits of spreadsheet tools but even then I could make use of this for a quick glance at results

**Comment by mjherzog** [comment]
The other important topic is here is what based CSV file to use to create the initial Analysis Workfile for a project. The current -info format is "clean" and simple in terms of one CSV row per file or directory, but then you need to cut and paste any copyright or license data from AbC Manager or another CSV Scan file (-cli, -clip or -clipeu) and in that case the relevant copyright and license data will be spread across multiple rows.

**Comment by pombredanne** [comment]
This is a dupe of #830
