### ISSUE TITLE
Sync scancode-toolkit with the SPDX License List 3.3

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1242]
Sync scancode-toolkit with the SPDX License List 3.3.

See https://spdx.org/licenses/ 
and
https://github.com/spdx/license-list-XML/blob/master/RELEASE-NOTES.md

**Comment by pombredanne** [comment]
@DennisClark sure thing. We need to have the JSON data generated though before I can do anything I created https://github.com/spdx/license-list-data/issues/37

**Comment by pombredanne** [comment]
@DennisClark FYI the fix is in #1245 and this contains everything from the SPDX list 3.3

**Comment by pombredanne** [comment]
This has been merged in develop.
