### ISSUE TITLE
License data for exceptions should have pointers the main license the exception relates to

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#126]
For instance, the Classpath exception to the GPL 2.0 should have a pointer to the GPL 2.0 license key.
And the LGPL-3.0 to the GPL-3.0. This can be useful to actually collect all the set of license texts that would need to be produced towards generating attribution for AboutCode or else in #123

**Comment by ened** [comment]
That would be very helpful. It explains why the "LGPL 2.0 or later" item only contains the permission note and misses the full license text, even though I would have expected it there.

**Comment by ened** [comment]
@pombredanne I could imagine this needs to work like this:

1. The definition of the main license is written in the `.yml` file, like `gpl-2.0-gcc.yml`, in a field called: `main_license`. That field is a key to the main license, like `gpl-2.0`. 
2. When scancode generates the list of licenses, it should be done in 2 passes. The first pass will go through the list of licenses, finds the `main_license` ones and adds them to the final list. The second pass should work as it is now.

Sounds good to you?

**Comment by pombredanne** [comment]
@ened You wrote:
> That would be very helpful. It explains why the "LGPL 2.0 or later" item only contains the permission note and misses the full license text, even though I would have expected it there.

This is actually a whart that we need to fix. `LGPL 2.0` or later should contain the full text of the LGPL, and the rare case of `LGPL 2.0 only` should be one or more notices. I debated to the SPDX,org mailing list on this topic a week or two ago.

This should be fixed.

Now, for exceptions and this `or later` topic, there would be a few ways to go at it:
1. add a field to the License data that would point to the `main_license` ... I may prefer to name this `exception_to` .
2. or add an expression field to the License data that would be for instance for `gpl-2.0-gcc.yml`: 
 > effective_license: gpl-2.0 with gpl-2.0-gcc

and also update all the rules to point to such an expression for licenses exceptions.

**Comment by pombredanne** [comment]
The new approach with #74 is going to be different after all. In particular there is no consistent way to tell which license an exception may apply too all the times. It may be more than one possibility or not defined.

- exception licenses will be flagged with an `is_exception` boolean tag.
- licenses that support `or_later` will be flagged with an `is_or_later` boolean tag
- licenses that are versioned will have a `next_version` field that points to the license key of the next version when available. This can be used for validation and possibly for a future license expression expansion (e.g. such that `GPL-1.0 or later` could be expanded to `GPL-1.0 or GPL-2.0 or GPL-3.0`) 
- a new NOTICE text will be added to store the standard notice that may exist for some licenses such as Apache or A/L/GPL or MPL licenses and in particular to have the standard "or later" notice for the license keys that are for an "or later license"  per #138
- Support for a preferred license version when there is an "or later" case would be something that would be added to a user config file

**Comment by pombredanne** [comment]
So I am closing this in favor of #74 and full support for license expressions.
