### ISSUE TITLE
Duplicate spdx_license_keys

### ISSUE THREAD

**Issue by furuholm** [nexB/scancode-toolkit#1264]
I have found two duplicated SPDX license keys in the license metadata:

### Nokia-Qt-exception-1.1
[nokia-qt-exception-1.1.yml](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/nokia-qt-exception-1.1.yml) and [qt-company-exception-lgpl-2.1.yml](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/qt-company-exception-lgpl-2.1.yml) both specifies spdx_license_key: `Nokia-Qt-exception-1.1`

Since spdx includes [`Qt-LGPL-exception-1.1`](
https://spdx.org/licenses/Qt-LGPL-exception-1.1.html) my guess is that simply changing the spdx_license_key to `Qt-LGPL-exception-1.1` should solve the problem for this one.

### GPL-2.0-with-bison-exception
[gpl-2.0-bison.yml](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/gpl-2.0-bison.yml) and [gpl-2.0-bison-2.2.yml](
https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/gpl-2.0-bison-2.2.yml) both specifies spdx_license_key: `GPL-2.0-with-bison-exception`

The notes of [gpl-2.0-bison.yml](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/gpl-2.0-bison.yml) says `replaced by bison-exception-2.0`, which is not an SPDX License exception. My guess is therefore that `spdx_license_key` should be removed from [gpl-2.0-bison.yml](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/gpl-2.0-bison.yml)

Will create a PR with the suggested fixes.

**Comment by furuholm** [comment]
PR also removes spdx_license_key from libtool-exception.yml since it has been deprecated and replaced with `libtool-exception-2.0`.

**Comment by pombredanne** [comment]
@furuholm Hi and thank you for the report and PR. Good catch!
Just curious: how did you find out about these?

Note that we added a few extra things to support these as explained here https://github.com/nexB/scancode-toolkit/issues/935#issuecomment-436050862

**Comment by furuholm** [comment]
@pombredanne Thanks for the fast response!

I saw it when trying to import all spdx license ids to a database table with unique constraint.

**Comment by pombredanne** [comment]
@furuholm Thanks for updating the PR. Now when you load licenses in your DB... do you use Python for this? And irrespective of this, have you considered the `is_deprecated` flag? All the licenses you are listing here are marked as deprecated. (but as a side note you may have found some interesting license data bug nonetheless)

If you use Python, you could call this https://github.com/nexB/scancode-toolkit/blob/3e59aae410c8637577b84d11360ddd5fb5c6cfac/src/licensedcode/cache.py#L76 that will give you a mapping of {license key -> License object) that are loaded from the yaml files. License objects are this https://github.com/nexB/scancode-toolkit/blob/3e59aae410c8637577b84d11360ddd5fb5c6cfac/src/licensedcode/models.py#L72

And just curious (but you do not have to answer) what is the DB meant to be used for? I will be glad to help if I can!

**Comment by furuholm** [comment]
@pombredanne Not using Python, but I did consider taking the `is_deprecated` flag into account, however I was not sure what the semantics were so I decided to keep the deprecated licenses as well. Since `qt-company-exception-lgpl-2.1` was not deprecated (as far as I can see) I thought I might as well fix the other ones as well.

The database is part of a software supply chain initiative where we are considering using ScanCode as the license scanner. If things go well we will hopefully be able to contribute more to this awesome project!

Thanks for informing me about `other_spdx_license_keys`. I did not know about that.

**Comment by pombredanne** [comment]
Thank you for the details. I will update and merge your pr by next week at the latest!

**Comment by pombredanne** [comment]
Note that the License model is here https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/models.py#L72 but the field doc is not great!... I will improve this with the 3.0 release

**Comment by furuholm** [comment]
Thanks @pombredanne! Huge props to you for fixing this so soon!
