### ISSUE TITLE
Please check options before opening output files and overwriting possible input files

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1266]
I wanted to scan a file and did the following:

$ ./scancode -l --json-pp /tmp/LICENSE
Usage: scancode [OPTIONS] <input> <OUTPUT FORMAT OPTION(s)>
Try 'scancode --help' for help on options and arguments.

Error: Missing argument "input".

where /tmp/LICENSE is the input file.

Of course, the mistake is that I needed to add '-' as the output file. What surprised me is that the command I typed in overwrote my input (and now I have a 0 bytes sized file), instead of first warning me to say that something is wrong.

**Comment by pombredanne** [comment]
@armijnhemel Thanks for the report and sorry for this buggy behaviour. This is a pita indeed. The default way for the options used for file outputs is to eagerly open them in write mode... from what I can see here https://github.com/nexB/scancode-toolkit/blob/86722b334aa3f91e799964d222b4b11f30f2e251/src/formattedcode/output_json.py#L69 

That's a bad idea. 
Do you think we should go as far as reporting an error if the output file exists? (that's an uncommon CLI behaviour, but if this can help that would be good)

**Comment by armijnhemel** [comment]
To be honest I would say: check first, open then. Overwriting files: unsure about that. This used to be a problem with old scancode, but I don't see it as a problem now TBH.

**Comment by pombredanne** [comment]
@armijnhemel I pushed in a branch a minor eval of a feature called "lazy" when opening output files. https://click.palletsprojects.com/en/7.x/api/#click.File ... 
Not sure this is what will solve your issue, but at least the file will not opened until the scan is done and outputs start to be written.

Beyond this, IMHO the simplest would be to prohibit asking for an output to an existing file.
This is a rather uncommon behavior for shell CLI tools, but I am fine with adding this kind of check if you think this is worth it.

**Comment by pombredanne** [comment]
@armijnhemel This has been merged in develop with "check first, open then"
If you think we need to implement something that never overrides existing files (even if this was requested as an output path) please reopen!

**Comment by armijnhemel** [comment]
I actually meant: first check if all the options are valid and only then open the files. That seems like an easier solution to me :-)

**Comment by pombredanne** [comment]
> I actually meant: first check if all the options are valid and only then open the files. That seems like an easier solution to me :-)

@armijnhemel this should be what happens now. the click "lazy" argument on file options delays opening files until they are used... in this case this means when output is being written at the tail end of the scan.
