### ISSUE TITLE
Rename Package.normalized_license to license_expression

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1268]
This is simpler and clearer

**Comment by pombredanne** [comment]
normalized license is a confusing term.... Any objection? @DennisClark you are good at names!

**Comment by DennisClark** [comment]
@pombredanne   do the right thing !!!

**Comment by pombredanne** [comment]
thx. So this would partially revert this recent commit: https://github.com/nexB/scancode-toolkit/commit/94187418d0da73bb1047407967befd4a0420167e

**Comment by pombredanne** [comment]
Done and merged.
