### ISSUE TITLE
Incorrect license detection on libwebp

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1270]
This is detected as having a proprietary license https://github.com/webmproject/libwebp/blob/v0.3.0/src/webp/decode.h

I'm not sure if the latest version is also not detected properly:
https://github.com/webmproject/libwebp/blob/485ff86fbb174b518834503cb39c9c8e20567f38/src/webp/decode.h

**Comment by pombredanne** [comment]
Thanks. Definitely a bug!

**Comment by pombredanne** [comment]
Fix and merged in develop
