### ISSUE TITLE
Remove built-in samples/

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1286]
These are mostly random and not great. They would be best removed.

**Comment by mjherzog** [comment]
Any set of samples is inherently somewhat random. Are you suggesting no samples or different ones>

**Comment by pombredanne** [comment]
@mjherzog I am suggesting to have have some samples but available separately and not built in Scancode or may be no samples at all.

**Comment by mjherzog** [comment]
Perhaps document some samples under AboutCode repo since we need them for ScanCode and also AbC Manager.

**Comment by AyanSinhaMahapatra** [comment]
Made this [comment](https://github.com/nexB/scancode-toolkit/issues/1031#issuecomment-549021457) related to this issue.

**Comment by abhi27-web** [comment]
Can I work on these issues. Please send me the details.

**Comment by pombredanne** [comment]
@abhi27-web this is not entirely easy as we are not yet sure what to do there.
I am closing in favor of #1286

**Comment by pombredanne** [comment]
I meant #1031 ..., not #1286!
