### ISSUE TITLE
Create basic documentation structure and tooling to build and publish

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1287]
This would be under `docs/` and should be using ReST, sphinx and published to readthedocs.org

**Comment by pombredanne** [comment]
This was pushed by @DennisClark with https://github.com/nexB/scancode-toolkit/commit/415d0c89267019b1c7bb35dc6bbb852d44419ec8

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne This should be closed now?

**Comment by majurg** [comment]
Closing this
