### ISSUE TITLE
Scan of cbccl_0.1_source.zip returns a wxwindows license

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1289]
In a recent scan of http://master.dl.sourceforge.net/project/cbccl/cbccl/cbccl_0.1/cbccl_0.1_source.zip the following license keys were returned: 
wxwindows 65
gpl-1.0-plus 33
gpl-2.0-plus 1

I believe that `wxwindows` has been deprecated and that alternatively the returned license expression should be:  `lgpl-2.0-plus WITH wxwindows-exception-3.1` .  This can be confirmed by the licence.txt file in the package, part of which I will quote here: 
```
                       WXWINDOWS LIBRARY LICENCE
     TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
  
  This library is free software; you can redistribute it and/or modify it
  under the terms of the GNU Library General Public Licence as published by
  the Free Software Foundation; either version 2 of the Licence, or (at
  your option) any later version.
```
followed by the rest of the usual lgpl-2.0 notice, and then an extensive "EXCEPTION NOTICE" text.  So the "WXWINDOWS LIBRARY LICENCE" is actually simply a notice for lgpl-2.0 with an exception. 

Perhaps this has been addressed already?  If so, I'm looking forward to v3.0 of scancode-toolkit.

**Comment by pombredanne** [comment]
@DennisClark Thanks! This is better now... when I scan this with the latest develop branch code I get this detection ... and the GPL-1.0 parts are likely incorrect. The project page says "wxWindows Library Licence" yet  there are still some ambiguities wrt to GPL-2.0 or LGPL in the code notices.. likely some quick GPL to LGPL text replacement gone south.

So some GPL may be right, most not.

```
  "summary": {
    "license_expressions": [
      {
        "value": "lgpl-2.0-plus WITH wxwindows-exception-3.1",
        "count": 65
      },
      {
        "value": "gpl-1.0-plus",
        "count": 33
      },
      {
        "value": null,
        "count": 16
      },
      {
        "value": "gpl-2.0-plus",
        "count": 1
      }
    ],
```

**Comment by pombredanne** [comment]
Fix and merged in develop. We now have proper expressions.
