### ISSUE TITLE
Scan of server-mariadb-10.3.11.tar.gz fails

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1298]
A scan of this package using a recent version of scancode fails to complete
https://github.com/MariaDB/server/archive/mariadb-10.3.11.tar.gz

Error log attached.

[server-mariadb-10.3.11.tar.gz-scan-error-log.txt.zip](https://github.com/nexB/scancode-toolkit/files/2622541/server-mariadb-10.3.11.tar.gz-scan-error-log.txt.zip)

**Comment by pombredanne** [comment]
Thanks! these are mostly warning... but even these should not be there

**Comment by pombredanne** [comment]
This has been fixed and merged in developed
