### ISSUE TITLE
something wrong with /opt/scancode-toolkit/src/licensedcode/models.py

### ISSUE THREAD

**Issue by arthur657834** [nexB/scancode-toolkit#1299]
the branch is develop

10:24:11 Path: ljtest/src/main/webapp/WEB-INF/database/model.xml
10:24:11   ERROR: for scanner: licenses:
10:24:11   ERROR: Unknown error:
10:24:11   Traceback (most recent call last):
10:24:11     File "/opt/scancode-toolkit/src/scancode/interrupt.py", line 91, in interruptible
10:24:11       return NO_ERROR, func(*(args or ()), **(kwargs or {}))
10:24:11     File "/opt/scancode-toolkit/src/scancode/api.py", line 172, in get_licenses
10:24:11       for match in idx.match(location=location, min_score=min_score, **kwargs):
10:24:11     File "/opt/scancode-toolkit/src/licensedcode/index.py", line 606, in match
10:24:11       matched = matcher(qry)
10:24:11     File "/opt/scancode-toolkit/src/licensedcode/index.py", line 529, in get_approximate_matches
10:24:11       query_run, self, rules_subset=rules_subset, top=MAX_CANDIDATES)
10:24:11     File "/opt/scancode-toolkit/src/licensedcode/match_set.py", line 281, in compute_candidates
10:24:11       thresholds = thresholds_getter(rule)
10:24:11     File "/opt/scancode-toolkit/src/licensedcode/models.py", line 846, in thresholds_unique
10:24:11       if not self._thresholds_unique:
10:24:11   AttributeError: _thresholds_unique

**Comment by pombredanne** [comment]
thanks! that's really weird though.

Could you try to run this on your checkout?
`./configure --clean && ./configure`

And then retry your command? Working from a checkout may need to re-configure when you switch branches or pull new code in.

**Comment by pombredanne** [comment]
@arthur657834 were you able to to try the command above?

**Comment by arthur657834** [comment]
it works,thank you

**Comment by pombredanne** [comment]
@arthur657834 excellent!
I am closing this then. Thank you for using ScanCode!
