### ISSUE TITLE
ms-pl license detected where no clues seem to be present

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#1306]
A recent ScanCode scan of a `.jsp` file returned a score of 50 for the presence of the `ms-pl` license.  The file itself, however, appears to contain nothing capable of triggering a score greater than 0.

**Comment by pombredanne** [comment]
@johnmhoran thank you. I had created rules to detect bare license ids but this is too weak. Here the rule `spdx_license_id_ms-pl_for_ms-pl.RULE` which contains `Ms-PL` is likely detected.

**Comment by pombredanne** [comment]
Fixed in develop. Thank you!
