### ISSUE TITLE
npm packagedcode parse can't handle list of homepage content

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1308]
homepage_url can be list instead of string in some json input.

By accessing https://registry.npmjs.org/npm-research, the homepage field in returned json is a list instead of string,

```
  "repository": {
    "type": "git",
    "url": "git://github.com/jprichardson/npm-research.git"
  },
  "homepage": [
    ""
  ],
  "keywords": [
    "npm",
    "github",
    "bitbucket",
    "research",
    "search",
    "package",
    "packages"
  ],

```

**Comment by pombredanne** [comment]
@linexb thank you for this report!

**Comment by pombredanne** [comment]
very specifically this means that when scanning this https://github.com/jprichardson/npm-research/blob/050a62a4b2dc252055793550aae72ddf00c18f6f/package.json for `--package` no package data is returned because of the parsing failure from the homepage being a list instead of a string

**Comment by sschuberth** [comment]
> homepage_url can be list instead of string in some json input.

Which BTW is invalid according to https://docs.npmjs.com/files/package.json#homepage. With that in mind, I guess it's OK to fail on that, as we can hardly support all kinds of invalid data.

**Comment by pombredanne** [comment]
This has been fixed and merged.
