### ISSUE TITLE
kernel/arch/alpha/Makefile license is gpl, but should be gpl-2.0 or gpl-1.0 ?

### ISSUE THREAD

**Issue by ened** [nexB/scancode-toolkit#134]
Say there is a Makefile like this:

```
#
# alpha/Makefile
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Copyright (C) 1994 by Linus Torvalds
#
```

Then scancode detects this as `gpl`, however it should be detected as `gpl-1.0` or `gpl-2.0`. `gpl` has no license description file (`.yml`).

**Comment by pombredanne** [comment]
@ened When a someone says just my code is GPL without stating a version, then you can pick any version. Per section 9 of the GPL https://enterprise.dejacode.com/license_library/Demo/gpl-2.0/#license-text :  

> "If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software Foundation."

So any one of the GPL 1, 2 or 3 could be selected as you rightly reported.

Now here there is another bit of data which is:
> "See the file "COPYING" in the main directory of this archive for more details.

Ideally, we should be able to interpret such a statement, and apply the license found in the corresponding COPYING file if present and detected.

Alternatively, we could effectively get rid of the bare "gpl" key (as well as the similar key for lgpl, gfdl and a few other related licenses) and update the license rules to effectively report a license choice instead.
That would be better I guess.

**Comment by pombredanne** [comment]
@ened so after thinking about this, I thing approaches could be either:
-  add a new tag to these "bare" licenses (mostly the GNU varieties: GPL, LGPL and GFDL) that would recommend arbitrarily one of the possible versions. An arbitrary choice could v2 licenses..
- treat these as licenses choices with an arbitrary default (such as the version in the middle V2 or the latest version)

**Comment by pombredanne** [comment]
@ened in the end this is a case that has been resolved as this is Linux specific and should therefore be GPL-2.0. This is what is returned after several refinements part of reviewing full kernel scans with kernel maintainers:
```
{
  "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
  "scancode_version": "2.1.0.post69.536f354.dirty.20171004195422",
  "scancode_options": {
    "--copyright": true,
    "--license": true,
    "--license-score": 0,
    "--license-text": true,
    "--format": "json-pp",
    "--diag": true
  },
  "files_count": 1,
  "files": [
    {
      "path": "scancode-toolkit-master/t",
      "scan_errors": [],
      "licenses": [
        {
          "key": "gpl-2.0",
          "score": 100.0,
          "short_name": "GPL 2.0",
          "category": "Copyleft",
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-2.0.html",
          "text_url": "http://www.gnu.org/licenses/gpl-2.0.txt",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-2.0",
          "spdx_license_key": "GPL-2.0",
          "spdx_url": "https://spdx.org/licenses/GPL-2.0",
          "start_line": 4,
          "end_line": 6,
          "matched_rule": {
            "identifier": "gpl-2.0-linux.RULE",
            "license_choice": false,
            "licenses": [
              "gpl-2.0"
            ],
            "matcher": "2-aho",
            "rule_length": 29,
            "matched_length": 29,
            "match_coverage": 100.0,
            "rule_relevance": 100
          },
          "matched_text": "This file is subject to the terms and conditions of the GNU General Public\n# License.  See the file \"COPYING\" in the main directory of this archive\n# for more details"
        }
      ],
      "copyrights": [
        {
          "statements": [
            "Copyright (c) 1994 by Linus Torvalds"
          ],
          "holders": [
            "Linus Torvalds"
          ],
          "authors": [],
          "start_line": 8,
          "end_line": 8
        }
      ]
    }
  ]
}
```

Closing this then. Thank you for your patience!
