### ISSUE TITLE
can't install with pip3

### ISSUE THREAD

**Issue by dankegel** [nexB/scancode-toolkit#1342]
python2.7 is dying (see https://pythonclock.org/ ), time to make sure python3 support is happy.

On Ubuntu 18.04, installing with 'pip3 install scancode-toolkit' fails with
```
Collecting scancode-toolkit
  Could not find a version that satisfies the requirement scancode-toolkit (from versions: )
No matching distribution found for scancode-toolkit
```

This is especially annoying since 'pip install scancode-toolkit' fails with a sigsegv (not scancode's fault; 'pip install simplejson' also crashes.  See https://github.com/simplejson/simplejson/issues/114 for workaround).

**Comment by pombredanne** [comment]
@dankegel yes! 
we are tracking this in #295 so let me move you comments there and close this as a dupe. See https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-458643606
