### ISSUE TITLE
Can't find right version of six when installed --user on mac osx 10.11

### ISSUE THREAD

**Issue by dankegel** [nexB/scancode-toolkit#1343]
Oh, dear $deity.  Life with python on old macs is difficult, especially for someone who doesn't really like either.

The command
$ pip install --user scancode-toolkit
fails initially with "TLSV1_ALERT_PROTOCOL_VERSION".
See workaround at
https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies/49748494

Then it succeeds, but the command
$ scancode --version

fails (naturally) because Mac pip installed it to ~/Library/Python/2.7/bin/scancode.

$ ~/Library/Python/2.7/bin/scancode --version

fails with

pluggy.manager.PluginValidationError: Plugin 'json-pp' could not be loaded: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))!

Fine, so install a newer six with
$ pip install --user 'six>=1.9'

Alas, that doesn't help, same error.  A pox on this runtime environment mess :-(

And, alas, removing ~/Library/Python and starting fresh doesn't change the result.

**Comment by dankegel** [comment]
Not a priority - I'm working on Linux dependencies, really, so I'm happy to ignore this for now.

**Comment by pombredanne** [comment]
@dankegel thank you for the report.
you wrote 
>  I'm happy to ignore this for now.

OK, but do you have the issue when you get a checkout of the develop branch and then run `./configure` ?
All the mac deps are pre-built and bundled in the thirdparty directory, so it should work always in this case.

When doing a pip install, it should work too, but this can be a tad more engaged as there are several Python libraries that have native code and may require a tad more setup.

**Comment by pombredanne** [comment]
note that I have used `pip install --user` ... as I always use a virtualenv :] ... so this may not have been must tested.

**Comment by pombredanne** [comment]
We dropped depending on six... and we no longer support Python 2.7. I am closing this now as I think this is no longer relevant.
