### ISSUE TITLE
Return null license_expression in maven package parser

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1344]
When parsing and returning a maven package using http://repo1.maven.org/maven2/edu/psu/swe/commons/commons-jaxrs/1.22/commons-jaxrs-1.22.pom

It returns:
 ```
  "license_expression": null,
    "declared_license": "The Apache License, Version 2.0\nhttp://www.apache.org/licenses/LICENSE-2.0.txt",
```
It should be:

>     "license_expression": "apache-2.0",
>     "declared_license": "The Apache License, Version 2.0\nhttp://www.apache.org/licenses/LICENSE-2.0.txt",

**Comment by pombredanne** [comment]
@linexb Thank you. This is an area that I am working to improve in the `improve-package-scans-and-summaries` branch that now returns instead `apache-2.0 AND unknown` and that will be further fix with a new license rule.

**Comment by linexb** [comment]
@pombredanne  Thank you. :)

**Comment by pombredanne** [comment]
Fixed and merged. Thanks!
