### ISSUE TITLE
GPL-2.0 false positive in assimp package

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1345]
https://raw.githubusercontent.com/assimp/assimp/master/contrib/zip/src/zip.c

is recognized as GPL 2 by scancode 2.9.9.post24.617d59a45 (develop branch)

     "licenses": [
        {
          "key": "gpl-2.0",
          "score": 66.36,
          "name": "GNU General Public License 2.0",
          "short_name": "GPL 2.0",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-2.0.html",
          "text_url": "http://www.gnu.org/licenses/gpl-2.0.txt",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-2.0",
          "spdx_license_key": "GPL-2.0-only",
          "spdx_url": "https://spdx.org/licenses/GPL-2.0-only",
          "start_line": 2,
          "end_line": 8,
          "matched_rule": {
            "identifier": "gpl-2.0_168.RULE",
            "license_expression": "gpl-2.0",
            "licenses": [
              "gpl-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false
          }
        }
      ],

This is incorrect. It seems that the license declaration is only using a part of the GPL2 license text:

/*
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

**Comment by pombredanne** [comment]
Thanks! this is a bug, though the detection is not exact as it should:
```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "2.9.9.post44.633499c.dirty.20190129155546",
      "options": {
        "input": "zip_not_gpl.c",
        "--json-pp": "-",
        "--license": true,
        "--license-diag": true,
        "--license-text": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2019-01-31T095413.532040",
      "end_timestamp": "2019-01-31T095417.934156",
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "zip_not_gpl.c",
      "type": "file",
      "licenses": [
        {
          "key": "gpl-2.0",
          "score": 66.36,
          "name": "GNU General Public License 2.0",
          "short_name": "GPL 2.0",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-2.0.html",
          "text_url": "http://www.gnu.org/licenses/gpl-2.0.txt",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-2.0",
          "spdx_license_key": "GPL-2.0-only",
          "spdx_url": "https://spdx.org/licenses/GPL-2.0-only",
          "start_line": 2,
          "end_line": 8,
          "matched_rule": {
            "identifier": "gpl-2.0_168.RULE",
            "license_expression": "gpl-2.0",
            "licenses": [
              "gpl-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 110,
            "matched_length": 73,
            "match_coverage": 66.36,
            "rule_relevance": 100
          },
          "matched_text": "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR\n * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,\n * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\n * OTHER DEALINGS IN THE SOFTWARE"
        }
      ],
      "license_expressions": [
        "gpl-2.0"
      ],
      "scan_errors": []
    }
  ]
}
```

**Comment by pombredanne** [comment]
Merge in develop. Thank you as always for reporting these precious findings!
