### ISSUE TITLE
Validate --format parameter earlier

### ISSUE THREAD

**Issue by ened** [nexB/scancode-toolkit#135]
Ensure to run basic validation for `--format` parameter before starting the scan.

"Does the file exist && is it readable" should suffice.

**Comment by pombredanne** [comment]
The new function in https://github.com/nexB/scancode-toolkit/commit/68ae00600d35fd194e9c7a07f8ca855015a592c0#diff-1e37ecfb9a8c3fccd8ecdfb2ce51f591L209 is used as a click callback to validate the format early.
But I would rather kill the custom template feature entirely together with the plain html output as explained in #324

**Comment by pombredanne** [comment]
So I am closing this as this will be eventually merged.
