### ISSUE TITLE
Consider new category for modified FOSS licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1351]
There are times when an existing FOSS license is modified it a little (see some Apache modifications for instance). It could make sense to report this as a new category

**Comment by LeChasseur** [comment]
Marking them as "variant" or "aberrant version" would be helpful.

**Comment by pombredanne** [comment]
Some examples of franken-apache-2.0 licenses
- http://www.sql-workbench.net/manual/license.html
- https://github.com/palantir/blueprint/blob/develop/LICENSE
