### ISSUE TITLE
Distinguish plain public domain dedication from US government public domain (e.g. 17 U.S. Code § 105)

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1354]
It would be good to distinguish plain public domain dedications from a US Government public domain under 17 U.S. Code § 105.
This could be done with a category, or probably better with its own license key.
This is a follow up of @LeChasseur in https://github.com/nexB/scancode-toolkit/issues/1352#issuecomment-460812449

> it would be helpful to distinguish cases in which the author has dedicated the work to the public domain and other cases in which a program is public domain because it is a govermental work . The reason is that govermental works might be copyright protected in other countries

Here are the rules that may need some review and assignment to a new license key (I suggest `us-govt-public-domain` )

- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/public-domain_116.RULE
- these are combined with a MIT and may need to be requalified https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/public-domain_and_mit.RULE and https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/dshell_mit_or_public.RULE

- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/public-domain-disclaimer_26.RULE
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/public-domain-disclaimer_27.RULE
-  https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/public-domain-disclaimer_28.RULE
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/public-domain_or_free-unknown_usgov.RULE
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/dshell_public.RULE
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/unknown_22.RULE

These use a well defined license key and should be OK: 

- `nist-pd` which is NOT recognized IMHO outside the US 
  - https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/nist-pd_1.RULE
  - https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/nist-pd_4.RULE
  - https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/nist-pd_5.RULE
- `cc0` which is recognized IMHO outside the US
  - https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/cc0-1.0_us_govt.RULE
  - https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/cc0-1.0_us_gov.RULE

And some common ways the US code is referenced: we could use this for new rules:
- under 17 USC 105.
- Section 105 of the Copyright Act of 1976
- Untied States Code Section 105
- title 17 Section 105

**Comment by pombredanne** [comment]
@lechasseur @DennisClark input welcomed. I suggested quite simply to create a new license key `us-govt-public-domain` for these. Any objections? @lechasseur that way you would know when a public domain may be problematic outside of the US as this might mean no license is granted at all. (I assume this was your requirement)

**Comment by DennisClark** [comment]
@pombredanne   Please create a new license key `us-govt-public-domain` and let me know what the text of it is going to be.

**Comment by pombredanne** [comment]
@DennisClark `us-govt-public-domain` is created and is in the PR #1522
@LeChasseur Existing samples  that were for such public domain dedication have been tagged accordingly so you will know if this is a US Gov't thing or not. 
See https://github.com/nexB/scancode-toolkit/blob/improved-license-rules-04-29/src/licensedcode/data/licenses/us-govt-public-domain.LICENSE for an example

**Comment by pombredanne** [comment]
This is all merged in develop. Closing
