### ISSUE TITLE
False-positives for Nokia Open Source License

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#1358]
Scanning [javassist](https://github.com/jboss-javassist/javassist) results in several false-positives for the Nokia Open Source License (tested with both ScanCode 2.9.7 and latest `develop`). E.g. scanning [file "Stmnt.java" from release 3.20.0 GA](https://github.com/jboss-javassist/javassist/blob/rel_3_20_0_ga/src/main/javassist/compiler/ast/Stmnt.java#L5-L7) triggers the false-positive in the linked lines although the  text clearly says "Mozilla Public License".

**Comment by pombredanne** [comment]
Fixed with https://github.com/nexB/scancode-toolkit/commit/f2eef03f9ed9f072c4662194f9ed6ce1e3871fb5 
https://github.com/nexB/scancode-toolkit/commit/60f726fccdb42b7f96a1379effc2702f8442142e
https://github.com/nexB/scancode-toolkit/commit/ad76a54bb1dce388e18c19c70886a6216c6d1f6a
