### ISSUE TITLE
ScanCode should be able to parse Chef metadata.json files

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1361]
Metadata for a cookbook can be found in metadata.json files and sometimes metadata.rb. These files are in the root of a cookbook project folder.

**Comment by JonoYang** [comment]
Overview of the Chef metadata files: https://docs.chef.io/config_rb_metadata.html

metadata is added in metadata.rb and compiled to metadata.json

**Comment by JonoYang** [comment]
@pombredanne If we find a `metadata.rb` file in a Chef cookbook, should we attempt to parse it if the cookbook does not have a `metadata.json` available?

**Comment by pombredanne** [comment]
Merged. Thanks!
