### ISSUE TITLE
VirtualCodebase should be able to import a scan where not every resource has a parent

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1363]
When we create a VirtualCodebase from a scan, we assume every Resource has a parent and that is not always the case. Some Resources are pruned from a scan using the `--ignore` option or are removed for privacy purposes. ScanCode should create the parents for these Resources so the scan can be loaded.

**Comment by JonoYang** [comment]
@pombredanne 

Currently, to create a VirtualCodebase from a scan, the Resources of the scan must follow these conditions:

- The first Resource in the scan needs to be the root
- Each subsequent Resource needs to be in top-down order (where the paths start from the root directory down)
- No parent Resource can be missing from the scan

I have created a function that returns a parent resource for a given path if the parent Resource exists. If it doesn't exist, it will recursively create the parent resource for a given path and return it.

This approach works for lightly damaged scans, where:

- The first Resource is the root
- Each Resource's path is base off the root path

This approach doesn't work in the cases where we are missing the root resource in the scan. For example, we cannot import a scan where the `--only-findings` options was used because `--only-findings` only reports the files that have findings and removes all other Resources that do not (the root Resource is removed since directories do not contain findings). 

Are we expected to be able to import scans that do not contain a root Resource or where the root Resource is not the first Resource in the scan? How damaged can a scan be before we refuse to create a VirtualCodebase from it?

**Comment by pombredanne** [comment]
Good points. The `--only-findings` is really the evil there I guess. How complex would it be to have something along these lines, ignoring for now how this would be plugged in the CLI?

We could have a codebase "repair" function that would take a damaged "files" list then add missing parent directories and ensure that all resources have all the same attributes (e.g. from looking at all "files" to collect each attribute (name, type). And if there is no common root, then a synthetic root named "root" would be created. Finally the list would be sorted in the proper expected and stable order and then fed to create a codebase.

An alternative design would be to evolve the whole Codebase code to support doing this on the fly... but IMHO that would be detrimental to the actual physical non-virtual codebase performance and will likely make the code messy.

So having something that takes a list or iterable of "files" and returns the same but usable for VC usage seems the simplest and most testable approach at first.  It could also be used for possible future codebase "type" conversion (such as getting for instance some iterable from a CSV or from an SPDX document or from a `find . -ls` or some other representation of a filesystem and "repair" these such that they can be used as the input to a VC)

Note that I am NOT talking about resources at all here... just a list of the basic data structures available from reloading a scan in and out. And use that as a front before creating the codebase.

**Comment by JonoYang** [comment]
@pombredanne 

> How complex would it be to have something along these lines, ignoring for now how this would be plugged in the CLI?

Can you elaborate? Are you referring to creating missing parents when importing an incomplete scan? If so, I've done that here during VirtualCodebase creation time (https://github.com/nexB/scancode-toolkit/commit/a3fe9f1b8bbb0acfb1a93010e53cb9baa61d4ace#diff-a8e64273dc1cb3ca2a1ff8127a989c6cR1416) This doesn't work when we don't have the root as the first Resource of the scan.

**Comment by JonoYang** [comment]
This has been fixed in #1406
