### ISSUE TITLE
Add license detection rules for badge URLs

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1380]
See @lukas-h https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba ... these URL will/do show up in README eventually and need to be properly detected: we should verify that there is one rule for every badge and URLs combos as well as license names translation. 

- There is also
- In German from the same author: https://gist.github.com/lukas-h/40df8fcbac877be380591787e4af996c
- @Gaboso in Portuguese https://gist.github.com/Gaboso/fb5b15558959cecbf16a0c8993577a57
- @JethroLee in Chinese https://gist.github.com/JethroLee/dd777676d30064fa62a65f514d23f601
- @Helmasaur in French https://gist.github.com/Helmasaur/fb8ca2c08131c58341d443b43672a1f5

See also https://licensebuttons.net/

**Comment by mriiinal** [comment]
Is there a patch in the working for this issue? If not, I can work on this.

**Comment by pombredanne** [comment]
@mriiinal none is working on this. Go for it! Thank you!

**Comment by mriiinal** [comment]
@pombredanne I've created a pull request #1401 , please review.

**Comment by i-m-vivek** [comment]
hi, I am new to open source can I work on this.

**Comment by pombredanne** [comment]
@i-m-vivek thanks!
There is a PR above by @mnpw that should guide you... but it could be that this is all done? 
 @mnpw do you recall what was left to do?

**Comment by i-m-vivek** [comment]
@mnpw if something is left please tell me. I will be happy to help.

**Comment by mnpw** [comment]
@pombredanne you can close this issue, from what I recall, it has already been completed. Thanks @i-m-vivek, please have a look at other open issues.

**Comment by lukas-h** [comment]
@pombredanne Thanks for being mentioned in such a useful project.

**Comment by pombredanne** [comment]
All merged in develop now. Thank you all!
