### ISSUE TITLE
aes-128-3.0 detected as public-domain

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1382]
```
/**
 * rijndael-alg-fst.c
 *
 * @version 3.0 (December 2000)
 *
 * Optimised ANSI C code for the Rijndael cipher (now AES)
 *
 * @author Vincent Rijmen <vincent.rijmen@esat.kuleuven.ac.be>
 * @author Antoon Bosselaers <antoon.bosselaers@esat.kuleuven.ac.be>
 * @author Paulo Barreto <paulo.barreto@terra.com.br>
 *
 * This code is hereby placed in the public domain.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
```
The above text is detected as `public-domain-disclaimer`
The correct license should be `aes-128-3.0` instead

**Comment by pombredanne** [comment]
IMHO this is correct and I reckon this can be confusing as I deleted this key in the past as opposed to mark it as deprecated as I should have (and I will fix this).  The explanation is here https://github.com/nexB/scancode-toolkit/pull/1317#discussion_r242167179:

> there is no aes-128-3.0 ... there is instead a public-domain-disclaimer which is a public domain dedication with a warranty disclaimer.

@DennisClark what's your take?

**Comment by mjherzog** [comment]
I think that we should be tracking more specific public domain notices because there are distinct public domain statements and the specific text may affect the viability of a public domain notice in some jurisdictions.

**Comment by DennisClark** [comment]
I think that there is enough extra information in aes-128-3.0 
* warranty disclaimer
* authors
* acknowledgments
to justify keeping it as a license.

**Comment by pombredanne** [comment]
ok, so I will reinstate this license alright.

**Comment by pombredanne** [comment]
@chinyeungli this has been fixed in devel
