### ISSUE TITLE
something wrong with  version of six

### ISSUE THREAD

**Issue by arthur657834** [nexB/scancode-toolkit#1386]
sudo pip list | grep -i six
pdfminer.six                     20181108   
six                              1.12.0 

sudo pip list | grep -i scancode
scancode-toolkit                 3.0.2   

22:24:08 + scancode --license --copyright --package --html=scancode-2019-02-21.html --verbose ./test
22:24:08 Traceback (most recent call last):
22:24:08   File "/usr/bin/scancode", line 7, in <module>
22:24:08     from scancode.cli import scancode
22:24:08   File "/usr/lib/python2.7/site-packages/scancode/cli.py", line 206, in <module>
22:24:08     plugin_classes, plugin_options = PluginManager.load_plugins()
22:24:08   File "/usr/lib/python2.7/site-packages/plugincode/__init__.py", line 190, in load_plugins
22:24:08     mgr_setup = manager.setup()
22:24:08   File "/usr/lib/python2.7/site-packages/plugincode/__init__.py", line 217, in setup
22:24:08     self.manager.load_setuptools_entrypoints(entrypoint)
22:24:08   File "/usr/lib/python2.7/site-packages/pluggy/manager.py", line 268, in load_setuptools_entrypoints
22:24:08     plugin = ep.load()
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2259, in load
22:24:08     if require: self.require(env, installer)
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2272, in require
22:24:08     working_set.resolve(self.dist.requires(self.extras),env,installer)))
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
22:24:08     requirements.extend(dist.requires(req.extras)[::-1])
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2489, in requires
22:24:08     dm = self._dep_map
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2700, in _dep_map
22:24:08     self.__dep_map = self._compute_dependencies()
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2724, in _compute_dependencies
22:24:08     parsed = next(parse_requirements(distvers))
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 30, in <lambda>
22:24:08     next = lambda o: o.next()
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2839, in parse_requirements
22:24:08     line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
22:24:08   File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2807, in scan_list
22:24:08     raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
22:24:08 ValueError: ('Expected version spec in', 'six ~=1.4', 'at', ' ~=1.4')

**Comment by pombredanne** [comment]
@arthur657834 thank you for the report and sorry for the inconvenience!
Can you tell how you installed scancode?
Did you use a release tarball? Or a pip install? did you had already a previous version installed? Any special reason why you used a sudo system install?

**Comment by arthur657834** [comment]
how:
sudo pip install scancode-toolkit


python --version
Python 2.7.5

uname -a
Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

i had not install scancode-toolkit before

**Comment by pombredanne** [comment]
@arthur657834 which exact version of which Linux distro do you run such that this can be reproduced in a VM? I feel like this is not directly a ScanCode issue per se, but rather a Linux issue in some other system package that installed six too.

Otherwise, can you try instead to use a release tarball at https://github.com/nexB/scancode-toolkit/releases/tag/v3.0.2 ?

Fetch https://github.com/nexB/scancode-toolkit/releases/download/v3.0.2/scancode-toolkit-3.0.2.tar.bz2 and extract. Then run your scancode command from within this extracted directory.

**Comment by arthur657834** [comment]
cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

use a release tarball,  there did not occur the problem,thank you for you help!

**Comment by pombredanne** [comment]
At this stage we no longer depend on six directly... I assume this is no longer an issue. Closing.
