### ISSUE TITLE
Adopt a simple issue template

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1390]
I am not sure I like them, but they can provide decent guidance for a ticket submitter.
See @majurg https://github.com/nexB/scancode-workbench/blob/develop/ISSUE_TEMPLATE.md for an example  

Any feedback?

**Comment by majurg** [comment]
I think we could have something like this is sconcode-toolkit. 

I think we should keep it shorter than scancode-workbench though; imo I think that none is too long for most issues.

**Comment by pombredanne** [comment]
@majurg PR welcomed :P

**Comment by pombredanne** [comment]
@majurg thanks! closing
