### ISSUE TITLE
Filter the license summary view in the html-app to show the data from a selected directory or file.

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#140]
**Narrative**: For the html-app, I want to see the a license summary based on where I select in the tree view.
**Context**: I want to perform a quick calculation of a license percentage based on the total number of files scanned and a specific license count for a selected directory or file
**Acceptance Criteria:** 
        - *Scenario 1:* When a user selects a directory or file, the license summary chart would show the results for selected directory or file licenses.

**Comment by nspsjsu** [comment]
Reviewed. Issue ready to close.

**Comment by jdaguil** [comment]
thanks @nspsjsu
