### ISSUE TITLE
Improve storage of package declared licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1403]
### Description
The declared license of a package is what we find in a package manifest license-related fields.
Today we take the values of fields and use a simple line separation.
Instead we should keep the field names and store that as JSON too, keeping some of the original structure such that we can a better determination/normalization of the license when we populate the `license_expression` field.

For instance this is a Maven POM snippet:
```
<licenses>
    <license>
        <name>BSD</name>
        <url>http://www.jcraft.com/jzlib/LICENSE.txt</url>
    </license>
</licenses>
```
and an npm package.json snippet (rather weird as it has both a legacy and new style of license tags:
```
{
  "license": "Apache-2.0",
...
  "licenses": [
    {
      "type": "Apache 2.0",
      "url": "https://github.com/spenceralger/grunt-esvm/blob/master/LICENSE.md"
    }
  ],
...
}

```
We should in these cases store and report something such as:
- maven: `"name": "BSD, "url": http://www.jcraft.com/jzlib/LICENSE.txt"`
- npm: `"license": "Apache-2.0", "type": "Apache 2.0", "url": "https://github.com/spenceralger/grunt-esvm/blob/master/LICENSE.md"
`

**Comment by vaibhav-k3** [comment]
Hello , i am new to Scancode Repo and i would like to work on this issue to start to learn about Scancode

**Comment by pombredanne** [comment]
@vaibhav-k3 thanks! so each Package subclass is fed a `declared_license` [string](https://github.com/nexB/scancode-toolkit/blob/c6d1de1d97da1b6ba6d76edae95d30dbe5aa1206/src/packagedcode/models.py#L446)  by a manifest parser. This happens [here](https://github.com/nexB/scancode-toolkit/blob/c6d1de1d97da1b6ba6d76edae95d30dbe5aa1206/src/packagedcode/maven.py#L976) for Maven and [here](https://github.com/nexB/scancode-toolkit/blob/c6d1de1d97da1b6ba6d76edae95d30dbe5aa1206/src/packagedcode/npm.py#L266) for npm for instance ... there are more places of course as each maifest parser does this eventually.

**Comment by vaibhav-k3** [comment]
@pombredanne , please review PR #1405

**Comment by linexb** [comment]
We have done maven, pypi and npm packages now, and we will develop further more for other types.

**Comment by pombredanne** [comment]
This has been merged. Thanks!
