### ISSUE TITLE
Incorrect 'npl-1.1' detected in RST files

### ISSUE THREAD

**Issue by blsaws** [nexB/scancode-toolkit#1408]
### Description
scancode incorrectly detects "npl-1.1" licenses in RST files.

This was found when running scancode against repo https://github.com/acumos/image-classification via command `scancode-toolkit-3.0.2/scancode --license --copyright --json=image-classification.json image-classification`

### System configuration
* verified on Ubuntu 16.04 LTS and MacOS Mojave 10.14.2 (18C54)
* using scancode-toolkit-3.0.2
* installed via wget from https://github.com/nexB/scancode-toolkit/releases/download/v3.0.2/scancode-toolkit-3.0.2.zip

**Comment by pombredanne** [comment]
@blsaws thank you for this one too++. Note that when you have several errors from the same package scan, a single ticket can work OK too if this is less work for you.

Your bug  should be fixed with the latest push I made to this branch/PR https://github.com/nexB/scancode-toolkit/pull/1384

**Comment by pombredanne** [comment]
Also fixed and merged in develop. Thank you ++ for this other report.
