### ISSUE TITLE
Incorrect 'nokos-1.0a' detected

### ISSUE THREAD

**Issue by blsaws** [nexB/scancode-toolkit#1409]
### Description
scancode incorrectly detects "nokos-1.0a" license

This was found when running scancode against repo https://github.com/acumos/image-classification via command `scancode-toolkit-3.0.2/scancode --license --copyright --json=image-classification.json image-classification`

### System configuration

- verified on Ubuntu 16.04 LTS and MacOS Mojave 10.14.2 (18C54)
- using scancode-toolkit-3.0.2
- installed via wget from https://github.com/nexB/scancode-toolkit/releases/download/v3.0.2/scancode-toolkit-3.0.2.zip

**Comment by pombredanne** [comment]
@blsaws Thank you for the report!
It should be fixed with the latest push I made to this branch/PR https://github.com/nexB/scancode-toolkit/pull/1384

**Comment by pombredanne** [comment]
Fixed and merged in develop. Thank you ++ for this report.
