### ISSUE TITLE
Duplicated license texts or rules

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#141]
The following are duplicated texts or rules.
Quite a few SPDX texts are dupes of the reference license text.
We should probably not keep both in these cases.

Another class are duplicated rules. These should be removed either keep one RULE or removing the RULE that duplicates a LICENSE.

| file               | duplicate            |
|------------------|-----------------------|
|abstyles.SPDX|abstyles.LICENSE|
|adobe-glyph.SPDX|adobe-glyph.LICENSE|
|adsl.SPDX|adsl.LICENSE|
|afl-2.1.SPDX|afl-2.1.LICENSE|
|afmparse.SPDX|afmparse.LICENSE|
|afpl-8.0.SPDX|afpl-8.0.LICENSE|
|agpl-1.0_2.RULE|agpl-1.0_1.RULE|
|agpl-1.0.SPDX|agpl-1.0.LICENSE|
|agpl-2.0.RULE|agpl-2.0_2.RULE|
|agpl-3.0_8.RULE|agpl-3.0.SPDX|
|allegro-4.SPDX|allegro-4.LICENSE|
|amdplpa.SPDX|amdplpa.LICENSE|
|antlr-pd.SPDX|antlr-pd.LICENSE|
|apache-1.0_2.RULE|apache-1.0_3.RULE|
|apache-1.0.SPDX|apache-1.0.LICENSE|
|apache-1.1_21.RULE|apache-1.1.SPDX|
|apsl-1.0.SPDX|apsl-1.0.LICENSE|
|apsl-1.1.SPDX|apsl-1.1.LICENSE|
|artistic-clarified.SPDX|artistic-clarified.LICENSE|
|bahyph.SPDX|bahyph.LICENSE|
|barr-tex.SPDX|barr-tex.LICENSE|
|beerware.SPDX|beerware.LICENSE|
|bittorrent-1.0.SPDX|bittorrent-1.0.LICENSE|
|bittorrent-1.1.RULE|bittorrent-1.1.LICENSE|
|boost-1.0.SPDX|boost-1.0.LICENSE|
|borceux.SPDX|borceux.LICENSE|
|broadcom-cfe_1.RULE|broadcom-cfe.LICENSE|
|bsd-2-clause-netbsd.RULE|bsd-2-clause-netbsd.LICENSE|
|bsd-ack.SPDX|bsd-ack.LICENSE|
|bsd-new_19.RULE|bsd-new_sup.RULE|
|bsd-new_23.RULE|bsd-new_29.RULE|
|bsd-new_58.RULE|bsd-new.LICENSE|
|bsd-new.SPDX|bsd-new.LICENSE|
|bsd-original-uc-1990.RULE|bsd-original-uc-1990.LICENSE|
|bsd-original.SPDX|bsd-original.LICENSE|
|bsd-protection.SPDX|bsd-protection.LICENSE|
|bsd-simplified.SPDX|bsd-simplified.LICENSE|
|bzip2-libbzip-2010.SPDX|bzip2-libbzip-2010.LICENSE|
|caldera.SPDX|caldera.LICENSE|
|cc-by-1.0_2.RULE|cc-by-1.0_1.RULE|
|cc-by-nc-nd-1.0.SPDX|cc-by-nc-nd-1.0.LICENSE|
|cddl-1.0_13.RULE|cddl-1.0_12.RULE|
|cddl-1.0_14.RULE|cddl-1.0_10.RULE|
|cddl-1.1.SPDX|cddl-1.1.LICENSE|
|cecill-1.0.SPDX|cecill-1.0.LICENSE|
|cecill-2.1_en_2.RULE|cecill-2.1.LICENSE|
|cecill-b.SPDX|cecill-b.LICENSE|
|cecill-c.SPDX|cecill-c.LICENSE|
|cmu-uc.SPDX|cmu-uc.LICENSE|
|cnri-python-1.6.1.SPDX|cnri-python-1.6.1.LICENSE|
|crossword.SPDX|crossword.LICENSE|
|cube.SPDX|cube.LICENSE|
|curl_4.RULE|curl_6.RULE|
|curl_7.RULE|curl.RULE|
|d-fsl-1.0-de.SPDX|d-fsl-1.0-de.LICENSE|
|d-zlib_1.RULE|d-zlib.LICENSE|
|diffmark.SPDX|diffmark.LICENSE|
|dotseqn.SPDX|dotseqn.LICENSE|
|dsdp.SPDX|dsdp.LICENSE|
|dvipdfm.SPDX|dvipdfm.LICENSE|
|efl-1.0.SPDX|efl-1.0.LICENSE|
|egenix-1.1.0.SPDX|egenix-1.1.0.LICENSE|
|elib-gpl.RULE|elib-gpl_2.RULE|
|epl-1.0.SPDX|epl-1.0.LICENSE|
|erlangpl-1.1.SPDX|erlangpl-1.1.LICENSE|
|eurosym.SPDX|eurosym.LICENSE|
|fastcgi-devkit.SPDX|fastcgi-devkit.LICENSE|
|frameworx-1.0.SPDX|frameworx-1.0.LICENSE|
|freetype.SPDX|freetype.LICENSE|
|fsf-mit.RULE|fsf-mit.LICENSE|
|fsf-unlimited.RULE|fsf-unlimited.LICENSE|
|fsf-unlimited.SPDX|fsf-unlimited.LICENSE|
|gfdl-1.1.SPDX|gfdl-1.1.LICENSE|
|gfdl-1.2.SPDX|gfdl-1.2.LICENSE|
|gfdl-1.3.SPDX|gfdl-1.3.LICENSE|
|gl2ps.SPDX|gl2ps.LICENSE|
|glide.SPDX|glide.LICENSE|
|glulxe.SPDX|glulxe.LICENSE|
|gnuplot.SPDX|gnuplot.LICENSE|
|gpl-1.0-plus.SPDX|gpl-1.0-plus.LICENSE|
|gpl-2.0_45.RULE|gpl-2.0_44.RULE|
|gpl-2.0_62.RULE|gpl-2.0.SPDX|
|gpl-2.0-autoconf_1.RULE|gpl-2.0-autoconf_3.RULE|
|gpl-2.0-bison_3.RULE|gpl-2.0-bison.RULE|
|gpl-2.0-javascript_1.RULE|gpl-2.0-javascript_3.RULE|
|gpl-2.0-mysql-connector-odbc_1.RULE|gpl-2.0-mysql-connector-odbc.RULE|
|gpl-2.0-mysql-floss_3.RULE|gpl-2.0-mysql-floss_4.RULE|
|gpl-2.0-plus_35.RULE|gpl-2.0-plus_12.RULE|
|gpl-2.0-plus_50.RULE|gpl-2.0-plus.SPDX|
|gpl-2.0-uboot_2.RULE|gpl-2.0-uboot.RULE|
|gpl-3.0-plus_14.RULE|gpl-3.0-plus_16.RULE|
|gpl-3.0-plus_15.RULE|gpl-3.0-plus_17.RULE|
|gpl-3.0-plus_8.RULE|gpl-3.0-plus.LICENSE|
|gsoap-1.3b.SPDX|gsoap-1.3b.LICENSE|
|haskell-report.SPDX|haskell-report.LICENSE|
|ibm-pibs.SPDX|ibm-pibs.LICENSE|
|imlib2.SPDX|imlib2.LICENSE|
|indiana-extreme-1.2.RULE|indiana-extreme-1.2.LICENSE|
|intel-acpi.SPDX|intel-acpi.LICENSE|
|ipa-font.SPDX|ipa-font.LICENSE|
|jasper-2.0.SPDX|jasper-2.0.LICENSE|
|khronos_1.RULE|khronos.LICENSE|
|khronos_2.RULE|khronos.LICENSE|
|latex2e.SPDX|latex2e.LICENSE|
|lbnl-bsd.SPDX|lbnl-bsd.LICENSE|
|leptonica.SPDX|leptonica.LICENSE|
|lgpl-2.1_31.RULE|lgpl-2.1_29.RULE|
|lgpl-2.1-nokia-qt.RULE|lgpl-2.1-nokia-qt-1.1.LICENSE|
|lgpl-2.1-plus_alt.RULE|lgpl-2.1-plus.LICENSE|
|lppl-1.0.SPDX|lppl-1.0.LICENSE|
|lppl-1.1.SPDX|lppl-1.1.LICENSE|
|lppl-1.2.SPDX|lppl-1.2.LICENSE|
|lppl-1.3a.SPDX|lppl-1.3a.LICENSE|
|makeindex.SPDX|makeindex.LICENSE|
|martin-birgmeier.RULE|martin-birgmeier.LICENSE|
|mit_2.RULE|mit_url.RULE|
|mit-ack.SPDX|mit-ack.LICENSE|
|mit-no-false-attribs.SPDX|mit-no-false-attribs.LICENSE|
|mit-old-style_3.RULE|mit-old-style.RULE|
|mpl-1.0.SPDX|mpl-1.0.LICENSE|
|mpl-2.0-no-copyleft-exception.SPDX|mpl-2.0-no-copyleft-exception.LICENSE|
|mpl-2.0.SPDX|mpl-2.0.LICENSE|
|mtll.SPDX|mtll.LICENSE|
|mup.SPDX|mup.LICENSE|
|mx4j_2.RULE|mx4j.LICENSE|
|naumen.SPDX|naumen.LICENSE|
|nbpl-1.0.SPDX|nbpl-1.0.LICENSE|
|netcdf.SPDX|netcdf.LICENSE|
|nlpl.SPDX|nlpl.LICENSE|
|nokia_qt_lgpl_gpl.RULE|qpl-1.0_1.RULE|
|noweb.SPDX|noweb.LICENSE|
|nrl.SPDX|nrl.LICENSE|
|ntpl.SPDX|ntpl.LICENSE|
|odbl-1.0.SPDX|odbl-1.0.LICENSE|
|ofl-1.0.SPDX|ofl-1.0.LICENSE|
|opengroup.SPDX|opengroup.LICENSE|
|openldap-1.1.SPDX|openldap-1.1.LICENSE|
|openldap-1.2.SPDX|openldap-1.2.LICENSE|
|openldap-1.3.SPDX|openldap-1.3.LICENSE|
|openldap-1.4.SPDX|openldap-1.4.LICENSE|
|openldap-2.0.1.SPDX|openldap-2.0.1.LICENSE|
|openldap-2.0.SPDX|openldap-2.0.LICENSE|
|openldap-2.1.SPDX|openldap-2.1.LICENSE|
|openldap-2.2.1.SPDX|openldap-2.2.1.LICENSE|
|openldap-2.2.2.SPDX|openldap-2.2.2.LICENSE|
|openldap-2.2.SPDX|openldap-2.2.LICENSE|
|openldap-2.3.SPDX|openldap-2.3.LICENSE|
|openldap-2.4.SPDX|openldap-2.4.LICENSE|
|openldap-2.5.SPDX|openldap-2.5.LICENSE|
|openldap-2.6.SPDX|openldap-2.6.LICENSE|
|openldap-2.7.SPDX|openldap-2.7.LICENSE|
|openldap-2.8.SPDX|openldap-2.8.LICENSE|
|openvpn-as-eula.RULE|openvpn-as-eula.LICENSE|
|osl-1.1.SPDX|osl-1.1.LICENSE|
|osl-2.0.SPDX|osl-2.0.LICENSE|
|php-3.0.SPDX|php-3.0.LICENSE|
|php-3.01.SPDX|php-3.01.LICENSE|
|psfrag.SPDX|psfrag.LICENSE|
|psutils.SPDX|psutils.LICENSE|
|python.SPDX|python.LICENSE|
|qhull.SPDX|qhull.LICENSE|
|rdisc.SPDX|rdisc.LICENSE|
|rpl-1.1.SPDX|rpl-1.1.LICENSE|
|saxpath.SPDX|saxpath.LICENSE|
|scea-1.0.SPDX|scea-1.0.LICENSE|
|snia.SPDX|snia.LICENSE|
|sugarcrm-1.1.3.SPDX|sugarcrm-1.1.3.LICENSE|
|sun-bcl-11-06_1.RULE|sun-bcl-11-06.LICENSE|
|sun-bcl-11-07_1.RULE|sun-bcl-11-07.LICENSE|
|sun-entitlement-03-15.RULE|sun-entitlement-03-15.LICENSE|
|sun-sissl-1.2.SPDX|sun-sissl-1.2.LICENSE|
|sunpro.RULE|sunpro.LICENSE|
|swig.RULE|swig.LICENSE|
|swl.SPDX|swl.LICENSE|
|tcl.SPDX|tcl.LICENSE|
|torque-1.1.SPDX|torque-1.1.LICENSE|
|tosl.SPDX|tosl.LICENSE|
|unicode-tou.SPDX|unicode-tou.LICENSE|
|unlicense.SPDX|unlicense.LICENSE|
|uoi-ncsa.SPDX|uoi-ncsa.LICENSE|
|vbAccelerator.RULE|vbAccelerator.LICENSE|
|vostrom.SPDX|vostrom.LICENSE|
|wsuipa.SPDX|wsuipa.LICENSE|
|wtfpl-1.0_2.RULE|wtfpl-1.0.LICENSE|
|wxwindows.SPDX|wxwindows.LICENSE|
|x11-hanson.RULE|x11-hanson.LICENSE|
|x11-tiff.SPDX|x11-tiff.LICENSE|
|x11-x11r5_1.RULE|x11-x11r5.LICENSE|
|x11-xconsortium.RULE|x11-xconsortium.LICENSE|
|xfree86-1.1.SPDX|xfree86-1.1.LICENSE|
|xskat.SPDX|xskat.LICENSE|
|ypl-1.0.SPDX|ypl-1.0.LICENSE|
|zed.SPDX|zed.LICENSE|
|zend-2.0.SPDX|zend-2.0.LICENSE|
|zimbra-1.3.SPDX|zimbra-1.3.LICENSE|
|zlib_blast2.RULE|zlib_variant.RULE|
|zlib_variant2.RULE|zlib_variant.RULE|
|zlib-acknowledgement.SPDX|zlib-acknowledgement.LICENSE|

**Comment by mjherzog** [comment]
So we remove .LICENSE in favor of .SPDX, but why remove .LICENSE in favor of .RULE?

**Comment by pombredanne** [comment]
@mjherzog actually I would be more in favor of removing the SPDX or rather replacing them by a pointer to the main .LICENSE text when this is a dupe. The rationale being that all licenses have .LICENSE text butr only some are in the SPDX list.
One way or the other does not matter too much in anycase as they would both be exposed anyway.

As for .RULE, these would just be removed (and the .LICENSE would never be removed)

**Comment by pombredanne** [comment]
This is all fixed and the checks are now done automatically with #86
