### ISSUE TITLE
lgpl-2.1-plus identified as gpl-2.0-plus

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#1418]
The scan of [lxc-2.1.1.tar.gz](https://linuxcontainers.org/downloads/lxc/lxc-2.1.1.tar.gz) misidentifies two `lgpl-2.1-plus` files as `gpl-2.0-plus`: `/lxc-2.1.1/src/lxc/storage/storage_utils.c` and `/lxc-2.1.1/src/lxc/storage/storage_utils.h`.

**Comment by pombredanne** [comment]
This is fixed and merged in develop. Thank you ++ for the report!
