### ISSUE TITLE
gpl-2.0-plus identified as agpl-3.0

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#1419]
The scan of [systemtap-3.1.tar.gz](https://sourceware.org/systemtap/ftp/releases/systemtap-3.1.tar.gz) misidentifies various `gpl-2.0-plus` files as `agpl-3.0`, e.g., `cmdline.cxx` and `cmdline.h`.

**Comment by pombredanne** [comment]
This is fixed and merged in develop. Thank you ++ for the report!
