### ISSUE TITLE
I have installed scancode-toolkit-2.2.1, I want to update it to the latest version. Is it just like a new installation? Also which will be the preferred version, is it 3.0.0 or 3.0.2

### ISSUE THREAD

**Issue by ChinnuJose** [nexB/scancode-toolkit#1438]
### Description
Please leave a brief discription of the bug or feature request:
* if reporting a bug, tell us how to reproduce the issue.

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by ChinnuJose** [comment]
It's not a bug, but a query for installing Scan code. 

I am running on Linux. And need to know if the upgrade is just like a fresh installation.

**Comment by pombredanne** [comment]
@ChinnuJose you wrote
> I have installed scancode-toolkit-2.2.1, I want to update it to the latest version. Is it just like a new installation? Also which will be the preferred version, is it 3.0.0 or 3.0.2 

There is no "upgrade" procedure ... just make a new installation in a new separate directory (not over the older installation) ... and the best version is the 3.0.2 for sure.
Thank you for using ScanCode!

**Comment by pombredanne** [comment]
@ChinnuJose did this work for you? If so feel free to close.
Thanks!

**Comment by ChinnuJose** [comment]
Yes, thank you

**Comment by pombredanne** [comment]
OK, I am closing this! Tell us if you have any issues, bugs or else. And thank you for using ScanCode!
