### ISSUE TITLE
Scan combining plug-in

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#1439]
It would be nice to extend the functionality of `--from-json` or have an additional plug-in that takes in n-number of scancode JSON scan files, concatenates them, and then outputs a single scan file JSON. 

This newly combined scan should have some virtual root location where its children are the scan root locations for all the other scans.

**Comment by DennisClark** [comment]
just a thought -- perhaps this could be implemented as a feature in scancode-workbench, where it might be able to take advantage of the underlying database.

**Comment by majurg** [comment]
@DennisClark Yes, that is a possibility. However, ScanCode outputs are used in a verity of different places (deltacode, DJE package import etc) and this could be useful for them as well.

**Comment by pombredanne** [comment]
This has been merged. Thanks!

**Comment by pombredanne** [comment]
This is merged and working. Thanks!
