### ISSUE TITLE
Review and refine "XFAIL" license detection tests

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1444]
### Description
There are several data-driven license detection tests that have been added recently from external sources and not yet reviewed and marked as "expected failure"  and that will be returned as XFAIL in a pytest run.

We should review each of these and either update the test or add new rules as needed

**Comment by Abhishek-Dev09** [comment]
Yes, some license does not passed with TestSlicDataDriven test such as cubeb_resampler.cpp, decnumber.h and many more.Same issues is also with TestFossLicDataDriven and TestFossTestsDataDriven which also fails some license that exist in data/more_licenses/licenses and data/more_licenses/tests respectively.I think it needs to be updated to prevent failure.

**Comment by pombredanne** [comment]
At this stage there are no xfail anymore, so we can close this.
