### ISSUE TITLE
Add support for python3 in fileutils.py

### ISSUE THREAD

**Issue by PyAgni** [nexB/scancode-toolkit#1451]
### Description
_fileutils.py_ uses exception throw and catching specifically for python2.
Since the syntax has changed in python3, it would be good to support both py2 and py3.

This will be a small part of solving issue #295

**Comment by pombredanne** [comment]
:+1: 
You could actually extend that fix through the howl codebase alright, this is rather non intrusive and non controversial.

**Comment by Abhishek-Dev09** [comment]
@pombredanne :This issues has been already solved by me. See #1430 .I have solved in commoncode module.

**Comment by PyAgni** [comment]
> +1
> You could actually extend that fix through the whole codebase alright, this is rather non intrusive and non controversial.

Yes that's the plan. Starting small, will do this in other modules too.

**Comment by PyAgni** [comment]
> @pombredanne :This issues has been already solved by me. See #1430 .I have solved in commoncode module #1452

I had not seen #1430 probably because you closed it. And if #1452 goes well and gets merged I'll work on some other issues. :)

**Comment by pombredanne** [comment]
:+1:

**Comment by arnav-mandal1234** [comment]
@PyAgni If it is okay with you can I take this issue? :)

**Comment by pombredanne** [comment]
Python 3 migration is now complete. Closing this!
