### ISSUE TITLE
MemoryError: out of memory on windows

### ISSUE THREAD

**Issue by dineshr93** [nexB/scancode-toolkit#1459]
### Description
I was just following the initial setup and ran the command in the help.
I get the out of memory error

### System configuration
For bug reports, it really helps us to know:
* Windows 10 64 bit
* https://github.com/nexB/scancode-toolkit/tree/v3.0.2
* scancode -h

`

> (scancode-toolkit-3.0.2) D:\software\scancode-toolkit-3.0.2> scancode --license --copyright --json-pp scancode_result.json samples
> Setup plugins...
> d:\software\scancode-toolkit-3.0.2\src\licensedcode\index.py:796: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   old_tid = old_dictionary_get(token)
> ERROR: failed to setup plugin: scan:licenses:
> Traceback (most recent call last):
>   File "d:\software\scancode-toolkit-3.0.2\src\scancode\cli.py", line 592, in scancode
>     plugin.setup(**kwargs)
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\plugin_license.py", line 119, in setup
>     get_index(return_value=False)
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\cache.py", line 67, in get_index
>     _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\cache.py", line 247, in get_cached_index
>     ifc.write(idx.dumps())
>   File "d:\software\scancode-toolkit-3.0.2\src\licensedcode\index.py", line 723, in dumps
>     return pickle.dumps(self, protocol=cPickle.HIGHEST_PROTOCOL)
>   File "c:\python27\Lib\pickle.py", line 1380, in dumps
>     Pickler(file, protocol).dump(obj)
>   File "c:\python27\Lib\pickle.py", line 224, in dump
>     self.save(obj)
>   File "c:\python27\Lib\pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "c:\python27\Lib\pickle.py", line 425, in save_reduce
>     save(state)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 554, in save_tuple
>     save(element)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 655, in save_dict
>     self._batch_setitems(obj.iteritems())
>   File "c:\python27\Lib\pickle.py", line 687, in _batch_setitems
>     save(v)
>   File "c:\python27\Lib\pickle.py", line 331, in save
>     self.save_reduce(obj=obj, *rv)
>   File "c:\python27\Lib\pickle.py", line 401, in save_reduce
>     save(args)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 568, in save_tuple
>     save(element)
>   File "c:\python27\Lib\pickle.py", line 286, in save
>     f(self, obj) # Call unbound method with explicit self
>   File "c:\python27\Lib\pickle.py", line 495, in save_string
>     self.memoize(obj)
>   File "c:\python27\Lib\pickle.py", line 246, in memoize
>     self.write(self.put(memo_len))
> MemoryError: out of memory
> 
> Removing temporary files...done.
> (scancode-toolkit-3.0.2) D:\software\scancode-toolkit-3.0.2>

`

**Comment by pombredanne** [comment]
@dineshr93 thank you for this report and sorry for that. This is a  bug ... I am closing this to track it all under #1458 which is the same issue and was filed briefly before your bug.
