### ISSUE TITLE
Update github wiki pages 

### ISSUE THREAD

**Issue by aj4ayushjain** [nexB/scancode-toolkit#1475]
-On the "How to : Run scan " wiki page 
 For the newer versions of scancode(--format is not supported and output file argument has to follow <OUTPUT FORMAT OPTIONS> )
1.The addition for basic usage command for newer version
2.The addition for 2 examples in newer version without format

-On the wiki page "How to :Format Scan output"
1.Similar changes on this page also

**Comment by Vishal260700** [comment]
@pombredanne  I have solved the Issue but with no Edit Access to Wiki Pages (Admin Access only), I am not able to edit them and make a pull request. On Separately cloning the Wiki also the How-To Section is Empty.

**Comment by majurg** [comment]
This is being tracked here: #1813 

Closing this.
