### ISSUE TITLE
Not able to detect GPL 2.0 license

### ISSUE THREAD

**Issue by nspsjsu** [nexB/scancode-toolkit#148]
File ref: https://github.com/qemu/qemu/blob/master/hw/block/virtio-blk.c
/*
 * Virtio Block Device
 *
 * Copyright IBM, Corp. 2007
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU GPL, version 2.  See
 * the COPYING file in the top-level directory.
 *
 */                         

No license is detected. ScanCode should be able to scan the above text and return gpl2.0 license.

**Comment by balusarakesh** [comment]
issue fixed in the latest version of scancode
