### ISSUE TITLE
 Improve declared licenses storage for Rubygems

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1480]
### Description
This is a sub ticket of #1403, the idea is let's keep the original data format of the declared license and use the class based function "compute_normalized_license"  to populate the license_expression field.

**Comment by pombredanne** [comment]
FYI I entered this https://github.com/rubygems/rubygems/issues/2713

**Comment by pombredanne** [comment]
This has been merged. Thanks
