### ISSUE TITLE
"pip install scancode-toolkit;  scancode --help" fails if future already installed

### ISSUE THREAD

**Issue by dankegel** [nexB/scancode-toolkit#1484]
### Description

Although scancode discourages installation via pip, developers still need to do it sometimes.

Currently, if some other app has done e.g. ```pip install future```, then ```pip install scancode-toolkit; scancode --help``` aborts with
```
pluggy.manager.PluginValidationError: Plugin 'json-pp' could not be loaded: (future 0.17.1 (/home/dank/.local/lib/python2.7/site-packages), Requirement.parse('future==0.16.0'))!
```

### System configuration
* ubuntu 18.04

**Comment by pombredanne** [comment]
reopening from Github autocloing this based on PR keywords.

**Comment by dankegel** [comment]
This one might have been fine to close, at least, if I was right :-)

**Comment by pombredanne** [comment]
This should be all set now.
