### ISSUE TITLE
GPL 3.0 false positive license detection in BusyBox

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#149]
The following line from BusyBox v1.17.4 depmod.c (line 71 in the file) returns an incorrect license detection of GPL 3.0.
```
if (strncmp(ptr, "gpl", 3) == 0
```

Download available at https://busybox.net/downloads/busybox-1.17.4.tar.bz2

**Comment by pombredanne** [comment]
that's interesting because it's code that checks for GPL symbols in installed Linux Kernel modules ;)

**Comment by pombredanne** [comment]
The simple resolution is to have a rule with `ptr, "gpl", 3` and no licenses in the .yml

**Comment by pombredanne** [comment]
All fixed.
