### ISSUE TITLE
extractcode fails to extract docx file - skips

### ISSUE THREAD

**Issue by a-tinsmith** [nexB/scancode-toolkit#1502]
### Description
Steps to reproduce:
* `./extractcode --verbose sample.docx`
* Nothing is extracted

I tried to debug the problem and found that:
* `OfficeDocHandler` is initialised with the properties:
`strict=True`
`filetypes=('zip archive',)`
* During the examination of the file is was determined as `Microsoft Word 2007+`
* Because of the `strict=True` the handler was **not** picked to extract the file.

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
MacOS 10.14.4
* What version of scancode-toolkit was used to generate the scan file?
`extractcode-libarchive        3.1.2`
* What installation method was used to install/run scancode? (pip/source download/other)
```bash
$ brew install icu4c
$ export PATH="/usr/local/opt/icu4c/bin:$PATH"
$ export PATH="/usr/local/opt/icu4c/sbin:$PATH"
$ pipenv install extractcode-libarchive
```

**Comment by pombredanne** [comment]
@a-tinsmith great catch: I think that this "strict=True" was originally set this way to avoid too much noise around non office documents with an office document extension. That said, if "Microsoft Word 2007+" is  reported as a type, the extraction should occur alright.
Do you have a `scancode -i` for that document so that we can see the various types detected?

**Comment by a-tinsmith** [comment]
@pombredanne , no problem. Here is the full JSON output of `scancode -i <file> --json-pp output.json`:

```json
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "3.0.2",
      "options": {
        "input": "sample-2007.docx",
        "--info": true,
        "--json-pp": "output.json"
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2019-04-04T064438.402889",
      "end_timestamp": "2019-04-04T064438.517834",
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "sample-2007.docx",
      "type": "file",
      "name": "sample-2007.docx",
      "base_name": "sample-2007",
      "extension": ".docx",
      "size": 7503,
      "date": "2019-04-03",
      "sha1": "b8e7827cf243e12ef95550ecddb93f4467abe569",
      "md5": "9ba52c7ea1028c58f7963f08cce867d9",
      "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "file_type": "Microsoft Word 2007+",
      "programming_language": null,
      "is_binary": true,
      "is_text": false,
      "is_archive": true,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "files_count": 0,
      "dirs_count": 0,
      "size_count": 0,
      "scan_errors": []
    }
  ]
}
```

**Comment by pombredanne** [comment]
thanks!
so the key are these:
```
      "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "file_type": "Microsoft Word 2007+",
```
And ideally we would want to collect these as well as extra small test files for also other office doc types. Is this something you could help with?
That would be to craft tests both on the typecode and extractcode side.

**Comment by a-tinsmith** [comment]
When I run `file -I sample.docx` in the shell it reports: `sample-2007.docx: application/zip; charset=binary`. So that would be sufficient check for extraction. I think that filetype detection in the extractcode was too precise.

I'm happy to help, but cannot promise the time. Maybe in a few days?

**Comment by pombredanne** [comment]
@a-tinsmith My bad... I was on the wrong ticket... closing this now. Thanks!
