### ISSUE TITLE
Incomplete Configuration as unable to combine parts of name of a parent directory

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [nexB/scancode-toolkit#1511]
### Description
The configuration of the project fails if the Repository is cloned in a directory which has a space in its name.

### How to Reproduce
Configuration Fails on Step 4 as described in the [CONTRIBUTING.rst](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst#development).
![Setting Up the Configuration](https://lh3.googleusercontent.com/fIy7ie1wE-y72wAQJtsadPkAGeadnNmJYp7z4yz_4XorhsmEiEAldvtJstPZVW8PSuO1lWD0YOWG "Setting Up")
```
|
|-GSoC Projies
  |
  |-scancode-toolkit
    |
    |-configure
```
![Configuration Error](https://lh3.googleusercontent.com/jqb7tYyKd8Y7mwdO4ZgAzy-Yvdi5dN5SE7AIGNucCcLDuU2CO-E7SMXHX12hOdx3kZSE4m4LbN4i "Configuration Error")

### System configuration
* OS: Linux (Ubuntu 18.04)
* Installation Method: Source Download [as per contribution Guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst#development).

**Comment by Vibhu-Agarwal** [comment]
The issue can be resolved by tweaking the [configure](https://github.com/nexB/scancode-toolkit/blob/develop/configure) and [configure.py](https://github.com/nexB/scancode-toolkit/blob/develop/etc/configure.py)
I would like to work on this issue and solve it.

**Comment by pombredanne** [comment]
@Vibhu-Agarwal sure thing: thank you!. This would need to be tested on Windows too. (The CI will test this and fail otherwise)

**Comment by pombredanne** [comment]
It's OK to start with Linux/POSIX only first of course

**Comment by pombredanne** [comment]
This is still an issue for Windows

**Comment by pombredanne** [comment]
I do not think is an issue anymore, but if so, I think the simpler way is going to demand a space-less installation path.
bin/scancode is generated by the Python wheel installer and we cannot do more than what Python in this domain.
I am closing this for now. If this is still an issue please reopen or create a new ticket
There is a new version 30.0.1 to test!
