### ISSUE TITLE
Make tests smarter to run tests faster

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1519]
### Description
Some ideas form Philippe:
1. split scancode in its libraries commoncode, licensedcode, etc (rather than the big mono repo it is today)
2. be smarter on what is tested when
- only retest things that are affected by a commit in general
- restest all in some cases such as a tag or master or develop merge

There are some pytest plugins that might help for this.

**Comment by pombredanne** [comment]
Chat log with py.test developers on #pylib on Freenode:
```
<pombreda> hum, I am still confused by y.test test collection https://gist.github.com/pombredanne/b268ac258ca7d773c4b35dc9b431dde6
<pombreda> that's a minimal example, the real one is https://github.com/nexB/scancode-toolkit/pull/1531
* pombreda is likely confused by the firstresult pluggy thing OR there is a bug
<pombreda> s/y.test/py.test
<pombreda> basically I have a pytest_ignore_collect plugin that ignores EVERYTHING
<pombreda> but things are still collected 
<cdunklau> pombreda: something else is returning non-None before your function
<pombreda> cdunklau: so that would have to be the standard code for collection then?
<pombreda> in particular this in main?
<pombreda> https://github.com/pytest-dev/pytest/blob/49d690d137be1edc79bfffce6720d1186c3eabf2/src/_pytest/main.py#L295
<pombreda> firstresult smells to me a tad like a wart, from a distance 
<pombreda> not that I would know how  wart smells :P
<cdunklau> pombreda: so i have tests/conftest.py and tests/test_blarg.py. When i run `pytest tests`, the hook is invoked, and nothing is collected
<cdunklau> pombreda: when i run `pytest tests/test_blarg.py`, the hook is not invoked, and the tests run
<pombreda> cdunklau, hum.... thx, that should give enough to dive and fix this. I want the combo of passing a list of paths AND selectively further filtering things from these paths
<pombreda> the weird thing is that the main.py hook is properly invoke in this case
<pombreda> no, my bad
<pombreda> shrikes
<pombreda> so for now I cannot do both 
<pombreda> even "py.test foo.py --ignore foo.py" does not ignore foo.py at all
<blueyed> pombreda: re "basically I have a pytest_ignore_collect plugin that ignores EVERYTHING" I would say this sounds like a bug/missing feature, but this hook might just not be called for args.
<blueyed> Unfortunately collection code is duplicated in main and python, and messy in general.. mostly since namespace packages were added there IIRC.
<blueyed> You might have better luck with the pytest_collect_file hook.. or use pytest_collection_modifyitems maybe.
```

**Comment by pombredanne** [comment]
See also this for a minimally failing configuration
https://gist.github.com/pombredanne/b268ac258ca7d773c4b35dc9b431dde6

And this is the key recommendation:
> <blueyed> pombreda: re "basically I have a pytest_ignore_collect plugin that ignores EVERYTHING" I would say this sounds like a bug/missing feature, but this hook might just not be called for args.

> <blueyed> Unfortunately collection code is duplicated in main and python, and messy in general.. mostly since namespace packages were added there IIRC.

><blueyed> You might have better luck with the pytest_collect_file hook.. or use pytest_collection_modifyitems maybe.

**Comment by pombredanne** [comment]
Note that the strategy that I would like to implement is the following:

1. to speed test runs

- if the current branch is develop or master, nothing special happens: run all tests
- otherwise, the list of changed modules is collected based on what git
  reports as changed agsint the develop branch and also adding the list
  of other modules that depend on these modules.
- then any path of files that is NOT in the changed modules is ignored
  from the test collection.

2. for Python3 tests for #295 

- initially, if a test module, class or function is not tagged to run on Python 3, it will be ignored entirely. We should also have a CLI option to run the tests anyway.
- later on when we have a majority of the tests passing on Python 3, run all tests there unless a test module, class or function is tagged NOT to run on Python 3: this is the opposite behavior than what we have at first

**Comment by pombredanne** [comment]
See also https://github.com/GoodRx/pytest-mark-no-py3

**Comment by majurg** [comment]
@pombredanne Perhaps relevant here: https://github.com/tarpas/pytest-testmon/

**Comment by pombredanne** [comment]
I am closing this now as #1531 is merged
