### ISSUE TITLE
scancode installed via pip fails if PyYaml 5.1 is installed

### ISSUE THREAD

**Issue by dankegel** [nexB/scancode-toolkit#1521]
Now that saneyaml is updated to not depend on a particular version of PyYAML, scancode's explicit dependency on a particular PyYAML is getting in the way.

To reproduce (on clean, updated Ubuntu 16.04, with https://launchpad.net/~dank/+archive/ubuntu/python-fixes installed):
```
$ rm -rf ~/.local
$ pip install scancode-toolkit
$ scancode --version
ScanCode version 3.0.2
$ pip list | grep -i pyyaml
PyYAML (3.13)
$ pip install PyYaml==5.1
$ scancode --version
pluggy.manager.PluginValidationError: Plugin 'json-pp' could not be loaded: (PyYAML 5.1 (/home/buildbot/.local/lib/python2.7/site-packages), Requirement.parse('PyYAML<=3.13,>=3.11'))!
```

See also https://github.com/nexB/saneyaml/pull/3#issuecomment-481779602

**Comment by dankegel** [comment]
See https://github.com/nexB/scancode-toolkit/pull/1522

**Comment by pombredanne** [comment]
All merged at last.
