### ISSUE TITLE
Incorrect license detection for FreeBSD  PSFL AND BSD3CLAUSE 

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1527]
### Description
The source MANIFEST file of freebsd  is at:https://github.com/nexB/scancode-toolkit/blob/develop/tests/packagedcode/data/freebsd/multi_license/%2BCOMPACT_MANIFEST

By running the freebsd packagedcode parser, the package result is at: 

https://github.com/nexB/scancode-toolkit/blob/develop/tests/packagedcode/data/freebsd/multi_license/%2BCOMPACT_MANIFEST.expected

We can see that both PSFL and  BSD3CLAUSE are detected as "unknown".

**Comment by pombredanne** [comment]
Fixed in #1552 
Thank you for the report!
