### ISSUE TITLE
ScanCode CLI doesn't handle whitespace

### ISSUE THREAD

**Issue by turbo** [nexB/scancode-toolkit#1530]
### Description

If the repository resides in a path with spaces, the CLI will fail to start:

```text
$ ./scancode --help
* Configuring ScanCode for first use...
./scancode: /Volumes/Vault 1/Projects/scancode-toolkit/bin/scancode: "/Volumes/Vault: bad interpreter: No such file or directory
```

### System configuration

* What OS are you running on: macOS
* What installation method was used to install/run scancode: Source clone

**Comment by pombredanne** [comment]
@turbo thank you for this report. I think this should be fixed now for macOS and Linux in the latest develop as reported in #1511 and then fixed in #1512 by @Vibhu-Agarwal 

Do you mind trying updating to the latest f the `develop` branch to try it?

**Comment by pombredanne** [comment]
@turbo ping?

**Comment by turbo** [comment]
I'll test it and get back to you.

**Comment by turbo** [comment]
Confirmed fixed.

**Comment by nrbrook** [comment]
This is still a problem. `bin/scancode` starts with `#!"/path/with spaces/to/scancode/bin/python2.7" and when run gives the error `-bash: /path/with spaces/to/scancode/bin/scancode: "/Users/path/with": bad interpreter: No such file or directory

**Comment by pombredanne** [comment]
I do not think is an issue anymore, but if so, I think the simpler way is going to demand a space-less installation path.
bin/scancode is generated by the Python wheel installer and we cannot do more than what Python in this domain.
I am closing this for now. If this is still an issue please reopen or create a new ticket
There is a new version 30.0.1 to test!
