### ISSUE TITLE
Add `extra_data` field to Package

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1532]
The `extra_data` field would be a dictionary whose keys and values are strings.

In the case of parsing package manifest files, it would be convenient to be able to carry over parsed package data to the Package class so we can use it to fill in some fields on the Package class.

**Comment by JonoYang** [comment]
This would be especially convenient in the case of parsing ABOUT files. It would be nice to roll up the information from an ABOUT file to the `about_resource` that the ABOUT file is for, but we need to parse the ABOUT file to know about the `about_resource`.

**Comment by pombredanne** [comment]
@JonoYang Thanks! I have been resisting adding this... but this is a good use case, so let's do it!

**Comment by pombredanne** [comment]
Actually this has been reverted. So I am leaving this opened for now.

**Comment by JonoYang** [comment]
`extra_data` has not been added to `Package` since we do not a problem that would be solved by having the `extra_data` field. `extra_data` was added in some branches, but removed since more pertinent fields are available for use.

**Comment by pombredanne** [comment]
This is all merged now. Closing
