### ISSUE TITLE
Have an option to disable exception suppression during Package scan time

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1533]
It would be handy to have an option to disable catching exceptions during Package scan time (https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode/api.py#L236) for the purpose of debugging.

**Comment by pombredanne** [comment]
@JonoYang good point. Exceptions are passed because this otherwise was creating too much noise for packages that contained test packages with invalid manifests. But this is useful not to and to report errors in some cases. May be we should introduce the notion of a WARNING or INFO error message

**Comment by JonoYang** [comment]
This has been merged into develop. Closing.
