### ISSUE TITLE
MIT license can't be detected if the format is "Apache-2.0/MIT"

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1537]
### Description

When running "compute_normalized_license" on the declared license on "Apache-2.0/MIT", it will detect the license result like "apache-2.0 AND unknown", as we can see that MIT is not detected correctly.

This issue was found when committing declared_license improvement for cargo, #1403  and the commit is: https://github.com/nexB/scancode-toolkit/blob/816b8877fcd78208dba9925524cde9e3be963dcd/tests/packagedcode/data/cargo/rustfmt/Cargo.toml.expected#L39

**Comment by pombredanne** [comment]
@linexb thanks! good catch. We need to add a new rule alright for this case.

**Comment by pombredanne** [comment]
This is now in develop. Thanks!
