### ISSUE TITLE
Unable to detect Adobe license rules

### ISSUE THREAD

**Issue by aj4ayushjain** [nexB/scancode-toolkit#1538]
While adding license rules for issue #296
adobe-acrobate-reader-eula license exist already in the rules but on scanning with (--license-text) the license gets undetected the licenses do not match exactly only few  lines  at the top are
altered .    

File for scan:- 
[Adobe.txt](https://github.com/nexB/scancode-toolkit/files/3095263/Adobe.txt)
or https://gitweb.gentoo.org/repo/gentoo.git/tree/licenses/Adobe

Rule file:-
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/adobe-acrobat-reader-eula.RULE

**Comment by pombredanne** [comment]
@aj4ayushjain good catch. I think I may know the reason. Let me dig this a bit

**Comment by pombredanne** [comment]
This is fixed with #1552

**Comment by pombredanne** [comment]
thanks!
