### ISSUE TITLE
Extraction of license text is incomplete and bracktest [] are around some words

### ISSUE THREAD

**Issue by MMarwedel** [nexB/scancode-toolkit#1547]
Hello,
scanning some C++ header files, there are sometimes several things going wrong:
1. The licences should be detected as "gpl-3.0-plus WITH gcc-exception-3.1" or similar, but is detected as "gpl-3.0-plus"
2. The first sentence and two words of the license text are cut away.
3. There are several words in brackets [], which looks like the print of an array from python.

Sample file:
From
https://packages.debian.org/sid/libstdc++-7-dev
download the source:
http://deb.debian.org/debian/pool/main/g/gcc-7/gcc-7_7.4.0.orig.tar.gz
use the directory:
gcc-7_7.4.0.orig/gcc-7-7.4.0/gcc-7.4.0-dfsg/gcc-7.4.0/libstdc++-v3/include/profile/

Results with scancode version 3.0.2:
Some files like "array" are detected right, but "base.h" or "unordered_base.h" are detected wrong:

scancode --license-clarity-score -l -p -c --classify --summary --summary-with-details --license-text --json-pp scanResults.json gcc-7_7.4.0.orig/gcc-7-7.4.0/gcc-7.4.0-dfsg/gcc-7.4.0/libstdc++-v3/include/profile

    {
      "path": "profile/unordered_base.h",
      "type": "file",
      "licenses": [
        {
          "key": "gpl-3.0-plus",
          "score": 97.06,
          "name": "GNU General Public License 3.0 or later",
          "short_name": "GPL 3.0 or later",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-3.0-standalone.html",
          "text_url": "http://www.gnu.org/licenses/gpl-3.0-standalone.html",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-3.0-plus",
          "spdx_license_key": "GPL-3.0-or-later",
          "spdx_url": "https://spdx.org/licenses/GPL-3.0-or-later",
          "start_line": 5,
          "end_line": 22,
          "matched_rule": {
            "identifier": "gpl-3.0-plus_6.RULE",
            "license_expression": "gpl-3.0-plus",
            "licenses": [
              "gpl-3.0-plus"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false
          },
          "matched_text": "is free\n// software; you can redistribute it and/or modify it under the\n// terms of the GNU General Public License as published by the\n// Free Software Foundation; either version 3, or (at your option)\n// any later version.\n//\n// [This] [library] is distributed in the hope that it will be useful,\n// but WITHOUT ANY WARRANTY; without even the implied warranty of\n// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n// GNU General Public License for more details.\n\n// [Under] [Section] [7] [of] [GPL] [version] [3], [you] [are] [granted] [additional]\n// [permissions] [described] [in] [the] [GCC] [Runtime] [Library] [Exception], [version]\n// [3].[1], [as] [published] [by] [the] [Free] [Software] [Foundation].\n\n// You should have received a copy of the GNU General Public License along\n// with [this] [library]; see the file COPYING3.  If not see\n// <http://www.gnu.org/licenses/>."
        },

....

      "license_expressions": [
        "gpl-3.0-plus",
        "gpl-1.0-plus"
      ],

**Comment by pombredanne** [comment]
@MMarwedel thank you for this report

About `There are several words in brackets [],` ... this is how we surround words that were not matched (it is not related to Python arrays/lists)

**Comment by pombredanne** [comment]
In a branch that I am working on on some license issues I get this now:
```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "3.0.2.post610.00f4b27.dirty.20190502080527",
      "options": {
        "input": [
          "libstdc++-v3/include/profile/base.h"
        ],
        "--json-pp": "-",
        "--license": true,
        "--license-diag": true,
        "--license-text": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2019-05-02T130019.131477",
      "end_timestamp": "2019-05-02T130022.193428",
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "base.h",
      "type": "file",
      "licenses": [
        {
          "key": "gpl-3.0-plus",
          "score": 87.01,
          "name": "GNU General Public License 3.0 or later",
          "short_name": "GPL 3.0 or later",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-3.0-standalone.html",
          "text_url": "http://www.gnu.org/licenses/gpl-3.0-standalone.html",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-3.0-plus",
          "spdx_license_key": "GPL-3.0-or-later",
          "spdx_url": "https://spdx.org/licenses/GPL-3.0-or-later",
          "start_line": 5,
          "end_line": 22,
          "matched_rule": {
            "identifier": "gpl-3.0-plus_with_gcc_exception31.RULE",
            "license_expression": "gpl-3.0-plus WITH gcc-exception-3.1",
            "licenses": [
              "gpl-3.0-plus",
              "gcc-exception-3.1"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 154,
            "matched_length": 134,
            "match_coverage": 87.01,
            "rule_relevance": 100
          },
          "matched_text": "This file is part of the GNU ISO C++ Library.  This library is free\n// software; you can redistribute it and/or modify it under the\n// terms of the GNU General Public License as published by the\n// Free Software Foundation; either version 3, or (at your option)\n// any later version.\n//\n// This library is distributed in the hope that it will be useful,\n// but WITHOUT ANY WARRANTY; without even the implied warranty of\n// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n// GNU General Public License for more details.\n\n// Under Section 7 of GPL version 3, you are granted additional\n// permissions described in the GCC Runtime Library Exception, version\n// 3.1, as published by the Free Software Foundation.\n\n// You should have received a copy of the GNU General Public License [along]\n// [with] [this] [library]; [see] [the] [file] [COPYING3].  If not see\n// <http://www.gnu.org/licenses/>."
        },
        {
          "key": "gcc-exception-3.1",
          "score": 87.01,
          "name": "GCC exception to GPL 3.0 or later",
          "short_name": "GCC exception to GPL 3.0 or later",
          "category": "Copyleft Limited",
          "is_exception": true,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gcc-exception-3.1.html",
          "text_url": "http://www.gnu.org/licenses/gcc-exception-3.1.html",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gcc-exception-3.1",
          "spdx_license_key": "GCC-exception-3.1",
          "spdx_url": "https://spdx.org/licenses/GCC-exception-3.1",
          "start_line": 5,
          "end_line": 22,
          "matched_rule": {
            "identifier": "gpl-3.0-plus_with_gcc_exception31.RULE",
            "license_expression": "gpl-3.0-plus WITH gcc-exception-3.1",
            "licenses": [
              "gpl-3.0-plus",
              "gcc-exception-3.1"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 154,
            "matched_length": 134,
            "match_coverage": 87.01,
            "rule_relevance": 100
          },
          "matched_text": "This file is part of the GNU ISO C++ Library.  This library is free\n// software; you can redistribute it and/or modify it under the\n// terms of the GNU General Public License as published by the\n// Free Software Foundation; either version 3, or (at your option)\n// any later version.\n//\n// This library is distributed in the hope that it will be useful,\n// but WITHOUT ANY WARRANTY; without even the implied warranty of\n// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n// GNU General Public License for more details.\n\n// Under Section 7 of GPL version 3, you are granted additional\n// permissions described in the GCC Runtime Library Exception, version\n// 3.1, as published by the Free Software Foundation.\n\n// You should have received a copy of the GNU General Public License [along]\n// [with] [this] [library]; [see] [the] [file] [COPYING3].  If not see\n// <http://www.gnu.org/licenses/>."
        }
      ],
      "license_expressions": [
        "gpl-3.0-plus WITH gcc-exception-3.1"
      ],
      "scan_errors": []
    }
  ]
}
Scanning done.
Summary:        licenses with 1 process(es)
Errors count:   0
Scan Speed:     1.38 files/sec. 
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s) 
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) 
Timings:
  scan_start: 2019-05-02T130019.131477
  scan_end:   2019-05-02T130022.193428
  setup_scan:licenses: 2.33s
  setup: 2.33s
  scan: 0.72s
  total: 3.06s
```
And I verified that all the licenses  in `gcc-7_7.4.0.orig/gcc-7-7.4.0/gcc-7.4.0-dfsg/gcc-7.4.0/libstdc++-v3/include/profile/` are detected correctly

I will also add a new rule and new tests when I am pushing this branch

**Comment by pombredanne** [comment]
Thanks again ++ for the report

**Comment by MMarwedel** [comment]
Thanks for the fast response. The fix is working for me.

**Comment by pombredanne** [comment]
@MMarwedel and thank you for testing this!
