### ISSUE TITLE
Scancode html format

### ISSUE THREAD

**Issue by ChinnuJose** [nexB/scancode-toolkit#1567]
### Description
I would like to know whether it is possible to define the template for html output in Scancode toolkit version 3.0.2. 
In older version we are able to specify the template in html output using –format in latest –format is no longer available. 

### System configuration
For bug reports, it really helps us to know:
* Linux
* Scancode-toolkit 3.0.2
* Downloaded the archive file and extracted to linux machine

**Comment by pombredanne** [comment]
@ChinnuJose sorry if the doc is not clear enough.
The options have changed there. You can now use:
- `--custom-output FILE`  to write scan output to FILE formatted with the custom Jinja template file pointed to by the `--custom-template` option
- `--custom-template FILE`  is to point to a Jinja template FILE to use as a custom template. If not specified a default template is used

**Comment by pombredanne** [comment]
Closing now. Please reopen if you feel this should be discussed further
