### ISSUE TITLE
Incorrect license detection: GPL instead of LGPL

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1568]
### Description
Reported by  `Allison Randal <allison@lohutok.net>` in https://lore.kernel.org/linux-spdx/alpine.DEB.2.21.1905200559350.3019@nanos.tec.linutronix.de/T/#u

```
> > -/* permission is hereby granted to copy, modify and redistribute this code
> > - * in terms of the GNU Library General Public License, Version 2 or later,
> > - * at your option.
```
is incorrectly detected as `gpl-2.0-plus` instead of `lgpl-2.0-plus`

**Comment by pombredanne** [comment]
@allisonrandal FYI

**Comment by allisonrandal** [comment]
LGTM

**Comment by zvr** [comment]
ehmmm... @pombredanne in the description of this issue, the first `lgpl-2.0-plus` should be `gpl-2.0-plus` to make sense...

**Comment by pombredanne** [comment]
@zvr thank you! I updated the description.

**Comment by pombredanne** [comment]
Thank you all: this is fixed and has been merged in the develop banch
