### ISSUE TITLE
Scan authors

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#157]
Authors are detected together with copyrights and are a useful origin clue.

**Comment by nakami** [comment]
@pombredanne, although, the tests for scanning authors are working. it seems like scancode doesn't find authors on its own yet.

running the development build, i seem to not find the expected test results as documented in the test files yet:
`scancode --format html-app tests\cluecode\data\authors authortest.html`

**Comment by pombredanne** [comment]
@nakami: at the moment the authors are only returned in the JSON output and not yet integrated in the `html-app` format

**Comment by nakami** [comment]
thank you for your quick response. i got the expected results in the JSON output now.

i expected the output formats to be updated all together. the roadmap showed a tick for authors scans so i implied that html-app included those as well already.

**Comment by pombredanne** [comment]
@nakami My bad. I updated the roadmap https://github.com/nexB/scancode-toolkit/wiki/Roadmap also adding easier to read icons.
@jdaguil what's you take on adding authors in the HTML app?

**Comment by pombredanne** [comment]
Authors have been added alright. Closing
