### ISSUE TITLE
update Wiki pages

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1570]
### Description
We shouldupdate these Wiki pages (or deprecate them and move them to actual real docs)
- https://github.com/nexB/scancode-toolkit/wiki/How-To:-Run-a-scan
- https://github.com/nexB/scancode-toolkit/wiki/How-To:-Format-scan-output
- https://github.com/nexB/scancode-toolkit/wiki/How-To:-Set-what-will-be-detected-in-a-scan
to be clear that the HTML app format has been deprecated

**Comment by RituRajSingh878** [comment]
```
(py27) rituraj@rituraj-G7-7588:~/Documents/git/scancode-toolkit$ ./scancode --format json samples samples.json
Error: no such option: --format
```
I tried this from[https://github.com/nexB/scancode-toolkit/wiki/How-To:-Run-a-scan]( https://github.com/nexB/scancode-toolkit/wiki/How-To:-Run-a-scan) and i got an error.

**Comment by RituRajSingh878** [comment]
@pombredanne, please review it and merge it and so that I can proceed further.

**Comment by RituRajSingh878** [comment]
> ```
> (py27) rituraj@rituraj-G7-7588:~/Documents/git/scancode-toolkit$ ./scancode --format json samples samples.json
> Error: no such option: --format
> ```
> 
> I tried this fromhttps://github.com/nexB/scancode-toolkit/wiki/How-To:-Run-a-scan and i got an error.

I have solved this issue in the pr #1574

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne Since we are already tracking the outdated wiki problem [here](https://github.com/nexB/scancode-toolkit/issues/1813) should we close this issue and [this other issue](https://github.com/nexB/scancode-toolkit/issues/1475)?

**Comment by majurg** [comment]
This is being tracked here: https://github.com/nexB/scancode-toolkit/issues/1813

Closing this.
