### ISSUE TITLE
Unsupported OS/platform 'win64'

### ISSUE THREAD

**Issue by AtToftegaard** [nexB/scancode-toolkit#1573]
Hi all,
When I try and install I get the following:
` * Configuring ScanCode for first use...`
`Junction created for C:\Users\Z6ATF\Desktop\test\bin <<===>> C:\Users\Z6ATF\Desktop\test\Scripts`
 ` * Activating ... `
`Unsupported OS/platform 'win64'.`
`See https://github.com/nexB/scancode-toolkit/ for supported OS/platforms.`
`Enter a ticket https://github.com/nexB/scancode-toolkit/issues asking for support of your OS/platform combo.`

`Failed to execute command:
C:\Users\Z6ATF\Desktop\test\bin\python.exe "C:\Users\Z6ATF\Desktop\test\etc\conf\base.py". Aborting...`

But am I correct in that the installation-guide (https://github.com/nexB/scancode-toolkit/wiki/Comprehensive-Installation) says 'Windows 7 and up'?

Cheers.

**Comment by pombredanne** [comment]
@AtToftegaard sorry for the late reply... we do not support yet Windows 64 bit directly. This means that you would need to install Python 32 bits and things will work ok.
This is tracked in #335

**Comment by pombredanne** [comment]
We now only support Windows 64. Closing.
