### ISSUE TITLE
Clarify types of plugins

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#1586]
We need to provide clarity more clarity regarding the different types of ScanCode plugins (names below are provisional):

1. "Internal" plugin - these are modules in scancode-toolkit/plugins/. Most currently deal with code extraction or code typing and are not written in Python.  In this case the run-time options are integrated with Toolkit. https://github.com/nexB/scancode-toolkit/tree/develop/plugins/scancode-ignore-binaries is written in Python - not sure that it belongs here.

2. "Embedded" plugin - where the plugin code is embedded in core code  - e.g. scancode-toolkit/blob/develop/src/licensedcode/plugin_license_policy.py.  In this case the run-time options are integrated with Toolkit.

3. "External" plugin - a third-party plugin that may not be in the scancode-toolkit repo. An example would be a customer-specific / private plugin. This area may require design in addition to documentation

And we also have code templates for creating a plugin at scancode-toolkit/src/plugincode/.

The purpose of this Issue is to standardize terminology for different types of ScanCode plugins to be followed by updated documentation with that terminology - esp. https://github.com/nexB/scancode-toolkit/wiki/Plugin-architecture.

**Comment by pombredanne** [comment]
that's a wart of merging in partial Git history from Pygments for a Groovylexer. And GitHub should allow us to disable autoclose... that's their bug

**Comment by pombredanne** [comment]
@mjherzog That was mistakenly autoclosed becasue of this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by chinyeungli** [comment]
I think this page is enough: https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_add_a_post_scan_plugin.html#how-to-add-post-scan-plugin

However, for the step (2) in https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_add_a_post_scan_plugin.html#top-level-folder-scancode-hello , are we forcing user to use `apache-2.0` ? If not, the wording will need to be updated to something like `A license file named in the format "<license_key>.LICENSE"`
