### ISSUE TITLE
Error message is not clear when unable to extract archives

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#160]
OS : windows 7 64-bit

I'm trying to extract a gzip file (`download URL` - `ftp://reflector.vtti.vt.edu/opensuse/distribution/13.2/repo/oss/suse/repodata/070c71c5f39d4c84872070069631f4572f8338a843df2ae8323b6262c1f91284-other.xml.gz`) which is of `size 99.2 MB` and when I try the command `C:\*****\070c71c5f39d4c84872070069631f4572f8338a843df2ae8323b6262c1f91284-other.xml.gz` I get the following error message : 
```
ERROR extracting: C:/Users/nexB/Documents/070c71c5f39d4c84872070069631f4572f8338a843df2ae8323b6262c1f91284-other.xml.gz: ''
Extracting done.
```
The above `error message is not clear` about what the problem is and the problem seems to be memory error in case of large files which is found by `enabling debugging`.

**Comment by balusarakesh** [comment]
issue fixed in the latest version of scancode
