### ISSUE TITLE
Port path handling to use pathlib/pathlib2

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1610]
### Description
We have a contrived way to deal with paths working around some bugs on Python2 on Linux.
This means that we use bytes on Linux and unicode elsewhere and a backport of os.fsencode and os.decode
Instead we should try to use pathlib (and its backport pathlib2) everywhere as ths would help with the Python 3 port quite a bit (see #295)

**Comment by pombredanne** [comment]
Another candidate is likely better: path.py by @jaraco ...
The pathlib2 backport may not be able to handle correctly some by paths on Python2.

**Comment by jaraco** [comment]
For easy reference: [path.py repo](/jaraco/path.py) and [pypi link](https://pypi.org/project/path.py).

**Comment by pombredanne** [comment]
@jaraco thank you! I noted that v12 and up is Python 3 only but that should not be holding us to use the 11.x on Python2 and 3 for now. @Abhishek-Dev09 ping. This is the ticket I created to track this effort.

**Comment by jaraco** [comment]
Yes, and 11.x should get bugfixes backported (on request).

**Comment by pombredanne** [comment]
The pathlib2 backport of pathlib does not support proper fsencoding/decoding on Python2, and therefore using pathlib is not an option for support of both Python2 and Pyhton3. We will instead use `path.py` that support both py2 and 3 nicely (before version 12)

**Comment by pombredanne** [comment]
See #1637

**Comment by jaraco** [comment]
It should not be necessary to specify path.py 11.x as long as you can count on pip 9 or a compatible installer to resolve the dependency, as path.py declares the python_requires and 12.x is excluded on python 2.

Your choice how to implement though.
