### ISSUE TITLE
Tri-license scenario not detected

### ISSUE THREAD

**Issue by bduranc** [nexB/scancode-toolkit#1611]
### Description
As part of performing curation in [ClearlyDefined](https://clearlydefined.io/definitions/git/github/jruby/jruby/8a269e34ff3d242ec90fb08061f79c2757a5e157); I have discovered some files that are tri-licensed _EPL-2.0 OR (GPL-2.0-or-later OR LGPL-2.1-or-later)_. However, ScanCode (as it runs in ClearlyDefined) has identified these as "_GPL-2.0-only_" which is not accurate.

<img width="354" alt="2019-06-20_14-58-16" src="https://user-images.githubusercontent.com/31491646/59884278-bb526100-936c-11e9-92a9-8905d806af48.png">

Some samples are below:

https://github.com/jruby/jruby/blob/8a269e34ff3d242ec90fb08061f79c2757a5e157/core/src/main/java/org/jruby/ext/socket/MulticastStateManager.java

https://github.com/jruby/jruby/blob/8a269e34ff3d242ec90fb08061f79c2757a5e157/core/src/main/java/org/jruby/ext/socket/RubyBasicSocket.java

https://github.com/jruby/jruby/blob/8a269e34ff3d242ec90fb08061f79c2757a5e157/core/src/main/java/org/jruby/ext/socket/RubyIPSocket.java

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? **Windows**
* What version of scancode-toolkit was used to generate the scan file? **ClearlyDefined**
* What installation method was used to install/run scancode? (pip/source download/other) **ClearlyDefined**

- CD Definition URL: **https://clearlydefined.io/definitions/git/github/jruby/jruby/8a269e34ff3d242ec90fb08061f79c2757a5e157**

**Comment by pombredanne** [comment]
@bduranc thank you ++ for this report. That's a new one to me. The current ScanCode was reporting things a tag better but mistakenly still as a mozilla tri-license (with a lower score) and some EPL 2.0

**Comment by pombredanne** [comment]
I just pushed a fix in a branch here https://github.com/nexB/scancode-toolkit/pull/1612/commits/26ddf02a9be23f9ccf65f8de0228baed349b7eb5 ... this will land in develop tomorrow and will be in the 3.1 release that will be cut next week!.
Thank you again!

**Comment by bduranc** [comment]
@pombredanne : No worries, glad to help.

**Comment by pombredanne** [comment]
Merged in develop... thanks you for the report!
