### ISSUE TITLE
Testing Script for the debian package

### ISSUE THREAD

**Issue by aj4ayushjain** [nexB/scancode-toolkit#1614]
This is for the testing of the resultant Debian package on the Debian based system.
This also can be used when the dependencies are being replaced with the respective  packaged version
-proper testing of the dependencies usage.

 
What should be done to binaries being given by the plugin (extractcode-libarchive etc) ?

--Should it be packaged along the package or the plugin need to be converted to binary providing Debian package alone. 

In reference to :- #1580

**Comment by pombredanne** [comment]
> What should be done to binaries being given by the plugin (extractcode-libarchive etc) ?

See #469 ... eventually you want:
1. find the correct native dependency
2. craft a scancode plugin for each of 7z, libarchive and libmagic that points to the Debian ssystem-installed one instead of a prebuilt bundled one

**Comment by pombredanne** [comment]
Closing for https://github.com/nexB/scancode-toolkit/issues/1580
