### ISSUE TITLE
Submission of Python-configparser and Python-pip

### ISSUE THREAD

**Issue by aj4ayushjain** [nexB/scancode-toolkit#1615]
In reference to :- #1580 

The package being created does not support python-configparser and python-pip which is available in debian currently as their is clash with backports module completely illustrated in 
https://bugs.launchpad.net/ubuntu/+source/configparser/+bug/1821247 
and which is solved in the PPA provided with it in Ubuntu.
https://launchpad.net/~dank/+archive/ubuntu/python-fixes/

So need to either file the bugs in debian for this and inform them regarding this so they will update the existing package.

When will the updated version of packaged be released by debian?

**Comment by pombredanne** [comment]
> When will the updated version of packaged be released by debian?

No idea, but you should not be hindered in your progress by a dependency on some work to be done by a thirdparty maintainer, your goal should be to get something working all the way working around these issues and enter ticket to possibly solve these later

**Comment by aj4ayushjain** [comment]
This not an issue anymore with the debian package. 
It was just an intermediate issue while creation of the package.
