### ISSUE TITLE
unable to detect license in the form of a URL

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#162]
OS : windows 7 64-bii
I've updated scancode to the latest version available

[respond.min.js.txt](https://github.com/nexB/scancode-toolkit/files/87779/respond.min.js.txt)

at line no 2 in the above file the URL `https://github.com/scottjehl/Respond/blob/master/LICENSE-MIT` has `MIT-License` in it and scancode failed to detect it.

**Comment by pombredanne** [comment]
@rakeshbalusa You could submit a PR for a new rule that contains this URL

**Comment by balusarakesh** [comment]
#164 issue fixed.
