### ISSUE TITLE
GPL-2-or-later recognized as GPL-3 or later

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1621]
ScanCode version 3.0.2.post866.8b64c93a7

recognizes:

https://android.googlesource.com/platform/external/ltrace/+/refs/heads/master/CREDITS

as GPL 3 or later, though it is GPL 2 or later. License statement is at the end of the file.

**Comment by armijnhemel** [comment]
https://android.googlesource.com/platform/external/ltrace/+/refs/heads/master/NEWS as well

**Comment by armijnhemel** [comment]
Quite a few files in Linux kernel 3.18.20 are now also recognized as GPL-3.0-or-later while they are GPL-2-or-later

**Comment by pombredanne** [comment]
All fixed and merged in develop... thanks you!
