### ISSUE TITLE
GPL 3 or later false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1622]
ScanCode version 3.0.2.post866.8b64c93a7

recognizes

https://android.googlesource.com/platform/external/ltrace/+/refs/heads/master/options.c

as both GPL-2.0-or later and GPL-3.0-or later, while it should be GPL-2.0-or-later

**Comment by armijnhemel** [comment]
https://android.googlesource.com/platform/external/selinux/+/refs/heads/master/prebuilts/bin/sesearch.py

same issue

**Comment by pombredanne** [comment]
Merged in develop... thanks you!
