### ISSUE TITLE
GPL-2-or-later recognized as "GPL-2.0-only, GPL-3.0-or-later"

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1623]
ScanCode version 3.0.2.post866.8b64c93a7

recognizes

https://android.googlesource.com/platform/external/lz4/+/refs/heads/master/examples/Makefile

as GPL-2.0-only, GPL-3.0-or-later but it should be GPL-2.0-or-later

**Comment by armijnhemel** [comment]
more files in this particular repo have the same error

**Comment by pombredanne** [comment]
Merged in develop... thanks you!
