### ISSUE TITLE
LGPL-2.1-or-later recognized as "LGPL-2.1-only, GPL2 only, GPL3 only"

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1624]
ScanCode version 3.0.2.post866.8b64c93a7

https://android.googlesource.com/platform/external/valgrind/+/refs/heads/master/helgrind/tests/tc17_sembar.c

recognized as LGPL2.1-only, gpl-2.0-only, gpl-3.0-only, should be lgpl-2.1-or-later

**Comment by pombredanne** [comment]
Merged in develop... all set!
