### ISSUE TITLE
GPL 2 or later recognized as GPL-2.0-or-later,LGPL-2.1-or-later,GPL-1.0-or-later,GPL-3.0-or-later

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1625]
ScanCode version 3.0.2.post866.8b64c93a7

https://android.googlesource.com/platform/external/valgrind/+/refs/heads/master/none/tests/ppc32/testVMX.c

recognized as GPL-2.0-or-later,LGPL-2.1-or-later,GPL-1.0-or-later,GPL-3.0-or-later should be GPL-2-or-later

Just the license statement will be recognized as GPL-3-or-later (which is wrong in itself).

The second comment block (that lists the release history) is what really screws up detection.

**Comment by pombredanne** [comment]
Merged in develop... all set!
