### ISSUE TITLE
unable to detect dual license MIT/BSD

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#163]
os : windows 7 64-bit
I've updated scancode to the latest version available.
[respond.js.txt](https://github.com/nexB/scancode-toolkit/files/87794/respond.js.txt)
Line no 1 in the above file has copyright and license embedded `copyright (c) 2012: Scott Jehl, Paul Irish, Nicholas Zakas. Dual MIT/BSD license`, scancode `detected only copyright but not the licenses.`

**Comment by pombredanne** [comment]
@rakeshbalusa Thanks! could you add a link to where this code comes from?
and `(c) Scott Jehl. MIT Lic.` should IMHO be detected as both a license and copyright.
Do mind submitting a pull request with new License rules for these two cases?

**Comment by rakeshbalusa** [comment]
@pombredanne  download URL for the package : `https://api.nuget.org/packages/respond.1.4.2.nupkg`
Yes, `(c) Scott Jehl`  is a copyright and `MIT Lic.` is the license and they need to be detected speperatley.
I will try to create a PR with new license rules.

**Comment by rakeshbalusa** [comment]
@pombredanne 
The tests seem to work when I delete my RULE files
RULE:
`Dual MIT/BSD license`
YAML:
```
licenses:
   - bsd-new
   - mit
license_choice: yes"
```
Test case for the above rule:
Test file:
`// Dual MIT/BSD license`
YAML file:
```
licenses:
   - mit
   - bsd-new
license_choice: yes
```
When I add the above files the test `tests/licensedcode/test_detection_datadriven.py::TestLicenseDataDriven::test_detection_no_license_depmod_c` is failing.
The license in the above test file (`\tests\licensedcode\data\licenses\no_license-depmod.c`) is `GPL-2.0-plus` and the license in the test files I've added is `Dual MIT/BSD license`

The `assert expected_licenses == license_result` in the line 177 (URL - `https://github.com/nexB/scancode-toolkit/blob/163-license-in-copyright/tests/licensedcode/test_detection_datadriven.py#L177`) is failing and the line `assert expected_licenses == ['test file: ' + test_file] + [repr(license_result)] + matches` throws the following error message :
```
          AssertionError: assert ['gpl-2.0-plus'] == ['test file: C:\\User...None, length=None)\n)]
            At index 0 diff: u'gpl-2.0-plus' != 'test file: C:\\Users\\nexB\\git\\scancode-163-license-in-copyright\\tests\\licensedcode\\data\\lice
ses\\no_license-depmod.c'
            Right contains more items, first extra item: "[u'gpl-2.0-plus', u'gpl-3.0']"
            Full diff:
            - [u'gpl-2.0-plus']
            + ['test file: C:\\Users\\nexB\\git\\scancode-163-license-in-copyright\\tests\\licensedcode\\data\\licenses\\no_license-depmod.c',
            +  "[u'gpl-2.0-plus', u'gpl-3.0']",
            +  LicenseMatch(
            +  Rule('gpl-2.0-plus_busybox.RULE', [u'gpl-2.0-plus'], choice=False, template=True, text=u'Licensed u...'),
            +  span=Span(start=30, end=42), score=100.0,
            +   ipos=Token(start=0, start_line=1, start_char=0, end_line=1, end_char=79, end=9, gap=0, value=None, length=None),
            +   qpos=Token(start=30, start_line=8, start_char=3, end_line=8, end_char=78, end=42, gap=0, value=None, length=None)
            + ),
            +  LicenseMatch(
            +  Rule('gpl-3.0_6.RULE', [u'gpl-3.0'], choice=False, template=False, text=u'GPL-3.0...'),
            +  span=Span(start=281, end=283), score=100.0,
            +   ipos=Token(start=0, start_line=1, start_char=0, end_line=1, end_char=7, end=2, gap=0, value=None, length=None),
            +   qpos=Token(start=281, start_line=71, start_char=21, end_line=71, end_char=34, end=283, gap=0, value=None, length=None)
            + )]
```

**Comment by pombredanne** [comment]
@rakeshbalusa can you split this in two tickets? The copyright and the license issues are unrelated and should be each their own bugs.

**Comment by rakeshbalusa** [comment]
splitting into two tickets :+1:

**Comment by rakeshbalusa** [comment]
@pombredanne  this issue has been fixed. can I close it?

**Comment by pombredanne** [comment]
@rakeshbalusa How could it be fixed without a commit for a new rule?

**Comment by pombredanne** [comment]
@rakeshbalusa what is the other ticket you created for the copyright? can you reference it in either ticket so we get a cross-link?

**Comment by rakeshbalusa** [comment]
`https://github.com/nexB/scancode-toolkit/pull/165` this issue has been fixed (only the dual license detection - MIT/BSD license) but the license sepration from copyright is not fixed for which I created a new ticket - `https://github.com/nexB/scancode-toolkit/issues/192`

**Comment by rakeshbalusa** [comment]
New rule fixed the issue :+1:
