### ISSUE TITLE
Unknown license may be a tad too much here

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1633]
### Description
In this notice common in a few Linux source code files:
```
/*
 * GPL HEADER START
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 only,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License version 2 for more details (a copy is included
 * in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; If not, see
 * http://www.sun.com/software/products/lustre/docs/GPLv2.pdf
 *
 * Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa Clara,
 * CA 95054 USA or visit www.sun.com if you need additional information or
 * have any questions.
 *
 * GPL HEADER END
 */
/*
 * Copyright (c) 2002, 2010, Oracle and/or its affiliates. All rights reserved.
 * Use is subject to license terms.
 *
 * Copyright (c) 2010, 2012, Intel Corporation.
 */
```

We detect everything OK and there is also a rule that reports `Use is subject to license terms.` as an unknown license
That is a tad noisy though. Should we keep that rule?

**Comment by pombredanne** [comment]
@richardfontana @armijnhemel @DennisClark @sschuberth what do you think?

**Comment by armijnhemel** [comment]
Isn't every file subject to license terms?

**Comment by pombredanne** [comment]
@armijnhemel  that's a bit my point :) FWIW, this was mostly in the kernel and is still in older kernels. This has been cleaned up and removed with the recent SPDX efforts to clean things up there (and the fact it was detected helped a bit may be)

**Comment by sschuberth** [comment]
+1 for removing the "Use is subject to license terms" rule.

**Comment by richardfontana** [comment]
I've seen this phrase used in source files from other projects (and I think from licensors other than Oracle). It feels to me like something that is useful to identify but not to identify it as "unknown license". More like "license notice that may or may not mean anything significant, and which has a history of being used non-interestingly in some open source projects".

**Comment by pombredanne** [comment]
Thank you for all the feedback!
For now, I will deactivate that rule and will come with a way to report these kind of clues but separately from the main licenses.
