### ISSUE TITLE
Terminal window closes unexpectedly when using --test-suite=all for the first time

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1638]
### Description
When I run `py.test` with `--test-suite=all` for the first time on the develop branch, somewhere in the middle of the tests, the terminal window will close and the tests stop running. I then open the terminal again and rerun the tests and the tests pass.

### System configuration
Ubuntu 16.04 and 18.04, ScanCode was cloned from github.

**Comment by pombredanne** [comment]
I never saw this before.... Can you try to use the logging options of pytest to get some clue? Otherwise, could it be the OOM killer that did this?

**Comment by JonoYang** [comment]
I have 32 gigs of ram on the systems this happened on and the swap is not being used. I'll check the pytest logging options.

**Comment by JonoYang** [comment]
This issue has been fixed in develop.
