### ISSUE TITLE
Revisit parsers in packagedcode

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1643]
In updating some package parsers for (#1588), I noticed that some of them are not being used at all despite being in the list of package parsers (e.g. https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/pypi.py)

**Comment by pombredanne** [comment]
@JonoYang good catch!

**Comment by pombredanne** [comment]
A good way to check would be to verify if we have at least one top level command line test for each package type.

**Comment by linexb** [comment]
I have added the argument "--list-package" to show all supported package code through command.

The usage and result is like this:
```
./scancode  --list-packages
--------------------------------------------
Package: about
  class: packagedcode.about:AboutPackage
  metafiles: *.ABOUT

--------------------------------------------
Package: android
  class: packagedcode.models:AndroidApp
  extensions: .apk
  filetypes: zip archive

--------------------------------------------
Package: android-lib
  class: packagedcode.models:AndroidLibrary
  extensions: .aar
  filetypes: zip archive

--------------------------------------------
Package: axis2
  class: packagedcode.models:Axis2Mar
  metafiles: META-INF/module.xml
  extensions: .mar
  filetypes: java archive , zip archive

--------------------------------------------
Package: bower
  class: packagedcode.bower:BowerPackage
  metafiles: bower.json, .bower.json


```

**Comment by pombredanne** [comment]
@linexb thanks... could you also add a tests for each know package type to make sure this is detected when using a command line scan?

**Comment by linexb** [comment]
Here is all packages we supported now and the status means if we have the test cases for it or not.

Package: about
Status: Yes

--------------------------------------------
Package: android
Status: No

--------------------------------------------
Package: android-lib
Status: No

--------------------------------------------
Package: autotools
Status: No

--------------------------------------------
Package: axis2
Status: No

--------------------------------------------
Package: bazel
Status: No

--------------------------------------------
Package: bower
Status: Yes

--------------------------------------------
Package: buck
Status: No

--------------------------------------------
Package: cab
Status: No

--------------------------------------------
Package: cargo
Status: Yes

--------------------------------------------
Package: chef
Status: Yes

--------------------------------------------
Package: chrome
Status: No

--------------------------------------------
Package: composer
Status: Yes

--------------------------------------------
Package: conda
Status: Yes

--------------------------------------------
Package: cpan
Status: No

--------------------------------------------
Package: deb
Status: No

--------------------------------------------
Package: dmg
Status: No

--------------------------------------------
Package: ear
Status: No

--------------------------------------------
Package: freebsd
Status: Yes

--------------------------------------------
Package: gem
Status: Yes

--------------------------------------------
Package: haxe
Status: Yes

--------------------------------------------
Package: installshield
Status: No

--------------------------------------------
Package: ios
Status: No

--------------------------------------------
Package: iso
Status: No

--------------------------------------------
Package: ivy
Status: No

--------------------------------------------
Package: jar
Status: No

--------------------------------------------
Package: jboss
Status: No

--------------------------------------------
Package: maven
Status: Yes

--------------------------------------------
Package: meteor
Status: No

--------------------------------------------
Package: mozilla
Status: No

--------------------------------------------
Package: msi
Status: No

--------------------------------------------
Package: npm
Status: Yes

--------------------------------------------
Package: nsis
Status: No

--------------------------------------------
Package: nuget
Status: Yes

--------------------------------------------
Package: pypi
Status: Yes

--------------------------------------------
Package: rpm
Status: Yes

--------------------------------------------
Package: shar
Status: No

--------------------------------------------
Package: squashfs
Status: No

--------------------------------------------
Package: war
Status: No

**Comment by linexb** [comment]
@pombredanne Adding the test to the package type whose status is "No" above will have no package found  so doesn't make sense, the root cause is those packages don't have function  "def recognize(cls, location)"  defined. Do you agree that we should include "recognize" function for those missed one or at least for some major ones? Or this may be by design? Please advise. :)

**Comment by pombredanne** [comment]
@linexb so if we do not have a `recognize(cls, location)` defined that makes sense. I think we are good with that then. I will need to revisit these though, sooner than later as we likely have a tad too many entries for these untested packages.

**Comment by JonoYang** [comment]
We now have the `--list-package` option that will tell the user which package scanners are available. The Pypi parser that was once disconnected is now used.
