### ISSUE TITLE
About file parser is opening its about_resource as a manifest file

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1653]
There is a bug in Package scans where About files are assigning the package root to a file. plugin_package.py then attempts to set the manifest path based on the root of the package, which it assumes it is a directory. The problem is that the package root is a file and the new manifest path does not make sense.

We could get around this by having a codebase-relative paths for manifests, or by relaxing the restriction on files Resource having child Resources.

**Comment by majurg** [comment]
Also, there are many instances where the top level directory may hold multiple about files so we need to take this into account.

**Comment by JonoYang** [comment]
There is a workaround that has been merged into develop: https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/plugin_package.py#L133, though this will have to be fixed properly.
