### ISSUE TITLE
Can i install it on CentOS?

### ISSUE THREAD

**Issue by ShandrisFeathermoon** [nexB/scancode-toolkit#1665]
### Description
Please leave a brief discription of the bug or feature request:
* if reporting a bug, tell us how to reproduce the issue.

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by Abhishek-Dev09** [comment]
Yes, CentOS is also version of linux.You can't open a issue for such small question.You can visit github page of any project and find which os it supports.

**Comment by pombredanne** [comment]
@ShandrisFeathermoon yes this is supported. There is a bug on some CentOS that you may be facing though. 

See https://github.com/nexB/scancode-toolkit/issues/443 and the workaround is to execute this once:
`sudo ln -s /usr/lib64/libbz2.so.1 /usr/lib64/libbz2.so.1.0`
