### ISSUE TITLE
MPL 2.0 license not detected

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#167]
OS : windows 7 - 64 bit
I've updated my scancode to the latest version available.

RPM file download URL : `http://bay.uchicago.edu/centos-vault/6.4/cr/x86_64/Packages/libreoffice-sdk-doc-4.0.4.2-9.el6.x86_64.rpm`

issue file path : `libreoffice-sdk-doc-4.0.4.2-9.el6.x86_64.rpm\usr\lib64\libreoffice\sdk\docs\cpp\ref\security_8hxx_source.html`

In the above html file the following license notice is `not detected which belongs MPL 2.0`: 
```
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/. 
```

**Comment by rakeshbalusa** [comment]
@pombredanne  the following text is present in the above issue file `security_8hxx_source.html` : 
```
<a name="l00005"></a>00005 <span class="comment"> * This Source Code Form is subject to the terms of the Mozilla Public</span>
<a name="l00006"></a>00006 <span class="comment"> * License, v. 2.0. If a copy of the MPL was not distributed with this</span>
<a name="l00007"></a>00007 <span class="comment"> * file, You can obtain one at http://mozilla.org/MPL/2.0/.</span>
<a name="l00008"></a>00008 <span class="comment"> *</span>
```
`scancode` is not able to detect license due to the `HTML tags`. If there are no tags then `scancode` can detect  this license and we don't need to add this `RULE`.

**Comment by pombredanne** [comment]
OK, let's wait for approximate license detection for this one. As well as pending markup stripping on HTML

**Comment by rakeshbalusa** [comment]
ok :+1:

**Comment by balusarakesh** [comment]
issue fixed.
