### ISSUE TITLE
Do not report absolute paths in CSVs

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1671]
### Description
The CSV output `files.path` attribute is always prefixed with a `/` ... this should only be the case when the path is an absolute path. Otherwise, only a relative path without a slash prefix should be there. The absolute way we have today makes it hard when you copy and paste a path in a shell.

**Comment by adityaviki** [comment]
Hi! @pombredanne I would like to work on the issue and wanted to know if someone is not already working on it?

**Comment by majurg** [comment]
@adityaviki Feel free to work on any open issues.
