### ISSUE TITLE
Copyright notice is not detected

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#1672]
Running ScanCode 3.0.2 (on Ubuntu 16.04) on a section of a codebase, I see that the following text at the top of one file was not detected as a copyright (`Acme Inc.` has been substituted for the actual name):

```
/******************************************************************************

  Copyright (C), 2001-2011, Acme Inc.

******************************************************************************
```

**Comment by pombredanne** [comment]
This has been merged in develop. Thank you for the report and fixes.
