### ISSUE TITLE
Check for Update - feature request

### ISSUE THREAD

**Issue by bobgob1** [nexB/scancode-toolkit#1688]
Feature Request:

To facilitate running on the most recently released version of scancode-toolkit, add "Check for Software Update" under Help menu.  Or some similar implementation.  Without this it is too easy to continue running old versions because if you aren't actively involved in development, you probably don't go to github to check.

**Comment by pombredanne** [comment]
@bobgob1 excellent suggestion... I think we can use something such as the pip nag that comes this way as a simple warning message that is issues no more than once per week.
```
You are using pip version 18.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

https://github.com/pypa/pip/blob/449d268b5a6a6e126e4f00f0c848f101e689c2a0/src/pip/_internal/utils/outdated.py

Actually we already have code in a branch in https://github.com/nexB/scancode-toolkit/commit/200d96196b050c3ae33aeb1cd309a72511059a0b by @jdaguil  so it should be easy to update and activate!

**Comment by pombredanne** [comment]
This is merged in develop now: all yours to test there (though it may be hard to test until we have made releases at PyPI).
Do you think we should have a command line option to also force a check if a newer version is available?

Otherwise this is automatic and done once a week at most

**Comment by bobgob1** [comment]
I like command line options as much as the next person, but perhaps a version check would be best done by overloading --version?   Would this mess anyone up who is parsing that info?  They can always just pick off the third field.
Something like:
scancode --version
ScanCode version 3.0.2 (A newer version, 3.0.3, is available at <link>>.
or 
ScanCode version 3.0.2 (This is the latest released version.)

**Comment by pombredanne** [comment]
> Would this mess anyone up who is parsing that info? 

I do not think so. The actual current version is available in a structured form in the scans alright. I can add that to a new line too.

**Comment by bobgob1** [comment]
What I would really like is if that version info  "A newer version ... is available" was part of the scancode output, because that's where I'll see it.

**Comment by pombredanne** [comment]
@bobgob1 I will add this in the results too. Good point and there is a bug that needs to be fixed before we push a proper release candidate.

**Comment by pombredanne** [comment]
One issue to fix is this message:
```
WARNING: You are using ScanCode Toolkit version 3.1.1.post147.a08176565, however the newer version 3.1.1 is available.
You should download and install the latest version of ScanCode with bug and security fixes and the latest license detection data for accurate scanning.
Visit https://github.com/nexB/scancode-toolkit/releases for details.
```
This showed up with a git clone

**Comment by pombredanne** [comment]
This is now working normally. Closing!
