### ISSUE TITLE
JPEG license detected but may not be really a license, only a copyright

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#169]
OS : windows 7 - 64 bit
I've updated my scancode to the latest version available.

RPM file download URL - `http://vault.centos.org/6.3/os/x86_64/Packages/libwmf-devel-0.2.8.4-22.el6.centos.x86_64.rpm`

issue file path : `libwmf-devel-0.2.8.4-22.el6.centos.x86_64.rpm-extract\usr\share\doc\libwmf-devel-0.2.8.4`
`scancode output` : 
```
Path	                What	Start Line	End Line		Info
C:/doc/temporary/delete/gd.html	License	107	108		JPEG License
```
The following text is in the lines 107 and 108 which is a `copyright notice` but `scancode detected JPEG License` : 
```
Becker and copyright (C) 1994-1998, Thomas G. Lane.  This software is based 
in part on the work of the Independent JPEG Group. See the file
```

**Comment by pombredanne** [comment]
@rakeshbalusa Is this a mentio  of the JPEG license or not?
I think it is. IMHO not a bug but the opportunity for a new test

**Comment by rakeshbalusa** [comment]
@pombredanne  yes, maybe due to the same name this could have happened. let me know if I have to close the issue.

**Comment by pombredanne** [comment]
This is the rule that is matched: https://github.com/nexB/scancode-toolkit/blob/4bcd694e51e47e42dd083644f577bbafb9cdcf61/src/licensedcode/data/rules/ijg_1.RULE
And this is indeed the common notice for the `ijg` license so this is not a bug.
