### ISSUE TITLE
include spdx version information

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1693]
### Description

The scancode results do not specify which SPDX version the license identifiers are from. It would be nice to include this.

**Comment by pombredanne** [comment]
@armijnhemel this makes sense. Where would see this? in the scan headers? Or with each license data?

**Comment by armijnhemel** [comment]
I would say scan headers.

**Comment by pombredanne** [comment]
This is now included in JSON scan headers as:
```
        extra_data:
            spdx_license_list_version: '3.19'
```
