### ISSUE TITLE
invalid copyright Copyright (c) 2000 detected

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#170]
OS : windows 7 - 64 bit
I've updated my scancode to the latest version available.

RPM file download URL - http://vault.centos.org/6.3/os/x86_64/Packages/libwmf-devel-0.2.8.4-22.el6.centos.x86_64.rpm

issue file path : `libwmf-devel-0.2.8.4-22.el6.centos.x86_64.rpm-extract\usr\include\libwmf\api.h`
The file content is:

```
/* libwmf (<libwmf/api.h>): library for wmf conversion
   Copyright (C) 2000 - various; see CREDITS, ChangeLog, and sources
```

In line 2 `copyright is not concluded` from which `scancode` detects an invalid copyright.
`scancode output` : 

```
Path                             What   Start Line  End Line        Info
C:/doc/temporary/delete/api.h   Copyright   1   2       Copyright (c) 2000
```

**Comment by pombredanne** [comment]
This may not be entirely a bug. This is a weird copyright

**Comment by pombredanne** [comment]
The latest code return `Copyright (C) 2000 - various` which is good enough in this case IMHO.
I am closing this. Thanks
