### ISSUE TITLE
Perl license notice is reported as artistic-2.0 OR gpl-1.0-plus

### ISSUE THREAD

**Issue by qduanmu** [nexB/scancode-toolkit#1714]
License expression of the license rule [artistic-2.0_or_gpl_5.RULE](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/artistic-2.0_or_gpl_5.RULE) is 'artistic-2.0 OR gpl-1.0-plus', should it be mapped to "artistic-perl-1.0 OR gpl-1.0-plus" instead?
(There are several other similar license rules).

Seems like Scancode will take a piece of very general rule text such as "licensed under the same terms as Perl itself" and somehow determine whether the code being scanned is Perl 5 or Perl 6 code, so that the correct Artistic version can be reported. For most of the 'artisitc-perl-1.0' license rules, I could see their rule text has something like 'either Perl version 5.x.x or, at your option, any later version of Perl 5 you may have available.' (related [commit](https://github.com/nexB/scancode-toolkit/commit/2d0d174bc6a316be2e1c3c53c61cb3bc06f31080)), otherwise, the 'artistic-2.0' will be reported. 

Some extra collected feedback about this:
"In Perl world, "Perl" means "Perl 5". "Perl 6" means "Perl 6". There are very few Perl 6 third-party sources https://modules.perl6.org/. I've never seen a Perl 6 source that would claim "the same as Perl". All Perl 6 sources I saw referred directly to Artistic 2.0."

**Comment by pombredanne** [comment]
@qduanmu thank you ++ for this... this is a bug alright. 
1. we can fix the rules alright
2. in a few ambiguous cases we can ensure that the rules are a `relevance: XXX` set in their yml such that we provide a hint that this is not 100% relevant


The difficulty in such cases is being both useful, accurate and not misleading so this definitely needs to be beefed up.

**Comment by pombredanne** [comment]
@qduanmu I think we are all set now and this is in the develop branch ! Thank you ++. Closing!
I also sent you an invite to join the chat channel for the project at https://gitter.im/aboutcode-org/discuss
