### ISSUE TITLE
Run plugin tests as apart of the CI suite

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#1715]
### Description
Currently, no tests are run for the various external plugins in the `plugins/` directory. These tests should probably be run in our CI environments since we include them in the source tree of `scancode-toolkit`. 

Alternatively, we could add these as git submodules with their own repos handling the CI/testing aspect. But for now, we should probably develop a way to make these run in their current state. 

For all of these 'external' plugins, we have to run some `pip install setup.py` in each plugin directory THEN run `py.test`.

**Comment by linexb** [comment]
The test of the compiled code  plugin can be started with these commands/steps, please refer to: https://github.com/nexB/scancode-toolkit/blob/1712-cppinclude-command/plugins/scancode-compiledcode/README.md

**Comment by majurg** [comment]
#1741 merged, closing this.
