### ISSUE TITLE
Naming of the plugins-builtin to be used with distro packages 

### ISSUE THREAD

**Issue by aj4ayushjain** [nexB/scancode-toolkit#1716]
This is for naming convention problem of the plugins which are to be used with the distro packages to provide the path to prebuilt binaries as provided by the system package.

Reference :-#1580

**Comment by aj4ayushjain** [comment]
@aj4ayushjain -The distro package plugins i do have created has the same name so they overwrite the existing one's or which ever executes last according to build-plugins.sh script only exists --->so need to segregate them.

@pombredanne -the package names could be different I think, as long as they provide a path alright?

@aj4ayushjain -The package name have to be same because debian package uses the internally the setup.py as reference for the required packages check after taking the required dependencies from user while packaging .(my understanding)
and this error it shows :
`➜  st sudo dpkg -i scancode-toolkit_3.0.2-1_all.deb 
[sudo] password for ayush: 
Selecting previously unselected package scancode-toolkit.
(Reading database ... 211489 files and directories currently installed.)
Preparing to unpack scancode-toolkit_3.0.2-1_all.deb ...
Unpacking scancode-toolkit (3.0.2-1) ...
Setting up scancode-toolkit (3.0.2-1) ...
➜  st scancode
Traceback (most recent call last):
  File "/usr/bin/scancode", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ayush/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/ayush/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/ayush/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ayush/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/ayush/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ayush/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'extractcode-7z' distribution was not found and is required by scancode-toolkit`

(couldn't technically know the working but that's only the issue).

**Comment by aj4ayushjain** [comment]
No i we have the same tags as well this is causing the issue .

**Comment by pombredanne** [comment]
@aj4ayushjain what does the deb contain for `extractcode-7z` ?

**Comment by aj4ayushjain** [comment]
The deb only contains the installed plugins  dir without any binaries.

**Comment by pombredanne** [comment]
But is `extractcode-7z` in it? can you paste a listing of the plugins?

**Comment by aj4ayushjain** [comment]
Ya i got it now the plugins name can be different inside along with tag remaining the same as the module which is inside `src/` dir name remains the  so it satisfies and works it is not overwritten!
Thanks for the help.

**Comment by pombredanne** [comment]
@aj4ayushjain :+1: 
I knew there should be a way out!
