### ISSUE TITLE
Incorrect detection of Linux-syscall-note

### ISSUE THREAD

**Issue by LeChasseur** [nexB/scancode-toolkit#1734]
Not sure if it is helpful to report wrong result without understanding the rules for identification and helping to correct them. Here the following file:
https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyeleven/license.txt
It contains a regular GPL-2.0 but no Linux-syscall-note. However, Scancode reports:

"licenses": [
        {
          "key": "gpl-2.0",
          "score": 80.99,
          "name": "GNU General Public License 2.0",
          "short_name": "GPL 2.0",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-2.0.html",
          "text_url": "http://www.gnu.org/licenses/gpl-2.0.txt",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-2.0",
          "spdx_license_key": "GPL-2.0-only",
          "spdx_url": "https://spdx.org/licenses/GPL-2.0-only",
          "start_line": 1,
          "end_line": 280,
          "matched_rule": {
            "identifier": "gpl-2.0_and_linux_kernel.RULE",
            "license_expression": "gpl-2.0 WITH linux-syscall-exception-gpl",
            "licenses": [
              "gpl-2.0",
              "linux-syscall-exception-gpl"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 3036,
            "matched_length": 2459,
            "match_coverage": 80.99,
            "rule_relevance": 100
          },

Let me know if this helps or not.

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? "3.1.1.post16.e9272cd"
* What installation method was used to install/run scancode? source download

**Comment by pombredanne** [comment]
@LeChasseur thanks for this. Definitely something weird... but it looks like the Wordpress folks have truncated their GPL license text. How shocking! :smile:  Let me dive deeper in this as in anycase we should not report the syscall notes there

**Comment by pombredanne** [comment]
This is confirmed as fixed in the develop branch.
