### ISSUE TITLE
ERROR: failed to run scan plugin: packages

### ISSUE THREAD

**Issue by krutztq** [nexB/scancode-toolkit#1735]
### Description
An error occured during a scan with the following command:
scancode -plucie --only-findings <dir> --json-pp result.json

### System configuration
* What OS are you running on? (Windows/MacOS/Linux)
Ubuntu 18.04.2 LTS
* What version of scancode-toolkit was used to generate the scan file?
3.1.1
* What installation method was used to install/run scancode? (pip/source download/other)
download

### Error message
Scanning done.
Some files failed to scan properly:
ERROR: failed to run scan plugin: packages:
Traceback (most recent call last):
  File "/home/name/tools/scancode-toolkit-3.1.1/src/scancode/cli.py", line 1033, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/name/tools/scancode-toolkit-3.1.1/src/packagedcode/plugin_package.py", line 165, in process_codebase
    new_manifest_path = os.path.join(parent_directory(new_package_root.path), resource.name)
NameError: global name 'os' is not defined

### Fix
Adding the following lines to src/packagedcode/plugin_package.py seems to fix it:
import os
from commoncode.fileutils import parent_directory

**Comment by pombredanne** [comment]
@krutztq Thank you for the report and sorry for that ... especially since it was already fixed by @adityaviki  !
Do you mind trying the latest `develop` to confirm this is fixed?

**Comment by krutztq** [comment]
No problem.. I already tested the changes of the relevant commit c4fc08c and the error did not occur.

**Comment by pombredanne** [comment]
@krutztq Thank you ++ for testing this and using scancode: If you have any further bug, issue or feature request... sent it our way .
