### ISSUE TITLE
Scantool packaging requires non-free Intel/AMD systems

### ISSUE THREAD

**Issue by madscientist159** [nexB/scancode-toolkit#1736]
When trying to use Scantool on a libre non-x86 platform, I discovered the following problems:

1.) The standard pip install method requires precompiled binaries.  Those binaries are only available for x86 systems.
2.) After downloading the source from this repository, I found more x86 binaries blocking build.  At minimum there are binaries in extractcode_libarchive with no clear way of how to build from source; those binaries are Intel-only.

For a tool designed to find non-free licenses, requiring proprietary hardware and closed-source system firmware to run said tool seems to be a major oversight.

**Comment by pombredanne** [comment]
@madscientist159 thank you for this report: the pre-built x86 binaries are only provided as a convenience such that they do not need to be compiled by end users. 

The full corresponding source code is in https://github.com/nexB/scancode-thirdparty-src/ and there is definitely a need for better documentation hee... we are working on it and in particular there is a student that started last week to work on improved docs as part of the Google Seasons of Docs sponsorship. 

That said, there are three binaries that we depend on:
- libarchive
- file aka. libmagic
- 7zip
All of these are fairly generic and common and to the best of my knowledge none of them is architecture-specific and all can be built for other arches including MIPS,  ARM and PowerPC.

The binaries can either be provided pre-compiled in plugins to scancode (as is done today for x86) OR a scancode plugin can point to system-installed shared libs and exes and provide the path where the exe live. @aj4ayushjain is the expert on that and may help there too.

Beside this, @aj4ayushjain is working on a complete Debian packaging and there is a FreeBSD port available.

I hope this helps! Can you elaborate which OS/Arch you are interested in?

**Comment by aj4ayushjain** [comment]
I would love to help you out if you could please provide more details .
Not actually an expert.:p

**Comment by madscientist159** [comment]
@pombredanne Great to hear there is interest in fixing the problem!

I am specifically looking at Debian on ppc64le.  My main desktop, where I do this kind of work, is based on a POWER9 Blackbird system, and after struggling for a bit trying to figure out how to recompile the binaries I ended up giving up and having someone else run the tools for me.

The documentation definitely needs help -- a COMPILING file would be great, even if it just had hints as to where to look for the sources for the precompiled binaries.

**Comment by aj4ayushjain** [comment]
@madscientist159 Is there much difference between ppc64le and ppc64el architectures except endianness?

As the plugins addresses the issue for ppc64el architectures.

**Comment by madscientist159** [comment]
@aj4ayushjain No difference at all -- one is Debian style for the same architecture, the other is used most other places.  It's the same thing though -- PowerPC 64 bit little endian.

**Comment by aj4ayushjain** [comment]
@madscientist159 Not much of a problem.

You can use the python plugins suffixed with system_provided which lie in plugins-builtin dir but before you need to install the following packages which will fetch the binaries according to your arch :-
1: extractcode-7z dependency - p7zip-full
2: extractcode-libarchive dependency - libarchive13
3: typecode-libmagic dependency - libmagic-dev,libmagic-mgc

Then everything seems to be sorted for now.

**Comment by madscientist159** [comment]
@aj4ayushjain My next concern becomes ease of installation for users of the POWER platform.  Is there any way we can provide the same out-of-box-experience for ppc64le as for x86 by at least shipping ppc64le builds on pip?

**Comment by aj4ayushjain** [comment]
@madscientist159 I think so this could be done only thirdparty binaries are the issue for now so we could include them for the ppc64le arch.
@pombredanne What's your take on this ?

**Comment by pombredanne** [comment]
All the binaries are built now at https://github.com/nexB/scancode-plugins
And all can be built from sources.
@madscientist159 I am closing this for now. Please reopen if you still want to work on PPC builds.
