### ISSUE TITLE
IBM proprietary license not detected with reference to a license

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#174]
```
StartFontMetrics 2.0
Comment Copyright (c) IBM Corporation 1990,1991.
Comment IBM Courier is a Trademark of the IBM Corporation.
Comment US Gov't Restricted Rights Notice - Use, Duplication or Disclosure
Comment Restricted By Accompanying License Agreement With IBM Corp.
Comment Creation Date: Tue Sep 17 16:16:44 1991
Comment UniqueID 263786
Comment VMusage 57844 76768
FontName Courier
FullName Courier
FamilyName Courier
Weight Regular
ItalicAngle 0
IsFixedPitch true
FontBBox -48 -288 684 841
UnderlinePosition -100
UnderlineThickness 50
Version 001.003
Notice Copyright (c) IBM Corporation 1990,1991.
EncodingScheme AdobeStandardEncoding
CapHeight 563
XHeight 430
Ascender 627
Descender -157
StartCharMetrics 479
```
License not detected by scancode even with reference to a license.
RPM : `xorg-x11-fonts-7.6-30.1.5.noarch.rpm`
download URL : `https://mirror.umd.edu/opensuse/distribution/13.2/repo/oss/suse/noarch/xorg-x11-fonts-7.6-30.1.5.noarch.rpm`
issue file path : `xorg-x11-fonts-7.6-30.1.5.noarch.rpm\usr\share\fonts\Type1\cour.afm`

**Comment by rakeshbalusa** [comment]
@pombredanne  the license to be detected is `ibm-developerworks-community-download` - `https://enterprise.dejacode.com/license_library/nexB/ibm-developerworks-community-download/`. please let me know if it's not correct.

**Comment by pombredanne** [comment]
@DennisClark what is your take on this?

**Comment by DennisClark** [comment]
I think the ibm-developerworks-community-download is a good default IBM license, esepcially since DeveloperWorks seems to contain everything-but-the-kitchen-sink.  However, if we have a way for ScanCode simply to say "proprietary notice" then that is ok too.

**Comment by mjherzog** [comment]
Detecting the "Restricted notice" and possibly the "US Gov't Restricted" line is a template for a generic proprietary notice - not a license.  Automating the association between this notice and a license text in the same code package is a stretch because the "accompanying license" is not named.

**Comment by pombredanne** [comment]
@mjherzog Thanks for you insights!

Here is what we will do then:
The rule text should be :
```US Gov't Restricted Rights Notice - Use, Duplication or Disclosure
Comment Restricted By Accompanying License Agreement```
And this should be for the plain `proprietary` license key https://github.com/nexB/scancode-toolkit/blob/c606f59785e43812be4d3e8cfabd62089c8b3157/src/licensedcode/data/licenses/proprietary.yml

@mjherzog the detection of smaller chunks of this notice is something best delegated to the approximated detection and not a specific very small rule.

**Comment by balusarakesh** [comment]
issue fixed.
