### ISSUE TITLE
Creative common license in Scancode

### ISSUE THREAD

**Issue by ummer9987** [nexB/scancode-toolkit#1740]
### Description
@pombredanne Does Creative Commons licenses are available in any version of Scancode. I am currently using Scancode version 3.0.2 in which Creative Commons are not listed in the rules. Could you please mention versions of Scancode if any  which will identify Creative commons licenses.

**Comment by pombredanne** [comment]
We should have all the CC licenses. They are stored in https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses

Each license is a pair of files that share the same base name (which is the license key):
- a file with a .yml extension contains the data about a license
- a file with a .LICENSE extension contains the license text

See https://github.com/search?l=&p=1&q=repo%3AnexB%2Fscancode-toolkit+extension%3ALICENSE+extension%3Ayml+path%3A%2Fsrc%2Flicensedcode%2Fdata%2Flicenses+filename%3Acc-%2A&ref=advsearch&type=Code&utf8=%E2%9C%93

**Comment by ummer9987** [comment]
@pombredanne 
is it possible to search a particular keyword in a package with scancode.

**Comment by pombredanne** [comment]
@ummer9987 re:

> is it possible to search a particular keyword in a package with scancode.

can you explain a bit more what you mean by this (btw it is usually best to create a new ticket for each unrelated question: it feels like this new question is not about CC licenses...)

**Comment by pombredanne** [comment]
Closing now for lack of response.
