### ISSUE TITLE
Incorrect Package URL returned from scan of insomnia-7.0.0.tar.gz

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1747]
A recent scan of insomnia-7.0.0.tar.gz from download URL https://github.com/getinsomnia/insomnia/archive/v7.0.0.tar.gz returned a Package URL of `pkg:npm/insomnia@1.0.0` which does not make any sense, because the version is very clearly `7.0.0` as indicated in both the package filename and the download URL. 

Scan results attached. 
[insomnia-7.0.0.tar.gz_scan.json.zip](https://github.com/nexB/scancode-toolkit/files/3692619/insomnia-7.0.0.tar.gz_scan.json.zip)

**Comment by majurg** [comment]
@DennisClark For what its worth, the package manifest for insomnia has its version at `v1.0.0` on the v7.0.0 tag in GitHub: https://github.com/getinsomnia/insomnia/blob/v7.0.0/package.json

So this may not be a ScanCode bug

**Comment by DennisClark** [comment]
@majurg    Shocking !    Closing ticket.
