### ISSUE TITLE
Crates cargo.toml "license-file=LICENSE"

### ISSUE THREAD

**Issue by fossygirl** [nexB/scancode-toolkit#1756]
### Description
cargo.toml license-file=LICENSE is often getting read as NOASSERTION because the community norm is to include that phrasing as a pointer to a LICENSE file in the package. Can we improve the scanning to understand this phrasing?

Example component: https://clearlydefined.io/definitions/crate/cratesio/-/memrange/0.1.3
https://clearlydefined.io/file/a6fc9020d3bf01aa315b15de1821e3ab2dba22584d7e672fcd14c293b5f2dee7

**Comment by pombredanne** [comment]
@fossygirl thanks! and yes. 

There is already a ticket that tracks this at a high level https://github.com/nexB/scancode-toolkit/issues/1675

> ### Follow license references to another file
> This is for references such as "see COPYING for license" to report the detected license in the referenced file if any e.g. mentions to look for license details in another file.
> We should have a way to follow license references using the referenced_filenames attribute and find the detected license in these filenames. And when such a conclusive reference is found positively, we should update the match to use the referenced license(s) that were detected.

And the important work is tracked in https://github.com/nexB/scancode-toolkit/issues/1364#issuecomment-514460202 and was initially for npms

> At this stage most license rules have been tagged with a referenced_filenames if they reference such a file. The next step is going to be to follow the referenced filenames in the general cases and in the special case of npm "SEE LICENSE IN" and point to the referenced license instead.

The `"SEE LICENSE IN"` is the way that npms document following licenses in files.

So there is already the ground work and design done... next is to implement this

**Comment by AyanSinhaMahapatra** [comment]
We have fixed and merged support for this. Here's the detection results for  the example now:
[memrange.json.txt](https://github.com/nexB/scancode-toolkit/files/10345454/memrange.json.txt)
