### ISSUE TITLE
Investigate a way to avoid elf/dwarf parser platform dependencies

### ISSUE THREAD

**Issue by licodeli** [nexB/scancode-toolkit#1765]
### Description
Let's find a good way to handle the OS platform dependencies for elf and dwarf parsers.

One possible solution is:
https://github.com/eliben/pyelftools

**Comment by pombredanne** [comment]
The newer compiledcode plugin now uses pyelftools ... See https://github.com/nexB/scancode-plugins/blob/53067ec8adc19e4809912a3c31eb73d668b918c2/binary-analysis/scancode-compiledcode/setup.py#L46
Closing now!
