### ISSUE TITLE
Add new licenses from the spdx license list version 3.7

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1789]
Please update the scancode-toolkit licenses with the latest entries on the spdx license list.

The version 3.7 release of the license list is now tagged and live at https://spdx.org/licenses. Along with documentation updates and markup tweaks, 6 new licenses and exceptions were added to the list:
* etalab-2.0
* MulanPSL-1.0
* OGL-Canada-2.0
* SSH-OpenSSH
* SSH-short
* UCL-1.0

**Comment by pombredanne** [comment]
I ran these rom ScanCode virtualenv:
1. `mkdir spdx`
2. `python etc/scripts/synclic.py -s spdx spdx`
```
....
#####################################################
Same licenses:        395
Add to ScanCode:      7
Updated in ScanCode:  2
Added to External::   0
Updated in External:  0
#####################################################
```
3. manual review of updates/changes to correct them

**Comment by pombredanne** [comment]
Done
