### ISSUE TITLE
Rule "bsd-new_or_gpl-2.0_12.RULE" matches even though GPL alternative block isn't there

### ISSUE THREAD

**Issue by MartinPetkov** [nexB/scancode-toolkit#1795]
### Description
It's not clear to me why [this block](https://github.com/apache/beam/blob/4fa1501b377e70df0971ec4a4b8f585fd8f34a6c/LICENSE#L277-L301) matches the bsd-or-gpl rule, since it's missing the the "Alternatively, this software may be distributed under the terms of the GNU General Public License ("GPL") version 2 as published by the Free Software Foundation." blurb. The only difference I can see is that it says "JANINO" instead of "the copyright holders".

Steps to reproduce:
```
$ git clone https://github.com/apache/beam
$ cd beam && git checkout 4fa1501b377e70df0971ec4a4b8f585fd8f34a6c
$ scancode --verbose --license -n 12 --json-pp ./results.json --only-findings --info --strip-root --license-text ./LICENSE
$ cat ./results.json
```

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
Linux
* What version of scancode-toolkit was used to generate the scan file?
ScanCode version 3.1.1.post168.648281097
* What installation method was used to install/run scancode? (pip/source download/other)
Pip

**Comment by pombredanne** [comment]
All fixed and merged in develop. Thank you!
