### ISSUE TITLE
[RFC} Consider adding a new "non-commercial" license category

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1805]
### Description
It would be great  to add a new non-commercial license category

There are only a few license that prohibit commercial usage (like the CC NC licenses). There are however a serious restriction for any kind of usage beyond personal home-style usage and this would deserve its own category IMHO as this is typically problematic to reuse both in FOSS and proprietary software.

**Comment by pombredanne** [comment]
@DennisClark @leChasseur your input is mucho welcomed

**Comment by DennisClark** [comment]
@pombredanne    I need to give this some extended thought, since I am generally quite reluctant to create a new license category.  Isn't there already a "free restricted" ?

**Comment by DennisClark** [comment]
@pombredanne   On further reflection I really think we should stick with Free Restricted for licenses that prohibit commercial use but are otherwise free.

**Comment by mjherzog** [comment]
Closing because Free Restricted handles this case. It does not make sense to create new Categories for each type of restriction.

**Comment by mjherzog** [comment]
Moot
