### ISSUE TITLE
Release links are broken

### ISSUE THREAD

**Issue by bs-matil** [nexB/scancode-toolkit#1811]
### Description
Current releases don't show a correct artifact url. 

Additionally, it would be good if the installation page also shows the pip installation guide. 

e.g. pip install scancode-toolkit==3.0.2

**Comment by pombredanne** [comment]
@bs-matil Sorry for the inconvenience! You wrote:

> Current releases don't show a correct artifact url.

Can you leaborate a bit? Which URL is not shown in which place?

> Additionally, it would be good if the installation page also shows the pip installation guide.
> e.g. pip install scancode-toolkit==3.0.2

Good point. We are working on a new release so that definitely something to add!

**Comment by bs-matil** [comment]
e.g. Release https://github.com/nexB/scancode-toolkit/releases/tag/v3.0.2 links in the bottom show 1.0.o

**Comment by pombredanne** [comment]
These concerns have been addressed AFAIK. Closing now.
