### ISSUE TITLE
Old Issue Template

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#1814]
The page https://github.com/nexB/scancode-toolkit/blob/develop/ISSUE_TEMPLATE.md shows the following warning 

> You are using an old version of issue templates. Please update to the new issue template workflow

The [Learn More Link](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) says

> You can customize the issue template chooser that people see when creating a new issue in your repository by adding a config.yml file to the .github/ISSUE_TEMPLATE folder.

This is also valid for other [community checklist items](https://github.com/nexB/scancode-toolkit/community) that are currently unchecked, though they are present in the root folder.

**Comment by AyanSinhaMahapatra** [comment]
I'll go ahead and solve these? @pombredanne

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra thank you for catching this: please go for it!
