### ISSUE TITLE
Configuring with Python 3.7 fails due to no matching distribution found for future>=0.16.0

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#1817]
### Description

I'm trying to configure ScanCode (current `develop` branch) with Python 3.7 as part of my work on an [Alpine-based Docker image](https://github.com/sschuberth/docker-files/tree/alpine-miniconda3). However, running `./configure` fails with

```
Collecting future>=0.16.0 (from scancode-toolkit==3.1.2->-r /opt/scancode/etc/conf/requirements_base.txt (line 10))
  ERROR: Could not find a version that satisfies the requirement future>=0.16.0 (from scancode-toolkit==3.1.2->-r /opt/scancode/etc/conf/requirements_base.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for future>=0.16.0 (from scancode-toolkit==3.1.2->-r /opt/scancode/etc/conf/requirements_base.txt (line 10))
* Configuring Python ...
* Installing components ...
Traceback (most recent call last):
  File "/opt/scancode/etc/configure.py", line 552, in <module>
    install_3pp(configs, root_dir, thirdparty_dirs, quiet=quiet)
  File "/opt/scancode/etc/configure.py", line 266, in install_3pp
    run_pip(requirements, root_dir, tpp_dirs, quiet)
  File "/opt/scancode/etc/configure.py", line 292, in run_pip
    call(pcmd, root_dir)
  File "/opt/scancode/etc/configure.py", line 139, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "/opt/conda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/opt/scancode/bin/pip" install --upgrade --no-index --no-cache-dir --find-links="/opt/scancode/thirdparty" --requirement "/opt/scancode/etc/conf/requirements_base.txt" --requirement "/opt/scancode/etc/conf/dev/requirements_base.txt"' returned non-zero exit status 1.
```

Can this be because the is no `future-*py3*` file in `thirdparty/`?

### System configuration

For bug reports, it really helps us to know:
* What OS are you running on? Ubuntu Linux 18.04
* What version of scancode-toolkit was used to generate the scan file? n/a
* What installation method was used to install/run scancode? From Git.

**Comment by AyanSinhaMahapatra** [comment]
Encountered the same ERROR.

**Comment by Abhishek-Dev09** [comment]
@sschuberth : I have solved that #1819 to support py 3.7 . Don't worry i working on it. FYI , we support upto python 3.6.8 . You need to install with python 3.6.8

**Comment by sschuberth** [comment]
Oh, I wasn't aware that there's such a big difference between Python 3.6.8 and 3.7.x that requires changes to dependencies. Anyway, thanks @Abhishek-Dev09 for working on it!

**Comment by Pratikrocks** [comment]
I have python 3.6 along with python 3.7 , how can i explicitly configure with python 3.6
_

**Comment by ritiek** [comment]
@Pratikrocks This may a bit late but if you're on Linux you can symlink the `python` executable to point to `python3.6`. This should help:

```shell
$ sudo cp `which python`{,.bak}
$ sudo ln -s `which python3.6` `which python`
```

You could revert these changes by running:
```shell
$ sudo mv `which python.bak` `which python`
```

----------

Otherwise, if you're on Windows I'm not sure if this would work but try editing your $PATH variable such that the order of directories with the python 3.6 executable comes after python 3.7. This should then override the location of python 3.7 executable with python 3.6 executable.

**Comment by Pratikrocks** [comment]
Thanks a lot it worked

**Comment by Zainab-Fahim** [comment]
> @Pratikrocks This may a bit late but if you're on Linux you can symlink the `python` executable to point to `python3.6`. This should help:
> 
> ```shell
> $ sudo cp `which python`{,.bak}
> $ sudo ln -s `which python3.6` `which python`
> ```
> 
> You could revert these changes by running:
> 
> ```shell
> $ sudo mv `which python.bak` `which python`
> ```
> 
> Otherwise, if you're on Windows I'm not sure if this would work but try editing your $PATH variable such that the order of directories with the python 3.6 executable comes after python 3.7. This should then override the location of python 3.7 executable with python 3.6 executable.

Hey @ritiek, I'm relatively a beginner here. Could you please tell me what the following lines mean;
```shell
 $ sudo cp `which python`{,.bak}
 $ sudo ln -s `which python3.6` `which python`
 ``` 
what is `{,.bak}` and by `which python` you mean the python version right? (example: `Python 3.8.10` )
Thank You for your kind time.

**Comment by pombredanne** [comment]
Closing this in favor of tracking https://github.com/nexB/scancode-toolkit/issues/2836 instead.

@Zainab-Fahim sorry for the late reply! ... do you mind to enter a separate issue or a discussion so we can help you? https://github.com/nexB/scancode-toolkit/discussions
