### ISSUE TITLE
All Good First Issues List

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#1825]
## What are Good First Issues?

A [good first issue](https://github.com/nexB/scancode-toolkit/labels/good%20first%20issue) means it's recommended for people who **haven't contributed to our codebase before**.

## Short Step by Step Guide

- Maintainers label Good First Issues and Update Here 
- Browse Issues
- Claim an Issue
- Maintainer Assigns you to That Issue
- Create an Issue using [this format](https://github.com/nexB/scancode-toolkit/issues/new?assignees=&labels=solving+good+first+issue&template=--good-first-issue.md&title=) labeled [`Solving a Good First Issue`]
- Follow the steps in this [`Solving a Good First Issue`] 

## Documentation on Good First Issues

Refer the guide to [solving Good First Issues](https://scancode-toolkit.readthedocs.io/en/latest/contribute/long_running_issues.html#good-first-issue) in our documentation.

## All Good First Issues

> A list of Good First Issues and People Assigned to them

- [ ] #1758 @Iamshankhadeep 
- [x] #1759 
- [ ] #1746 
- [ ] #1627 
- [ ] #1381 
- [ ] #1380 
- [ ] #1378 
- [ ] #1377 
- [ ] #1283 
- [ ] #1003 
- [ ] #997 
- [x] #922
- [ ] #863
- [ ] #852
- [ ] #624  
- [ ] #595 
- [x] #514 
- [ ] #461 
- [ ] #366 
- [ ] #296 
- [ ] #254

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra  should this be closed in favor or only a dynamic listing based on the label?

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne Yes! This wasn't useful at all in hindsight.
