### ISSUE TITLE
Merge two scans of the same codebase using --from-json

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1843]
This may be a useful thing. Take for example that we have one info scan of a codebase and one package scan of the same codebase, this new function would merge the results of the two scans into one, where the info and package info for a resource in the codebase is combined.

**Comment by pombredanne** [comment]
This works nicely. Closing

**Comment by pombredanne** [comment]
For reference:
```
scancode -i samples/ --json-pp a.json
scancode -c samples/ --json-pp c.json
scancode -l samples/ --json-pp b.json
scancode --from-json a.json --from-json b.json --from-json c.json --json-pp d.json
less d.json 
```
