### ISSUE TITLE
Update scancode-toolkit github pages with new documentation links

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1849]
It's time to let visitors to https://github.com/nexB/scancode-toolkit to know about the latest documentation at https://scancode-toolkit.readthedocs.io/en/latest/ 

Please add a sentence under the first paragraph of https://github.com/nexB/scancode-toolkit#scancode-toolkit  to say

`Read more about ScanCode here:  https://scancode-toolkit.readthedocs.io/en/latest/ `

Please update each redundant wiki page in the collection at https://github.com/nexB/scancode-toolkit/wiki  to insert that same sentence and to remove the old wiki text. The goal is to have one place for the documentation.

**Comment by AyanSinhaMahapatra** [comment]
To sum up from our discussion in the [gitter chat](https://gitter.im/aboutcode-org/gsod-season-of-docs) -

- We are keeping all the wiki pages.
- Different links at different wiki pages, to their corresponding/closest resembling page in the RTD documentation, like the wiki page for comprehensive installation should point to the RTD install page. - A link to the main RTD page should also be there additionally.
- All the old text in the wikis are deleted

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark If [this Home Page](https://github.com/nexB/scancode-toolkit/wiki) looks fine, I'll go ahead and do the same in all the other pages.

**Comment by AyanSinhaMahapatra** [comment]
This PR #1851 adds [this commit](https://github.com/nexB/scancode-toolkit/pull/1851/commits/245e4abfe0715459d62d70e03c3e1783f8c29af1) to add the line you suggested in README.

**Comment by AyanSinhaMahapatra** [comment]
Wiki updated - 

- [x] Home
- [x] Comprehensive Installation
- [x] Development
- [x] Documentation
- [x] FAQ
- [ ] Google Summer of Code 2019
- [ ] How To: Add a post scan plugin
- [ ] How to: Add new license rules for enhanced detection
- [ ] How To: Extract archives
- [ ] How To: Format scan output
- [ ] How To: Run a scan
- [ ] How To: Set what will be detected in a scan
- [x] IDE Configuration
- [x] License Policy Plugin
- [x] Plugin architecture
- [ ] Plugin Architecture GSoC 2017 Final Report
- [x] Roadmap
- [x] Runtime performance reports
- [x] Support

**Comment by pombredanne** [comment]
that's great. Thanks!
