### ISSUE TITLE
Make the copyright holder value a single holder

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#186]
**Narrative**: Make the copyright holder value a single holder when there are multiple names in the statement vs multiple holder values for each name in the statement
**Context**: Discussion stems from #182 and #120. How do we want to viewing the copyright holder summary in the html-app
**Acceptance Criteria:** 
        - _Scenario 1:_ When multiple names appear in the statement the value for the holder would be all names in the statement with the Copyright and year part of the statement stripped out. i.e.: 
`Copyright (c) 2042 John Doe, Michael Foo and Jane Bar.` would return `John Doe, Michael Foo and Jane Bar` as the holder instead of 3 separate holders `John Doe`, `Michael Foo` and `Jane Bar`

**Comment by jdaguil** [comment]
Comments from #182: 
@pombredanne commented
@jdaguil splitting John Doe, Michael Foo and Jane Bar in three holders is theoretically possible but eventually hard. I would deal with this later. The hard part is recognizing actual names with some accuracy.
So for now, the focus is to get clean holders possibly composed of multiple names when they are so

**Comment by pombredanne** [comment]
@jeffmcaffer pinging you here so you will be notified when this is fixed

**Comment by pombredanne** [comment]
Done and merged in develop
