### ISSUE TITLE
Documentation build error

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1866]
### Description
See https://travis-ci.org/nexB/scancode-toolkit/jobs/627621941#L552
```
Warning, treated as error:

/home/travis/build/nexB/scancode-toolkit/docs/source/tutorials/how_to_visualize_scan_results.rst:30:undefined label: workbench_requirements (if the link has no caption the label must precede a section header)

The command "./scripts/sphinx_build_link_check.sh" exited with 2.

1.51s$ ./scripts/doc8_style_check.sh

The command "./scripts/doc8_style_check.sh" exited with 0.
```

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne @majurg 

Created these 3 PRs,

https://github.com/nexB/scancode-toolkit/pull/1867
https://github.com/nexB/aboutcode/pull/38
https://github.com/nexB/scancode-workbench/pull/419

**Comment by majurg** [comment]
@AyanSinhaMahapatra So I took care of https://github.com/nexB/aboutcode/pull/38 and https://github.com/nexB/scancode-workbench/pull/419 

Ill leave the merging of #1867 to @pombredanne

**Comment by AyanSinhaMahapatra** [comment]
@majurg Thanks!

**Comment by rpotter12** [comment]
@pombredanne @majurg This issue should be open again as these warning appeared again.
