### ISSUE TITLE
Provide an option in `extractcode` to extract sepecific extension files

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1870]
For instance, I would only want to extract `.rpm`, `.zip`, `.tar.gz`, but not `.jar` files.

The current `extractcode` does not have the ability for user to define which files do the user want to extract or ignore from the extraction.

**Comment by JRavi2** [comment]
Hey, can I work on adding this feature?

**Comment by majurg** [comment]
@JRavi2 Yes you can.

**Comment by JRavi2** [comment]
Okay, so I thinking of implmenting it like this:
The user while calling extractcode, would provide a 'filter' flag mentioning the extensions of the files he/she wants to extract,
`extractcode samples --filter=zip,tar`
And if no filter option is provided all the files in the given directory would be extracted
@majurg Does this sound okay?

**Comment by majurg** [comment]
@JRavi2 I think we are better off implementing this as `--ignore`, like `scancode` does. It is easier to reason about things this way, and we can specify multiple ignores, like `extractcode --ignore=*.tar.gz --ignore=*.jar`

**Comment by JRavi2** [comment]
@majurg You're right, `--ignore` sounds more appropriate. I'll implement it that way.
