### ISSUE TITLE
Failure to collect matched license text in some rare case with unicode

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1872]
### Description

When scanning this file https://github.com/go-gitea/gitea/blob/v1.10.2/public/vendor/plugins/pdfjs/web/locale/az/viewer.properties
with these options: `--license --license-text` the scan fails.

The failure happens exactly here:
https://github.com/nexB/scancode-toolkit/blob/b564c32fe116d9a26a4ca09b6b7ea551da60f85c/src/licensedcode/match.py#L1446
because of this weird Unicode thing:
https://gist.github.com/pombredanne/b90d0090bed9e9e976ba2ea454b02abd
which is not a bug per @vstinner in https://bugs.python.org/issue34723

Reported indirectly by @MTecknology following some chats at Debian IRC #licenses
 

```python
Python 3.6.8 (default, Dec 20 2019, 11:17:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a='İrəli'
>>> len(a)
5
>>> len(a.lower())
6
>>> import re
>>> re.split('\\W', a)
['İrəli']
>>> re.split('\\W', a.lower())
['i', 'rəli']
>>> [len(x) for x in re.split('\\W', a.lower())]
[1, 4]
>>> sum(len(x.lower()) for x in a)
6
>>> len(a.lower())
6
>>> list(a)
['İ', 'r', 'ə', 'l', 'i']
>>> list(a.lower())
['i', '̇', 'r', 'ə', 'l', 'i']
>>> [x.isalpha() for x in a.lower()]
[True, False, True, True, True, True]
```

**Comment by pombredanne** [comment]
the gist of the issue is that an uppercase string without punctuation characters may contain a punctuation once lowercased

**Comment by jonassmedegaard** [comment]
Why lowercase?

If purpose of lowercasing is to normalize - i.e. to reach a form where possible to reliably compare agnostic to variation in representation of each character, then my understanding is that the the proper unicode form for that is foldcase: https://www.w3.org/International/wiki/Case_folding

**Comment by jonassmedegaard** [comment]
...but (depending on what exactly it is you want to do) it seems the Python "foldcase" function "cannot pass the Turkey Test" - as discussed (including a solution - which may or may not address the issue you are having here): https://stackoverflow.com/questions/40348174/should-i-use-python-casefold

**Comment by pombredanne** [comment]
@jonassmedegaard the purpose of lowecasing here is indeed casefolding. And casefolding is indeed what happens. But that's not a Python bug after all, this is instead a standard behavior for Unicode in this specific case of Turkish characters. The sequence of events in the scancode side:
1. to find licenses the scanned text (a.k.a. the "query") is broken into words and lowercased. All punctuation except the + are used together with spaces as word/token separators.  
2. once a match is found we recover the exact matched text by breaking again into words this time keeping punctuation and case intact and reconstruct the matched text based on the positions of tokens matched in 1.

In this specific case and rare case, Unicode states that the lowercase/casefolded version of the Turkish `'İ'` is folder in two characters   `'i', '̇'` where the second character is a reported as a punctuation. Since we have an extra punctuation in the set of tokens in 1., it was not aligned  anymore with the list of tokens from 2.... hence the error.

**Comment by inishchith** [comment]
@pombredanne I tried to reproduce the issue, found out that the scan succeeds and extracted the license text correctly. ( output below ).

```json
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "3.1.1",
      "options": {
        "input": [
          "../viewer.properties"
        ],
        "--json-pp": "output.json",
        "--license": true,
        "--license-text": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2020-01-08T062020.715699",
      "end_timestamp": "2020-01-08T062038.082592",
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "viewer.properties",
      "type": "file",
      "licenses": [
        {
          "key": "apache-2.0",
          "score": 100.0,
          "name": "Apache License 2.0",
          "short_name": "Apache 2.0",
          "category": "Permissive",
          "is_exception": false,
          "owner": "Apache Software Foundation",
          "homepage_url": "http://www.apache.org/licenses/",
          "text_url": "http://www.apache.org/licenses/LICENSE-2.0",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:apache-2.0",
          "spdx_license_key": "Apache-2.0",
          "spdx_url": "https://spdx.org/licenses/Apache-2.0",
          "start_line": 3,
          "end_line": 13,
          "matched_rule": {
            "identifier": "apache-2.0_12.RULE",
            "license_expression": "apache-2.0",
            "licenses": [
              "apache-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "3-seq",
            "rule_length": 119,
            "matched_length": 85,
            "match_coverage": 71.43,
            "rule_relevance": 100
          },
          "matched_text": "# Licensed under the Apache License, Version 2.0 (the \"License\");\n# you may not use this file except in compliance with the License.\n# You may obtain a copy of the License at\n#\n#     http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable law or agreed to in writing, software\n# distributed under the License is distributed on an \"AS IS\" BASIS,\n# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n# See the License for the specific language governing permissions and\n# limitations under the License."
        }
      ],
      "license_expressions": [
        "apache-2.0"
      ],
      "scan_errors": []
    }
  ]
}
```

Please let me know if I got something wrong.

Thanks!

**Comment by pombredanne** [comment]
@inishchith You did not get anything wrong: the file at https://raw.githubusercontent.com/go-gitea/gitea/e88d67b774ae615208b25133c299f2d50b3a018b/public/vendor/plugins/pdfjs/web/locale/az/viewer.properties scans alright on Python 2 and fails on Python 3:
> "scan_errors": [
> "ERROR: for scanner: licenses:\nERROR: Unknown error:\nTraceback (most recent call last):\n  File \"/home/po/scancode-toolkit/src/scancode/interrupt.py\", line 92, in interruptible\n    return NO_ERROR, func(*(args or ()), **(kwargs or {}))\n  File \"/home/po/scancode-toolkit/src/scancode/api.py\", line 201, in get_licenses\n    matched_text = match.matched_text(whole_lines=True, highlight=False)\n  File \"/home/po/scancode-toolkit/src/licensedcode/match.py\", line 564, in matched_text\n    highlight_not_matched=highlight_not_matched, _usecache=_usecache)\n  File \"/home/po/scancode-toolkit/src/licensedcode/match.py\", line 1597, in get_full_matched_text\n    location, query_string, dictionary=idx.dictionary)\n  File \"/home/po/scancode-toolkit/src/licensedcode/match.py\", line 1421, in tokenize_matched_text\n    _tokenize_matched_text(location, query_string, dictionary))\n  File \"/home/po/scancode-toolkit/src/licensedcode/match.py\", line 1446, in _tokenize_matched_text\n    assert len(tokenized) == 1, repr((is_text, token_str, tokenized))\nAssertionError: (True, '\u0130r\u0259li', ['i', 'r\u0259li'])\n"
      ]


I have a fix that I will commit shortly.

**Comment by pombredanne** [comment]
@inishchith and BTW thank you ++ for taking the time to run a test there ! :bowing_man:

**Comment by inishchith** [comment]
@pombredanne you're welcome ;)

**Comment by pombredanne** [comment]
BTW this issue seems well known as  "The Turkish-I Problem" See:

- https://blog.codinghorror.com/whats-wrong-with-turkey/
- https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/ms973919(v=msdn.10)?redirectedfrom=MSDN#the-motivation-the-turkish-i-problem 
- https://en.wikipedia.org/wiki/Dotted_and_dotless_I#In_computing

**Comment by pombredanne** [comment]
This has been fixed and merged in develop
