### ISSUE TITLE
Promote Python 3.6 to primary platform (vs Python 2.7)

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#1874]
### Description
The installation documentation currently references a choice of Python 2.7 or 3.6, but most of the specific steps reference Python v2.7. Shouldn't the primary use case now be Python 3.6 since Python 2.7 is EOL as of the new year.

### Link to Documentation Pages

https://github.com/nexB/scancode-toolkit/docs/source/getting-started/install.rst
https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html

### Select Category
-  General Improvement

**Comment by AyanSinhaMahapatra** [comment]
I'm working on this. Thanks.

**Comment by AyanSinhaMahapatra** [comment]
PR #1851 added to address this issue.
