### ISSUE TITLE
Scanning a path with "%" fails on Windows

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#1876]
### Description

At least with ScanCode 3.0.2, scanning a path that contains "%" (the percent character) fails on Windows:

```
$ scancode --json-pp - --license NPM\%40xtuc\long\4.2.2\package.json
Usage: scancode [OPTIONS] <input> <OUTPUT FORMAT OPTION(s)>
Try 'scancode --help' for help on options and arguments.

Error: Invalid value for "input": Path "NPM\0xtuc\long\4.2.2\package.json" does not exist.
```

Note the `%40xtuc` in the input path vs. `0xtuc` in the error message.

Background: To guard against characters that are invalid / special on some file systems, [ORT](https://github.com/heremaps/oss-review-toolkit) percent-encodes charaters like `@` when downloading source code in order to scan it. At the example of the `long` NPM package version 4.2.2 from the `@xtuc` scope, it gets downloaded into a directory named "NPM\%40xtuc\long\4.2.2" where `@` is percent-encoded as `%40`.

### How To Reproduce

This can *only* be reproduced on *Windows*, it works on Linux. Also, I was only able to reproduce it with ScanCode version 3.0.2, as versions 3.1.x have [another issue](https://github.com/nexB/scancode-toolkit/issues/1875) on Windows.

1. Create a directory with "%40" as part of its name.
2. Create a file to scan within that directory.
3. Point ScanCode at that file to scan.

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Windows 10 x64
* What version of scancode-toolkit was used to generate the scan file? 3.0.2
* What installation method was used to install/run scancode? Git

**Comment by sschuberth** [comment]
Possibly related ScanCode issues: https://github.com/nexB/scancode-toolkit/issues/442, https://github.com/nexB/scancode-toolkit/issues/542

**Comment by pombredanne** [comment]
@sschuberth thanks for that report.
