### ISSUE TITLE
Recent scan detects Simplified BSD as unknown

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1887]
A recent scan of istio-1.3.5 (via scancode.io) detected the license in 

https://github.com/istio/istio/blob/1.3.5/vendor/github.com/russross/blackfriday/LICENSE.txt

as `unknown`.   Note that the file starts with the sentence

`Blackfriday is distributed under the Simplified BSD License:` 

followed by a copyright statement and what appears to be the standard bsd-simplified text.

**Comment by pombredanne** [comment]
@DennisClark thanks.. This is because `"distributed under"` in "distributed under the Simplified BSD License" is reported solo as a license intro which taken alone is unknown.

**Comment by pombredanne** [comment]
This has been fixed with https://github.com/nexB/scancode-toolkit/commit/01feaad2f4a6ea2f422dcec520ab2348de23e7f3 and merged in develop.
