### ISSUE TITLE
New user signup returns "PermissionError"

### ISSUE THREAD

**Issue by theOpetunde** [nexB/scancode-toolkit#1892]
### Description

New users trying to sign-up through this link http://ec2-52-53-177-18.us-west-1.compute.amazonaws.com/en-us/registration/signup_volunteer/ get permission error after filling out all the necessary required details and licking on the "sign-up" button

### How To Reproduce

1) Go to http://ec2-52-53-177-18.us-west-1.compute.amazonaws.com/en-us/registration/signup_volunteer/

2) Click on "Sign up" button at the upper right corner of the webpage

3) Fill in the necessary and required details

4) Click on the "Sign-up" button at the end of the form

5) The system returns a "PermissionError" as displayed in the screenshot below

![anita borg](https://user-images.githubusercontent.com/60391138/73954949-d5907d80-4902-11ea-89bc-a0d3234111eb.PNG)

This error was detected using Windows OS and Chrome Browser

**Comment by pombredanne** [comment]
@theOpetunde is this a mistake of yours? If so you can entirely delete this

**Comment by theOpetunde** [comment]
my apologies. It was intended for another project. I'll delete it right away

**Comment by theOpetunde** [comment]
It appears I can only close an issue. There is no delete issue option

**Comment by pombredanne** [comment]
@theOpetunde that's fine we are cool! I though for as ec this was spam. this is closed alright, no harm done!
Now you need to try ScanCode and provide some feedback! :smiley:
