### ISSUE TITLE
Add new "bad" licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1899]
See https://github.com/ErikMcClure/bad-licenses by @ErikMcClure
This is a list of off licenses that we should detect

**Comment by msrb** [comment]
One more here: https://github.com/landondyer/kasm/blob/master/LICENSE

It's "Anyone But Richard M Stallman" (ABRMS) license.

**Comment by hp77-creator** [comment]
I would like to work on this issue @pombredanne, Can you guide me what I should do?

**Comment by pombredanne** [comment]
@msrb thanks!
@hp77-creator Sure this is about adding new licenses and/or license detection rules. The process is explained there https://scancode-toolkit.readthedocs.io/en/latest/how-to-guides/index.html
