### ISSUE TITLE
bsd test with no-op non-endorsement clause is effectively freebsd (not bsd-new)

### ISSUE THREAD

**Issue by jonassmedegaard** [nexB/scancode-toolkit#1900]
These file src/licensedcode/data/rules/bsd-new_141.RULE contains this as 3rd clause:
>  * Neither the name of  nor the names of its
>    contributors may be used to endorse or promote products derived
>    from this software without specific prior written permission.

Sure, it is "just a typo" that organisation name is missing - but effect is that the clause _cannot_ hold any meaning at all: which names is it that cannot be used to endorse? the name [undef] and the names of contributors to [undef] -> noone!

I think this test should legally be categorized as BSD-2-Clause.

Even better was if it was classified BSD-2-Clause with metadata hinting that it contains a dangling no-op 3rd clause that seems to be a typo.

**Comment by pombredanne** [comment]
@jonassmedegaard AFAICR this is actually done on purpose such that we can detect as a 100% match things such:
```
  * Neither the name of FOOBAR nor the names of its
    contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.
```
Did you see an actual match to the text without a name in the wild?

**Comment by jonassmedegaard** [comment]
No, I triedd but failed to locate any samples in the wild.

Are you saying that I am reading the yaml file wrong or that in other ways this case is unsuitable for testing?

I discovered it while reusing the tests of scancode-toolkit for testing accuracy of licensecheck - and seem to recall that you told me to simply check all the files with a corresponding yaml file. If there is more to it than that, then it is probably helpful with a bit of documentation somewhere - to also help other competitors trying do do what I do ;-)

**Comment by pombredanne** [comment]
> Are you saying that I am reading the yaml file wrong or that in other ways this case is unsuitable for testing?

Let's put it this way: say that you have found all the words in this rule in this sequence and that there is typically extra words to mention the name in the middle, then this is a proper bsd-new match for scancode (in this case because of the extra word this will be reported as less than 100% match).

ScanCode does eventually exhaustive pair-wise diffs so it will find added and removed words .

 > I discovered it while reusing the tests of scancode-toolkit for testing accuracy of licensecheck - and seem to recall that you told me to simply check all the files with a corresponding yaml file. If there is more to it than that, then it is probably helpful with a bit of documentation somewhere - to also help other competitors trying do do what I do ;-)

For your sanity, I hope you are not rewriting everything scancode does in Perl ;)

**Comment by pombredanne** [comment]
> If there is more to it than that, then it is probably helpful with a bit of documentation somewhere - to also help other competitors trying do do what I do ;-)

There is not more to it than that, but again since we do a diff all rules files used for detection are akin to a fuzzy pattern (except that they are not tagged as patterns would). If you use regexes, this is going to be a challenge for sure to get the same results.

**Comment by jonassmedegaard** [comment]
I think I understand. So this is not a bug, just a flaw in how I (ab)use the testsuite for different (regex-based) detection technique.

**Comment by jonassmedegaard** [comment]
...and to answer your (non-)question: No, I don't expect to mimick everything in scancode-toolkit - I expect to have something reusable for multiple purposes (which scancode-toolkit might be extended to do as well, but that would have to wait for someone else doing it, or for me learning Python)
