### ISSUE TITLE
GPLv2 licensed file recognized as GPLv1 and GPLv3

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1904]
### Description
https://github.com/Azure/azure-iot-sdk-c/blob/master/build_all/arduino/Makefile.iot

is a GPLv2 file, but scancode says:

      "license_expressions": [
        "gpl-1.0-plus",
        "gpl-3.0"

### How To Reproduce

> Tell us how to reproduce the issue. 

1. get scancode
2. get that file I linked
3. run scancode

### System configuration

> For bug reports, it really helps us to know:

Fedora 30

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
This has been fixed and merged in develop with https://github.com/nexB/scancode-toolkit/commit/caf97a5c38d579e02edb286e0945cf2eb5e70baf and https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/gpl-2.0_849.RULE
Test added with b5f6efbb851627164773348c3d28154c3cf4a160
