### ISSUE TITLE
libwebsockets: static linking exception not recognized

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1905]
### Description

Several files in older versions of libwebsockets have a "static linking exception":

https://libwebsockets.org/git/libwebsockets/tree?id=e6bd6296bd9f90f6a264ea9e69825552e8702490

### How To Reproduce

> Tell us how to reproduce the issue. 

1. download older version of libwebsockets
2. run scancode

### System configuration

> For bug reports, it really helps us to know:

Linux Fedora 30

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
This has been fixed and merged in develop
