### ISSUE TITLE
libwebsockets: LGPL 2.1-only recognized as or-later 

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1906]
### Description

https://libwebsockets.org/git/libwebsockets/tree/lib/output.c?id=e6bd6296bd9f90f6a264ea9e69825552e8702490

is LGPL-2.1-only but Scancode sees:

LGPL-2.1-only
LGPL-2.1-or-later
Other Copyleft Licenses

### How To Reproduce

1. download older version of websockets
2. run scancode

### System configuration

> For bug reports, it really helps us to know:

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
This has been fixed and merged in develop
