### ISSUE TITLE
bzip2 1.0.5: recognized as "Free unknown"

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1908]
### Description

bzip2.c is recognized as "free unknown":

      "license_expressions": [
        "bzip2-libbzip-2010",
        "bsd-new",
        "free-unknown"
      ],

### How To Reproduce
1. download bzip2 1.0.5
2. run scancode

### System configuration

> For bug reports, it really helps us to know:

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
Fixed in develop
