### ISSUE TITLE
Incorrect copyright detected: "copyright owner as Not a Contribution. Contributor"

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#191]
OS : windows 7 - 64 bit
I've updated my scancode to the latest version available.

RPM download URL - `http://bay.uchicago.edu/centos-vault/6.4/cr/x86_64/Packages/libreoffice-wiki-publisher-4.0.4.2-9.el6.x86_64.rpm`

file location : `libreoffice-wiki-publisher-4.0.4.2-9.el6.x86_64\libreoffice-wiki-publisher-4.0.4.2-9.el6.x86_64\usr\lib64\libreoffice\share\extensions\wiki-publisher\license\THIRDPARTYLICENSEREADME.html`

In the lines 59, 69, 78, 87 `invalid copyrights` are found :

```
Path                                               What Start Line  End Line        Info
C:/doc/temporary/delete/THIRDPARTYLICENSEREADME.html    Copyright   56  96      copyright owner as Not a Contribution. Contributor
copyright owner as Not a Contribution. Contributor
copyright owner as Not a Contribution. Contributor
copyright owner as Not a Contribution. Contributor
```

**Comment by pombredanne** [comment]
This has been fixed in #790
Thank you!
