### ISSUE TITLE
cmake: agpl false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1910]
### Description
For cmake the files:

cmake-3.4.1/Source/cmCommandArgumentParser.cxx
cmake-3.4.1/Source/cmCommandArgumentParserTokens.h

are recognized as AGPL-3.0-or-later. They are not.

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

Fedora 30

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
Fixed and merged in develop. Thanks!
