### ISSUE TITLE
iptables: GPL-2.0-only recognized as GPL-2.0-or-later

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1911]
### Description

The following files in iptables 1.4.10 are recognized as both GPL-2.0-only and GPL-2.0-or-later but are GPL-2.0-only:

iptables-1.4.10/extensions/libipt_ECN.c
iptables-1.4.10/ip6tables-restore.c
iptables-1.4.10/ip6tables-save.c
iptables-1.4.10/iptables-xml.c

There are more files inside iptables 1.4.10 that have the same pattern.

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

Fedora 30

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
Fixed and merged in develop. Thanks!
