### ISSUE TITLE
libtool 2.2.10: libtool exception not recognized

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1912]
### Description

libtool-2.2.10/libltdl/argz.c

has the libtool exception, but scancode sees it as "unknown".

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:
Fedora 30

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
This has been fixed and merged in develop, thank you!
