### ISSUE TITLE
linux 2.6.39: GPL2 file recognized as GPL1, GPL2 and GPL3

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1914]
### Description

Linux kernel, v2.6.39

arch/arm/mach-s5pc100/gpiolib.c

is recognized as GPL 1, GPL 2 and GPL 3

The following rules were triggered:

            "identifier": "gpl-1.0_11.RULE",

            "identifier": "gpl-3.0_123.RULE", (line 280)

These are triggered because of variable names called "GPL0" through "GPL4":

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/arm/mach-s5pc100/gpiolib.c?h=linux-2.6.39.y#n280

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

Fedora 30
ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
This has been fixed and merged  in develop, thank you!
