### ISSUE TITLE
linux 2.6.39: GPL2-or-later recognized as GPL-3-or-later

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1915]
### Description

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/wireless/atmel.h?h=linux-2.6.39.y

is recognized as GPL-3.0-or-later

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

ScanCode version 3.1.1.post337.16377111fe

**Comment by armijnhemel** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/wireless/atmel_cs.c?h=linux-2.6.39.y

Also, it should be interesting to note that at the end of the file there is also a license text:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/wireless/atmel_cs.c?h=linux-2.6.39.y#n261

**Comment by pombredanne** [comment]
Thanks. All fixed and merged in develop

> Also, it should be interesting to note that at the end of the file there is also a license text:

Note that ScanCode always scans everything .
