### ISSUE TITLE
mtd-utils: GPL3 false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1917]
### Description

http://git.infradead.org/mtd-utils.git/blob/aea36417067dade75192bafa03af70b6eb2677b1:/flash_erase.c#l79

is confusing scancode, which thinks it is GPL1, GPL2 and GPL3. There is no mention of GPL3

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

ScanCode version 3.1.1.post337.16377111fe

**Comment by armijnhemel** [comment]
Other files in mtd-utils 1.5.2 have similar issues:

mtd-utils-1.5.2/mtdpart.c
mtd-utils-1.5.2/nanddump.c

etc.

**Comment by pombredanne** [comment]
All fixed and merged in develop. Thanks!
