### ISSUE TITLE
ntp-4.2.6p3: AGPL-3.0-or-later false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1918]
### Description

http://repository.timesys.com/buildsources/n/ntp/ntp-4.2.6p3/

ntp-4.2.6p3/sntp/libopts/genshell.c

is recognized as AGPL, but it is not.

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:
ScanCode version 3.1.1.post337.16377111fe

**Comment by armijnhemel** [comment]
ntp-4.2.6p3/sntp/libopts/genshell.h

**Comment by pombredanne** [comment]
Fixed and merged in develop. Now reported as gpl-3.0-plus
