### ISSUE TITLE
OpenVPN 2.3.4: GPL-1.0-or-later false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1919]
### Description

openvpn-2.3.4/contrib/pull-resolv-conf/client.up

is recognized as GPL-1.0-or-later but it is not.

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

ScanCode version 3.1.1.post337.16377111fe

**Comment by pombredanne** [comment]
Fixed and merged in develop
