### ISSUE TITLE
MIT license not seperated from copyrights

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#192]
os : windows 7 64-bit
I've updated scancode to the latest version available.

download URL for the package : `https://api.nuget.org/packages/respond.1.4.2.nupkg`
[respond.js.txt](https://github.com/nexB/scancode-toolkit/files/87794/respond.js.txt)

one of the copyrights from the line 24 in the above file  is detected as `(c) Scott Jehl. MIT Lic.` where `MIT Lic` is license but not a copyright.

**Comment by pombredanne** [comment]
@rakeshbalusa the best we can here would be IMHo to have a license rule for `MIT Lic` and at some time remove detected licenses from detection copyright or the inverse. This is very hard here to say that MIT is not and organization but a license.

**Comment by balusarakesh** [comment]
I feel that this should not be our concern, since the author of the file put a `license in a copyright` that too a very vague one `MIT Lic.`
