### ISSUE TITLE
socat: font exception false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1924]
### Description

related to #1920 and #1921 

socat-2.0.0-b4/filan.h
is recognized as PS-or-PDF-font-exception-20170817 and GPL-2.0-only but it is GPL-2.0-only only

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
Fixed and merged in develop
