### ISSUE TITLE
tcpdump-4.1.1: Apache 2 false positive/GPL-2.0-only false positive/GPL-2.0-or-later false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1925]
### Description

tcpdump-4.1.1/print-stp.c

is recognized as:

Apache-2.0
BSD-3-Clause
GPL-2.0-only
GPL-2.0-or-later

but the header is:

/*
 * Copyright (c) 2000 Lennert Buytenhek
 *
 * This software may be distributed either under the terms of the
 * BSD-style license that accompanies tcpdump or the GNU General
 * Public License
 *
 * Format and print IEEE 802.1d spanning tree protocol packets.
 * Contributed by Lennert Buytenhek <buytenh@gnu.org>
 */

It does not mention GPL version 2, or GPL version 2 or later or Apache.

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
This has been fixed and merged in develop.
