### ISSUE TITLE
tcpdump 4.1.1: GPL-2.0-or-later false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1926]
### Description

tcpdump-4.1.1/win32/Include/getopt.h

is reported to be:

GPL-2.0-or-later
LGPL-2.0-or-later
Other Copyleft Licenses

but only LGPL-2.0-or-later applies.

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
This has been fixed and merged in develop.
