### ISSUE TITLE
U-Boot 2010.06: GPL-3 false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1927]
### Description

u-boot-2010.06/arch/powerpc/cpu/ppc4xx/4xx_pci.c

GPL-2.0-only
GPL-2.0-or-later
GPL-3.0-only
IBM-pibs
Unknown License reference
unknown

but only GPL-2.0-only and the IBM or the unknown licenses seem to be correct.

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
This has been fixed and merged in develop. Thanks!This has been fixed and merged in develop
