### ISSUE TITLE
U-Boot: GPL-1.0-only, GPL-2.0-only and GPL-3.0-only false positives

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1928]
### Description

u-boot-2010.06/board/netphone/netphone.c

recognized as:

GPL-1.0-only
GPL-2.0-only
GPL-2.0-or-later
GPL-3.0-only

but the file is GPL-2.0-only only

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by armijnhemel** [comment]
u-boot-2010.06/board/netta2/netta2.c
u-boot-2010.06/board/stx/stxxtc/stxxtc.c

**Comment by pombredanne** [comment]
Good catch!
there are a bunch of defines and symbols GPL0, GPL1, GPL2 and GPL3 that are the sources of the false positives

```
125 #define GPL1_0000       0x00000000
126 #define GPL1_0001       0x00040000
127 #define GPL1_1110       0x00080000
128 #define GPL1_1111       0x000C0000
129 
130 #define GPL2_0000       0x00000000
131 #define GPL2_0001       0x00010000
132 #define GPL2_1110       0x00020000
133 #define GPL2_1111       0x00030000
134 
135 #define GPL3_0000       0x00000000
136 #define GPL3_0001       0x00004000
137 #define GPL3_1110       0x00008000
138 #define GPL3_1111       0x0000C000
```

**Comment by pombredanne** [comment]
This has been fixed and merged in develop. Thanks!
