### ISSUE TITLE
U-Boot: LGPL-3.0-only false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1929]
### Description

> Please leave a brief description of the bug or feature request:

u-boot-2010.06/doc/README.mpc8349itx

recognized as LGPL3 but it is just the name of a board jumper

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
This has been fixed and merged in develop
