### ISSUE TITLE
which: GPL-2.0-only false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1931]
### Description

which-2.20/bash.c

is recognized as GPL-2.0-only but it should be GPL-2.0-or-later

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
This has been fixed and merged in develop
