### ISSUE TITLE
zlib 1.2.5: LGPL false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1933]
### Description

zlib-1.2.5/old/as400/compile.clp

LGPL is a variable somewhere in the code:

             DCL        VAR(&SRVLIB) TYPE(*CHAR) LEN(10) +
                          VALUE('LGPL')                         /* Service program library. */

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
This has been merged in develop. Thanks!
