### ISSUE TITLE
Incorrect hyperlink in Pull Requests

### ISSUE THREAD

**Issue by Gaupeng** [nexB/scancode-toolkit#1934]
### Description

> A brief description of the Documentation Improvement or New Section request.

While creating a pull request, one of the checkmarks suggests to run tests locally
> Tests pass -- look for a green checkbox heavy_check_mark a few minutes after opening your PR
Run [tests](https://aboutcode.readthedocs.io/en/latest/scancode-toolkit/contribute/contrib_dev.html#running-tests) locally to check for errors.

However the link goes to a page that does not exist. The correct link to that would be::
https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#scancode-toolkit-developement-running-tests

### Select Category

-  Inconsistency [x]
-  New Section Request []
-  General Improvement []
-  Typo/Mistakes []
-  Other []

**Comment by AyanSinhaMahapatra** [comment]
Hey, I think this was fixed some days ago by this [commit](https://github.com/nexB/scancode-toolkit/commit/9530931c3016f8b5c04b225a8cce96cfd1de2cba).

Basically, the Pull Request Template is located [here](https://github.com/nexB/scancode-toolkit/blob/develop/.github/PULL_REQUEST_TEMPLATE.md). 

Is this still valid?

**Comment by Gaupeng** [comment]
Ah, should have checked for it. Thanks! Closing this now.
