### ISSUE TITLE
GPL license is not detected

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#194]
OS : windows 7 - 64 bit
I've updated my scancode to the latest version available.

RPM file download URL - `http://bay.uchicago.edu/centos-vault/6.4/cr/x86_64/Packages/libreoffice-sdk-doc-4.0.4.2-9.el6.x86_64.rpm`

issue file path : `libreoffice-sdk-doc-4.0.4.2-9.el6.x86_64.rpm\usr\lib64\libreoffice\sdk\docs\cpp\ref\search\search.js`

In the line 6 in this text the GPLis not detected:
```
   // The code in this file is loosly based on main.js, part of Natural Docs,
// which is Copyright (C) 2003-2008 Greg Valure
// Natural Docs is licensed under the GPL.
```

**Comment by rakeshbalusa** [comment]
@pombredanne  I'm trying to add a new  RULE  for the above issue `is licensed under the GPL` but it is affecting other test cases which has the same text and they are failing. what am I supposed to do?

**Comment by balusarakesh** [comment]
#199 issue fixed.
