### ISSUE TITLE
Test for Python 3.7 and Python 3.8 on CI

### ISSUE THREAD

**Issue by ritiek** [nexB/scancode-toolkit#1958]
Currently, Travis CI and Azure Pipelines run checks only on Python 2.7 and Python 3.6. However, newer Python minor releases can sometimes bring out breaking changes, which means that ScanCode could fail to run properly on such Python versions. It should be a good idea to also add support for Python 3.7 and Python 3.8 on our CI to make sure ScanCode runs as expected on these Python versions too.

----------

A [good first issue](https://github.com/nexB/scancode-toolkit/labels/good%20first%20issue)
means it's recommended for people who **haven't contributed to our codebase before**.
If you've solved a good first issue and want to help with more, you are welocome too!

If that's you, we're interested in helping you take the first step and can answer questions and
help you out as you do. Note that we're especially interested in contributions from people from
groups underrepresented in free and open source software!

We feel that the process of solving easy issues is great for new contributors, as they help in
understanding the codebase, building up confidence and get to know the Organization closely.

Thanks for deciding to contribute and welcome to ScanCode Toolkit. 💝

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update
**within a week** of claiming a good-first-issue. We're happy to keep it assigned to you for longer
if you update us with a request for more time or help, but if we don't see any activity a week
after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can
easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://github.com/nexB/scancode-toolkit/labels/good%20first%20issue). Thanks!

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Make sure you've already claimed this issue from the
  [Good First Issues List](https://github.com/nexB/scancode-toolkit/issues/1825) and you've been
  assigned to this Issue by a maintainer. You should have your name beside the issue,
  in the list, added by a maintainer.

- [ ] **Reproduce** Try to reproduce the problem in the most minimal way with a command line
  invocation of scancode as outlined above, trying to find a few files that make this fail.

- [ ] **Create a Unit test** Once you have a minimally reproducible problem, create a unit test
  (that is failing for now) that reproduces the problem. Assert the things that should be there
  in the results.

- [ ] **Come up with a Solution** Look at the failure trace and try to understand why this is not
  working and which places the code may need fixing.

- [ ] 📝 **Code your Solution**

- [ ] 📝 **Run the tests locally**
  Refer [Documentation](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests)

- [ ] 💾 **Commit and Push** your changes. Do check out this documentation on 
  [writing good commit messages](https://aboutcode.readthedocs.io/en/latest/aboutcode-docs/writing_good_commit_messages.html) 

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

    1. If you are familiar with the terminal or would like to learn it,
       [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
       on how to send a pull request using the terminal.

    2. You can also go to your Fork of ScanCode Toolkit and open a pull request from the branch you've pushed to.
       Always create the Pull Request with the develop branch, unless otherwise instructed by maintainers. 

- [ ] Make Sure all the Tests Pass

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

**Comment by Abhishek-Dev09** [comment]
@ritiek : We deosn't support python beyond 3.6.8 . This issue already created https://github.com/nexB/scancode-toolkit/issues/1817 . And we are working on it.
