### ISSUE TITLE
Update macOS image on Azure pipelines

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1964]
The macOSX 10.13 VM are being retired.
```
##[error]This job was temporarily blocked because it uses a Microsoft hosted agent (MacOS-10.13) that will be permanently removed on March 23rd, 2020.  See https://aka.ms/blocked-hosted-agent for more information.
,##[error]The remote provider was unable to process the request.
```
See https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/

We need to replace the 10.13 image with the 10.14 in our azure pipelines

**Comment by TG1999** [comment]
Hi, I checked the azure-pipelines.yml it has both the images 10.13 and 10.14 so should I just remove that 10.13, since 10.14 is already there

**Comment by pombredanne** [comment]
> so should I just remove that 10.13, since 10.14 is already there

@TG1999 yes :+1:
