### ISSUE TITLE
./configure command causes error with exit status 1.

### ISSUE THREAD

**Issue by nitish81299** [nexB/scancode-toolkit#1966]
### Description

Trying to setup scancode-toolkit using `./configure` command.

```
Collecting future>=0.16.0 (from scancode-toolkit==3.1.2->-r /home/nitish/dev/Projects/scancode-toolkit/etc/conf/requirements_base.txt (line 10))
  ERROR: Could not find a version that satisfies the requirement future>=0.16.0 (from scancode-toolkit==3.1.2->-r /home/nitish/dev/Projects/scancode-toolkit/etc/conf/requirements_base.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for future>=0.16.0 (from scancode-toolkit==3.1.2->-r /home/nitish/dev/Projects/scancode-toolkit/etc/conf/requirements_base.txt (line 10))
Traceback (most recent call last):
  File "/home/nitish/dev/Projects/scancode-toolkit/etc/configure.py", line 552, in <module>
    install_3pp(configs, root_dir, thirdparty_dirs, quiet=quiet)
  File "/home/nitish/dev/Projects/scancode-toolkit/etc/configure.py", line 266, in install_3pp
    run_pip(requirements, root_dir, tpp_dirs, quiet)
  File "/home/nitish/dev/Projects/scancode-toolkit/etc/configure.py", line 292, in run_pip
    call(pcmd, root_dir)
  File "/home/nitish/dev/Projects/scancode-toolkit/etc/configure.py", line 139, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/home/nitish/dev/Projects/scancode-toolkit/bin/pip" install --upgrade --no-index --no-cache-dir --find-links="/home/nitish/dev/Projects/scancode-toolkit/thirdparty" --requirement "/home/nitish/dev/Projects/scancode-toolkit/etc/conf/requirements_base.txt"' returned non-zero exit status 1
```
### How To Reproduce
1) Cd in to cloned repo.
2) run `./configure`
3) See the error 

### System configuration

* What OS are you running on? (Windows/MacOS/Linux)
Manjaro 
* What version of scancode-toolkit was used to generate the scan file?
3.1.2
* What installation method was used to install/run scancode? (pip/source download/other)
[Git clone](https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#installation-from-source-code-git-clone)

**Comment by majurg** [comment]
@nitish81299 What version of python are you using?

**Comment by nitish81299** [comment]
> @nitish81299 What version of python are you using?

I am using python 3.8.1, but also tested the build with virtualenvironment of version 3.6.

**Comment by pombredanne** [comment]
@nitish81299 3.8.1 would likely be the issue, we do not have support for it yet when using configure as some third-parties would need to be recompiled ... Can you try this:
1. `git clone ...`
2. `python3 -m venv .`
3. `source bin/activate`
4. `pip install -e .`

**Comment by nitish81299** [comment]
I tried to do in python3.6 venv but I am still facing the same issue.

All the 4 steps that you mentioned worked perfectly but when I run `./configure` I getting the same issue.

**Comment by ritiek** [comment]
@nitish81299 This is really weird.

Just to confirm - what is your python and pip version as indicated by
```shell
$ python -V

$ pip -V
```
?

**Comment by nitish81299** [comment]
> @nitish81299 This is really weird.
> 
> Just to confirm - what is your python and pip version as indicated by
> 
> ```shell
> $ python -V
> 
> $ python -m pip -V
> 
> $ pip -V
> ```
> 
> ?

`Python 3.6.10`
`pip 18.1`

**Comment by ritiek** [comment]
I see. What if you manually install `future` via pip:
```
$ pip install future
```

Does it still fail? If it does fail, try running it again with verbose output enabled:
```
$ pip install future -vvv
```
and post the output here.

**Comment by nitish81299** [comment]
>  pip install future -vvv

```
(venv) ➜  scancode-toolkit git:(develop) ✗  pip install future -vvv
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-pjsrgifv
Created temporary directory: /tmp/pip-req-tracker-m_gji3mb
Initialized build tracking at /tmp/pip-req-tracker-m_gji3mb
Created build tracker: /tmp/pip-req-tracker-m_gji3mb
Entered build tracker: /tmp/pip-req-tracker-m_gji3mb
Created temporary directory: /tmp/pip-install-31521bb9
Requirement already satisfied: future in ./venv/lib/python3.6/site-packages (0.16.0)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-m_gji3mb'

```

**Comment by ritiek** [comment]
Hm. It says `future` is already installed. Is `./configure` still failing? Perhaps with a different error?

**Comment by nitish81299** [comment]
I performed a simple reboot and refollowed @pombredanne instructions and it's working.

I noticed that error is coming due to `python version 3.8`.

Thank you all.

**Comment by majurg** [comment]
Closing this for now. See #295 for process towards supporting python 3.x+
