### ISSUE TITLE
Documentation says reference data is under CC-BY-1.0

### ISSUE THREAD

**Issue by carmenbianca** [nexB/scancode-toolkit#1984]
### Description

The documentation in getting-started/home says the following:

> Release of the code and reference data under attribution licenses (Apache 2.0 and CC-BY-1.0)

This appears to be incorrect to me. The reference data is licensed under CC0-1.0 according to the README:

> Public domain CC-0 for reference datasets.

(This should probably also be edited to use the SPDX license identifier, CC0-1.0).

### Link to Documentation Page

https://scancode-toolkit.readthedocs.io/en/latest/getting-started/home.html

### Select Category

-  Inconsistency [x]
-  New Section Request []
-  General Improvement []
-  Typo/Mistakes [x]
-  Other []

**Comment by pombredanne** [comment]
@carmenbianca thank you! I guess that would qualify as a genuine cobbler's son problem, would it?

**Comment by pombredanne** [comment]
@carmenbianca if a PR is not too much to ask that would be mucho welcomed!

**Comment by carmenbianca** [comment]
@pombredanne Will craft a PR after the weekend :+1:
