### ISSUE TITLE
Enhance package scan with API request for package-lock.json and yarn.lock 

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1989]
There are many useful metadata that can be extracted from package-lock.json and yarn.lock files which scancode's package scan should parse and log these data.

**Comment by JRavi2** [comment]
@chinyeungli Aren't we already parsing package-lock.json and yarn.lock files [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/npm.py#L822) and [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/npm.py#L929)?

**Comment by chinyeungli** [comment]
Thanks @JRavi2 for pointing out.
The current code will get the name and version from these lock files. The purpose of this ticket is to take one step futher to have an API request to get the license/copyrigt information from the packages.
For instance,
For `@angular-builders/custom-webpack`, we will get the package information from https://registry.npmjs.org/@angular-builders/custom-webpack and then do the parsing and extract the useful information.

**Comment by chinyeungli** [comment]
actually this need to be on hold as this may not be a good fit for scancode-toolkit.

**Comment by majurg** [comment]
@chinyeungli @JRavi2 As far as the API request portion, this is the job of an external tool for now. Scancode should not go out to the web during a scan. 

However, we want to make sure the `yarn.lock` parsing returns a pURL for each dependency found in the `yarn.lock` file. There may be a ticket out there already for this, but if not, I think we can use this one.

**Comment by chinyeungli** [comment]
closing as this does not fit with the scancode toolkit
