### ISSUE TITLE
scancode -h fails on pip install

### ISSUE THREAD

**Issue by mwelsh1118** [nexB/scancode-toolkit#1992]
### Description

On scancode -h, I receive a pip install failure. Subsequent calls to scancode -h fail with a message about C:\scancode-toolkit-2.2.1\bin\scancode being missing. If I delete the bin junction point, I can re-run scancode -h and produce the initial pip failure.

### How To Reproduce

Copy scancode-toolkit-2.2.1.zip contents to C:\scancode-toolkit-2.2.1

`pip install --no-allow-external --use-wheel --no-index --no-cache-dir --quiet --find-links="C:\scancode-toolkit-2.2.1\thirdparty/base" --find-links="C:\scancode-toolkit-2.2.1\thirdparty/prod" -r "C:\scancode-toolkit-2.2.1\etc\conf\base.txt"`

Prints:
 `Could not find a version that satisfies the requirement py2-ipaddress<3.0,>=2.0 (from scancode-toolkit==2.2.1->-r C:\scancode-toolkit-2.2.1\etc\conf\base.txt (line 10)) (from versions: )`

`No matching distribution found for py2-ipaddress<3.0,>=2.0 (from scancode-toolkit==2.2.1->-r C:\scancode-toolkit-2.2.1\etc\conf\base.txt (line 10))`

I also tried replacing slash in the paths with backslash, but no luck.

### System configuration

Python 3.6.4 (32-bit)
Pip 9.0.1

* What OS are you running on? Windows 10
* What version of scancode-toolkit was used to generate the scan file? 2.2.1
* What installation method was used to install/run scancode? download of zip

**Comment by pombredanne** [comment]
@mwelsh1118 the combination of versions you have will not work.
Please try at least ScanCode 3.1.1 for any Python 3.6 usage.
2.2.1 is a rather old version and will surely not work with Python 3

**Comment by mwelsh1118** [comment]
@pombredanne Thanks. I tried 2.2.1 because it was marked as the "Latest release"; all others were pre-release.

I had a similar problem with 3.1.1, though.  And unlike 2.2.1, after I delete the bin junction point, I still get errors about C:\scancode-toolkit-3.1.1\Scripts\scancode not being an operable program.

**Comment by mwelsh1118** [comment]
@pombredanne Do you have any other suggestions?

**Comment by pombredanne** [comment]
@mwelsh1118 here is what I can see when running on fresh Windows 10 VM.

1. I installed the Python version you have from this (32 bits) https://www.python.org/ftp/python/3.6.4/python-3.6.4.exe
In the installer I checked "Add Python 3.6 to PATH". Then I click the "Customize Installation link"->the "Next" button and checked "Install for all users". Then "Install" button. Then "Close"

2. I fetched https://github.com/nexB/scancode-toolkit/releases/download/v3.1.1/scancode-toolkit-3.1.1.zip 

3. I extracted that with "right click/Extract All" to `C:\Users\pombreda\Downloads\scancode-toolkit-3.1.1`

4. I started a Command Prompt

5. There I typed:
```
cd C:\Users\pombreda\Downloads\scancode-toolkit-3.1.1\scancode-toolkit-3.1.1
configure.bat --python "C:\Program Files (x86)\Python36-32\python.exe"
scancode -h
```
And this works 

OR this is another way using pip:
A. I first delete C:\Users\pombreda\Downloads\scancode-toolkit-3.1.1 to reset everything

B. I re-extracted the scancode zip with "right click/Extract All" to `C:\Users\pombreda\Downloads\scancode-toolkit-3.1.1`

C. I started a Command Prompt

D. There I typed these (creating a virtualenv along the way):
```
cd C:\Users\pombreda\Downloads\scancode-toolkit-3.1.1\scancode-toolkit-3.1.1
python -m venv .
Scripts\activate
pip install --no-allow-external --use-wheel --no-index --no-cache-dir --quiet --find-links=thirdparty -e .
scancode -h
```
and this works too.
Can you try one of these may be?
If not can paste the whole set of error messages that you may see in the command prompt?

**Comment by mwelsh1118** [comment]
> configure.bat --python "C:\Program Files (x86)\Python36-32\python.exe"

This was the part I missed! After wiping out the original install, re-extracting, and running configure.bat, I was able to get scancode -h to print the help. Thanks for your help!
