### ISSUE TITLE
Nnn

### ISSUE THREAD

**Issue by manzurulislam789** [nexB/scancode-toolkit#2004]
## Possible Labels

- new feature

## Select Category

-  Enhancement []
-  Add License/Copyright []
-  Scan Feature []
-  Packaging []
-  Documentation []
-  Expand Support []
-  Other []

**Comment by manzurulislam789** [comment]
Notification folder

**Comment by manzurulislam789** [comment]
Filed

**Comment by pombredanne** [comment]
?
