### ISSUE TITLE
License scan for Domain.java will return `public-domain` because of the constructor

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#2013]
### Description

If a java file is named "Domain.java", the licesne scan will return `public-domain` as a detected license because of the constructor statement
i.e.
```
public Domain () {
...
}}}
```
For instance,
https://introcs.cs.princeton.edu/java/42sort/Domain.java.html

Scancode should be smart enough to tell this is a constructor statement instead of comment/notice etc.

**Comment by pombredanne** [comment]
This has been fixed and merged in develop.
