### ISSUE TITLE
Announce deprecation of Windows 32-bit and Python 2.7 support

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#2022]
#1435 # Description

We need to announce that SCTK v3.2 will be the last to support Windows 32-bit or Python 2.7. 
We probably need to post this prominently in at least two places:
- README on GitHub
-  A new Announcement or similar section in RTD.
The announcement should be clear about whether there will be any exceptions for critical bugs.

**Comment by pombredanne** [comment]
This is done here https://github.com/nexB/scancode-toolkit/blob/cce8cbc64746ed58f2f0a9bf03d6c3500bd7cc1c/scancode.bat#L20 and is now tracked in https://github.com/nexB/scancode-toolkit/issues/2366

**Comment by pombredanne** [comment]
next up is to make this visible in the README too

**Comment by pombredanne** [comment]
This has long been deprecated now, so announcing it is no longer needed. Closing now
