### ISSUE TITLE
Recognize site-packages installed python packages (e.g. dist-info)

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2023]
See also https://github.com/nexB/scancode-toolkit/issues/253 for details

**Comment by pombredanne** [comment]
@rpotter12 this would be a ticket of interest

**Comment by rpotter12** [comment]
@pombredanne I will look at this. Thanks :)

**Comment by pombredanne** [comment]
This has been implemented and merged in develop as part of the "installed files" features.
