### ISSUE TITLE
`virtualenv` is required but not mentioned.

### ISSUE THREAD

**Issue by is2ei** [nexB/scancode-toolkit#2025]
### Description

I found I need to run `pip install virtualenv` before running `./configure`.

> To configure your local environment for development, locate to the main directory of the local repository, run the configure script. The configure script creates an isolated Python virtual environment in your checkout directory, the Python pip tool, and installs the thirdparty libraries (from the thirdparty/ directory), setup the paths, etc. See https://virtualenv.pypa.io/en/latest/ for more details.

### Link to Documentation Page

https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst

### Select Category

-  Inconsistency []
-  New Section Request []
-  General Improvement [x]
-  Typo/Mistakes []
-  Other []

**Comment by pombredanne** [comment]
@is2ei you wrote:

> I found I need to run pip install virtualenv before running ./configure

I am sorry things did not work out for you alright! 
Normally you do not need to install or create your own since virtualenv is included in the checkout.
Can you provide a few extra details like which OS, version of Python,etc. you have used and face an issue with?

**Comment by is2ei** [comment]
@pombredanne 

OS information:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G4032
```

Python information:
```
$ python --version
Python 3.6.8
```

I tried to attach the error message but I couldn't reproduce it after I installed `virtualenv` manually. If no one experienced the same issue, I guess this issue should be closed.
