### ISSUE TITLE
pyparsing: gpl-v2 false positive (should be v3!)

### ISSUE THREAD

**Issue by tieguy** [nexB/scancode-toolkit#2040]
### Description

scanning https://github.com/pyparsing/pyparsing/blob/master/examples/pymicko.py returns GPL v2, should be v3.

### System configuration

* What OS are you running on?  MacOS
* What version of scancode-toolkit was used to generate the scan file? 3.1.1
* What installation method was used to install/run scancode? pip + pyenv

**Comment by pombredanne** [comment]
This has long been fixed and released and I had forgotten to update this. Closing now. Thanks for the report!
