### ISSUE TITLE
pandas: false positive on GFDL, should be BSD-2-clause

### ISSUE THREAD

**Issue by tieguy** [nexB/scancode-toolkit#2041]
### Description

https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/src/inline_helper.h

### How To Reproduce

Scans as GFDL, text is:

`Copyright (c) 2016, PyData Development Team
All rights reserved.

Distributed under the terms of the BSD Simplified License.

The full license is in the LICENSE file, distributed with this software.`

### System configuration

* What OS are you running on? MacOS
* What version of scancode-toolkit was used to generate the scan file? 3.1.1
* What installation method was used to install/run scancode?  pip + pyenv

**Comment by pombredanne** [comment]
This has long been fixed and relased... so I am closing this now. Thanks for the report!
