### ISSUE TITLE
ScanCode fails to detect the attached email and url

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#205]
I've created 2 files:
`CY_created-email.c` with the following context
```
abc@example.com
```
and `CY_created-url.c` with the following context:
```
http://www.example.com
```

However, scancode fails to detect the above with the `--email` and `--url`

**Comment by pombredanne** [comment]
@chinyeungli example.com is specifically filtered out as a domain: neither emails no URLs would be returned for these as they are example and not real. 

This happens here https://github.com/nexB/scancode-toolkit/blob/a9fd41b7dbf2a157f13fe6e4c43ad0fa1d678d8d/src/cluecode/finder.py#L439 and https://github.com/nexB/scancode-toolkit/blob/develop/src/cluecode/finder_data.py#L39
