### ISSUE TITLE
Clarify the difference between file info and package info scans.

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#206]

**Comment by pombredanne** [comment]
@jdaguil file infos are basic file information for any file
package info are specific details for packages, typically derived from a package manifest such as RPM metadata, an NPM, a gem, a wheel, a Jar, etc

The actual range of data returnable for a package are in the model here: https://github.com/nexB/scancode-toolkit/blob/51d7d149d729a10b0b4cb56ae4143bf7a7b448b2/src/packagedcode/models.py#L97
For now, the package infos returned are minimal and we are ramping these up with additional details

**Comment by pombredanne** [comment]
@jdaguil I assume that this question was answered yo your satisfaction. Closing now
