### ISSUE TITLE
Dev utility: Create new repo to expose pre-built wheels, tarballs and ABOUT files as releases in a PyPI-like repo

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2068]
Actually we already have that:

https://github.com/nexB/thirdparty-packages/

**Comment by Abhishek-Dev09** [comment]
I have created the repo for wheels, tarballs and ABOUT files [here](https://github.com/Abhishek-Dev09/Third_party/releases/tag/py-3.6)

**Comment by pombredanne** [comment]
that's good, tat a test repo alright. The interesting part is the code to automate the upload of wheels and such.
