### ISSUE TITLE
Add "Help" or "About" section to html-app

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#207]
**Narrative**: I want to see be able to find "Help" information about the ScanCode scan results and UI within the html-app. 
**Context**: The html-app does not have description about the different tabs, filters, etc or other documentation that would be helpful to the user.
**Acceptance Criteria:** 
        - *Scenario 1:* A user should be able to access documentation about the html-app and scan results within the html-app.

**Comment by mjherzog** [comment]
Part of the help system should be a link to new Wiki pages on GH where we provide several "How To Interpret the Data from ScanCode" examples using sample scans.
