### ISSUE TITLE
 Dev utility: Create build loop in repo to build and upload wheels and sdist for all operating systems and Python versions in our "personal" PyPI

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2071]
Note that for the GitHub release upload part there are few nice tools and libraries to consider:
- @paulthomson https://github.com/google/github-release-retry
- @jwilges https://github.com/jwilges/monocat
- @YakDriver https://github.com/plus3it/satsuki

**Comment by ncoghlan** [comment]
You may also want to look at https://github.com/joerick/cibuildwheel

**Comment by pombredanne** [comment]
So the candidates for building the wheel on all OSes x Python versions combos are:
- https://github.com/joerick/cibuildwheel (thanks @ncoghlan ! )
- https://github.com/altendky/romp (with a more general purpose focus and Azure-only and a focus on running on-demand)

**Comment by pombredanne** [comment]
See also #2087

**Comment by pombredanne** [comment]
Eventually we built a tool that handles creation, documentation and publishing of wheels and source https://github.com/nexB/scancode-toolkit/tree/1bddb92c70abcf26cf9435061e429bae62cbe040/etc/release
And this is also part of the https://github.com/nexB/skeleton

For the release proper https://github.com/google/github-release-retry does the job until GH fixes their flakiness.
