### ISSUE TITLE
Dev utility: Create release scripts to build archives

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2072]
One archive for each OS/Python combo should be created and each should have its exact set of pinned requirements included in the built archive, no more and no less.

**Comment by pombredanne** [comment]
See #2117

**Comment by pombredanne** [comment]
So the way this would typically work out would be IMHO this:
1. there is a single MANIFEST.in file that excludes `tests/` and `docs` and includes the `thirparty/`
2. somehow there is a script that is launched and that accepts as option something like `--os window or linux or macox`, `--arch 32 or 64` and `--python 36, 37, etc` ... these should normally be the same value as the wheel tags. And also accept a requirements file as an input.
3. This script will first wipe clean the thirdparty/ directory 
4. Then it will  download there just the set of wheels, sdists and ABOUT files that are needed for the options that were chosen.  These wheels should be selected exactly from the provided requirement files and fetched from our own "github-repo-release-Pypi-repo" and saved in the thirdparty/ dir
5. finally the script generates an a `python setup.py sdist` that will include the current thirdparty and possibly renames that file so it contains the proper os/arch/python "tags" it its archive name. 

Another way can work too. That's one of the  ways :)

**Comment by Abhishek-Dev09** [comment]
@altendky : Your suggestion are also welcome here.

**Comment by Abhishek-Dev09** [comment]
@pombredanne : Only sdist/wheels are available in thirdparty not ABOUT,NOTICE because we are using `pip-download` here, that will be integrated with `romp` because `romp` will provide matrix for python/os/ach.

**Comment by pombredanne** [comment]
The new https://github.com/nexB/scancode-toolkit/blob/1bddb92c70abcf26cf9435061e429bae62cbe040/etc/release/scancode-create-release.sh script creates these alright.
