### ISSUE TITLE
killing/abort running scan in python

### ISSUE THREAD

**Issue by Angi2412** [nexB/scancode-toolkit#2085]
## Short Description
It would be helpful if it would be possible to kill or abort a running scan, which was started via the pip package.

## Possible Labels

- new feature

## Select Category

-  [X] Enhancement
-  [ ] Add License/Copyright
-  [ ] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [ ] Expand Support
-  [ ] Other

## **Describe the Update**

There should be a command with which it is possible to kill or abort a running scan. 
In our application, we are using a Redis queue to queue ScanCode scanning jobs beside others. In the future, we want to implement the possibility for our user to kill or abort a running scan through the user interface. Because the method "delete()" given by [RQ](https://python-rq.org/) is not sufficient the next possible solution would be to implement the abort method ourselves for which we would need an abort function from ScanCode.

## **How This Feature will help you/your organization**
It would make it possible to implement a delete function in our user interface.

## **Possible Solution/Implementation Details**

Implement a "kill()" function. 

## **Example/Links if Any**

At the moment our function looks like this:
```
@app.route('/deleteScan')
def deleteScan():
    """
    deletes a given scan request
    :return: success message
    """
    # init info message
    qu = False
    d = False
    f = False
    # get hash from request
    hash = request.args.get("hash")
    # cancels job in queue
    try:
        job = Job.fetch(id=hash, connection=r)
        job.delete()
        qu = True
    except NoSuchJobError:
        logging.warning(f"No Job with id {hash} to delete.")
    # removes entry from db
    try:
        sql.update_status(hash, "deleting")
        sql.delete_scan(hash)
        d = True
    except errors as err:
        if err.errno == errorcode.ER_KEY_NOT_FOUND:
            logging.warning(f"No db entry with hash {hash} to delete.")
    # removes package folder
    path = os.path.join(sglobals.workpath, "data", "files", hash)
    if os.path.exists(path):
        try:
            c = Cleaner()
            c.delete_scan_folder(path)
            f = True
        except errors as err:
            logging.warning(f"Could not delete folder: {err}")
    else:
        logging.warning(f"Path to delete does not exist: {path}")
    message = f'Scan {hash} delete status: \n queue: {qu} \n database: {d} \n folder: {f}'
    logging.info(message)
    return message
```
## **Can you help with this Feature**

I don't think so. I don't know the architecture of the program that good.

**Comment by pombredanne** [comment]
@Angi2412 thank you ++ for this. Let me review this in details and reply

**Comment by pombredanne** [comment]
BTW, if you are working on some integrations where you need to call in directly ScanCode functions, feel free to reach out here and on Gitter https://gitter.im/aboutcode-org/discuss for help and discussion.

**Comment by pombredanne** [comment]
@Angi2412 I am not I get otherwise the issue here. You want to interrupt a call to a scancode function? Do you call `cli.run_scan` with multiprocessing? can you paste how you call things?

**Comment by Angi2412** [comment]
@pombredanne thank you for the hint with the gitter :)
I do use `cli.run_scan` with multiprocessing - the number of cores is determined dynamically because the application is deployed on several servers with dockers which all have different CPU resources. 

Here's how I call the scan process:
```
rc, results = cli.run_scan(
            os.path.split(path)[0], license=True, copyright=True,
            return_results=True, processes=cores
        )
```

I'm using an older cli file from the developer branch because the current cli file leads to a weird error:
something along the lines that something is missing in the header of something (i will try to reproduce an open an issue) ^^

**Comment by pombredanne** [comment]
@Angi2412 OK, so you really do not have a handle on the process tree that is currently running in rq?
If that is so, what you are looking for is a way to signal whatever is running that they should stop ASAP and gracefully terminate.
I am not sure what would be the way specifically for rq, but two solutions I can think of consist in using a file and react accordingly if the file is present or use a signal on POSIX.

For a file-based solution, you would need to create some unique name for that file ahead of time when you call your code and pass that to your callable: 
```
import os

def do_something(watch_file_location, **kwargs):
    """
    Do something until a file is found at `watch_file_location`.
    """
    # do our biiding here, looping until we are done
    while True:
        if os.path.exists(watch_file_location):
            # do some graceful exit housekeeping
            break
        # do really something

    # clean this up more here before existing
```



If on POSIX only a solution may be using signals:
```
import signal
MUST_STOP = False

def stop_handler(*args, **kwargs):
    """
    Signal handler to set global variable to True. 
    """
    global MUST_STOP
    MUST_STOP = True

# set a signal, so that when the process will receive a SIGTERM the handler executes
signal.signal(signal.SIGTERM, stop_handler)

def do_something(*args, **kwargs):
    global MUST_STOP
    # do our biiding here, looping until we are done
    while True:
        if MUST_STOP:
            # do some graceful exit housekeeping
            break
    # clean this up more here
```

you would need to send a SIGTERM to the running process, something that you may not know at all?

I would need to understand a bit more to see how and if it makes sense to have a hook in scancode to support something like that.


Now the thing that's a bit puzzling to me is why you could not kill the parent process running in rq instead when you want to kill something?

**Comment by Angi2412** [comment]
Thank you for the in detail answer :) 
I see now, that killing the process via ScanCode is the wrong approach. I will continue researching the approach using rq.
