### ISSUE TITLE
summarization appends a numeric suffix to a consolidated package filename when it is not necessary or helpful

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#2094]
Recent scans show that summarizations always append a numeric suffix of `_1` to a consolidated package filename when it is not necessary to make it unique.  That is unfortunate because it results in a misleading perception about what the version of a package actually is; for example: a consolidated package filename of `pkg_pypi_cryptography_2_8_1` is provided for the package with a Package URL = `pkg:pypi/cryptography@2.8`  which is actually correct.  There is no v2.8.1 of this package, only a 2.8 (see https://pypi.org/project/cryptography/2.8/#files ).   

So it appears that the summarization/consolidation process wants to make sure that we don't have duplicate filenames clashing (good) but it is appending the suffix even when it is not needed (not good) and in this example, confusing and misleading.   Ultimately it would be even better if the process could find or construct a package filename to match one of the real filenames such as those at https://pypi.org/project/cryptography/2.8/#files but that enhancement can come later; in the meantime, it would be better if the naming algorithm only started adding a suffix when it finds an actual duplicate.

**Comment by JonoYang** [comment]
@DennisClark 

Thanks for pointing out how the numeric suffix at the end of a purl can mislead people about the version of the package. I did not anticipate that. The idea of just using the package name and version from the purl is interesting. I can definitely start with removing the numeric suffixes from filenames and only using the numeric (or some other) suffix when need.  I'll let you know when I got something that addresses these issues.

**Comment by JonoYang** [comment]
@DennisClark 

I got a branch up where the consolidation plugin does not add a numeric suffix to a consolidated package filename if there is only one instance of a given package. Let me know if behaves more like what you expect: https://github.com/nexB/scancode-toolkit/tree/2094-consolidation-filename-change

**Comment by DennisClark** [comment]
@JonoYang   Thanks!  I'll try it out soon.

**Comment by DennisClark** [comment]
```
dennis-clarks-macbook-pro:scancode-toolkit-2094-consolidation-filename-change dclark1330$ ./scancode -clip --info --classify --license-clarity-score --consolidate -n 4 --max-in-memory 0 /Users/dclark1330/Downloads/gpdb-6.8.1/ --json-pp /Users/dclark1330/Downloads/gpdb-6.8.1.json
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages with 4 process(es)...
[####################] 12453                                                                                           
ERROR: failed to run post-scan plugin: consolidate:
Traceback (most recent call last):
  File "/Users/dclark1330/scancode-toolkit-2094-consolidation-filename-change/src/scancode/cli.py", line 1045, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/dclark1330/scancode-toolkit-2094-consolidation-filename-change/src/summarycode/plugin_consolidate.py", line 208, in process_codebase
    package_url = PackageURL.from_string(purl)
  File "/Users/dclark1330/scancode-toolkit-2094-consolidation-filename-change/lib/python2.7/site-packages/packageurl/__init__.py", line 337, in from_string
    raise ValueError('A purl string argument is required.')
ValueError: A purl string argument is required.

Scanning done.
Some files failed to scan properly:
ERROR: failed to run post-scan plugin: consolidate:
Traceback (most recent call last):
  File "/Users/dclark1330/scancode-toolkit-2094-consolidation-filename-change/src/scancode/cli.py", line 1045, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/dclark1330/scancode-toolkit-2094-consolidation-filename-change/src/summarycode/plugin_consolidate.py", line 208, in process_codebase
    package_url = PackageURL.from_string(purl)
  File "/Users/dclark1330/scancode-toolkit-2094-consolidation-filename-change/lib/python2.7/site-packages/packageurl/__init__.py", line 337, in from_string
    raise ValueError('A purl string argument is required.')
ValueError: A purl string argument is required.
Path: gpdb-6.8.1/src/bin/gpfdist/regress/data/fixedwidth/fixedwidth_big.tbl
Path: gpdb-6.8.1/src/bin/gpfdist/regress/data/gpfdist2/lineitem_cr.tbl
Path: gpdb-6.8.1/src/bin/gpfdist/regress/output/custom_format.source
Path: gpdb-6.8.1/src/bin/gpfdist/remote_regress/output/custom_format.source
Path: gpdb-6.8.1/src/test/regress/data/lineitem.csv
Path: gpdb-6.8.1/src/test/regress/data/lineitem_small.csv
Path: gpdb-6.8.1/src/test/regress/data/order.csv
Path: gpdb-6.8.1/src/test/regress/sql/qp_olap_window.sql
Summary:        info, licenses, copyrights, packages with 4 process(es)
Errors count:   9
Scan Speed:     3.64 files/sec. 85.69 KB/sec.
Initial counts: 13427 resource(s): 12453 file(s) and 974 directorie(s) 
Final counts:   13427 resource(s): 12453 file(s) and 974 directorie(s) for 286.52 MB
Timings:
  scan_start: 2020-06-25T165514.093533
  scan_end:   2020-06-25T175529.886209
  setup_scan:licenses: 4.36s
  setup: 4.36s
  inventory: 2.94s
  pre-scan:classify: 9.96s
  pre-scan: 9.96s
  scan:packages: 2.75s
  scan: 3423.91s
  post-scan:classify-package: 2.75s
  post-scan:consolidate: 136.69s
  post-scan:license-clarity-score: 22.83s
  post-scan: 162.28s
  output:json-pp: 8.99s
  output: 8.99s
  total: 3627.53s
Removing temporary files...done.
dennis-clarks-macbook-pro:scancode-toolkit-2094-consolidation-filename-change dclark1330$ 
```

**Comment by DennisClark** [comment]
I ran the test on gpdb-6.8.1.tar.gz  
It's a really big one, but I wanted to look for any possible anomalies! 
Guess I managed to do that.

**Comment by JonoYang** [comment]
@DennisClark 

Some of the consolidated packages do not have purls to create identifiers from. I've created a workaround to use the `root_path` of where a package was detected as the identifier. For example, a ruby package was detected at `gpdb-6.8.1/gpdb-doc/book`, but there is no purl available for the resulting detected package, my fix is to just take that root path (`gpdb-6.8.1/gpdb-doc/book`) and prepend `consolidated-package` to it, resulting in `consolidated_package_gpdb_6_8_1_gpdb_doc_book` as the identifier.

Please pull in the new changes and let me know if this is getting closer to something that works.

**Comment by DennisClark** [comment]
Thanks @JonoYang    I'll try this out today.

**Comment by DennisClark** [comment]
Hi @JonoYang  your fix took care of the error reported by the scan.  I'm doing some further investigation and analysis of the actual results and will get back to you on that.

**Comment by DennisClark** [comment]
this has been addressed by other tickets
