### ISSUE TITLE
Is there a way to call it directly from python code?

### ISSUE THREAD

**Issue by soimkim** [nexB/scancode-toolkit#2105]
Is there a way to call it directly from python code?
I want to call it from python code, like calling from cli.
If I call it after installing with pip, an error occurs. : https://github.com/nexB/scancode-toolkit/issues/1947

## Select Category
-  [ ] Enhancement
-  [ ] Add License/Copyright
-  [ ] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [ ] Expand Support
-  [*] Other

## **How This Feature will help you/your organization**
If it can be called directly from a python script, the utilization is better.

**Comment by Angi2412** [comment]
@soimkim not sure if it helps and how it is supposed to be used, but I use it like this:

```python
from scancode import cli

rc, results = cli.run_scan(path, license=True, copyright=True, return_results=True, processes=cores)
```

while "cores" is the number of CPU cores available.

**Comment by soimkim** [comment]
I installed with pip and called it like you shared it, and I get an error.
- OS: ubuntu 18.04, Python : 3.6

** Error Message:
`Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/scancode/cli.py", line 669, in run_scan
    raise te
  File "/venv/lib/python3.6/site-packages/scancode/cli.py", line 666, in run_scan
    is_enabled = plugin.is_enabled(**kwargs)
TypeError: is_enabled() missing 1 required positional argument: 'facet'`

**Comment by Angi2412** [comment]
Oh sorry, I forgot to mention, that I'm using the CLI file from the dev branch because I got the same error.
It's not a very "clean" solution I know, but as long as there's no update for the pip package I found it's the only way it's working for me...

**Comment by pombredanne** [comment]
@soimkim I am pushing a new wheel today as a new candidate release. As @Angi2412  pointed out, you need to use the `develop` branch to call `run_scan()`  https://github.com/nexB/scancode-toolkit/blob/f488b6c2172f588e80e1b764ed6158444e92b8ef/src/scancode/cli.py#L539

@Angi2412 tag and new candidate release wheel on its way :)

**Comment by soimkim** [comment]
The develop branch works fine. :-)
Thanks for the quick answer.

**Comment by pombredanne** [comment]
Dear @soimkim you wrote:

> The develop branch works fine. :-)
> Thanks for the quick answer.



I am glad this worked for you. Please feel free to reach out for further help!
 May I ask what kind of app you are building? I am always interested in how scancode can be used.

**Comment by soimkim** [comment]
Dear @pombredanne ,

I am writing a Python Script to execute Scancode when analyzing source code in CI/CD environment.
Scancode is very useful for viewing the analysis results in the workbench, and it is also good for parsing because it outputs the results in json format.
We will use it to notify the developer of the detected license for the newly added commit.

**Comment by pombredanne** [comment]
I think this is all fixed now. Closing!
Happy new year!
