### ISSUE TITLE
Failure to configure on Linux

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2108]
originally from  @sschuberth https://github.com/nexB/scancode-toolkit/issues/1875#issuecomment-649532709

> Running v3.1.1 fails with "cannot import name RPM"
> @pombredanne I'm actually seeing this error again on latest develop, but on Linux! Is there a regression?

**Comment by sschuberth** [comment]
I cannot reproduce this anymore, latest `develop` (f488b6c2172f588e80e1b764ed6158444e92b8ef) configures fine for me on Ubuntu 18.04 with both Python 2.7 and Python 3.6 installed.

**Comment by pombredanne** [comment]
@sschuberth thank you for checking this!
