### ISSUE TITLE
SCTK: Parse Python poetry lockfile and manifest 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2109]
See https://github.com/python-poetry/poetry
These are now using pyproject.toml

**Comment by AyanSinhaMahapatra** [comment]
See https://python-poetry.org/docs/basic-usage/

Example: https://github.com/Tinche/cattrs/blob/master/poetry.lock

**Comment by AyanSinhaMahapatra** [comment]
This is completed with https://github.com/nexB/scancode-toolkit/pull/3757 and merged, closing this.
