### ISSUE TITLE
Bugs in .yml files, for Scancode Rules/Licenses

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#2111]
### Description

> A brief description

In .yml files for scancode license detection rules,  the `is_license_notice` key should normally have the value `yes`, if True, and the key wouldn't exist if `False`. 

But in some cases, (very few, 5 files), they had these values for the `is_license_notice` key - `'yes - LICENSE'`, `'yes - LICENSE - LICENSE.mxSetup'`, `'ye'`  , `'text'`

Files in question - 
-  `'yes - LICENSE - LICENSE.mxSetup'` -> `egenix-1.1.0_2.RULE`
- `'yes - LICENSE'`->`bsd-new_474.RULE`
- `'ye'` -> `postgresql_6.RULE`,    
- `'text'` -> `sun-bsd-no-nuclear_itext_2.RULE` and `sun-bsd-no-nuclear_itext_unicode_1.RULE`

Another similar error in `is_license_reference`:

- `text` -> `gpl-2.0_and_unknown_trommel_1.RULE`

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra good find. let's fix these with a PR

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne Yes! I'll open a PR.

**Comment by AyanSinhaMahapatra** [comment]
Another issue, the file `dropbear.LICENSE` has `minimum_coverage` = `680` which is the only instance of a RULE/LICENSE having more than 100 value, also likely a bug.
