### ISSUE TITLE
ImportError: cannot import name 'PDFTextExtractionNotAllowed'

### ISSUE THREAD

**Issue by danielthieleog** [nexB/scancode-toolkit#2119]
### Description

Since 2020-07-21 I have an error when scanning with a fresh installation of scancode-toolkit, installed with `pip install scancode-toolkit`:

> ImportError: cannot import name 'PDFTextExtractionNotAllowed'

For details see [scancode-toolkit_error_pdfminer_six.txt](https://github.com/nexB/scancode-toolkit/files/4952094/scancode-toolkit_error_pdfminer_six.txt)

The error comes from updated pdfminer.six release 20200720, which replaces the former release 20200517.

For details of pdfminer.six see

https://github.com/pdfminer/pdfminer.six/releases/tag/20200720

The incompatible change was introduced with

https://github.com/pdfminer/pdfminer.six/commit/6a9269b432b861fdd8de6f532759833faf9a9159#diff-ed5a6cbc9c19d300709043df14c3333e

As workaround you can install an older version of pdfminer.six

```
pip install pdfminer.six==20200517
```

This was mentioned on https://stackoverflow.com/questions/63004650/camelot-mporterror-cannot-import-name-pdftextextractionnotallowed-from-pdfmi and https://github.com/camelot-dev/camelot/issues/169 .

For a real fix `PDFTextExtractionNotAllowed` has to be replaced in scancode-toolkit by `PDFTextExtractionNotAllowedWarning` and `PDFTextExtractionNotAllowedError`.

### How To Reproduce

```
# Workdir is /app
pip install virtualenv \
    && virtualenv -p /usr/local/bin/python3.6 venv-scancode \
    && . venv-scancode/bin/activate \
    && pip install scancode-toolkit pyicu

virtualenv -p /usr/local/bin/python3.6 venv-scancode
. venv-scancode/bin/activate

/app/venv-scancode/bin/extractcode --shallow /scan
/app/venv-scancode/bin/scancode -lp --json-pp - /scan --summary
```

### System configuration

Running on Linux in python:3.6 docker container.
Release 3.1.1 of scancode-toolkit.
Installed with pip.

**Comment by 0xc0170** [comment]
Thanks, I was just about to look at this one as Travis started failing today, this is the cause. 

I'll use the workaround for now to unblock us.

**Comment by danielthieleog** [comment]
Looks like workaround must not be used with new release 3.2 and bug is solved.

Using obsolete workaround with 3.2 lead to different error: "Exception: CRITICAL: libmagic DLL and is magic database are not installed. Unable to continue: you need to install a valid typecode-libmagic plugin with a valid and proper libmagic and magic DB available."

Apart from that additionally I had to pip install extractcode. Otherwise the binary extractcode was not available as before.

**Comment by pombredanne** [comment]
@danielthieleog indeed... I thought I had reported that here ... in fact I had pushed a PR upstream in pdfminer to fix this https://github.com/pdfminer/pdfminer.six/pull/461
Thank you for noticing this!
