### ISSUE TITLE
problem with Copyright Summary using ScanCode 1.6.0

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#212]
I ran scancode on a relatively large library, ffmpeg-3.0, using the --format html-app option, and the results are generally successful and the output useful. 
Scanning files...
  [####################################]  5667  
Scanning done.
real    31m41.470s
user    30m36.505s
sys 0m15.395s

However, the "Copyright Summary" tab of the html display only shows the phrase "Total Files Scanned: 5667", and nothing else, when I position on the top-level ffmpeg-3.0 folder, even though the "License & Copyright Details" tab shows 6,005 entries at the same level.  The problem with the Copyright Summary is resolved when I go to lower levels in the project hierarchy, suggesting that the problem is the way the software is trying to handle the large number of files at the top level. 

![screen shot 2016-02-26 at 1 20 07 pm](https://cloud.githubusercontent.com/assets/4991620/13365869/6f82c80e-dc8c-11e5-9714-1fab5a4d82fd.png)

**Comment by pombredanne** [comment]
@jdaguil I think that we could also consider truncating very long copyrights that are likely a fluke.

**Comment by pombredanne** [comment]
@DennisClark I am closing this as these type of features are now provided by https://github.com/nexB/aboutcode-manager instead.
