### ISSUE TITLE
Create Issue template for license detection bugs

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#2127]
I recently reported #2126 - a complex license detection bug. It would have been helpful to have a template for the data needed for this type of specific license detection bug. I did look at some of the license detection files, but could not figure out what needs to be done.

**Comment by AyanSinhaMahapatra** [comment]
Thanks for the ticket @mjherzog, opening a PR shortly.

**Comment by AyanSinhaMahapatra** [comment]
Thanks for the ticket @mjherzog, opening a PR shortly.

**Comment by mjherzog** [comment]
New Issue Template looks good.
