### ISSUE TITLE
Include license policy using a configuration file

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#214]

**Comment by pombredanne** [comment]
This ticket was originally an experiment but it makes sense to flesh out a bit the design and goals.
Here is what I think these could be:

**Context**

When running a scan:
- there are certain results that are useful to ignore such as a some copyright statements per #106, specific file paths to ignore per #36, some file types (such as PDF) that may not be super useful to scan per #119 
- there are also certain results that could be flagged as OK, not OK or requiring some review. This could be for instance a certain license or license category: e.g. if I am scanning my GPL-licensed project it may be problematic to include proprietary-licensed code in it. Or it could be known copyrights such as my own copyright, or it could even be some package, urls or emails. Or it could the absence of some data that could be a trigger: for instance the absence of a copyright or license. 
- the usage context or the type or classification of a scanned file may matter too: for instance it may be perfectly  OK for an Apache-licensed project to use a GPL-licensed build utility or some test code but that may not be OK when used in the main code.

**Approach**

Based on this a policy would be some rules that define:
- what to scan and not to scan
- with certain scan results, (e.g. a license, copyright, package, etc) whether this is OK, not OK or needed some review (e.g. a while list, black list and grey list or green, orange, red markers)

The rules could apply to a whole scan or several scans (and therefore should be stored in a config file that could be referenced in a command line option) and the rules could be also specific to certain portions of a code tree (either by having several config files scattered in a code tree or by having a central file that can reference sub tree elements)

The usage would be that once the scan is completed then the policy would be "applied" on the results and the final scan results enhanced with the matched policy elements. This could take the form of a new attribute attached to a file in the scan results and providing the results of "matching" the policy rules to the scan results. Specific outputs (such as the html-app) and GUI tools (such as the https://github.com/nexB/aboutcode-manager) could then use that data to provide feedback and navigation of the results based on the incorporated policy feedback. A scan summary could provide a summary of compliance with the defined policy listing things OK, not OK, and requiring review. We go even go as far as reporting an error return code from running a scan based on this.

@mjherzog you had some opinion on this. Input welcomed.
@nakami @sschuberth ditto, based on  ticket #106 and comments.

**Comment by sschuberth** [comment]
Sounds good to me, but just one remark for clarity ...

> The usage would be that once the scan is completed then the policy would be "applied" on the results

If a policy defines the exclusions of some paths, that part of the policy should of course be applied *before* the scan to reduce the scanning time, and just "filter" the full results.

**Comment by pombredanne** [comment]
@sschuberth good point: the path exclusions should be best done upfront and best done as we walk files using this [function](https://github.com/nexB/scancode-toolkit/blob/12030cc668222b2aa5710f1b0e4f700ad5af9823/src/commoncode/fileutils.py#L250)  that has already all the provisions for exclusions (aka. `ignores`) and is actually called from [here](https://github.com/nexB/scancode-toolkit/blob/12030cc668222b2aa5710f1b0e4f700ad5af9823/src/scancode/cli.py#L516)

**Comment by pombredanne** [comment]
From #659  by @majurg

>It would be nice to have some sort of integration between scancode and a customer's instance of DejaCode. Specifically, we would like the ability to access usage policy from Dejacode and integrate that data into scancode results file.

>This process could be done during scan time, or as an external utility that runs on the scancode results file. This utility could also be a summarization feature of sorts, returning the number of licenses found during scanning that violate an org's usage policy and their file-paths.

>All thoughts on this issue are welcome, especially from @mjherzog, @DennisClark and @pombredanne.

**Comment by majurg** [comment]
#1008 merged. Closing.
