### ISSUE TITLE
Windows install fails latest 3.1.1 for Python 3.7.8

### ISSUE THREAD

**Issue by NickBower-Woodside** [nexB/scancode-toolkit#2158]
First problem, finds Python but it doesn't

```
C:\Users\nick\Downloads\scancode-toolkit-3.1.1>scancode -h
* Configuring ScanCode for first use...
Python 3.7.8
C:\Program Files\Python\Python37\python.exe
* Unable to find an installation of Python.
```

So manually trying to set it

```
C:\Users\nick\Downloads\scancode-toolkit-3.1.1>configure --python "C:\Program Files\Python\Python37\python.exe"
Python 3.7.8
C:\Program Files\Python\Python37\python.exe
Junction created for C:\Users\w50576\Downloads\scancode-toolkit-3.1.1\bin <<===>> C:\Users\nick\Downloads\scancode-toolkit-3.1.1\Scripts
ERROR: Could not find a version that satisfies the requirement future>=0.16.0 (from scancode-toolkit==3.1.1->-r C:\Users\nick\Downloads\scancode-toolkit-3.1.1\etc\conf\requirements_base.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for future>=0.16.0 (from scancode-toolkit==3.1.1->-r C:\Users\nick\Downloads\scancode-toolkit-3.1.1\etc\conf\requirements_base.txt (line 10))

```

**Comment by hobbeschild** [comment]
I have the same issue.  Any progress?

**Comment by pombredanne** [comment]
we may not yet fully support using Python 3.7 when installing from a release archive unless you install from sources and recompile the native code.
This is however coming up soon: there is no problem with the code, this is only a packaging issue that is solved and comes in the next after newest version
That said, the latest develop branch or the latest release https://github.com/nexB/scancode-toolkit/releases/tag/v3.2.1rc2 is the one you want to work with in all cases.

**Comment by pombredanne** [comment]
@hobbeschild @NickBower-Woodside Do you mind to take a stab at installing the latest 31.0.0b4 on Windows? This would be super useful as part of the beta testing before we release!
Thanks in advance https://github.com/nexB/scancode-toolkit/releases/tag/v31.0.0b4

**Comment by pombredanne** [comment]
I am closing this now. AFAIK things work fine with the latest. We have pushed a 31.0.0rc1 release candidate too.
