### ISSUE TITLE
Point scancode detected license keys to a scancode-toolkit URL for the license text

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#2165]
Point scancode detected license keys to the scancode-toolkit URL for the license text.

A lot of details need to be worked out, primarily where the licenses are stored and can be reliably found and maintained.

**Comment by DennisClark** [comment]
Consider a new open repo just for licenses.  Proposed name:  `scancode-license-reference`

**Comment by DennisClark** [comment]
Suggested description: "A reference list of a wide variety of licenses that have been discovered in publicly available software projects, including open source, free proprietary, source available, and commercial license notices. This wide-ranging list may be considered an extension of the more meticulously curated SPDX license list.  The licenses and their texts are available to use in SPDX documents as license references."

**Comment by DennisClark** [comment]
Consider something like `LicenseDB`

**Comment by pombredanne** [comment]
See https://github.com/nexB/licensedb/issues/1

**Comment by pombredanne** [comment]
We now provide the `scancode_url` to the ScanCode repo and the `licensedb_url` to the licenseDB in the latest PR #3150 that is landing in develop anytime.
I am closing this as done.
