### ISSUE TITLE
Detect Python packages from a dist-packages directory

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#2166]
In `/usr/lib/python3/dist-packages`, you can see for some installed packages, there is an egg-info directory that contains metadata for that package: 

![image](https://user-images.githubusercontent.com/6044800/90535120-65737780-e12f-11ea-818c-0a82167148ac.png)

ScanCode should detect a Package from the PKG-INFO found in the egg-info directories. For Packages detected in this manner, we should be able to get a list of installed Python files for that Package in a similar way we do for Debian Packages (https://github.com/nexB/scancode-toolkit/blob/2058-collect-system-packages/src/packagedcode/debian.py#L93). 

Using my screenshot as an example: scancode should get Package info from `asn1crypto-0.24.0.egg-info/PKG-INFO`. The list installed files of the Package created from `asn1crypto-0.24.0.egg-info/PKG-INFO` should be the Python files found in the `asn1crypto` directory,

**Comment by JonoYang** [comment]
I have tried running `scancode -ipcl /usr/lib/python3/dist-packages/asn1crypto-0.24.0.egg-info/PKG-INFO --json-pp -` on my machine and it appears that scancode is having troubles parsing PKG-INFO files as there is no Package result.

**Comment by rpotter12** [comment]
> I have tried running `scancode -ipcl /usr/lib/python3/dist-packages/asn1crypto-0.24.0.egg-info/PKG-INFO --json-pp -` on my machine and it appears that scancode is having troubles parsing PKG-INFO files as there is no Package result.

@JonoYang Maybe this can be fixed by changing function name in  line https://github.com/nexB/scancode-toolkit/blob/d2e4f2a3a9a935e9131c9ebb6ce57fc311bb9a24/src/packagedcode/pypi.py#L143 by `parse_unpackaged_source`. You can try this. :)

**Comment by JonoYang** [comment]
@rpotter12 

I have done your suggestion and replaced `parse_pkg_info` with `parse_unpackaged_source` on line 143 of `scancode-toolkit/src/packagedcode/pypi.py` and I am still encountering the same problem where the PKG-INFO file is not being parsed.

**Comment by rpotter12** [comment]
@JonoYang after editting the code, navigate to that folder where the file is and then run command `scancode -ipcl PKG-INFO --json-pp -`. May this will get success. It worked for me.:)

**Comment by rpotter12** [comment]
BUG:
I have edited some code then used command `scancode -ipcl /usr/lib/python3/dist-packages/asn1crypto-0.24.0.egg-info/PKG-INFO --json-pp -` but it didn't give me any output for packages but when navigate to that directory and run command `scancode -ipcl PKG-INFO --json-pp -` it gives me desired output for packages. It happen for some other files too. We need to fix this too.
