### ISSUE TITLE
Authors scan does not find "Created by Company"

### ISSUE THREAD

**Issue by nakami** [nexB/scancode-toolkit#217]
According to the test files (scancode-toolkit/tests/cluecode/data/authors/author_no_author-c.c) 
`Created by IntelliJ IDEA` is not expected to be found. 
Is this legitimate?

Why is this expected to be found on the other hand then:
`// Created: Sun Feb  9 10:06:01 2003 by faith@dict.org`
( scancode-toolkit/tests/cluecode/data/authors/author_stacktrace_cpp-stacktrace_cpp.cpp)

I checked **test_authors.py** (scancode-toolkit/tests/cluecode/test_authors.py) for the expected results.

**Comment by pombredanne** [comment]
@nakami `Created by IntelliJ IDEA` is a common comment added by an IDE to code that was created or generated by the IDE. As such this is not an indication of origin, merely an indication that a tool was used. So this is entirely legitimate and is excluded specifically as being common "junk" in https://github.com/nexB/scancode-toolkit/blob/c7f808cce1e9a46fe83c529c8cb789dbc57af958/src/cluecode/copyrights.py#L905

On the other hand  `Created: Sun Feb 9 10:06:01 2003 by faith@dict.org` clearly refers to an individual (albeit indirectly through an email) and can be an origin clue. So this is returned,

**Comment by nakami** [comment]
thank you for the clarification

**Comment by pombredanne** [comment]
@nakami anytime! can I go ahead and close this ticket?

**Comment by pombredanne** [comment]
btw if you want to experiment with running the tests just for that part here would be the steps:
1. clone the repo
2. run `source configure` or `configure.bat`
3. run `py.test -vvs tests/cluecode/test_authors.py` for a single threaded test run only for authors tests or `py.test -vvs tests/cluecode/test_authors.py -n4` to run on 4 processors for a faster run.

**Comment by nakami** [comment]
sure, you may close it. thanks again.
