### ISSUE TITLE
BSD license recognized as EPL

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2171]
### Description

BSD license is recognized as EPL

https://bitbucket.org/nielsenb/aniso8601/raw/6bcea1cd4c50134bb6f3825cf3cd7f79cda039b9/aniso8601/builders/python.py

### How To Reproduce

Download https://bitbucket.org/nielsenb/aniso8601/raw/6bcea1cd4c50134bb6f3825cf3cd7f79cda039b9/aniso8601/builders/python.py
Run scancode

### System configuration

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by pombredanne** [comment]
Thank you ++ for the report, as usual!

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra here are tow interesting very closely related texts to the original reference by @armijnhemel :+1: 
```
# This software may be modified and distributed under the terms
# of the BSD license.  See the LICENSE file for details.
```

- https://github.com/acscreative/continentalpools-dev/blob/9692a9883e63d03408832417859fd065eeb6bf20/wp-content/plugins/post-smtp/Postman/Postman-Mail/mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Exception/HydrationException.php#L6

```
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
```

- https://github.com/danivand/cgbp/blob/dae6a0c42f6bb0518aa24a09e504d00fbccfd5fb/hsv.h#L6

```
 * This software may be modified and distributed under the terms
 * of the ISC license.  See the LICENSE file for details.
```

**Comment by LeChasseur** [comment]
I had the same issue with the following additional aspect (which seems strange to me): the same header is interpreted differently, i.e.: https://bitbucket.org/nielsenb/aniso8601/src/master/aniso8601/interval.py creates the result BSD-3-Clause and GFDL-1.1-only, all other files of the package create the result EPL-1.0

**Comment by pombredanne** [comment]
@LeChasseur thank you for the additional details that's helpful to help investigate!

**Comment by pombredanne** [comment]
I am attaching the set of current rules and exact files that are at play to help create the unit tests later.
[ticket-2171.zip](https://github.com/nexB/scancode-toolkit/files/5149521/ticket-2171.zip)

**Comment by pombredanne** [comment]
Fixed in develop. Thank you
