### ISSUE TITLE
AGPLv3 reference recognized as GPLv2

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2174]
### Description

https://github.com/openimis/openimis-be-api_fhir_py/blob/master/LICENSE.md

is recognized as:

AGPL-3.0-only
GPL-2.0-only
Kevan Stannard License

while it should only be AGPL.

### How To Reproduce

> Tell us how to reproduce the issue. 

get
https://github.com/openimis/openimis-be-api_fhir_py/blob/master/LICENSE.md

and run scancode
### System configuration

> For bug reports, it really helps us to know:

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by pombredanne** [comment]
Thank you++

**Comment by pombredanne** [comment]
Fixed and merged in develop.
