### ISSUE TITLE
AGPL3 only recognized as "or later"

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2176]
### Description
https://raw.githubusercontent.com/openimis/openimis-be-api_fhir_py/master/setup.py

recognized as:

        "agpl-3.0-plus",
        "agpl-3.0"

but there is no "or later" in the file.

### How To Reproduce

> Tell us how to reproduce the issue. 

https://raw.githubusercontent.com/openimis/openimis-be-api_fhir_py/master/setup.py
run scancode

### System configuration

> For bug reports, it really helps us to know:

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by pombredanne** [comment]
Thanks!
the match is that:
```
          "start_line": 15,
          "end_line": 15,
          "matched_rule": {
            "identifier": "agpl-3.0-plus_101.RULE",
            "license_expression": "agpl-3.0-plus",
            "licenses": [
              "agpl-3.0-plus"
            ],
            "is_license_text": false,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": true,
            "matcher": "2-aho",
            "rule_length": 1,
            "matched_length": 1,
            "match_coverage": 100.0,
            "rule_relevance": 100.0
          },
          "matched_text": "AGPL"
        },
```
which means we are missing a rule for this variant     license='GNU AGPL v3',

**Comment by pombredanne** [comment]
Fixed and merged in develop! Thank you!
