### ISSUE TITLE
GFDL detected where none present

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2177]
### Description

https://bitbucket.org/nielsenb/aniso8601/raw/6bcea1cd4c50134bb6f3825cf3cd7f79cda039b9/aniso8601/interval.py

is recognized as:

        "bsd-new",
        "gfdl-1.1"

but there is no gfdl

### System configuration

> For bug reports, it really helps us to know:

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by pombredanne** [comment]
Thank you ++ for the report. Fixed and merged in develop
