### ISSUE TITLE
Direction for generating requirements file

### ISSUE THREAD

**Issue by Abhishek-Dev09-zz** [nexB/scancode-toolkit#2182]
For example:

`'ftfy <  5.0.0; python_version == "2.7"',
'ftfy>=  5.0.0; python_version > "3"',`
See this issue at jazzband/pip-tools#1202
 For pinning such wheels , we need to drop py2 support. For now remove such constraint , keep only python 3 package in setup.py . 

For creating requirements files with hashes for all os/arch/python 

- PYTHON_EXE=python3 ./configure 
- source bin/activate
- pip install -r etc/scripts/req_tools.txt
- python etc/scripts/freeze_and_update_reqs.py --find-links thirdparty --requirement requirements-py36_all.txt

For creating requirements files with hashes as per os/arch/python .
- python3 etc/scripts/deps_download.py --find-links https://github.com/Abhishek-Dev09/thirdparty/releases/tag/v2.0 --requirement etc/conf/requirements-"$python_version"_all.txt --dest thirdparty
- python etc/scripts/freeze_and_update_reqs.py --find-links thirdparty --requirement etc/conf/requirement-"$python_version"_"$platform".txt

**Comment by pombredanne** [comment]
@Abhishek-Dev09 re:
> ftfy < 5.0.0; python_version == "2.7"', 'ftfy>= 5.0.0; python_version > "3"',

Could we use an older version of ftfy on Python 3.0?

**Comment by Abhishek-Dev09** [comment]
Don't know if we dont remove `python_version` , Then you will not get this package in requirement files.

**Comment by pombredanne** [comment]
Eventually we built a tool that handles creation, documentation and publishing of wheels and source https://github.com/nexB/scancode-toolkit/tree/1bddb92c70abcf26cf9435061e429bae62cbe040/etc/release
And this is also part of the https://github.com/nexB/skeleton

See https://github.com/nexB/skeleton/blob/main/etc/scripts/gen_requirements.py
