### ISSUE TITLE
psycopg: LGPL2 false positive

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2185]
### Description

https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/__init__.py

reports both LGPL2 and LGPL3. The header contains the phrase "version 2" but that refers to the version of the package.

### How To Reproduce
https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/__init__.py
run scancode

### System configuration

> For bug reports, it really helps us to know:

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by pombredanne** [comment]
Fixed and merged in develop! Thanks
