### ISSUE TITLE
psycopg2: GPL3 false positive and OpenSSL exception missed

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2186]
### Description

https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/_ipaddress.py

reports GPL3 and LGPL3, but it is only LGPL3. In addition, the OpenSSL exception is missed.

### How To Reproduce

https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/_ipaddress.py
run scancode

### System configuration

> For bug reports, it really helps us to know:

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by pombredanne** [comment]
Fixed in develop. Thank you
