### ISSUE TITLE
psycopg2: AGPL false positive and missed OpenSSL exception

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2187]
### Description

https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/_json.py

AGPL and LGPL reported (it is only LGPL), OpenSSL exception missed

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by pombredanne** [comment]
Fixed in develop. Thank you
