### ISSUE TITLE
psycopg2: LGPL 2.0 and LGPL 2.1 false positive, missed LGPL3 and OpenSSL exception

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2188]
### Description

https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/errors.py

Reported: LGPL 2.0 and 2.1, missed LGPL 3.0 and OpenSSL exception

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

Linux
57dab7d242e17e1e74b412ec893188f9dfc39d0a

**Comment by LeChasseur** [comment]
I want to add that the same license header leads to various results, compare with 
https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/extensions.py
and
https://raw.githubusercontent.com/psycopg/psycopg2/master/lib/errorcodes.py (without OpenSSL exception)

**Comment by pombredanne** [comment]
Thank you ++ for the reports. These have been fixed and merged in develop
