### ISSUE TITLE
develop: False positive detections for `facebook-patent-rights-2`

### ISSUE THREAD

**Issue by fviernau** [nexB/scancode-toolkit#2189]
### Description

I wanted to try-out the upcoming 3.2 release and therefore used revision 3068680.
I compared the scan results against the ones from ScanCode 3.0.2.
For `facebook-patent-rights-2` revision 3068680 reports false positive detections which were not reported in version 3.0.2

### How To Reproduce

Run this bash script:
```
#!/bin/bash

mkdir temp
cd temp

# Get the files to scan
wget https://files.pythonhosted.org/packages/6e/4d/4d2fe93a35dfba417311a4ff627489a947b01dc0cc377a3673c00cf7e4b2/Pygments-2.6.1.tar.gz
wget https://files.pythonhosted.org/packages/2c/2f/7b4d0b639a42636362827e611cfeba67975ec875ae036dd846d459d52652/numpy-1.19.1.zip
tar xfv Pygments-2.6.1.tar.gz
unzip numpy-1.19.1.zip

# copy the files to scan into scan-dir
mkdir scan-dir
cp Pygments-2.6.1/doc/_build/doctrees/faq.doctree scan-dir
cp numpy-1.19.1/doc/neps/nep-template.rst scan-dir 
cp numpy-1.19.1/numpy/fft/_pocketfft.c scan-dir

scancode --json-pp scancode-result.json -l scan-dir
cat scancode-result.json
```

Outcome: finding point to:
- binary data
-    ``` 
     this NEP as an example) or licensed under the Open Publication License_.
       _Open Publication License: https://www.opencontent.org/openpub/```
- Licensed under a 3-clause BSD style license - see LICENSE.md

### System configuration

* What OS are you running on? Ubuntu 20.04
* What version of scancode-toolkit was used to generate the scan file? 3068680
* What installation method was used to install/run scancode? ran the script in the `dist` dir.

**Comment by pombredanne** [comment]
Thank you ++
Note that to help with finding more about the issue I use this:
`scancode -l --license-text --license-text-diagnostics --json-pp -`

**Comment by pombredanne** [comment]
See also https://github.com/numpy/numpy/pull/17238

**Comment by pombredanne** [comment]
And FYI, https://github.com/numpy/numpy/pull/17238 has been merged in numpy

**Comment by pombredanne** [comment]
This is all fixed in develop now. Thank you ++ for the report!

Note that in order to provide decent examples on how to fix these issues in the future I tried to make small focus commits for everyone's "edification" :smiley_cat:

**Comment by fviernau** [comment]
Thanks @pombredanne for fixing these before the 3.2 release, helps a lot! Cheers F
