### ISSUE TITLE
need support to run on multiple processes

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#219]
It seems scancode can run its test cases on multiple processes. It would be nice if scancode can run its scans on multiple processes.

**Comment by pombredanne** [comment]
great idea. Can you elaborate a bit what you have in mind?

**Comment by balusarakesh** [comment]
The idea is to take input(number of processes) from users with an extra option in the `CLI` like `-n 4` where the scans run on 4 processes in parallel. By default we can set this value to 1. In this way we can speed up the process of running scans.

**Comment by pombredanne** [comment]
This has been implemented as part of #267 . Closing
