### ISSUE TITLE
Delete license ogc-2006 which is a duplicate of ogc-1.0

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#2190]
Delete license ogc-2006 which is a duplicate of ogc-1.0.  

Note that ogc-1.0 is equivalent to SPDX license OGC-1.0.

**Comment by pombredanne** [comment]
@DennisClark Thanks! note that we would not delete, but rather do these steps:
1. mark the `ogc-2006` license with `is_deprecated: yes`
2. reassign all rules and tests that referenced to `ogc-2006` to `ogc-1.0`

**Comment by DennisClark** [comment]
@pombredanne   This still needs to be done, please.  We only need ogc-1.0 and not this one.

**Comment by pombredanne** [comment]
@DennisClark ack :+1:

**Comment by pombredanne** [comment]
Fixed in develop. Thank you!
