### ISSUE TITLE
Recognize NPM Node packages

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#220]
When using scancode to scan a codebase it must detect npm packages based on `package.json` and `node_modules` directory trees. 
The basic code is already in, but need to be plugged in actual scans

**Comment by balusarakesh** [comment]
already avaliable

**Comment by pombredanne** [comment]
This is not plugged in the scan proper yet

**Comment by pombredanne** [comment]
All merged and fixed
