### ISSUE TITLE
Recognize Maven and JAR Java packages

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#221]
When using scancode to scan a codebase it must scan the `JAR` files with extension `.jar` in a different way and provide metadata from these packages by extracting the files and reading the corresponding `pom.xml` or `.pom`.
Sometimes there can be multiple JARs embedded in a single JAR(`This is an example of one such JARs - `http://ws4j.googlecode.com/files/ws4j-1.0.1.jar`) and in that case an implementation of some hierarchical relation would be good. 
This metadata must be written into the file given as output from scancode and this file can contain metadata regarding all the packages in the codebase.

**Comment by balusarakesh** [comment]
Added parser for Maven packages in the commit `https://github.com/nexB/scancode-toolkit/commit/febc9340d0185064dbb5b176b4c050823011388b`

**Comment by pombredanne** [comment]
Basic support for Maven is in now. I am not sure we cover bare Jars and Wars correctly, though this is another ticket to create
