### ISSUE TITLE
Recognize Nuget Windows packages

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#222]
When using scancode to scan a codebase it must scan the packages like nuget with extension `.nupkg` in a different way and provide metadata from these packages by extracting the files and reading the corresponding `.nuspec` file. This metadata must be written into the file given as output from scancode and this file can contain metadata regarding all the packages in the codebase.
Some pointers:
The main website is at: https://www.nuget.org/packages
There is an API. In the call below this downloads the latest versilon of the `Javascript-FastClass` package
https://packages.nuget.org/api/v2/package/Javascript-FastClass/

This call `https://packages.nuget.org/api/v2/package/Newtonsoft.Json/5.0.7` would get a specific version 5.0.7 of `Newtonsoft.Json`

Download URL format:
https://www.nuget.org/api/v2/package/{package_name}/{version}

This article provide some doc on how to use the API: http://chris.eldredge.io/blog/2013/02/25/fun-with-nuget-rest-api/ . This is based on ATOM and MSFT WCF and is rather verbose. 

The nuspec files spec is at: https://docs.nuget.org/create/nuspec-reference and this provide some insights on how packages are created: https://docs.nuget.org/create/creating-and-publishing-a-package

See also: https://en.wikipedia.org/wiki/Open_Packaging_Conventions

There is a new json format: http://docs.nuget.org/Consume/ProjectJson-Format

These may be tools of interest:
- https://github.com/python-openxml/opc-diag

**Comment by balusarakesh** [comment]
added parser for Nuget packages in the commit `https://github.com/nexB/scancode-toolkit/commit/febc9340d0185064dbb5b176b4c050823011388b`

**Comment by pombredanne** [comment]
Basic support now in develop. Closing
