### ISSUE TITLE
Invalid value error at cli.py, line 860 of version 3.1.1

### ISSUE THREAD

**Issue by pitargue** [nexB/scancode-toolkit#2221]
I'm trying to run Scancode in a docker container.  Obviously I don't have all the libraries installed and I can't seem to figure out what's missing.  This is the error I'm getting.

$ /gitdisk/9.4.0h0/scancode-toolkit-3.1.1/scancode -clip -n 72 --json - axis >& scancode_results.json

Setup plugins...
Collect file inventory...
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try 'scancode --help' for help on options and arguments.

Error: Invalid value: ERROR: failed to collect codebase at: 'axis'
Traceback (most recent call last):
  File "/gitdisk/9.4.0h0/scancode-toolkit-3.1.1/src/scancode/cli.py", line 860, in run_scan
    max_in_memory=max_in_memory
  File "/gitdisk/9.4.0h0/scancode-toolkit-3.1.1/src/scancode/resource.py", line 284, in __init__
    self._populate()
  File "/gitdisk/9.4.0h0/scancode-toolkit-3.1.1/src/scancode/resource.py", line 443, in _populate
    parent = parent_by_loc.pop(top)
KeyError: '/gitdisk/9.4.0h0/axis/sequans/src/4G/asw/apps/host/rcs/api'

So, what do I need to install to make this run to completion?

**Comment by pombredanne** [comment]
@pitargue thanks for the report. Let me see what is the issue.
Also could you try to reproduce with the newer 3.2.0rc1 version at https://github.com/nexB/scancode-toolkit/releases/tag/v3.2.0rc1

**Comment by pitargue** [comment]
Closing issue.  Installed python 3.6 following the directions on the install page, and all is well.  I must of fat fingered the original configuration of the docker image missing some package listed on the install page.  So, pilot error.  :-)
