### ISSUE TITLE
Resolve circular module dependencies 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2233]
### Description

ScanCode depends on plugins and plugins depend on "plugincode" which is in ScanCode.
"plugincode" also depends on "commoncode" which is also in ScanCode.

Therefore we need to extract "plugincode" and "commoncode" as external wheels to avoid circular dependencies.

**Comment by pombredanne** [comment]
After a chat with @JonoYang and @majurg things are a little more muddied and byzantine. There are weird (even if small) cross-modules dependencies creeping in several places. Here is the story so far as well as the proposed cure.

### Make `commoncode` as its own repo and independent package
- [x] need to remove the dep on `from scancode_config import scancode_root_dir' which should be guarded with a try/except and come with a sensible default, like in commoncode.fileutils
- [x] from then on `commoncode` can be a dep for every other repo/package/module without circular deps problems


### Make`plugincode` as its own repo and independent package
- [x] `plugincode` needs to become its own library to break the circular dep plugin->scancode->plugin
- [x] imports `from scancode` and `from scancode.resource` needs to be refactored (likely by moving things to commoncode?)
- [x] beside the standard lib and third-party, `commoncode` will be the only other dep of `plugincode` (better would be to have no dependencies at all, but we would still need scancode.resources that would be moved to commoncode)


### Make `extractcode` as its own repo and independent package

- this will help with porting scancode to other OS and architectures as there would be fewer dependencies
- today extractcode is mostly independent except for a circular dependency between extractcode and typecode that we would need to be broken and a bit of code used for packagedcode rubygems so scancode does not need full extractcode.
We would:
- [x] make extractcode depend on typecode: this way we have a scancode fully functional without extractcode
- [x] remove dep of packagedcode on extractcode for rubygems, replacing that by standard library calls

Additionally we could also make `extractcode` work in a more limited way without any of the native code plugins
for libarchive and p7zip:
- [x] the standard library supports fewer archive formats but still can handle zip and tar archives and gzip, bzip2 and lzma/xz compression. See https://docs.python.org/3/library/archiving.html.
- this could be using an extra_requires on the new `extractcode` package that would install native libarchive and 7z plugins ... but would otherwise have less feature without them.
- this usage of the standard library could also be made part of `commoncode`


### Make `typecode` as its own repo and independent package

- [x] `typecode` would become a dep for `extractcode` and `scancode`, but *would not have circular* package dependencies
- [x] `typecode` would have extra features when `extractcode` is installed using try/except imports but would not explicitly depend on it (except may be with an `extra_requires`?). This is achieved with the new typecode.extractible module

- [x] we would make `typecode.contenttype.Type.is_archive` work also without `extractcode` in a degraded way probably using a list of extensions of known archive files and simpler tests using the standard library more limited support with only zip/gz/bz2/lzma and tar. See also `extractcode` suggestion of using an `extra_requires`.

- [ ] `typecode` would not depend explicitly on a `typecode-libmagic` provider plugin. But it would fail loudly to run if you do not install at least one such plugin. (Or a default could be to use a system-provided libmagic but is likely to be less stable and robust so this is not something to consider for now)

Instead there would be two `extra_requires` defined in the setup: 

- [ ] one to depend on `typecode-libarchive` "system-provided" e.g. system installed where the plugins tries to get the path to libmagic and mgic DB from the current installation. 
- [ ] one to depend on `typecode-libarchive` "plugin-provided" e.g. plugin bundling libarchive and libmagic

- [ ] typecode-libarchive plugins would be removed as default deps from `scancode` since they would be only a typecode dependency.



###  For scancode-toolkit we will use extra_requires for optional `extractcode`.
 - [ ] extra_requires for extractcode


### We need to release these new repos as their own to PyPI and consider adopting a skeleton approach

We are starting to have many repos for our projects and consistency with a common skeleton is becoming a must IMHO
There is cookiecutter https://github.com/cookiecutter/cookiecutter but this feels more as a one off generation
But I likely much prefer this approach from @jaraco who among many other things is the maintainer extraordinaire of setuptools (and an impressively smart cookie) See https://blog.jaraco.com/a-project-skeleton-for-python-projects/ and https://github.com/jaraco/skeleton and  https://github.com/jaraco/jaraco.develop/blob/master/skeleton.md

- consider using some automation to help dealing with releases of PyPI. One approach would be to automatically publish in the CI based on tags
- and also integrate the automated publication of docs on read the docs in the CI based on tags


### Potentially also make `licensedcode`, `cluecode` and `packagedcode` their own package.

**Comment by rpotter12** [comment]
@pombredanne This sounds too good. :+1: :)

**Comment by pombredanne** [comment]
Todo on each repo:
1. simplify setup.py version handling
2. create a README for each new repo
3. consider documentation for each new repo
4. review and streamline license (especially with #2222 )
5. what about AUTHORS and Changelogs

**Comment by pombredanne** [comment]
We will need a common branch in scancode-toolkit to remove the modules that have been split:
- with removal of the module
- the updates to setup.py
- the new wheels added to thridparty/ for now

**Comment by pombredanne** [comment]
Status for now:
- https://github.com/nexB/commoncode has been created by @majurg 
- https://github.com/nexB/plugincode has been created by @JonoYang 

We will be using the jaraco's skeleton ways with this repo https://github.com/nexB/skeleton

**Comment by pombredanne** [comment]
Also todo: add a dependency on plugincode for the binary providers in https://github.com/nexB/scancode-plugins

**Comment by AyanSinhaMahapatra** [comment]
closing this, we have these in different repos now
