### ISSUE TITLE
Incorrect license detection

### ISSUE THREAD

**Issue by lemoshi** [nexB/scancode-toolkit#2242]
### Description

The license detection is not correct when we scan the file `ghostscript-9.25~dfsg+1/contrib/gdevhl12.c` in the bundle `ghostscript_9.25~dfsg+1.orig.tar.xz`. The text below
```
108    Thanks to L. Peter Deutsch <ghost@aladdin.com> for making gdevdjet.c
109    and gdevdljm.[ch] available under a dual AFPL/GPL license.
```
is detected as
```
        "licenses": [
          {
            "key": "gpl-1.0-plus",
            "score": 11.0,
            "name": "GNU General Public License 1.0 or later",
            "short_name": "GPL 1.0 or later",
            "category": "Copyleft",
            "is_exception": false,
            "owner": "Free Software Foundation (FSF)",
            "homepage_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
            "text_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
            "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-1.0-plus",
            "spdx_license_key": "GPL-1.0-or-later",
            "spdx_url": "https://spdx.org/licenses/GPL-1.0-or-later",
            "start_line": 2,
            "end_line": 2,
            "matched_rule": {
              "identifier": "gpl_200.RULE",
              "license_expression": "gpl-1.0-plus",
              "licenses": [
                "gpl-1.0-plus"
              ],
              "is_license_text": false,
              "is_license_notice": false,
              "is_license_reference": true,
              "is_license_tag": false,
              "matcher": "2-aho",
              "rule_length": 2,
              "matched_length": 2,
              "match_coverage": 100.0,
              "rule_relevance": 11
            },
            "matched_text": "   and gdevdljm.[ch] available under a dual AFPL/GPL license."
          }
        ],
```

The expected result is `AFPL or GPL`

### How To Reproduce

> scancode --copyright --license --info --license-diag --license-text --only-findings --is-license-text --strip-root --processes 4 --json-pp result.json 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
Linux
* What version of scancode-toolkit was used to generate the scan file?
3.2.0
* What installation method was used to install/run scancode? (pip/source download/other)
pip

**Comment by pombredanne** [comment]
Good catch. 
I can see this in http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=contrib/gdevhl12.c;h=9f4d617cbfaf75a8dc78b3bfddaf109a8bde2b88;hb=d7d05e0ef54662054e038b421795e6e7dedd1e4a
The code has a properly detected  `public-domain-disclaimer` at the top for reference.
And the exact text for the error is: 
```
 Thanks to L. Peter Deutsch <ghost@aladdin.com> for making gdevdjet.c
 and gdevdljm.[ch] available under a dual AFPL/GPL license.
```
But the file referenced:
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=devices/gdevdjet.c;h=ea81dead4806a9e7ed81eb8f87149adc8f45ff4e;hb=d7d05e0ef54662054e038b421795e6e7dedd1e4a
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=devices/gdevdljm.c;h=fa859164f5398be783f1a82e76f39563737e68ba;hb=d7d05e0ef54662054e038b421795e6e7dedd1e4a
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=devices/gdevdljm.h;h=679bd561b9fb33f82dfb33c3aefa231ba69507cc;hb=d7d05e0ef54662054e038b421795e6e7dedd1e4a

... have a different notice pointing to a LICENSE file at:
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=LICENSE;h=572496a331cefa0933a9e997374f5e7dde3b95c8;hb=d7d05e0ef54662054e038b421795e6e7dedd1e4a

which is clearly an AGPL-3.0 notice from what I can see.


Note that for the code in question but latest version all the files have a properly detected  `public-domain-disclaimer`:
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=contrib/gdevhl12.c;h=9f4d617cbfaf75a8dc78b3bfddaf109a8bde2b88;hb=HEAD
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=devices/gdevdjet.c;h=9f4d617cbfaf75a8dc78b3bfddaf109a8bde2b88;hb=HEAD 
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=devices/gdevdljm.h;h=9f4d617cbfaf75a8dc78b3bfddaf109a8bde2b88;hb=HEAD 
- http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=devices/gdevdljm.c;h=9f4d617cbfaf75a8dc78b3bfddaf109a8bde2b88;hb=HEAD 

Therefore the notice `available under a dual AFPL/GPL license.` is lacking clarity on several counts.
1. for the version you found, the LICENSE is AGPL and not AFPL/GPL.
2. the newer version is all  `public-domain-disclaimer` and not AFPL/GPL.

For something to make sense, this should have been:
- `available under the AGPL-3.0 license.` for the version 9.25
- `available under the a public domain dedication with warranty disclaimer` for the latest version
- note that it may have been correct a long time ago when the AFPL/GPL dual license was in use
And in all cases this is really not a license notice, but rather some mostly incorrect reference to the license of some other files.

Ping to @chris-liddell or @HenryStiles from Artifex : is there something that could be fixed upstream? I have found that Ghostscript licensing notices are often lacking clarity (and this is an understatement). I helped clean things up in the Linux kernel and could help doing the same there too if you fancy it.

@lemoshi In the meantime here is what I suggest to resolve this small mess:

1. add a new rule with the text `available under a dual AFPL/GPL license`  with this .yml data file:
```
license_expression: afpl-9.0 OR gpl-1.0-plus
is_license_notice: yes
relevance: 90
```
this `relevance: 90` is capturing the uncertainty as to which license this is about. This will catch the 

2. also add a "false positive" rule for the whole text:
```
Thanks to L. Peter Deutsch <ghost@aladdin.com> for making gdevdjet.c
and gdevdljm.[ch] available under a dual AFPL/GPL license.
```
 with this .yml data file:
```
license_expression: afpl-9.0 OR gpl-1.0-plus
is_license_reference: yes
is_false_positive: yes
relevance: 100
```
This will basically skip entirely when found verbatim as in this form this is now always a misleading reference to a license of some other files and not from the current file. (Though it may have been correct a long time ago when the AFPL/GPL dual license was in use, it was still not a statement about the license of the file in which it is found)

**Comment by chris-liddell** [comment]
It was not a "good catch". The license and copyright of that file was changed with the permission of the original author.

**Comment by pombredanne** [comment]
@chris-liddell thank you for chiming in!

> It was not a "good catch". The license and copyright of that file was changed with the permission of the original author.

The "good catch" statement was about @lemoshi  having caught the bug we are contemplating here in scancode detection ... not about some other thing.

> Equally, the quoted comment is not a statement of the distribution license, but a note of credit and thanks to the L Peter Deutsch - I see to no reason to expunge or edit that record from the source files.

Fair enough. I think I have way to cope with this using  a "false positive" license detection rule to avoid having this trigger an incorrect AFPL or GPL detection. These kind of comments about licenses are always a source of confusion for a license detection engine

**Comment by chris-liddell** [comment]
> @chris-liddell thank you for chiming in!
> 
> > It was not a "good catch". The license and copyright of that file was changed with the permission of the original author.
> 
> The "good catch" statement was about @lemoshi having caught the bug we are contemplating here in scancode detection ... not about some other thing.

Sorry, that came across as bitchier than I intended, I didn't mean to be rude about it.

> > Equally, the quoted comment is not a statement of the distribution license, but a note of credit and thanks to the L Peter Deutsch - I see to no reason to expunge or edit that record from the source files.
> 
> Fair enough. I think I have way to cope with this using a "false positive" license detection rule to avoid having this trigger an incorrect AFPL or GPL detection. These kind of comments about licenses are always a source of confusion for a license detection engine

If there's a "tag" or something that I can add at or near the comment that would be easier, I'm happy to do that?

**Comment by pombredanne** [comment]
@chris-liddell re:

> Sorry, that came across as bitchier than I intended, I didn't mean to be rude about it.

We are cool. It could be found rude to be @ tagged on a random github ticket too, so I am grateful that it caught your attention!

> If there's a "tag" or something that I can add at or near the comment that would be easier, I'm happy to do that?

I think the best way would be to adopt something similar to the way the Linux kernel documents licenses (which a way that was really started by uboot https://gitlab.denx.de/u-boot/u-boot )

See https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/process/license-rules.rst
I helped a bit there and the TLDR; outcome is that you can mostly just grep the licenses of the kernel and get excellent and accurate results.

This is now also codified at the set of REUSE guidelines at the FSFE https://reuse.software/

Either way works. 

A quick example would be: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/asm-generic/atomic-instrumented.h#n1

There are a few quirks though because "public domain" is not a known SPDX license identifier. But there are ways around this.
Again I am game to help there.

**Comment by pombredanne** [comment]
So just to be clear: 
Using a comment with a tag such as `// SPDX-License-Identifier: GPL-2.0` using https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/  and https://spdx.org/licenses/ for licenses is the way to go.

This would not be tagging a specific comment as not being a license BUT, it would be tagging the whole file as being under a license... so this would bring clarity alright.

**Comment by chris-liddell** [comment]
I assume we're allowed C style comments, so:
/* SPDX-License-Identifier: AGPL-3.0-only */

And does it have to be first line in the file?

Part of our problem is is that *most* of Ghostscript is distributed under APGL *and* commercial licenses. Hence why we don't *generally* mention licenses other that in the LICENSE and doc/COPYING files (let's leave out the situation with the URW++ PCL Truetype fonts!).

The exceptions are the "third-party libraries" (e.g libjpeg, libpng etc) each of which have their own license files included in their respective directories. And the files under "contrib" directory: those are files that, for one reason or another, are *only* included in the AGPL licensed distribution.

So, for those files under contrib/ I'll happily add something along the lines of the above

**Comment by pombredanne** [comment]
re

> I assume we're allowed C style comments, so:
> /* SPDX-License-Identifier: AGPL-3.0-only */

Yes, any comment style works. Keeping things on a single line is important though to keep things easy to grep.
FWIW, using the atypical `//` C++ style comments in C code has been a topic of many discussion on LKML and was wanted by Linus to make this stick out ;) 

> And does it have to be first line in the file?

No, that's justs the convention adopted in the Linux kernel that Linus wanted for the licenses to be super prominent. It can be anywhere.
Putting it towards the top of files is the most common way

> Part of our problem is is that most of Ghostscript is distributed under APGL and commercial licenses. Hence why we don't generally mention licenses other that in the LICENSE and doc/COPYING files (let's leave out the situation with the URW++ PCL Truetype fonts!).

You could also have very much something such as:
`/* SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Artifex-Commercial-License */`
and document what `LicenseRef-Artifex-Commercial-License` means somewhere once in your doc.
That would be both explicit, unambiguous and 100% to anyone IMHO.

I assume that by `Ghostscript is distributed under APGL and commercial licenses` you meant that this is a choice: open source is AGPL OR you can buy a commercial license to lift the AGPL requirement, correct?

**Comment by chris-liddell** [comment]
> re
<SNIP>
> Part of our problem is is that most of Ghostscript is distributed under APGL and commercial licenses. Hence why we don't generally mention licenses other that in the LICENSE and doc/COPYING files (let's leave out the situation with the URW++ PCL Truetype fonts!).
> 
> You could also have very much something such as:
> `/* SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Artifex-Commercial-License */`
> and document what `LicenseRef-Artifex-Commercial-License` means somewhere once in your doc.
> That would be both explicit, unambiguous and 100% to anyone IMHO.

For the contrib/ AGPL (or other!) licensed files, I can make that call myself. But the rest of the sources that needs a decision from "head office" and possibly reviewed by an attorney. I'm happy to raise the suggestion at the next "full" developers meeting.

> I assume that by `Ghostscript is distributed under APGL and commercial licenses` you meant that this is a choice: open source is AGPL OR you can buy a commercial license to lift the AGPL requirement, correct?

Basically, yes.

**Comment by lemoshi** [comment]
Hi Chris, thanks for your confirmation and the insight here.

Hi Philippe,
Really appreciate your help again. I learned a lot from this thread.
I'll try to create a pull request with the two rules you suggested above.

> add a new rule with the text available under a dual AFPL/GPL license with this .yml data file:
```
license_expression: afpl-9.0 OR gpl-1.0-plus
Is_license_notice: yes
relevance: 90
```
>this relevance: 90 is capturing the uncertainty as to which license this is about. This will catch the

>also add a "false positive" rule for the whole text:
>Thanks to L. Peter Deutsch <ghost@aladdin.com> for making gdevdjet.c
>and gdevdljm.[ch] available under a dual AFPL/GPL license.
>with this .yml data file:
```
license_expression: afpl-9.0 OR gpl-1.0-plus
is_license_reference: yes
is_false_positive: yes
relevance: 100
```

I have a few questions here:
1. There is no version specified in the text `dual AFPL/GPL`. Is there any rule that requests the `gpl-1.0-plus` should be used instead of the latest `gpl-3.0-plus`?
2. what does the `relevance` do in the `.yml` file? I saw it before but didn't understand it.
3. Is this `relevance` score `90` made via your experience or some algorithm?
4. In your response, your word was truncated at `This will catch the`. Did you want to say something here?

**Comment by pombredanne** [comment]
@lemoshi you asked:

> 1. There is no version specified in the text dual AFPL/GPL. Is there any rule that requests the gpl-1.0-plus should be used instead of the latest gpl-3.0-plus?

- For the AFPL, the v8 is not much seen ever so I went with v9.
- For the GPL, all the versions of the license are clear there: https://www.gnu.org/licenses/gpl-3.0.html#section14

>> _If the Program does not specify a version number of the GNU General Public License, you may choose any version ever published by the Free Software Foundation._

What this means practically is that `gpl-1.0-plus` satisfies the "any version ever published" so that's what we use in the cases where the version of the GPL or LGPL is not explicit.


> 2. what does the relevance do in the .yml file? I saw it before but didn't understand it.

The relevance is documented there: https://github.com/nexB/scancode-toolkit/blob/0c08442e46606938547a2e4fec70780c6ca6f345/src/licensedcode/models.py#L733

The relevance can either be:
- computed automatically (the default) based on the number of words in a rule: 18 words and up means 100% relevance and below we have a degradation
- set explicitly by hand in the YAML for small rules that are highly relevant and other cases 

See https://github.com/nexB/scancode-toolkit/blob/0c08442e46606938547a2e4fec70780c6ca6f345/src/licensedcode/models.py#L1093

        Compute and set the `relevance` attribute for this rule. The
        relevance is a float between 0 and 100 where 100 means highly
        relevant and 0 means not relevant at all.
        For instance a match to the "gpl" or the "cpol" words have a fairly low
        relevance as they are a weak indication of an actual license and could be a
        false positive and should therefore be assigned a low relevance. In contrast
        a match to most or all of the apache-2.0 license text is highly relevant. The
        Rule relevance is used as the basis to compute a match score.
        The relevance is either pre-defined in the rule YAML data file with the
        "relevance" attribute or computed base on the rule length here using
        this approach:
        - a false positive or a negative rule has a relevance of 100.
        - a rule of length equal to or larger than a threshold has a 100 relevance
        - a rule of length smaller than a threshold has a relevance of
          100/threshold, rounded down.


> 3. Is this relevance score 90 made via your experience or some algorithm?

This is to convey that there is no ambiguity about the licenses... but some ambiguity about the version of AFPL. That's from experience.

> 4. In your response, your word was truncated at This will catch the. Did you want to say something here?

I wanted to say:

`This will catch the .... fact that there is some ambiguity about the version of AFPL (8 or 9)`
