### ISSUE TITLE
Update contribution guidelines to include doc, changelogs and authors

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2252]
This would help keeping these up to date!

**Comment by remote007** [comment]
hey @pombredanne @AyanSinhaMahapatra is this issue still open ?

**Comment by AyanSinhaMahapatra** [comment]
@remote007 yes!

**Comment by shricodev** [comment]
I'd like to work on this issue but have some doubts.🤔
Should they fetch the information from the files and add it to the **CONTRIBUTING.rst** file, or should I add links to those files?
Should they be added to the very bottom? @pombredanne @AyanSinhaMahapatra

**Comment by shricodev** [comment]
If we want to copy the entire contents of any **filename.rst**, we can simply use ` .. include::filename.rst` appears to be what works for me. This is possible because the files are in .rst format, which markdown(.md) does not support. Should I go ahead with the edits?
Correct me If I am wrong.

**Comment by AyanSinhaMahapatra** [comment]
No not like that, CONTRIBUTING.rst is a guideline for contributing, and we need to mention there that:

* you need to also update the CHANGELOG if you're making important changes that need to be communicated, like a change in the API/CLI options/behaviour/a new feature and other misc things like that.
* you need to update the AUTHORS to include your own name if it's a code change or a significant doc/other changes 
* a link to the RTD docs where there is a more detailed guide for contributing code/docs respectively

So these isn't talking just about copying/including the contents as whole AFAIK

**Comment by shricodev** [comment]
Thank you very much for clarifying @AyanSinhaMahapatra.
I was simply complicating things. So all we have to do now is add these details to the file, right?
