### ISSUE TITLE
Need a variable to store SHA512 of Nuget packages

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#226]
https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/models.py
In the Package class we don't have a variable to store `SHA512` for a given package.
Nuget API provides the SHA512 for its packages, for example - `https://api.nuget.org/v3/catalog0/data/2015.02.12.00.46.55/microsoft.aspnet.razor.3.2.3.json`

**Comment by pombredanne** [comment]
We also need to add support for explicit sha512 and sha256 hashing in commoncode

**Comment by pombredanne** [comment]
#229 Merged.
