### ISSUE TITLE
Add new timescale license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2268]
See https://github.com/timescale/timescaledb/blob/master/tsl/LICENSE-TIMESCALE
and https://blog.timescale.com/blog/building-open-source-business-in-cloud-era-v2/

But we careful as versions have changed over time
https://github.com/timescale/timescaledb/commits/master/tsl/LICENSE-TIMESCALE

We could also treat these as plain proprietary rules.

**Comment by sritasngh** [comment]
@pombredanne I would like to work at this issue.
