### ISSUE TITLE
License data structure:  In ouput include SPDX expressions, report matched rule by expression and do not report individual licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2278]
In ScanCode output include SPDX expressions, report matched rule by expression and do not report individual licenses. Licenses should be reported as their own top-level "licenses"

**Comment by AyanSinhaMahapatra** [comment]
This is completed and merged.

detected licenses are reported by license-expression and no license keys, and license reference data at top level.
