### ISSUE TITLE
Design the data structure for reporting per-license data when we use license expressions

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2279]
For use in ABC-TK, ScanCode-TK, ABCMger, etc

**Comment by sritasngh** [comment]
@pombredanne can you provide some more information please:)

**Comment by AyanSinhaMahapatra** [comment]
We don't report per license data at the file level but at the top-level license references which is a unique record of each license seen in the scan.

This is merged, closing this!
