### ISSUE TITLE
Inaccurate license detection: detect gpl-2.0-plus and lgpl-2.0-plus in addition to expect epl-1.0 and lgpl-2.1-plus

### ISSUE THREAD

**Issue by amottier** [nexB/scancode-toolkit#2297]
### Description

When running ScanCode on [this file](https://gitlab.ow2.org/sat4j/sat4j/-/blob/master/org.sat4j.core/src/main/java/org/sat4j/ExitCode.java) it will correctly report:
* epl-1.0 : https://gitlab.ow2.org/sat4j/sat4j/-/blob/master/org.sat4j.core/src/main/java/org/sat4j/ExitCode.java#L5
* lgpl-2.1-plus : https://gitlab.ow2.org/sat4j/sat4j/-/blob/master/org.sat4j.core/src/main/java/org/sat4j/ExitCode.java#L10

But incorrectly find:
* gpl-2.0-plus
* lgpl-2.0-plus

### How To Reproduce

Download the file and run ScanCode asking it to produce the HTML report:

`wget https://gitlab.ow2.org/sat4j/sat4j/-/raw/master/org.sat4j.core/src/main/java/org/sat4j/ExitCode.java && ./scancode --license --html test.html ./ExitCode.java`

### System configuration

* OS: `Debian GNU/Linux 10 Buster amd64`
* Cersion of scancode-toolkit: `3.1.1`
* Installation method used to install/run scancode: install as an application by downloading `scancode-toolkit-3.1.1.tar.bz2` from GitHub Release Page

**Comment by pombredanne** [comment]
@amottier Thanks!

See the commits in https://github.com/nexB/scancode-toolkit/pull/2296/commits/7a75cfe0b72cd0c001e6dfc634cc0f1b70486afb and https://github.com/nexB/scancode-toolkit/pull/2296/commits/9ebdb56b0493b910aa673312733f5ab500d9b194 that were originally reported by @mhow2 on Gitter

**Comment by amottier** [comment]
@pombredanne I'm willing to test the changes brings by 7a75cfe and 9ebdb56 but it seems that they are not referenced in any branch (I get a GitHub warning: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.").

Is it possible for you to create a branch that include those changes? Thanks.

**Comment by amottier** [comment]
Actually it seems that commit 2991fa79989b8443574dcb41834cac0a87ce40f4 as the same content as 7a75cfe and 50c95f2ea278f148a61b95464b05ebe7d776a0d6 is the same as 9ebdb56. So I guess that I can test use any branch that include those two commit for my test.

**Comment by amottier** [comment]
I did give a try to both `license-updates-2020-10` and `release-20-12-prep` without success.

I'm getting the following error while running my test on `license-updates-2020-10` (with Python 2.7):
```
Error: Invalid value: ERROR: failed to setup plugin: scan:licenses:
Traceback (most recent call last):
  File "/home/antoine/workspace/github/other-projects/scancode-toolkit/src/scancode/cli.py", line 702, in run_scan
    plugin.setup(**requested_options)
  File "/home/antoine/workspace/github/other-projects/scancode-toolkit/src/licensedcode/plugin_license.py", line 130, in setup
    get_index(return_value=False)
  File "/home/antoine/workspace/github/other-projects/scancode-toolkit/src/licensedcode/cache.py", line 66, in get_index
    _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)
  File "/home/antoine/workspace/github/other-projects/scancode-toolkit/src/licensedcode/cache.py", line 274, in get_cached_index
    rules_data_dir=rules_data_dir)
  File "/home/antoine/workspace/github/other-projects/scancode-toolkit/src/licensedcode/models.py", line 492, in get_rules
    validate_rules(rules, licenses)
  File "/home/antoine/workspace/github/other-projects/scancode-toolkit/src/licensedcode/models.py", line 535, in validate_rules
    raise InvalidRule('\n'.join(message))
InvalidRule: Errors while validating rules:

ignorables must be a list of strings
```

and when trying to run `./configure` on `release-20-12-prep` (with Python 3.7)
```
ERROR: Could not find a version that satisfies the requirement contextlib2==0.5.5
ERROR: No matching distribution found for contextlib2==0.5.5
```

@pombredanne any recommendations regarding the branch/tag/commit and Python version I might use to confirm that this issue is fixed? Thanks.

**Comment by amottier** [comment]
We finally managed to run version `21.2.25` with Python 3.7 (version provided by Debian Buster) and we can confirm that the issue is now resolved.

Thanks a lot @pombredanne :clap:
