### ISSUE TITLE
Add license tests with new text

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2300]
See https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt

**Comment by sritasngh** [comment]
@pombredanne Can I work on this issue?

**Comment by sritasngh** [comment]
https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fmesher/LICENCE.txt
fmesher is also distributed under the terms of the Aladdin 
Free Public License. Do they have to be added under Aladdin free Public License test?

**Comment by pombredanne** [comment]
Hi! Thank you for your patience!
You could run detection on both https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt and https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fmesher/LICENCE.txt and add rules as needed to get things working correctly.

@AyanSinhaMahapatra do you thing you could lend a hand to @itssingh ?

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne Yes! Looking into it now.

**Comment by sritasngh** [comment]
Thank You so much:)

**Comment by sritasngh** [comment]
@pombredanne @AyanSinhaMahapatra When I scanned [fsolver](https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt) , I got scanned result where [two lines of "Triangle" , CMS-9318163 and an NSERC 1967 Scholarship.  There is no warranty whatsoever.  Use at your own risk.](https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt#L321) license text has been detected as [Generic Bare Warranty Disclaimer](https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L230), but there is no Generic License as you can see [link](https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L207) isn't working. This two lines are detected under warranty-disclaimer_32.RULE which is "There is no warranty". Which is incorrect.

**Comment by sritasngh** [comment]
@pombredanne @AyanSinhaMahapatra  I couldn't find the original License for "Triangle". What can I do for this license text detected https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L230?

**Comment by sritasngh** [comment]
As discussed on the channel I will add a proprietary license rule for the text matched [here](https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L230). There is also a Lua copyright used in [fsolver](https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt#L378), It's scanned output gives different licenses [other-permissive](https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L269), [newsletr](
https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L305), [gpl-2.0-plus](https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L341), and unknown-license-reference(https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L233). How can a single copyright give different License references?

**Comment by pombredanne** [comment]
> @pombredanne @AyanSinhaMahapatra I couldn't find the original License for "Triangle". What can I do for this license text detected https://gist.github.com/itssingh/4eee9bc42fadf1b86e6c533767119080#file-fsolver_output-json-L230?

These should be new rules:
- `distributed under the terms of the Aladdin  Free Public License:` should be made a rule for `afpl-9.0` with a `relevance: 99` the rationale being that we have no version, so we pick the latest and degrade relevance to denote this uncertainty.

- the next segment is detected correctly including the fact it is modified. Nothing to add there . https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt#L7:L303

- For this, the text https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt#L339:L357 there could be made into a `proprietary-license` rule 

- And this is an old, legacy and rare Lua license. We can treat it for now as an `other-permissive` rule until we see more occurrence of it https://github.com/Bacchustaf/SyRe_MSc/blob/078df81c8d13c873b15c92684167f4503bd766df/xfemm-code-310/mfemm/pfemm/fsolver/LICENCE.txt#L382:L407

**Comment by sritasngh** [comment]
@pombredanne fsolver uses `Aladdin Free Public License version 8` so shouldn't there be a license rule for `afpl-8.0_url_3.RULE` `fsolver is distributed under the terms of the Aladdin Free Public License:` with 

> license_expression: afpl-8.0
is_license_reference: true
match_coverage: 100.0
rule_relevance: 27
ignorable_copyrights:
    - Copyright (c) 1994, 1995, 1997, 1998, 1999, 2000 Aladdin Enterprises, Menlo Park, California,
        U.S.A.
ignorable_holders:
    - Aladdin Enterprises, Menlo Park, California, U.S.A.

**Comment by pombredanne** [comment]
I do not want to see fsolver as a word in rules, this is too rare.
(Adding new words in rules is not something that's entirely free computing-wise)

So `afpl-8.0_url_3.RULE` as `distributed under the terms of the Aladdin Free Public License` is fine
And this `afpl-8.0_url_3.yml`:
```YAML
license_expression: afpl-8.0
is_license_notice: yes
relevance: 99
```
