### ISSUE TITLE
Stream JSON output

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2303]
When doing large scans to JSON, it is possible to use a lot of RAM as the whole scan result data set must be in memory at once such that it can be serialized to JSON.
To avoid this we could consider iterating instead with a JSON streams processor such as https://github.com/dcbaker/jsonstreams that should help avoiding exhausting memory.

**Comment by pombredanne** [comment]
See https://github.com/nexB/scancode-toolkit/blob/abfe573bfe1f8a18c17418a45e0c1ff57c8a07fc/src/formattedcode/output_json.py for the place where we would likely plug that.

The first thing would be to check that this (having the whole results set in RAN) is indeed a memory hog

**Comment by JonoYang** [comment]
This has been merged into develop. Closing.
