### ISSUE TITLE
thirdparty/dev directory missing from scancode 3.2.3 release

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#2306]
When I download scancode from the first two links (scancode-toolkit-3.2.3.tar.bz2, and scancode-toolkit-3.2.3.zip) on the scancode 3.2.3 download page and run the `configure` script , I get the error that there are missing dependencies. I found out that this occurs because the configure script is attempting to install the dev dependencies, but the directory that contains the dev dependencies is missing from scancode-toolkit-3.2.3.tar.bz2, and scancode-toolkit-3.2.3.zip. The archives from the links labeled `Source code` has the `thirdparty/dev` directory and can be configured with no issues.

![image](https://user-images.githubusercontent.com/6044800/97474321-389ac800-1909-11eb-90db-458d5afafc47.png)

We should add the `thirdparty/dev` directory and its contents to the main release

**Comment by pombredanne** [comment]
This has been fixed
