### ISSUE TITLE
Failed to load Resource: 1045031 while scanning. All results lost.

### ISSUE THREAD

**Issue by FrankHeimes** [nexB/scancode-toolkit#2320]
I downloaded scancode-toolkit-3.2.3 and ran this command on Windows 10, version 1909, OS build 18363.900:
`scancode -clpieu --html D:\scancode-output.html D:\Dev\Main`

using `C:\Program Files\Python36\python.exe`, Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32.

It started and scanned almost 1 million files for 9 days straight.
`Setup plugins...`
`Collect file inventory...`
... scanned 968613 files ...

But then it bailed out with an exception, throwing all results from the long work into the bin. See below.

Any explanation?
I did not delete any files or folders from `D:\TEMP`, to answer that question in advance.

Is there a chance that a file with intermediate results still exists? If yes, where?
Except scanning many sub directories manually instead of the root directory, can I somehow make sure that intermediate errors don't trash the entire results collected so far?

```
...
[-#------------------] 967685 Scanned: libecpg.lib
[---------------#----] 968613 Scanned: xml_woarchive.obj
Removing temporary files...done.
Traceback (most recent call last):
  File "C:\My\scancode-toolkit-3.2.3\Scripts\scancode-script.py", line 33, in <module>
    sys.exit(load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')())
  File "C:\My\scancode-toolkit-3.2.3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\My\scancode-toolkit-3.2.3\lib\site-packages\commoncode\cliutils.py", line 95, in main
    standalone_mode=standalone_mode, **extra)
  File "C:\My\scancode-toolkit-3.2.3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\My\scancode-toolkit-3.2.3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\My\scancode-toolkit-3.2.3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\My\scancode-toolkit-3.2.3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\my\scancode-toolkit-3.2.3\src\scancode\cli.py", line 458, in scancode
    *args, **kwargs)
  File "c:\my\scancode-toolkit-3.2.3\src\scancode\cli.py", line 855, in run_scan
    quiet=quiet, verbose=verbose, kwargs=requested_options, echo_func=echo_func,
  File "c:\my\scancode-toolkit-3.2.3\src\scancode\cli.py", line 1046, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "c:\my\scancode-toolkit-3.2.3\src\scancode\cli.py", line 1140, in scan_codebase
    location, rid, scan_errors, scan_time, scan_result, scan_timings = next(scans)
  File "C:\My\scancode-toolkit-3.2.3\lib\site-packages\click\_termui_impl.py", line 259, in next
    rv = next(self.iter)
  File "c:\my\scancode-toolkit-3.2.3\src\scancode\pool.py", line 48, in wrap
    return func(self, timeout=timeout or 3600)
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 735, in next
    raise value
commoncode.resource.ResourceNotInCache: Failed to load Resource: 1045031 from 'D:\\TEMP\\scancode-tk-3.2.3-ob0ge5qs\\scancode-codebase-2020-11-03T143446.667944-oz9ws723\\27\\000ff227'

(scancode-toolkit-3.2.3) C:\My\scancode-toolkit-3.2.3>
```

**Comment by pombredanne** [comment]
@FrankHeimes I am sorry that this failed. 
This is going to be a rather hard to diagnose bug as it looks somehow intermediate results files that were cached may have gone missing?

Did you run this with  exactly these arguments?
`scancode -clpieu --html D:\scancode-output.html D:\Dev\Main`

What are the characteristics of the machine this is running under? (RAM, CPU?)?

This also could be a bug that I am currently working on and it seems to be very similar to #2293 , #2160 #2106 #2293  but that's sounds far fetched.

**Comment by pombredanne** [comment]
Did you run this scan using multiprocessing (e.g the --process or -n option?)

**Comment by FrankHeimes** [comment]
@pombredanne 
Yes, I ran exactly the command as noted on an Intel Core i7-2600K 3.4 GHz, 16GB RAM, 64 Bit Windows 10, version 1909, OS build 18363.900.

No, I did not use the `--process` or `-n` option. I noticed that the process used only one core.

I think I'll try again using the multi-process option and after configuring a separate `TEMP` folder that is unknown to any other process.

**Comment by pombredanne** [comment]
@FrankHeimes there is something else too to consider
 @JonoYang worked on #2303 which does JSON streaming of the output and may help with very large scans.


The other thing to consider may be https://github.com/nexB/scancode.io/ where the scans would be stored in a DB and therefore any intermediate glitch would be likely mitigated.

**Comment by pombredanne** [comment]
> i7-2600K 3.4 GHz, 16GB RAM, 64 Bit Windows 10, version 1909, OS build 18363.900.

I would guesstimate that a scan of ~ 1M files would take about 5 hours with  7 processes on a machine like yours and a JSON output.

**Comment by FrankHeimes** [comment]
I think this was a one-time issue. Two subsequent scans finished without any problems.

**Comment by pombredanne** [comment]
@FrankHeimes Thanks reporting back.

**Comment by jloehel** [comment]
@pombredanne Can we please open this again. I experience these failures more often with long running (more than 5 hours) scans. Multiple scans are running in "parallel" (asyncio) and use multiple processes.

Python version: 3.11
Scancode version: v32.3.2
OS: Ubuntu 21.04 LTS

If you need any debugging information please let me know.

**Comment by mjherzog** [comment]
@jloehel Please open a new issue because the SCTK version for this issue was 3.2.3.
