### ISSUE TITLE
Detection of google maps platform terms of service

### ISSUE THREAD

**Issue by MarcelBochtler** [nexB/scancode-toolkit#2322]
## Short Description
ScanCode should detect [Google Maps Platform Terms of Service](https://cloud.google.com/maps-platform/terms) as used by e.g. https://mvnrepository.com/artifact/com.google.android.libraries.places/places/2.4.0

## Possible Labels

- license scan

## Select Category

-  [ ] Enhancement
-  [x] Add License/Copyright
-  [ ] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [ ] Expand Support
-  [ ] Other

**Comment by pombredanne** [comment]
@MarcelBochtler Thanks for this. I can see that there are several versions at https://cloud.google.com/maps-platform/terms#prev-versions ... do you think that every historic version should be added?

Do you feel like drafting a PR for this license?

@DennisClark ^

**Comment by MarcelBochtler** [comment]
> do you think that every historic version should be added?

[The library where I found this license](https://mvnrepository.com/artifact/com.google.android.libraries.places/places/2.4.0) does not mention a specific version of the license in its metadata.
But at least for the Android SDK License you do have [historic](https://github.com/nexB/scancode-toolkit/blob/9d53e94474347da5292aae7be9bb7cedb4399a9a/src/licensedcode/data/licenses/android-sdk-preview-2015.LICENSE) and ["unversioned"](https://github.com/nexB/scancode-toolkit/blob/9d53e94474347da5292aae7be9bb7cedb4399a9a/src/licensedcode/data/licenses/android-sdk-license.LICENSE) licenses available.

**Comment by pombredanne** [comment]
All the versions published at https://cloud.google.com/maps-platform/terms#prev-versions have been added in July 2021 with https://github.com/nexB/scancode-toolkit/commit/a54667792f1467961b4940dff7d08822ca4d72fa ... closing ... Happy new year.
