### ISSUE TITLE
Add full A/L/G PL/FDL texts to "plus"/"or-later" variants of the licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2327]
Today we only have a notice for the text of  the "or later" variants licenses.
Such as here: https://github.com/nexB/scancode-toolkit/blob/a78fda974392c08dfcec3a41a283a303a6978b46/src/licensedcode/data/licenses/gpl-2.0-plus.RULE
We want to also have the full text there.
I suggest simply to do this:
```
< text of the "or later" notice >
---------------------------------------
< full license text >
````

**Comment by pombredanne** [comment]
@DennisClark FYI

**Comment by pombredanne** [comment]
@chinyeungli this also means that these texts will be usable as-is in Attribution generation

**Comment by sankha555** [comment]
Hello @pombredanne, I have tried to study the specifications of this issue and would like to work on it. 

From what I understood in the specifications and seeing the license files in the codebase, I could find many "plus" variants of licenses. As an example, am I correct in understanding that it is required to append the gpl-1.0 license text after the notice in the gpl-1.0-plus.LICENSE file? There were many other examples like numerous variants of the gpl-2.0 license as well. If you think that I have understood the issue properly, could you please assign it to me and also provide other necessary inputs for the same? Thanks!

**Comment by pombredanne** [comment]
This has been fixed and merged. Closing
