### ISSUE TITLE
Copyright and URLs data structure: Data structure inconsistency in results

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-toolkit#2350]
### Description

`copyrights`, `holders`, `authors` use the `value` key where `urls` and `emails` use `url` and `email` as keys.

```
'urls': [{'url': 'http://pypi.python.org/pypi/python-cjson/1.0.5', 'end_line': 57, 'start_line': 57}]
'copyrights': [{'value': 'Copyright (c) 2009, by the authors', 'end_line': 4, 'start_line': 3}]
```

**Comment by NinaPacifier** [comment]
hey @tdruez  Can I work on this issue??

**Comment by tdruez** [comment]
@NinaPacifier Sure 👍

**Comment by akugarg** [comment]
Hey @tdruez !
If this issue is still open Can I work on this?

**Comment by tdruez** [comment]
Hi @akugarg, yes PR welcome 👍
