### ISSUE TITLE
Python 2.7 deprecation on Debian

### ISSUE THREAD

**Issue by jeremiah** [nexB/scancode-toolkit#2352]
### Description
When running ./configure on a Debian-based system, I receive this warning;

```DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support```

### How To Reproduce

git clone scancode.git
./configure

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)  -- Debian Buster
* What version of scancode-toolkit was used to generate the scan file? -- git log says;
`ba4bbf216 (HEAD -> master, tag: v3.2.3, origin/master) Merge pull request #2305 from nexB/release-3`
* What installation method was used to install/run scancode? (pip/source download/other) -- source download

**Comment by pombredanne** [comment]
@jeremiah Thanks! we dropped support for Python 2 entirely now in the latest release. So you can update then.
