### ISSUE TITLE
Lift pygments requirements

### ISSUE THREAD

**Issue by priv-kweihmann** [nexB/scancode-toolkit#2356]
latest release still enforces the usage of a very outdated version of pygments: https://github.com/nexB/scancode-toolkit/blob/b14ca7b2af3ee09486d9cf704752118db5d75064/setup.py#L188.
After patching the setup.py locally, I'm running fine with pygments 2.7.x release for my use cases.

I couldn't figure out from the commit that introduced the limitation, if the usage of that (even then) old version as done on purpose or not.

Please remove the version limitation and add support for pygments 2.7.x releases

**Comment by pombredanne** [comment]
At this stage, Pygments is now vendored in typecode, so we have no more a hard constraint on the version.
This will be fixed in the next release after v21.2.25

**Comment by pombredanne** [comment]
This is fixed now in https://github.com/nexB/scancode-toolkit/blob/6d2320ca15a7e19b50ffd151449406a1d41d65cc/setup.cfg#L92
