### ISSUE TITLE
Lift version limitation for bitarray

### ISSUE THREAD

**Issue by priv-kweihmann** [nexB/scancode-toolkit#2358]
latest release still enforces the usage of an outdated version of bitarray:

https://github.com/nexB/scancode-toolkit/blob/b14ca7b2af3ee09486d9cf704752118db5d75064/setup.py#L156

After patching the setup.py locally, I'm running fine with bitarray 1.6.1 release for my use cases.
Please remove the version limitation and add support for bitarray < 2.0 releases

**Comment by pombredanne** [comment]
@priv-kweihmann Thanks. I will fix that in the next release  after v21.2.25

**Comment by pombredanne** [comment]
This has been fixed a while back
https://github.com/nexB/scancode-toolkit/blob/6d2320ca15a7e19b50ffd151449406a1d41d65cc/setup.cfg#L57
Closing now.
