### ISSUE TITLE
Installation issues in MacOS Big Sur 11.1

### ISSUE THREAD

**Issue by archanray** [nexB/scancode-toolkit#2369]
### Description

> Please leave a brief description of the bug or feature request:
Can not install scann. It spits out the following error:
`
ERROR: Could not find a version that satisfies the requirement scann
ERROR: No matching distribution found for scann
`

### How To Reproduce

> Tell us how to reproduce the issue. 

`pip install scann`

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux) `MacOS Big Sur 11.1` Python details: `Python 3.8.5`, `pip 20.3.3` 
* What version of scancode-toolkit was used to generate the scan file? `Have none`
* What installation method was used to install/run scancode? (pip/source download/other) `pip`

**Comment by tdruez** [comment]
@LousyLory what about `pip install scancode-toolkit`?

https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#pip-install

**Comment by mohsinm-dev** [comment]
I think you should upgrade the pip to the new version and try to run it again, Hopefully, it will work

**Comment by pombredanne** [comment]
Fixed in ScanCode TK v21.2.25 ... pushed in a few
