### ISSUE TITLE
Add OIL licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2384]
See https://github.com/StarkDrones/OPNLv1/blob/main/.github/LICENSE.md and  https://github.com/StarkDrones/OPNLv2/blob/main/.github/LICENSE.md

There seems to some use in the wild https://github.com/search?q="Open+Innovation+License"&type=code that may jsutify a named license.
The alternative is to create multiple detection rules instead.
The licenses are somehow problematic for reuse as they are Company-specific

**Comment by akugarg** [comment]
Hey!@pombredanne
Can I work on this?

**Comment by dhruvitpokharna** [comment]
@pombredanne Hey can i start trying to resolve the issue and also can you give a head start.

**Comment by pombredanne** [comment]
@akugarg thanks!
