### ISSUE TITLE
Package license data structure: Improve tracing of license detection in package manifests

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2389]
There is little to no logging in place as well as no intermediate results and it is therefore hard to understand how a package `declared_license` has been detected in a `license_expression`. We should potentially keep all the same intermediate results as we have in regular license detection as a diagnostic option, and while this may seem verbose this would be essential to track issues.

**Comment by AyanSinhaMahapatra** [comment]
This was added with the following PRs:
* https://github.com/nexB/scancode-toolkit/pull/2961
* https://github.com/nexB/scancode-toolkit/pull/3154
* https://github.com/nexB/scancode-toolkit/pull/3286
We now have the entire license detection objects with the matches (with file origin info) for detections in package manifests. so this is completely traceable. Closing!
