### ISSUE TITLE
Setting up 21.2.9 fails when running initial configure.

### ISSUE THREAD

**Issue by bnowacky** [nexB/scancode-toolkit#2391]
### Description

cloning git repo, and running ./scancode -h fails  with missing packages : 
ERROR: Could not find a version that satisfies the requirement pyahocorasick<1.5,>=1.4 (from scancode-toolkit[full])
ERROR: No matching distribution found for pyahocorasick<1.5,>=1.4

### How To Reproduce

- Clone repo or download from releases page (scancode-toolkit-21.2.9_py36-macos.tar.xz) 
-  untar/unzip downloaded files, or cd into cloned repo.
- in repo run ./scancode -h
- configuration fails with error on missing requirements. 

### System configuration

> For bug reports, it really helps us to know:
What OS: Mac BigSur 11.3, Python 3.8.2
What version of Scancode:  scancode-toolkit-21.2.9
Installation: downloaded tar from release page, ran ./scancode -h

**Comment by pombredanne** [comment]
@bnowacky I do not think there is a test that ran on macOS bigsur
Could you run the following test for me?
and paste the results here?
This is to isolate possible setup issues and check if you can actually compile native code alright for wheels if needed: 
```
mkdir scancode-tmp
curl -o scancode-tmp/virtualenv.pyz https://bootstrap.pypa.io/virtualenv/virtualenv.pyz
python3.8 scancode-tmp/virtualenv.pyz scancode-tmp
source scancode-tmp/bin/activate
pip install --verbose pyahocorasick
```

Also this would be another test that recreates mostly what configure does:
```
git clone https://github.com/nexB/scancode-toolkit
cd scancode-toolkithttps://github.com/nexB/scancode-toolkit
python3.8 etc/thirdparty/virtualenv.pyz .
source bin/activate
pip install -e . -r requirements.txt
```

**Comment by bnowacky** [comment]
Not a problem! Do you want me to manually install pyahocorasick, and then try to run scancode and paste the results, or just the results of the pip install?

**Comment by pombredanne** [comment]
@bnowacky the pip install output would be enough

**Comment by pombredanne** [comment]
@bnowacky ping... I would like to fix this and release a new dot version ASAP as this is getting me real worried
I have also this https://github.com/nexB/scancode-plugins/issues/4 reported by @tiulpin which should be fixed now

**Comment by pombredanne** [comment]
Fixed in v21.2.25

**Comment by mensfeld** [comment]
I'm seeing it still with 21.2.25. Also https://github.com/nexB/scancode-toolkit/releases/tag/v21.2.25 has release notes for 21.2.9 (at least title). Didn't you release by accident 21.2.19 as 2.2.25?

**Comment by mensfeld** [comment]
@pombredanne should I create a second issue or is there a branch that I could test? Sorry to bother you :pray:

**Comment by pombredanne** [comment]
@mensfeld 

> I'm seeing it still with 21.2.25. Also https://github.com/nexB/scancode-toolkit/releases/tag/v21.2.25 has release notes for 21.2.9 (at least title). Didn't you release by accident 21.2.19 as 2.2.25?

That was just a title typo! fixed . Thanks





> @pombredanne should I create a second issue or is there a branch that I could test? Sorry to bother you pray

Please create a new issue
