### ISSUE TITLE
Make Extractcode a separate tool of ScanCode

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#240]
`https://github.com/nexB/scancode-toolkit/tree/develop/src/extractcode`
I think it's a good idea to make `Extractcode` in Scancode-toolkit a separate opensource product of nexB.
If converted into a command line tool instead of just a package in Scancode-toolkit it can serve as a perfect tool for extraction of archives.

Observation 1 : 
[389-ds-base-devel-1.2.10.2-18.el6_3.i686.rpm.txt](https://github.com/nexB/scancode-toolkit/files/198044/389-ds-base-devel-1.2.10.2-18.el6_3.i686.rpm.txt)
[a-csv-2.0.0.tgz.txt](https://github.com/nexB/scancode-toolkit/files/198043/a-csv-2.0.0.tgz.txt)
[bountysource-0.0.14-fx1.xpi.txt](https://github.com/nexB/scancode-toolkit/files/198045/bountysource-0.0.14-fx1.xpi.txt)
[evaporate.typescript.definitelytyped.0.0.1.nupkg.txt](https://github.com/nexB/scancode-toolkit/files/198047/evaporate.typescript.definitelytyped.0.0.1.nupkg.txt)
[pep8-1.7.0-py2.py3-none-any.whl.txt](https://github.com/nexB/scancode-toolkit/files/198048/pep8-1.7.0-py2.py3-none-any.whl.txt)
[spring-context-4.2.5.RELEASE.jar.txt](https://github.com/nexB/scancode-toolkit/files/198046/spring-context-4.2.5.RELEASE.jar.txt)

All the above files are corrupted(I opened them with a notepad and placed some random strings in random places) even then extractcode is able to extract most of the files, where as `7-zip`, `archive manager` and `unzip` in ubuntu are not able to extract them.

Observation 2:
Another observation I made is while extracting a large zip file (200 MB, will post a link to google drive if needed) and these are the results : 

Using Ubuntu 14.04:
Extractcode was able to extract 14975 files
Archive manager was able to extract 13086 files
7zip was able to extract 14707 files
unzip command was able to extract 14707 files

Using Windows 8.1:
Extractcode was able to extract 14975 files
7zip was able to extract 14710 files

**Comment by pombredanne** [comment]
Extractcode has at last been extracted in https://github.com/nexB/extractcode !
Closing now.
