### ISSUE TITLE
./etc/configure.py Exception raised for latest release 'v21.2.9' 

### ISSUE THREAD

**Issue by arturrz** [nexB/scancode-toolkit#2406]
### Description

The goal is to update scancode-toolkit from v3.1.1 to v21.2.9. When configuring for 'first use' an exception in raised at line 84 of
<path_to_scancode>/etc/configure.py. Additionally a SyntaxError: invalid syntax is rasied. Se bellow for errors:

* Configuring ScanCode for first use...
  File "/home/scancode-toolkit-21.2.9/etc/configure.py", line 84
    raise Exception(f'Failed to run {cmd}') from e
                                         ^
SyntaxError: invalid syntax
./scancode: line 119: /home/scancode-toolkit-21.2.9/bin/scancode: No such file or directory

### How To Reproduce

To reproduce follow the next steps: 
1.- Got to https://github.com/nexB/scancode-toolkit/releases and download  scancode-toolkit-21.2.9_py36-linux.tar.xz (I'm running the toolkit on linux)
2.- I ran both, ./scancode -h and ./configure
3.- You should see the errors mentioned before on the screen. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? 

NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"

* What version of scancode-toolkit was used to generate the scan file?
v21.2.9
* What installation method was used to install/run scancode? (pip/source download/other)
Downloaded scancode-toolkit-21.2.9_py36-linux.tar.xz extracted it and then ran ./scancode -h and ./configure.

**Comment by arturrz** [comment]
As a side note, I did the same procedure for v3.2.3 and it works perfectly. :)

**Comment by pombredanne** [comment]
@arturrz sorry for this! Which Python version do you have installed? I think that Ubuntu 16 has Python 2 only by default and that would be the error cause (the error message is not helpful and should be updated) 
The default Python3 there is Python 3.6
To work around this:
1. get Python 3.6 installed either through pyenv or the deadsnakes ppa
2. if using pyenv you can make this your default shell or local python
3. alternatively if using the deadsnakes ppa or building your own Python, you can use this for the first run:
- `CONFIGURE_PYTHON_EXECUTABLE=<path to your python3.6> ./scancode -h`
- OR if python3.6 in your path: `CONFIGURE_PYTHON_EXECUTABLE=python3.6 ./scancode -h`
or with configure:
- OR `CONFIGURE_PYTHON_EXECUTABLE=<path to your python3.6> ./configure`
- OR if python3.6 in your path: `CONFIGURE_PYTHON_EXECUTABLE=python3.6 ./configure`

**Comment by pombredanne** [comment]
@arturrz ping? does 3.6 work for you?

**Comment by arturrz** [comment]
Hi, thanks for your support. I'll be working on this durign this week. I'll ping you with the outcomes of this work around, i confirmed and our  system has Python2.6 and 3.7 installed. But haven't done any tests yet. Will keep you posted. Thanks for your support on this.

**Comment by pombredanne** [comment]
> our system has Python2.6 and 3.7 installed.

In this case the release tarballs that are for 3.6 only. But scancode can be installed from PyPI alright and support 3.7

**Comment by arturrz** [comment]
I installed python3.6 and all of the suggestions you made in your first response work perfectly. :)
No need to install scancode from PyPI. So I have no feedback on that workaround but still thanks for the support. 
Great tool since v3.1.1 :)

**Comment by pombredanne** [comment]
@arturrz you wrote:

> Great tool since v3.1.1 :)

thank you for the kind words! It is hopefully getting better and better.
