### ISSUE TITLE
Update NLTK to latest version

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2414]
The current version has several regex warnings. 
The work consists in:
1. collecting the wheel and sdist craft the ABOUT files and creating a PR to add the latest NLTK in https://github.com/nexB/thirdparty-packages/tree/main/pypi
2. update the setup.cfg and requirements.txt 
3. run the copyright tests, fix the code until all tests pass. Submit a PR early would be good.

**Comment by piyush0411** [comment]
Hi @pombredanne Sir
I was reading through the documentation and code for this toolkit and found this issue a good one to start. 
I just wanted to confirm if I was thinking in the right direction to solve this issue.
NLTK released its latest version 3.5. So changing the version of nltk in the two files mentioned will solve this issue.
If I am thinking correctly, I would like to solve this issue. Kindly help me if I am wrong.

Thanks :)

**Comment by Aayush-hub** [comment]
@pombredanne @tdruez Can I take up this issue?

**Comment by Pushpit07** [comment]
Updating to version 3.5 would be an easy task considering it is a minor version bump. @pombredanne,  I would like to take this up.

**Comment by pombredanne** [comment]
At this stage we have dropped using NLTK in favor of a lightweight fork https://github.com/nexB/pygmars/
So I am closing this is as this no longer applies.
