### ISSUE TITLE
RFC: Report all detected license data by expression

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2416]
Today we have a combo of reporting by license key and by license expression.
Since we detected license expressions, we should always report everything by license expression.
This would mean a significant output data structure change:
- The `licenses` file attribute would go away.
- Instead the detection details would be provided under the `license_expressions`
- We should avoid to repeat each license details and instead introduce a top-level `licenses` codebase attribute that would list the detected license reference information (and could optionally include the standard license text)

**Comment by AyanSinhaMahapatra** [comment]
This is merged and in develop now. We have license references reported seperately and license data is reported by license-expression and not license keys.
