### ISSUE TITLE
Add recognize function to detect different types of packages known to scancode

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#242]
Take the example of the module `pyrpm` (URL - `https://github.com/nexB/scancode-toolkit/tree/develop/src/packagedcode/pyrpm)` in `Packagedcode` which can detect an RPM file in a given codebase. It is a good idea to have a `recognize` function in each and every subclass of the `Package` class which can detect the corresponding packages.
Hierarchy of the Package types must be strictly maintained. For example, `Bower` packages are a type of `NPM` packages and the corresponding `BowerPackage` must be a subclass of `NpmPackage` but not the `Package` class itself.

A working scenario : 
Each and every file in a given codebase must be passed to the recognize functions of all the `Package` subclasses and if any recognize function returns true then the file must be processed depending on the subclass whose method returned true.

**Comment by balusarakesh** [comment]
@pombredanne  please add any notes which is relevant to this issue.

**Comment by pombredanne** [comment]
@balusarakesh the original ticket is  #117 ... This tickets= sounds like a dupe
