### ISSUE TITLE
GPL2 file recognized as GPL3

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#2430]
### Description

I am scanning libiwinfo and the files in it (such as iwinfo_wext.c is recognized as GPL3 or later even though it clearly is GPL2: https://github.com/wlanslovenija/iwinfo/blob/master/iwinfo_wext.c

**Comment by pombredanne** [comment]
Thank you! This will be fixed in the next release

**Comment by pombredanne** [comment]
This has been merged in develop and is in the v21.3.31 release.
Thank you ++
