### ISSUE TITLE
Timeout error despite high timeout

### ISSUE THREAD

**Issue by Angi2412** [nexB/scancode-toolkit#2431]
### Description

I do also get this TimeoutError error even when I provide a rather large timeout of 43200 seconds (12 hours).

Here is an output of the log:
```
Scanned: /octoscan/octoscan/data/files/7700de4a/docker-docker-ce/19.03.14-3.el7.x86_64/src/linux_x86_64/docker-ce-19.03.14-3.el7.src.rpm-extract/engine.tgz-extract/engine/vendor/archive/tar/testdata/pax-records.tar-extract/file
03/10/2021 11:10:55 AM DEBUG: nontext_ratio1: 1.0
03/10/2021 11:10:55 AM DEBUG: nontext_ratio2: 1.0
03/10/2021 11:10:55 AM DEBUG: is_likely_binary: True
03/10/2021 11:10:55 AM DEBUG: detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
03/10/2021 11:10:55 AM DEBUG: failure: decodable_as_unicode: False
03/10/2021 12:10:55 PM ERROR: Exception occurred during scan: TimeoutError
```

### How To Reproduce

The scanned file is: `docker-docker-ce 19.03.14-3.el7.x86_64`

```python
from scancode import cli
rc, results = cli.run_scan(
            os.path.split(path)[0], license=True, copyright=True,
            return_results=True, processes=cores, verbose=(os.getenv("DEBUG")), quiet=(not os.getenv("DEBUG")),
            timeout=int(os.getenv("TIMEOUT")))
```

### System configuration
* What OS are you running on? (Windows/MacOS/Linux)
Linux / docker
* What version of scancode-toolkit was used to generate the scan file?
21.2.25
* What installation method was used to install/run scancode? (pip/source download/other)
pip with Python 3.6

**Comment by avishmehta68710** [comment]
i also got this error and when i checked the code in several file instead of importing the whole os library we can import the component in the os library that are needed. i did this experiment as importing the only os modules needed instead of importing the whole os module. when i checked the time difference my method was approx 2 seconds faster and i did that on only one file.
if my method is right can i work on this issue

**Comment by Angi2412** [comment]
I also executed the following code fragment with no problem. It was mentioned in some other issues regarding the timeout error (e.g. https://github.com/nexB/scancode-toolkit/issues/2320):

```
import multiprocessing
tuple(multiprocessing.Pool(4).imap(print, (1, 2, 3)))
```

**Comment by pombredanne** [comment]
@Angi2412 thanks! That's a bug alright. Do you have a download URL for the docker binary?

**Comment by Angi2412** [comment]
@pombredanne Yes, the file `docker-ce-19.03.14-3.el7.x86_64.rpm` can be downloaded from the official docker website -> [here](https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-19.03.14-3.el7.x86_64.rpm).

**Comment by Angi2412** [comment]
I could observe the same behaviour and error message with this file: [moby v20.10.5](https://github.com/moby/moby/releases/tag/v20.10.5).

**Comment by pombredanne** [comment]
@Angi2412 thanks! this helps

**Comment by Angi2412** [comment]
Does v21.3.31 (fa3e3662868c331232f75a93d4b8a1797bc8ddb5) already resolve this issue?

**Comment by pombredanne** [comment]
@Angi2412 not yet fully.
