### ISSUE TITLE
Copyrights in reuse-compliant repositories not detected

### ISSUE THREAD

**Issue by daniel-eder** [nexB/scancode-toolkit#2432]
### Description

ScanCode Toolkit does not find Copyright statements in reuse-compliant repositories. It seems this might be relatively easy to fix by adding a regex to pick up `SPDX-FileCopyrightText: <copyright-statement>`.

### How To Reproduce

1. Scan the reuse example: https://git.fsfe.org/reuse/example/src/branch/master 
2. Note that copyright statements are missing, such as `SPDX-FileCopyrightText: 2017 Peter Janzen` in [cat.jpg.license](https://git.fsfe.org/reuse/example/src/branch/master/img/cat.jpg.license)

### System configuration
Latest version of ORT Toolkit (ScanCode Toolkit version: 3.2.1rc2)

**Comment by pombredanne** [comment]
@daniel-eder and the fix is in for your review :)

**Comment by daniel-eder** [comment]
@pombredanne Fix confirmed! In our example https://git.fsfe.org/reuse/example/src/branch/master/img/cat.jpg.license ScanCode now correctly detects `SPDX-FileCopyrightText: 2017 Peter Janzen`

**Comment by pombredanne** [comment]
This has been merged in develop and is in the v21.3.31 release.
Thank you ++
