### ISSUE TITLE
Copyright detection range is sometime approximative

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-toolkit#2446]
input.txt:

```
Files: src/macos/src/macos_main.cpp
Copyright: 2001, Eric Lavigne
License: curl

Files: docs/examples/rtsp.c
Copyright: 2011, Jim Hollinger
```

`scancode -ce --json-pp - input.txt`

Current results:
```json
"copyrights": [
    {
      "value": "Copyright 2001, Eric Lavigne",
      "start_line": 2,
      "end_line": 3
    },
    {
      "value": "Copyright 2011, Jim Hollinger",
      "start_line": 6,
      "end_line": 6
    }
],
```

Expected results:
```json
"copyrights": [
    {
      "value": "Copyright 2001, Eric Lavigne",
      "start_line": 2,
      "end_line": 2
    },
    {
      "value": "Copyright 2011, Jim Hollinger",
      "start_line": 6,
      "end_line": 6
    }
],
```

The first copyright is detected on line 2 to 3, while only present on line 2, where the second copyright is properly detected on line 6 only.

**Comment by sritasngh** [comment]
@tdruez can I work on this issue?

**Comment by itssingh** [comment]
Input text: 
```
Files: src/macos/src/macos_main.cpp
Copyright: 2001, Eric Lavigne 
License: curl
All rights reserved

Copyright (c) 1991, 1992 Paul Kranenburg <pk@cs.few.eur.nl>
Copyright (c) 1993 Branko Lankester <branko@hacktic.nl>
Copyright (c) 1993 Ulrich Pegelow <pegelow@moorea.uni-muenster.de>
Copyright (c) 1995, 1996 Michael Elizabeth Chastain <mec@duracef.shout.net>
Copyright (c) 1993, 1994, 1995, 1996 Rick Sladkey <jrs@world.std.com>
Copyright (C) 1998-2001 Wichert Akkerman <wakkerma@deephackmode.org>
All rights reserved.
```

Result:
>  "copyrights": [
        {
          "value": "Copyright 2001, Eric Lavigne <pk@cs.few.eur.nl>",
          "start_line": 2,
          "end_line": 4
        },
        {
          "value": "Copyright (c) 1991, 1992 Paul Kranenburg <pk@cs.few.eur.nl>",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Copyright (c) 1993 Branko Lankester <branko@hacktic.nl>",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Copyright (c) 1993 Ulrich Pegelow <pegelow@moorea.uni-muenster.de>",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Copyright (c) 1995, 1996 Michael Elizabeth Chastain <mec@duracef.shout.net>",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Copyright (c) 1993, 1994, 1995, 1996 Rick Sladkey <jrs@world.std.com>",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Copyright (c) 1998-2001 Wichert Akkerman <wakkerma@deephackmode.org>",
          "start_line": 6,
          "end_line": 12
        }
      ],
      "holders": [
        {
          "value": "Eric Lavigne",
          "start_line": 2,
          "end_line": 4
        },
        {
          "value": "Paul Kranenburg",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Branko Lankester",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Ulrich Pegelow",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Michael Elizabeth Chastain",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Rick Sladkey",
          "start_line": 6,
          "end_line": 12
        },
        {
          "value": "Wichert Akkerman",
          "start_line": 6,
          "end_line": 12
        }
      ],
      "authors": [],
      "emails": [
        {
          "email": "pk@cs.few.eur.nl",
          "start_line": 2,
          "end_line": 2
        },
        {
          "email": "branko@hacktic.nl",
          "start_line": 7,
          "end_line": 7
        },
        {
          "email": "pegelow@moorea.uni-muenster.de",
          "start_line": 8,
          "end_line": 8
        },
        {
          "email": "mec@duracef.shout.net",
          "start_line": 9,
          "end_line": 9
        },
        {
          "email": "jrs@world.std.com",
          "start_line": 10,
          "end_line": 10
        },
        {
          "email": "wakkerma@deephackmode.org",
          "start_line": 11,
          "end_line": 11
        }
      ],
      "scan_errors": []
    }
  ]

Start line and end line is incorrect for copyrights and holders whereas it gives correct result for emails field.

**Comment by sritasngh** [comment]
input.txt:
```
`Files: src/macos/src/macos_main.cpp
Copyright: 2001, Eric Lavigne
License: curl`
```
`$ SCANCODE_DEBUG_COPYRIGHT=yes scancode --copyright --json-pp - input.txt`

Result:
```
> DEBUG:cluecode.copyrights:# candidate_lines: evaluating line:(1, 'Files: src/macos/src/macos_main.cpp\n')
> DEBUG:cluecode.copyrights:# candidate_lines: evaluating line:(2, 'Copyright: 2001, Eric Lavigne\n')
> DEBUG:cluecode.copyrights:   candidate_lines: line is candidate
> DEBUG:cluecode.copyrights:# candidate_lines: evaluating line:(3, 'License: curl\n')
> DEBUG:cluecode.copyrights:   candidate_lines: line is in copyright
> DEBUG:cluecode.copyrights:candidate_lines: finally yielding candidates
>     [(2, 'Copyright: 2001, Eric Lavigne\n'), (3, 'License: curl\n')]
```
@pombredanne @tdruez copyright scan result is giving incorrect range because `DEBUG:cluecode.copyrights:   candidate_lines: line is in copyright`. Could it be a good approach if I limit candidate _lines to only single line when it get 

> DEBUG:cluecode.copyrights:# candidate_lines: evaluating line:(2, 'Copyright: 2001, Eric Lavigne\n')
> DEBUG:cluecode.copyrights:   candidate_lines: line is candidate

It will also help to debug this https://github.com/nexB/scancode-toolkit/issues/2445.

**Comment by pombredanne** [comment]
>  Could it be a good approach if I limit candidate _lines to only single line when it get

That would truncate several copyrights. Instead I think a better approach is to post-process the detected values against the original line range and find the correct start and end line (and even better as a bonus the offset or the start and end column in each line)

**Comment by pombredanne** [comment]
>can I work on this issue?

Sure thing, and you do not need to ask for permission! Yet that's always a good idea to ask like you did here so we can avoid stepping on each other's toes. :+1:

**Comment by pombredanne** [comment]
The latest https://github.com/nexB/pygmars/ now supports Token with line numbers and offsets. This is being integrated in copyright detection

**Comment by pombredanne** [comment]
This is now all fixed in the develop branch and we get these results:
```
        copyrights:
            -   value: Copyright 2001, Eric Lavigne
                start_line: 2
                end_line: 2
            -   value: Copyright 2011, Jim Hollinger
                start_line: 6
                end_line: 6
        holders:
            -   value: Eric Lavigne
                start_line: 2
                end_line: 2
            -   value: Jim Hollinger
                start_line: 6
                end_line: 6
        authors: []
```
