### ISSUE TITLE
Unsupported Python, OS, platform or architecture: Only Python 64 bits 3.6 and above are supported

### ISSUE THREAD

**Issue by jonCeg21** [nexB/scancode-toolkit#2448]
### Description
So I came across this plugin and this looks so promising but it does not work on a windows OS.

---------- Supported systems not on windows 10 OS
The supported systems are Mac, Linux and WSL (Windows Subsystem for Linux). Thus I followed this guide: 
https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-6---install-your-linux-distribution-of-choice.
I downloaded the ubuntu 16.04 because of the python3.6 requirement. 

---------- Old ubuntu version + upgrade python version on ubuntu subsystem
Ubuntu 16.04 is equipped with python5.3 so I updated the python version to the 3.6 following this tutorial from edwinksl:
https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get.
Now I had a subsystem for Linux on my windows 10 and python3.6. But when I ran python3 --version I would get the old python5.3. So I then added the alias python3='/usr/bin/python3.6' to my user .bashrc. After this python3.6 appeared when running $python3 --version. 

---------- Prerequisites
I ran the command $ sudo apt install bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev
This installed the necessary prerequisites.

---------- Download and install scancode zip
Then I manually downloaded the scancode zip file scancode-toolkit-21.2.25_py36-linux.tar.xz to my windows 10 machine. I manually copied the zip file to the ubuntu subsytem to my user directory. So my user directory contains the zip file (user directory = ~$). In my user directory I extracted the zip file with the command: tar -xvf scancode-toolkit-21.2.25_py36-linux.tar.xz.
This worked fine and now I have a directory "scancode-toolkit-21.2.25" with al the necessary files in that directory.

---------- PROBLEM
So now when I navigate to the scancode directory and run ./scancode --help I get the message: 
* Configuring ScanCode for first use...
Unsupported Python, OS, platform or architecture: Only Python 64 bits 3.6 and above are supported.
See https://github.com/nexB/scancode-toolkit/ for supported OS/platforms. Enter a ticket https://github.com/nexB/scancode-toolkit/issues asking for support of your OS/platform combo.

---------- QUESTION
How is this possible!? I did everything in my power to make the environment compatible. I have a subsystem for linux for windows 10, I have python3.6, I have the libraries and I have the scancode directory AND still the error states that my python is not sufficient although it is in fact 3.6 and above. Anyone any idea? 

### How To Reproduce

> Read Description to see how to reproduce

### System configuration

> For bug reports, it really helps us to know:

WINDOWS 10 OS + Windows Subsystem for Linux UBUNTU 16.04
WSL 1 NOT WSL 2
PYHTON 3.6.13
SCANCODE 21.2.25
Installation as an Application: Downloading Releases

**Comment by s4-2** [comment]
Hello @jonCeg21 , Yes it is true that on windows this software is not supported and thus many issue regarding this occurs. So I don't have clear idea how would I help but do visit on [Details](Please visit https://github.com/nexB/scancode-toolkit/issues/2366)

**Comment by jonCeg21** [comment]
Thank you @s4-2 for your response. I know it is not supported on Windows, that is why I installed WSL on my Windows machine. This is also the recommended solution in #2366. But when I use WSL 1 ubuntu 16.04 with python 3.6.13 I get the error mentioned above: Unsupported Python, OS, platform or architecture: Only Python 64 bits 3.6 and above are supported. 
So this has something to do with the python interpreter I presume.

**Comment by s4-2** [comment]
@jonCeg21 Yes I think you are right. As it must support 3.6 above python version.

**Comment by jonCeg21** [comment]
After a week of struggling and not reading the scancode documentation, I came to the conclusion that this tool only works on an ubuntu 18.04 OS because that one has native python3.6.9. Using ubuntu20.04 with the python 3.9.8 does not seem to work. Using WSL for Windows does not seem to work or there is little documentation on how to set it up. This ticket reamains open until this issue be solved I presume.

**Comment by pombredanne** [comment]
@jonCeg21 ScanCode is supported on Windows alright and #2366 is a request for comment to possibly drop support for native and support only WSL. For now, this not the case:

I do not think that you combo of `WINDOWS 10 OS + Windows Subsystem for Linux UBUNTU 16.04` and `WSL 1 NOT WSL 2` has ever been tested. At least for now, I do not know how to run tests under WSL, WSL1 is unlikely to ever be something that could run alright .

1. when you need quick support you can also ask on our chat channel at https://gitter.im/aboutcode-org/discuss

2. Do you mind to try the standard installation on Windows and not WSL? And report here by pasting the detailed traces of any error you may face?

3. Are you running Windows 64 bits?

**Comment by pombredanne** [comment]
@jonCeg21 re: https://github.com/nexB/scancode-toolkit/issues/2448#issuecomment-809499322

> After a week of struggling and not reading the scancode documentation, 

I am sorry for your struggle,m and you should bring it to our chatroom so that someone can help you.

> I came to the conclusion that this tool only works on an ubuntu 18.04 OS because that one has native python3.6.9. 
> Using ubuntu20.04 with the python 3.9.8 does not seem to work. 

It should work and is tested, but that would be require using a pip installation rather than an archive download 
See the tests definitions here: https://github.com/nexB/scancode-toolkit/blob/96c73a2761eee3c1d8ba57c47efaa475f7459409/azure-pipelines.yml#L125 

> Using WSL for Windows does not seem to work or there is little documentation on how to set it up. 

WSL has not yet been tested and is unlikely to work and we need help to setup some tests there to ensure that it is working. 
Help would be much welcome if you have a WSL setup.
Note though that we would likely never be able to support WSL1 as this looks too different from POSIX and Linux.
 
For now, a Windows install should work with:

1. a release tarball assuming you have Windows 10 64 bits and a Python 3.6.x 64 bits installed. It should work with a simple extract and run, as documented.
2. pip installation assuming you have Windows 10 64 bits and a Python 3.6, 3.7, 3.7 or 3.9 (and typically installed in an isolated  virtual env)

**Comment by jonCeg21** [comment]
@pombredanne thank you for your extensive response. So in conclusion:
- It can work on ubuntu20.04 when using a pip installation rather than an archive download. 
=> Can I use this documentation https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#pip-install ?
=> So it does work on python versions higher than python3.6 ?

- So it does indeed work on a Windows 10 you say? Well this is my setup:

=> When I execute the command >where.exe python

=> I get 
C:\Users\jonasda\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\jonasda\AppData\Local\Programs\Python\Python36-32\python.exe
                  "empty line"   
                                                         
=> My environment variable path looks like this
C:\Users\jonasda\AppData\Local\Programs\Python\Python36-32\Scripts\
%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
C:\Program Files\apache-maven-3.6.3\bin
C:\Users\jonasda\AppData\Roaming\Python\Python36\Scripts
C:\Users\jonasda\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu16.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\jonasd\scancode-toolkit-21.2.25
C:\Users\jonasda\AppData\Local\Programs\Python\Python36-32

=> When try to run >scancode -h I get this error:

* Configuring ScanCode for first use...
* WARNING: Native Windows will be deprecated in the future in favor of Windows Subsystem for Linux
* WARNING: Please visit https://github.com/nexB/scancode-toolkit/issues/2366 for details and to provide feedback
Unsupported Python, OS, platform or architecture: 32 bits: use a 64 bits OS and Python instead.
See https://github.com/nexB/scancode-toolkit/ for supported OS/platforms. Enter a ticket https://github.com/nexB/scancode-toolkit/issues asking for support of your OS/platform combo.

Am I doing something wrong then if you say it can be done on Windows 10?

**Comment by pombredanne** [comment]
> C:\Users\jonasda\AppData\Local\Programs\Python\Python36-32\python.exe
"empty line"

You need a 64 bits Python and this is 32 bits.

**Comment by pombredanne** [comment]
@jonCeg21 I am closing for now for lack of activity. Feel free to reopen
