### ISSUE TITLE
Creating  docs automatically for scancode data

### ISSUE THREAD

**Issue by robinsingh-ai** [nexB/scancode-toolkit#2455]
### Description
I have seen [this](https://github.com/nexB/aboutcode/wiki/Project-Ideas-Create-docs-automatically-from-scancode-data) new project idea where we have to create docs automatically from scancode data, these can be done using automodule method from autodoc extension, 
> but as @AyanSinhaMahapatra you mentioned on gitter that "we want something that parses more specifically, since the data we want to show, is only a small part of the classes, i.e. there will be (a lot) of functions and methods also documented which we don't want. We likely have to craft something similar but more specific to our requirements, which only takes out certain docstrings/class attributes having the documentation for that data field, and creates the doc from there." 

### Solution
autodoc is an extension of the sphinx which is used to Include documentation from docstrings that is available inside the source code, so there are many in-built methods that are available in the autodoc extension like automodule, autoclass and autoexception etc.
- .. automodule:: <module name> : which can be used to import any source file having all the classes and functions
-  .. autoclass:: <class name> : which can be used to import any class inside the source program.
- The key to using these features is the :members: attribute. If:
  - If we don’t include it at all, only the docstring for the object is brought in:
      - For example if we import api.py from src/scancode then sphinx will only parses this dockstring
![Screenshot from 2021-03-25 15-18-53](https://user-images.githubusercontent.com/55009875/112454463-b828a800-8d7e-11eb-9656-f4a116c3a915.png)
  - if we just use :members: with no arguments, then all public functions, classes, and methods are brought it that have a docstring. 
  - If we explictly list the members like :members: <function_1>, <function_2>, <function_3> those explict members are brought.

For more refer [this](https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example)
 
So like this way, we can only parse that data that we want to show in docs

@majurg  and @AyanSinhaMahapatra  need your suggestion on this solution
looking forward to your reply

### Select Category

-  [ ] Inconsistency
-  [ ] New Section Request
-  [X] General Improvement
-  [ ] Typo/Mistakes
-  [ ] Other

**Comment by AyanSinhaMahapatra** [comment]
A duplicate issue, closing this. See #2008 and #2425
