### ISSUE TITLE
Eclipse sua should be considered "CopyLeft Limited"

### ISSUE THREAD

**Issue by tardyp** [nexB/scancode-toolkit#2477]
One of my scans detected an eclipse-sua notice.

It is categorised as CopyLeft, while I think it should be "CopyLeft Limited", as this is more or less only referering to EPL which is already Limited.

https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2017.yml

There are a bunch of them.

**Comment by pombredanne** [comment]
@tardyp this makes sense. @DennisClark what's your take?

**Comment by pombredanne** [comment]
@tardyp I would guess the same would apply not only to https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2017.yml but also to these:
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2001.yml
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2002.yml
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2003.yml
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2004.yml
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2005.yml
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2010.yml
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2011.yml
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/eclipse-sua-2014.yml

**Comment by tardyp** [comment]
indeed, basically eclipse-sua-*.yml are candidates for "CopyLeft Limited" Category
