### ISSUE TITLE
Add detection for Apple MFi License

### ISSUE THREAD

**Issue by vbisserie** [nexB/scancode-toolkit#2497]
https://www.lawinsider.com/dictionary/mfi-license

**Comment by vbisserie** [comment]
Sorry, the 'Apple Example Code License' is detected.

**Comment by pombredanne** [comment]
> Sorry, the 'Apple Example Code License' is detected.

@vbisserie that's OK, I am glad it works and even more glad that you care for it! :+1: 

Any incorrect detection is a bug!
