### ISSUE TITLE
Support detecting the "License Agreement for Solace Software"

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#2498]
## Short Description

Please add support for detecting the [License Agreement for Solace Software](https://solace.com/license-software) as referred to e.g. by https://repo1.maven.org/maven2/com/solacesystems/solsuite/10.8.1/solsuite-10.8.1.pom

## Possible Labels

"license scan"

## Select Category

-  [ ] Enhancement
-  [x] Add License/Copyright
-  [ ] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [ ] Expand Support
-  [ ] Other

**Comment by pombredanne** [comment]
The actual link is https://solace.com/wp-content/uploads/2019/03/Solace-Software-EULA.pdf and the version is `Version: APRIL 1, 2020` so I guess a key could be `solace-eula-2020` ?
@DennisClark what do you think?

**Comment by mnonnenmacher** [comment]
@pombredanne I belive this can be closed, you have added the license in 6e12bd13dcdf31ae2695882767dc7329676de824.
