### ISSUE TITLE
Use dparse2 for Python 2 and dparse for Python 3

### ISSUE THREAD

**Issue by cole-h** [nexB/scancode-toolkit#2501]
I'm in the process of packaging scancode-toolkit for Nixpkgs (https://github.com/NixOS/nixpkgs/pull/120009) and ran into an issue where dparse2 is used for Python 2 support, but our version of pdfminer doesn't support Python 2 (and so scancode-toolkit, which depends on both, wouldn't build on Python 2). I opted to disable the package on Python 2, which led me to need to patch the `dparse2` dependency to use the normal `dparse` package.

It would be very nice to have `dparse2` only necessary when using Python 2, and have the ability to use `dparse` on Python 3 and up.

**Comment by pombredanne** [comment]
@cole-h Hi! that's awesome! actually we dropped support for Python2 entirely and the only reason for the temporary dparsee release at https://github.com/nexB/dparse/releases/tag/0.5.0.1 was a Python backport.
We could normally fully switch to the regular dparse at this stage

**Comment by pombredanne** [comment]
@cole-h which version are you porting to nix?

**Comment by cole-h** [comment]
I've packaged the latest version, 21.3.31.

**Comment by pombredanne** [comment]
@cole-h ack ... anything we can do to help, please tell. You can also consider a smaller footprint with the scancode-toolkit-mini package from Pypi (created with the ./setup-mini.cfg settings) as it has fewer deps for a start

**Comment by cole-h** [comment]
Thanks for your support!

I ran into 2 other dependency issues that seem trivial (to my layman's eyes) to resolve:

* the version bound on `ftfy` is unnecessary; I was able to build and run `--help` just fine with that bound removed altogether
* the same can be said of the version bound on bitarray; I was able to build with 1.7.1 and run `--help` fine as well

**Comment by pombredanne** [comment]
@cole-h all the upper versions bound have been removed in the develop branch. I still want to keep some lower bounds as the minimal version that we test against and that is pinned in the app archives for sanity.

Also dparse2 is now used instead of dparse which I will not further anymore. And overall the set of dependencies has changed quite a bit too

I am closing this now... but feel free to reopen!
