### ISSUE TITLE
False positive license detection in jaxen-1.1.3.jar-extract/org/jaxen/dom/NamespaceNode.class

### ISSUE THREAD

**Issue by Thomshan** [nexB/scancode-toolkit#2515]
**Description**

Scancode Toolkit reports the presence of a proprietary license in line number 134 of  
jaxen-1.1.3.jar-extract/org/jaxen/dom/NamespaceNode.class. 
This fix is to add a new RULE with this .yml `is_false_positive: yes` some `notes: not a license reference, seen in Jaxen` and this text in .RULE : `node may not be modified`
The identifier is "proprietary-license_276.RULE" whose relevance is currently 100 and should be 70 instead.

**How To Reproduce**

Run the following commands:

`scancode --license --license-text --license-text-diagnostics --json-pp jaxen.json jaxen-1.1.3.jar-extract/org/jaxen/dom/NamespaceNode.class`

`strings jaxen-1.1.3.jar-extract/org/jaxen/dom/NamespaceNode.class | grep -A2 -B2 "may not be modified"`

**System configuration**

Version of Scancode used: v21.3.31

**Comment by pombredanne** [comment]
This is fixed in the latest release. Thank you ++ for the report!
