### ISSUE TITLE
delete old temporary files before running new tests

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#252]
Scancode creates a lot of files in `tmp` folder when running test cases. These files stay in that directory unless they are deleted manually. I think it's a good idea to delete the files from previous tests before running new ones, in this way only the test files for the latest tests are stored and the older ones are deleted.

**Comment by pombredanne** [comment]
This is really only a test environment issue. Not worth fixing IMHO but thanks for the report.
