### ISSUE TITLE
Recognize Python packages (wheels, eggs, various dist as archives or installed)

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#253]
scancode must be able to detect Python packages used by in a project by parsing files like `setup.py`, `.whl` files, `.eggs` files, `requirements.txt` or `pip_requirements.txt`.

**Comment by sschuberth** [comment]
Just for the record, while PR #421 is thankfully merged, support for recognizing Python packages based on `*requirements*.txt` files is still missing.

**Comment by pombredanne** [comment]
@sschuberth indeed. There are several limitation in the current code.

1. support for requirements is one: https://github.com/landscapeio/requirements-detector may be what the doctor ordered, may be together with `pip` proper used as a library

2. support for parsing `setup.py` is somewhat weak too. These could be some pointers:
* https://github.com/msabramo/flake8-exact-pin/blob/master/flake8_exact_pin.py
* https://gitlab.com/abre/setup-freeze/blob/master/setup_freeze.py
* https://github.com/msabramo/setuppycheck/blob/master/setuppycheck.py
* https://github.com/inveniosoftware/requirements-builder/blob/master/requirements_builder/requirements_builder.py
* https://github.com/specialunderwear/setupreader/blob/master/setupreader.py
* https://github.com/pombredanne/setupreader
* https://github.com/ashwoods/python-packr/blob/master/setup_parser.py
* https://github.com/openembedded/openembedded-core/blob/f3e753372baac43d0921186340cf260df056de20/scripts/lib/recipetool/create_buildsys_python.py#L181
* https://github.com/yosi-dediashvili/SubiT/blob/ee154c43c3c0170e82750d428688b4d441f95134/build/setup.py
* https://github.com/mk-fg/fgtk/blob/master/dev/distribute_regen
* https://github.com/noisy/parse_setup.py
* http://stackoverflow.com/questions/24236266/how-to-extract-dependencies-information-from-a-setup-py
* http://stackoverflow.com/questions/27790297/parse-setup-py-without-setuptools
* https://github.com/andymckay/baked/blob/master/baked.py
* https://github.com/mgood/quipu/blob/master/quipu.py
* https://github.com/newville/asteval

3. Parsing actual packages as installed could likely benefit from code/functions existing in `distutils`, `pip` and `setuptools`

**Comment by pombredanne** [comment]
The basic is there. Addintional updates will be for post 2.0

**Comment by pombredanne** [comment]
Our hand rolled code for Python packages needs beefing. We should use instead:

1. https://github.com/pombredanne/pkginfo enhanced for pip-installed wheels
2. The requirements parser from pyup by @jayfk https://github.com/pyupio/pyup/blob/master/pyup/requirements.py

And possibly yet more candidates:

- Setup.py dynamic execution in docker:
  - https://github.com/noisy/parse_setup.py (but this needs docker)

- Setup.py through AST:
  - https://github.com/amitsaha/parse_setup_py by @amitsaha though I need to ask about the license

Setup.py through mocking:

- https://github.com/inveniosoftware/requirements-builder/blob/master/requirements_builder/requirements_builder.py by the buddies from invenio BSD-licensed

- https://github.com/specialunderwear/setupreader by @specialunderwear GPL-licensed

Using pip to parse requirements and some other pointers :

- https://github.com/narfman0/parse-requirements-not-suckily
- https://github.com/collective/collective.recipe.pip 
- https://github.com/witsch/buildout.packagename/blob/master/buildout/packagename/__init__.py
- https://github.com/msabramo/setuppycheck/blob/master/setuppycheck.py
- https://gitlab.com/abre/setup-freeze/blob/master/setup_freeze.py

**Comment by pombredanne** [comment]
See also this https://bugs.launchpad.net/pkginfo/+bug/1700200 submitted to @tseaver  and this simple patch to support properly dist-info installed wheels https://github.com/pombredanne/pkginfo/commits/master

**Comment by amitsaha** [comment]
@pombredanne I have now added a LICENSE to https://github.com/amitsaha/parse_setup_py/ . Please feel free to see if you find it useful.

**Comment by pombredanne** [comment]
@amitsaha Thanks ++!

**Comment by jayfk** [comment]
Is there any interest in splitting the requirements parsing into a library?

**Comment by pombredanne** [comment]
@jayfk that would be awesome... and I am game to help!

In fact, I think that with the triad of your own requirements parsing code that's you robustly tested at scale, the `pkginfo` of @tseaver for detecting and collecting as-installed Python packages and a safe `setup.py` handler (better based on an AST parsing rather than a mock execution) we could have a semi universal solution to answer this question: 

> is this a python package and what are its dependencies? 

That would only be semi universal for now as it would also need eventually to handle a few extra formats such as `pbr` 's setup.cfg metadata, the improved `setup.cfg` metadata in the latest `setuptools` (both being simple .ini files) and  @kennethreitz new `Pipfile` and `Pipfile.lock` format.

**Comment by jayfk** [comment]
Awesome. I'll try to put something together.

**Comment by jayfk** [comment]
All right, I've played around with this a little. I'll probably upload some code later today.

I thought about a clean `parse` entrypoint that takes some content and returns a `DependencyFile` class.

### requirements.txt
```python
from dparse import parse, filetypes

content = """
-e common/lib/calc
South==1.0.1 --hash==abcdefghijklmno
pycrypto>=2.6
git+https://github.com/pmitros/pyfs.git@96e1922348bfe6d99201b9512a9ed946c87b7e0b
distribute>=0.6.28, <0.7
# bogus comment
-e .
pdfminer==20140328
-r production/requirements.txt
--requirement test.txt
"""

df = parse(content, filetype=filetypes.requirements_txt)

print(df.json())
```

```json
{
  "file_type": "requirements.txt",
  "content": "\n-e common/lib/calc\nSouth==1.0.1 --hash==abcdefghijklmno\npycrypto>=2.6\ngit+https://github.com/pmitros/pyfs.git@96e1922348bfe6d99201b9512a9ed946c87b7e0b\ndistribute>=0.6.28, <0.7\n# bogus comment\n-e .\npdfminer==20140328\n-r production/requirements.txt\n--requirement test.txt\n",
  "path": null,
  "sha": null,
  "dependencies": [
    {
      "name": "pycrypto",
      "specs": [
        [
          ">=",
          "2.6"
        ]
      ],
      "line": "pycrypto>=2.6",
      "line_numbers": null,
      "index_server": null,
      "hashes": [],
      "dependency_type": "requirements.txt"
    },
    {
      "name": "distribute",
      "specs": [
        [
          ">=",
          "0.6.28"
        ],
        [
          "<",
          "0.7"
        ]
      ],
      "line": "distribute>=0.6.28, <0.7",
      "line_numbers": null,
      "index_server": null,
      "hashes": [],
      "dependency_type": "requirements.txt"
    },
    {
      "name": "pdfminer",
      "specs": [
        [
          "==",
          "20140328"
        ]
      ],
      "line": "pdfminer==20140328",
      "line_numbers": null,
      "index_server": null,
      "hashes": [],
      "dependency_type": "requirements.txt"
    }
  ]
}
```

### conda.yml
```python
content = """
name: my_env
dependencies:
  - gevent=1.2.1
  - pip:
    - beautifulsoup4==1.2.3
    - requests>=2.3
"""
df = parse(content, path="conda.yml")

print(df.json())
```

```json
{
  "file_type": "conda.yml",
  "content": "\nname: my_env\ndependencies:\n  - gevent=1.2.1\n  - pip:\n    - beautifulsoup4==1.2.3\n    - requests>=2.3\n",
  "path": "conda.yml",
  "sha": null,
  "dependencies": [
    {
      "name": "beautifulsoup4",
      "specs": [
        [
          "==",
          "1.2.3"
        ]
      ],
      "line": "beautifulsoup4==1.2.3",
      "line_numbers": null,
      "index_server": null,
      "hashes": [],
      "dependency_type": "requirements.txt"
    },
    {
      "name": "requests",
      "specs": [
        [
          ">=",
          "2.3"
        ]
      ],
      "line": "requests>=2.3",
      "line_numbers": null,
      "index_server": null,
      "hashes": [],
      "dependency_type": "requirements.txt"
    }
  ]
}
```
### tox.ini
```python
content = """
[testenv:bandit]
commands =
    bandit --ini setup.cfg -ii -l --recursive project_directory
deps =
    bandit==1.4.0
[testenv:manifest]
commands =
    check-manifest --verbose
"""
df = parse(content, path="tox.ini")

print(df.json())
```

```json
{
  "file_type": "tox.ini",
  "content": "\n[testenv:bandit]\ncommands =\n    bandit --ini setup.cfg -ii -l --recursive project_directory\ndeps =\n    bandit==1.4.0\n[testenv:manifest]\ncommands =\n    check-manifest --verbose\n",
  "path": "tox.ini",
  "sha": null,
  "dependencies": [
    {
      "name": "bandit",
      "specs": [
        [
          "==",
          "1.4.0"
        ]
      ],
      "line": "bandit==1.4.0",
      "line_numbers": null,
      "index_server": null,
      "hashes": [],
      "dependency_type": "requirements.txt"
    }
  ]
}
```

**Comment by pombredanne** [comment]
@jayfk thanks++ this looks great! I could then easily plugin this in ScanCode by invoking the right "filetypes" parser on a given file that's being scanned. On the conda side I might contribute a few extras as I am interested in other metadata available beside the deps... but that can come later.

**Comment by jayfk** [comment]
Yup. I have a somewhat useable prototype here: https://github.com/pyupio/dparse
It's not quite there yet, I'll keep you posted once it's useable.

One major pain point right now is that it requires an outdated setuptools release. 😡

**Comment by pombredanne** [comment]
@jayfk you wrote:

> One major pain point right now is that it requires an outdated setuptools release.

what? you are not running setuptools `198.3` ? ;)

**Comment by pombredanne** [comment]
@jayfk you rock!

**Comment by jayfk** [comment]
Okay, this is now useable for `requirements.txt`, `tox.ini` and `conda.yml` (PyPi dependencies only). 

I'm planning to add read-only `setup.py` support soon.

**Comment by pombredanne** [comment]
@jayfk Thanks++
So I guess my approach will be to:
1. for conda and tox files invoke with the proper filetypes. Check for exceptions and is_valid
2. for req-like looking text files invoke with the proper filetypes. Check for exceptions and is_valid too. Since there are possibly more filename variety there, I will fish with a wide net and balk if this does not parse and only return errors when this is really a requirements*.txt files. I guess something similar to this: https://github.com/pyupio/pyup/blob/e6d2984efb42be8d195ac1f2c7e6a27505596fdc/pyup/bot.py#L486

**Comment by linexb** [comment]
This can be another tool: https://pypi.org/project/wheel-inspect/

**Comment by pombredanne** [comment]
This is all done now and merged in develop.
