### ISSUE TITLE
Undocumented Error: Error: Invalid value for '--from-json': Value must be an iterable. 

### ISSUE THREAD

**Issue by m0100434** [nexB/scancode-toolkit#2535]
### Description

I installed the tool via pip install

ran the following command in my terminal :   scancode -l -p -c --html adore.html ADORE_DECLARATIONS

ADORE_DECLARATIONS is my folder that contains subfolders with python scripts. 

Received Error: 

C:\Python>scancode -l -p -c --html adore.html ADORE_DECLARATIONS
c:\python\python394\lib\site-packages\cluecode\copyrights.py:3122: FutureWarning: Possible set difference at position 3
  remove_tags = re.compile(
c:\python\python394\lib\site-packages\nltk\tag\sequential.py:540: FutureWarning: Possible nested set at position 7
  self._regexps = [(re.compile(regexp), tag,) for regexp, tag in regexps]
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try the 'scancode --help' option for help on options and arguments.

Error: Invalid value for '--from-json': Value must be an iterable.

### How To Reproduce

> Tell us how to reproduce the issue. 

scancode -l -p -c ADORE_DECLARATIONS --html adore.html

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Windows
* What version of scancode-toolkit was used to generate the scan file?  the one available through pip on May 27th 2021
* What installation method was used to install/run scancode? pip

**Comment by pombredanne** [comment]
@m0100434 Thanks for the report. This is likely related to #2534 , #2521 and #2529

**Comment by anthonyharrison** [comment]
Same issue for me using Linux (kali). Can't run any scans or any of the examples.

Revert click to version 7.1.2 and it works

pip install click==7.1.2

**Comment by pombredanne** [comment]
This is now fixed in the latest release v21.6.7 and up.
Thank you all! Feedback welcomed.
