### ISSUE TITLE
link in summary is wrong error 404

### ISSUE THREAD

**Issue by ididitmyway** [nexB/scancode-toolkit#2536]
The link to ("ScanCode.io web app" ) -> ("https://github.com/nexB/scancode.io")
in the md file from ("https://github.com/nexB/scancode-toolkit")
points to ("https://github.com/nexB/scancodeio")

error 404

**Comment by pombredanne** [comment]
Thanks!

**Comment by pombredanne** [comment]
@ididitmyway Thank you!
This has been fixed by @sschuberth  in https://github.com/nexB/scancode-toolkit/commit/9daa269f690e7c1aa2e81a12aa74e6704d63c5ff and released
