### ISSUE TITLE
Add new is_unknown flag in data model definition

### ISSUE THREAD

**Issue by akugarg** [nexB/scancode-toolkit#2549]
Add a new flag for licenses that are tagged as "unknown" i.e. not matched with a known named license. 
This will help in segregating the special license keys with the known ones.
## Possible Labels

- new feature

## Select Category

-  [x] Enhancement
-  [ ] Add License/Copyright
-  [x] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [ ] Expand Support
-  [ ] Other

**Comment by AyanSinhaMahapatra** [comment]
See #1675 for more details.
