### ISSUE TITLE
Docker fails to run on scancode-toolkit 21.6.7 

### ISSUE THREAD

**Issue by balakrishna-mukundaraj** [nexB/scancode-toolkit#2554]
ERROR: Cannot install scancode-toolkit==21.6.7 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

The conflict is caused by:
scancode-toolkit 21.6.7 depends on pygments
The user requested (constraint) pygments

To fix this you could try to:

    loosen the range of package versions you've specified
    remove package versions to allow pip attempt to solve the dependency conflict

The command '/bin/sh -c ./scancode --help' returned a non-zero code: 1

Steps to reproduce and error:
[error.txt](https://github.com/nexB/scancode-toolkit/files/6655227/error.txt)

**Comment by pombredanne** [comment]
Thanks for the report. This should be fixed in the upcoming release.

**Comment by pombredanne** [comment]
This has been fixed in https://github.com/nexB/scancode-toolkit/pull/3053 and will be in release v31
Thank you for your patience!
