### ISSUE TITLE
Issue building a docker container from Version 21.6.7

### ISSUE THREAD

**Issue by ididitmyway** [nexB/scancode-toolkit#2560]
### Description

Building 21.6.7 caused the following error. ( building 21.3.31 in the same way worked fine )

Processing ./thirdparty/pluggy-0.13.1.tar.gz
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  WARNING: Requested pluggy<1.0,>=0.12.0 from file:///scancode-toolkit/thirdparty/pluggy-0.13.1.tar.gz (from scancode-toolkit==21.6.7), but installing version 0.0.0
WARNING: Discarding file:///scancode-toolkit/thirdparty/pluggy-0.13.1.tar.gz. Requested pluggy<1.0,>=0.12.0 from file:///scancode-toolkit/thirdparty/pluggy-0.13.1.tar.gz (from scancode-toolkit==21.6.7) has inconsistent version: filename has '0.13.1', but metadata has '0.0.0'
ERROR: Cannot install scancode-toolkit==21.6.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    scancode-toolkit 21.6.7 depends on pluggy<1.0 and >=0.12.0
    The user requested (constraint) pluggy==0.13.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The command '/bin/sh -c ./scancode --reindex-licenses' returned a non-zero code: 1

### How To Reproduce

> download scancode-toolkit-21.6.7_sources.tar.xz in ubuntu server 20.04 LTS
> tar xf the tar.xz
> cd into it
> build it 
> result error abouve

> wget https://github.com/nexB/scancode-toolkit/releases/download/v21.6.7/scancode-toolkit-21.6.7_sources.tar.xz
> tar xf scancode-toolkit-21.6.7_sources.tar.xz
> cd scancode-toolkit-21.3.31/
> sudo docker build -t scancode-toolkit:21.6.7 .

### System configuration

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by yellowsta726** [comment]
I have successfully built on Debian Buster, but have the same issue on MacOS BigSur.

**Comment by tapdiego-amzn** [comment]
Reporting the same issue on macOS Catalina.

**Comment by pombredanne** [comment]
This is solved in https://github.com/nexB/scancode-toolkit/pull/3053 and will be released with v31.
