### ISSUE TITLE
Report of license rules

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#2566]
This a new feature request for a report of License Rules from ./scancode-toolkit/src/licensedcode/data/rules/ . When you have multiple rules for a license, it is difficult to compare them in the GH filesystem without a log copy/paste to some other document. 

The request is for some way to extract the license rules data for a license key into a document or spreadsheet. This could be via a command by license key or alternatively a way to just download all License Rules at a point in time so that you could search it like a small database. 

The objective is to improve license detection by looking at all current License Rules together.

**Comment by mjherzog** [comment]
I am raising the urgency of this request - specifically to support "reform" of the definitions and rules for commercial-license and proprietary-license.

**Comment by pombredanne** [comment]
> alternatively a way to just download all License Rules at a point in time so that you could search it like a small database.

This can be done by downloading the whole scancode but that may not be what you want.

> The request is for some way to extract the license rules data for a license key into a document or spreadsheet.

There are two ways to get this:
1. ... and we need this anyway: we could have them in the licensedb  with rules page where we could search, and browse and slice though the rules: we could also download the list of XLS the same way we can do this with the licensedb today (and with columns) ... the fields would be different than the one we have for the licenses... these would be the rules fields.
2. have an option in the SCTK CLI to create such as report 

I am much more in favor of doing 1. in https://github.com/nexB/scancode-licensedb/ as we will then be able to use it to add links to matched rules in all our license matches

**Comment by pombredanne** [comment]
Another thing is that we could also include simple "diffing" of two selected licenses or two selected rules  possibly reusing the code of  @alandtse  in https://github.com/spdx/spdx-license-diff (if there is a license change on the horizon and if this can be used server side)or something similar

**Comment by mjherzog** [comment]
Solution 1 for the LicenseDB makes good sense to support a variety of use cases. The primary requirement is some useful human-friendly display of the rules for a license. We should not add this to SCTK CLI because you may want to do this outside of a Scan.

**Comment by AyanSinhaMahapatra** [comment]
See [this comment](https://github.com/nexB/scancode-toolkit/pull/2685#issuecomment-912717107).

**Comment by AyanSinhaMahapatra** [comment]
@mjherzog This can be closed as the LicenseDB update is tracked seperately here : https://github.com/nexB/scancode-licensedb/issues/3

**Comment by AyanSinhaMahapatra** [comment]
Closing as this is completed and LicenseDB issue is tracked seperately here : https://github.com/nexB/scancode-licensedb/issues/3
