### ISSUE TITLE
Unknown Licenses should be reported separately

### ISSUE THREAD

**Issue by akugarg** [nexB/scancode-toolkit#2574]
We should have a separate section for reporting unknown licenses and not mixed with all license detections for clarity.

## 

- new feature

## Select Category

-  [x] Enhancement
-  [ ] Add License/Copyright
-  [x] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [ ] Expand Support
-  [ ] Other

## **Possible Solution/Implementation Details**

#1675 for more details

**Comment by akugarg** [comment]
Currently we have something like this :
Licenses:[
{}
{}
]

We could have something like any of the two options below:
Having complete different sections for two:
Known Licenses:[
{} ... {} 
] 
Unknown Licenses:[
{}...{}
]  
                                                             OR
having subsections within licenses array itself
Licenses:[
Known:[ {} {} ]

Unknown:[ {} {} ]
]

**Comment by AyanSinhaMahapatra** [comment]
Yes, we could keep the `licenses` as it is, and just name the new list `unknown_licenses` also. 
@pombredanne does this sound okay?
