### ISSUE TITLE
is Documentation pointing to latest (development) version OR stable version

### ISSUE THREAD

**Issue by zivian** [nexB/scancode-toolkit#2575]
### Description
is Documentation pointing to latest (development) version OR stable version ?

> A brief description of the Documentation Improvement or New Section request.

### Link to Documentation Page
https://scancode-toolkit.readthedocs.io/en/latest/

> Where the confusion/inconsistency/incomplete documentation is.

as a first time or regular user, i will be interested to know or learn or fix few issues by looking into docs. 

### Select Category

-  [ ] Inconsistency
-  [ ] New Section Request
-  [ ] General Improvement
-  [ ] Typo/Mistakes
-  [ ] Other

**Comment by pombredanne** [comment]
@zivian sorry for missing this... @AyanSinhaMahapatra  this has been fixed now, has it?

The default was  latest (development) version (and this was a bug) and is now  stable version

**Comment by AyanSinhaMahapatra** [comment]
Yes. [scancode-toolkit.readthedocs.io/](https://scancode-toolkit.readthedocs.io/) now goes to the stable version, and it goes to latest only if https://scancode-toolkit.readthedocs.io/en/latest/ is asked for explicitly.
