### ISSUE TITLE
Progress bar does not display correctrly in the CLI: SCTK-21.6.7 count does not increment

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#2583]
Running a -clip scan on Ubuntu 18.04 on a remote VM and on Ubuntu 18.04 on the latest WSL2, using scancode-toolkit-21.6.7, I've noticed that the file count no longer increments/increases but rather remains at 0 for the duration, e.g., during the scan:

```
[--------------------] 0 Scanned: [current filename being scanned]

```

and when the scan has finished:

```
[####################] 0
Scanning done.

```

**Comment by pombredanne** [comment]
`update_min_steps` may be the culprit based on https://github.com/pallets/click/issues/676 and https://github.com/pallets/click/pull/1698

Or any of these: https://github.com/pallets/click/issues?q=is%3Aissue+progressbar+is%3Aclosed

And based on https://github.com/pallets/click/issues/1777
>  @davidism commented on Feb 15
> Yes, please use tqdm, I don't plan to add more to our implementation.

And https://github.com/pallets/click/issues/1924
>  davidism commented on May 21 •
> We're no longer working on the progress bar implementation. Use a dedicated library like tqdm to render progress bars in cases where Click's does not suffice.

then may be we should drop using Click for this?

**Comment by pombredanne** [comment]
This is now fixed and merged in develop!
Thank you ++ for the report
