### ISSUE TITLE
Problems checking out the develop branch on Windows (Filename too long)

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#259]
I'm having trouble checking out the `develop` branch on Windows:

```
error: unable to create file tests/packagedcode/data/maven/longtest/expected/com/google/collect/com.springsource.com.google.common.collect/0.5.0.alpha/com.springsource.com.google.common.collect-0.5.0.alpha.pom.bz2 (Filename too long)
```

While I agree this Windows-specific limitation is annoying, is there some easy fix to shorten the path? The part `com/google/collect/com.springsource.com.google.common.collect` looks somewhat redundant.

**Comment by pombredanne** [comment]
@sschuberth Thanks. This is an easy fix. I am surprised this was not caught by the test runs on appveyor 
https://ci.appveyor.com/project/nexB/scancode-toolkit

**Comment by sschuberth** [comment]
That's probably because AppVeyor clones to a directory that is closer to the root. But as soon as you have some directories in between you'll exceed the path limit.

**Comment by pombredanne** [comment]
@sschuberth This should be fixed now. Could you give it a shot?

**Comment by sschuberth** [comment]
Works for me now, thanks!

**Comment by sschuberth** [comment]
I'm again having a problem with this, the offending paths being

    tests/packagedcode/data/m2/e/com/google/collect/com.springsource.com.google.common.collect/0.5.0.alpha/com.springsource.com.google.common.collect-0.5.0.alpha.pom.bz2
    tests/packagedcode/data/m2/r/com/google/collect/com.springsource.com.google.common.collect/0.5.0.alpha/com.springsource.com.google.common.collect-0.5.0.alpha.pom.bz2

Do you see a change to shorten these paths again, too?

**Comment by pombredanne** [comment]
@sschuberth sorry I had missed your comment here. The difficult thing is that I was trying to reproduce a faithful maven directory tree. But I guess this could put in a tarball to avoid problems. Or just mock shorter paths in this only case.

**Comment by sschuberth** [comment]
It's probably not worth to address the issue if I'm the only one having these problems (due to the long path name of the parent folder I use for my GitHub projects). Also AppVeyor CI passes. I've anyway worked around this by now by using a shortcut from my usual path to a special short path for ScanCode. So I'll just close this again, but it's still good to have this conversation for the record.

**Comment by pombredanne** [comment]
well I committed a quick fix anyway before seeing your comment ;)
