### ISSUE TITLE
Unable to finish extraction

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#26]
operating system: windows 7, 64-bit
i downloaded the RPM `ant-1.9.2-9.el7.noarch.rpm` from the url `http://mirror.centos.org/centos/7.1.1503/os/x86_64/Packages/ant-1.9.2-9.el7.noarch.rpm` and saved it in the directory called `distro`.
when I gave the command `scancode --extract  C:\doc\linux_distro\data\distro`, scancode was not able to finish the extraction and I waited for more than half hour. 
Interestingly I was able to see the folder `ant-1.9.2-9.el7.noarch.rpm-extract` but I `did not see` any message like `extraction finished` in the terminal.

**Comment by pombredanne** [comment]
Thanks for the bug report. The details will help a lot to fix this bug.

**Comment by rakeshbalusa** [comment]
facing the above issue with the following `RPMs` also

`apache-commons-codec-1.8-7.el7.noarch.rpm` url : `http://mirror.centos.org/centos/7.1.1503/os/x86_64/Packages/apache-commons-codec-1.8-7.el7.noarch.rpm` 

`apache-commons-collections-3.2.1-21.el7.noarch.rpm` url : `http://mirror.centos.org/centos/7.1.1503/os/x86_64/Packages/apache-commons-collections-3.2.1-21.el7.noarch.rpm`

**Comment by pombredanne** [comment]
Implemented in #29
