### ISSUE TITLE
License is detected by "bootloader-exception" for "BSD-3-Clause" file.

### ISSUE THREAD

**Issue by soimkim** [nexB/scancode-toolkit#2605]
### Description

The phrase "Distributed under the terms of the Modified BSD License.\n|\n| The full license is in the file COPYING.txt, distributed with this software." is matched with 'gpl-2.0-plus AND bootloader-exception'.

-> There is no GPL-related phrase, and it says Modified BSD License, so it should be extracted as BSD-3-Clause (https://opensource.org/licenses/BSD-3-Clause).

### How To Reproduce

1. Download the source from https://github.com/nucleic/kiwi/tree/1.1.0
2. Run ScanCode
3. ScanCode result : 
- https://github.com/nucleic/kiwi/blob/1.1.0/kiwi/util.h :

``` /*-----------------------------------------------------------------------------
| Copyright (c) 2013-2017, Nucleic Development Team.
|
| Distributed under the terms of the Modified BSD License.
|
| The full license is in the file COPYING.txt, distributed with this software.
|----------------------------------------------------------------------------*/ 
 ```

``` {
      "path": "kiwi/util.h",
      "type": "file",
      "licenses": [
        {
          "key": "gpl-2.0-plus",
          "score": 60.61,
          "name": "GNU General Public License 2.0 or later",
          "short_name": "GPL 2.0 or later",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html",
          "text_url": "http://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html",
          "reference_url": "https://scancode-licensedb.aboutcode.org/gpl-2.0-plus",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/gpl-2.0-plus.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/gpl-2.0-plus.yml",
          "spdx_license_key": "GPL-2.0-or-later",
          "spdx_url": "https://spdx.org/licenses/GPL-2.0-or-later",
          "start_line": 4,
          "end_line": 6,
          "matched_rule": {
            "identifier": "gpl-2.0-plus_and_bootloader-exception_1.RULE",
            "license_expression": "gpl-2.0-plus AND bootloader-exception",
            "licenses": [
              "gpl-2.0-plus",
              "bootloader-exception"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
...
```                                                    

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Ubuntu 18.04
* What version of scancode-toolkit was used to generate the scan file? scancode-toolkit==21.3.31
* What installation method was used to install/run scancode?  pip

**Comment by pombredanne** [comment]
Thank you for the report!
This is still present in the latest version of scancode release a week or so ago.
I think that this is a poster child issue for the solution proposed in #2637

**Comment by AyanSinhaMahapatra** [comment]
This is fixed in the develop now and https://github.com/nexB/scancode-toolkit/issues/2637 is also closed, attaching scan results:
[2605-kiwi.json.txt](https://github.com/nexB/scancode-toolkit/files/10023351/2605-kiwi.json.txt)
