### ISSUE TITLE
scancode -h returns error in Windows 11

### ISSUE THREAD

**Issue by gunaztar** [nexB/scancode-toolkit#2610]
I am trying to use scancode toolkit in my windows 11 system. I installed python3.6.8 64 bit and downloaded the latest scancode zip file(scancode-toolkit-21.6.7_py36-windows.zip) and unzipped to a folder. When I try to run 
scancode -h

 I am always getting the below error message:

* Configuring ScanCode for first use...
* WARNING: Native Windows may be deprecated in the future in favor of Windows Subsystem for Linux 2
* WARNING: Please visit https://github.com/nexB/scancode-toolkit/issues/2366 for details and to provide feedback
C:\Python\Python36\python.exe: can't open file '3.6': [Errno 2] No such file or directory

I tried installing different version of python and to a different path also. Path variables are configured properly in environment variables. No idea of why this error message?

**Comment by pombredanne** [comment]
@gunaztar Thanks for the report! I did not even knew that Windows 11 was a thing ... so you may be the first user reporting a bug.
Have you tried installing the default path? and all default Python installer options?

or at `C:\Python36\` ?

This is how we find a Python: https://github.com/nexB/scancode-toolkit/blob/develop/configure.bat#L90

**Comment by pombredanne** [comment]
@gunaztar I found the problem using a VM and please bear with me!
Thank you for the report.

**Comment by gunaztar** [comment]
Thanks. What's the solution? Installed python on the default path and given all default Python installer options.

**Comment by pombredanne** [comment]
@gunaztar this should be fixed now with v21.8.4 ... can you give it a try?
Thanks!

**Comment by pombredanne** [comment]
@gunaztar that was a plain bug, FWIW... thank you for reporting this ++

**Comment by pombredanne** [comment]
@gunaztar I am closing this now since this has been fixed. Thank you for the report!

**Comment by AngelSanchez87** [comment]
Hello,

I am trying to prepare scancode in my Windows 11, with the last version of scancode and the last version of python. And I get always this error.
Can someone help me?
![image](https://github.com/nexB/scancode-toolkit/assets/74961562/9192c70f-51a6-49a3-bb1a-006fc081f447)

Best regards.

**Comment by AyanSinhaMahapatra** [comment]
@AngelSanchez87 can you run `python --version` to get the python version? i.e. do you have python installed properly and added to your PATH variable?

**Comment by AngelSanchez87** [comment]
Yes, for sure. My python version is:

![image](https://github.com/nexB/scancode-toolkit/assets/74961562/ebf96f9f-5d12-40d9-851c-bd3a443ed5b3)

Thank you for helping!

**Comment by AngelSanchez87** [comment]
Sorry I forgot to answer: Yes, I have added it to the my PATH variable.

**Comment by AngelSanchez87** [comment]
I have just found the problem. I downloaded scancode for python 3.10, instead of 3.11.

Sorry for my mistake. And thank you for your help.

Kind regards.

**Comment by pombredanne** [comment]
@AngelSanchez87 that's cool! eventually we want in the future to have a single Windows app bundle that comes with Python inside!
