### ISSUE TITLE
InstalledWindowsProgram.populate_installed_files() does not return the right relative paths for installed files

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#2614]
I am running a few Windows Docker images through a scancode.io pipeline. I noticed that I was getting an error that scancode.io cannot find the installed files of a package from a particular Docker layer.
```
   installed file rootfs_path: /Windows/Microsoft.NET/Framework64/v4.0.30319/1033/CvtResUI.dll
   layer rootfs_path: f358be10862ccbc329638b9e10b3d497dd7cd28b0e8c7931b4a545c88d7f7cd6/Windows/Microsoft.NET/Framework64/v4.0.30319/1033/CvtResUI.dll
      installed file is missing: /Windows/Microsoft.NET/Framework64/v4.0.30319/1033/CvtResUI.dll
...
```

In the above example, the proper layer rootfs_path for `CvtResUI.dll` should be `f358be10862ccbc329638b9e10b3d497dd7cd28b0e8c7931b4a545c88d7f7cd6/Files/Windows/Microsoft.NET/Framework64/v4.0.30319/1033/CvtResUI.dll`. In Docker Windows layers, the rootfs starts in the `Files` directory rather than the layer directory itself. `InstalledWindowsProgram.populate_installed_files()` should be modified to assume that the `root_dir` passed in is equivalent to the Docker layer directory itself.

**Comment by JonoYang** [comment]
The issue happens in scancode.io here (https://github.com/nexB/scancode.io/blob/main/scanpipe/pipes/docker.py#L145) where scancode.io attempts to get the CodebaseResources that are the installed files to a particular package. It concatenates the Docker layer id and the installed file path and uses the resulting path as part of the query. This leads to the incorrect codebase path of `f358be10862ccbc329638b9e10b3d497dd7cd28b0e8c7931b4a545c88d7f7cd6/Files/Windows/Microsoft.NET/Framework64/v4.0.30319/1033/CvtResUI.dll`

**Comment by AyanSinhaMahapatra** [comment]
@JonoYang is this fixed in the commits referenced above? can you confirm?
