### ISSUE TITLE
Update contributing docs

### ISSUE THREAD

**Issue by mapelpapel** [nexB/scancode-toolkit#2630]
### Description
When trying to run pytest on Windows, it fails most tests. Somehow, it can't load all modules.

### How To Reproduce
Follow [Contributing Guide](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* clone Scancode
* `.\configure` (PowerShell, embedded in PyCharm) / `configure` (cmd)
* `.\Scripts\activate` (PowerShell) `Scripts\activate` (cmd)
* `pytest [-vvvs -n8]`

### Log Output
Sadly, a part of the output is cut off (at the end of the log). It's always the same error with different modules.
PowerShell output: https://drive.google.com/file/d/1t-UMEk9nW7K-3NtQRkNhs8xSClMH4PAF/view?usp=sharing
cmd output: https://drive.google.com/file/d/1Ic3dT0aUS1L43Elpjt_hCxwabjwbMKPl/view?usp=sharing

### System configuration
* Windows 10 20H2
* Scancode 21.8.4
* Installed from Source (PyCharm Chrome extension / GitBash for Windows)
* PyCharm 2021.2

**Comment by mapelpapel** [comment]
Ok, I found the Problem myself... 
I needed to run `configure --dev`, which I found in the documentation (but not contributing file)

**Comment by AyanSinhaMahapatra** [comment]
Reopening this.

The contributing file should be updated (and maybe we should just include the contributing file in docs, instead of having two seperate contributing docs).
