### ISSUE TITLE
We could incorrectly skip npm licenses if the extracted license text is not a string or mapping  

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2639]
See https://github.com/nexB/scancode-toolkit/blob/41d2d5b4e9284505b39691c3f21b85ab7dc16772/src/packagedcode/npm.py#L109
... We could skip npm licenses if the declared license is not a string or mapping  

We need a third case there, otherwise there is a possibility that we would silently not detect a license (we would still report that as a declared license alright)

**Comment by AyanSinhaMahapatra** [comment]
This is fixed in develop, as we parse all package extracted_license_statements in a similar fashion where they can be anything: string, list, mappings or some composite forms.
