### ISSUE TITLE
Tool kills itself when processing a "big" file

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#264]
The issue is likely due to not enough RAM.

One potential solution is to implement a timeout option so that the tool will skip to process the "problem/big" file and keep working on others instead of waiting to have the RAM issue and kill itself.

**Comment by pombredanne** [comment]
This is now fixed with the new code added for #267 . A default timeout of 120s and max memory of 1GB is enforced now. It can be overridden with  the new `--timeout`  and `--max-memory` command line options.
