### ISSUE TITLE
Do not yield npm dependencies as packages too 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2640]
These should be part of the dependencies list only and not reported both as deps AND as plain packages.
https://github.com/nexB/scancode-toolkit/commit/8759bd8fe2eb949a2f19c2a63ca8e2b45e6ddaa3#diff-e4c48ccec58b79d00305962756a49af0c450b76f51f72995b8d0f723f23f31f4R921 is not correct IMHO

**Comment by AyanSinhaMahapatra** [comment]
This is fixed in develop, with the new package detection in v31, closing.
