### ISSUE TITLE
Version of LGPL not detected in cairo files

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#265]
Using scancode-toolkit-1.6.0.  Scanning the project from https://www.cairographics.org/releases/cairo-1.8.0.tar.gz  resulted in many license detections of "LGPL" in the directory named /src/ even though the files contain notices that refer to LGPL 2.1, for example the notice below from cairo-pdf-surface.c.   it is a bit tricky, of course, because the notice mentions multiple licenses, and sometimes refers to "the LGPL" and sometimes provides the version number; nevertheless, it is clear from reading the notice that lgpl-2.1 is intended. 

/* cairo - a vector graphics library with display and print output
 *
 * Copyright © 2004 Red Hat, Inc
 * Copyright © 2006 Red Hat, Inc
 * Copyright © 2007, 2008 Adrian Johnson
 *
 * This library is free software; you can redistribute it and/or
 * modify it either under the terms of the GNU Lesser General Public
 * License version 2.1 as published by the Free Software Foundation
 * (the "LGPL") or, at your option, under the terms of the Mozilla
 * Public License Version 1.1 (the "MPL"). If you do not alter this
 * notice, a recipient may use your version of this file under either
 * the MPL or the LGPL.
 *
 * You should have received a copy of the LGPL along with this library
 * in the file COPYING-LGPL-2.1; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * You should have received a copy of the MPL along with this library
 * in the file COPYING-MPL-1.1
 *
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY
 * OF ANY KIND, either express or implied. See the LGPL or the MPL for
 * the specific language governing rights and limitations.
 *
 * The Original Code is the cairo graphics library.
 *
 * The Initial Developer of the Original Code is University of Southern
 * California.
 *
 * Contributor(s):
 *	Kristian Høgsberg <krh@redhat.com>
 *	Carl Worth <cworth@cworth.org>
 *	Adrian Johnson <ajohnson@redneon.com>
 */

**Comment by balusarakesh** [comment]
issue fixed in the latest version of scancode
