### ISSUE TITLE
Directory file information missing from scan results

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#266]
I ran a scan over the samples directory in the scancode toolkit. The `samples` directory file information is missing from the infos results.

I expected to see file information like the following for the directory, but the `samples` file information entry and corresponding results were completely missing from the json scan results:

```
    "infos": [
        {
          "type": "directory", 
          "name": "samples", 
          "extension": "", 
          "date": "2015-11-28", 
          "size":, 
          "sha1": "", 
          "md5": "", 
          "files_count": null, 
          "mime_type": "", 
          "file_type": "", 
          "programming_language": "", 
          "is_binary": null, 
          "is_text": null, 
          "is_archive": null, 
          "is_media": null, 
          "is_source": null, 
          "is_script": null
        }
      ], 
```

I used "scancode_version": "1.6.1"

**Comment by pombredanne** [comment]
Ok. we never return the directories indeed. Would you want them to be always returned or only based on an option?

**Comment by pombredanne** [comment]
Also, what about the size and file_counts? these can be (in fact are already behind the scenes) computed all right

**Comment by jdaguil** [comment]
The file information for other other sub directories under `samples` is detected (i.e. `JGroups`, `zlib`, `arch` all return file info). However, `samples` itself did not return any information.

**Comment by pombredanne** [comment]
The directories are now always returned in the scan. Closing!
