### ISSUE TITLE
ocb-open-source-2013 not recognized

### ISSUE THREAD

**Issue by mmurto** [nexB/scancode-toolkit#2670]
### Description

ScanCode does not recognize `ocb-open-source-2013` in https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/modes/OCBBlockCipher.java.

### System configuration

ScanCode commit 5db9d0511.

**Comment by pombredanne** [comment]
@mmurto Thank you ++ for this report!
In case you could be interested to help fix similar issues in the future I tried to make a didactic PR in #2677

- The first commit https://github.com/nexB/scancode-toolkit/commit/e9286de6348d99a64952c122ed37348fe39e2449 adds the minimal rule and a test to fix the issue
 
- The second commit at https://github.com/nexB/scancode-toolkit/commit/98c4393b31f39a8dfbacb9e720bea235c28b8287 adds a bunch of extra rules that have been collected left and right for other mentions of this license

Your review there is much welcomed!

**Comment by pombredanne** [comment]
This  fixed and merged in develop. Thank you++

**Comment by mmurto** [comment]
> @mmurto Thank you ++ for this report!
> In case you could be interested to help fix similar issues in the future I tried to make a didactic PR in #2677
> 
> * The first commit [e9286de](https://github.com/nexB/scancode-toolkit/commit/e9286de6348d99a64952c122ed37348fe39e2449) adds the minimal rule and a test to fix the issue
> * The second commit at [98c4393](https://github.com/nexB/scancode-toolkit/commit/98c4393b31f39a8dfbacb9e720bea235c28b8287) adds a bunch of extra rules that have been collected left and right for other mentions of this license
> 
> Your review there is much welcomed!

Thank you, I'll try a fix next time!

One thing that's not immediately obvious from the rules you added is that why is `relevance` 100 in all of them? Could it be something else and what would that mean? [This](https://github.com/nexB/scancode-toolkit/blob/e912830fae079d1f25c4d88995360e1c49a697f9/src/licensedcode/models.py#L783-L790) generally describes what it's about, but if there's any more information about what relevance should be for different kind of rules, that may come useful 🤓

**Comment by pombredanne** [comment]
Actually the relevance is not needed. The only time when a relevance is needed is when you have a small rule *(small as a in made of only a few words) and that is still highly relevant. For instance: `license: gpl3+` would be two words, but would be 100% relevant as a license tag for the gpl 3.
