### ISSUE TITLE
On the html-app license summary, I want to click on the listed licenses and ...

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#271]
... and I would like this to open the License & Copyright details tab listing only the files with this license

**Comment by sschuberth** [comment]
Actually, I do believe we should clearly separate between license and copyright here. That is, if in the *License Summary* I click on "No License Found", I want to see the list of all files that lack license information (no matter whether there is copyright information or not), and if in the *Copyright Summary* I click on "No Copyright Found", I want to see the list of all files that lack copyright information (no matter whether there is license information or not).

**Comment by pombredanne** [comment]
@sschuberth this makes sense.... note that this bare HTML app will likely be superseded by an upcoming Electron-based app that @jdaguil is working on

**Comment by pombredanne** [comment]
Actually this is something that is implemented in https://github.com/nexB/aboutcode-manager instead ... @jdaguil can you paste the ticket link here for reference so I can close this?

**Comment by pombredanne** [comment]
I am closing as this is not something for scancode to implement.  This has been implemented in https://github.com/nexB/aboutcode-manager/issues/167
