### ISSUE TITLE
accept patterns as file paths 

### ISSUE THREAD

**Issue by balusarakesh** [nexB/scancode-toolkit#272]
scancode is a command line tool and I think it's a good idea to accept patterns in file paths
for example:
`scancode --license /home/nexB/files/COPYING*` must scan all the files with patterns `COPYING*`

**Comment by pombredanne** [comment]
I have been thinking about this and I cannot find a good justification for it. It further creates some complexity as shell expansion works differently on posix and windows. I am closing this for now. Please reopen if you feel strongly otherwise and can help with the implementation.
