### ISSUE TITLE
Typo in command to enter...

### ISSUE THREAD

**Issue by tgodau** [nexB/scancode-toolkit#2720]
### Description

https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#pip-install

Point 2.: Run `pip install --upgraded pip setuptools wheel` to install the latest versions of base utilities.

"--upgraded" won't work.
The correct command should be:

 `pip install --upgrade pip setuptools wheel`

### Link to Documentation Page

see above

### Select Category

-  [ ] Inconsistency
-  [ ] New Section Request
-  [ ] General Improvement
-  [X] Typo/Mistakes
-  [ ] Other

**Comment by beastrun12j** [comment]
I would like to work on this issue

**Comment by pombredanne** [comment]
@beastrun12j Thank you!
