### ISSUE TITLE
"OSError: [Errno 28] No space left on device: '...' " during scan

### ISSUE THREAD

**Issue by goekDil** [nexB/scancode-toolkit#2721]
### Description

[moby-20.10.5.zip](https://github.com/nexB/scancode-toolkit/files/7252772/moby-20.10.5.zip)

After scanning the folder 'moby-20.10.5' I ran into following error:

* (from docker logs)
![image](https://user-images.githubusercontent.com/91614140/135285125-f97ee5d8-29ba-47bf-b602-ee959cf52ad7.png)

There should be enough space left on the device.

### How To Reproduce

Scan folder 'moby-20.10.5' with following function.

![image](https://user-images.githubusercontent.com/91614140/135282685-eb1302af-bdec-40ce-9b51-b57c0b3969e9.png)

Note, that max_depth=0, such that there are no limitations.

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
Windows/docker, as well as Linux/docker
* What version of scancode-toolkit was used to generate the scan file?
21.8.4
* What installation method was used to install/run scancode? (pip/source download/other)
pip with Python 3.6

**Comment by pombredanne** [comment]
Would this be with https://github.com/moby/moby/archive/refs/tags/v20.10.5.tar.gz ?

**Comment by pombredanne** [comment]
And I had not seen your attachment! so I am good wih the code link you provided.

So I think this is sparse tarball issue which is 60GB extracted and only 5KB otherwise, unextracted, and not even compressed 

Can you test scanning that one single 5KB file? 
https://github.com/moby/moby/blob/363e9a88a11be517d9e8c65c998ff56f774eb4dc/vendor/archive/tar/testdata/gnu-sparse-big.tar

And can you detail what pre-processing you apply on this. Did you call extractcode first?
Is there a place where I can see your code? I am always interested in how ScanCode is integrated!

**Comment by pombredanne** [comment]
Note that this could be related to https://github.com/nexB/scancode-toolkit/issues/2431 where @Angi2412 and @avishmehta68710 both mentioned having a similar issue or at least this comment https://github.com/nexB/scancode-toolkit/issues/2431#issuecomment-800013030 references the same code:
> I could observe the same behaviour and error message with this file: moby v20.10.5.

**Comment by goekDil** [comment]
Yes, I apply extractcode first! Unfortunately, there is no place where you can see my code, but I can provide a minimalexample.py: 

```
  from scancode import cli
  import multiprocessing
  import logging
  from extractcode import extract
  
  def main():
  
      extract_log = extract.extract(location='gnu-sparse-big.tar', recurse=True)
      i = 0
      for e in extract_log:
          print(e)
  
      rc, results = cli.run_scan(
          'gnu-sparse-big.tar-extract', license=True, copyright=True,
          return_results=True, processes=14, verbose=True, quiet=False,
          timeout=46800)
  
      print(rc, results)
  
  if __name__ == "__main__":
      main()
  ```

As you proposed, I tested the one single 5KB file and the exact same Error occurs:

![image](https://user-images.githubusercontent.com/91614140/135405769-9eddc133-da5a-4726-8610-a5c79a5f5912.png)
(docker logs) (Linux and Windows with docker)

Depending on the machine I work on
* I either experience the same Issue as in #2431 (Linux with docker or run minimalexample.py as standalone python script)
* or there appears the Issue "OSError: [Errno 28] No space left on device" as I mentioned above (Windows with docker, as well as Linux with docker)

**Comment by goekDil** [comment]
Thank you very much! After further analysis, I also came to the conclusion that this is a sparse file issue.
