### ISSUE TITLE
Add a command line option to dump the license data

### ISSUE THREAD

**Issue by fviernau** [nexB/scancode-toolkit#2738]
The OSS Review Toolkit needs to have all license IDs along with the respective license text for the ScanCode version it uses.
Currently it extracts it from the license data directory, see e.g. [1] [2]. So it depends on the directory structure as well as on the file formats of ScanCode license data. A ScanCode command line option for dumping

1. licenseIDs
2. corresponding texts
3. corresponding license category (not needed now, only maybe nice to have IMO to enable using the categories within ORT by implementing a conversion to [3])

..to a JSON? file would help to remove that mentioned dependency.

[1] https://github.com/oss-review-toolkit/ort/blob/093a510aa8545cc61cc172d7a7a274f56df87d84/spdx-utils/build.gradle.kts#L62-L71
[2] https://github.com/oss-review-toolkit/ort/blob/093a510aa8545cc61cc172d7a7a274f56df87d84/spdx-utils/build.gradle.kts#L238-L343
[3] https://github.com/oss-review-toolkit/ort/blob/093a510aa8545cc61cc172d7a7a274f56df87d84/model/src/main/kotlin/licenses/LicenseClassifications.kt

**Comment by AyanSinhaMahapatra** [comment]
There are two options:

 - We have a command line option (I was thinking something like  --get-license-data folder_path) in SCTK to:
Just generate the .json/.yml files used to generate the LicenseDB pages and have validation tests (this way we have the sort of API for license data and other tools like ORT can consume and not read the actual License files)
- Do everything in option 1. plus we actually generate the pages (.html files and the index.html) too locally (this would mean adding almost everything in the repository scancode-licensedb into scancode-toolkit, history preserved of course) i.e. move the code into a licensedcode file and the template/static also there.

@pombredanne :

IMHO there are  different things
- SCTK shall be able to generate a dump that would include JSON/YML and HTML  (with more or less flexbility TBD, but a single option for now is fine). The output should be exactly like the  scancode-licensedb output
- The  scancode-licensedb repo will stay as is, minus the generation code and would instead use the the CLI option in 1. to create itself (and the history stay in this repo entirely)

**Comment by AyanSinhaMahapatra** [comment]
This is in develop now, and will be released in a release-candidate soon, @fviernau can you try it out. More details in the PR linked above ^ .

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra I think this is all done now? correct? If so please close.

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne yes!

This is now present as a seperate console command `scancode-license-data` at https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/license_db.py#L208
