### ISSUE TITLE
Please use stderr ONLY for errors

### ISSUE THREAD

**Issue by FrankHeimes** [nexB/scancode-toolkit#2743]
## Short Description
Please use `stderr` **only** for errors, not for warnings or informal messages

## Possible Labels
- enhancement
- GUI and outputs
- should have

## Select Category

-  [x] Enhancement

## **Describe the Update**
I'm running scancode 30.0.0 and Python 3.9 on Windows 10 (21H1).

I'm currently running scancode as a build step in my TFS build definition.
The TFS build logger automatically examines `stdout` and `stderr` and flags all messages, that were emitted to the latter, as errors.
This is usually very helpful since `stderr` should contain error messages as the name suggests.

However, scancode needlessly prints informal and progress messages to `stderr`, too.
This is not necessary because scancode is not a filter that dumps any result data to `stdout`.

So the build log in TFS incorrectly flags the following as error message and thus marks that build step as failed:
```
2021-10-22T01:46:22.9272603Z ##[error]Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages, emails, urls, generated with 8 process(es)...
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
... 
```

## **How This Feature will help you/your organization**
As a workaround, I have to redirect `stderr` to `stdout` using `2>&1`.
But this makes it more difficult to track real errors scancode might encounter.

## **Possible Solution/Implementation Details**
Please review the output commands in scancode and use `stderr` exclusively for error messages.

**Comment by pombredanne** [comment]
@FrankHeimes Have you tried the `--quiet` option? It has been designed to only report errors to stderr and nothing else. If it does not work as advertized this is a bug!

**Comment by FrankHeimes** [comment]
@pombredanne Thanks for the tip. I forgot about this option. After specifying `--quiet`, nothing was printed to stderr, except for the _"Some characters ..."_ message (issue [1873](https://github.com/nexB/scancode-toolkit/issues/1873)). But that issue is still open anyways.
