### ISSUE TITLE
Scancode-toolkit-30.1.0 Python 3.8 Windows 10 installation issue

### ISSUE THREAD

**Issue by Mhanna112** [nexB/scancode-toolkit#2750]
Getting "'"C:\Users\hannmar\Downloads\scancode-toolkit-30.1.0\Scripts\scancode"' is not recognized as an internal or external command,
operable program or batch file." when I try to run scancode-h in the correct directory where the scancode folder is located.

**Comment by pombredanne** [comment]
@Mhanna112 sorry for the late reply. 
Can yo explain how you installed scancode exactly and what is your OS/arch/Python version?

**Comment by pombredanne** [comment]
@Mhanna112 Can you try this with the latest beta? 
https://github.com/nexB/scancode-toolkit/releases/tag/v31.0.0b4

**Comment by Nikolai-Hlubek** [comment]
Hi I wanted to report the same error as the OP on windows 10.

For version 30.1.0 and 31.0.0b3 I get the same error as the OP. For 31.0.0b4 I get the error below: 

```
  File "C:\toolchain\tools\python3\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\toolchain\tools\python3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'virtualenv.activation.xonsh'
```

**Comment by pombredanne** [comment]
This should be solved in https://github.com/nexB/scancode-toolkit/pull/3053 and will be released with v31.
But I am not sure 100% since I never got details wrt. how ScanCode has been installed and what's the version of Python used.

**Comment by pombredanne** [comment]
I am closing it for now... please reopen of file a new issue if you are still experiencing this.
