### ISSUE TITLE
Scancode takes a very long time to scan certain files

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#277]
This file (from tracecode): [graph_bash.pdf](https://github.com/nexB/scancode-toolkit/files/338131/graph_bash.pdf) takes a very long time to be scanned with scancode. 

It would be nice if the scancode-toolkit had a way to handle such problematic files, such as an exclusion list or a sane timeout period for particular filetypes.

**Comment by pombredanne** [comment]
ScanCode now enforces a timeout with the fixes in #267. This should handle weird PDFs nicely. Closing now.
