### ISSUE TITLE
Correct code and/or docstrings or both

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2771]
In get_primary_license, the docstring is not correct,
The text says:
```
Return a license expression string which is the primary license for the
debian copyright file.
```
but nothing is returned

https://github.com/nexB/scancode-toolkit/blob/1fdf40faabc0cf91fb3e7e8ff11412fcfb358577/src/packagedcode/debian_copyright.py#L374

**Comment by adii21-Ux** [comment]
I did try and solve this issue and found out problem was only with docstring

**Comment by adityasangave** [comment]
I did try and solve this issue and found out the problem was only with docstring, should I open a PR
