### ISSUE TITLE
Bogus "Outdated ScanCode Toolkit version" message when running ScanCode 30.1.0

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#2796]
### How To Reproduce

```
ort (master) $ scancode --license LICENSE --json-pp a.json
Setup plugins...
Collect file inventory...
Scan files for: licenses with 1 process(es)...
[####################] 2                 
Scanning done.
Summary:        licenses with 1 process(es)
Errors count:   0
Scan Speed:     1.50 files/sec. 
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s) 
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) 
Timings:
  scan_start: 2022-01-14T092000.290009
  scan_end:   2022-01-14T092007.659667
  setup_scan:licenses: 6.70s
  setup: 6.70s
  scan: 0.67s
  total: 7.37s
Removing temporary files...done.
WARNING: Outdated ScanCode Toolkit version! You are using an outdated version of ScanCode Toolkit: 30.1.0 released on: 2021-09-24. A new version is available with important improvements including bug and security fixes, updated license, copyright and package detection, and improved scanning accuracy. Please download and install the latest version of ScanCode. Visit https://github.com/nexB/scancode-toolkit/releases for details.
```

So ScanCode version 30.1.0 complains about being outdated although there currently is no newer release at https://github.com/nexB/scancode-toolkit/releases or https://pypi.org/project/scancode-toolkit/#history.

**Comment by adityasangave** [comment]
Yes I noticed that too @pombredanne should I work on this?

**Comment by adityasangave** [comment]
So I guess the problem is not comparing locally installed scancode version with latest version instead of just checking whether 90 days has passed by since latest release take a look at these images @pombredanne 
![Screenshot from 2022-01-15 22-09-51](https://user-images.githubusercontent.com/88366673/149630562-8d82f192-8c4f-41b3-a396-8bb851986a85.png)
![Screenshot from 2022-01-15 22-09-58](https://user-images.githubusercontent.com/88366673/149630565-c22c8d9c-1177-4a7a-ac8d-e11431fcd2f5.png)
![Screenshot from 2022-01-15 22-10-16](https://user-images.githubusercontent.com/88366673/149630566-f7adc17b-2f8d-48d3-b8b7-7502014b959c.png)

**Comment by pombredanne** [comment]
That's a bug alright!

**Comment by adityasangave** [comment]
@pombredanne remainder you said we need to talk about solution to above problem

**Comment by pombredanne** [comment]
yes!
So there are two use cases:
1. offline usage in which case no check should be done
2. online usage in which case a PyPI lookup should be done at most once a week

This was essentially the previous implementation if I recall? You may want to search the history a bit

**Comment by adityasangave** [comment]
Ok I'll do some search and will get back to you

**Comment by adityasangave** [comment]
Ok So I found out before version 30.0.0 we only used PyPI check of scancode version both for online and offline take a look
![Screenshot from 2022-02-08 18-29-46](https://user-images.githubusercontent.com/88366673/152992058-9425ac48-115b-4c09-91cb-11abdae50245.png)
![Screenshot from 2022-02-08 18-30-05](https://user-images.githubusercontent.com/88366673/152992063-54f9e12d-a588-4f08-a9a6-8cb0a928335e.png)
![Screenshot from 2022-02-08 18-30-16](https://user-images.githubusercontent.com/88366673/152992068-fa9b9381-8ae5-45c3-bca7-6a8259b3b147.png)

**Comment by adityasangave** [comment]
So I guess the solution for solving this problem when offline we need to store latest version of scancode-toolkit somewhere for e.g. in scancode-config.py so that exception won't occur, what do you think?

**Comment by pombredanne** [comment]
@adii21-Ux Good research! Thank But pasting images makes it bit hard... please use text. That said, I think now that just removing the https://github.com/nexB/scancode-toolkit/blob/cec5846d3864fd53d13c3e6f536ecc8a39f448e8/src/scancode/outdated.py#L138 and https://github.com/nexB/scancode-toolkit/blob/cec5846d3864fd53d13c3e6f536ecc8a39f448e8/src/scancode/outdated.py#L70 to remove all "local" checks is fine.

**Comment by adityasangave** [comment]
Ok i'll make the changes
