### ISSUE TITLE
Provide option to reference a specific DejaCode dataspace in scan results

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#280]
The scan process currently builds an output that contains a constructed URL to the nexB "Demo" dataspace; that works fine, and when a user clicks on that URL, the Demo version of the nexB license in the License Library is presented.  However, the benefit of that is somewhat limited if the scancode user has a subscription to DejaCode, in which case it would be best if that user can tell the scanning process which dataspace to use when constructing a DejaCode license URL.  

Also, even more beneficial would be the ability for the scancode user to provide an API Key to a specific dataspace, and for scancode to return the Usage Policy set for that license in the dataspace associated with the API.  Doing that would provide extremely useful information directly to the scancode user, providing a logical way to sort and filter the results to find the files/packages with a license that requires Review by someone in the scancode user's organization (or requires some other action).  By doing something like this, the user can focus immediately on the problem items, or at least those that require some kind of action.

**Comment by DennisClark** [comment]
See related Tickets #382  and   #214

**Comment by pombredanne** [comment]
@DennisClark the url is now datapsace neutral and use urns as in https://enterprise.dejacode.com/urn/urn:dje:license:cc0-1.0 .... If you are logged in, if will go in your own ds.
