### ISSUE TITLE
Running scancode command after extractcode in a batch-file fails

### ISSUE THREAD

**Issue by DominikLechner1** [nexB/scancode-toolkit#2804]
### Description
I tried to scan some *.jar Files automatically, by extracting them first, and then running the scan. I wanted to do this with a batch-file, however in the batch file the task stops after completing extractcode.
If I copy and paste the two commands into the cmd-console, it works like a charm and both are executed.
> Please leave a brief description of the bug or feature request:

### How To Reproduce
Run extractcode and scancode from a batch-file

D:\scancodeToolkit\scancode-toolkit-30.1.0\extractcode --verbose "D:\temp"
D:\scancodeToolkit\scancode-toolkit-30.1.0\scancode -l --processes 6 --include "License.txt" --include "MANIFEST.MF" --include "License" --include "Manifest" --include "*_lic.txt" --include "pom.xml" --only-findings --json-pp "D:/temp/results.json"  "D:/temp"

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* Windows 10
* What version of scancode-toolkit was used to generate the scan file?
* 30.1.0
* What installation method was used to install/run scancode? (pip/source download/other)
source download

**Comment by DominikLechner1** [comment]
Sorry my bad, initially I thougt, extractcode exits the batch-file, which I considered undesired behaviour. 
But I solved my Issue by writing "call" before each command in the batch-file.

**Comment by pombredanne** [comment]
@DominikLechner1 good to know! Keep us posted on your automation efforts!
