### ISSUE TITLE
Full text of CC-BY-4.0 is recognized as `license notice` instead of `license text`

### ISSUE THREAD

**Issue by daniel-eder** [nexB/scancode-toolkit#2807]
### Description

When scanning the [official REUSE example repo](https://git.fsfe.org/reuse/example) with ScanCode 30.1.0 the [CC-BY-4.0.txt](https://git.fsfe.org/reuse/example/src/branch/master/LICENSES/CC-BY-4.0.txt) is recognized as `license notice` instead of `license text`.

### How To Reproduce

This issue has been produced by scanning https://git.fsfe.org/reuse/example with ORT, following https://github.com/oss-review-toolkit/ort/blob/master/docs/getting-started.md.

The issue should reproduce independent of the exact ScanCode Toolkit configuration.

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Ubuntu 20.04 x64
* What version of scancode-toolkit was used to generate the scan file? 30.1.0 
* What installation method was used to install/run scancode? run with ORT

**Comment by pombredanne** [comment]
Thanks you ++
Good catch!
