### ISSUE TITLE
--from-json option throws error

### ISSUE THREAD

**Issue by lucasgonze** [nexB/scancode-toolkit#2814]
### Description

`./scancode --from-json scancodeio-output.json --json-pp /tmp/t.json
` 
throws error
`
failed to collect codebase at: 'scancodeio-output.json'`

### How To Reproduce

> Tell us how to reproduce the issue. 

1. Use scancode.io to generate json
2. Save the output
3. scancode-toolkit-30.1.0/scancode --from-json scancodeio-output.json --json-pp /tmp/t.json

Copy of json output file: [Magma.json.zip](https://github.com/nexB/scancode-toolkit/files/7938169/Magma.json.zip)

### System configuration

* OS: OS X Monterey 12.1
* Python 3.9
* scancode-toolkit-30.1.0

**Comment by lucasgonze** [comment]
Detailed error info and CLI log:
![image](https://user-images.githubusercontent.com/111581/151083968-49d01382-bd52-4ba8-8287-2fa2dc2b3649.png)

**Comment by pombredanne** [comment]
@lucasgonze Thanks for the report.... Your input JSON file looks like it is truncated?

**Comment by lucasgonze** [comment]
You're correct. Thank you for the reality check.

If I can reproduce the issue that produced the truncated JSON, I will post it separately.
