### ISSUE TITLE
Cache pickling error in the 86 branch

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#284]
We get this random error on cache and pickling. See https://github.com/grantjenks/python-diskcache/issues/25

**Comment by pombredanne** [comment]
Based on this http://stackoverflow.com/questions/34916679/numpy-test-error-in-virtualenv-with-error-test-multiarray-testnewbufferprotocol this could be a Python bug

**Comment by balusarakesh** [comment]
I just tested the code and it seems to work fine.

**Comment by pombredanne** [comment]
The fix was switfly merged  https://github.com/grantjenks/python-diskcache/issues/25 
@grantjenks : Thank you ++!
Next is to update to the latest Pypi 1.7.0 of diskcache

**Comment by pombredanne** [comment]
Done. Closing.
