### ISSUE TITLE
Question on how to run scancode

### ISSUE THREAD

**Issue by dvc94ch** [nexB/scancode-toolkit#288]
When I run setup.py install, it doesn't install the scripts listed in entry_point. I also tried to `import scancode.command_line` from a python repl like suggested [here](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) but that didn't work either.

Here is a pastebin of what is installed.
http://sprunge.us/RBBM

PS. I purged the binaries in `src/extractcode/bin` and `src/typecode/bin` folders from the codebase.

**Comment by pombredanne** [comment]
For now, you cannot just setup.py yet (working on it and though it may work, it is not tested yet).
ScanCode is meant to run a local/isolated virtualenv and self-contains all of its deps. 

For development-type work, from a fresh checkout or full source download, run:
`source configure`
This will effectively create a virtualenv, activate it, install any needed deps (that are actually vendored in `thirdparty`) and run a `pip install -e .` on scancode, mostly equivalent to a `setup.py install`

NB: I am assuming that you are running a *nix OS.

I hope this helps: I am not sure what you want to achieve. If this is just to run scancode, just untar a download or clone the repo and run `./scancode` directly: it will self-configure on the first run.

As a side note:
> PS. I purged the binaries in src/extractcode/bin and src/typecode/bin folders from the codebase.

Ouch... do not do this! these are essential directories that contains pre-built native binaries... (libarchive, 7zip and other for extractcode and libmagic for typecode) this will surely result in a non-working scancode ...

**Comment by dvc94ch** [comment]
I intend to write a plugin for guix (a package manager) to run it against our existing package database and compare it to the licenses that where supplied manually. The first step is packaging scancode.

> Ouch... do not do this! these are essential directories that contains pre-built native binaries... (libarchive, 7zip and other for extractcode and libmagic for typecode) this will surely result in a non-working scancode

Binaries aren't accepted according to our packaging guidelines. Is there reason why it can't pick up the libraries through LD_LIBRARY_PATH?

> For now, you cannot just setup.py yet (working on it and though it may work, it is not tested yet).

That would be nice! Again guix is basically a virtualenv at the distro level, so any packages can be added to a profile. We have support for python-packages that use setuptools.

**Comment by dvc94ch** [comment]
So the initial plan is to determine the number licenses that are both found by scancode and are declared in the packages vs the licenses only declared or only found to estimate a combined error rate of manual and scancode license auditing, and take it from there. Please let me know if you improve the installation process or if you determine that the error is on my end =)

Feel free to close the issue for now and thank you for your prompt reply!

Cheers,
David

**Comment by pombredanne** [comment]
Guix is a mighty fine tool indeed.
So breaking the packaging would be a tad involved but not impossible.
The reason why binaries are vendored is to allow to just fetch a tarball or clone and run without further deps and that on Linux/Windows/Mac (the later two being somewhat painful to get right and not always having a decent compiler on hand)

The way the .so's and exe are found is based on [code here](https://github.com/nexB/scancode-toolkit/blob/dd290b91d451b88cb4f8cdb2844688ad6000d085/src/commoncode/command.py). This actually sets the paths needed for either opening a dynamic lib or getting to an os/arch specific exe.
I have all the corresponding [source code](https://github.com/nexB/scancode-thirdparty-src) on hand should you want to recompile the binaries or find a corresponding Guix package. 

There should not be too many hard deps on a version except likely for ... well... yes there are: 7z, libarchive, libmagic newer versions have not been tested yet!  

Otherwise, several Python libraries (some of them with natives) are in the `thirdparty` directory.
The overall initial setup is through the `./configure` script.

To recap, I think this would be needed:
1. collect (ro create) the Guix packages as deps for every vendored binaries in `src/`
2. collect (ro create) the Guix packages as deps for every vendored python package in `third-party/`
3. we would need to come with a clean way to get to the exe and .so based on their actual Guix locations
4. the bootstrap script `/scancode` and `/extractcode` would need to be replaced by something that sets the paths correctly (whcih I assume Giux is probably quite string about)

Note also that I am planning to push a new release candidate for v2 over the week end. I will make sure at this can install nicely from Pypi. That would take care of point 2. at least.

You also wrote:
> So the initial plan is to determine the number licenses that are both found by scancode and are declared in the packages vs the licenses only declared or only found to estimate a combined error rate of manual and scancode license auditing, and take it from there.

I actually want a Guix package metadata parser in ScanCode too! and yes, this is a sound approach of yours: scan the actual asserted licenses at the metadata level and compare with the actual real one detected in the sources  (or binaries as scancode dives into these too)

**Comment by pombredanne** [comment]
You wrote:
> Please let me know if you improve the installation process or if you determine that the error is on my end

You are not exactly a lambda scancode user... and the installation process is making a major assumption: you can just download and run. Can you confirm that this is working at least for you locally when you just have a Python 2.7 in your path? 

Re-packaging in Guix just breaks this fine assumption indeed. Nothing wrong with that on your part, this was not planned ahead but supporting a Guix package would be is a good thing to me.

**Comment by dvc94ch** [comment]
>2. collect (ro create) the Guix packages as deps for every vendored python package in third-party/

I already packaged all the python dependencies.

>3. & 4. The way the .so's and exe are found is based on code here. This actually sets the paths needed for either opening a dynamic lib or getting to an os/arch specific exe.

So it looks like LD_LIBRARY_PATH is respected. Guix takes care of setting it correctly. And if bin/lib isn't found (I already removed them) then `get_bin_lib_dirs` returns `None` and the LD_LIBRARY_PATH isn't overwritten. So this looks good too.

1. collect (ro create) the Guix packages as deps for every vendored binaries in src/

Haven't done this yet. I like taking things one step at the time and this wasn't necessary yet.


What I'm missing is `setup.py install` creating a bin directory somewhere and adding a script that loads and runs scancode/cli.py.

**Comment by pombredanne** [comment]
You wrote:
> What I'm missing is setup.py install creating a bin directory somewhere and adding a script that loads and runs scancode/cli.py.
> Maybe there already is a way, I tried running python2 cli.py --help but that didn't work.

The setup.py already generates a calling script alright.
When using the standard scancode, it creates these under `bin/scancode` at the same level as the scancode directory.

for instance with a fresh clone if I run:
`./configure`
I can then run:
`./bin/scancode` alright 

Can you check this works for you?
The script is a standard setuptools-generated entry point script

**Comment by pombredanne** [comment]
Note also that you would not need extractcode for now to get things working (this is a separate command line for now), so the only non-python dep you need  __in the current__ version to get the license detection going would be libmagic. And this documents exactly which version: https://github.com/nexB/scancode-toolkit/blob/dd290b91d451b88cb4f8cdb2844688ad6000d085/src/typecode/bin/linux-32/lib/file.ABOUT

**Comment by pombredanne** [comment]
Note also that there updated Python deps (including some with native code, but they compile from source nicely on Linux) that will trickle when I merge the #86 branch, but they should be trivial

BTW, do you have a pointer to an example of a Guix guile "descriptor" for a Python package?

**Comment by pombredanne** [comment]
Actually if I create a bare virtualenv by hand and once activated if I cd to the scancode dir and run a python setup.py install the scripts are not generated. And the develop branch does not install yet with setup.py. I will look into this in details tomorrow or over the week-end. Thank you for hanging in there.

**Comment by dvc94ch** [comment]
Here is an example python package. It doesn't have any dependencies. Or if it has native dependencies I haven't noticed yet. A C dependency would be added to the inputs field, and a python dependency would be added to the propagated-inputs field. (Since all python dependencies needs to be available to the dependant package also)

```scheme
(define-public python-nltk
  (package
  (name "python-nltk")
  (version "3.2.1")
  (source
    (origin
      (method url-fetch)
      (uri (string-append
             "https://pypi.python.org/packages/58/85/"
             "8fa6f8c488507aab7d6234ce754bbbe61bfeb8382489785e2d764bf8f52a/"
             "nltk-" version ".tar.gz"))
      (sha256
       (base32
        "0skxbhnymwlspjkzga0f7x1hg3y50fwpfghs8g8k7fh6f4nknlym"))))
  (build-system python-build-system)
  (inputs
    `(("python-setuptools" ,python-setuptools)))
  (home-page "http://nltk.org/")
  (synopsis "Natural Language Toolkit")
  (description "Natural Language Toolkit")
  (license license:asl2.0)))

(define-public python2-nltk
  (package-with-python2 python-nltk))
```

Thank you for looking into this! I'm working of the development branch, it saved me packaging an old python-nltk version...

**Comment by daym** [comment]
Actually, propagated-inputs should be avoided and often it also works if you add the python dependencies to input (since we hotpatch the python scripts in the python-build-system so they will find them later).

**Comment by dvc94ch** [comment]
Cool! Some of the python deps are already on the mailing list and Leo commented on them. I just haven't gotten a chance yet to update them. I attached the rest. Please don't be shocked at the ugliness, it's a wip ;-)

[0001-guix-license-wip.patch.txt](https://github.com/nexB/scancode-toolkit/files/420111/0001-guix-license-wip.patch.txt)

**Comment by pombredanne** [comment]
@dvc94ch looking good! Is there anything I can do to help on my side?
I see you are packaging the current stable master 1.6.0. Are you able to run the tests alright?
for instance with `py.test tests/licensedcode` ? (this takes a while when multithreaded)

**Comment by pombredanne** [comment]
@daym you wrote:
> If there's no way to install a script in scancode then we can just manually install in the package spec. I can do that if needed.

Is there something I can help with here? 
The structure is this:
`scancode` at the root is a bootstrap shell script. It does this:
1. invoke the `configure` script which calls the `etc/configure.py` script that creates a local virtualenv and then installs the vendored deps from `thirdparty/` 

2. and finally that configure process also  `pip install .` that  installs scancode itself in this local virtual. This is equivalent to a `python setup.py install` in the activated local virtualenv. The setup.py has the directives to generate a console entry point which is created at that stage by `setuptools` directly under the `bin/` dir of the local virtualenv as `bin/scancode`. That generated script is ware of the virtualenv path which is what setuptools does.

3. calls the `bin/scancode` script.

I guess you are unlikely to want to reuse all this machinery, but you would still want to get the generated script from the `setup.py install`, right? Does guix has the way to deal with this for other similar tools with CLI (such as `pip` or `httpie` https://github.com/jkbrzt/httpie/blob/5efc9010ccc260d99e5790fa1a9fe5b06039ae96/setup.py#L84 ) ?

**Comment by pombredanne** [comment]
Ping: is there something left to do here? @dvc94ch  Are you all set on Guix side?

**Comment by dvc94ch** [comment]
Sorry, I'll have to look into this again. I have a large backlog of stuff
to do (like finishing the guixsd port to arm and finishing support for
rust/cargo packages). I should have more time around Christmas when the
semester is over...

**Comment by pombredanne** [comment]
@dvc94ch no rush. There are many improvement coming in anyway :)

**Comment by pombredanne** [comment]
BTW, will you be at FOSDEM?

**Comment by dvc94ch** [comment]
Maybe, don't know yet for sure.

**Comment by dvc94ch** [comment]
Closing as duplicate of #469
