### ISSUE TITLE
Change emoji

### ISSUE THREAD

**Issue by kalashvasaniya** [nexB/scancode-toolkit#2881]
### 🧐 What you will have to Do

You'll have to contribute to the ScanCode Toolkit Documentation, to solve inconsistensies/update
docs.

 - You'll find an issue from [here](https://github.com/nexB/scancode-toolkit/issues/1826)
 - Create an issue using this template [here]() 
 - And then solve it (Follow the Task List Below).

### A first-timer's Issue

A [first-timers-only issue](https://github.com/nexB/scancode-toolkit/labels/first%20timers%20only)
means we've worked to make it more legible to folks who either **haven't contributed to our codebase before,
or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and
help you out as you do. Note that we're especially interested in contributions from people from
groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors and
this issue is for you. 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through
our general [good first issue](https://github.com/nexB/scancode-toolkit/labels/good%20first%20issue) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :)
You need to learn basic reStructuredText formatting, and very basic linux/git commands. 
We are happy to walk you through the process.

Useful Links - 

* [reStructuredText basics](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)
* [Git Basics](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository)

Remember, basic help is just one Google Search away!

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update
**within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as
long as you need if you update us with a request for more time or help, but if we don't see any
activity a week after you claim it we may reassign it to give someone else a chance.
Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can
easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise,
[take a look at some other issues you can help with](https://github.com/nexB/scancode-toolkit/labels/20first%20timers%20only).
Thanks!

### 🤔❓ Questions?

Leave a comment below!

### 📋 Step by Step

- [ ] 🙋 **Issue Claimed**: Make sure you've claimed this issue from the
  [First Timers Only Issues List](https://github.com/nexB/scancode-toolkit/issues/1826) and you've been
  assigned to this Issue by a maintainer.

- [ ] **Review Guidelines** Check out our Code of Conduct and Contributing Guidelines before you start working. 

- [ ] **Refer Documentation** Refer [docuementation](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_doc.html)
  for more help on the contribution process and to understand our Sphinx and reStructuredText built
  documentation generation better.

- [ ] **Build Docs Locally** Fork the repository, clone it to your local system, and setup a
  virtualenv to build the docs locally. 

- [ ] 📝 **Update** Fix the errors/inconsistencies.

- [ ] **Run Test Scripts** Run the Test Scripts to make sure Docs are building successfully and are style compliant.

- [ ] 💾 **Commit** your changes, 

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

    1. If you are familiar with the terminal or would like to learn it,
       [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
       on how to send a pull request using the terminal.

    2. You can also go to your Fork of ScanCode Toolkit and open a pull request from the branch you've pushed to.
       Always create the Pull Request with the develop branch, unless otherwise instructed by maintainers. 

- [ ] 🔗 **Link the Parent Issue** Refer [Documentation]()
  on creating First Timers Only Issues for more help.

- [ ] 🏁 **Done** Ask in comments for a review :)

**Comment by pombredanne** [comment]
What is this about? there is nothing but boilerplate in this
