### ISSUE TITLE
extractcode --shallow inconsistency 

### ISSUE THREAD

**Issue by clempou** [nexB/scancode-toolkit#2895]
### Description

> A brief description of the Documentation Improvement or New Section request.

The Section "Performing Extraction" from the tutorial page "How to run a scan" mentions a Note:
"--shallow option can be used to recursively extract packages" while the "How to extract archives" tutorial mentions:
"--shallow
Do not extract recursively nested archives (e.g. Not archives in archives)."

### Link to Documentation Pages

> Where the confusion/inconsistency/incomplete documentation is.

https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_run_a_scan.html#performing-extraction 
vs.
https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_extract_archives.html

Both should mention that a shallow extraction only decompresses "first level" archives in the code tree being scanned (If I recall correctly 😉)
### Select Category

-  [x] Inconsistency
-  [ ] New Section Request
-  [ ] General Improvement
-  [ ] Typo/Mistakes
-  [ ] Other

**Comment by pombredanne** [comment]
@clempou Thanks! that's a bug alright. `--shallow` means non-recursive

**Comment by lf32** [comment]
@pombredanne what would be the preferred text?
```
`--shallow` option can be used to prevent recursive extraction of nested archives.
```
