### ISSUE TITLE
required match percentage for Scan to identify a string of text as a license must be increased

### ISSUE THREAD

**Issue by lalitbittu11** [nexB/scancode-toolkit#2900]
Scan thinks there is a "google-patent-license-webm" but this is not true 

The rule (bsd-new_and_google-patent-license-webm_5.RULE):

*  Use of this source code is governed by a BSD-style license
*  that can be found in the LICENSE file in the root of the source
*  tree. An additional intellectual property rights grant can be found
*  in the file PATENTS.

The text in the source code:

     1                     // Copyright 2014 The Go Authors. All rights reserved.
     2                     // Use of this source code is governed by a BSD-style
     3                     // license that can be found in the LICENSE file.
     4                     
     5                     // Package oauth2 provides support for making
     6                     // OAuth2 authorized and authenticated HTTP requests,
     7                     // as specified in RFC 6749.
     8                     // It can additionally grant authorization with Bearer JWT.

So, except line 2 and 3, the whole part is missing (except for the word “grant”) from the source codes.

![image](https://user-images.githubusercontent.com/64598741/160547897-5659e149-1d1e-4be3-b235-b448a26a219a.png)

**Comment by pombredanne** [comment]
@lalitbittu11 Thanks for the report! This is a bug alright.

**Comment by pombredanne** [comment]
This is fixed with the commit above.

**Comment by AyanSinhaMahapatra** [comment]
This is fixed, closing!
