### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by TechnologyClassroom** [nexB/scancode-toolkit#2901]
When installing from pip on Ubuntu 18.04, I ran into this error:

```
ERROR: Could not install packages due to an OSError: [Errno 36] File name too long: '/home/user/.local/lib/python3.6/site-packages/licensedcode/data/rules/gpl-3.0_with_sencha-app-floss-exception_or_gpl-3.0_with_sencha-dev-floss-exception_or_sencha-commercial_and_public-domain_and_mit_and_mit_1.RULE'
```

Referenced [scancode file link](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/gpl-3.0_with_sencha-app-floss-exception_or_gpl-3.0_with_sencha-dev-floss-exception_or_sencha-commercial_and_public-domain_and_mit_and_mit_1.RULE)

Commands ran:

    sudo apt update && sudo apt upgrade -y && sudo apt install -y python3-pip python3-setuptools python-dev bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libpopt0
    python3 -m pip install scancode-toolkit

**Comment by pombredanne** [comment]
@TechnologyClassroom Thank you for the report.
This is surprising though.... are you running some kind of encrypted filesystem like luks?
https://en.wikipedia.org/wiki/Linux_Unified_Key_Setup ... this would be the only case I can think of. Which FS you have?

**Comment by pombredanne** [comment]
See https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs 

```
$ python -c "print(len('gpl-3.0_with_sencha-app-floss-exception_or_gpl-3.0_with_sencha-dev-floss-exception_or_sencha-commercial_and_public-domain_and_mit_and_mit_1.RULE'))"
144
```
where 144 is just one too many above 143... which is luks and ecryptfs max filename length! So fixing this will be easy: shortening these names and adding a test to ensure we reject names longer than 143 chars.

**Comment by TechnologyClassroom** [comment]
> encrypted filesystem like luks

You guessed it!

**Comment by pombredanne** [comment]
@TechnologyClassroom This is fixed in https://github.com/nexB/scancode-toolkit/pull/2918

**Comment by pombredanne** [comment]
And this has been merged in develop. Closing now. Thanks again.
