### ISSUE TITLE
Issues about the `--dwarf` plugin

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#2902]
### Description

There are two issues that I spot for the `--dwarf` plugin:
1. Nothing is returned from the `--csv` output (Note that the `--json` and `--yaml` work fine)
2. The returned dwarf reference path is not normalized (i.e. there are some path that have project/a/b/c/../../test.c)

### How To Reproduce

```
scancode --dwarf <project> --csv output.csv
```

**Comment by mjherzog** [comment]
Added the information to Issue 2422. We should track the progress there instead
