### ISSUE TITLE
How to use --ignore in run_scan() 

### ISSUE THREAD

**Issue by xu1119** [nexB/scancode-toolkit#2906]
I call scancode from python code by using run_scan, code is below:
’‘’
from scancode import cli
path = '/work/osl/sample'
rc, results = cli.run_scan(path, license=True, info=True, ignore='*.js', return_results=True, processes=2)
‘’‘
code executes successfully，but error message occurs in result:
’‘’
"errors": [
                "ERROR: failed to run pre-scan plugin: ignore:\nTraceback (most recent call last):\n  File \"/root/miniconda3/envs/osl/lib/python3.8/site-packages/scancode/cli.py\", line 1057, in run_codebase_plugins\n    plugin.process_codebase(codebase, **kwargs)\n  File \"/root/miniconda3/envs/osl/lib/python3.8/site-packages/scancode/plugin_ignore.py\", line 76, in process_codebase\n    includes = {\nTypeError: 'NoneType' object is not iterable\n"
            ]
‘’‘
scancode-toolkit version: 30.1.0
where is the problem？

**Comment by AyanSinhaMahapatra** [comment]
Try putting the `ignore` patterns in a tuple/list, see the ignore plugin code [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode/plugin_ignore.py#L64).

`rc, results = cli.run_scan(path, license=True, info=True, ignore=('*.js'), return_results=True, processes=2)` should work imho

**Comment by xu1119** [comment]
> Try putting the `ignore` patterns in a tuple/list, see the ignore plugin code [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode/plugin_ignore.py#L64).
> 
> `rc, results = cli.run_scan(path, license=True, info=True, ignore=('*.js'), return_results=True, processes=2)` should work imho

I try putting the ignore patterns in a tuple and also try in a list, it dosen't work, the error message is same.

**Comment by xu1119** [comment]
It is my problem, I ignore a single element tuple should contain a comma.
```
rc, results = cli.run_scan(path, license=True, info=True, ignore=('*.js',), include=('*',), return_results=True)
```
can work
