### ISSUE TITLE
Upgrade to support also Python 3.x

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#295]
The time is now!
 Some important reads:
- the official guide: https://docs.python.org/3/howto/pyporting.html
- a great extensive guide from @fedora-python  https://portingguide.readthedocs.io/en/latest/process.html

**Comment by pombredanne** [comment]
And this likely means only Python 3.5 and up

**Comment by sschuberth** [comment]
Here's one more vote to support Python 3 as that would make [debugging multiprocessing exceptions](http://stackoverflow.com/questions/29080650/debugging-errors-in-python-multiprocessing) like issue #413 a bit easier.

**Comment by pombredanne** [comment]
At a high level the key issues I can think of are:
- unicode vs. bytes, since a good many functions handle low level bytes and not unicode and Py3 is unicode by default.
- native libraries using C/C++
- other third-party libraries
- doctests (with `u''` in their expectations) or other similar tests

And in all cases, I want to support 2 and 3 at the same time with a single codebase which is not a big deal.


FWIW, most libraries should be OK except some natives. Upcoming ones (e.g. https://github.com/nexB/license-expression/ ) are also ok (I just ported that to Python 3)

**Comment by pombredanne** [comment]
For the 2 to 3 update, **the first step** will be effectively to gather wheels for every ScanCode-bundled dependencies

I do not know which one would be OK or not: this has to be tested

And eventually a Python 3 wheel --if not available-- can be built for all OSes/archs using https://github.com/pombreda/thirdparty-manylinux/ https://github.com/pombreda/thirdparty that are Travis and Appveyor build loops that create wheels and upload them to http://dl.bintray.com/pombreda/thirdparty/

Note that I have already started collecting Python 36 wheels there

And once all deps are available, **the second step** is to ensure that all the tests pass both on Py2 and Py3 and start making fixes, one at a time which will be the guide to make the port work

And BTW the minimum Python3 version we will support in ScanCode is 3.6.1.
Nothing before that :wink:

**Comment by vivonk** [comment]
According to me, most helpful is [this](http://python-future.org/compatible_idioms.html) so why we are collecting python wheels on version dependent. Are you trying say that packages of python3 should be installed as well like it do in python 2 case`(bin/python2.7)` for virtualenv purposes?

**Comment by sschuberth** [comment]
More reasons to upgrade to Python 3.x, and version 3.7 in particular: https://docs.python.org/3/whatsnew/3.7.html#optimizations

**Comment by davidak** [comment]
You have 11 months left to migrate to python 3. Then python 2 will no longer be maintained.

https://pythonclock.org/

What is the status?

**Comment by sschuberth** [comment]
> This is likely quite a bit of work especially if we want to keep support for Python 2 which may not be a good idea?

Wouldn't it be a nice & clean cut to make ScanCode 3.0 only support Python 3? That would be easy to remember 😉

**Comment by davidak** [comment]
>Would you be willing to chip in

Sadly i have already too many projects :D

**Comment by pombredanne** [comment]
@davidak fair enough: may be you will be willing to kick in the tires when we start to have something usable?

**Comment by davidak** [comment]
For now it works for me to manually set the license in my script. When this library works with python 3 i might try to detect it automatically.

**Comment by pombredanne** [comment]
from @dankegel in https://github.com/nexB/scancode-toolkit/issues/1342
> python2.7 is dying (see https://pythonclock.org/ ), time to make sure python3 support is happy.
> 
> On Ubuntu 18.04, installing with 'pip3 install scancode-toolkit' fails with
 ```
Collecting scancode-toolkit
  Could not find a version that satisfies the requirement scancode-toolkit (from versions: )
No matching distribution found for scancode-toolkit
```

> This is especially annoying since 'pip install scancode-toolkit' fails with a sigsegv (not scancode's fault; 'pip install simplejson' also crashes.  See https://github.com/simplejson/simplejson/issues/114 for workaround).

**Comment by pombredanne** [comment]
I wrote before 
> And in all cases, I want to support 2 and 3 at the same time with a single codebase which is not a big deal.

And

> This is likely quite a bit of work especially if we want to keep support for Python 2 which may not be a good idea?

Unless someone disagree, the next major version after the 3.x release (4.x) will be ported and made to run **only on Python3**. And **Python2 support will be dropped in 4.x** and available only in maintenance branches of the 3.x releases.

Having a codebase that does not try to support both versions will help quite a bit. Also I do not want to  try to support any Python 3 version before version 3.6. So it is more like we will be **migrating to Python 3.6+**

Objections and feedback welcomed!

**Comment by dankegel** [comment]
Happy to lose python 2.7.   python's story is way too hairy at the moment; we need to get to a place where everyone can always use venv.

**Comment by mjherzog** [comment]
Python 3.6 sounds good

**Comment by majurg** [comment]
I agree with @dankegel. Once we are fully migrated to python36+ I do not see a good reason to go out of our way to support python2.

**Comment by dankegel** [comment]
Please support python 3.5+, in particular, vanilla Ubuntu 16.04.

**Comment by rishi-s8** [comment]
@pombredanne, I would like to work on this. I have gone through [porting guide](https://docs.python.org/3/howto/pyporting.html). Can you help me get started?

**Comment by shubham06vijay** [comment]
Hi everyone!! I am Shubham Vijay. I am currently pursuing B-tech in Computer Science and Engineering from Visvesvaraya National Institute of Technology, Nagpur(NIT Nagpur). I would like to contribute to Port ScanCode to Python 3 . I have prior knowledge in python, c++,java and android.  I am interested in participating in GSOC 2019. I would like to contribute and discuss GSOC participation with the mentors and look forward to contributing to this project of About Code's as well. Can you help me get started with the environment needed and what exactly is expected?

**Comment by dankegel** [comment]
Here's one possible path:

1) Install ubuntu 16.04 (possibly using docker or lxc or virtualbox instead of a real machine) (because many people need to use scancode on ubuntu 16.04, which will be in common use in conservative companies for many years)
2) sudo apt-get remove python2.7
3) sudo apt-get install python3 python3-pip build-essential
4) Follow https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst
but before running configure, edit it to change python2.7 to python3
5) Run it and observe the failure:
```
ubuntu@demo-ubu1604:~/scancode-toolkit$ ./configure
...
  Could not find a version that satisfies the requirement nltk<4.0,>=3.2 (from scancode-toolkit==3.0.2->-r /home/ubuntu/scancode-toolkit/etc/conf/base.txt (line 10)) (from versions: )
No matching distribution found for nltk<4.0,>=3.2 (from scancode-toolkit==3.0.2->-r /home/ubuntu/scancode-toolkit/etc/conf/base.txt (line 10))

Failed to execute command:
pip install --upgrade --no-index --no-cache-dir --find-links="/home/ubuntu/scancode-toolkit/thirdparty" -r "/home/ubuntu/scancode-toolkit/etc/conf/base.txt". Aborting...
```

6) Read configure and etc/configure.py
7) Realize that it refers to bundled python2 versions of everything
8) Give up on configure and thirdparty, which are evidently a layer that will need to be
revisited later, and just use plain old 'pip3 install --editable .' 
(you may need to read up a lot on python development, e.g.
https://pip.pypa.io/en/latest/reference/pip_install/#editable-installs )
9) Observe the error
```
Collecting py2-ipaddress<3.5,>=2.0 (from scancode-toolkit===3.0.2)
  Downloading https://files.pythonhosted.org/packages/06/f2/ff20f2d2fd4757be329c8ecb81e9e7fa3bec0b65445821e3a575410cf194/py2-ipaddress-3.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    py2-ipaddress: For Python 3.x, please use the official ipaddress module.
```
10) Fix by editing setup.py to refer to ipaddress (with no version spec for now) instead of py2-ipaddress
11) Rerun 'pip3 install --editable .'
12) Observe next error:
```
Collecting extractcode-libarchive (from scancode-toolkit===3.0.2)
  Could not find a version that satisfies the requirement extractcode-libarchive (from scancode-toolkit===3.0.2) (from versions: )
```
13) Fix by simply removing the version specifier on extractcode-libarchive in setup.py for now
14) Rerun 'pip3 install --editable .'
15) Observe next error:
16) etc etc.

Good luck!

**Comment by utkarshg99** [comment]
@pombredanne @majurg I have read the entire conversation above and have also found out that this topic is included as one of the project ideas for GSoC'19. I am quite interested on working on this. I have read the python 2 to python 3 porting guide and have a knowledge of both versions of python. Can you tell me from where should I start working on this issue?

**Comment by dankegel** [comment]
If https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-469076254 is not enough of a hint for how to start, it might not be the project for you.

**Comment by pombredanne** [comment]
@dankegel Thank you ++ for https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-469076254 ... We are thinking alike there exactly. :bowing_man:

**Comment by Abhishek-Dev09** [comment]
I already have done all this But i need these dependencies 'extractcode-libarchive', 'extractcode-7z', 'typecode-libmagic', that supports python3.

**Comment by Abhishek-Dev09** [comment]
> Here's one possible path:
> 
> 1. Install ubuntu 16.04 (possibly using docker or lxc or virtualbox instead of a real machine) (because many people need to use scancode on ubuntu 16.04, which will be in common use in conservative companies for many years)
> 2. sudo apt-get remove python2.7
> 3. sudo apt-get install python3 python3-pip build-essential
> 4. Follow https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst
>    but before running configure, edit it to change python2.7 to python3
> 5. Run it and observe the failure:
> 
> ```
> ubuntu@demo-ubu1604:~/scancode-toolkit$ ./configure
> ...
>   Could not find a version that satisfies the requirement nltk<4.0,>=3.2 (from scancode-toolkit==3.0.2->-r /home/ubuntu/scancode-toolkit/etc/conf/base.txt (line 10)) (from versions: )
> No matching distribution found for nltk<4.0,>=3.2 (from scancode-toolkit==3.0.2->-r /home/ubuntu/scancode-toolkit/etc/conf/base.txt (line 10))
> 
> Failed to execute command:
> pip install --upgrade --no-index --no-cache-dir --find-links="/home/ubuntu/scancode-toolkit/thirdparty" -r "/home/ubuntu/scancode-toolkit/etc/conf/base.txt". Aborting...
> ```
> 1. Read configure and etc/configure.py
> 2. Realize that it refers to bundled python2 versions of everything
> 3. Give up on configure and thirdparty, which are evidently a layer that will need to be
>    revisited later, and just use plain old 'pip3 install --editable .'
>    (you may need to read up a lot on python development, e.g.
>    https://pip.pypa.io/en/latest/reference/pip_install/#editable-installs )
> 4. Observe the error
> 
> ```
> Collecting py2-ipaddress<3.5,>=2.0 (from scancode-toolkit===3.0.2)
>   Downloading https://files.pythonhosted.org/packages/06/f2/ff20f2d2fd4757be329c8ecb81e9e7fa3bec0b65445821e3a575410cf194/py2-ipaddress-3.4.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     py2-ipaddress: For Python 3.x, please use the official ipaddress module.
> ```
> 1. Fix by editing setup.py to refer to ipaddress (with no version spec for now) instead of py2-ipaddress
> 2. Rerun 'pip3 install --editable .'
> 3. Observe next error:
> 
> ```
> Collecting extractcode-libarchive (from scancode-toolkit===3.0.2)
>   Could not find a version that satisfies the requirement extractcode-libarchive (from scancode-toolkit===3.0.2) (from versions: )
> ```
> 1. Fix by simply removing the version specifier on extractcode-libarchive in setup.py for now
> 2. Rerun 'pip3 install --editable .'
> 3. Observe next error:
> 4. etc etc.
> 5. once it all installs, get the tests to pass
> 
> Good luck! I'm not involved in scancode development except as a grateful (and occasionally irate) user, nor am I involved in GSOC anymore, but I suspect getting some way down that path would improve your chances at having your proposal accepted.
> 
> If your initial changes are suitable for landing on current master and work with both python2 and 3 (see https://setuptools.readthedocs.io/en/latest/python3.html perhaps) and are accepted before you submit your proposal, so much the better. (Even though python2 compatibility will probably be dropped once it's working with python3, a gradual transition which supports python2 while the python3 port is proceeding might not be a bad thing.) But that's just me; the scancode maintainers may feel differently.

We can't do these things on mojave. As mojave is unix-like os.

**Comment by pombredanne** [comment]
@Abhishek-Dev09 re

> I already have done all this 

It would be good to have a PR even if this work in progress such that this can be discussed and commented 

> But i need these dependencies 'extractcode-libarchive', 'extractcode-7z', 'typecode-libmagic', that supports python3.I have wheel file of these dependencies but it supports only python 2.So please help in getting this .whl file.

The natives are built from [sources](https://github.com/nexB/scancode-thirdparty-src)  ... and copied to their respective [/plugins](https://github.com/nexB/scancode-toolkit/tree/develop/plugins) and then assembled from there [too](https://github.com/nexB/scancode-toolkit/tree/develop/plugins) as proper wheels using a dedicated [build script](https://github.com/nexB/scancode-toolkit/blob/develop/etc/release/build-plugins.sh)  

Now most of these should not be Python-version specific... the fact the wheels are tagged Python 2 only is a safety or a mistake. Each plugin may need a setup.cfg universal tag eg.
```
[bdist_wheel]
universal = 1
```

That's not easy... that's why this is a project!

> We can't do these things on mojave. As mojave is unix-like os.

What do you mean? this is rather cryptic! What is mojave and why would this be related to ScanCode Python 3 port? And if you are meaning macOS, then there is no reason that this should not work, so please be specific.

ScanCode support mac, linux and windows and the port needs to have all tests passing on all three. It might be a good idea to setup the tests and CI (Travis and Appveyor) to run with Python 3 BTW (this will fail of course for now).

**Comment by Abhishek-Dev09** [comment]
@pombredanne,Thanks for helping me.I have done it.Only type errors are left.These will also solved soon.

**Comment by pombredanne** [comment]
Note: the port from 2 to 3 has to be a gradual process where small, incremental and consistent changes that work on both Python versions are pushed, reviewed and merged on a regular basis and therefore work on both Python 2 and Python3 for quite a while.
I will NOT accept any kind of massive PR that upgrades everything from 2 to 3 at once, that would be a complete waste of time.

**Comment by Abhishek-Dev09** [comment]
@pombredanne :You mean to say that our code is compatible with both version 2 & 3.

**Comment by pombredanne** [comment]
@pombredanne for a while and until the bulk or all of the port is completed yes. At some point we will drop 2 and branch it out for maintenance, but not immediately.

**Comment by Abhishek-Dev09** [comment]
@pombredanne @dankegel @majurg :Its a my way:
Step1)Remove version py2.7 if installed.And install latest version of python.
Step2)Edit configure and configure.bat and make compatible with py3.
Step3)Follow https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst
Step4)Run it and observe the failure with nltk.
It means that our dependencies is not compatible with py3. So our first goal is to ensure all deps are compatible with py3.
Check all wheel of third party ,pombredanne has already done for us(http://dl.bintray.com/pombreda/thirdparty/). If does not exist we create whl file  or downloaded on pypi. He has guided us how to create wheel file on https://github.com/pombreda/thirdparty-manylinux/ and https://github.com/pombreda/thirdparty .
Step5)After solving all deps, Use AutoPEP8 to make the code comply with PEP8 style guide which will also help with the porting.
Step6)Use 2to3 to make the code Python 3 compatible.
Step7)Run again you find so many type errors, solve one at a time after each run.
Step8)After that You find no errors, Configuring  completed.
Above method is verfied by me.It works you can see http://dpaste.com/2XX0PDA

**Comment by Abhishek-Dev09** [comment]
@pombredanne- Any recommendation you want to prefer? Is i am moving in right direction?

**Comment by dankegel** [comment]
Start small.  Please submit a merge request that fixes one python 3 error in the body of scancode (not its setup scripts or thirdparty directory) and does not break existing code with python 2.7.

**Comment by Abhishek-Dev09** [comment]
@dankegel-Is my approach is correct?But you also earlier recommended like this only.Without solving dependencies, how  can we proceed?We have to edit the script to add support the py3.6+.

**Comment by dankegel** [comment]
In https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-469076254 I advocated for bypassing the thirdparty directory and configure.py by using traditional ```pip install --editable .```
I still feel that's the way to go, since it's more convenient, and thirdparty and configure.py are ephemeral and can be tackled later with no loss of generality or efficiency in development.

**Comment by Abhishek-Dev09** [comment]
@dankegel -As i have solve all dependencies via requirement.txt. It automatically solve all problems related to third party.Nothing we have to do.

**Comment by dankegel** [comment]
Why do you say setup.py does not need any changes?  It clearly doesn't work with python3 yet.

If ```$ pip install --editable .``` doesn't work with python 3, something's wrong, and needs fixing.

**Comment by Abhishek-Dev09** [comment]
But i am working on py3.7.1. I have got no error.

**Comment by dankegel** [comment]
Well, then, send in an MR that just gets ```$ pip3 install --editable .``` to succeed, and I'll try it out.  Happy to learn.

**Comment by Abhishek-Dev09** [comment]
What do you mean by  MR?You want to say that install individual third party by pip3 install.But  you there is so many deps. Through requirement.txt   you eliminate errors in one flow.
Requirement.txt is better than install requires.
https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by dankegel** [comment]
Oh, sorry, MR = merge request.  It's what some systems call PR = pull request.

I'm not saying to install individual third party dependencies one at a time.  On a fresh system,
you should be able to do 
```
$ pip3 --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)
$ git clone git@github.com:nexB/scancode-toolkit.git
$ cd scancode-toolkit
$ pip3 install --editable .
```
and have it succeed.  This should pull in all the dependencies automatically.

Currently it fails with 
```
    py2-ipaddress: For Python 3.x, please use the official ipaddress module.
```

Please submit a pull request that makes the above few commands succeed with python 3.5+.

**Comment by Abhishek-Dev09** [comment]
ABHISHEKs-MacBook-Air:~ abhi$ cd desktop
ABHISHEKs-MacBook-Air:desktop abhi$ cd scancode-toolkit
ABHISHEKs-MacBook-Air:scancode-toolkit abhi$ pip3 --version
pip 19.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
ABHISHEKs-MacBook-Air:scancode-toolkit abhi$ pip3 install --editable
Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...
--editable option requires 1 argument
Why  i can't proceed with requirement.txt.There is any drawback of using it.

**Comment by dankegel** [comment]
You forgot to specify the argument to --editable, which is the current directory, .  Try pasting the command from my log exactly.

You can do whatever you like with requirements.txt, but since users expect in the end to be able to install scancode from pypy with pip3, you also have to fix the problems I'm pointing out.

I'm afraid that's my last reply on the subject for a while until you do send in that pull request I suggested, or some other useful pull request.

**Comment by Abhishek-Dev09** [comment]
@dankegel :In your way,I will getting error intbitset, pyicu
1)Failed building wheel for intbitset
2)Failed building wheel for pyicu

**Comment by dankegel** [comment]
Works fine with python 2.7, e.g.
```
$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
$ pip install --editable .
```

Your mission, should you choose to accept it, is to make ```pip3 install --editable . ``` succeed with python 3.5+ as it does with python 2.7.

If the errors you mentioned were with python3.x, then you have some work to do.

**Comment by Abhishek-Dev09** [comment]
How to fix intbitset and pyicu?

**Comment by dankegel** [comment]
No idea without knowing what your environment is and what the log says.  You may be missing some native libraries.

Did the command succeed with python2?  Get it to succeed there first.

**Comment by Abhishek-Dev09** [comment]
No ,i succeed with python 3.7.1. It showing 15 errors and 2 warning for intbitset after solving extracode libarchive.

**Comment by pombredanne** [comment]
@Abhishek-Dev09 you wrote:
> Through requirement.txt   you eliminate errors in one flow. Requirement.txt is better than install requires.
> https://packaging.python.org/discussions/install-requires-vs-requirements/

requirements is not better, it serves a different purpose. This is a "lockfile" while a setup.py is a statement of dependencies. The setup.py has versions ranges that should work and can be somewhat flexible to accommodate the widest possible usage, typically as a library. A requirements file best usage is to lock all the versions of all resolved dependencies to provide a more stable/reproducible experience.  The reproducible part of a lock file benefits is handled by bundling all deps in the `thirdparty/` dir... so there is typically no need for an extra lock file since we go much further by bundling ;)

**Comment by pombredanne** [comment]
@Abhishek-Dev09 re:
> No ,i succeed with python 3.7.1. It showing 15 errors and 2 warning for intbitset after solving extracode libarchive.

I am a bit lost... I have some difficulties to understand the path and approach you are taking for this port....do you have a proper C compiler installed on your machine? This is needed for any native dep such as `intbitset` which does install without any problems on Python 3.6.5
```
(tmp) $ python -V
Python 3.6.5
$ pip install intbitset
Collecting intbitset
  Using cached https://files.pythonhosted.org/packages/6b/02/071198144a273f8d89c28a4be8fa971b60a4d80a60bd4c8f1e9d7223d296/intbitset-2.3.0.tar.gz
Collecting six (from intbitset)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Building wheels for collected packages: intbitset
  Building wheel for intbitset (setup.py) ... done
  Stored in directory: /home/pombreda/.cache/pip/wheels/ba/bb/f1/a70eabb11a545817e3c40e1002ab16de37be574fecb636cb28
Successfully built intbitset
Installing collected packages: six, intbitset
Successfully installed intbitset-2.3.0 six-1.12.0
$ python
Python 3.6.5 (default, Apr 25 2018, 15:04:06) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from intbitset import intbitset
>>> intbitset(range(12))
intbitset([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
```

Also it is really hard to answer questions without much context such as when you ask `How to fix intbitset and pyicu?` ... I would appreciate if you can help us help you. A good background reading is this http://www.catb.org/esr/faqs/smart-questions.html

**Comment by Abhishek-Dev09** [comment]
@pombredanne :Please check my Pr where I am wrong in building plugins.

**Comment by HAKSOAT** [comment]
Is this available for the GSoC 2019?

**Comment by pombredanne** [comment]
@HAKSOAT it sure is. Welcome! This is listed as one of the project ideas alright on https://github.com/nexB/aboutcode/wiki/GSOC-2019 all these are "available".... and you can come with your own ideas too. But discuss them first

**Comment by dankegel** [comment]
And see https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-469076254 et seq.

**Comment by Abhishek-Dev09** [comment]
@dankegel:I doesn't understand step 13 ,you have mentioned at 
https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-469076254.Can you explain?

**Comment by dankegel** [comment]
My mistake; extractcode-libarchive is a strange beast.

I was hoping you'd be able to install that with e.g. ```pip3 install --editable plugins/extractcode-libarchive-manylinux1_x86_64```
but it appears there are circular dependencies.

The folks who packaged scancode have some 'splainin to do :-)

I think you can make progress by simply commenting out the extractcode-libarchive and extractcode-7z (and typecode-libmagic) lines in setup.py.

The next problem you might see is 
```
  ext/_yaml.c:4:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyYAML
```
which on Ubuntu one fixes with ```sudo apt install python3-dev```.

After that, ```pip3 install --editable .``` succeeds here, and ```pip3 list``` shows it's installed.

Oddly, though, ```pip3 install --editable plugins/extractcode-libarchive-manylinux1_x86_64``` still fails after that, complaining about scancode-toolkit not being installed.

Shrug.  Python packaging is beyond the ken of mortal men :-) 

Can anyone who actually understands this stuff explain?  Thanks!

**Comment by Abhishek-Dev09** [comment]
@dankegel :After removing these plugins, it is completely installed then one error found on module pyicu but I fixed that.After that its get installed.Then I ported these plugins that also throwing same error.But sometimes extractcode-7z gets installed but other two have same problems.

**Comment by pombredanne** [comment]
@dankegel  you wrote:
> I was hoping you'd be able to install that with e.g. pip3 install --editable plugins/extractcode-libarchive-manylinux1_x86_64
> but it appears there are circular dependencies.
> The folks who packaged scancode have some 'splainin to do :-)

Great catch! The install requires of the `plugins/extractcode*` and `plugins/typecode*` would need to be removed. The dep on `scancode-toolkit` makes no sense. Once this is removed, the proper plugi can be installed with a `pip -e` and the rest of the main `pip -e ` install should carry on mostly.

I have no idea why pyicu is used ... is must be a dep of dep somewhere with Py3.

**Comment by pombredanne** [comment]
As an example of a commit stream for the Python3 port see this branch https://github.com/nexB/scancode-toolkit/commits/python3-port-commits-sequence-example
(note that even some code may be worthy of being merged in this, particular I will cherry pick for sure some of the RPM code)

**Comment by Shubhambindal2017** [comment]
I am interested to solve this issue. This issue is also included in AboutCode's project idea in GSOC 2019, so should I start working on this now or wait for the GSOC period ?

**Comment by dankegel** [comment]
It's up to you, but the more familiar with the code you are, the more realistic a proposal you can make, and the sooner you can get commits in and show a draft proposal to the project; both may increase your chances of selection.

I suspect it's only worth it if you're interested in the project regardless of GSOC, but that's just my guess.

**Comment by pombredanne** [comment]
@flub suggested using a `conftest.py` local pytest plugin 
What we have here seems great:
https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option

Here is a chat log from #pylib 


* pombreda> Howdy :)  I have this problem that will need solving soon: https://github.com/nexB/scancode-toolkit is being ported to Py3. 
For that we need to continue supporting py2  also and I have ~10000 tests (many data driven) that run in a few minutes locally on a decent laptop and take ~ 2 hours on travis or appveyor. If I add tox or a matrix to run CI tests on py2 and py3 I will have a major issue: until the port will be completed most of the tests will fail on py3 and therefore these will fail the CI run/build. I need to devise a smart way way where only a few of the tests are being run on Py3, gradually as we know they are passing. Do not run them all. I wonder if anyone has faced this problem before. 
I could of course massively use @skipIf or tags manually. And it may be what's required in the end but I am sure that: we can do better! I forgot to mention that I use pytest and xdist/excnet extensively.  And that we are likely going to have a Google Summer of Code student slotted to help on port work. 
And as is often the case, laying out the problem in writing triggers ideas for solutions.
So may be I could craft a test discovery plugin that would NOT run anything if on Python 3 UNLESS the test has been marked has passing on Python3 and if the plugin is not activated, it would run on both: that way we can crawl our way through stating what is tested on Python3 and tag these, rather than the other way. And the other way (e.g. skips/tag) can be used towards the end of the port when most tests should run and pass on Py3 and only a few leftovers are problematic. By the other way, I mean skipping explicitly (and btw I also forgot to mention that ScanCode also uses pluggy for its own plugins )

* flub> pombreda: sure, tagging things as runnable and doing the skipif in conftest.py is a sane approach

* pombreda> flub, even better. Iwas stupidly considering a plugin

* flub> well, conftest.py is really a plugin - just local to your project

* pombreda> good point: flub, let me dive in to conftest.py ... I never used this so far and btw then I guess I would still use tox to run across Pythons. I assume that tox just does not care about conftest.py and leave this to py.test alright
flub, https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option seems to be all I need : thx ++
So at first we will tag which tests can run on Python3. And skip the one not tagged when on Py3.

* flub> yep, sounds reasonable.  glad the docs were helpful :)

* pombreda> then when we progress later we can invert the pattern and untag these and tag all the ones that had no tag. And then skip only the tagged ones. That switch would require some scripting to modify the test code... but since they are rather uniformly structure code-wise that should be possible (flub, the docs are great :+1) and I like the idea of a simple local conftest.py that can do some of it hackish bidding locally since this is really only for the port duration

* flub> you can also mark entire modules (and probably packages?) at once btw, which may also be useful for your case

* pombreda> flub, I will have to find out how :) and yes that will be useful as we want to progress packages by packages and module by module in many cases

**Comment by pombredanne** [comment]
See also https://docs.pytest.org/en/latest/example/markers.html#marking-whole-classes-or-modules

**Comment by qduanmu** [comment]
@pombredanne, I’m using scancode-toolkit (from command line and as library) in our project which is based on python2.7, and now we are planning to make the project python3 compatible. I could see the great progress of porting scancode-toolkit to python3(3.6+) here, could I know if there is any rough schedule/ETA for this work? Thank you.

**Comment by dankegel** [comment]
Yeah, a status report and how-to might be handy.

**Comment by pombredanne** [comment]
@Abhishek-Dev09 if you could post a status, that's in high demand :heart: !

**Comment by Abhishek-Dev09** [comment]
GSoC update- Discussion of Porting of path on different platforms through the use of path.py. 
For more details - Refer to nexB/scancode-toolkit#1637

**Comment by pombredanne** [comment]
Some status update:
- we now have one module ported: `commoncode` and this the utility module reused everywhere. yeah!
- for the next steps, we will continue module-by-module, and we could break it down with a tracking ticket for each module for sanity.
- the porting order should be:

  - plugincode
  - typecode
  - extractcode
  - textcode
  - scancode basics (some tests are integration tests and will have to wait to be ported)
  - formattedcode, starting with JSON (some tests are integration tests and will have to wait to be ported)
  - cluecode
  - licensedcode
  - packagedcode (depends on licensecode)
  - summarycode
  - fixup the remaining bits and tests

**Comment by pombredanne** [comment]
Here is a bit of status and what I think should be the remaining port order:

These modules have been ported:
- commoncode, plugincode, typecode, extractcode, textcode :+1: 
@Abhishek-Dev09  congrats for the work done so far!

The porting order for the remainder modules should be:
- cluecode
- formattedcode, starting with JSON (some tests are integration tests and will have to wait to be ported)
- scancode basics (some tests are integration tests or use licenses or packages and will have to wait to be ported until the modules are ported below: these will mean marking ported tests a a more granular level than a whole module)
- licensedcode
- packagedcode (depends on licensecode)
- summarycode
- scancode complete
- fixup the remaining bits and tests

**Comment by pombredanne** [comment]
Status update: using the develop branch we have now reached a major milestone, we have liftoff on Python 3!
I can run `scancode -clipeu samples/ --json-pp - -n4` without errors ;)

At the last status update https://github.com/nexB/scancode-toolkit/issues/295#issuecomment-520246956
we had these modules ported:
* commoncode, plugincode, typecode, extractcode, textcode

An now we have these new modules:
* cluecode, licensedcode, most of scancode and parts of packagedcode and formattedcode (JSON)

What is left todo:
 * packagedcode remainder
 * summarycode
 * scancode remainder
 * various leftovers and fixups

We are ALMOST there and you can start playing with it... to kick in the tires!
@Abhishek-Dev09 :heart: !

**Comment by pombredanne** [comment]
Status: the port to Python 3 is done!

Congrats to @Abhishek-Dev09 and everyone that helped. :heart:

**Comment by hakandilek** [comment]
Is this working or documented somewhere how to get scancode running on Python3?

I've tried running it within Docker (`python:3.8.0-slim-buster`)and get this following error:

```
* Configuring ScanCode for first use...
  ERROR: Could not find a version that satisfies the requirement future>=0.16.0 (from scancode-toolkit==3.1.1->-r /scancode/etc/conf/requirements_base.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for future>=0.16.0 (from scancode-toolkit==3.1.1->-r /scancode/etc/conf/requirements_base.txt (line 10))
Traceback (most recent call last):
  File "/scancode/etc/configure.py", line 573, in <module>
    install_3pp(configs, root_dir, thirdparty_dirs, quiet=quiet)
  File "/scancode/etc/configure.py", line 284, in install_3pp
    run_pip(requirements, root_dir, tpp_dirs, quiet)
  File "/scancode/etc/configure.py", line 310, in run_pip
    call(pcmd, root_dir)
  File "/scancode/etc/configure.py", line 137, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/scancode/bin/pip" install --upgrade --no-index --no-cache-dir --find-links="/scancode/thirdparty" -qq --requirement "/scancode/etc/conf/requirements_base.txt"' returned non-zero exit status 1.
/scancode/scancode: line 114: /scancode/bin/scancode: No such file or directory
```

BTW, it runs just fine in image `python:2.7.17-slim-buster`

**Comment by Abhishek-Dev09** [comment]
> Is this working or documented somewhere how to get scancode running on Python3?
> 
> I've tried running  it within Docker (`python:3.8.0-slim-buster`)and get this following error:

@hakandilek : Try with python 3.6.8. Till now we support upto python 3.6.8. And we are working on Python 3.7 and Python 3.8

**Comment by hakandilek** [comment]
> Try with python 3.6.8.

Thanks @Abhishek-Dev09 

I've tried with `python:3.6.9-slim-buster` and it did work.

**Comment by pombredanne** [comment]
We now support fully Python 3.6, 3.7, 3.8 and 3.9 on Linux, Windows and macOS 64 bits.
we dropped Python 2 support (available in legacy 3.x versions)
Thank you all for the efforts and @Abhishek-Dev09  in particular!
