### ISSUE TITLE
cluecode warning message on running scancode-toolkit (cli)

### ISSUE THREAD

**Issue by lf32** [nexB/scancode-toolkit#2957]
### Description
Everytime I execute `scancode` (installed using pip) I get this error message saying
```
/home/<redacted>/.local/lib/python3.10/site-packages/cluecode/copyrights.py:3382: FutureWarning: Possible set difference at position 3
  remove_tags = re.compile(
```

### How To Reproduce

Install scancode-toolkit using pip

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? **Linux**
* What version of scancode-toolkit was used to generate the scan file? **30.1.0**
* What installation method was used to install/run scancode? **pip**

**Comment by AyanSinhaMahapatra** [comment]
See #2686, this is a duplicate then?

**Comment by lf32** [comment]
looks duplicate, will close it
