### ISSUE TITLE
Dropping support for Linux 32 bits

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#297]
This is really starting to become old and is not even having its test run on each build. 

@K-rex you had reported #33 and we had added support last year for you. This means that you will have to either use older versions going forward or recompile the native code yourself. 

I will add instructions for this. Note I may be able to keep older versions around for 32 bits but the effort is not worth it IMHO. 

Feedback?, questions?

**Comment by pombredanne** [comment]
@K-rex ... I guess you are no longer interested. Since I have not received further interest for Linux 32 bits, I will discontinue support for it unless I have a few requests. for this. 32 bits is on its way out!

**Comment by K-Rex** [comment]
Sorry for my lately reply. We have the holiday in my country. Thanks you for your help last year. Maybe the older version in 32 bits is enough for me.
