### ISSUE TITLE
Silence noisy warnings for pyicu

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2990]
See this when running SCTK latest develop:
``
scancode-toolkit-master/venv/lib/python3.6/site-packages/fingerprints/cleanup.py:54: ICUWarning: Install 'pyicu' for better text transliteration.
  text = ascii_text(text)
``

**Comment by pombredanne** [comment]
Not seen anymore as reported by @AyanSinhaMahapatra ... moving to later and lower priority

**Comment by AyanSinhaMahapatra** [comment]
This is fixed and not seen anymore, closing.

**Comment by AyanSinhaMahapatra** [comment]
I saw this again, this is happening when we use the `--summary` option due to the use of `fingerprints.generate` in the `src/summarycode/summarizer.py`. 

See https://github.com/nexB/scancode-toolkit/issues/3016#issuecomment-1397144996

**Comment by rritik772** [comment]
hey, I am new to contributing. So, I need a little bit of help.

I have done some research and came to conclusion that the warning is generated by library `Normality` which is used in `Fingerprints` and it is [here](https://github.com/pudo/normality/blob/17c8e141d5382be8e3f097b25914079b28fc7cbf/normality/transliteration.py#L68).

Also I have different solution based on it.
1. Using `warnings.simplefilter("ignore")` it will filter and ignore all the warnings
2. Using ```with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=ICUWarning)``` this will ignore all the ICUwarning
3. Using `warnings.simplefilter("ignore", ICUWarning)` in global scope of summary

What should I do.

Also can you please assign this issue to me.
