### ISSUE TITLE
scan won't run if extract option is set

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#3]
OS: Windows 7 - 64bits
Python 2.7
scancode version: 1.0.0

I've an sample archive that I want to extract and run scan on it. I have the `--format html-app` set follow by the `-e` option which is the extract.
However, the tool only did the extraction without running the scan.

Following are the command that I used:
```
(scancode-toolkit-1.0.0) C:\Users\Downloads\scancode-toolkit-1.0.0>scancode --format html-app -e C:\Users\Downloads\test\ C:\Users\Downloads\test.html
Extracting archives...
Extracting done.
(scancode-toolkit-1.0.0) C:\Users\Downloads\scancode-toolkit-1.0.0>
```

**Comment by pombredanne** [comment]
This is the expected behaviour for now until we have improved the extraction such that it runs transparently.

For now the command line help text says:
>   -e, --extract         Extract archives found in <input> recursively, ignoring other options.

I think we can make this more explicit ... and of course implement extract + scan at once

**Comment by pombredanne** [comment]
@chinyeungli I suggest this in the short term?
```
Extracting archives... All other scan options are ignored...
Extracting done.
```
Would this make sense?

**Comment by chinyeungli** [comment]
It makes sense.
Or another option is to stop and prompt a message to user when the user have extraction and other options set. The tool will then tell the user that other options cannot be run together with the extraction option set.
Just an idea.

**Comment by pombredanne** [comment]
@chinyeungli so you thing rejecting incompatible options is a better approach? I kinda like that too

**Comment by chinyeungli** [comment]
I think so.. 
User may expect to extract and get the scan result when the tool is launched. However, when the user come back, only the extraction is completed and no scan was performed. The user will need to re-run the tool. It may waste the user time especially if run on a large project.

**Comment by pombredanne** [comment]
The latest code now rejects incompatible options.

**Comment by pombredanne** [comment]
The latest develop code now has a separate extractcode command for extraction. I am closing this ticket for now.
