### ISSUE TITLE
Please provide support for OWASP Cyclone DX format 

### ISSUE THREAD

**Issue by usmankhanisb** [nexB/scancode-toolkit#3007]
## Short Description
The Scancode features can further help us in security or supply chain security. I request a feature which support generation of SBOM files in Cyclone dx and SPDX format. This can be used to secure software from inherent vulnerabilities and secure supply chain of software. 

## Possible Labels

- new feature

## Select Category

-  [ ] Enhancement

-  [ ] Scan Feature

**Comment by Jeeppler** [comment]
@usmankhanisb CycloneDx is already supported: https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/output-format.html#all-scan-output-options

@pombredanne I think this issue can be closed.

**Comment by AyanSinhaMahapatra** [comment]
@Jeeppler yes, closing this. We have a follow up issue to improve the cyclonedx output option at https://github.com/nexB/scancode-toolkit/issues/2987 btw also.
