### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#301]
This is the right things to do to set proper expectations: http://contributor-covenant.org/ is the way to go

**Comment by inishchith** [comment]
@pombredanne I think i can work on this issue . any pointers ?

**Comment by inishchith** [comment]
@pombredanne I've read through the reference and opened a PR . i think after getting it merged i can open a PR at [covenant.org repo](https://github.com/ContributorCovenant/contributor_covenant) . ping

**Comment by pombredanne** [comment]
This has been merged and is done now
