### ISSUE TITLE
DOS/32 Advanced DOS Extender Software License (4 clause BSD/Apache 1.1 hybrid)

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#3019]
### Description

A possibly interesting BSD variant:

https://github.com/open-watcom/open-watcom-v2/blob/master/bld/redist/dos32a/license.d32
https://dos32a.narechk.net/content/license.html

It is a lot like a 4 clause BSD license, except it uses some different wording lifted from Apache 1.1:

```
3. The end-user documentation included with the redistribution, if any,
must include the following acknowledgment:
```

Section 4 might also be derived from Apache 1.1 (section 5):

```
4.  Products derived from this software  may not be called "DOS/32A" or
"DOS/32 Advanced".
```

**Comment by pombredanne** [comment]
Would you consider this a permissive license?

**Comment by DennisClark** [comment]
yes

**Comment by DennisClark** [comment]
see https://scancode-licensedb.aboutcode.org/dos32a-extender.html
