### ISSUE TITLE
Add new argument `package_adder` to `DatafileHandler.assemble()`

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#3034]
We want to reuse the code from the `assembly()` method of the different `PackageHandler`s in scancode.io, and the current method of associating Packages to Resources (in the `assembly()` methods), where we append `package_uid` to `resource.for_packages`,  does not work there. We need to be able to pass in a function that performs the Package - Resource association, so we can use the `assembly()` methods in different contexts.

The `package_adder` argument is a function that takes in a `package_uid`, `resource`, and `codebase`. It is used in places where we want to associate a Resource to a Package using the `package_uid`.

**Comment by AyanSinhaMahapatra** [comment]
This was added with https://github.com/nexB/scancode-toolkit/pull/3035, closing!
Thanks @JonoYang!
