### ISSUE TITLE
Detect new NuGet license URLs with expressions

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3037]
Following discussions in https://github.com/nexB/scancode-toolkit/issues/2877 there is service: https://docs.microsoft.com/en-us/nuget/nuget-org/licenses.nuget.org
Therefore we can have SPDX expressions of this shape `https://licenses.nuget.org/(LGPL-2.0-only WITH FLTK-exception OR Apache-2.0+)`

We should extend the matcher used to detect SPDX license identifiers to suppoty this

**Comment by AyanSinhaMahapatra** [comment]
This is finished in #2961

**Comment by AyanSinhaMahapatra** [comment]
Closing this!
