### ISSUE TITLE
Consider CLA's as license clues? 

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#3038]
We have Contributor License agreements as licenses/rules in scancode and we should consider if we report these instead as `license_clues` instead of adding them in `license_detections` proper.

The steps discussed related to this are:

1. decide on a case by case basis if some CLA's are more like proper license detections or they are license clues.
2. if a CLA is decided as a license clue, add `is_clue` as True for the corresponding rules for that CLA
3. break rules containing CLA's and other proper license expressions such that all CLA rules are standalone.
4. report license matches to CLA's in `license_clues`

We also have detections of CLAs [here](https://github.com/nexB/scancode-toolkit/issues/2878#issuecomment-1054006455) in the license report contributed by Porsche AG OSO w.r.t discussion in ORT community meeting on scancode false positives. 

Also see #2877 for the discussion of adding `is_clue` flag to rules, w.r.t different cases.

These are some CLAs in scancode licenses:

(Have to decide which of these are clues or not)

`is_clue` | license_key | short_name | name
-- | -- | -- | --
True | dco-1.1 | DCO 1.1 | Developer Certificate of Origin 1.1
True | dgraph-cla | Dgraph Community License Agreement | Dgraph Community License Agreement
True | generic-cla | Generic CLA | Prior Generic Contributor License Agreement
True | isotope-cla | Isotope Commercial License Agreement | Isotope Commercial License Agreement
True | jetty-ccla-1.1 | Jetty CCLA 1.1 | Jetty Project Corporate Contributor License Agreement V1.1
True | newton-king-cla | Newton-King CLA | James Newton-King CLA
True | owf-cla-1.0-copyright-patent | OWF CLA 1.0 - Copyright and Patent | OWF Contributor License Agreement 1.0 - Copyright and Patent
True | owf-cla-1.0-copyright | OWF CLA 1.0 - Copyright | OWF Contributor License Agreement 1.0 - Copyright

**Comment by AyanSinhaMahapatra** [comment]
These are some CLAs in scancode licenses:

(Have to decide which of these are clues or not)

`is_clue` | license_key | short_name | name
-- | -- | -- | --
True | dco-1.1 | DCO 1.1 | Developer Certificate of Origin 1.1
True | dgraph-cla | Dgraph Community License Agreement | Dgraph Community License Agreement
True | generic-cla | Generic CLA | Prior Generic Contributor License Agreement
True | isotope-cla | Isotope Commercial License Agreement | Isotope Commercial License Agreement
True | jetty-ccla-1.1 | Jetty CCLA 1.1 | Jetty Project Corporate Contributor License Agreement V1.1
True | newton-king-cla | Newton-King CLA | James Newton-King CLA
True | owf-cla-1.0-copyright-patent | OWF CLA 1.0 - Copyright and Patent | OWF Contributor License Agreement 1.0 - Copyright and Patent
True | owf-cla-1.0-copyright | OWF CLA 1.0 - Copyright | OWF Contributor License Agreement 1.0 - Copyright

**Comment by DennisClark** [comment]
Most of these items are not really software "licenses" but Contributor License Agreements (CLA's) that describe the allowed or required licensing that any contributor should assign to a code contribution.  There are two items in the list that are not CLA's but rather proper licenses: 

dgraph-cla | Dgraph Community License Agreement
is a "Source-available" license (note that this category is not open source). 

isotope-cla | Isotope Commercial License Agreement
is a "Commercial" license. 

So the other items are certainly important useful information (basically "key files" or "notices") about a software project, but do not really identify the license-expression that should apply to that project. @AyanSinhaMahapatra   I will let you and @pombredanne  determine the best way to handle them; your proposed solution looks fine to me.

**Comment by DennisClark** [comment]
we are now treating CLA's as another category of license and we return them in license expressions
