### ISSUE TITLE
ScanCode incorrectly identifies BSD-3-Clause text as proprietary license

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#3039]
### Description

I ran ScanCode 31.0.0rc1 on the Fedora source package for webkit2gtk3-2.36.5. The license text in one file, which appears to be identical or substantially identical to this Webkit source file:
https://github.com/WebKit/WebKit/blob/main/Source/cmake/DetectSSE2.cmake
was incorrectly identified as "proprietary-license" by ScanCode, with the score 90.99, for reasons that are unclear to me. 
The "matched-rule" is "proprietary-license_501.RULE".

### System configuration

* What OS are you running on? (Windows/MacOS/Linux) Linux
* What version of scancode-toolkit was used to generate the scan file? 31.0.0rc1
* What installation method was used to install/run scancode? (pip/source download/other)
I used the Linux release archive for the stated version of scancode-toolkit.

**Comment by pombredanne** [comment]
@richardfontana Thank you ++ for the report!

**Comment by pombredanne** [comment]
See https://github.com/nexB/scancode-toolkit/pull/3041 for a likely fix

**Comment by pombredanne** [comment]
@richardfontana this fix works and has been merged and will be in the next release.
Thanks!
