### ISSUE TITLE
new license: BigScience RAIL license v1.0

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#3052]
### Description

https://huggingface.co/spaces/bigscience/license

is a new license for AI models. It can be best qualified as an "ethical license".

**Comment by pombredanne** [comment]
@armijnhemel Thanks!

**Comment by pombredanne** [comment]
@DennisClark FYI

**Comment by pombredanne** [comment]
@DennisClark See also this list from @LeChasseur https://github.com/LeChasseur/ifrOSS/blob/master/EthicalLicenses.md

**Comment by pombredanne** [comment]
We now have https://scancode-licensedb.aboutcode.org/bigscience-open-rail-m.html and https://scancode-licensedb.aboutcode.org/bigscience-rail-1.0.html
Thanks!
