### ISSUE TITLE
Scancode toolkit not running on Apple silicon (M1)

### ISSUE THREAD

**Issue by OmkarPh** [nexB/scancode-toolkit#3061]
### Description
I downloaded archives from the latest release [here](https://github.com/nexB/scancode-toolkit/releases/tag/v31.0.1)
Unzipped the archive, and then tried `./scancode --help` but it's giving these errors.
Tried on the normal terminal as well as terminal using rosetta
![image](https://user-images.githubusercontent.com/48476025/185976333-dd53dd6d-969b-4941-a6d2-b7d0902a4421.png)

Error on rosetta terminal:
![image](https://user-images.githubusercontent.com/48476025/185976389-738de603-a9e8-488b-a684-7ccfb0c0e2c7.png)

### How To Reproduce
- Download latest [scancode-toolkit](https://github.com/nexB/scancode-toolkit/releases/tag/v31.0.1)
- Unzip the archive
- Go to the unzipped directory & run `./scancode --help`

### System configuration
* MacOS - Monterey 12.5
* MacBook Air (M1, 2020)
* scancode-toolkit version - v31.0.1
* installation method - Downloaded archive from release section

**Comment by OmkarPh** [comment]
@pombredanne @AyanSinhaMahapatra ^^

**Comment by pombredanne** [comment]
I could not reproduce.... can you confirm that you used exactly this:
- download https://github.com/nexB/scancode-toolkit/releases/download/v31.0.1/scancode-toolkit-v31.0.1_py3.8-macos.tar.gz
- in a terminal `tar -xf scancode-toolkit-v31.0.1_py3.8-macos.tar.gz` and cd to the directory and run scancode?

**Comment by pombredanne** [comment]
Also do you have `python3`?
IF you run `python3` in a terminal, what shows up?

**Comment by OmkarPh** [comment]
yes, I tried that again, and still the same error:
![image](https://user-images.githubusercontent.com/48476025/186652320-c4562a97-6147-499c-b6fb-db05504c978b.png)

**Comment by robinsandhu** [comment]
I cannot reproduce the bug either.

System details:

<img width="981" alt="Screenshot 2022-09-04 at 9 31 06 PM" src="https://user-images.githubusercontent.com/40196431/188322617-6142edca-c712-4232-829f-2d3a10bd4114.png">

**Comment by pombredanne** [comment]
@robinsandhu Thank you ++ for checking!
@OmkarPh You have Python 3.9 rather than the default stock Python 3.8

**Comment by OmkarPh** [comment]
I had an arm-only python installed on my machine, that was the issue
@pombredanne & I discussed and tried with a universal python install and it worked fine, 
Specifically, i tried this version - https://www.python.org/downloads/release/python-3913/
![image](https://user-images.githubusercontent.com/48476025/188659250-caac9204-5c0a-40d1-807d-636f900b1b2f.png)

**Comment by pombredanne** [comment]
Thanks! that was a bit of an head scratcher for sure... Glad we could find a way to fix this
