### ISSUE TITLE
InvalidRule: Inconsistent rule text for: cc0-1.0_176.RULE

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-toolkit#3067]
### Description

"InvalidRule: Inconsistent rule text for: cc0-1.0_176.RULE" while scanning `_codecs_jp.cpython-38-x86_64-linux-gnu.so` file from `docker://python:3.8-slim-buster`.

### How To Reproduce

[_codecs_jp.cpython-38-x86_64-linux-gnu.so.zip](https://github.com/nexB/scancode-toolkit/files/9422726/_codecs_jp.cpython-38-x86_64-linux-gnu.so.zip)

```
$ pip install scancode-toolkit==31.0.2
$ scancode --license _codecs_jp.cpython-38-x86_64-linux-gnu.so --json -
```

```
Some files failed to scan properly:
Path: _codecs_jp.cpython-38-x86_64-linux-gnu.so
```

### System configuration

* What version of scancode-toolkit was used to generate the scan file? -> 31.0.2

**Comment by tdruez** [comment]
Encounter the same issue on various rules while scanning `docker://docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2`

Inconsistent rule text for: 
- `gpl-3.0-plus_28.RULE`
- `lgpl-2.0-plus_68.RULE`
- `gpl-2.0-plus_bare_single_word.RULE`
- `gpl-3.0_357.RULE`
- `mpl-2.0_21.RULE`
- `gpl-3.0-plus_28.RULE`
- `gpl_bare_word_only.RULE`

Problematic files:
- `usr/sbin/install-info`
- `var/lib/rpm/Basenames`
- `var/lib/rpm/__db.003`
- `var/lib/rpm/Dirnames`
- `var/lib/rpm/Name`
- `var/lib/rpm/Packages`
- `var/lib/rpm/Providename`
- `var/lib/rpm/Requirename`
- `usr/share/elasticsearch/jdk/jmods/java.base.jmod`
- `usr/share/elasticsearch/modules/ingest-geoip/GeoLite2-City.mmdb`

**Comment by pombredanne** [comment]
Thanks... That's a major one. We are on it. 
This is related to https://github.com/nexB/scancode-toolkit/issues/3044 that I thought was only a "nice to have"

**Comment by pombredanne** [comment]
This has been merged and released. Thanks for the report!
