### ISSUE TITLE
Provide an "ambiguity_clue" field to support the setting of ambiguous_compound_licensing

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3075]
When the summary option is requested, SCTK provides some high-level information including a license_clarity_score in the scan results.  One of the summary fields is `ambiguous_compound_licensing` which is set to true or false, and is defined as 

"Indicates that the software has a license declaration that makes it difficult to construct a reliable license expression, such as in the case of multiple licenses where the conjunctive versus disjunctive relationship is not well defined. Scoring Weight = -10" 

This is a very useful indicator, but it would be even more useful if the scan results would include any text that caused this `ambiguous_compound_licensing` indicator to be set to true.  A typical example would be a notice text referring to a "dual" license, since that term is often used loosely in actual practice, and may refer to either a conjunctive or disjunctive situation.  By providing the exact text that was detected, someone reading the scan results can more easily determine the actual licensing terms more precisely. 

Suggested field name is `ambiguity_clue` but that is just a suggestion.

**Comment by JonoYang** [comment]
I'm closing the ticket for now as it may be unfeasible to report the specific places where the license ambiguity happens. Scancode has no awareness of the context and cannot determine if one license is more of a problem than another. The best we can do is to say that there is a license ambiguity detected in the key files and to show what licenses were detected.

I think that the idea of pointing out license issues and making suggestions for them is worth revisiting.
