### ISSUE TITLE
Incorrect purl type for cocoapods

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3081]
### Description

https://github.com/nexB/scancode-toolkit/blob/9c0f4ccca5cfc9cb79168dc888412c7246a2418d/src/packagedcode/cocoapods.py#L197 has "pods" as a purl type for cocoapods.
It should be "cocoapods" instead https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#cocoapods

**Comment by AyanSinhaMahapatra** [comment]
Merged and released, closing this.
