### ISSUE TITLE
The contents of the analyzed file are output.

### ISSUE THREAD

**Issue by soimkim** [nexB/scancode-toolkit#3084]
### Description
When analysis is executed, the contents of the analyzed file are output.

`$ scancode --json-pp - --license --copyright display-webos`
![image](https://user-images.githubusercontent.com/4284712/188035217-a561ee87-bd84-4ed0-b883-8dc7dee0e0d0.png)

### How To Reproduce

> Tell us how to reproduce the issue. 
1. Unzip the file.  (File Source: https://www.npmjs.com/package/@signageos/display-webos)
[display-webos.tar.gz](https://github.com/nexB/scancode-toolkit/files/9474090/display-webos.tar.gz)
2. Run scancode. `$ scancode --json-pp - --license --copyright display-webos`
3. The contents of the analyzed file are output as in the capture attached above.

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Ubuntu 20.04
* What version of scancode-toolkit was used to generate the scan file? scancode-toolkit==31.1.0
* What installation method was used to install/run scancode? pip install scancode-toolkit

**Comment by pombredanne** [comment]
Thanks for the report. The attached tarball is empty... is this for https://registry.npmjs.org/@signageos/display-webos/-/display-webos-2.3.0-beta.1.tgz ?

**Comment by pombredanne** [comment]
Actually never mind... that's tracing flags that I forgot to turn off..
I am pushing a new release ASAP!
Thank you ++ for the report :bow:

**Comment by soimkim** [comment]
Thank you! File upload was blocked. 😢

**Comment by pombredanne** [comment]
You can only upload zip files in issues . Tarballs need to be further wrapped in a zip. Weird... but that's their way.

**Comment by pombredanne** [comment]
This has been fixed and released in v31.1.1
Thank you ++
