### ISSUE TITLE
Latest scancode-toolkit not building on SLES 15 SP4.

### ISSUE THREAD

**Issue by gk4delltech** [nexB/scancode-toolkit#3094]
The latest scancode-toolkit is not building on SLES 15 SP4.   I could build a month ago, but not now.   We cannot seem to resolve the dependencies.

sudo zypper install -y python3-devel git-core
sudo pip install --upgrade pip setuptools wheel ftfy jaraco-functools commoncode plugincode debian-inspector importlib-metadata jinja2 zipp markupsafe requests click
mkdir ~/source
cd ~/source
git clone https://github.com/nexB/scancode-toolkit.git
cd scancode-toolkit
git checkout develop
./configure
source venv/bin/activate
sudo pip install scancode-toolkit
which scancode

**Comment by pombredanne** [comment]
@gk4delltech Would you have a log of the errors and some details on your configuration so it could be reproduced? 

How would one be able to reproduce this? Can a container be used for this?

What is the OS/architecture you have used and which Python version?

Some notes:
- `sudo pip install ` may not be the best way to install as you would mix it other installations? I would prefer using an isolated virtualenv
- you seem to install from a checkout and then a pip installation on top?
- why do you first install scancode dependencies and then scancode afterwards?

**Comment by gk4delltech** [comment]
I've tried following the venv way and also with packages installed on the system.

**Comment by gk4delltech** [comment]
[scancode-install.log](https://github.com/nexB/scancode-toolkit/files/9499706/scancode-install.log)

**Comment by gk4delltech** [comment]
Please disregard.   User error.

**Comment by pombredanne** [comment]
@gk4delltech no problem. If you experience any issue with building on openSUSE, please report and we will try to help.
Note that we could also add a container-based smoke test to make sure things work in all cases?
