### ISSUE TITLE
Build RPMs for scancode

### ISSUE THREAD

**Issue by gk4delltech** [nexB/scancode-toolkit#3095]
The LSB and ISO Linux was the genisis of the Linux Foundation.   The scancode-toolkit needs to live up to the LF standards of portability.   Either [fix to build](https://github.com/nexB/scancode-toolkit/issues/3094) or offer noarch RPMs.

**Comment by pombredanne** [comment]
@gk4delltech Thanks for the report! Do you think you can help contribute RPMs?

**Comment by pombredanne** [comment]
BTW, I am note sure that scancode "is anti ISO Linux (ie., LSB)" in anyway shape or form I can fathom! ;)

**Comment by gk4delltech** [comment]
The SPDX workgroup should have a build farm and CI/CD to do this.

**Comment by pombredanne** [comment]
@gk4delltech 

>The SPDX workgroup should have a build farm and CI/CD to do this.

I am pretty sure the SPDX workgroup has no such build farm; but even if it did and assuming we could get access to it ( ScanCode is an independent project from SPDX), there is still quite a bit of work that would be required to create, build and test packages on various Linux distros than just having a build farm. This is a lot of work from my personal experience, especially to get all the dependencies packaged as RPMs. Debian folks have chipped in to help there to get everything on Debian and this is not done yet..

Note that there is a super outdated RPM specfile in https://github.com/nexB/scancode-toolkit/blob/develop/etc/build/scancode-toolkit.spec and it would need lots of love too IMHO.

**Comment by pombredanne** [comment]
Let me reopen this. We still need RPMs alright!
