### ISSUE TITLE
elastic-license-v2 duplicate of Elastic-2.0

### ISSUE THREAD

**Issue by hanna-modica** [nexB/scancode-toolkit#3097]
### Description

The license under the licenseref [elastic-license-v2](https://github.com/nexB/scancode-toolkit/blob/24aae228fa0d06059a59c9748f9d366850a8d47a/src/licensedcode/data/licenses/elastic-license-v2.yml) is a duplicate of [Elastic-2.0](https://spdx.org/licenses/Elastic-2.0.html). If the license is present, both license refs are reported by ScanCode

### How To Reproduce

Scan a recent version of elasticsearch. In our case we scanned [v.7.17.1](https://github.com/elastic/elasticsearch/tree/v7.17.1)

### System configuration

* Linux
* OSS Review Toolkit
* ScanCode Toolkit v.30.1.0

**Comment by pombredanne** [comment]
Thanks for the report. For background, our elastic license predates the addition in SPDX and the latest update from Feb. 7th adopted the SPDX id  in https://github.com/nexB/scancode-toolkit/commit/2debf40ea5981fd8201a636f68d30bd4df9438db 

Do you have an example of a specific file path with the issue?
Did you try it with the latest ScanCode toolkit 31.x?

**Comment by hanna-modica** [comment]
Hi @pombredanne,

we did not try with ScanCode Toolkit 31.x. Seeing the commit you posted I believe, this issue should be fixed by upgrading the ScanCode-Version in ORT.
Thank you for the hint. This ticket can be closed from my perspective.

**Comment by pombredanne** [comment]
Thanks for checking!
