### ISSUE TITLE
Unable to deploy post-scan plugins - unreachable documentation links (404)

### ISSUE THREAD

**Issue by ekidonatan** [nexB/scancode-toolkit#3103]
I'm currently working on deploying a postscan plugin as instructed by the ScanCode-Toolkit's [postscan plugin documentation](https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_add_a_post_scan_plugin.html#how-to-add-post-scan-plugin). However, the links provided in the documentation for "Add A Post-Scan Plugin" are unreachable. The `scancode-toolkit/plugins/` directory doesn't exist in the develop branch of the git repo.

**Comment by AyanSinhaMahapatra** [comment]
Thanks for the report, we moved out the plugins directory out of the main repository and the documentation needs to be updated.  I will do this right away. Follow these links instead:

https://github.com/nexB/scancode-plugins/tree/main/misc/scancode-ignore-binaries
https://github.com/nexB/plugincode

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra while updating the doc, the example could be refreshed too, s=though the code is still valid.
@ekidonatan just curious, what would this plugin be doing? do you plan to make it open source?

**Comment by ekidonatan** [comment]
@AyanSinhaMahapatra Thanks for letting me know.
@pombredanne I'm planning on deploying a plugin that would redirect the scancode output into a SQLite DB. I'm probably going to make it open source though I haven't decided on that yet.

**Comment by AyanSinhaMahapatra** [comment]
This is updated now: https://scancode-toolkit.readthedocs.io/en/stable/tutorials/how_to_add_a_post_scan_plugin.html
