### ISSUE TITLE
Package released application archives for Python 3.9, 3.10 and 3.11 and not only 3.8

### ISSUE THREAD

**Issue by Jeeppler** [nexB/scancode-toolkit#3124]
## Short Description

Debian 11 comes with Python 3.9 packaged. Meaning, `apt install python3` will install Python 3.9. At the time of writing there is no other Python version supported, therefore a Python 3.9 archive package should be provided to be able to easily install Scancode on Debian 11. Debian 11 is the current stable version of Debian.

## Possible Labels

- Python3
- new feature

## Select Category

-  [x] Packaging

## **How This Feature will help you/your organization**

This feature will help all users using Debian 11 or Python 3.9.

**Comment by pombredanne** [comment]
we need to package for 3.9 3.10 and 3.11 for v32.
