### ISSUE TITLE
consolidate option should be marked as deprecated in the docs

### ISSUE THREAD

**Issue by bwjohnson-ss** [nexB/scancode-toolkit#3126]
### Description

It looks like the consolidate option is on the path to deprecation, but the docs don't mention that fact.

```
Run post-scan: consolidate...
/scancode-toolkit/src/scancode/cli.py:1077: ConsolidatorPluginDeprecationWarning: The --consolidate option will be deprecated in a future version of scancode-toolkit.
```

### Link to Documentation Page

https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/list-options.html#all-post-scan-options

### Select Category

-  [x] Inconsistency
-  [ ] New Section Request
-  [ ] General Improvement
-  [ ] Typo/Mistakes
-  [ ] Other

**Comment by pombredanne** [comment]
Thanks!
