### ISSUE TITLE
Extend license data model to tell which licenses IDs represent a CLA

### ISSUE THREAD

**Issue by fviernau** [nexB/scancode-toolkit#3147]
Contributor License Agreements (CLAs) seem fundamentally different from licenses which apply to the use of open source.
The likelyhood that also the handling in context of policy automation differs seems high.

So, it would make sense to have a way to tell which licenses do represent a CLA. This could be done by either of

1. Introducing a dedicated category and assigning CLAs (only) to that category
2. Adding an attribute to the license data model, like e.g. `is_cla`

I'd tend towards 1., as the licenses seem so different - but I'm not a legal person and lack the overview and details of all the licenses.

**Comment by DennisClark** [comment]
@fviernau   thanks very much for your observations.  I am generally very reluctant to introduce a new license category, but the CLA case is so obviously different that it might be the best approach, and would potentially provide corresponding benefits for clarity and reporting purposes. I will discuss this further with my colleagues.  This approach should of course help us with resolving Issue #3038

**Comment by DennisClark** [comment]
done
