### ISSUE TITLE
Generate DejaCode license URL in a dataspace neutral manner

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#315]
Instead of 

https://enterprise.dejacode.com/license_library/Demo/gpl-2.0/

ScanCode should generate a URL in this format: 

a dataspace independent URL to a license would be: https://enterprise.dejacode.com/urn/?urn=urn:dje:license:gpl-2.0

**Comment by DennisClark** [comment]
Alternatively, the following format might work: 
Use the URN URL :slightly_smiling_face: we could probably simplify the URL to something like https://enterprise.dejacode.com/urn/urn:dje:license:gpl-2.0

**Comment by tdruez** [comment]
@majurg from https://github.com/nexB/dejacode/issues/382#issuecomment-245010248

> Before making any changes in ScanCode, let's see if we can simplify the schema of the URN URL.

**Comment by majurg** [comment]
@tdruez: alright, will change when DJE simplified schema is implemented.

**Comment by tdruez** [comment]
@majurg the new URL for URN is `/urn/urn:dje:license:gpl-2.0/`
This change will be published to DejaCode Production tonight.
You can already prepare the change on the ScanCode side and we'll be able to merge tomorrow :)

**Comment by majurg** [comment]
Confirmed working on the latest development branch. Closing this issue.
