### ISSUE TITLE
License Analysis - resulting in error "Process completed with exit code 1"

### ISSUE THREAD

**Issue by NaveenTSW** [nexB/scancode-toolkit#3161]
### Description

License Analysis - resulting in error "Process completed with exit code 1"

### How To Reproduce

Post successful scancode setup in Linux distro - Ubuntu , 20.04.5 LTS , Python version - '3.10.6', the license analysis command
run  scancode -clpeui -n 2 --ignore "*.js" --html result.html .  &> output.txt && grep 'Error' output.txt > result.txt
is resulting in error "process completed with exit code 1"

same command worked fine till 25th and started failing.

run  scancode -clpeui -n 2 --ignore "*.js" --html result.html .  &> output.txt && grep 'Error' output.txt > result.txt
### System configuration

> For bug reports, it really helps us to know:
Linux distro - Ubuntu , 20.04.5 LTS , Python version - '3.10.6'

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
Can you attach the JSON scan output as txt? it will contain error details.

**Comment by NaveenTSW** [comment]
[1_Setup Scancode and Run analysis.txt](https://github.com/nexB/scancode-toolkit/files/10111664/1_Setup.Scancode.and.Run.analysis.txt)
Please find the scan setup and output details in the attached file, thanks

**Comment by pombredanne** [comment]
@NaveenTSW this file is empty

**Comment by pombredanne** [comment]
and how did you install Scancode?

**Comment by NaveenTSW** [comment]
[1_Setup Scancode and Run analysis.txt](https://github.com/nexB/scancode-toolkit/files/10113856/1_Setup.Scancode.and.Run.analysis.txt)
check this attachment please

**Comment by NaveenTSW** [comment]
installing scancode using github actions as mentioned below

- name: Set up Python 
          uses: actions/setup-python@v2
          with: 
            python-version: '3.10.6'
        
        - name: Install Scancode
          run: |
            pip install --upgrade pip setuptools wheel 
            pip install scancode-toolkit

**Comment by pombredanne** [comment]
Your text file contains no error log at all.
Can you instead run this:
`scancode -clpeui -n 2 --verbose --ignore "*.js" --json-pp output.json <path to your code>`

And I would need at least:
1. the header with the error section
2. any error at the file level
3. the stdout with a stack trace that was printed on screen

**Comment by NaveenTSW** [comment]
![image](https://user-images.githubusercontent.com/104576221/204569435-037707d0-08f2-484f-9d85-a3c6dded93a5.png)
Yes, I am unable to see the details on error as this is running on github hosted runners, all I can see is error as in attached image, the same step was working fine and started failing recently.
will try verbose and see if it comes up with more details, thanks.

**Comment by pombredanne** [comment]
@NaveenTSW do not capture standard out/error then, just let it be. ScanCode will return a proper error code on failure.

In your CI, replace your call:
`run scancode -clpeui -n 2 --ignore "*.js" --html result.html . &> output.txt && grep 'Error' output.txt > result.txt`
by:
`run scancode --verbose -clpeui -n 2 --ignore "*.js" --html result.html --json-pp result.json .`
and make sure you keep the result.html and result.json as artifacts of your build.

If you swallow the error like it is done now, there is no way to investigate anything.
