### ISSUE TITLE
ScientiaMobile commercial license not detected

### ISSUE THREAD

**Issue by vargenau** [nexB/scancode-toolkit#3162]
### Description

Download Haproxy at: http://www.haproxy.org/download/2.6/src/snapshot/haproxy-ss-20221026.tar.gz

File ```contrib/wurfl/wurfl/wurfl.h``` contains the following header:

```
/*
 * InFuze C API - HAPROXY Dummy library version of include
 *
 * Copyright (c) ScientiaMobile, Inc.
 * http://www.scientiamobile.com
 *
 * This software package is the property of ScientiaMobile Inc. and is licensed
 * commercially according to a contract between the Licensee and ScientiaMobile Inc. (Licensor).
 * If you represent the Licensee, please refer to the licensing agreement which has been signed
 * between the two parties. If you do not represent the Licensee, you are not authorized to use
 * this software in any way.
 *
 */
```

When running ScanCode, this commercial license is not detected.

SPDX result is:
```
# File

FileName: ./haproxy-ss-20221026/contrib/wurfl/wurfl/wurfl.h
SPDXID: SPDXRef-138
FileChecksum: SHA1: a4272af065e6f2201c0cc431cc72da9372723419
LicenseConcluded: NOASSERTION
LicenseInfoInFile: NONE
FileCopyrightText: <text>Copyright (c) ScientiaMobile, Inc. http://www.scientiamobile.com
</text>
```

### How To Reproduce

```
scancode -c -l -i --license-text --spdx-tv haproxy_ss_20221026.spdx haproxy-ss-20221026
```

### System configuration

* What OS are you running on? Linux Ubuntu 22.10
* What version of scancode-toolkit was used to generate the scan file?
```
scancode --version
ScanCode version: 31.2.1
ScanCode Output Format version: 2.0.0
SPDX License list version: 3.17
```
* What installation method was used to install/run scancode? pip

**Comment by pombredanne** [comment]
@vargenau Thank you for the report! :bow: 
I entered this https://github.com/haproxy/haproxy/issues/1948 upstream and we will be adding rules to correctly detect this weirdness.

**Comment by pombredanne** [comment]
This https://github.com/nexB/scancode-toolkit/commit/097298d66a2a9d971e1827061ec19ee7d92c1bc7 is fixing this

**Comment by pombredanne** [comment]
@vargenau this has been kindly fixed upstream by @wtarreau in https://github.com/haproxy/haproxy/issues/1948 and together with the fixes mentioned earlier, this is ready to be closed now. This is also ready in the latest ScanCode toolkit 32rc release

**Comment by pombredanne** [comment]
Actually there is likely still a pending issue upstream as explained https://github.com/haproxy/haproxy/issues/1948#issuecomment-1398663073 and 
here https://github.com/haproxy/haproxy/issues/1948#issuecomment-1398702087
