### ISSUE TITLE
Publish new licenses to licensedb as soon as they are defined in develop

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3187]
rather than wait for a new release of scancode-toolkit, we should publish new licenses to the licensedb as soon as we define and recognize them

**Comment by AyanSinhaMahapatra** [comment]
I've created a sample GitHub Action to run updates daily at 16 UTC or 8 AM PT to build and push to licenseDB repository from scancode-toolkit develop.

It works as follows in the GitHub action:

1. clones  `scancode-toolkit` develop branch
2. creates a virtualenv and pip installs `scancode-toolkit` develop from the clone
3. in a script gets the latest commit from scancode-toolkit develop branch
4. using a python script and a JSON file with the last scancode-toolkit commit stored, checks if the develop branch has a new commit
5. if there is no new commit, the python script raises an Exception and fails (also fails if pip install scancode-toolkit fails), failing the script and the GitHub action, and does nothing
6. if there is new commits, we store the commit hash for the last commit at the JSON file
7. we build docs and dump the licensedb data using the new `scancode-license-data` console script
8. we delete the toolkit clone and commit only the doc changes i.e. the licensedb updates
9. we push this to scancode-licensedb main branch from the github action and the licensedb website is also refreshed soon after. 

Example GitHub action on no new commits: [failed action](https://github.com/AyanSinhaMahapatra/scancode-licensedb/actions/runs/3901932365/jobs/6664375341#step:5:316)
Example GitHub action on new commits: [successful action](https://github.com/AyanSinhaMahapatra/scancode-licensedb/actions/runs/3901748849/jobs/6663973608)
Example automated commit pushed to develop:  [AyanSinhaMahapatra/scancode-licensedb@55e57e4e](https://github.com/AyanSinhaMahapatra/scancode-licensedb/commit/55e57e4e)

Do you think this works?
Please suggest updates/improvements if any.

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark this is completed!

See the following github action runs:

* [a successful run](https://github.com/nexB/scancode-licensedb/actions/runs/3953851067) when there are new commits in scancode, here we have updates commited and pushed automatically. See [the commit](https://github.com/nexB/scancode-licensedb/commit/b6225d8fbee2533b9c007283b61d4e62cc594223), here nothing changes as there were no license updates, just the last seen commit hash was updated.
* [a failed run](https://github.com/nexB/scancode-licensedb/actions/runs/3941055382) when there aren't new commits in scancode. Nothing changes here.

Btw, @pombredanne added a workflow trigger so this can be triggered manually, in addition to the daily check.

Follow up issue to improve the commit message: https://github.com/nexB/scancode-licensedb/issues/27

**Comment by AyanSinhaMahapatra** [comment]
This is completed, is running successfully for now and we have further improvements being tracked in seperate issues:
- https://github.com/nexB/scancode-licensedb/issues/31
- https://github.com/nexB/scancode-licensedb/issues/27
Closing this!
