### ISSUE TITLE
ERROR while installing scancode via pip install without failing

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#3195]
While pip installing the new scancode version v31.2.4 I had this: 

```
ERROR: requests 2.28.1 has requirement charset-normalizer<3,>=2, but you'll have charset-normalizer 3.0.1 which is incompatible. 
```

But the install finished successfully and scancode also ran without errors.

Ubuntu 20.04, Python 3.8.10, scancode v31.2.4, pip install

**Comment by shricodev** [comment]
It seemed to completely work for me though in my VMware and also on my  Windows. @AyanSinhaMahapatra 
Faced no such errors when installing with pip.
I think the error is limited to the version of Ubuntu or Python.

![cmdline-scancode](https://user-images.githubusercontent.com/76906722/211769302-e292bb7d-0cfe-46da-afdf-70f9a82d47df.png)

Linux: Parrot OS 5.1
Windows 10 Home
Python 3.10/3.9/3.8.5 64-bit

**Comment by AyanSinhaMahapatra** [comment]
Yeah, @pombredanne couldn't reproduce also btw, thanks for testing!

**Comment by shricodev** [comment]
On googling I found it had to deal with the version of the requests module https://github.com/psf/requests/issues/6281

**Comment by AyanSinhaMahapatra** [comment]
Yes this is because of https://github.com/psf/requests/blob/v2.28.1/setup.cfg#L8, they've updated this upper bound in develop but haven't released yet.

**Comment by pombredanne** [comment]
I cannot reproduce with Ubuntu 16.04, Python 3.8.10, scancode v31.2.4, pip install.
Can you try exactly this, in a new, fresh shell:
```bash
mkdir -p ~/tmp/sctk-3124
cd ~/tmp/sctk-3124
mkdir venv 
wget -O venv/virtualenv.pyz https://bootstrap.pypa.io/virtualenv/virtualenv.pyz
python3 venv/virtualenv.pyz --never-download --seeder pip  \
  --pip embed --setuptools embed --wheel embed \
  --no-vcs-ignore --no-periodic-update ./venv
source venv/bin/activate
pip install scancode-toolkit &> sctk-install-log.txt
```
Then attach `sctk-install-log.txt` here?

**Comment by AyanSinhaMahapatra** [comment]
That didn't reproduce the error:

[sctk-install-log.txt](https://github.com/nexB/scancode-toolkit/files/10391712/sctk-install-log.txt)

I was doing previously:

```
/usr/bin/python3 -m venv venvs/scancode-31.2.4-venv-test/
source venvs/scancode-31.2.4-venv-test/bin/activate
pip install scancode-toolkit
```

**Comment by AyanSinhaMahapatra** [comment]
This can't be reproduced anymore and requests also has a new version with updated version bounds, so closing this.
