### ISSUE TITLE
html and html-app: links should default to opening in a new tab

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#320]
While working with both `html` and `html-app` scancode outputs, links to licenses and other urls open in the same page as 'app' itself. This interrupts the analysis of the scancode data and forces me to find my place again. 

Changing these links to only open in a new tab/window would increase the usability of both the `html` and `html-app` formats of the scancode results.

**Comment by DennisClark** [comment]
My 2 cents:  I totally agree that the proposed change would be an improvement.
