### ISSUE TITLE
/scancode-toolkit-v31.2.4/configure throwing error 

### ISSUE THREAD

**Issue by kasakirankumar** [nexB/scancode-toolkit#3215]
After initial setup done using below like on Centos 7(python 3.10)
https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#installation-on-linux-and-mac
seeing below error after running  ./scancode --help

**[vagrant@hostb scancode-toolkit-v31.2.4]$ ./scancode
* Configuring ScanCode for first use...
/home/vagrant/scancode-toolkit-v31.2.4/configure: line 232: python3.8: command not found**

how to resolve this issue? please suggest. Thanks.

**Comment by pombredanne** [comment]
Let me move this to ScanCode toolkit.

**Comment by pombredanne** [comment]
The version 31.2.4 application archive works only on Python 3.8 for now.
We do not have yet a Python 3.10 bundle (though we test and run fine on Python 3.10)
See https://github.com/nexB/scancode-toolkit/issues/3124 for details.

**Comment by kasakirankumar** [comment]
Thank you for quick response. will check by downgrade python version.

**Comment by AyanSinhaMahapatra** [comment]
@kasakirankumar we are nearing a v32.0.0rc2 release, and here are some app archives you can test with if you need all python versions support for app archives: https://github.com/AyanSinhaMahapatra/scancode-toolkit/releases/tag/v32.0.0rc2.4 also see #3235
