### ISSUE TITLE
v32.0.0rc1 has only Python 3.8 downloads

### ISSUE THREAD

**Issue by vargenau** [nexB/scancode-toolkit#3235]
### Description

v32.0.0rc1 has only Python 3.8 downloads

https://github.com/nexB/scancode-toolkit/releases/tag/v32.0.0rc1

Would it be possible to have downloads for Python 3.9 and Python 3.10?

I am on Ubuntu 22.10

**Comment by pombredanne** [comment]
@vargenau this is a timely request and it's in the air!
@AyanSinhaMahapatra is working on it in https://github.com/nexB/scancode-toolkit/pull/3232
Ayan... do you have some early testable builds that you may have crafted in your fork?

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne Yes, and #3232 is ready for review, and we'll release v.32.0.0rc2 right after it is merged!

@vargenau you can try out https://github.com/AyanSinhaMahapatra/scancode-toolkit/releases/tag/untagged-32aa6157370c113fb31c which was released from my fork with a tag on the #3232 branch. Let us know if it works allright!

**Comment by vargenau** [comment]
@AyanSinhaMahapatra I get a 404 error on https://github.com/AyanSinhaMahapatra/scancode-toolkit/releases/tag/untagged-32aa6157370c113fb31c

**Comment by AyanSinhaMahapatra** [comment]
Oh! I didn't know draft releases are only visible to maintainers/owners, sorry for the confusion. Try https://github.com/AyanSinhaMahapatra/scancode-toolkit/releases/tag/v32.0.0rc2.4

**Comment by vargenau** [comment]
I have successfully installed:
```
./scancode --version
ScanCode version: 32.0.0rc1
ScanCode Output Format version: 3.0.0
SPDX License list version: 3.19
```

Thank you!
