### ISSUE TITLE
Setup plugin before running command

### ISSUE THREAD

**Issue by zzberth** [nexB/scancode-toolkit#3237]
Hi team,

I want to use the scancode command to convert license into spdx license identifier, and I may use this command a lot.

I noticed a lot of time was spent in setup plugin. Is there a way to permanently enable the plugin to reduce the time of each command?

![Screenshot 2023-02-02 at 17 12 44](https://user-images.githubusercontent.com/93831344/216289360-6a0d65dc-2916-401a-89db-d86712e76b49.png)

**Comment by pombredanne** [comment]
@zzberth this is time that's used to load the license index in memory. There is a tool in etc/ (scanserv) that's been designed to load a socket server locally and avoid the penalty of re-loading this. Alternatively you can consider also scancode.io as this would keep the licensedb loaded.
I am really interested to fix this in anycase. I wonder how we could speed it up, assuming that the only reasonable solution is preloading and keep in memory.

**Comment by zzberth** [comment]
Hi @pombredanne, thanks for your reply. Is there any documentation for the preloading index to memory? I'm not familiar with this.
