### ISSUE TITLE
Output JSON cannot be processed by about

### ISSUE THREAD

**Issue by lucasgonze** [nexB/scancode-toolkit#3244]
### Description

Use scancode to generate a json file. Send the file into aboutcode-tool. Get error.

### How To Reproduce

> Tell us how to reproduce the issue. 

```
$ npm install js-yaml
$ scancode -pcl --license-text node_modules/js-yaml/  --json-pp /tmp/d.json
$ about attrib /tmp/d.json /tmp/about.json
Running aboutcode-toolkit version 7.2.0
Generating attribution...
Command completed with 1 errors or warnings.
CRITICAL: Required field: 'name' not found in the <input>
Error log: /private/tmp/about.json-error.log
```

For the contents of the json file, see https://gist.github.com/lucasgonze/bf122611f3b4d97bbbca65cb0f0744e3

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)

OS X

* What version of scancode-toolkit was used to generate the scan file?

```$ scancode --version
ScanCode version: 31.2.4
ScanCode Output Format version: 2.0.0
SPDX License list version: 3.18```

* What installation method was used to install/run scancode? (pip/source download/other)

pip

<!-- 
Your help makes ScanCode Toolkit better! We *deeply* appreciate your help in improving ScanCode Toolkit.
-->

**Comment by mjherzog** [comment]
AboutCode Toolkit was not designed to directly process ScanCode Toolkit scan data. It was designed for input from ABOUT files in a more generalized format, likely with curation after a Scan. One key reason is that generating Attribution at the file level from a Scan could create an extremely large and noisy notice file (depending on the scope or your scan).  
See also the doc at https://aboutcode-toolkit.readthedocs.io/en/latest/general.html. This issue would probably be better handled as an enhancement request for AboutCode Toolkit.

**Comment by lucasgonze** [comment]
@mjherzog Thanks for this background. I'll rethink the request. I appreciate the thoughtful reply.

**Comment by chinyeungli** [comment]
@lucasgonze Thanks for your feedback. FYI, the `attrib` command in aboutcode-toolkit has an option to work with scancode's scan with the `--scancode` option. See https://aboutcode-toolkit.readthedocs.io/en/latest/reference.html#id3

**HOWEVER**, it is not currently working as the implemented version in AbcTK is out-dated (https://github.com/nexB/aboutcode-toolkit/issues/518) , I will work on this to make it work.

as @mjherzog points out, it is not highly recommend to run it directly from ScanCode Toolkit scan data as it may create much noise, but the option is (will be) there.

**Comment by mjherzog** [comment]
@lucasgonze It looks like I lost track of our latest AboutCode TK features. I re-opened this issue so that you can track it here while we work on the issue for AboutCode Toolkit. 

@chinyeungli Thank you for catching my mistake!

**Comment by chinyeungli** [comment]
@lucasgonze actually I just tried the latest stable release (not the development version) 31.2.4 (the same as you used) and the structure is still the same. So, in you case, you will first want to include `-i` in your scan to get the file info. After that, use the `--scancode` option in `about` to generate the attribution.

i.e.
```
scancode -pcli --license-text node_modules/js-yaml/  --json-pp /tmp/d.json
about attrib --scancode /tmp/d.json /tmp/about.json
```

Let me know if this is working.

**Comment by lucasgonze** [comment]
@chinyeungli Thank you for taking the time to help me solve this! That incantation worked perfectly.
