### ISSUE TITLE
LicenseListVersion: 3.6

### ISSUE THREAD

**Issue by vargenau** [nexB/scancode-toolkit#3257]
### Description

In SPDX, we have:
```
LicenseListVersion: 3.6
```
That should be:
```
LicenseListVersion: 3.19
```

### How To Reproduce

```
svn checkout https://svn.code.sf.net/p/phpwiki/code/trunk phpwiki
```

```
./scancode -c -l -i --license-text --spdx-tv phpwiki.spdx phpwiki
```

Resulting SPDX file:

[phpwiki.spdx.txt](https://github.com/nexB/scancode-toolkit/files/10745540/phpwiki.spdx.txt)

### System configuration

```
./scancode --version
ScanCode version: 32.0.0rc1
ScanCode Output Format version: 3.0.0
SPDX License list version: 3.19
```
Ubuntu 22.10

**Comment by AyanSinhaMahapatra** [comment]
This bug was caused because SPDX python was using the license list version from it's own config and silently ignoring the SPDX license list version passed by scancode-toolkit. This should be fixed by #3271 where we are now forcing this value onto `Document.CreationInfo()`

**Comment by vargenau** [comment]
Thank you for the fix and the explanation. It was very strange to have such an old license list version.

I have opened a bug: https://github.com/spdx/tools-python/issues/491

**Comment by vargenau** [comment]
I have fixed it in tools-python: https://github.com/spdx/tools-python/pull/492

It will be in the next release.
