### ISSUE TITLE
Docker run No license be detected！

### ISSUE THREAD

**Issue by allen7lee** [nexB/scancode-toolkit#3272]
### Description
I had used https://github.com/nexB/scancode-toolkit/blob/develop/Dockerfile to build docker images .then run it but no any licenses be detected!
NO any licenses information in result.html!

### How To Reproduce

download https://github.com/nexB/scancode-toolkit/archive/refs/tags/v32.0.0rc2.tar.gz
tar zxvf scancode-toolkit-32.0.0rc2.tar.gz
cd scancode-toolkit-32.0.0rc2

docker build --tag scancode-toolkit:latest .
cd samples
docker run --rm -v $PWD/:/project scancode-toolkit:latest -n 10 -clpeui  --html /project/result.html  /project

### System configuration

* What OS are you running on? (Windows/MacOS/Linux)  centos 7.0
* What version of scancode-toolkit was used to generate the scan file? 32.0.0rc2
* What installation method was used to install/run scancode? (pip/source download/other) source download

**Comment by pombredanne** [comment]
@allen7lee Thank you for the report: its a bug alright. The JSON results are correct though.

[result.json.txt](https://github.com/nexB/scancode-toolkit/files/10813618/result.json.txt)

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra I think this is a blocker for 32. Moving to the milestone

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne on it!

**Comment by pombredanne** [comment]
This is fixed in https://github.com/nexB/scancode-toolkit/pull/3275
