### ISSUE TITLE
Upgrade spdx-tools to release 0.7.1 

### ISSUE THREAD

**Issue by vargenau** [nexB/scancode-toolkit#3289]
Upgrade spdx-tools to release 0.7.1 

https://pypi.org/project/spdx-tools/

https://github.com/spdx/tools-python/releases/tag/v0.7.1

This will solve https://github.com/nexB/scancode-toolkit/issues/3255

**Comment by vargenau** [comment]
@pombredanne any issue with that proposed upgrade?

**Comment by vargenau** [comment]
@pombredanne @AyanSinhaMahapatra any issue with that proposed upgrade?

**Comment by onny** [comment]
Can you create a pull request for the update of spdx-tools to 0.7.1 :)

**Comment by pombredanne** [comment]
@onny re:
> Can you create a pull request for the update of spdx-tools to 0.7.1 :)

Help is mucho welcomed there as this is breaking a few things that will need to be updated and fixed.

Note that we are eventually switching in a near future to this new library https://github.com/nexb/turbo-spdx that is simpler and cleaner and entirely generated from the SPDX schema and guaranteed to match the spec. It also let's go of the SPDX legacy of tag/values, XML and RDF to focus on clean JSON only.

**Comment by pombredanne** [comment]
@vargenau no issue, beyond the need to do the work and fix the code accordingly!

**Comment by vargenau** [comment]
@pombredanne 
Thank you for your answer.
I thought that updating from 0.7.0rc0 to 0.7.1 (one minor revision) would cause no compatibility issue.
I can help, if you tell me what are the issues with 0.7.1

**Comment by vargenau** [comment]
Closing as spdx_tools has been upgraded to 0.8.1
