### ISSUE TITLE
Invalid DejaCode license URL's reported

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#329]
Using scancode-toolkit-2.0.0rc1 I scanned the latest lxml-master from https://github.com/lxml/lxml with all output options.  The scan ran without any problems; however, it reports licenses that do not exist in DejaCode as if they are DejaCode licenses.  For example, on the file ez_setup.py it reports the following: 

https://enterprise.dejacode.com/urn/urn:dje:license:gpl-3.0
https://enterprise.dejacode.com/urn/urn:dje:license:sencha-app-floss-exception
https://enterprise.dejacode.com/urn/urn:dje:license:sencha-dev-floss-exception
https://enterprise.dejacode.com/urn/urn:dje:license:sencha-commercial
https://enterprise.dejacode.com/urn/urn:dje:license:public-domain
https://enterprise.dejacode.com/urn/urn:dje:license:mit
https://enterprise.dejacode.com/urn/urn:dje:license:mit

The two "exception" licenses do not exist in DejaCode, but it constructed DejaCode URL values for them anyway.

**Comment by DennisClark** [comment]
[lxml-master-scan2.json.zip](https://github.com/nexB/scancode-toolkit/files/522718/lxml-master-scan2.json.zip)

Scan results attached.

**Comment by pombredanne** [comment]
Thanks. I will need to do a sync and submit the missing licenses for addition to DejaCode

**Comment by pombredanne** [comment]
All these are properly reported now. And there have been several sync since. Closing
