### ISSUE TITLE
Have a auto generated page about packages

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#3298]
A suggestion from @tdruez :

we should add a new section in the toolkit documentation auto-generated using a similar output as the --list-packages so it can be referenced in ScanCodeio and elsewhere?

### Select Category

-  [ ] Inconsistency
-  [x] New Section Request
-  [ ] General Improvement
-  [ ] Typo/Mistakes
-  [ ] Other

**Comment by AyanSinhaMahapatra** [comment]
@tdruez see https://scancode-toolkit.readthedocs.io/en/doc-update-licenses/reference/available_package_parsers.html, I've added a table view, would this work? 

Another option could be one tsub-section for every available package parser, and in this case we can point with URLs like: https://scancode-toolkit.readthedocs.io/en/doc-update-licenses/reference/available_package_parsers.html#<datasource_id>

**Comment by tdruez** [comment]
@AyanSinhaMahapatra looks good but I would put the `Description` column first and the `Path Patterns` second.

**Comment by AyanSinhaMahapatra** [comment]
@tdruez thanks for the feedback, I'll update the PR accordingly.
