### ISSUE TITLE
License clarity score plugin does not work with jar 

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#3306]
The license clarity score plugin needs to be updated to work on jars and poms, in addition to standard codebase layouts.

**Comment by JonoYang** [comment]
This has been addressed in https://github.com/nexB/scancode-toolkit/pull/3315, where we explicitly report the top-level files of JAR packages. This allows the file classification plugin to properly classify files within a JAR, and allows the summary plugin to work correctly.

**Comment by pombredanne** [comment]
Thanks! closing now.
