### ISSUE TITLE
GPL reference in gli project not detected

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#331]
scancode 2.0.0.rc1 does not seem to pick up [this reference to GPL](https://github.com/g-truc/gli/blob/master/external/glm/test/external/gli/core/shared_ptr.inl#L4). Maybe that's because of the spelling of "licence"?

**Comment by sschuberth** [comment]
Sorry, I was not using version 2.0.0.rc1 but version 1.6.0. Version 2.0.0.rc1 indeed does detect that GPL reference.

**Comment by pombredanne** [comment]
Yes this is might be the reason. Don't we all love english dialects?

**Comment by pombredanne** [comment]
Just to be on the safe side, I added a few extra rules and tests
