### ISSUE TITLE
Release new patch for version 31

### ISSUE THREAD

**Issue by zhernovs** [nexB/scancode-toolkit#3310]
HERE would love to use newer version of Scancode (currently on 30.1.0) together with ORT. But [ORT still doesn't support new output format version](https://github.com/oss-review-toolkit/ort/issues/6617) that you have in v32. On the other hand we can't use latest v31 without a fix from [this](https://github.com/nexB/scancode-toolkit/commit/6358a4b81d6ce3446e9ffce223458d535c884820) commit. It's already merged into develop and included in latest release candidate for v32. 

Maybe it's possible to release another patch version for v31 with mentioned commit?

**Comment by AyanSinhaMahapatra** [comment]
@zhernovs see the PR above #3312 , this is just so you can review if this is all you need for the `31.2.5` backport release, then I'll push the tag on this and you will have the release.

Reference: https://github.com/nexB/scancode-toolkit/pull/3218#issuecomment-1497114761

**Comment by zhernovs** [comment]
This is all we need, Thanks @AyanSinhaMahapatra, please go ahead.

**Comment by AyanSinhaMahapatra** [comment]
See https://github.com/nexB/scancode-toolkit/releases/tag/v31.2.5 and https://pypi.org/project/scancode-toolkit/31.2.5/, we have a new scancode-toolkit v31.2.5 backport release. :rocket:

**Comment by AyanSinhaMahapatra** [comment]
This is done, closing this.
