### ISSUE TITLE
The license category for `ms-cla` should be `cla`

### ISSUE THREAD

**Issue by fviernau** [nexB/scancode-toolkit#3317]
The license is currently categorized as "patent license", whereas "cla" seems to be the better fit. See also https://github.com/nexB/scancode-licensedb/blob/ba55a604cb7b0bb614ae578d71a1be8fe37ba6d5/docs/ms-cla.json.

**Comment by pombredanne** [comment]
Good catch! I am moving this to ScanCode toolkit proper. Can I interest you in a small patch for this?
@DennisClark ping too.

**Comment by fviernau** [comment]
> Can I interest you in a small patch for this?

Sure, I'll file a PR soon.
