### ISSUE TITLE
SCTK: Validate that we can extract all valuable information from a JAR manifest

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3333]
In particular there are standard properties but also OSGI bundle-specific properties with useful origin and license information.

**Comment by JonoYang** [comment]
@AyanSinhaMahapatra I think we have done what we can to get as much info from pom.xml and manifest.mf files?

**Comment by AyanSinhaMahapatra** [comment]
@JonoYang yeah this was added at https://github.com/nexB/scancode-toolkit/pull/3447 
Closing!
