### ISSUE TITLE
Properly report key files for JARs

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3334]
This is important for:
- license detection in a package
- classification of key files for summarization and license scoring

The key files of a JAR are typically under META-INF, or OSGI-INF and more rarely at the root of a JAR.

WARs and EARs may have different conventions.

**Comment by JonoYang** [comment]
This has been addressed in #3315, where we explicitly report the top-level files of JAR packages. This allows the file classification plugin to properly classify files within a JAR, and allows the summary plugin to work correctly.

**Comment by pombredanne** [comment]
@JonoYang Thanks! closing now as this completed.
