### ISSUE TITLE
Support Python 64 bits on Windows 64

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#335]
Today only Python 32 bits is supported on Windows 64

Following a discussion in https://github.com/nexB/scancode-toolkit/pull/333
@sschuberth wrote:

> when will ScanCode run with 64-bit Python on Windows? 

@pombredanne replie:

> running on 64bits should not be a big issue, this is just about recompiling all the thirdparty and ensuring the tests pass: I have started working on getting 64 bits Python wheels here https://github.com/pombreda/thirdparty to have a fully automated rebuild of all thirddparties. There are some of them that can compile only under Mingw and I did not come down to these yet. If you are interested to chip in I could guide you alright. This is is mostly about native libraries and testing: the candidates are likely libarchive, libmagic and 7zip and it is very possible that no recompilation is needed at all since these are either spawned (7zip) or use with a ctypes binding (libarchive, libmagic)

**Comment by pombredanne** [comment]
#616 is alos the ticket that was used to track this

**Comment by pombredanne** [comment]
@chinyeungli Can you tell if this works fine for you now?

**Comment by chinyeungli** [comment]
```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> print(struct.calcsize("P") * 8)
64
```
I am running 64bits, and I have no problem of running scancode-tk

**Comment by pombredanne** [comment]
@chinyeungli Thanks
At this stage I am calling this done and closed!
