### ISSUE TITLE
False positive license detection based on gpl_200.RULE

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3374]
In a recent scan of pom.xml in jsoup-1.15.3.jar the scan results included gpl-1.0-plus based on a score of 100 on gpl_200.RULE but the actual text in the pom.xml file tells a different story: 

line 352
`      <!-- javax.annotations.nonnull, with Apache 2 (not GPL) license. Build time only. -->` 

Obviously the author wanted to make sure to clarify that GPL was NOT being inherited from javax.annotations.  There is no indication of any GPL licensed code in the project. This can probably be addressed by a new RULE. 

[pom.xml.zip](https://github.com/nexB/scancode-toolkit/files/11366957/pom.xml.zip)

**Comment by AyanSinhaMahapatra** [comment]
This was added as a rule and is now fixed. Here's the scan for reference:
[jsoup-pom.xml--scan-results.json.txt](https://github.com/nexB/scancode-toolkit/files/13366762/jsoup-pom.xml--scan-results.json.txt)
Closing, thanks @DennisClark
