### ISSUE TITLE
False positive license detection on epl-2.0_59.RULE

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3375]
A recent scan of pom.xml in spatial4j-0.7.jar returned a detection of epl-2.0 with a score of 71.43 on epl-2.0_59.RULE 

Although spatial4j is an Eclipse Foundation project, it is clearly licensed under apache-2.0 (also detected, correctly) as described at https://projects.eclipse.org/projects/locationtech.spatial4j  as well as the first 5 lines of this pom.xml. 

There is no mention of the epl-2.0 license in the text of this pom.xml. 

[pom.xml.zip](https://github.com/nexB/scancode-toolkit/files/11367101/pom.xml.zip)

**Comment by AyanSinhaMahapatra** [comment]
This was fixed, so closing! Attaching results for reference.
Thanks @DennisClark 
[spatial4j-pom.xml-scan-results.json.txt](https://github.com/nexB/scancode-toolkit/files/13366664/spatial4j-pom.xml-scan-results.json.txt)
