### ISSUE TITLE
False positive detection on generic-cla_28.RULE

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3380]
A recent scan of `README.md` in project `ssri-9.0.1.tgz` detected the generic-cla based on a 4.44 score with RULE generic-cla_28.RULE  giving the following as matched_text: 

```
"Contributing [The] [ssri] [team] [enthusiastically] welcomes contributions and"
```

but that is not a convincing match with the RULE itself: 
```
## Contributing

This project welcomes contributions and suggestions. Most contributions require you to agree to a
Contributor License Agreement (CLA) declaring that you have the right to, and actually do, grant us
the rights to use your contribution. For details, visit https://cla.microsoft.com.
```

The README.md file text does not actually refer to any kind of CLA, but is rather concerned with basic procedures and group dynamics: 
```
### Contributing

The ssri team enthusiastically welcomes contributions and project participation!
There's a bunch of things you can do if you want to contribute! The [Contributor
Guide](CONTRIBUTING.md) has all the information you need for everything from
reporting bugs to contributing entire new features. Please don't hesitate to
jump in if you'd like to, or even ask us questions if something isn't clear.
```

So I think that the generic-cla_28.RULE should be improved by making this text required in curly brackets:
`Contributor License Agreement`   

By the way, the contents of `ssri-9.0.1.tgz` do not actually contain a file called CONTRIBUTING.md (as far as I could tell) which further reduces any evidence of an actual CLA. 
[ssri-9.0.1.tgz](https://github.com/nexB/scancode-toolkit/files/11376669/ssri-9.0.1.tgz)

**Comment by AyanSinhaMahapatra** [comment]
This is added with the commit above.
Thanks @DennisClark , see results for reference.
[ssri-9.0.1-scan-results.json.txt](https://github.com/nexB/scancode-toolkit/files/13366364/ssri-9.0.1-scan-results.json.txt)
