### ISSUE TITLE
Separate scanner from api + other toolkit-related modules

### ISSUE THREAD

**Issue by xizhao** [nexB/scancode-toolkit#34]
I think it would be valuable to have the scanner itself as a completely separate module in a different repo, or every "strategy" as separate repos.  The rule aggregation is a different job than the toolkit of creating the HTML templates and other data.

Also maybe consider building the scanning module in a language like go, which can be compiled into a binary.

**Comment by pombredanne** [comment]
@xizhao can you elaborate a bit your thought there? I am not sure I get what you meant...

The scanner code proper (in the sense of walking a directory tree to do things on it) is a rather small piece of code that lives in src/scancode/

The actual scan work is done on a file-by-file basis in functions that take a file location as an input and return scan for that one file (such as detecting a license, a copyright or else). At a high level these functions are in src/scancode/api.py

About Go, what would be the benefits of a rewrite? Compiled binaries bring all kinds of portability issues with them (see for instance  https://github.com/nexB/scancode-toolkit/issues/33 ... )

**Comment by pombredanne** [comment]
@xizhao do you have some more input there?

**Comment by pombredanne** [comment]
@xizhao  you wrote:
> I think it would be valuable to have the scanner itself as a completely separate module in a different repo, or every "strategy" as separate repos. The rule aggregation is a different job than the toolkit of creating the HTML templates and other data.

Re-reading your comment I think you meant splitting the scancode-toolkit repo in multiple repos, one `scancode-licensedcode`, one for `scancode-cluecode` and so... where what you call a "strategy" is a scan such as a license scan, a copyright scan and so on?  Am I correct?

**Comment by pombredanne** [comment]
@xizhao You never replied, so I assume that you are not interested. Closing.
