### ISSUE TITLE
Update SPDX LicenseListVersion to 3.21

### ISSUE THREAD

**Issue by vargenau** [nexB/scancode-toolkit#3442]
## Short Description

Version: 3.21 of SPDX license list is out since 2023-06-18

See https://spdx.org/licenses/

**Comment by AyanSinhaMahapatra** [comment]
@vargenau he have updated this in https://github.com/nexB/scancode-toolkit/pull/3437 and tracked in https://github.com/nexB/scancode-licensedb/issues/37.
See https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode_config.py#L147 and this should be also visible on a source code checkout/configure and then `scancode --version`.
We also have this available now at: https://scancode-licensedb.aboutcode.org/ (Updated just now).
This should also be released as a new SCTK too, in the upcoming days.

**Comment by vargenau** [comment]
This has been implemented in ScanCode v32.0.6.
