### ISSUE TITLE
Optionally do not detect license when scanning a package

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3445]
In order to support a lighweight and fast package-only scan I would like to have an option in the code (not a CLI option for now) such that we can bypass license detection when running a package scan. This is a nice to have have and would support https://github.com/nexB/scancode.io/issues/720

**Comment by AyanSinhaMahapatra** [comment]
This is now there with https://github.com/nexB/scancode-toolkit/pull/3689 both as an option in the code (see the API function `get_package_data` [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode/api.py#L295) which has the `package_only` option there) and as a CLI option: `--package-only` [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/plugin_package.py#L165). This is also there in scancode.io with https://github.com/nexB/scancode.io/pull/1118. So closing!
