### ISSUE TITLE
SPDX rdf tests pass automatically

### ISSUE THREAD

**Issue by armintaenzertng** [nexB/scancode-toolkit#3448]
### Description

The SPDX rdf tests currently pass automatically. This is due to [this line](https://github.com/nexB/scancode-toolkit/blob/a15174f31efaf8816e8c9a65c9f85c4beffc0227/tests/formattedcode/test_output_spdx.py#L130) in the code, which basically sets `expected == result` per default.
The bug can be fixed by removing the linked line.

As almost all spdx tests are skipped via the `@pytest.mark.scanslow` annotation, this does not affect most of the tests.
However, if you remove these annotations they will fail with the above fix.

When upgrading the spdx-tools to the new 0.8 version, these test have to be slightly adapted, anyway. I can offer to do this while working on the library upgrade.

### How To Reproduce

Remove [this line](https://github.com/nexB/scancode-toolkit/blob/a15174f31efaf8816e8c9a65c9f85c4beffc0227/tests/formattedcode/test_output_spdx.py#L130) in the code and execute for example [this test](https://github.com/nexB/scancode-toolkit/blob/a15174f31efaf8816e8c9a65c9f85c4beffc0227/tests/formattedcode/test_output_spdx.py#L197) (you have to remove the annotation first).

### System configuration

Ubuntu 22.04.2 LTS, Scancode 32.0.5rc3

**Comment by armintaenzertng** [comment]
I'm not sure about the other part of the if clause, which will also pass automatically due to [this line](https://github.com/nexB/scancode-toolkit/blob/a15174f31efaf8816e8c9a65c9f85c4beffc0227/tests/formattedcode/test_output_spdx.py#L124). But maybe that is the intended behavior in that case?

**Comment by pombredanne** [comment]
Great catch!
So the behaviour should be:
1. if the test fixture regeneration environment variable REGEN_TEST_FIXTURES is set then the expected results file should be update with the latest results content.
2. otherwise, the test should run and the results checked against pre-computed expected results

Therefore the whole block at https://github.com/nexB/scancode-toolkit/blob/a15174f31efaf8816e8c9a65c9f85c4beffc0227/tests/formattedcode/test_output_spdx.py#L128-L131 should be replaced by this:
```Python
expected = load_and_clean_rdf(expected_file)
```

**Comment by pombredanne** [comment]
Can I interest you in a patch? :angel:

**Comment by armintaenzertng** [comment]
> Can I interest you in a patch?

Yes, most certainly! :)
Can I interest you in our new [spdx-tools version 0.8](https://pypi.org/project/spdx-tools/0.8.0rc1/)? :D

**Comment by armintaenzertng** [comment]
@pombredanne, just in case you missed it, I opened a PR to fix this in #3451.
