### ISSUE TITLE
Upgrade `spdx-tools` to version 0.8

### ISSUE THREAD

**Issue by armintaenzertng** [nexB/scancode-toolkit#3455]
## Short Description
Upgrade `spdx-tools` to v0.8

## Possible Labels

- dependencies

## Select Category

-  [ ] Enhancement
-  [ ] Add License/Copyright
-  [ ] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [x] Expand Support
-  [ ] Other

## **Describe the Update**

Update the `spdx-tools` dependency from `0.7.0rc0` to `0.8.0rc2` or later.

## **How This Feature will help you/your organization**
The new 0.8 version of the `spdx-tools` lays the groundwork for the upcoming SPDX-3.0 implementation in python. We therefore expect broad adoption of the 0.8 version.
Tools that use the 0.8 version of the `spdx-tools` currently can't simultaneously use scancode which depends on the 0.7 version (there can't be two different versions of the same library in a single environment).
This issue currently blocks adoption of the `spdx-tools` in tern, for example.

## **Example/Links if Any**

Pending PR in tern that introduces `spdx-tools` in version 0.8: https://github.com/tern-tools/tern/pull/1233

## **Can you help with this Feature**

I will open a PR that takes care of the upgrade while preserving the current feature set.

**Comment by priv-kweihmann** [comment]
FYI: release of 0.80 is out since last week - no need to upgrade to a rc
