### ISSUE TITLE
Add LLAMA 2 community license

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#3463]
### Description

https://github.com/facebookresearch/llama/blob/main/LICENSE

**Comment by armijnhemel** [comment]
The LLAMA 2 license seems to have been added in 8de1e90d1428547578f55cf50af0b3fa49699edc but there is no `.RULE` file yet.

**Comment by pombredanne** [comment]
@armijnhemel A LICENSE is enough to detect the license text

**Comment by armijnhemel** [comment]
> @armijnhemel A LICENSE is enough to detect the license text

Oh, in that case the LICENSE isn't working for this particular license.

Attached the output I am currently getting.

[llama.json](https://github.com/nexB/scancode-toolkit/files/13461673/llama.json)

**Comment by pombredanne** [comment]
I added a few rules for the various notices showing up in the wild.

@armijnhemel you wrote:
> Oh, in that case the LICENSE isn't working for this particular license.

Did you work on a checkout? And if so did you run "scancode-reindex-licenses" after pulling in the latest?

**Comment by armijnhemel** [comment]
> I added a few rules for the various notices showing up in the wild.
> 
> @armijnhemel you wrote:
> 
> > Oh, in that case the LICENSE isn't working for this particular license.
> 
> Did you work on a checkout? And if so did you run "scancode-reindex-licenses" after pulling in the latest?

No, I hadn't run that. I had run a `make clean` and a `configure` but apaprently that didn't rebuild the license index. Now it works, so closing this issue.
