### ISSUE TITLE
Optionally only collect the PURL of packages, source packages and dependencies in ScanCode Toolkit

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3464]
I would like to have a minimal and lightweight, fast --package scan option that does not do anything more than collecting PURLs, either for actual packages that are present and for their dependencies. This would then a nice input for other pipelines and tools that are based on PURL only.

Minimal would mean that beyond PURL (and may be a version range for depsn) no other metadata, no license detection and no complex assembly, nor package files or package instance creation would be needed.

This could be a new `--purl` scan option, with a skinny output data structure to design.

**Comment by AyanSinhaMahapatra** [comment]
> with a skinny output data structure to design.

Do you mean only populating the fields necessary as discussed above in the existing package_data/packages data structure to get the PURLs from them. And then have a new top level skinny data structure containing all the PURLs?

**Comment by AyanSinhaMahapatra** [comment]
This was added with https://github.com/nexB/scancode-toolkit/pull/3689, closing!
