### ISSUE TITLE
Improve the text and detection rules associated with cmu-uc

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3491]
The license text of cmu-uc contains specific references to various copyright holders that do not reflect the usage of the very same license in code copyrighted by other holders. Note that the SPDX posting of this license, MIT-CMU, does not contain those references, but uses the more generic phrase "the copyright holders".   Please change the license text to the following, and update the SCTK license detection rules appropriately.

Permission to use, copy, modify and distribute this software and its documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appears in all copies and that both that copyright notice and this permission notice appear in supporting documentation, and that the names of the copyright holders not be used in advertising or publicity pertaining to distribution of the software without specific written permission.

THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM THE LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   one more change please. The original posting of this license in the Fedora list calls it "CMU Style".  Please use "CMU Style" for both the full name and the short name.   Thanks. 

https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing%2FMIT#CMU_Style

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark thanks!
the license text is fixed above ^
and the name changes are already there at https://scancode-licensedb.aboutcode.org/cmu-uc.html
closing!
