### ISSUE TITLE
Support for common ignore (svn, git, etc)

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#35]
Broken down from  @K-Rex #33

I want to use -c -l to scan, but it scan all the files like .c .h and all, I don't want to scan .svn/ directory. How can I do?

**Comment by pombredanne** [comment]
@K-Rex .svn directories should be excluded alright and this is a bug because this features has not been activated by default. 

The function to iterate files: https://github.com/nexB/scancode-toolkit/blob/master/src/commoncode/fileutils.py#L290 can accept ignores. in the same way you have svn or git ignores. 

There is a whole module for ignores just there: https://github.com/nexB/scancode-toolkit/blob/master/src/commoncode/ignore.py

What if we add an --ignore command line option to point to an ignore file and we add a default to  ignore the common version control subdirectories and files that are listed here?
https://github.com/nexB/scancode-toolkit/blob/master/src/commoncode/ignore.py#L175

**Comment by K-Rex** [comment]
I had known ignore list before, but I don't know how to fix it. 
You fixed this issue below link "Ignore version control artifacts by default when scanning. #35" ?
I think it a good idea to add --ignore command.
Thank you very much.

**Comment by pombredanne** [comment]
@K-Rex:  can you try download the latest from the develop branch here:
https://github.com/nexB/scancode-toolkit/archive/332acf2d13cc7997432a86a0ca077f17ca5c7eb6.tar.gz
This fix should ignore by default the version control directories such as .svn or .git.

Tell me if this works and I will push a new release

**Comment by pombredanne** [comment]
@K-Rex The latest https://github.com/nexB/scancode-toolkit/releases/tag/v1.3.0 ignores VCS files by default now.
I am starting a new ticket #36 to implement configurable ignore with a `--ignore` option
