### ISSUE TITLE
Copyright holder name lacks legal entity in some cases

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#351]
In some cases the Copyright holder name lack the legal entity. For example, given the line

    Copyright (c) 2016 HERE Europe B.V.

(which is part of an MIT license), ScanCode 2.0.0.rc1 detects

      "copyrights": [
        {
          "statements": [
            "Copyright (c) 2016 HERE Europe"
          ], 
          "holders": [
            "HERE Europe"
          ], 
          "authors": [], 
          "start_line": 3, 
          "end_line": 3
        }
      ], 

As you can see, both the statement and the holder lack the `B.V.` which denotes the [legal entity](https://en.wikipedia.org/wiki/Besloten_vennootschap_met_beperkte_aansprakelijkheid), and as such is quite important to have as part of the holder name.

**Comment by pombredanne** [comment]
@sschuberth Thanks for the report. #351 should fix this. If you can check if this work for you, I will merge it in.

**Comment by pombredanne** [comment]
Fixed and verified.
