### ISSUE TITLE
Are the compiled executables available for download?

### ISSUE THREAD

**Issue by SoftCircuits** [nexB/scancode-toolkit#3514]
Are the compiled executables available for download anywhere? I'm a developer but I have no tools for Python. I'm looking for Windows builds.

**Comment by mjherzog** [comment]
You can download the Windows installation package from: https://github.com/nexB/scancode-toolkit/releases/tag/v32.0.6.
The current release will work with Python 3.7, 3.8, 3.9 or 3.10.

**Comment by SoftCircuits** [comment]
@mjherzog Thanks, but I couldn't find any EXE files in that download. Am I going to have to compile it myself?

**Comment by mjherzog** [comment]
No - you extract the files and run a configure program - see https://scancode-toolkit.readthedocs.io/en/stable/getting-started/install.html#installation-on-windows-10

**Comment by SoftCircuits** [comment]
@mjherzog I don't understand why I'm having so much trouble with this. I downloaded and unzipped *scancode-toolkit-v32.0.6_py3.11-windows.zip*, The instructions you linked to state *On Windows 10, double-click the new folder, select one of the files inside the folder (e.g., ‘setup.py’), and right-click.* But, in fact, there is no *setup* file in the package.

So I ran `scancode -h`. And I got the following.

```
C:\Users\jwood\source\repos\rjmartino\usrailandlogistics\ScancodeToolkit>scancode -h
* Configuring ScanCode for first use...
* WARNING: Native Windows may be deprecated in the future in favor of Windows Subsystem for Linux 2
* WARNING: Please visit https://github.com/nexB/scancode-toolkit/issues/2366 for details and to provide feedback
'py' is not recognized as an internal or external command,
operable program or batch file.
```

As an executable, I'm expecting an EXE file. So at this point, I really don't know what I'm supposed to be looking for or why it doesn't work.

**Comment by chinyeungli** [comment]
Hi @SoftCircuits , can you verify that you have the python3.11 installed in your system?
https://www.python.org/downloads/release/python-3110/

**Comment by SoftCircuits** [comment]
@chinyeungli As I explained in my first post, I have no tools for Python. This is *exactly* why I was asking about an already compiled version of the tool... Because I don't program with Python, I have no tools for Python, and I don't particularly want to.

In the tools I use (C#, C++, etc.), I am able to produce executable files that will run without the user having a compiler or other tools. That's what I am looking for.

**Comment by mjherzog** [comment]
ScanCode Toolkit and our other tools all require Python - it is our primary language.
We have no plans to change that.

**Comment by SoftCircuits** [comment]
@mjherzog Like I said, I have no plans to change my tools either. But I can still produce an executable. But I don't know enough about Python to know why that is difficult. Can Python not compile?

**Comment by mjherzog** [comment]
Python is an interpretative language. You do not compile code in the way that you do for C/C++.
