### ISSUE TITLE
Wrong license detection for Jacoco

### ISSUE THREAD

**Issue by bennati** [nexB/scancode-toolkit#3515]
Scancode detects license https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/ace-tao_5.RULE
in file https://github.com/jacoco/jacoco/blob/master/LICENSE.md (line 13)

Tested with Scancode 32.0.6

ran the command `scancode jacoco/LICENSE.md --license --license-text --license-text-diagnostics --license-diagnostics --license-references --json-pp o.json`

Attached json output 
[o.json.zip](https://github.com/nexB/scancode-toolkit/files/12657809/o.json.zip)

**Comment by AyanSinhaMahapatra** [comment]
@bennati Thanks for the report!
I've added/updated rules and heuristics to account for this case and other cases like this.

**Comment by AyanSinhaMahapatra** [comment]
fixed, closing!
