### ISSUE TITLE
mpl-1.1 detected incorrectly (false positive)

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3516]
A recent scan of  opentofu-main.zip (there are no tags or releases) 
from https://github.com/opentofu/opentofu 
returned mpl-2.0 correctly but also mpl-1.1 incorrectly.  Here is what I found in the scan results:

```
rules/mpl-1.1_38.RULE",          "start_line": 31,          "matched_text": "License\n\n[Mozilla",          "match_coverage": 100.0,          "matched_length": 2,          "rule_relevance": 90,          "rule_identifier": "mpl-1.1_38.RULE",          "license_expression": "mpl-1.1"        },        {          "score": 100.0, 
```
It seems to me that the matched_text of "License\n\n[Mozilla" is not adequate to detect mpl-1.1.  

I think that `mpl-1.1_38.RULE` should probably be removed altogether. 

Scan results attached.  
[opentofu-main.zip_scan.json.zip](https://github.com/nexB/scancode-toolkit/files/12675795/opentofu-main.zip_scan.json.zip)

**Comment by AyanSinhaMahapatra** [comment]
I've added a rule to add this specific case, and now the detection looks like this:

```
{
          "license_expression": "mpl-2.0",
          "matches": [
            {
              "score": 33.0,
              "start_line": 32,
              "end_line": 34,
              "matched_length": 6,
              "match_coverage": 100.0,
              "matcher": "2-aho",
              "license_expression": "mpl-2.0",
              "rule_identifier": "mpl-2.0_133.RULE",
              "rule_relevance": 33,
              "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/mpl-2.0_133.RULE",
              "matched_text": "License\n\n[Mozilla Public License v2.0]("
            }
          ],
          "detection_log": [],
          "identifier": "mpl_2_0-4684e725-dab2-6f1f-26cc-70db3181a40a"
        }
```

The `mpl-1.1_38.RULE` seems pretty harmless otherwise and would match some cases atleast, specially in license tags in manifests which are often short and to the point. We can reduce the score maybe?

**Comment by AyanSinhaMahapatra** [comment]
Fixed, closing!
Thanks @DennisClark
