### ISSUE TITLE
proprietary-license incorrectly detected (false positive) 

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3518]
A recent scan of opentofu-main.zip (there are no tags or releases)
from <https://github.com/opentofu/opentofu>
returned proprietary-license incorrectly.  Here is what I found in the scan results:

"https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/proprietary-license_276.RULE",          "start_line": 31,          "matched_text": "\t// function may not be modified after calling this since they can be",          "match_coverage": 100.0,          "matched_length": 4,          "rule_relevance": 100,          "rule_identifier": "proprietary-license_276.RULE",          "license_expression": "proprietary-license"        }  

It seems to me that the matched_text "\t// function may not be modified after calling this since they can be"  has nothing to do with licensing, and is more likely code comments regarding code logic and how it should be used.  

proprietary-license_276.RULE  needs to be investigated and probably removed.

**Comment by DennisClark** [comment]
[opentofu-main.zip_scan.json.zip](https://github.com/nexB/scancode-toolkit/files/12675999/opentofu-main.zip_scan.json.zip)

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark I've:
* added a false positive rule specific to this case, and
* also updated the proprietary-license_276.RULE as a license clue

so this should not show up as a detection anymore, and in future cases like this, it would show up as a clue instead.
Note that this rule is often used to detect license clauses, so completely removing it may not be the best option here.

**Comment by AyanSinhaMahapatra** [comment]
This is added and fixed, closing!
