### ISSUE TITLE
There is a weird `?` in 3dslicer-1.0 text

### ISSUE THREAD

**Issue by maxhbr** [nexB/scancode-toolkit#3521]
See: 

https://github.com/nexB/scancode-toolkit/blob/9e4d706c0c592f1415e16534f0637b4e227d4791/src/licensedcode/data/licenses/3dslicer-1.0.LICENSE#L105
Souldn't that be `Women's`?

**Comment by AyanSinhaMahapatra** [comment]
Thanks for the report @maxhbr , it's also present in the original text at: https://github.com/Slicer/Slicer/blob/v5.4.0/COPYRIGHT.txt#L97, so we should report it upstream for fixing too?
No use of fixing it here first, if the corrected version doesn't exist anywhere in the wild.

**Comment by maxhbr** [comment]
Thx
