### ISSUE TITLE
Add MIT-testregex and flag it as such

### ISSUE THREAD

**Issue by omajid** [nexB/scancode-toolkit#3530]
### Description

SPDX has formalized this license as MIT-testregex:

https://github.com/spdx/license-list-XML/pull/2058

Scancode currently identifies this license as "other-permissive".  Would it be possible to identify it as mit-testregex (to match SPDX) or as an MIT variant?

### How To Reproduce

Scan one of the following files:

- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/AttRegexTests.cs
- https://go.dev/src/regexp/testdata/testregex.c
- https://opensource.apple.com/source/Libc/Libc-1353.60.8/tests/regex/testregex.c.auto.html
- https://android.googlesource.com/platform/external/rust/crates/regex-automata/+/refs/heads/master/data/fowler-tests/LICENSE

Scancode should classify this as MIT (or, better as MIT-testregx, to match SPDX).

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? scancode-toolkit 32.0.6
* What installation method was used to install/run scancode? pip

**Comment by DennisClark** [comment]
The license `MIT-testregex` has not yet been published to the SPDX License List, which is currently at Version: 3.21 2023-06-18.  It has been approved, per the PR that you provided, and has been added to the 3.22 milestone.  ScanCode will recognize all new licenses on the SPDX list when a new milestone version is published.

**Comment by pombredanne** [comment]
FWIW, we have been tracking and detecting this for several years as a generic "other-permissive" detection rule at https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/other-permissive_141.RULE and this rule (may be other related ones) will need to be updated when this happens.
@AyanSinhaMahapatra did we decide anything wrt. to updating rules vs. just considering them as immutable and deprecated and instead create new ones?

**Comment by DennisClark** [comment]
@omajid  @pombredanne  @AyanSinhaMahapatra     See #3541  for SPDX License List 3.22  details.

**Comment by DennisClark** [comment]
@omajid   please see https://scancode-licensedb.aboutcode.org/mit-testregex.html

**Comment by AyanSinhaMahapatra** [comment]
> did we decide anything wrt. to updating rules vs. just considering them as immutable and deprecated and instead create new ones?

We are always preserving this rules by deprecating them so they are immutable as identifiers.

This is added, so closing this.
Thanks @pombredanne @DennisClark @omajid
