### ISSUE TITLE
suggestion: rename "vince license" to "MIT (SEI)"

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#3536]
### Description

When scanning https://github.com/CERTCC/labyrinth/blob/main/LICENSE the "vince license" is reported:

```
  "files": [
    {
      "path": "LICENSE",
      "type": "file",
      "detected_license_expression": "vince",
      "detected_license_expression_spdx": "LicenseRef-scancode-vince",
      "license_detections": [
        {
          "license_expression": "vince",
          "matches": [
            {
              "score": 79.38,
              "start_line": 7,
              "end_line": 54,
              "matched_length": 335,
              "match_coverage": 79.38,
              "matcher": "3-seq",
              "license_expression": "vince",
              "rule_identifier": "vince.LICENSE",
              "rule_relevance": 100,
              "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/vince.LICENSE"
            }
          ],
          "identifier": "vince-3800b723-5aed-08d0-b1b9-f981030737d5"
        }
      ],
      "license_clues": [],
      "percentage_of_license_text": 74.12,
      "scan_errors": []
    }
  ]

```

I believe that the name "vince license" should be change, also because it overlaps with this one which was added earlier:

https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/mit_and_unknown-license-reference_3.RULE

The header of the "vince license" clearly says `MIT (SEI)`, as do the other ones.

**Comment by DennisClark** [comment]
Sorry @armijnhemel  but I would prefer not to change the name of this license.  The text at https://github.com/CERTCC/VINCE/blob/main/LICENSE.txt starts with 

```
VINCE

Copyright 2023 Carnegie Mellon University.

MIT (SEI)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal ...
```

so naming the license VINCE is arguably justified, even if it is simply the name of the associated project, but the name VINCE is used repeatedly in the license text.  On the other hand, the acronym "SEI" is quite obscure, and one has to pay really close attention and dig a bit to discover that it means "Software Engineering Institute", a rather weak identification since it does not indicate that this rather generically named institute is actually part of Carnegie Mellon University, so "SEI" does not really provide much value as part of a license name.  

Thanks for using SCTK!

**Comment by armijnhemel** [comment]
I think you might have misunderstood what I was saying: the license at https://github.com/CERTCC/labyrinth/blob/main/LICENSE is very very similar to the "vince license", as it is also from CMU/SEI and only differs in a few places, most notably the name of the package, the locations of the README. Otherwise they appear to be the same license.

So what I intended to say: both this license and the vince license are an instance of the generic "MIT (SEI)" license, which was already included (somewhat) here: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/mit_and_unknown-license-reference_3.RULE

Currently the license for labyrinth repository search is detected as "vince license" and that is incorrect.

@pombredanne

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra    Please change the Name and Short Name of license with key `vince` to `MIT (SEI)` in SCTK and the LicenseDB

**Comment by armijnhemel** [comment]
> @AyanSinhaMahapatra Please change the Name and Short Name of license with key `vince` to `MIT (SEI)` in SCTK and the LicenseDB

You probably also want to look at what the variable parts of the license text are, also see #3538

**Comment by AyanSinhaMahapatra** [comment]
The update was done and is available at https://scancode-licensedb.aboutcode.org/vince.html
thanks @DennisClark @armijnhemel
