### ISSUE TITLE
Add new Clojure GPL exception

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3540]
This looks like this:
The exception first showed up in metabase in 2015 in this commit https://github.com/metabase/metabase/blob/666b1b453a71a1fca19e7b81739a58ce7fa45a14/LICENSE.txt#L663-L665

```
Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or combining it with any of the below libraries (or a modified version of that library), containing parts covered by the terms of any of the below libraries, the licensors of this Program grant you additional permission to convey the resulting work.

....
```
The list of paths and files that follows the exception varies though, but the presence of clojure is common. This exception is seen applied to the AGPL mostly but references the GPL.

Other places:
- https://github.com/elifesciences/elifesciences-publications-repository-archiver/blob/312e7a8dc7a952d878cc7af3c735e256184f366b/LICENCE.txt#L678-L684
- https://github.com/howonlee/mertonon/blob/7530a68b8a7276e2427cf05b5cac648a2bbbdcb9/license.md?plain=1#L11-L13
- https://github.com/metabase/metabase/blob/24b35534722fbdc3c4201bb81e0f6f130f6acfd6/LICENSE-AGPL.txt#L664-L667
- https://github.com/howonlee/mertonon/blob/7530a68b8a7276e2427cf05b5cac648a2bbbdcb9/license.md?plain=1#L11-L13

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   please add new license exception

key: clojure-exception-to-gpl-3.0
name: Clojure Exception to GPL-3.0
short name: Clojure Exception to GPL-3.0
owner: Metabase
category: Copyleft

text: 
Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or combining it with any of the below libraries (or a modified version of that library), containing parts covered by the terms of any of the below libraries, the licensors of this Program grant you additional permission to convey the resulting work.

notes:
This exception first showed up in metabase in 2015. The list of paths and files that follows the exception varies in actual use, but the presence of Clojure is common to the list. This exception is also seen applied to the AGPL but usually references GPL-3.0.

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark this license was added and is available at https://scancode-licensedb.aboutcode.org/clojure-exception-to-gpl-3.0.html, also added some rules for the various occurances above.
