### ISSUE TITLE
gpl-2.0 incorrectly detected in the zeromq/libzmq-4.3.5 README

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3544]
A recent scan of https://github.com/zeromq/libzmq/archive/refs/tags/v4.3.5.tar.gz  returns gpl-2.0 as one of the detected licenses in the README file.  

The culprit appears to be https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/gpl-2.0_1076.RULE  which probably needs to be adjusted to have more required text, since the README is clearly indicating the Mozilla Public License 2.0.  Scan results attached. 

[libzmq-4.3.5.tar.gz_scan.json.zip](https://github.com/nexB/scancode-toolkit/files/12848167/libzmq-4.3.5.tar.gz_scan.json.zip)

**Comment by AyanSinhaMahapatra** [comment]
Fixed with commits above ^ see scan results attached too.
Thanks @DennisClark 
[libzmq-4.3.5-scan-results.json.txt](https://github.com/nexB/scancode-toolkit/files/13365193/libzmq-4.3.5-scan-results.json.txt)
