### ISSUE TITLE
Dead links in the generated licensedb

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3546]
The edit text/edit data is obsolete as there is only one file now. See https://github.com/nexB/scancode-toolkit/edit/develop/src/licensedcode/data/licenses/lzma-sdk-2008.yml for instance which is the edit data link https://scancode-licensedb.aboutcode.org/lzma-sdk-2008.html
We should have only one edit link.

**Comment by AyanSinhaMahapatra** [comment]
This is fixed by the commit above, closing!
