### ISSUE TITLE
False positive for Apache 2.0 / MPL 1.1 dual license

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#355]
Using ScanCode 2.0.0rc2, [this file](https://github.com/heremaps/here-aaa-java-sdk/blob/master/examples/here-oauth-client-example/src/main/java/com/here/account/oauth2/tutorial/GetHereClientCredentialsAccessTokenTutorial.java) triggers a false positive for an Apache 2.0 / MPL 1.1 dual license. As you can see from the boiler plate, the file is licensed under Apache 2.0 only.

The funny thing is that the MPL-1.1 license is listed to start at line 4, i.e. within the Apache 2.0 boiler plate text. But if I remove everything in the file *except* the Apache 2.0 boiler plate, ScanCode report an accurate match of just Apache 2.0.

**Comment by pombredanne** [comment]
@sschuberth If I use the latest from the develop branch I cannot reproduce this. I merged recently quite a few fixes and this likely caught this. I added a test anyway.

**Comment by pombredanne** [comment]
The updates from #353 that fixed your issue are likely some of these rules that were refined and detected a dual apache/mpl:
- https://github.com/nexB/scancode-toolkit/pull/353/files#diff-c49e188d04e9a924ce8159e4a558f81e
- https://github.com/nexB/scancode-toolkit/pull/353/files#diff-ed33010ec2f92e44f7dae55ae6472b05

**Comment by sschuberth** [comment]
Confirmed that the very latest *develop* branch (ead7599) fixes the issue, my fork was still at 50eaeec. Thanks!
