### ISSUE TITLE
Convert license rule to warranty disclaimer

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3557]
This https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/free-unknown_1.RULE (copied below) and may be a few other commonly seen in Autotools build scripts should not be unknown, but rather a mere warranty disclaimer:

```YAML
---
license_expression: free-unknown
is_license_notice: yes
notes: typically for GPL but this can vary and be various versions
---

This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
```

**Comment by pombredanne** [comment]
Same for https://github.com/nexB/scancode-toolkit/blob/1c4d6bedd7bd40f21fbd9818db6e1864d0fe77b5/src/licensedcode/data/rules/free-unknown_3.RULE

**Comment by pombredanne** [comment]
Another case is https://github.com/nexB/scancode-toolkit/blob/1c4d6bedd7bd40f21fbd9818db6e1864d0fe77b5/src/licensedcode/data/rules/free-unknown_4.RULE where this is at best a license clue and not a clear license statement.

**Comment by AyanSinhaMahapatra** [comment]
These are addressed by https://github.com/nexB/scancode-toolkit/pull/3584
3 rules linked are either marked as deprecated or license clue.
Closing this
