### ISSUE TITLE
Convert other-permissive_320.RULE to detect an actual license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3569]
This https://git.savannah.gnu.org/gitweb/?p=libidn.git;a=blob;f=lib/punycode.c;h=14d70152b9c5723778af174ff6027cc3742b749e;hb=HEAD#l54 is treated as a rule in https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/other-permissive_320.RULE
Libidn (and this punycode code) is frequent enough that it would be best to have a named license for this

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   please replace this rule with one that points to a new license

key: punycode
name: Punycode License
owner: nicemice
category: permissive
homepage:  [https://git.savannah.gnu.org/gitweb/?p=libidn.git;a=blob;f=lib/punycode.c;h=14d70152b9c5723778af174ff6027cc3742b749e;hb=HEAD#l54](https://git.savannah.gnu.org/gitweb/?p=libidn.git%3Ba%3Dblob%3Bf%3Dlib%2Fpunycode.c%3Bh%3D14d70152b9c5723778af174ff6027cc3742b749e%3Bhb%3DHEAD#l54)

```
Disclaimer and license: Regarding this entire document or any
portion of it (including the pseudocode and C code), the author
makes no guarantees and is not responsible for any damage resulting
from its use.  The author grants irrevocable permission to anyone
to use, modify, and distribute it in any way that does not diminish
the rights of anyone else to use, modify, and distribute it,
provided that redistributed derivative works do not contain
misleading author or version information.  Derivative works need
not be licensed under similar terms.
```

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark thanks, this is added with https://github.com/nexB/scancode-toolkit/pull/3586
