### ISSUE TITLE
Convert other-permissive_97.RULE to detect bsd-credit

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3571]
Instead of `other-permissive` the other-permissive_97.RULE should detect `bsd-credit`

https://scancode-licensedb.aboutcode.org/bsd-credit.html

Note that some instances in the wild of the license truncate the warranty disclaimer, but the first two paragraphs should be sufficient to identify `bsd-credit` : 

```
Permission to use, copy, modify, and distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright notice
and this permission notice appear in all copies.

Modification and redistribution in source and binary forms is permitted provided
that due credit is given to the author and the OpenBSD project (for instance by
leaving this copyright notice intact).
```

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark 
I've added a rule for the `bsd-credit` LICENSE with the two paragraphs above.
But the rule you've mentioned above: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/other-permissive_97.RULE does not seem to have the above two paragraphs, and also does not have anything related to the credit line (`due credit is given to the author and the OpenBSD project`) 
```
This is a free software and is opened for education,
research and commercial developments under license policy of following trems.


* The  module is a free software and there is NO WARRANTY.
* No restriction on use. You can use, modify and redistribute it for
  personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
* Redistributions of source code must retain the above copyright notice.
```
Are you sure we want to requialify this as `bsd-credit`

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra    I'll investigate this later today and get back to you.  Thanks for the comments.

**Comment by DennisClark** [comment]
I think I made a big copy+paste mistake, my bad.   Trying to sort that out now ...

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   I think we need a new license for https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/other-permissive_97.RULE     
Please add the following license; if it already exists under another key (which i have not been able to find) please let me know. 

key: ugui
name: UGUI License
owner: Achim Doebler
category: Permissive
homepage: https://github.com/achimdoebler/UGUI 
other: https://raw.githubusercontent.com/achimdoebler/UGUI/master/LICENSE.md 

notes: 
Copyright (C) 2015, Achim Döbler, all rights reserved.
URL: http://www.embeddedlightning.com/

text: 
This is a free software and is opened for education,
research and commercial developments under license policy of following terms.

* The  module is a free software and there is NO WARRANTY.
* No restriction on use. You can use, modify and redistribute it for
  personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
* Redistributions of source code must retain the above copyright notice.


@AyanSinhaMahapatra    also please correct the spelling error in the RULE, which should be `terms` instead of `trems` . 

Thanks!

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark added this and deprecated the rule. Thanks!
