### ISSUE TITLE
Convert rule to other-permissive or create new license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3578]
See https://github.com/nexB/scancode-toolkit/blob/1c4d6bedd7bd40f21fbd9818db6e1864d0fe77b5/src/licensedcode/data/rules/free-unknown_2.RULE

    This source code is freely redistributable and may be used for
    any purpose.  This copyright notice must be maintained. 
    Lance Norskog And Sundry Contributors are not responsible for 
    the consequences of using this software.

This is not unknown. Alternatively this could be made a license of its own as this is frequent enough based on https://github.com/search?q="Lance+Norskog+And+Sundry+Contributors"&type=code 

@DennisClark @AyanSinhaMahapatra

**Comment by DennisClark** [comment]
this could be made a license of its own. stay tuned.

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   Please create a new license: 

key: lance-norskog-license
name: Lance Norskog License
category: Permissive
Other URLs: 
https://github.com/LanceNorskog
https://github.com/search?q=%22Lance+Norskog+And+Sundry+Contributors%22&type=code
text: 
This source code is freely redistributable and may be used for
any purpose.  This copyright notice must be maintained. 
Lance Norskog And Sundry Contributors are not responsible for 
the consequences of using this software.

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark Thanks, this is added at https://github.com/nexB/scancode-toolkit/pull/3586/files

**Comment by AyanSinhaMahapatra** [comment]
This is now added at https://github.com/nexB/scancode-toolkit/pull/3586, thanks @pombredanne @DennisClark
