### ISSUE TITLE
test_dump_rule_file depends on OS filename sorting

### ISSUE THREAD

**Issue by licquia** [nexB/scancode-toolkit#3581]
### Description

The test `TestRule.test_dump_rule_file` in `tests/licensedcode/test_models.py` appears to rely on the native OS to sort directory listings when finding rule files to compare.  On my system (Debian 12), this results in the test attempting to compare a rule file for GPL 2.0 to a rule file for the LZMA license, which obviously fails.  Sorting the results of `models.load_rules()` for each fixes the problem.

### How To Reproduce

```
git checkout develop
./configure --dev
venv/bin/py.test -n6
```

### System configuration

* What OS are you running on? (Windows/MacOS/Linux)
** Linux, specifically Debian 12
* What version of scancode-toolkit was used to generate the scan file?
** The develop branch (specifically, commit 1c4d6bed)
* What installation method was used to install/run scancode? (pip/source download/other)
** Checkout from GitHub

**Comment by pombredanne** [comment]
Thanks! I wonder if there is something special with Debian 12 and the file system encoding? @AyanSinhaMahapatra we likely want to add Debian 12 as a CI target.

**Comment by licquia** [comment]
I'm not sure; my guess was that it was simply unsorted by default, since the results from the debugger showed the files being reported in what seemed like a random order.  For what it's worth, it's a brand-new install (never upgraded from a previous version of Debian), and here are the mount flags pasted from `sudo mount` for the root FS and /tmp:

        /dev/nvme0n1p2 on / type ext4 (rw,noatime,discard)
        tmpfs on /tmp type tmpfs (rw,noatime,inode64)

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne yes, we have https://github.com/nexB/scancode-toolkit/issues/2731 open to also have debian in CI
