### ISSUE TITLE
Query on installing python and other packages on Redhat linux system to run scancode

### ISSUE THREAD

**Issue by Ahmed-A-Syed** [nexB/scancode-toolkit#359]
Hi,

We were planning to install scancode-toolkit on Redhat linux system. As per the wiki, to run scancode-toolkit, we need Python 2.7 "devel" and a few extra packages:
1) My question is running the below command (as mentioned in wiki) is sufficient? Does it install python 2.7 devel version and other packages?bcoz the below command doesnt mention any python version?  
        **sudo yum install python-devel zlib bzip2-libs xz-libs libxml2-devel libxslt-devel** 

(or) Do i need to run other command to install python 2.7 devel and extra packages?

**Note:** we dont have access to run this command or install on the machine, so unix team will install or run the command. so i need to give them specific command to run so that required python 2.7 devel and few extra packages gets downloaded to run scancode-toolkit successfully on linux

2) can i install the python and other packages in my custom directory like **root/app/myworkspace/** or installation of python and packages are to be done at any specific linux folder directory like installation of python in **C:drive on windows**?

As am new to scancode and linux systems. Can you help me on clarifying this questions?

**Comment by pombredanne** [comment]
1. This should install Python 2.7 on recent RedHat versions. Which version do you run?
And what would be the output of running:
`yum search python | grep -i "python-devel"`

2. It may be possible to do user installation of RPMs (see for instance this https://www.cyberciti.biz/tips/how-to-extract-an-rpm-package-without-installing-it.html ) but thus is likely  not something for the faint of heart.

Now there is a good chance that your version of RedHat has already a Python 2.7 installed.
Could you run `python -v` and report the output?

Beside this is a link to install Python 2.7 on RH7 or 6: http://developers.redhat.com/products/rhel/get-started-rhel7-python/

And also on Centos 6 (and possibly RH6 too) these instructions are linked in ScanCode readme to build Python 2.7 from sources: https://github.com/nexB/attributecode/wiki/BuildingPython27OnCentos6

**Comment by Ahmed-A-Syed** [comment]
**> yum search python | grep -i devel**
*Note* Red Hat Network repositories are not listed below. You must run this command as root to access RHN repositories.
python27-tools.x86_64 : A collection of development tools included with Python

**python -v**
Python 2.6.6 (r266:85192, May 22 2015, 08:34:51)

**Comment by pombredanne** [comment]
So I reckon this must an older RH6, is this correct?

**Comment by pombredanne** [comment]
Sorry I just your message at the same I was replying.

**Comment by pombredanne** [comment]
So the resolution to install Python 2.7 on RHEL 6 should be this exactly: https://github.com/nexB/attributecode/wiki/BuildingPython27OnCentos6

**Comment by pombredanne** [comment]
It requires to compile it, unless somehow RedHat provides it otherwise, but not having a commercial subscription to RH I cannot tell.

**Comment by Ahmed-A-Syed** [comment]
https://github.com/nexB/attributecode/wiki/BuildingPython27OnCentos6. Its difficult from our side to convince them to do all the steps mentioned in the link .they will not do it

does the command - sudo yum install python-devel zlib bzip2-libs xz-libs libxml2-devel libxslt-devel is not compatible with RHEL 6.7 version.

**Comment by Ahmed-A-Syed** [comment]
there is no such information in the wiki which states that the command works only on recent redhat linux version :(

**Comment by Ahmed-A-Syed** [comment]
i even tried to install it on windows to test scancode .but it even doesnt work on windows . raised an issue #362

**Comment by pombredanne** [comment]
So about installing Python 2.7 on RHEL, this is to the best of my knowledge the only way. If you cannot compile a package, then you would need to find a prebuilt Python 2.7 package for RHEL.  

You also wrote:
> does the command - sudo yum install python-devel zlib bzip2-libs xz-libs libxml2-devel libxslt-devel is not compatible with RHEL 6.7 version.

Are you saying this did not work? This has been tested on CentOS and CentOS is derived from RHEL so this should work. If it does not I do not know what could.

May be you can try this?

http://developers.redhat.com/blog/2013/02/14/setting-up-django-and-python-2-7-on-red-hat-enterprise-6-the-easy-way/

**Comment by pombredanne** [comment]
And this too? https://www.softwarecollections.org/en/scls/rhscl/python27/

**Comment by pombredanne** [comment]
Otherwise, my instructions are essentially the same as these: http://tecadmin.net/install-python-2-7-on-centos-rhel/ e.g. compile from sources.

**Comment by Ahmed-A-Syed** [comment]
I think we both are on wrong page. 

My current linux machine environment is 
1)  Red Hat Enterprise Linux Server release 6.7
2)  python 2.6.6 (my machine already contains it)

Now i want to run scancode-toolkit on my linux machine, so my question is does running the below command works and sufficient enough to run everything successfully (or) do i face any problems?

**Note :** i havent used this command yet on my linux machine. Before running this command on my current machine, i want to know from you that running the below command will suits my current environment?
      sudo yum install python-devel zlib bzip2-libs xz-libs libxml2-devel libxslt-devel


If it doesnt work, can i install python27 devel and packages separately like below

      sudo yum install python27-devel
      sudo yum install zlib bzip2-libs xz-libs libxml2-devel libxslt-devel

**Comment by pombredanne** [comment]
@Ahmed-A-Syed if you have a Python 2.7 package from your package repos, then running:
`sudo yum install zlib bzip2-libs xz-libs libxml2-devel libxslt-devel python27-devel` should be enough. It has been tested on CentOS 6 which is derived from RHEL 6.

Otherwise, you need to build Python 2.7 from sources following:  https://github.com/nexB/attributecode/wiki/BuildingPython27OnCentos6

**Comment by Ahmed-A-Syed** [comment]
okay.. will let u know in few days

**Comment by pombredanne** [comment]
@Ahmed-A-Syed Is everything OK on your side now? I just want to make sure before closing this ticket for good.

**Comment by Ahmed-A-Syed** [comment]
@pombredanne : Sorry for being late. today they installed the python devel and other packages. our yum repo contains _python27-python-2.7.8-18._ so they installed the same. will the installed version is sufficient to run scancode-toolkit on Linux successfully. Or do we need explicitly python _2.7.10 or 2..7.12_ . please clarify on this and can close the ticket.

**Comment by pombredanne** [comment]
@Ahmed-A-Syed Python 2.7.8 should work just fine!

**Comment by pombredanne** [comment]
@Ahmed-A-Syed Was everything working for you? I would like to close this

**Comment by Ahmed-A-Syed** [comment]
Yes, you can close this.! forgot to close the issue
