### ISSUE TITLE
Do not crash with Cargo workspaces

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3598]
We need to support correctly workspaces:
https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

> A workspace is a set of packages that share the same Cargo.lock and output directory. 

Here is an example: https://github.com/tauri-apps/tauri/blob/dev/Cargo.toml

**Comment by AyanSinhaMahapatra** [comment]
This is fixed with #3602 

See scan below:
[tauri-dev-scan-results.json.txt](https://github.com/nexB/scancode-toolkit/files/13430735/tauri-dev-scan-results.json.txt)
