### ISSUE TITLE
Reference to MIT not detected

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#360]
[This file](https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/AdditionalAnswers.java) from mockito contains

    /*
     * Copyright (c) 2007 Mockito contributors
     * This program is made available under the terms of the MIT License.
     */

However, ScanCode 2.0.0rc2 (ead75993dadf20f86d2a62b946d3d96763f10b97) does not detect this license reference, only the copyright:

    {
      "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "scancode_version": "2.0.0rc2",
      "files_count": 1,
      "files": [
        {
          "path": "AdditionalAnswers.java",
          "licenses": [],
          "copyrights": [
            {
              "statements": [
                "Copyright (c) 2007 Mockito contributors"
              ],
              "holders": [
                "Mockito contributors"
              ],
              "authors": [],
              "start_line": 2,
              "end_line": 3
            }
          ],
          "packages": []
        }
      ]
    }

**Comment by pombredanne** [comment]
Thanks for the report! the latest push fixes and should be merged shortly in develop and covers also #361

**Comment by pombredanne** [comment]
Fixed and merged.
