### ISSUE TITLE
False positives reported for netty project

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#361]
ScanCode 2.0.0rc2 (ead75993dadf20f86d2a62b946d3d96763f10b97) reports for [CRC32.java](https://github.com/netty/netty/blob/netty-3.9.2.Final/src/main/java/org/jboss/netty/util/internal/jzlib/CRC32.java) from netty-3.9.2.Final to contain `Apache-2.0`, `BSD-3-Clause` and `BSD-2-Clause`:

    {
      "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "scancode_version": "2.0.0rc2",
      "files_count": 1,
      "files": [
        {
          "path": "CRC32.java",
          "licenses": [
            {
              "key": "apache-2.0",
              "score": 100.0,
              "short_name": "Apache 2.0",
              "category": "Attribution",
              "owner": "Apache Software Foundation",
              "homepage_url": "http://www.apache.org/licenses/",
              "text_url": "http://www.apache.org/licenses/LICENSE-2.0",
              "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:apache-2.0",
              "spdx_license_key": "Apache-2.0",
              "spdx_url": "http://spdx.org/licenses/Apache-2.0",
              "start_line": 4,
              "end_line": 14,
              "matched_rule": {
                "identifier": "apache-2.0_36.RULE",
                "license_choice": false,
                "licenses": [
                  "apache-2.0"
                ]
              }
            },
            {
              "key": "bsd-new",
              "score": 95.74,
              "short_name": "BSD-Modified",
              "category": "Attribution",
              "owner": "Regents of the University of California",
              "homepage_url": "http://www.opensource.org/licenses/BSD-3-Clause",
              "text_url": "",
              "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:bsd-new",
              "spdx_license_key": "BSD-3-Clause",
              "spdx_url": "http://spdx.org/licenses/BSD-3-Clause",
              "start_line": 19,
              "end_line": 30,
              "matched_rule": {
                "identifier": "bsd-new_46.RULE",
                "license_choice": false,
                "licenses": [
                  "bsd-new"
                ]
              }
            },
            {
              "key": "bsd-simplified",
              "score": 55.81,
              "short_name": "BSD-Simplified",
              "category": "Attribution",
              "owner": "Regents of the University of California",
              "homepage_url": "http://www.opensource.org/licenses/BSD-2-Clause",
              "text_url": "http://opensource.org/licenses/bsd-license.php",
              "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:bsd-simplified",
              "spdx_license_key": "BSD-2-Clause",
              "spdx_url": "http://spdx.org/licenses/BSD-2-Clause",
              "start_line": 32,
              "end_line": 41,
              "matched_rule": {
                "identifier": "bsd-simplified_1.RULE",
                "license_choice": false,
                "licenses": [
                  "bsd-simplified"
                ]
              }
            }
          ],
          "copyrights": [
            {
              "statements": [
                "Copyright 2012 The Netty Project"
              ],
              "holders": [
                "Netty Project"
              ],
              "authors": [],
              "start_line": 2,
              "end_line": 2
            },
            {
              "statements": [
                "Copyright (c) 2000,2001,2002,2003 ymnk, JCraft,Inc."
              ],
              "holders": [],
              "authors": [],
              "start_line": 17,
              "end_line": 17
            }
          ],
          "packages": []
        }
      ]
    }

However, as can be seen from the source code, `BSD-2-Clause` is not correct.

Similarly, for [JZlib.java](https://github.com/netty/netty/raw/netty-3.9.2.Final/src/main/java/org/jboss/netty/util/internal/jzlib/JZlib.java) `Apache-2.0`, `BSD-3-Clause` and `public-domain-disclaimer` are reported, but again only the first two are correct.

**Comment by pombredanne** [comment]
Thanks for the report! the latest push fixes and should be merged shortly in develop

**Comment by pombredanne** [comment]
This is fixed now.
