### ISSUE TITLE
Facing Issue while running scancode-toolkit on windows 7 32 bit 

### ISSUE THREAD

**Issue by Ahmed-A-Syed** [nexB/scancode-toolkit#362]
We were facing the below issue while running scancode-toolkit.
It generates scancode_myproject_result.html file ,but the size is 0Kb 

1) Downloaded scancode-toolkit from https://github.com/nexB/scancode-toolkit.git
2) Downloaded Python 2.7 32 bit from  https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi
and installed on C:Drive

**Python:**
	C:\Python27>python
		Python 2.7.12 (v2.7.12:d33edcf92851, Jun 27 2016, 11:09:22) [MSC v.1500 32 bit (Intel)] on win32
		Type "help", "copyright", "credits" or "license" for more information.
		>>>

**Error:**
		C:\Downloads\scancode-toolkit-develop>**scancode --format html samples/MyProject_1.0 scancode_myproject_result.html**
		Scanning files...
		[####################################]  1622
		Scanning done.
		Traceback (most recent call last):
		File "c:\downloads\scancode-toolkit-develop\bin\scancode-script.py", line 9, in <module>
			load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
		File "c:\downloads\scancode-toolkit-develop\lib\site-packages\click\core.py", line 664, in __call__
			return self.main(*args, **kwargs)
		File "c:\downloads\scancode-toolkit-develop\src\scancode\utils.py", line 61, in main
			standalone_mode=standalone_mode, **extra)
		File "c:\downloads\scancode-toolkit-develop\lib\site-packages\click\core.py", line 644, in main
			rv = self.invoke(ctx)
		File "c:\downloads\scancode-toolkit-develop\lib\site-packages\click\core.py", line 837, in invoke
			return ctx.invoke(self.callback, **ctx.params)
		File "c:\downloads\scancode-toolkit-develop\lib\site-packages\click\core.py", line 464, in invoke
			return callback(*args, **kwargs)
		File "c:\downloads\scancode-toolkit-develop\src\scancode\cli.py", line 268, in scancode
			save_results(files_count, results, format, input, output_file)
		File "c:\downloads\scancode-toolkit-develop\src\scancode\cli.py", line 410, in save_results
			output_file.write(as_template(scanned_files))
		File "c:\downloads\scancode-toolkit-develop\src\scancode\format.py", line 194, in as_template
				'start': entry['start_line'],
		TypeError: string indices must be integers, not str

**Note:** MyProject_1.0 is a gradle based java web application project.

**Comment by pombredanne** [comment]
So you took the latest ScanCode from develop?

**Comment by pombredanne** [comment]
I cannot reproduce on Linux. I will try on Windows tomorrow morning. I do not run some smoke tests on Windows on a full release install and probably should.

**Comment by pombredanne** [comment]
I think I know what this is about. I will push a fix tomorrow.

**Comment by pombredanne** [comment]
@Ahmed-A-Syed can you try to run this instead?
```
scancode -clip --format html-app samples/MyProject_1.0 scancode_myproject_result.html
```

**Comment by Ahmed-A-Syed** [comment]
earlier i did a can on the old version available with me i.e;  ' scancode-toolkit-2.0.0rc1'. but even it throws same error. so i tried with latest ScanCode  develop version but stil i got the same error. so i posted it. 

meanwhile let me try running the command suggested by you.

**Comment by Ahmed-A-Syed** [comment]
running the  command suggeted by u doesnt give any errors and generates a report. but if i open the html file, empty is shown in tabs..

google chrome console shows below errors:
     **scancode_datatable.js:197 Uncaught TypeError: Cannot read property 'join' of undefined**
scancode_datatable.js :197

      Uncaught TypeError: Cannot read property 'aDataSort' of undefined - jquery.dataTables.min.js:64

**Comment by pombredanne** [comment]
thank you. That should be enough to help me fix this

**Comment by pombredanne** [comment]
I have a test now that reproduces your problem.

**Comment by pombredanne** [comment]
A failing scan returns this:
```
{
  "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
  "scancode_version": "2.0.0rc2",
  "files_count": 1,
  "files": [
    {
      "path": "tests/scancode/data/failing/patchelf.pdf",
      "type": "file",
      "name": "patchelf.pdf",
      "extension": ".pdf",
      "date": "2016-11-08",
      "size": 61294,
      "sha1": "acc89479c313e8031fe3fee931198ab562124c36",
      "md5": "b855891730415a35a34e38181bae92f6",
      "files_count": null,
      "mime_type": "application/pdf",
      "file_type": "PDF document, version 1.4",
      "programming_language": "Matlab",
      "is_binary": null,
      "is_text": true,
      "is_archive": null,
      "is_media": null,
      "is_source": true,
      "is_script": null,
      "licenses": {
        "errors": "unpack requires a string argument of length 8"
      },
      "copyrights": {
        "errors": "unpack requires a string argument of length 8"
      },
      "packages": []
    }
  ]
}
```
The errors should NOT be returned as part of scanned data, but I should create a top-level new attribute at the file level to accumulate possible errors instead.

**Comment by Ahmed-A-Syed** [comment]
took latest code and ran the command on windows. it works well. 
      scancode -clip--format html samples/MyProject_1.0 scancode_myproject_result.html

No more error - **TypeError: string indices must be integers, not str**
Report is generated and able to see.

But where as **html-app** generates errors 

      scancode_datatable.js:197 Uncaught TypeError: Cannot read property 'join' of undefined -   scancode_datatable.js :197

     Uncaught TypeError: Cannot read property 'aDataSort' of undefined - jquery.dataTables.min.js:64

**Comment by pombredanne** [comment]
Hum... sorry for that. I thought it would work alright. This line 197 is just something I thought I made more robust.... let me check this.

**Comment by pombredanne** [comment]
@Ahmed-A-Syed I cannot find a way to reproduce this easily. Is the scan you ran on publicly available code?
Can you tell me when and were these errors showed up?

**Comment by pombredanne** [comment]
I may at least need to have some snippets of the JSON output included in data.json that was generated

**Comment by pombredanne** [comment]
@Ahmed-A-Syed this latest commit should fix the issue you have faced anyway

**Comment by Ahmed-A-Syed** [comment]
@pombredanne :due to weekend i was not able to reply to ur comments. Let me try with latest develop code and will let u know. before that i wanna appreciate you. . usually other opensource groups responses are very late. you response time on the issue or comments is amazing and fast. That internally makes us to go forward and use the scancode toolkit.

**Comment by pombredanne** [comment]
@Ahmed-A-Syed thank you for the kind feedback. but if you have a bug I may hit it and every user may hit the same bug... so fixing things is rather important :) I am using it everyday myself!

**Comment by Ahmed-A-Syed** [comment]
great..works with latest code.
