### ISSUE TITLE
Wrong repository, sorry. :)

### ISSUE THREAD

**Issue by mmurto** [nexB/scancode-toolkit#3623]
Wrong repository, sorry. :)

**Comment by pombredanne** [comment]
Actually are you sure this was not about ScanCode license detection? I have a patch for something sounding just like this "Implement long query line splitting "

**Comment by mmurto** [comment]
I was hacking around the ScanCode tokenizer in Rust, and tried to reference the ScanCode code in an issue from VSCode, which automatically created the issue here. So no, not relevant for you. :)

**Comment by pombredanne** [comment]
@mmurto this sounds interesting, do you have a URL?

**Comment by mmurto** [comment]
@pombredanne just initial sketching currently, but I'll let you know if I get anywhere. :)
