### ISSUE TITLE
Store errors in scans at the file level

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#364]
The current develop stores errors if any as dict `{'errors': message}` for each scan such as in: `'licenses': {'errors': message}}` : this break the expectation that a scan result is a list and may confuse downstream tools about the type of scanned data when there is an error.

Instead I propose this approach: store an `errors` attribute at the file level. This would be a list, similar to the `licenses` or `coyrights` scan data. Each item would be a dict keyed by "scan name" and the value a tuple of (short mesage, full traceback).
This list would be always present and possibly empty when there is no error.

Here is an example of how it looks like today:
```
{
  "files": [
    {
      "path": "", 
      "copyrights": {
        "errors": "unpack requires a string argument of length 8"
      }
    }
  ]
}
```

and with this new approach we would get instead:
```
{
  "files": [
    {
      "path": "tests/scancode/data/failing/patchelf.pdf",
      "copyrights": [],
      "scan_errors": [
        {
          "copyrights": [
            "unpack requires a string argument of length 8",
            "Traceback (most recent call last):\n  File \"/home/pombreda/w421/scancode-toolkit/src/scancode/cli.py\", line 390, [......]
          ]
        }
      ]
    }
  ]
}
```

**Comment by pombredanne** [comment]
note that this is also related to #362

**Comment by majurg** [comment]
👍  this change if the list defaulted to empty if there are no errors.

**Comment by mjherzog** [comment]
This could become pretty verbose with traceback.  Does it make sense to think of some separate Errors file for anything beyond the basic error message?

**Comment by pombredanne** [comment]
@mjherzog you have a good point, but on the other hand if you have errors and you do not collect a full traceback in these cases, you do not have much diagnostic data on hand. The alternative could be to sore the traceback details in a separate log file. This could come in a second step

**Comment by JonoYang** [comment]
:+1: Perhaps traceback and more verbose logging can be enabled using an option?

**Comment by pombredanne** [comment]
@JonoYang good point

**Comment by jdaguil** [comment]
👍 this change is fine with me.

**Comment by chinyeungli** [comment]
👍 looks good to me

**Comment by nspsjsu** [comment]
seems fine 👍

**Comment by pombredanne** [comment]
The format of how errors are stored is now a simple list of error messages stored under each file under the `scan_errors` attribute. By default it contains only simple/short messages. If the new `--diag` command line option is used, then a full stack trace is also included in the scan_errors list. I think this addresses everything in this ticket including @mjherzog @JonoYang feedback to avoid storing too much verbose errors by default.
Closing now.
