### ISSUE TITLE
Add release smoke tests for Windows

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#366]
We have them for Linux and Mac and should run them for Windows too.

**Comment by starlord1311** [comment]
@pombredanne  can i take up this issue?

**Comment by pombredanne** [comment]
@starlord1311 sure. You do not need any approval to work on one!

**Comment by Abhishek-Dev09** [comment]
What do you mean by smoke test?Is it that test which we test after building using test suite.

**Comment by pombredanne** [comment]
Yes. See https://github.com/nexB/scancode-toolkit/blob/c6d1de1d97da1b6ba6d76edae95d30dbe5aa1206/etc/release/release.sh#L38 for POSIX.

**Comment by pombredanne** [comment]
This is now part of the https://github.com/nexB/scancode-toolkit/blob/cce8cbc64746ed58f2f0a9bf03d6c3500bd7cc1c/etc/release/scancode-create-release.sh tests.
This has not yet been included in the main CI loop but this is good enough.
