### ISSUE TITLE
New license in libpng/pngcrush?

### ISSUE THREAD

**Issue by LeChasseur** [nexB/scancode-toolkit#3708]
Haven't found the following license in the database:
https://github.com/cloudflare/pngcrush/blob/deflate.gcc.amd64/cexcept.h
Seems to be me a permissive license.

**Comment by pombredanne** [comment]
@LeChasseur Thanks!
This is actually detected exactly as https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/other-permissive_67.RULE but since you bring it up, now  is the time to give it a name and promote it as a proper named license.

The original place is http://www.nicemice.net/cexcept/

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   please create this new license and make the associated adjustments to the rules (see comments above).  Note that we already have another license, punycode, from owner nicemice.

key: cexcept-2008
short-name: cexcept License 2008
name: cexcept License 2008
spdx-identifier: LicenseRef-scancode-cexcept-2008
category: Permissive
owner: nicemice
text-url: https://github.com/cloudflare/pngcrush/blob/deflate.gcc.amd64/cexcept.h
other-url: http://www.nicemice.net/cexcept/

text: 
This software may be modified only if its author and version
information is updated accurately, and may be redistributed
only if accompanied by this unaltered notice.  Subject to those
restrictions, permission is granted to anyone to do anything
with this software.  The copyright holders make no guarantees
regarding this software, and are not responsible for any damage
resulting from its use.

notes: 
cexcept.h 2.0.1 (2008-Jul-19-Sat)
http://www.nicemice.net/cexcept/
Adam M. Costello
http://www.nicemice.net/amc/
Copyright (c) 2000-2008 Adam M. Costello and Cosmin Truta.

**Comment by LeChasseur** [comment]
Thanks, perfect.

**Comment by AyanSinhaMahapatra** [comment]
Added, closing!
