### ISSUE TITLE
v32.1.0_p3 requests python 3.10 when python 3.11 already installed

### ISSUE THREAD

**Issue by adrienlaveau** [nexB/scancode-toolkit#3736]
### Description

Installing scancode-toolkit-v32.1.0 on window 10 using the file ( scancode-toolkit-v32.1.0_py3.11-windows.zip ) from this release when executing all the steps from the documentation https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#installation-on-windows-10 I get the following error message : 

```
C:\Users\XXXX\scancode-toolkit-v32.1.0_py3.10-windows\scancode-toolkit-v32.1.0>scancode -h
* Configuring ScanCode for first use...
* WARNING: Native Windows may be deprecated in the future in favor of Windows Subsystem for Linux 2
* WARNING: Please visit https://github.com/nexB/scancode-toolkit/issues/2366 for details and to provide feedback
Python 3.10 not found!
Installed Pythons found by py Launcher for Windows
 -3.9-64 *
 -3.11-64

Requested Python version (3.10) not installed, use -0 for available pythons
```

But the github landing page states that python11 is supported. Am I doing something wrong ? 

### How To Reproduce

Download : scancode-toolkit-v32.1.0_py3.11-windows.zip
Follow precise steps of  https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#installation-on-windows-1

### System configuration

> For bug reports, it really helps us to know:

* Windows 11
* scancode-toolkit : scancode-toolkit-v32.1.0_py3.10-windows
* What installation method was used to install/run scancode : [Installation as an Application: Downloading Releases](https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#app-install)

Thank you for the support

**Comment by pombredanne** [comment]
@adrienlaveau you would need to download  the 
scancode-toolkit-v32.1.0_py3.11-windows.zip for Python 3.11 instead of the archive for Python 3.10

Use this:
https://github.com/nexB/scancode-toolkit/releases/download/v32.1.0/scancode-toolkit-v32.1.0_py3.11-windows.zip

**Comment by adrienlaveau** [comment]
Thank you.

Sorry for not seeing this... 

Thanks for the projects.

**Comment by pombredanne** [comment]
> Sorry for not seeing this...

Nah.... this is not obvious... we need to find a way to improve this! Any suggestions?

**Comment by adrienlaveau** [comment]
Hum, maybe making obvious Python category in download page. Or maybe just updating the error message like "scancode-toolkit supports various python version but the correct installer needs to be used. Check the download page for you python version"
Which is basicslly whst you told me and solved the issue right away.
