### ISSUE TITLE
Unexpected output for field vcs_url in cargo workkspaces

### ISSUE THREAD

**Issue by meretp** [nexB/scancode-toolkit#3769]
### Description

When scanning [/boring-sys/Cargo.toml](https://github.com/cloudflare/boring/blob/master/boring-sys/Cargo.toml)  with the current release of ScanCode I get the following package data detection including an object for the vcs_url. Is this the expected behaviour? From the [model definition](https://github.com/nexB/scancode-toolkit/blob/4f49985c26b6b8f951f116dfa3fe39ce27bd4ce8/src/packagedcode/models.py#L604) of a package I would have expected an optional string here. Also, I don't really know how to interpret this value.
```
 "files": [
    {
      "path": "Cargo.toml",
      "type": "file",
      "package_data": [
        {
          "type": "cargo",
          "namespace": null,
          "name": "boring-sys",
          "version": null,
          "qualifiers": {},
          "subpath": null,
          "primary_language": "Rust",
          "description": "FFI bindings to BoringSSL",
          "release_date": null,
          "parties": [
            {
              "type": "person",
              "role": "author",
              "name": "Alex Crichton",
              "email": "alex@alexcrichton.com",
              "url": null
            },
            {
              "type": "person",
              "role": "author",
              "name": "Steven Fackler",
              "email": "sfackler@gmail.com",
              "url": null
            },
            {
              "type": "person",
              "role": "author",
              "name": "Ivan Nikulin",
              "email": "ifaaan@gmail.com",
              "url": null
            }
          ],
          "keywords": [],
          "homepage_url": null,
          "download_url": null,
          "size": null,
          "sha1": null,
          "md5": null,
          "sha256": null,
          "sha512": null,
          "bug_tracking_url": null,
          "code_view_url": null,
          "vcs_url": {
            "workspace": true
          },
          ...]}
``` 
There is also a scan_error, maybe this is related to the unexpected output here?
```
"scan_errors": [
        "get_package_and_deps: Failed to assemble PackageData: PackageData(type='cargo', namespace=None, name='boring-sys', version=None, datasource_id='cargo_toml'):\nTraceback (most recent call last):\n  File \"../scancode-toolkit-v32.1.0/venv/lib/python3.11/site-packages/packagedcode/plugin_package.py\", line 413, in get_package_and_deps\n    for item in items:\n  File \"../scancode-toolkit-v32.1.0/venv/lib/python3.11/site-packages/packagedcode/cargo.py\", line 44, in assemble\n    workspace_root_path = resource.parent(codebase).path\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'bool' object has no attribute 'path'\n"
      ]
```

### How To Reproduce

This is the command I used, executed within the extracted directory of the latest release downloaded from GitHub.
`./scancode -clpu --only-findings -n 20 --license-text --json result_boring_cargo.json ../boring/boring-sys/Cargo.toml`

### System configuration

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? v32.1.0, I also checked with a previous version v 32.0.8, but there the vcs_url is just null.

**Comment by pombredanne** [comment]
@meretp Thanks! Support for Cargo workspace is a recent addition @AyanSinhaMahapatra
- https://github.com/nexB/scancode-toolkit/issues/3602
- https://github.com/nexB/scancode-toolkit/issues/3598

**Comment by AyanSinhaMahapatra** [comment]
@meretp this should be fixed with a lot of bugfixes and improvements on cargo workspaces, see https://github.com/nexB/scancode-toolkit/pull/3783#issue-2305352534 for details on this.
See also attached the scan results for boring: 
[boring-master-scan.json](https://github.com/nexB/scancode-toolkit/files/15402149/boring-master-scan.json)
