### ISSUE TITLE
Create a "collect_manifest" scan option to generate a lockfile when none exists

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3772]
Proposed: a new "collect_manifest" scan option that prompts scancode to figure out the dependencies when there is no clearly specified manifest, and then store that generated lockfile in the scan results. 

Benefits: 
- Better dependency results
- Traceability of the dependency results by making the generated manifest persistent

**Comment by pombredanne** [comment]
After consideration, we would rather not have a scancode option for this. Instead it will be a separate standalone executable that is tracked in https://github.com/nexB/dependency-inspector/ and specifically in this issue:
- https://github.com/nexB/dependency-inspector/issues/2
