### ISSUE TITLE
Add new floodgap license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3774]
Add Floogap license from http://www.floodgap.com/software/ffsl/ by @classilla

It used in the wild:
- https://github.com/search?q="Floodgap+Free+Software+License"&type=code
- https://www.google.com/search?q="Floodgap Free Software License"&pws=0&gl=us&gws_rd=cr#gws_rd=cr&ip=1

Reported by @pabs3

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   please synchronize with this new license, ffsl-1  

https://enterprise.dejacode.com/licenses/nexB/ffsl-1/

**Comment by AyanSinhaMahapatra** [comment]
Added, closing!
