### ISSUE TITLE
enhancement: push docker image on Github container 

### ISSUE THREAD

**Issue by RomainPelletant** [nexB/scancode-toolkit#3776]
## Short Description
Provide a docker image stored in GitHub containers.

## Possible Labels

- new feature

## Select Category
-  Enhancement

## Update Github action to build and push new docker image into Github containers
CI based on docker image for scan step could be directly based on that image without rebuilding it on the fly.

## **Possible Solution/Implementation Details**
A Github action building and pushing new docker image on new release / tag creation.
Release could provide a direct link the that docker image tag associated.

-  [ ] Github action on new release/tag to build and push new docker image
-  [ ] Include link to this docker image with tag in release body

## **Can you help with this Feature**
WIP

**Comment by pombredanne** [comment]
This makes perfect sense. 
See this work in progress:
- https://github.com/nexB/scancode-toolkit/issues/3026
- https://github.com/nexB/scancode-toolkit/pull/3027

I am closing this issue here as a duplicate.
