### ISSUE TITLE
Synchronize scancode licenses with SPDX license list 3.24.0

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3787]
Synchronize scancode licenses with SPDX license list release 3.24.0: 

https://github.com/spdx/license-list-XML/releases/tag/v3.24.0

**Comment by AyanSinhaMahapatra** [comment]
Stats on the new SPDX licenses:

- Licenses which already existed in LicenseDB: 17/25 (exact matches)
   - as licenses: 12 (updated SPDX key from scancode-licenseref) 
   - as rules: 5
- New licenses: 8/25
   - Partial matches: 5 (small/medium text variations)
   - entirely new texts: 2 (both exceptions)
   - any-osi: 1 (the weird one: choose any osi license!)
