### ISSUE TITLE
Separate JSON data into a separate file from html app

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#38]
The html app should have the JSON data in a separate file rather than inside the file

**Comment by pombredanne** [comment]
This makes perfect sense... IMHO to work around the limitations of loading JSON files in a local HTML page and the differences between browsers you might want to take a look at using JSONP?

**Comment by pombredanne** [comment]
@jdaguil I think this is all fixed, right? if so please close
