### ISSUE TITLE
Incorrect copyright detected as "Byten ( c ) Exactly"

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#380]
In this:
```
... don’t fit into your fixed-size buffer.
Byten ( c )
Exactly n bytes. If the
```
`Byten (c) Exactly` in incorrectly detected

**Comment by JonoYang** [comment]
Incorrect detection has been fixed somewhere. A new test has been created to ensure that `Byten (c) Exactly` is not detected has been merged in at #433.
