### ISSUE TITLE
Limit number of urls and emails reported in a single file 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#384]
At times some file -such as a test file- may contain a large number of emails and/or urls. Millions of them. We should limit the number of returned items per file in these cases to a sensible number like a few 100's and report a warning that not everything was scanned...

**Comment by sam09** [comment]
Anyone working on this? I would love to give it a try

**Comment by pombredanne** [comment]
@sam09 Go for it . Thanks!

**Comment by sam09** [comment]
I think we could probably limit the list of emails and urls to a 1000?
The get_urls and get_emails method can be modified to limit the number.
https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode/api.py.

**Comment by pombredanne** [comment]
@sam09 anything with more than a 100 emails or urls is likely a data file with a huge amount of these. Actually 50 would already be a huge lot. 

One consideration is how to report such cases of partial detection? some warning in the scan errors? some what to state like: 123673 URLs were detected in this file. Only the first 100 are reported... TBD. Suggestions  are welcomed.

Also it could make sense to make the max number a CLI option and have a default to 50 or 100 for instance. In which case the issue of reporting partial detection may be a lesser issue.

**Comment by pombredanne** [comment]
and also since both urls and email would need a limit, having a single wrapper function that works for both would the way to go imho.... e.g. some generic function that accepts an iterable and yields a truncated iteable.   It may even exists in the stdlib itertools.

**Comment by pombredanne** [comment]
e.g. https://docs.python.org/2.7/library/itertools.html?highlight=itertools#itertools.islice

**Comment by pombredanne** [comment]
so with this and a `functools.partial` you can create simple wrappers and use at first a hardcoded limit of say 50, and later a CLI option for the limit, where using `0` would mean return all.

**Comment by inishchith** [comment]
@pombredanne I'd like to work on this , can you assign this to me ?

**Comment by majurg** [comment]
@inishchith I believe you can assign yourself :)

**Comment by majurg** [comment]
@inishchith Assignees can only be apart of our GitHub org for now, but you are free to contribute to this (and any other) issue. :)

**Comment by inishchith** [comment]
Oh , I'll it a try  👍

**Comment by inishchith** [comment]
@majurg do i restrict the number to 100 per file for now ? and report as per above comments by @pombredanne ?

**Comment by majurg** [comment]
@inishchith 100 per file is a good place to start for now.

**Comment by inishchith** [comment]
@majurg do we just print the warning on the CL :
```
warning : 1235671 urls detected at <location> but only first 100 were reported
```
or is there a better way to report ?

**Comment by inishchith** [comment]
@pombredanne @majurg please suggest

**Comment by pombredanne** [comment]
@inishchith there is no need to have a CLI warning at all.
Instead you should be looking at the #787 branch https://github.com/nexB/scancode-toolkit/tree/787-new-plugin-architecture and consider these updates:
1. add a new option to each of email and url scanner plugins that sets a limit to the returned number of things. Using a default of say 50.
2. update the plugins to return a closure scanner function using this new arguments 
3. update the scanner function accordingly to break after a the set number of items
4. if the option is 0, there should not be a limit on the number of returned items

**Comment by inishchith** [comment]
@pombredanne I'll give it a try . Actually i's looking for a good first issue so that i can get started . still i'll try .

**Comment by inishchith** [comment]
One more thing @pombredanne default would be set to 50 . are we providing the user to enter a number right from CLI ?

**Comment by inishchith** [comment]
@pombredanne i mean an example of CLI command would be helpful .

**Comment by pombredanne** [comment]
This has been merged in develop.
