### ISSUE TITLE
Error with latest develop on Ubuntu 12.x with Python 2.7.3

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#385]
When running this I get some weird error `Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored` only sometimes. Only on This older Python 2.7.3

It is likely linked to this Python bug http://bugs.python.org/issue15101

```
~/bin/scancode-toolkit/scancode -cilp --diag ~/bin/scancode-toolkit/samples ~/t.json -n4
Scanning files for: infos, licenses, copyrights, packages with 4 process(es)...
Building license detection index...Done.
Scanning files...
  [####################################]  43
Scanning done.
Scan statistics: 43 files scanned in 18s.
Scan options:    infos, licenses, copyrights, packages with 4 process(es).
Scanning speed:  2.84 files per sec.
Scanning time:   15s.
Indexing time:   3s.
Saving results...
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
```

**Comment by pombredanne** [comment]
@chinyeungli You had mentioned to me that you experienced this issue. Would you mind checking if this fixes it for you?

**Comment by chinyeungli** [comment]
sure

**Comment by pombredanne** [comment]
Hum that latest code still errors out but in a new way, this time hitting this bug: https://bugs.python.org/issue14881

**Comment by pombredanne** [comment]
This latest commit should fix this. Let me test it more on a VM.

**Comment by pombredanne** [comment]
well it seems even worse. I think the only sane thing is to upgrade Python may be?

**Comment by pombredanne** [comment]
This is now fixed... The resolution is not super pretty but works now.
