### ISSUE TITLE
Add support to extract .pkg file

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#387]
The `extractcode` currently does not support to extract `.pkg` file.

**Comment by chinyeungli** [comment]
Sample `.pkg` file
https://www.macupdate.com/download/57517/AirMount.pkg

**Comment by pombredanne** [comment]
This is now fixed in develop. Thank you for the report!
FWIW, the fix was reasonable easy as the underlying extraction libraries do support the XAR format, so it was mostly about enabling new archive handlers reusing existing extractors.
