### ISSUE TITLE
Still no --verbose output on Jenkins CI

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#388]
Although cf024ac88462b79fc5b7a00207d7f8fcc8a854e7 says "--verbose output is always send to stdout", I still do not see the individual files being scanned printed to the console / log when running ScanCode as part of a Jenkins CI job.

**Comment by pombredanne** [comment]
@sschuberth sorry for that, I thought I fixed it, but I did not add a test. There is something fishy happening in the guts of the click ProgressBar. I think I will just skip using a progress bar subclass ProgressLogger for verbose output entirely i.e. not use at all https://github.com/nexB/scancode-toolkit/blob/3d89c2871543a61576cd485e2335da93e96a8c98/src/scancode/utils.py#L83

**Comment by sschuberth** [comment]
On the other hand, it probably does not make sense to duplicate too much code for verbose vs. non-verbose output, and I'd be curious what's the cause for ProgressLogger not showing output for a non-tty stdout.

**Comment by pombredanne** [comment]
Actually not using ProgressLogger is likely to mean less code than using it... so no worries there

**Comment by pombredanne** [comment]
So after all the issue what that ProgressLogger was not forcing itself to be visible at all times (with the `hidden` attribute) which this fixed: https://github.com/nexB/scancode-toolkit/commit/376cb9dbe77e0df2caf5fdbd6b1a3bba4c9bcea3#diff-7412a01bdb89dd7c7021bf5530be25a7R97

The logic is that `--verbose` forces the output to go to `stdout`. There is one case where this is may be awkward: If a CLI run does not specify an output file then the scan results are also printed to `stdout` and when combined with a `--verbose` option then the per-file progress and the scan results will both go to `stdout` which can be a tad messy but is corner case: the general approach should be to use an explicit file.

**Comment by sschuberth** [comment]
Another alternative would be to always send "primary" output (i.e. the scan results) to *stdout*, but all other output (warnings, errors, progress, which includes output from `--verbose`) to *stderr*. That would sort of solve the problem when specifying `--verbose` but no output file: While it still looks messy / interleaved in the terminal, you could easily separate the streams, e.g. by redirecting only *stderr* to a file.

**Comment by pombredanne** [comment]
Of course! And this much much cleaner!
So the behavior should be:
1. if no output file is specified, send the scan results to `stdout` 
2. no option: messages, progress bar and summary sent to `stderr`. 
3. `--quiet` no messages, no progress bar, no summary 
4. `--verbose` messages, per-file log and  summary sent to `stderr`

as a side note, if `--quiet` and `--verbose` are both requested, `--quiet` wins for now.

**Comment by pombredanne** [comment]
ok, I will go ahead and implement this then.

**Comment by sschuberth** [comment]
Just wanted to comment that I've verified 376cb9dbe77e0df2caf5fdbd6b1a3bba4c9bcea3 to fix the issue, I now see `--verbose` output in the Jenkins console log. Thank you! Feel free to close this, or leave it open as a reminder until you've implemented the above behavior WRT sending output to *stdout* vs. *stderr*.

**Comment by pombredanne** [comment]
@sschuberth Thank you for the review. I will keep this open to track the proposed update.

**Comment by pombredanne** [comment]
This should be all fixed now with the latest merge of #418
