### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by UShan89** [nexB/scancode-toolkit#394]
Please ignore if this is a duplicate or known issue. Below is trace from Windows Subsystem for Linux with pip to install scancode-toolkit.

**FIX:**

Using python-dev package fixes this. python-dev needs to be listed as a system library dependency. 

`Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/url/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lxgYzz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/url
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)`

**Comment by pombredanne** [comment]
@UShan89 Thanks for the report! Can you elaborate a bit on your installation? pip 1.5.4 seems quite old a version. Which OS/Arch and Python version were you trying to install a Scancode wheel on?
Which command did you use for this? and which version of Scancode?

**Comment by pombredanne** [comment]
BTW, we have no support for the "Windows Subsystem for Linux" of Windows 10. Which explains this. I am keeping this open for now.

**Comment by JonoYang** [comment]
I am able to set up and run ScanCode using "Bash on Ubuntu on Windows" on a clean installation Windows 10 Pro 64-bit on a VM by following the quick start instructions. (As an aside, the instructions need to be updated a bit as the dependencies `libbz2` and `xzutils` were not found by apt-get but `bzip2` and `xz-utils` were.)

There are issues when ScanCode is run on a symlinked directory, however.

**Comment by pombredanne** [comment]
I am closing for now unless someone wants to tackle support for this
