### ISSUE TITLE
Docker image does not build anymore

### ISSUE THREAD

**Issue by FaberFlorian** [nexB/scancode-toolkit#3955]
https://github.com/aboutcode-org/scancode-toolkit/blob/6e4293750b1b2d9104ee621335dc113d1b27b4b6/Dockerfile#L10

Please update the Dockerfile:

`ERROR: Package 'scancode-toolkit' requires a different Python: 3.8.16 not in '>=3.9'`

FROM --platform=linux/amd64 python:3.8-slim-buster
e.g. ->
FROM --platform=linux/amd64 python:3.9-slim-buster
but 3.13 is current stable.

**Comment by AyanSinhaMahapatra** [comment]
@FaberFlorian thanks for the report! 

I seem to have missed updating the dockerfile when I was releasing scancode yesterday, let me fix this
 😅

We should probably also have some CI with tests for the dockerfile, to make sure things like this don't happen again.

**Comment by JonoYang** [comment]
@FaberFlorian I've updated the Dockerfile and added a CI build test in https://github.com/aboutcode-org/scancode-toolkit/tree/3955-update-Dockerfile . Let me know if this works for you

**Comment by FaberFlorian** [comment]
Well, I already built it locally after some modifications since I wanted to test it. We will see with the next release :) I wonder why nobody noticed that. Is nobody using the docker container?

**Comment by mjherzog** [comment]
Most people are using SCTK as a library or a command line tool or "indirectly" with ScanCode.io where Docker is a primary use case.

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra ping we need to fix this ASAP

**Comment by JonoYang** [comment]
@pombredanne The Dockerfile has been updated already. I think this issue can be closed
