### ISSUE TITLE
gpl-2.0 detected for a jar file from apache

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#396]
Not sure how the `pdfbox-app-1.8.2.jar` being detected as gpl-2.0

https://repo1.maven.org/maven2/org/apache/pdfbox/pdfbox-app/1.8.2/pdfbox-app-1.8.2.jar

**Comment by pombredanne** [comment]
This is a fluke. Somewhere in the binary there is a GPL string. Thanks for the report.... We should NOT scans compressed binary files at all...  This confirms the suspicion of @yahalom5776 in #374

**Comment by pombredanne** [comment]
Note that at least that the reported score is very low... e.g. 5/100 as it should

**Comment by pombredanne** [comment]
This is now fixed in develop.
