### ISSUE TITLE
Cli fails with --no-check-version option

### ISSUE THREAD

**Issue by alexzurbonsen** [nexB/scancode-toolkit#4004]
### Description

If the `--no-check-version` option is used, scancode cli fails. There is an unbound local variable `outdated`.

### How To Reproduce

Run any scancode cli command with `--no-check-version`.

Or add this test to `test_cli.py`

```
def test_no_version_check_run_is_successful():
    test_file = test_env.get_test_loc('single/iproute.c')
    result_file = test_env.get_temp_file('json')
    run_scan_click(['--no-check-version', test_file, '--json', result_file], expected_rc=0)
```

and run

```sh 
pytest tests/scancode/test_cli.py::test_no_version_check_run_is_successful
```

### System configuration

On latest release (32.3.0). This is easy enough to see from the code. I guess no further details are needed.

**Comment by AyanSinhaMahapatra** [comment]
Thanks @alexzurbonsen!
