### ISSUE TITLE
Incomplete Copyright report in HTML ouput

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#401]
I'm using ScanCode 2.0.0rc2 (Git revision 1e3ade0) to scan some proprietary code. In the HTML result file, some copyright headers are missing from the listing. The interesting bit is, there is a file `A` for which the copyright header is properly detected, and a file `B` which contains exactly the same header, for which the copyright header is not detected. Both files `A` and `B` appear in the "File Information" section, which means they are in fact scanned, and `B` is not accidentally excluded from the scan or similar.

Would you have any idea what might cause this? Is the copyright listing maybe somehow truncated it it already contains a certain amount of the same copyright holder information?

**Comment by pombredanne** [comment]
There is no truncation that takes place that I can think of.
To rule out any issue from the output side, do you have the same issue when you use a plain JSON output?

And could you create some mocks/sanitized of two of these headers to paste here so I can try to reproduce this?

**Comment by pombredanne** [comment]
@sschuberth Any update? I would like to get this fixed and settled soon enough!

**Comment by sschuberth** [comment]
@pombredanne Sorry for the delay, it took me a while to re-run the (large) scan. I can now confirm that the JSON output properly shows the copyright header for file `B`. So for some reason it only gets dropped from HTML output ...

**Comment by pombredanne** [comment]
@sschuberth ok, that is bug there then... let check this out... I added a test but this is passing and not truncating. There must be something very peculiar about these two files. When you just scan a copy of only A and B in a separate directory, do you also have the issue with HTML?

**Comment by sschuberth** [comment]
@pombredanne I basically just checked that, and no, in that case the copyright holder is properly included in the HTML report. I'll try to narrow it down further.

**Comment by sschuberth** [comment]
Ha, I just realized file `B` is listed in the "Some files failed to scan properly. See scan for details:" section. But this only happened in the scan which used HTML as the output format. In the second run using JSON file `B` was scanned properly. So my guess is this was pure coincidence due to temporary memory pressure on the scanning machine, or so.

@pombredanne What are the possible reasons for a file being listed in the "Some files failed to scan properly. See scan for details:" section?

**Comment by sschuberth** [comment]
BTW, the fact that file `B` shows up in the "File Information" section despite it not being scanned properly seems to be a side-effect of issue #375.

**Comment by pombredanne** [comment]
@sschuberth you wrote "What are the possible reasons for a file being listed in the "Some files failed to scan properly. See scan for details:" section?"

It can be anything of:
- a timeout expired
- a memory quota exceeded
- an actual exception or error when processing a file which can be anything that could go south: corrupted file, bug, etc 

If you use the the `--diag` option, the `scan_errors` attribute of the files that did fail to scan properly may contain extra information if available including an additional stack trace if applicable.

**Comment by pombredanne** [comment]
> BTW, the fact that file B shows up in the "File Information" section despite it not being scanned properly seems to be a side-effect of issue #375.

I will keep this in mind. I need to work seriously on the Package detection this week including adding several new Package manifest parsers (Go, Gem,Debian, Windows PE/DLL, Python, Composer, may be android,  improved Maven, may be gradle, Bower, etc) and design the proper handing of how we report detected dependencies, but then pluggable reporting will be up on deck next (together with license expressions support).

**Comment by sschuberth** [comment]
I'm closing this as the original issue was not really one: The file for which I expected ScanCode to detect a Copyright entry was not properly scanned for unknown reasons. With this in mind, it's not a surprise that the Copyright was not found. I'll file a more appropriately named issue if this happens again and I can reproduce it.
