### ISSUE TITLE
Change the returned license category from `Attribution` to `Permissive`

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#408]
The scancode toolkit is currently return `Attribution` as one of the license categories. However, we do not have a License Category of `Attribution`, it should be `Permissive`

**Comment by pombredanne** [comment]
This makes sense and is easy enough. Would you mind a pull request?

**Comment by chinyeungli** [comment]
I can do that

**Comment by pombredanne** [comment]
@chinyeungli I think we are all set now. Thank you!
