### ISSUE TITLE
ScanCode does not detect bpmn-io license

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#409]
A rule for the bpmn-io license is needed.

**Comment by pombredanne** [comment]
@JonoYang Thanks. It is this: http://bpmn.io/license/ ?
And if so is it not detected at all, or rather detected as MIT?

**Comment by JonoYang** [comment]
It is not detected at all. I ran ScanCode on https://github.com/bpmn-io/bpmn-js, only a JSON license was found in the license file.

**Comment by JonoYang** [comment]
Merged in #410
