### ISSUE TITLE
Older json2csv script should be kept with the newer version for legacy ScanCode results

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#415]
The old version of json2csv should be readded for compatibility with scan results from previous versions of ScanCode.

**Comment by pombredanne** [comment]
@JonoYang what is the latest version that support ScanCode v1.6 JSON scans

**Comment by pombredanne** [comment]
Actually this is 55643a104cf8cad154e03bfa8bb4e9b067b1c464
What you could do is to keep that version as json2csv1 and renamed the current one as json2csv2 for now.
Pretty soon json2csv1 will vanish anyway... Or we could more simply tag the repo to easily get that older version back

**Comment by JonoYang** [comment]
I have a local branch where I took the original json2csv.py and its tests and renamed it as json2csv_legacy. I can push it to the repo and create a pull request if needed.

**Comment by pombredanne** [comment]
@JonoYang I think this is good enough for now.

**Comment by pombredanne** [comment]
This is done. Closing
