### ISSUE TITLE
(L)GPL false positives for jansson project

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#422]
Running ScanCode f346dd2c198f2e26e6c1008dfd519bf854af9dff like

    $ scancode -f JSON -l jansson_config.h

with [jansson_config.h](https://github.com/akheron/jansson/blob/074bb3838f83c8ed5b2ec3ec075c9405e6589214/android/jansson_config.h) from https://github.com/akheron/jansson results in

    {
      "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "scancode_version": "2.0.0rc2",
      "files_count": 1,
      "files": [
        {
          "path": "jansson_config.h",
          "scan_errors": [],
          "licenses": [
            {
              "key": "gpl-2.0",
              "score": 51.61,
              "short_name": "GPL 2.0",
              "category": "Copyleft",
              "owner": "Free Software Foundation (FSF)",
              "homepage_url": "http://www.gnu.org/licenses/gpl-2.0.html",
              "text_url": "http://www.gnu.org/licenses/gpl-2.0.txt",
              "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-2.0",
              "spdx_license_key": "GPL-2.0",
              "spdx_url": "http://spdx.org/licenses/GPL-2.0",
              "start_line": 4,
              "end_line": 5,
              "matched_rule": {
                "identifier": "gpl-2.0_8.RULE",
                "license_choice": false,
                "licenses": [
                  "gpl-2.0"
                ]
              }
            },
            {
              "key": "mit",
              "score": 10.0,
              "short_name": "MIT License",
              "category": "Attribution",
              "owner": "MIT",
              "homepage_url": "http://opensource.org/licenses/mit-license.php",
              "text_url": "",
              "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:mit",
              "spdx_license_key": "MIT",
              "spdx_url": "http://spdx.org/licenses/MIT",
              "start_line": 5,
              "end_line": 5,
              "matched_rule": {
                "identifier": "mit_14.RULE",
                "license_choice": false,
                "licenses": [
                  "mit"
                ]
              }
            }
          ]
        }
      ]
    }

Note that `gpl-2.0` is a false positive here.

**Comment by sschuberth** [comment]
Slightly different false positive for a different file in the same project: For [hashtable.h](https://github.com/akheron/jansson/blob/074bb3838f83c8ed5b2ec3ec075c9405e6589214/src/hashtable.h) `lgpl-2.1` is reported as a false positive, see

    {
      "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "scancode_version": "2.0.0rc2",
      "files_count": 1,
      "files": [
        {
          "path": "hashtable.h",
          "scan_errors": [],
          "licenses": [
            {
              "key": "lgpl-2.1",
              "score": 54.55,
              "short_name": "LGPL 2.1",
              "category": "Copyleft Limited",
              "owner": "Free Software Foundation (FSF)",
              "homepage_url": "http://www.gnu.org/licenses/lgpl-2.1.html",
              "text_url": "http://www.gnu.org/licenses/lgpl-2.1.txt",
              "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:lgpl-2.1",
              "spdx_license_key": "LGPL-2.1",
              "spdx_url": "http://spdx.org/licenses/LGPL-2.1",
              "start_line": 891,
              "end_line": 895,
              "matched_rule": {
                "identifier": "lgpl-2.1_22.RULE",
                "license_choice": false,
                "licenses": [
                  "lgpl-2.1"
                ]
              }
            },
            {
              "key": "mit",
              "score": 10.0,
              "short_name": "MIT License",
              "category": "Attribution",
              "owner": "MIT",
              "homepage_url": "http://opensource.org/licenses/mit-license.php",
              "text_url": "",
              "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:mit",
              "spdx_license_key": "MIT",
              "spdx_url": "http://spdx.org/licenses/MIT",
              "start_line": 895,
              "end_line": 895,
              "matched_rule": {
                "identifier": "mit_14.RULE",
                "license_choice": false,
                "licenses": [
                  "mit"
                ]
              }
            }
          ]
        }
      ]
    }

**Comment by pombredanne** [comment]
@sschuberth Thanks for the report (and happy new year!)
Let me push a few new rules right away.... It looks like the jansson authors borrowed a bit from the common L/GPL notices for their MIT.

**Comment by sschuberth** [comment]
Thanks, and Happy New Year to you too!

**Comment by pombredanne** [comment]
@sschuberth These commits fix the issue. I also ran a full scan on jansson's head and also added a new (rare) license that was not detected correctly with https://github.com/nexB/scancode-toolkit/commit/da5eeff26818a9e48feb96921df761740b141351

Thanks again for the report!
