### ISSUE TITLE
Writing SPDX output to a file raises an expection

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#436]
This is basically a note to myself since I've introduced the bug. Running something like

    $ scancode -f spdx-tv NOTICE a.spdx

results in

      File "scancode-toolkit/src/scancode/cli.py", line 717, in save_results
        write_document(doc, output_file)
      File "scancode-toolkit/local/lib/python2.7/site-packages/spdx/writers/tagvalue.py", line 188, in write_document
        out.write('# Document Information\n\n')
    TypeError: write() argument 1 must be unicode, not str

@pombredanne As I'm still a Python beginner, do you think this can be fixed without modifying the spdx-tools package to write *unicode* instead of *str*?

**Comment by pombredanne** [comment]
@sschuberth I think that the SPDX tools should be unicode all the way. And for now in ScanCode you could work around this by forcing the doc to be unicode in:
https://github.com/nexB/scancode-toolkit/blob/99f0a0de9062c44cc8cdb9cf3a7efd270dbdfd57/src/scancode/cli.py#L714
with something like 
```
doc = unicode(doc, 'utf-8')
```

**Comment by pombredanne** [comment]
but one sec... this is non sense. Hold on

**Comment by pombredanne** [comment]
Use something like this for now:
```
        from StringIO import StringIO

        doc_as_string = StringIO()
        
        if format == 'spdx-tv':
            from spdx.writers.tagvalue import write_document
            write_document(doc, doc_as_string)
        else:
            from spdx.writers.rdf import write_document
            write_document(doc, doc_as_string)

        output_file.write(unicode(doc_as_string.getvalue(), 'utf-8'))
```

**Comment by pombredanne** [comment]
This will fail if the output is not unicode-decodable.... but I think this is OK for now.

**Comment by pombredanne** [comment]
FWIW, I tested locally the proposed solution above and it works fine.

**Comment by sschuberth** [comment]
> output_file.write(unicode(doc_as_string.getvalue(), 'utf-8'))

Interestingly, with that I was getting

    TypeError: decoding Unicode is not supported

This apparently is because `getvalue()` already *does* return unicode, so I've changed the code to just

    output_file.write(str_buffer.getvalue())

see PR #441. However, I'm wondering why the code was working for you then. Any idea about that?

**Comment by pombredanne** [comment]
@sschuberth I had made only a quick test ... and I may not have pasted exactly what I tested :)
