### ISSUE TITLE
I can only see the resources displayed as a table instead of a tree.

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#45]
I ran: scancode --format html-app samples samples.html on my windows machine.

And the result on my machine only shows table on left resource panel. 
![sample](https://cloud.githubusercontent.com/assets/13014965/9005734/435abfc6-37b3-11e5-9341-dcfe144619e5.png)

**Comment by pombredanne** [comment]
This is likely due to using backslashes vs posix paths.

**Comment by pombredanne** [comment]
This is a tree alright but not broken down in nodes

**Comment by pombredanne** [comment]
The issue is posix path vs. windows path separator on the one hand and also #46 absolute vs. relative path on the other hand

**Comment by pombredanne** [comment]
This is fixed now
