### ISSUE TITLE
Exception: unable to get the scancode report 

### ISSUE THREAD

**Issue by aparnaNammi** [nexB/scancode-toolkit#462]
Hi, I'm not able to see the scancode report after successfully running the scancode  on my codebase, 
When I try to debug I see the below exception as and when I click on any folder in the left side project tree.{exception}	Unable to get property 'aDataSort' of undefined or null reference at 
File: jquery.dataTables.min.js, Line: 64, Column: 204
Please help.
Thanks  Aparna.

**Comment by pombredanne** [comment]
@aparnaNammi Thank you for this other report!
Can you tell me:
1. which version of ScanCode do you use? (e.g `develop` and a commit or a release and which one?)
2. which command line options did you use for this run? (and which format?)
3. assuming you are looking at an HTML or HTML app output, what is your web browser?

**Comment by aparnaNammi** [comment]
Thanks for quick response, the below are the details for your questions
1. scancode-toolkit-2.0.0rc1
2. ./scancode --format html-app project_R1.17 project_R1.17_result.html --verbose
3.  IE 11

**Comment by pombredanne** [comment]
Could you try if you have the same problem with the latest from develop that you can get here: https://github.com/nexB/scancode-toolkit/archive/develop.zip ?

rc1 is a tad old version as we are closing on 2.0.0 (Per https://github.com/nexB/scancode-toolkit/compare/v2.0.0.rc1...develop there have been over 450 commits since ;) )

**Comment by aparnaNammi** [comment]
Thank you so much . I will take the latest one and proceed

**Comment by pombredanne** [comment]
@aparnaNammi any update? did this work for you?

**Comment by pombredanne** [comment]
Closing now since there is no conversation. Please check https://github.com/nexB/aboutcode-manager too!
