### ISSUE TITLE
Make scancode --version report the Git commit

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#465]
When using ScanCode's `develop` branch and updating often, the version number in the source code / last tag in Git stays the same although potentially quite a lot of code has changed. A such it would be beneficial if `scancode --version` would report its Git commit in some way in order to determine the exact version, maybe by appending the output of `git describe --tags`. That would also solve the problem of keeping the source code in sync with Git tags, as the current source code reports "ScanCode version 2.0.0rc3" although the latest Git tag is "v2.0.0.rc2". Maybe baking the version info into ScanCode could be done as part of running `configure`?

**Comment by pombredanne** [comment]
@sschuberth I agree with you. The only difficulty is to get something that works all the time when you are either running:
1. from a `git clone` where git is available or not
2. from a Github tar/zipball download
3. from a release download (e.g. a Python sdist)

There are many tools available that may help... but I do not know if they can support all three cases without requiring to have Git installed as a dependency. This would require some research. 

- https://pypi.python.org/pypi?%3Aaction=search&submit=search&term=setuptools%20Git
- https://pypi.python.org/pypi?%3Aaction=search&submit=search&term=setuptools%20scm
- https://pypi.python.org/pypi?%3Aaction=search&submit=search&term=setuptools%20vcs

**Comment by pombredanne** [comment]
This is fixed. Right @sschuberth ?

**Comment by sschuberth** [comment]
Yes, thanks @pombredanne!
