### ISSUE TITLE
Add `sfl-license` rule

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#475]
```
    License:    This is free software; you can redistribute it and/or modify
                it under the terms of the SFL License Agreement as provided
                in the file LICENSE.TXT.  This software is distributed in
                the hope that it will be useful, but without any warranty.
```
The above license is detected as `"key":"lgpl-2.1","score":41.67`
The correct license should be `sfl-license`

**Comment by pombredanne** [comment]
For reference here is a link http://bioinfo.mbb.yale.edu/genome/yeast/cluster/database/php-3.0.14/dl/crypt/prelude.h

**Comment by agneet42** [comment]
hi. i'd like to work on this. could someone guide me through?

**Comment by pombredanne** [comment]
@agneet42 Thanks for your interest. Did you read the wiki docs and the README on the topic of adding license rules and tests? See https://github.com/nexB/scancode-toolkit/wiki/How-to:-Add-new-license-rules-for-enhanced-detection 

A good intro is also to study this PR: https://github.com/nexB/scancode-toolkit/pull/498 to get what it means.

**Comment by agneet42** [comment]
Thank you sir. I'm going through the topic of adding license rules and tests.
