### ISSUE TITLE
Externalize licenses rules and tests in new repo: collaboration with Debian

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#477]
I chatted with Debian developers: @jonassmedegaard in particular and  we agreed to start some collaboration. 

The data set of licenses and licenses tests available in scancode is rather meaty (and possibly quite unique and valuable of its own).

The idea would be to externalize and promote the licenses, rules and test data to their own repository  such that the Debian maintainers and anyone else can use building license detection tools can reuse these possibly to refine other tools. And we can also all collaborate more easily to make this data better and richer for everyone.

The project would likely live at https://alioth.debian.org/projects/licenses/ and may be mirrored to Github for convenience (for scancode users/contributors)

Others have expressed some interest or a positive feedback on the idea:
 @marga-debian  @maxyz  @zacchiro @olasd @carandraug @dod38fr

**Comment by pombredanne** [comment]
I am not sure the effort is worth it to break things in separate repo. 
@jonassmedegaard I think this has not been in your way anyway, correct?

We have however published https://scancode-licensedb.aboutcode.org/ with the data and this will soon also be available at https://licensedb.org/

So I am closing this now.

**Comment by jonassmedegaard** [comment]
What would be helpful to me is the tests - not the polished license data.

It seems that the source for the LicenseDB project is https://github.com/nexB/scancode-licensedb - which does not contain any tests :-(
