### ISSUE TITLE
License detection error for fuse 2.9.1 

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#478]
The fuse project contains non-standard LGPLv2 notices which are reported as "gpl".  The error was found in fuse 2.9.1 from https://github.com/libfuse/libfuse/archive/fuse_2_9_1.tar.gz.
1. The line numbers for the license are correctly identified, but the following notice text  is reported as "gpl":
>   This program can be distributed under the terms of the GNU LGPLv2.
>   See the file COPYING.LIB

See the /include/ and /lib/ directories for many examples of this error.

2. The file /include/fuse_kernel.h has a license choice of GPL or BSD-Simplified, but it is is reported as gpl, lgpl and bsd-simplified.  There is no LGPL notice text in this file. The text is:

> This program can be distributed under the terms of the GNU GPL.
>     See the file COPYING.
> 
>     This -- and only this -- header file may also be distributed under
>     the terms of the BSD Licence as follows:
> 
>     Copyright (C) 2001-2007 Miklos Szeredi. All rights reserved.
> 
>     Redistribution and use in source and binary forms, with or without
>     modification, are permitted provided that the following conditions
>     are met:
>     1. Redistributions of source code must retain the above copyright
>        notice, this list of conditions and the following disclaimer.
>     2. Redistributions in binary form must reproduce the above copyright
>        notice, this list of conditions and the following disclaimer in the
>        documentation and/or other materials provided with the distribution

**Comment by pombredanne** [comment]
Reviewed as fixed. @johnmhoran Thanks!
