### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#48]
OS: Windows 8.1 64-bit
Python version 2.7 (for windows 64 bit)
Scan-code release version: 1.3.1
I am trying to find the license name for the following text:
```Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the Thai Open Source Software Center Ltd nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.```
- I have extracted the scan-code and opened a terminal in the Scan-code directory. 
- Copied the above text into a file "test-license.txt"
- Ran the command `scancode --license C:\Users\***\Documents\test-license.txt`

The following error message was displayed:
```
[------------------------------------]  1
Traceback (most recent call last):
 File "C:\Users\rakesh\Documents\scancode-toolkit-1.3.1\bin\scancode-script.py"
, line 9, in <module>
   load_entry_point('scancode-toolkit==1.3.1', 'console_scripts', 'scancode')()

 File "C:\Users\rakesh\Documents\scancode-toolkit-1.3.1\lib\site-packages\click
\core.py", line 664, in __call__
   return self.main(*args, **kwargs)
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\scancode\cli.py", l
ine 230, in main
   standalone_mode=standalone_mode, **extra)
 File "C:\Users\rakesh\Documents\scancode-toolkit-1.3.1\lib\site-packages\click
\core.py", line 644, in main
   rv = self.invoke(ctx)
 File "C:\Users\rakesh\Documents\scancode-toolkit-1.3.1\lib\site-packages\click
\core.py", line 837, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "C:\Users\rakesh\Documents\scancode-toolkit-1.3.1\lib\site-packages\click
\core.py", line 464, in invoke
   return callback(*args, **kwargs)
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\scancode\cli.py", l
ine 290, in scancode
   results.append(scan_one(input_file, copyright, license, verbose))
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\scancode\cli.py", l
ine 336, in scan_one
   data['licenses'] = list(get_licenses(input_file))
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\scancode\api.py", l
ine 80, in get_licenses
   from licensedcode.models import get_license
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\licensedcode\models
.py", line 41, in <module>
   from licensedcode import index
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\licensedcode\index.
py", line 31, in <module>
   from textcode import analysis
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\textcode\analysis.p
y", line 32, in <module>
   import typecode.contenttype
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\typecode\contenttyp
e.py", line 48, in <module>
   from typecode import magic2
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\typecode\magic2.py"
, line 209, in <module>
   libmagic = load_lib()
 File "c:\users\rakesh\documents\scancode-toolkit-1.3.1\src\typecode\magic2.py"
, line 193, in load_lib
   root_dir = command.get_base_dirs(typecode.bin_dir)[0]
IndexError: list index out of range
```

**Comment by pombredanne** [comment]
Thanks for the bug report. This is partly a bug and partly not.

First Python 64 bits is not supported on Windows, you need to use Python 32 bits. This is explained in the installation doc in the README

Second, this is a bug in the sense that you should have received a more explicit message telling you and not this strack trace.

**Comment by pombredanne** [comment]
@rakeshbalusa Could you test the latest develop branch ? You should get a better error message now.

**Comment by jdaguil** [comment]
@rakeshbalusa could you test if this is fixed?

**Comment by rakeshbalusa** [comment]
@pombredanne  there is no error now and it has shown "bsd-new" as output. I put all the license text in `one single line` and it still worked !!

**Comment by pombredanne** [comment]
@rakeshbalusa thanks!. Closing
