### ISSUE TITLE
File type information in JSON output should be "false" instead of "null"

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#495]
In JSON output with `--info`, we have e.g.

    ...
    "is_binary": null,
    "is_text": true,
    ...

It seems odd that `is_binary` is `null` instead of `false`, as it should be the opposite of `is_text`'s value. Likewise for the other `is_*` key, they never seem to be `false`, just `null`.

**Comment by pombredanne** [comment]
Let me dig why this is the case: I may wanted these to be used as tri-boolean, but I doubt and this is more likely a bug. Good catch! In Python `false` is `False` and `null` is `None` and they both result to `False` in an `if XXX` like expression, but this may not be the case in other languages.... and to your point it does not look good nor consistent.

**Comment by pombredanne** [comment]
All merged in develop. @sschuberth Thanks for the report!
