### ISSUE TITLE
License (with FSF copyright) is not properly detected in re2 project

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#496]
I'm scanning the [re2](https://github.com/google/re2) project. While the copyright of [Copyright (c) 2009 Free Software Foundation, Inc.](https://github.com/google/re2/blob/master/benchlog/benchlog.c2#L1664) is detected fine, only an "unknown" license is found in [these](https://github.com/google/re2/blob/master/benchlog/benchlog.c2#L1665-L1666) lines.

I wonder if it makes sense to create a special rule here, and if the license (GPL-2 in this case, as the code comes from g++) really cannot be determined, at least call it something like "fsf-unknown"?

**Comment by pombredanne** [comment]
Thanks. Let me look into this right away.

**Comment by pombredanne** [comment]
I could add a rule for this.... but fsf-unknown feels may be a tad dry?
```
# This is free software; see the source for copying conditions.  There is NO
# warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Normally this `see the source for copying conditions` should ideally 1. be detected 2. be resolved with #377 and there is some WIP code in this [branch](https://github.com/nexB/scancode-toolkit/tree/377-detect-see-file-licenses)

**Comment by sschuberth** [comment]
Dealing with this more generally as part of #377 sounds like the best solution to me. I'm fine with waiting for your respective branch to get merged and do not require a rule to be added right now. So feel free to close this :-)

**Comment by pombredanne** [comment]
@sschuberth I will surely not close... And adding a `free-unknown` make sense in addition to the plain unknown. The FSF part is really the copyright which by design should not be part of the license itself. Let me add this change to get   `free-unknown` in these cases

**Comment by pombredanne** [comment]
@sschuberth there you go. There is quite a variety of these free but not clearly stated license notices FWIW. I also refined quite a few more along the way.

**Comment by pombredanne** [comment]
@sschuberth if the new `free-unknown` license works for you then you can close this alright

**Comment by sschuberth** [comment]
Looks like it's working great, thanks!
