### ISSUE TITLE
Ruby "same terms as" license notice incorrectly identified as GPL|Artistic 2.0

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#499]
ScanCode detects the following license notice,
https://github.com/google/signet/blob/master/lib/compat/digest/hmac.rb#L33 as "GPL" and as "Artistic 2.0":

> All rights reserved.  You can redistribute and/or modify it under
> the same terms as Ruby.

I assume this is because of the resemblance of the "same terms as" Ruby license notice to the old GPL/Artistic Perl counterpart.

**Comment by richardfontana** [comment]
Here's a similar case from another project (unicorn)
https://bogomips.org/unicorn.git/tree/ext/unicorn_http/unicorn_http.rl 
https://bogomips.org/unicorn.git/tree/lib/unicorn/app/old_rails.rb
https://bogomips.org/unicorn.git/tree/lib/unicorn/app/old_rails/static.rb
https://bogomips.org/unicorn.git/tree/lib/unicorn/cgi_wrapper.rb
https://bogomips.org/unicorn.git/tree/test/test_helper.rb
https://bogomips.org/unicorn.git/tree/test/unit/test_http_parser.rb
https://bogomips.org/unicorn.git/tree/test/unit/test_request.rb
https://bogomips.org/unicorn.git/tree/test/unit/test_response.rb
https://bogomips.org/unicorn.git/tree/test/unit/test_server.rb
https://bogomips.org/unicorn.git/tree/test/unit/test_signals.rb

> * You can redistribute it and/or modify it under the same terms as Ruby 1.8 or
>  * the GPLv2+ (GPLv3+ preferred)

**Comment by pombredanne** [comment]
@richardfontana Thanks for the report. Working on it. This is likely resolved with a simple license detection rule addition.

**Comment by pombredanne** [comment]
For reference this is a test scan with diagnostic before fixing.
It matched this [rule](https://github.com/nexB/scancode-toolkit/blob/22727b91059c458377da7aa43da763459abe2354/src/licensedcode/data/rules/artistic-2.0_or_gpl_5.RULE)

As a side note GPL and Artistic are detected together bu not yet reported as a proper expression which will be done soon as part of this ticket #74 

```
$ ./scancode -l -f json-pp --license-text --diag  tests/licensedcode/data/licenses/hmac.rb
Scanning files for: licenses with 1 process(es)...
Building license detection index...Done.
Scanning files...
  [####################################]  1                  
Scanning done.
Scan statistics: 1 files scanned in 2s.
Scan options:    licenses with 1 process(es).
Scanning speed:  0.82 files per sec.
Scanning time:   1s.
Indexing time:   1s.
Saving results.
{
  "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
  "scancode_version": "2.0.0rc3",
  "files_count": 1,
  "files": [
    {
      "path": "hmac.rb",
      "scan_errors": [],
      "licenses": [
        {
          "key": "artistic-2.0",
          "score": 60.0,
          "short_name": "Artistic 2.0",
          "category": "Copyleft Limited",
          "owner": "Perl Foundation",
          "homepage_url": "http://www.perlfoundation.org/",
          "text_url": "http://www.perlfoundation.org/attachment/legal/artistic-2_0.txt",
          "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:artistic-2.0",
          "spdx_license_key": "Artistic-2.0",
          "spdx_url": "http://spdx.org/licenses/Artistic-2.0",
          "start_line": 33,
          "end_line": 34,
          "matched_rule": {
            "identifier": "artistic-2.0_or_gpl_5.RULE",
            "license_choice": true,
            "licenses": [
              "artistic-2.0",
              "gpl"
            ],
            "matcher": "3-seq",
            "rule_length": 20,
            "matched_length": 12,
            "match_coverage": 60.0,
            "rule_relevance": 100
          },
          "matched_text": "You can redistribute and/or modify it under\n# the same terms as"
        },
        {
          "key": "gpl",
          "score": 60.0,
          "short_name": "GPL",
          "category": "Copyleft",
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "",
          "text_url": "",
          "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl",
          "spdx_license_key": "GPL-1.0+",
          "spdx_url": "",
          "start_line": 33,
          "end_line": 34,
          "matched_rule": {
            "identifier": "artistic-2.0_or_gpl_5.RULE",
            "license_choice": true,
            "licenses": [
              "artistic-2.0",
              "gpl"
            ],
            "matcher": "3-seq",
            "rule_length": 20,
            "matched_length": 12,
            "match_coverage": 60.0,
            "rule_relevance": 100
          },
          "matched_text": "You can redistribute and/or modify it under\n# the same terms as"
        }
      ]
    }
  ]
}
```

**Comment by pombredanne** [comment]
This [commit](https://github.com/nexB/scancode-toolkit/commit/1aadc9680c92661c2e8f7a4b4719756de715bb7f) fixes the first part of your report, i.e.
> ScanCode detects the following license notice,
> https://github.com/google/signet/blob/master/lib/compat/digest/hmac.rb#L33 as "GPL" and as "Artistic 2.0"

by adding a new rul and test

**Comment by pombredanne** [comment]
For the [second part](https://github.com/nexB/scancode-toolkit/issues/499#issuecomment-280540696) of this ticket, I reckon that Ruby licenses are a tad messy, so let me take advantage of this report to clean things up and getting back to the bottom on the variations by working from the COPYING history: https://github.com/ruby/ruby/commits/trunk/COPYING

Note that the approach is to detect the ruby licenses proper as ruby and the variations of dual licensing of ruby+gpl (various versions) and ruby+bsd as rules detecting both licenses together.

**Comment by pombredanne** [comment]
So the 
- [ruby.LICENSE](https://github.com/nexB/scancode-toolkit/blob/1aadc9680c92661c2e8f7a4b4719756de715bb7f/src/licensedcode/data/licenses/ruby.LICENSE) is (no longer up to date)  a 1999 version of Ruby licensing. It contains the dual licensing terms and should not.
- [ruby.SPDX](https://github.com/nexB/scancode-toolkit/blob/1aadc9680c92661c2e8f7a4b4719756de715bb7f/src/licensedcode/data/licenses/ruby.SPDX) points to the latest 2010 text
- [ruby-2011](https://github.com/nexB/scancode-toolkit/blob/1aadc9680c92661c2e8f7a4b4719756de715bb7f/src/licensedcode/data/licenses/ruby-2011.LICENSE) is just the dual licensing ruby+bsd. It should be rules and not a license proper

So I will move the ruby.SPDX to replace the ruby.LICENSE (and keep ruby.LICENSE as a license RULE) THEN... retire the ruby-2011 license to a RULE detecting dual ruby+bsd  AND add new rules and tests for each of the historical variants of Ruby (eventually with the various dual licensing statements) AND create new rules for the issues you reported above.

**Comment by richardfontana** [comment]
@pombredanne Because of the confusion that seems inherent in much of the use of "same terms as" Ruby licensing, I think it may be best _not_ to flesh it out too much - rather it is better to signal to the user that there is some sort of Ruby License licensing here. So maybe just reporting as 'ruby' is best.

**Comment by pombredanne** [comment]
@richardfontana  Reporting `ruby` is what happens now so we can leave it this way then.

**Comment by pombredanne** [comment]
@richardfontana as a fun fallout of my diffing the history of all these Ruby license texts... I am now the author of the latest version of the Ruby license https://github.com/ruby/ruby/commit/9cbe4553f4e25d0a9beb4b6393b601c1d0ab3a17
This is a minor change (only whitespaces ;) )

**Comment by pombredanne** [comment]
@richardfontana if you do not have further feedback can I go ahead and close this?

**Comment by richardfontana** [comment]
@pombredanne Thank you, no further feedback.
