### ISSUE TITLE
Weird copyright detected in binary data stream

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#50]
reported by @chinyeungli

In this archive https://rubygems.org/downloads/chunky_png-1.2.8.gem the file:
`chunky_png-1.2.8.gem-extract/data.tar.gz-extract/spec/resources/pixelstream.rgb `
gets a very weird copyright detected (with a long yyyyycccc type of string)

**Comment by pombredanne** [comment]
Looking a bit at the file:
1. this is a binary data stream of "pixels"
2. when strings are extracted there are a few typical things:
2.1 long runs of repeated characters and sometimes long runs of null characters. I think that considering a run of more than about 5 or 10 repeated chars would qualify a string as junk, copyright-wise
2.2 things that are gibberish but are are detected as nouns by the POS tagger rules, such as : "OCoIA3A (c) AaOE12OCA1

Digging a bit more, the key issue is that the file is treated as text instead of binary. This is binary for sure, by binaryornot.check.is_binary() on this file returns False.

Let me do a few tests and debug with @audreyr binaryornot head

**Comment by audreyr** [comment]
If you figure out a fix, I'm happy to merge upstream and put out a new binaryornot release.

**Comment by pombredanne** [comment]
@audreyr thanks... I will file a ticket and PR on binaryornot :smile: 
I think the issue stems from looking at bytes from 127 to 256
I will come with a suggestion either refining the heuristic or supplementing it with chardet (though that would be an extra dep)

**Comment by pombredanne** [comment]
See https://github.com/audreyr/binaryornot/issues/10 . Best would be to fix this with a patch to upstream binaryornot

**Comment by pombredanne** [comment]
I contributed a fix to upstream and this was kindly pulled in by @audreyr ... Upgrading to the latest binaryornot is all that is needed
