### ISSUE TITLE
Spurious detection of TreeView licenses in braintree 2.10.3

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#500]
Portions of code in certain files in braintree (version 2.10.3 tested) are incorrectly detected as, variously,  the TreeView Developer and TreeView Distributor licenses:
https://github.com/braintree/braintree_ruby/blob/2.10.3/lib/braintree/customer.rb (TreeView Distributor License detected at lines 3-57 and 67-138)
https://github.com/braintree/braintree_ruby/blob/2.10.3/spec/integration/braintree/address_spec.rb (TreeView Developer License detected at lines 201-273; TreeView Distributor License detected at lines 273-361)
https://github.com/braintree/braintree_ruby/blob/2.10.3/spec/integration/braintree/credit_card_spec.rb (TreeView Developer License detected at lines 11-88; TreeView Distributor License detected at lines 1048-1122)
https://github.com/braintree/braintree_ruby/blob/2.10.3/spec/integration/braintree/customer_spec.rb (TreeView Developer License detected at lines 71-112, 654-734, 734-799, 799-851, 855-926, 927-1001)

**Comment by pombredanne** [comment]
@richardfontana Interesting bug. Good catch. Note that if you use the `--format json-pp` or `--format json` (the default) and  do a license scan with these two extra args: `--license-text` to nclude the detected licenses matched text and `--diag` to include additional license detection diagnostic information, the scan result will be much more detailed. And they are good enough to include in a bug report so you do not have then to provide such a detailed report yourself.

**Comment by pombredanne** [comment]
For instance with https://github.com/braintree/braintree_ruby/blob/2.10.3/lib/braintree/customer.rb
and `./scancode -clip -f json-pp --license-text --diag customer.rb customer.rb-scancode.txt`
I get the attached scan : [customer.rb-scancode.txt](https://github.com/nexB/scancode-toolkit/files/782694/customer.rb-scancode.txt)

Some points:
- the score is quite low: e.g. the match covers only a small part of the matched license or rule in ScanCode
- the treeview-distributor.LICENSE(https://github.com/nexB/scancode-toolkit/blob/96ef2946dd83afcff0193253e0bdc6e3339ad12b/src/licensedcode/data/licenses/treeview-distributor.LICENSE) is the matched text and this is a rather exotic license for sure.
- in the matched text section, the parts enclosed in [square brackets] are the part that were not matches. A sequence of six `customer` words was what triggered the detection which is an obvious spurrious and false positive match.

I have two way to resolve this:
1. Set the minimum score that should be reached to consider a match to treeview-distributor.LICENSE as a proper match
2. OR add `customer` as a very frequent word to the `frequent_tokens.py`(https://github.com/nexB/scancode-toolkit/blob/96ef2946dd83afcff0193253e0bdc6e3339ad12b/src/licensedcode/frequent_tokens.py) list of common words that of themselves are not discrimant enough to trigger a license detection.

I may do both in this case.

**Comment by pombredanne** [comment]
This is fixed in the `develop` branch

**Comment by pombredanne** [comment]
And I ended up adding a minimum coverage to the treeview licenses(https://github.com/nexB/scancode-toolkit/commit/22727b91059c458377da7aa43da763459abe2354#diff-6c842226e0264ec27d0299ea72d8e903R7) and `customer`(https://github.com/nexB/scancode-toolkit/commit/22727b91059c458377da7aa43da763459abe2354#diff-98dac1c1db1ec7ba40305fce4cd3037cR4189) and related as frequent tokens.

**Comment by pombredanne** [comment]
@richardfontana if you do not have further feedback can I go ahead and close this?

**Comment by richardfontana** [comment]
@pombredanne Thank you, no further feedback.
