### ISSUE TITLE
Ruby "same terms as" notice incorrectly identified as LGPL 2.1 in extlib 0.9.16

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#501]
The following Ruby license notice in a file in extlib 0.9.16 is incorrectly identified as LGPL 2.1, presumably because it bears some similarity to the standard GNU LGPL notice:
https://github.com/datamapper/extlib/blob/v0.9.16/lib/extlib/dictionary.rb#L22

>   This module is free software. You may use, modify, and/or redistribute this
>   software under the same terms as Ruby.
>  
>   This program is distributed in the hope that it will be useful, but WITHOUT
>   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
>   FOR A PARTICULAR PURPOSE.

**Comment by pombredanne** [comment]
Thanks. This should be an easy fix with a new detection rule.

**Comment by pombredanne** [comment]
This should be fixed now.

**Comment by pombredanne** [comment]
@richardfontana if you do not have further feedback can I go ahead and close this?

**Comment by richardfontana** [comment]
@pombredanne Thank you, no further feedback.
