### ISSUE TITLE
Collect more data from Maven POMs

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#505]
"dependency_version", "dependency_scope", "contributor_email", "issue_url"  fields are not captured yet in the Maven parser: and we should to support these fields

**Comment by pombredanne** [comment]
@linexb  Could you look instead in a completely different implementation of parsing Maven POMs? with https://github.com/sassoftware/pymaven  and in a maven2.py script? I think this would be much better to get actual deps. And eventually we can patch pymaven and submit upstream our improvements as it may support dependencies well but not basic information fields.

See also https://github.com/sassoftware/pymaven/issues/3

**Comment by pombredanne** [comment]
These are captured now but may not be full added to packages as part of #529

**Comment by pombredanne** [comment]
This is merged in develop.
