### ISSUE TITLE
Cannot run scancode from another directory anymore

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#506]
From @sschuberth  in https://github.com/nexB/scancode-toolkit/pull/503#issuecomment-281369099

your fix for this regression introduced another regression :-) Now, we cannot run `scancode` from another directory than the scancode directory itself anymore. I.e. running

    scancode-toolkit/scancode -f json scancode-toolkit/AUTHORS.rst

results in

      File "scancode-toolkit/src/scancode/cli.py", line 82, in <module>
        notice_text = open('NOTICE').read()
    IOError: [Errno 2] No such file or directory: u'NOTICE'

**Comment by pombredanne** [comment]
@sschuberth This commit is fixing this

**Comment by sschuberth** [comment]
@pombredanne I also see commit to the `tests` directory. Did you forget to push something?

**Comment by pombredanne** [comment]
@sschuberth I had. Thanks!

**Comment by pombredanne** [comment]
I will merge this is ass soon as the tests are done on at least one Ci host.

**Comment by pombredanne** [comment]
This is all fixed and merged. Thanks!

**Comment by sschuberth** [comment]
Confirmed to be fixed, thanks!
