### ISSUE TITLE
GPL-3.0 license notice identified as GPL-2.0 in cloud-init

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#508]
ScanCode applied to the current master branch of cloud-init (https://git.launchpad.net/cloud-init/) identifies a standard GPL-3.0 license notice as GPL-2.0.
[LICENSE-scancode.txt](https://github.com/nexB/scancode-toolkit/files/791201/LICENSE-scancode.txt)

**Comment by pombredanne** [comment]
@richardfontana Thank you for the report!

**Comment by pombredanne** [comment]
@richardfontana This latest commit in the `develop` branch should fix your issue

**Comment by pombredanne** [comment]
@richardfontana any other feedback on this? If this fixed to your satisfaction you can close alright

**Comment by richardfontana** [comment]
Thanks @pombredanne
