### ISSUE TITLE
Benchmark ScanCode with PyPy / Pyston

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#512]
Hi @pombredanne! I wonder whether you have ever done any benchmarking with using [PyPy](http://www.pypy.org/) or [Pyston](https://github.com/dropbox/pyston) instead of the default CPython. Would you expect any considerable speedup?

**Comment by sschuberth** [comment]
> PyPy does not support native C extensions

They [seem to do](http://doc.pypy.org/en/latest/faq.html#do-cpython-extension-modules-work-with-pypy), but from what I read it does not really make sense performance-wise.

> I would not expect considerable speedups as there is good part of scanning files which is about I/O

That's what I was thinking, too. Glad you confirm it.

> I do not know about Pyston internals and this could be worth a try.

The [blog](https://blog.pyston.org/) says "It uses modern JIT techniques and natively supports many CPython C extension modules". On the other hand Dropxbox just announced they'd be discontinuing sponsoring Pytson development, so maybe its future is a bit uncertain.

**Comment by sudeepb02** [comment]
Hello, I'd like to work on this issue. Would you please guide me to get started?

**Comment by pombredanne** [comment]
@sudeepb02 simply: try to install ScanCode on Pypy and Pyston. This is a long shot though and this may just NOT work at all. In which case the case is closed.

If you are interested in benchs as a GSOC project proposal, I suggest you look at this project idea: #378

**Comment by sudeepb02** [comment]
@pombredanne Before running the test with Pypy, I ran all the tests with Python and there are out of the total test cases 10099 passed, 65 were skipped and 146 have failed. Is this an issue?

**Comment by pombredanne** [comment]
ok I am closing this as we cannot run on Pypy for now anyway.
