### ISSUE TITLE
Identify that information are from scancode or another tool

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#513]
For results such as packages, there is no direct way to determine from the JSON that this came from scancode or another tool. This is implicit. We should have a way to list which tool provided data explicitly.

**Comment by pombredanne** [comment]
A way to track which tools have touched a JSON could be to include some history/log so we know this has been touched by scancode, then aboutcode manager then something else, etc.

**Comment by patniharshit** [comment]
Hi, I am new here. Looking to contribute. Can you guide me on how to start with this issue?

**Comment by kartiksibal** [comment]
@pombredanne I'd like to resolve this, if no one is working on it. 

If no one is. I was thinking of making a log file, wherein, whenever a tool makes changes to the JSON. There is an explicit record. Which can maybe be done, by creating a wrapper/decorator? I am not sure if I am expressing my thought correctly here. Please do share your approach.

Thanks :-)

**Comment by pombredanne** [comment]
@patniharshit @kartiksibal  I guess only one of the two of you should work on this.

 @patniharshit what's your approach? did you start? @kartiksibal same question. 

 @kartiksibal Your approach sounds ok. Show me some code so I can understand what you mean exactly.

**Comment by kartiksibal** [comment]
@pombredanne Sure. I'll do that.

**Comment by kartiksibal** [comment]
@pombredanne I am thinking of making a `@log`, decorator, for this, which will write to a file whenever a change to JSON has been made, hence containing the tool used. 

Am I somewhere near, to what your expectations are with this? :-)

**Comment by patniharshit** [comment]
@pombredanne I didn't had any ideas in particular. I was hoping to get started here if somebody could guide me on what to do. 
But since kartiksibal has something, I am cool with he going ahead with this.

**Comment by kartiksibal** [comment]
@patniharshit I think, what matters is coming up with an efficient solution to the problem, it doesn't matter who does it. We are here to improvise the product and learn. :-D

I'd love to know how you were thinking of approaching this issue. :-)

**Comment by pombredanne** [comment]
@kartiksibal I can comment when I see some code.

**Comment by kartiksibal** [comment]
@pombredanne I am on it.

**Comment by pombredanne** [comment]
@kartiksibal you wrote:

> I have made a very minuscule change in /src/scancode/cli.py. Just when we dump the JSON data, I have added this . Is this somewhere on the lines of what you were expecting with this enhancement? :-)

It is hard for me to review paste bins: do you mind make a PR for your change or attach or submit a patch instead?

**Comment by kartiksibal** [comment]
@pombredanne Apologies for the delay, got too engrossed in the project and I messed up a little here. :sweat_smile:

**Comment by pombredanne** [comment]
This is closed in favor of tracking this in #211
