### ISSUE TITLE
Spurious detection of ACE TAO license 

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#519]
In the file tzfile.h in ICU (Icu4c, version 57.1, file source/tools/tzcode/tzfile.h (checked out from svn repository http://source.icu-project.org/repos/icu/tags/release-57-1), ScanCode detects a set of #define directives as the ACE TAO license. 
[tzfile.h-scancode.txt](https://github.com/nexB/scancode-toolkit/files/800621/tzfile.h-scancode.txt)

**Comment by pombredanne** [comment]
@richardfontana Thank you for the report! This now is fixed in the `develop` branch.

**Comment by pombredanne** [comment]
@richardfontana any other feedback on this? If this fixed to your satisfaction you can close alright

**Comment by richardfontana** [comment]
Thanks @pombredanne
