### ISSUE TITLE
--extract should not be an option but a separate command

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#52]
Extraction feels like a wart in the scancode command. It does not share any of the semantics of the command and should be best as a separate command such as `extractcode` that would only extract things.

**Comment by mjherzog** [comment]
I strongly agree - we, of all people, know how many twists and turns there are for extraction so it needs to be part of a scanning pipeline, but not deeply embedded in other steps in the scanning pipeline.

**Comment by pombredanne** [comment]
This is fixed now
