### ISSUE TITLE
Add support for composite licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#522]
Some licenses such as SPDX's sleepycat and the licenses parked in https://github.com/nexB/scancode-toolkit/tree/d1da4db48a768a870332489507af7ae926becf34/src/licensedcode/data/composites and https://github.com/nexB/scancode-toolkit/tree/d1da4db48a768a870332489507af7ae926becf34/src/licensedcode/data/composites-rules are not plain "lower level" licenses, but composed of several licenses.

They are valuable in that they provide a way to report the common licensing of common packages (such as NetSNMP) with a single key.

We should support detecting and reporting these. I am thinking of this approach:

- add a new flag to License `is_composite` for such licenses. Also add that same flags to the corresponding Rules
- add a new field to License `composite_expression` for such licenses that would be the underlying license expression this license is made of.

For detection, these licenses and rules would be excluded from the main license detection flow. Once matches have been collected and if a match to the same licenses as a composite is found, then a second level of limited matching would be done against the related composite. If the composite is effectively matched, then the original match would be replaced by the composite match.

**Comment by mjherzog** [comment]
Two comments:
1. Conjunctive is likely a  better name than composite
2. How could we design this so that we flag new license/notice files that are very likely conjunctive licenses/notices from the scan?  The pattern of multiple licenses in one file should be a strong clue for this and in most cases it is likely to be conjunctive rather than disjunctive.

**Comment by pombredanne** [comment]
@mjherzog 
1. I am not sure conjunctive is a better name as the underlying expression could be a complex combo of conjunctions and disjunctions?  eg. `gpl-2.0 or later with classpath exception and (mit or gpl-2.0 or later) and bsd`
2. actually we would only report as a composite things that are known to be a composite (e.g starting with the few we have [here](https://github.com/nexB/scancode-toolkit/tree/d1da4db48a768a870332489507af7ae926becf34/src/licensedcode/data/composites) ... so we would never flag new combos of licenses as composites unless they are known ahead of time to be a composite. We we find otherwise multiple licenses in a file, these will  be reported as a list of license expressions based on how each license or group of licenses was detected. We could also craft a synthetic file-level expression that would combine (and simplify) all the licenses found in one file in one expression, but that would be a summary and would not replace each individual detections IMHO

**Comment by pombredanne** [comment]
So here is the plan:

Support for composite licenses detection in ScanCode would come along these lines:

Because they contain several other existing license texts, even though they could easily be detected at once,  their text and rules introduces too much bias in the detection which ends up often being inaccurate.

Therefore the approach would be to know which licenses are composite and what is the corresponding expression of lower level licenses. 

We would need to know when a license is actually a composition of several existing licenses. This is the case for things such as dropbear, net-snmp and so on. This will be a field `composite_of` with a license `expression` that would list the underlying licenses.

The scan would look this way:  
1. the license and rules texts for composite licenses would not be part of the main detection index, but from a secondary index only.
2. the detection would work first on the main index, detecting eventually all lower level licenses
3. then for license matches found in a given file, if all the detected licenses correspond to the lower level licenses of an existing composite license, a second rematch would be done this time only to verify if what we detected is really a composite or instead only lower level licenses.
4. based on this secondary matching, we would return either the composite or the lower level licenses.

**Comment by mjherzog** [comment]
One other perspective is to define this as "composite notice" rather than composite license where license expression covers the combination of licenses and the typical pattern is that the composite license notice is normally documents subcomponent-license combinations.  So the combination of license conditions is better covered by a corresponding license expression and the composite notice serves two purposes:
- Explanation of subcomponent licensing without complex hierarchies/relationships
- Faster/better Attribution

**Comment by pombredanne** [comment]
After all I have decided not to treat these specially as what we have today is good enough. Instead when they are detected they will be reported as any other license.
