### ISSUE TITLE
json2csv.py should not prepend a root directory on the resource path

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#524]
Now that root paths are reintroduced into ScanCode resource paths, json2csv.py does not need to prepend the resource path with `/code` anymore.

**Comment by pombredanne** [comment]
I think this should become/stay as an option. The output may of may not have a root dir as this is as option on the scancode side.

**Comment by JonoYang** [comment]
I agree that this should become an option. By default, json2csv.py should not add a root directory, as the new version of ScanCode reintroduces root directories. In the cases where the scan result does not have a root directory, then json2csv.py should have an option, like `--prepend-root`.

**Comment by yasharmaster** [comment]
I want to work on this issue. Can someone guide me where to get started?

**Comment by pombredanne** [comment]
@yasharmaster Thanks. You would need to wait for input from @JonoYang for this.

**Comment by JonoYang** [comment]
@yasharmaster 

`json2csv.py` converts ScanCode scan result data from JSON to CSV. For legacy compatibility, the path value is prepended with `/code`. Since the newer releases of ScanCode, we do not need to prepend `/code` anymore, but this should be an option if we ever need to do so. 

You should start by finding the script here:
- https://github.com/nexB/scancode-toolkit/blob/develop/etc/scripts/json2csv.py

You should look at the `flatten_scan()` and `cli()` functions to see how the path value is being changed and to see where to add in options.

**Comment by kartiksibal** [comment]
@JonoYang When exactly is **json2csv.py** being called?

**Comment by jack17529** [comment]
@kartiksibal  dude I have nearly solved it please take another issue ,I gonna submit P.R.

**Comment by pombredanne** [comment]
@kartiksibal @jack17529 there is already a work in progress PR by @yasharmaster who is working on this: a different PR is always welcomed, but duplicating work does not make sense especially on such a small feature. 

You should collaborate instead such as providing comments and feedback and review on the current PR.

**Comment by pombredanne** [comment]
And yet another PR #541 that I had to close ass duplicate from @sudeepb02 
... Please have mercy on us: one at a time!

**Comment by kartiksibal** [comment]
Haha. Also, @pombredanne It'd be awesome if you could assign the issue, to whoever is working on it. It'd avoid such confusions in the future. Cheers! :-D

**Comment by pombredanne** [comment]
@kartiksibal issues in GH can only be assigned to actual project collaborator, e.g. these that have earned comitter right from the project standpoint. This is not great but this is the way for now.
Irrespective of this, asking first on the ticket and checking existing PR and ticket comment is the right thing to do.

**Comment by kartiksibal** [comment]
@pombredanne Oh my bad. That totally skipped my mind and I very much agree to that, which is why I hadn't started working on it. But,  I wasn't able to find where exactly,  is json2csv being used. Hence the question. :-)

**Comment by pombredanne** [comment]
@kartiksibal You run it as `python etc/scripts/json2csv.py` once you have a scan json on hand. Eventually it would need to be made a plugin with #381

**Comment by kartiksibal** [comment]
@pombredanne I hadn't seen #381,  because of which I was confused as to where exactly, is this being used. :-)

**Comment by sudeepb02** [comment]
@pombredanne Sorry for all the trouble. I didn't see if @agneet42 was working on it. Maybe that was because this issue wasn't mentioned in the PR message. Anyway, I'll se if I can help with other issues

**Comment by pombredanne** [comment]
@sudeepb02 no problem. You review if this PR is always welcomed too.

**Comment by sudeepb02** [comment]
@pombredanne Thanks 👍

**Comment by jack17529** [comment]
@pombredanne Please assign me any issue related to this in future if needed.I have worked on the code.

**Comment by pombredanne** [comment]
@jack17529 send a  separate PR if you have worked on a solution. 

I cannot and will not assign you to work on anything: 1. you are not a committer/collaborator on this project (yet). 2. this is not how we work and in anycase to become a full committer/collaborator you would have to demonstrate your abilities first, including being able to submit  proper PRs (and not just one but several over a long period of time).

So if you want to help, participate in the discussion or/and submit PRs. Show us what you can do. Be gentle and read the tickets then ask **before** starting work.

**Comment by jack17529** [comment]
@pombredanne  first you don't answer my comments and then you give your points.

**Comment by JonoYang** [comment]
merged in #597
