### ISSUE TITLE
The UI of html-app produced by the scancode needs some improvement

### ISSUE THREAD

**Issue by singh1114** [nexB/scancode-toolkit#525]
The UI of html-app produced by the command "./scancode --format html-app ...." needs some improvement.

**Comment by mjherzog** [comment]
This app is being deprecated and replaced by AboutCode Manager - https://github.com/nexB/aboutcode-manager

**Comment by majurg** [comment]
I agree with @mjherzog, we are phasing out the usage of `html-app` in favor of `aboutcode-manager` https://github.com/nexB/aboutcode-manager.

Minor changes can certainly be made, but sweeping UI/UX improvements are not what we want to do here. 

@singh1114 What in particular do you wish was different about the `html-app` UI?

**Comment by singh1114** [comment]
@majurg 
These are just the minor changes a few changes like the position of the of few things to make them more readable. You can see the #526 for the for the image of the changes.

**Comment by majurg** [comment]
@singh1114 I am not opposed to the general direction of your changes. However, you need some UI improvement. 

For instance, you would need to make sure the 'bar' object containing the pathname is the same dimensions as the tree-view box below it. 

I also think the the text 'scan results for: ' should be on the same line as the path. In fact, change that would probably make the tests pass without having to change the test cases themselves. 

All in all, these UI changes would need a more 'polish' to be considered an improvement from their current state.

**Comment by singh1114** [comment]
@majurg: I agree on what you suggest about the bar length and the same line thing.

What changes do you suggest for making it "polished"?

**Comment by pombredanne** [comment]
I am closing this and further work on the UI can take place in  https://github.com/nexB/aboutcode-manager that should be used for visualization of scans instead.
