### ISSUE TITLE
Is this a new MIT variant?

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#536]
As a follow up to #534, is this a new MIT variant or not? 
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/plain/drivers/gpu/drm/gma500/cdv_intel_crt.c?id=refs/tags/v4.10

The middle sentence contains this extra: `(including the next paragraph)`
```
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
```
The rest is otherwise 100% MIT.
@DennisClark is this something your legal friends would consider material or not?
and therefore should I treat this as detection rule or a new license?

**Comment by DennisClark** [comment]
I think this is a detection rule issue and not a new license.

**Comment by pombredanne** [comment]
Thanks. We will can then either create a new rule to get 100% or leave it as is and get 99% something detection for this case, as it is now.

**Comment by mjherzog** [comment]
We do not need to add new license samples to get to 100% if we already have 99% - the latter seems very accurate in this case.

**Comment by pombredanne** [comment]
@mjherzog thanks for the input. Closing then.
