### ISSUE TITLE
The root node is not included as part of the scan results

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#543]
This issue relates to how AboutCode Manager displays the JSON scan-result nodes, raising the possibility of including a root node object with a key:value setting of `"type":"directory"` in the scan-result files.  (Whether included in the scan file or inferred by AboutCode Manager, the `type` values (`directory` or `file`) are used to sort sibling nodes and display node icons in the AboutCode Manager tree.)

**Comment by pombredanne** [comment]
@johnmhoran Thanks! 
Now would this apply when you scan a single file? I guess yes?

**Comment by johnmhoran** [comment]
@pombredanne  I'm not sure I understand the import of your question -- could you please expand?

**Comment by pombredanne** [comment]
So say you `scancode myfile.txt` a single file: the path returned is `mydir/myfile.txt` where `myfile.txt` is a single file and `mydir` the parent dir of `myfile.txt`

Say now you `scancode mydir` a dir: the paths returned are `mydir/myfile.txt`  and `mydir/yourfile.txt` that are the two files in `mydir`

 My point is that I guess you want all the details for `mydir` in both cases. Which is an evidence to me now that I explained it.

**Comment by singh1114** [comment]
To clear the statement:
When I scanned samples.html path returned is:
`"path":"scancode-toolkit/samples.html"`
On the other hand when I scanned samples directory:
`"path":"samples/__filenames__"`

So somehow scan-code is telling all the files that it is scanning. So, what @johnmhoran want is to remove the directory name scancode-toolkit from the first case. Am I right @johnmhoran?

**Comment by pombredanne** [comment]
@singh1114 this is about whether or not the root dir has all "info" attributes or not. ATM it does not

**Comment by pombredanne** [comment]
@johnmhoran I am pushing this to post 2.0

**Comment by pombredanne** [comment]
With the latest merge of #885 this has been fixed. Thanks! Closing!
