### ISSUE TITLE
Spurious detection of "Deutsche Freie Software Lizenz" in flatpak 0.8.3

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#549]
ScanCode detects the Deutsche Freie Software Lizens in this German translation file in flatpak 0.8.3
https://github.com/flatpak/flatpak/blob/0.8.3/po/de.po
[de.po-scancode.txt](https://github.com/nexB/scancode-toolkit/files/832151/de.po-scancode.txt)

**Comment by pombredanne** [comment]
@richardfontana Thanks! Looking into this now.

**Comment by pombredanne** [comment]
@richardfontana this isfixed in the `develop` branch. Thanks again for this report.
