### ISSUE TITLE
ScanCode detects original PCRE license in PCRE2 AUTHORS file

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#557]
PCRE2 is basically under the 3-clause BSD license, but I gather that the original version of PCRE was under the legacy [PCRE license](https://enterprise.dejacode.com/licenses/Demo/pcre/), which as far as I can tell is not present in PCRE2. ScanCode appears to detect the PCRE license in the [AUTHORS](https://vcs.pcre.org/pcre2/code/tags/pcre2-10.23/AUTHORS?view=markup) file of PCRE2 because of some author/copyright notice information common with the PCRE license text. 

[AUTHORS-scancode.txt](https://github.com/nexB/scancode-toolkit/files/842669/AUTHORS-scancode.txt)

**Comment by pombredanne** [comment]
@richardfontana Thanks. Working on it.

**Comment by pombredanne** [comment]
@richardfontana This is fixed in the latest `develop` branch.
