### ISSUE TITLE
"All rights reserved." line after copyright stament is not picked up

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#559]
For a copyright statement like

    /*
     * Copyright (c) 2017 HERE Europe B.V.
     * All rights reserved.
     */

ScanCode (commit db5f6eb) only reports

    "copyrights":[{"statements":["Copyright (c) 2017 HERE Europe B.V."],"holders":["HERE Europe B.V."],"authors":[],"start_line":2,"end_line":3}]

in the JSON output, whereas I'd expect the statement to be `"Copyright (c) 2017 HERE Europe B.V.\nAll rights reserved."`

**Comment by pombredanne** [comment]
@sschuberth actually, it was an early choice in the design in the copyright detection. The rationale was this: https://en.wikipedia.org/wiki/All_rights_reserved

> "All rights reserved" is a copyright formality indicating that the copyright holder reserves, or holds for their own use, all the rights provided by copyright law. Originating in the Buenos Aires Convention of 1910, it no longer has any legal effect in any jurisdiction. However, it is still used by many copyright holders.

So I am open to have that back, but the value is low. In the context of a proper and comprehensive notice capture in #260 it would be caught in the combo copyright + license.

**Comment by sschuberth** [comment]
@pombredanne That's interesting feedback, let me point our Legal guys at this.

**Comment by pombredanne** [comment]
@sschuberth It is not often that I can refer to the obsolescence of a 100+ years old international treaty or convention as an excuse to NOT fix a bug. :dancer:

**Comment by sschuberth** [comment]
After some discussion with our Legal department they agree that it's more of a "habit" to include the "All rights reserved", and that they don't regard it as a major issue if it's missing from the detected copyright statement. As such I'm closing this issue.

**Comment by pombredanne** [comment]
@sschuberth Thanks for having followed up on this.
