### ISSUE TITLE
Essential tickets to fix for v2.0 release

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#568]
Here is the list of v2.0 tickets I think should be closed to complete 2.0:
https://github.com/nexB/scancode-toolkit/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0
@sschuberth @chinyeungli @majurg @JonoYang @jdaguil @johnmhoran You input is welcomed.

My goal is to close these asap and push a 2.0.0 final

**Comment by pombredanne** [comment]
Note that most have a fix or need not a lot of work except for #542 but I really want it in 2.0.0

**Comment by sschuberth** [comment]
Can we have #504 on the list?

**Comment by pombredanne** [comment]
@sschuberth done. Though this is one that require potentially significant work and may depend on #377

**Comment by majurg** [comment]
@pombredanne :+1: on the list. The sooner we can push a final the better IMO.

**Comment by pombredanne** [comment]
@sschuberth I want to push a final rc3 today for 2.0 and I will work on #504 right after that.
