### ISSUE TITLE
Add OSET Public License

### ISSUE THREAD

**Issue by yasharmaster** [nexB/scancode-toolkit#570]
The OSET Foundation releases its software via the [OSET Public License](http://www.osetfoundation.org/public-license/). This can be added to the ScanCode licenses.

**Comment by yasharmaster** [comment]
I will open a PR adding the license soon.

**Comment by pombredanne** [comment]
sure :) Start with a test. It is very close to the MPL2

**Comment by pombredanne** [comment]
For reference this was merged in develop with #572 
Thanks!
