### ISSUE TITLE
Update README package names in Debian/Ubuntu python-dev installation command

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-toolkit#579]
Replace `libbz2` with `bzip2` and replace `xzutils` with `xz-utils`

**Comment by pombredanne** [comment]
Actually make sure you handle the changes that occurred between Ubuntu 14 and 16. We still support both. Somewhere in the README history you should see @majurg changes that got wiped out somehow

**Comment by pombredanne** [comment]
e.g. you cannot just replace. You need to add and state which package is for version. Ideally we want to check/confirm that these are the same for Debian too.

**Comment by JonoYang** [comment]
I've set up Ubuntu 12.04 and Ubuntu 14.04 on virtual machines and tried to install the packages from the quick start section using `sudo apt-get install python-dev libbz2 xzutils zlib1g libxml2-dev libxslt1-dev`. Both versions of Ubuntu said that `libbz2` was replaced by `bzip2` and that `xzutils` did not exist. I believe that moving forward with the changes would not cause any issues for users of any recent version of Ubuntu.

**Comment by johnmhoran** [comment]
The reference to the two now-problematic packages appears to have been introduced in [this July 27, 2015 commit](https://github.com/nexB/scancode-toolkit/commit/c22126cafc142c8095dc4007347b0b8495d2fb3d#diff-88b99bb28683bd5b7e3a204826ead112).  It is not clear when these packages became problematic.

**Comment by pombredanne** [comment]
@johnmhoran @JonoYang is this still a thing? I want to close this for 2.0

**Comment by pombredanne** [comment]
Ok, this wass fixed in https://github.com/nexB/scancode-toolkit/commit/d6b82c4e350954718a8cb136b5221c681e258ca1 but the commit was not referenced... hence my confusion!
