### ISSUE TITLE
Commit subjects with #-prefixed issue ids turn into comments

### ISSUE THREAD

**Issue by all3fox** [nexB/scancode-toolkit#580]
Currenty, it is common practice in this repo to write a commit message that begins with a #-prefixed issue number. See for instance:

```
git log -n 1 242bc863ab1ae1481e39bf5ab655236648282219
git log -n 1 150a63755e039bc125bc9857d0dd276e5d143af3
```

However, [`CONTRIBUTING.md`][1] does not actually mention this requirement at all and gives a generic commit message example here [at step 7][2].

Most confusing is probably the fact that `#` by default starts a comment in git message, unless you opt-out for a one-liner message with `git commit -m "#42 Will make it into the message"`. In order to open your commit message with `#`, you have to set your `git.commentchar` to something else first:

```
git config core.commentchar ";"
```

In my opinion, these are not the steps you would like a newcomer to go through. At least they need to be documented in detail.

Finally, a bonus point to consider: if you use a full url to the issue in the following fairly common structures (that ususally come at the very end of the commit message):

```
Fixes: https://github.com/nexB/scancode-toolkit/issues/564
Closes: https://github.com/nexB/scancode-toolkit/issues/564
Refs: https://github.com/nexB/scancode-toolkit/issues/564
```

then you (depending on setup) can Ctrl + click those links in your terminal when doing `git log`. No such possibility with `gh-XXX` or `#XXX` style references. And websites like github will automatically close/reference those issues as usual.

Any thoughts? First confusion occurance [was here][3].

[1]: https://github.com/nexB/scancode-toolkit/blob/5c1d577c6bc39a45c8f978e5b4562c42a2bbaa97/CONTRIBUTING.rst#contributing
[2]: https://github.com/nexB/scancode-toolkit/blob/5c1d577c6bc39a45c8f978e5b4562c42a2bbaa97/CONTRIBUTING.rst#development
[3]: https://github.com/nexB/scancode-toolkit/pull/577#issuecomment-290256071

**Comment by pombredanne** [comment]
This looks good: we can either use this or use end of line issue number which is a tad less verbose. I am going for this for now and I updated https://github.com/nexB/aboutcode/wiki/Writing-good-commit-messages accordingly
