### ISSUE TITLE
ScanCode should support Conda

### ISSUE THREAD

**Issue by aviaryan** [nexB/scancode-toolkit#584]
Right now installation of ScanCode fails when the host environment's primary Python is [Conda](https://www.continuum.io/downloads) (Anaconda or Miniconda). 
I guess this is because Anaconda doesn't work with virtualenv. 
Since Conda is a very popular Python distribution and it supports all major OS platforms, I think ScanCode should support it. 

Ref: [Stacktrace of installing ScanCode over Conda](https://pastebin.com/CbZ2KXjD)

**Comment by pombredanne** [comment]
@aviaryan it has been a long while and nothing has been done here. I think that conda now support pip package installations too nicely, is this right? May be we could convert this ticket to perform this test. I am not super enthused to support yet another packaging format as there is a support and test burden for each one...

**Comment by pombredanne** [comment]
Closing for now.
