### ISSUE TITLE
Multiple repos in one html-app file ?

### ISSUE THREAD

**Issue by kalagp** [nexB/scancode-toolkit#585]
@Hello

I was looking to scan the multiple repos and generate a single html-app file ? Any workaround solution are welcome.

**Comment by pombredanne** [comment]
@kalagp what do you have in mind exactly? e.g. what do you mean by multiple repos?
If you mean multiple directories each containing a check-out of a code repository, you could just put all these in one directory and scan that directory? Or is there something else you had in mind?

**Comment by kalagp** [comment]
@pombredanne is there any limitations if we have multiple check-out of a code repos in one directory ? I am looking around 120 - 150 repos ?

**Comment by pombredanne** [comment]
@kalagp there is no limitations per se, but you are likely to hit some human and hardware limits:

1. the generated file may be so big that it may be impractical to load in a browser
2. there will too much data to review at once
2. the run time may be much longer : now if the repos are all small it may not be an issue. Did you try to run a plain JSON scan with multiple processes? How long does it take in your setup ? 

Now the key question for you is more one of process. What's the benefit of looking at 150 at once vs. looking 150 times at one repo? I tend to think that the later (e.g. divide and conquer) is a better option to avoid info glut and deal with a human accessible volume of data.

Note also that @jdaguil is working on a desktop Electron-based app as a better way to review scans that a static HTML. @jdaguil do you think that your stuff is stable enough for @kalagp to give it a shot?

**Comment by kalagp** [comment]
@pombredanne I have one more question ..

I am scanning the repo by placing the entire thing in one directory, so do we have an option to exclude one particular sub-directory while scanning ?? If so, can you give me an example ??

**Comment by pombredanne** [comment]
@kalagp there is a new feature in https://github.com/nexB/scancode-toolkit/pull/528 to ignore "globs"... It is not yet merged in develop and if you could give a shot at it and tell me if this is what you expect, it would be great!

**Comment by kalagp** [comment]
@pombredanne  Yes, I would like to give a shot. Can you give me some examples on a particular use case ??

**Comment by pombredanne** [comment]
@kalagp It offers a new `--ignore` argument that you can use multiple time to ignore some paths. @yashdsaraf is this a correct depiction?

**Comment by yashdsaraf** [comment]
@pombredanne Yes that is correct. It can ignore multiple paths or files both supporting standard glob pattern (except ```**```).

**Comment by kalagp** [comment]
@pombredanne @yashdsaraf  Awesome.. Is this available in 'develop' branch ??

**Comment by yashdsaraf** [comment]
No not yet, it will be soon though (I hope :P). You can find the relevant code in #528 which is linked to [this repo](https://github.com/yashdsaraf/scancode-toolkit).

**Comment by kalagp** [comment]
@yashdsaraf  Thanks. But let me know once its merged to 'develop' branch.

**Comment by pombredanne** [comment]
@kalagp could you give it a shot for testing before it is merged? That would be very useful

**Comment by kalagp** [comment]
@yashdsaraf  Can we ignore any sub-directory while scanning the parent directory ?? 
For example: scancode --ignore par1/output1 --format par1/ par1/output/test.html ??

**Comment by yashdsaraf** [comment]
Yes, whatever pattern is supplied using the `--ignore` option, all the files are scanned *only* against that pattern, so from the given example, `output1` which is a child of `par1` will be ignored along with all its contents (if any), but the `par1` directory will still be scanned as well as all its contents other than output1. For more examples of ignore option see: https://github.com/yashdsaraf/scancode-toolkit/blob/develop/src/scancode/cli.py#L133

**Comment by pombredanne** [comment]
@yashdsaraf can you provide an example of a CLI?

**Comment by yashdsaraf** [comment]
@pombredanne certainly, if a directory tree like 
`samples`
`samples/arch`
`samples/README`
`samples/arch/zlib.tar.gz`
 is scanned with parameters
`scancode --ignore */arch/* samples`
then the paths scanned as a result would be
`samples`
`samples/arch`
`samples/README`
As you can see the `arch` directory's contents were ignored, but the parent directory i.e `samples` was still scanned for rest of its contents.

**Comment by pombredanne** [comment]
@kalagp I am closing this ticket unless you have an objection: please reopen.
On the initial issue that was to merge "Multiple repos in one html-app file" this is unlikely to happen in scancode proper because the html-app is going to be deprecated in favor of the AboutCode Manager at https://github.com/nexB/aboutcode-manager which has many more visualization capabilities that we woucl ever cram in a single page static application. I have also entered a ticket there https://github.com/nexB/aboutcode-manager/issues/180 to add support for merging several tickets.
