### ISSUE TITLE
Add actual license texts and captured notices to SPDX output

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#588]
Non-SPDX licenses are represented as `LicenseRef-<scancode license key>` in the SPDX output.
The actual corresponding text should be included in the results using typically these tags:
```
LicenseID:
LicenseName:
ExtractedText:
```
etc

The actual extracted text should be included too and is collected as part of #260

**Comment by pombredanne** [comment]
@sschuberth in order to close in on 2.0, and also for #504 my plan for now would be to add a link to the scancode license and work out the proper solution immediately post 2.0? would this be OK as temp approach?

**Comment by sschuberth** [comment]
Would you have an example of how exactly such a link would look like? Like, would it be easy to retrieve the license text from the link in a post-processing step on our side? In any case, I guess that's OK as a temporary solution.

**Comment by pombredanne** [comment]
@sschuberth This is merged in develop. 
For now this is the "matched_text" if --license-text was used, otherwise this is a url to the license in the scancode repo (as a text is mandatory in SPDX)

#504 is still open to include the proper full text post 2.0
