### ISSUE TITLE
Consider adding licenses from http://www.clipol.org/licences.json

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#589]
http://www.clipol.org/ and http://www.clipol.org/licences.json contains licenses. We need to check if we have them all and if not add the missing ones.

**Comment by susg** [comment]
Hi, I would like to work on this issue.

**Comment by pombredanne** [comment]
@susg Thanks, excellent choice! So first thing is to fetch all the license texts and create tests to check how they are detected today. Then based on that, there will be a need to eventually add new licenses and or new license detection rules. Check the wiki for details on how this is done.

**Comment by susg** [comment]
Can you tell me how to create a test. I could only find in the wiki how to add a new rule and even the [pull request 258](https://github.com/nexB/scancode-toolkit/pull/258/commits/9e37150e7950ffa761c7a7c232142f6ddc78180b) it only shows how to add new rule to detect license.

**Comment by pombredanne** [comment]
@susg you can see for instance the pairs of (file under test and .yml expectation) in this: 
https://github.com/nexB/scancode-toolkit/pull/810/files#diff-2b390ea0fd80e716a5e3664b98d7cfaa

**Comment by abhirooptalasila** [comment]
Hey. Is this issue still open?

**Comment by pombredanne** [comment]
@abhirooptalasila yes it is.

**Comment by pombredanne** [comment]
The site went dark but there is code at https://github.com/kmewhort/clip ... not sure this is worth looking into. Closing
