### ISSUE TITLE
import errors because python include path not set correctly

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#592]
it appears that some of the extensions on my system are not found by scancode (I am playing around a bit and want to test with some extension).

By default:

>>> import sys
>>> sys.path
['', '/usr/lib/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gst-0.10', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']

In scancode:

['/home/armijn/git/scancode-toolkit/bin', '/home/armijn/git/scancode-toolkit/lib/python27.zip', '/home/armijn/git/scancode-toolkit/lib64/python2.7', '/home/armijn/git/scancode-toolkit/lib64/python2.7/plat-linux2', '/home/armijn/git/scancode-toolkit/lib64/python2.7/lib-tk', '/home/armijn/git/scancode-toolkit/lib64/python2.7/lib-old', '/home/armijn/git/scancode-toolkit/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7', '/usr/lib/python2.7', '/usr/lib64/python2.7/lib-tk', '/home/armijn/git/scancode-toolkit/lib/python2.7/site-packages', '/home/armijn/git/scancode-toolkit/src']

The directories /usr/lib64/python2.7/site-packages and some others seem to be missing. I am not sure if this is on purpose or not.

**Comment by majurg** [comment]
This is on purpose. `scancode-toolkit` creates and isolate virtualenv when you run the command `source configure`. 

Your system extensions are not touched, and if you want access to the same libs inside of scancode, simply `pip install` them inside the `scancode-toolkit` virtualenv.

**Comment by armijnhemel** [comment]
I see. My inner former Unix-sysadmin is screaming. Not everything here in the future is good. Closing.

**Comment by pombredanne** [comment]
@armijnhemel 
> My inner former Unix-sysadmin is screaming. 

How well... a virtualenv is not much different from a poor man's *nix, is it? ;)

Now by default, we ignore system installed packages entirely as they may otherwise conflict with ours.
I guess we could add a configure option to avoid that, but more practically once you can full install ScanCode from pypi with #24 this would become a non-event for your use case .
