### ISSUE TITLE
please include option to include full path in the JSON output

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#593]
I am running the following command:

    $ ./scancode /tmp/tmpdTWS0C/bzip2-1.0.1/randtable.c

In the output I see:

    "path":"bzip2-1.0.1/randtable.c"

and part of the path is gone. I understand that this is the default in scancode:

    " The default is to always include the last directory
       segment of the scanned path such that all paths
       have a common root directory."

While I understand its motivation it is awkward for me, as I am doing correlations with output from other tools. My bookkeeping would be a lot less complicated if there could be an option like --full-path that would give me the full path that was scanned (inverse of --strip-root).

**Comment by armijnhemel** [comment]
Created a patch, see #594

**Comment by pombredanne** [comment]
Thanks. This makes sense!

**Comment by pombredanne** [comment]
This is merged in develop. Thanks!
