### ISSUE TITLE
The Files row highlighted when moving up and down with the arrows is faint in the browser

### ISSUE THREAD

**Issue by harris1nj** [nexB/scancode-toolkit#60]
The row highlighted, which is seven rows below the dark highlighted row, is very faint. I tried this out in Chrome, Firefox, and Internet Explorer and got the same results. Scancode is an impressive tool otherwise.

![noname](https://cloud.githubusercontent.com/assets/6350715/9364538/d5443428-467a-11e5-9934-045326dd0a29.png)

**Comment by pombr** [comment]
@harris1nj Thanks for the bug report! What would be better colors?

@jdaguil what do you think could be done ?

**Comment by jdaguil** [comment]
@harris1nj @pombr Thanks for reporting. I will try to change the hover color to a less subtle color.

**Comment by harris1nj** [comment]
No color in particular, just something you can see better.

**Comment by jdaguil** [comment]
@harris1nj does this color work better?
