### ISSUE TITLE
Lock timeout....

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#603]
```
 File "/home/scancode/scancode-toolkit/src/licensedcode/index.py", line 135, in get_index
    _LICENSES_INDEX = get_or_build_index_from_cache()
  File "/home/scancode/scancode-toolkit/src/licensedcode/cache.py", line 83, in get_or_build_index_from_cache
    with yg.lockfile.FileLock(index_lock_file, timeout=LICENSE_INDEX_LOCK_TIMEOUT):
  File "/home/scancode/scancode-toolkit/local/lib/python2.7/site-packages/yg/lockfile/__init__.py", line 43, in __enter__
    self.acquire()
  File "/home/scancode/scancode-toolkit/local/lib/python2.7/site-packages/yg/lockfile/__init__.py", line 99, in acquire
    raise FileLockTimeout()
yg.lockfile.FileLockTimeout
```

This came after this commit https://github.com/nexB/scancode-toolkit/commit/9be63735625d19cdc2486a654b701217144a3a49

It it happens with this setup at https://github.com/nexB/scancode-toolkit/tree/0cd685915b9cf3b13864ba8a172d11d9b68cdfb1

* 144 cores Intel, 256GB, 16T SSD running Debian 64
* `scancode -clp --verbose --license-text -f spdx-tv -n 4 --strip-root pathtoscan/ spdxfile`
* ... spawned in 40 parellel runs, with a loop to scan a whole Debian pool.

It ran OK with 16685bd94a7dd091f53ccfae8ec6f7d30f8c15bc

**Comment by pombredanne** [comment]
This is likely introduced weirdly enough by https://github.com/zopefoundation/zc.lockfile/pull/8

The main diffs are:
 - yg.lockfile https://github.com/yougov/yg.lockfile/compare/2.1.1...2.2.2
 - zc.lockfile https://github.com/zopefoundation/zc.lockfile/compare/1.1.0...1.2.1

**Comment by pombredanne** [comment]
@jaraco @jimfulton I am pinging you there for reference. 

You may have an idea why this could timeout at times.

This is a license scan for a full Debian packages pool. Overall since the debian pool is about 24K packages, this will run about 24,000 x 4 = 96,000 processes total, ~160 concurrent at anytime, e.g acquiring and releasing 96K lock file locks over ~ 11 hours.

The yg.lockfile timeout is 180s. The typical time needed with a lock is a couple secs for each process. This is using multiprocessing intensively across multiple // sessions. 

I am under the impression that in some cases the lock may not be closed/released correctly, hence why this times out?

**Comment by pombredanne** [comment]
also this is Python 2.7.9 64bits Intel, on debian 8.

**Comment by pombredanne** [comment]
So as a stopgap, I will see how we can bypass the need for locking in many cases. @sschuberth do you work from a clone and update that? or do you use a fresh clone when you run massive scans on your side?

**Comment by sschuberth** [comment]
@pombredanne Are you referring to the software we scan, or how we update ScanCode itself? Fo rthe software to scan we do fresh clones. For ScanCode itself, we just fetch into an existing clone.

**Comment by pombredanne** [comment]
@sschuberth thanks. That was for the software you scan.

**Comment by pombredanne** [comment]
so with dc2ee02b77c74b381b1f6fc15e66b682b4b6f6de in #604 we now only ever do a single cache check for a given checkout. This will make the issue go away here, but there is still something fishy about this lockfile problem IMHO.

**Comment by pombredanne** [comment]
e..g this is only a workaround

**Comment by jaraco** [comment]
> The yg.lockfile timeout is 180s.

By my reading, the [default timeout is 10s](https://github.com/yougov/yg.lockfile/blob/2.2.1/yg/lockfile/__init__.py#L30). Where do you see 180s? Do you mean you're setting the timeout to 180s?

The only meaningful change to yg.lockfile between 2.1.1 and 2.2.1 is [in this file](https://github.com/yougov/yg.lockfile/commit/c57b5cb29c4fc49dcb697aa4657304b9f93c7e9f#diff-c47a771e30373249f82ca2fbc88971d2).

For what it's worth, here's [the diff of this package at the commits referenced above](https://github.com/nexB/scancode-toolkit/compare/16685bd...9be6373).

Are you running this on Python 3.4+ or something earlier? If Python 3.3 or earlier, the exception trapped in `suppress_file_not_found` is more broad, so that may be related.

I guess the first thing I would do is test with new/old versions of yg.lockfile and zc.lockfile to determine which package is implicated in the behavior change.

**Comment by pombredanne** [comment]
@jaraco Thanks ++ for chiming in!

I am setting the timeout to 180s here https://github.com/nexB/scancode-toolkit/blob/0cd685915b9cf3b13864ba8a172d11d9b68cdfb1/src/licensedcode/cache.py#L71

And this happens running Python 2.7.9 on Debian 8.

> I guess the first thing I would do is test with new/old versions of yg.lockfile and zc.lockfile to determine which package is implicated in the behavior change.

We can try that... The thing is that it only happens at a fairly large scale and semi-randomly and each test run is for now ~11hours and a few mega-watts ;)

**Comment by jaraco** [comment]
> ~11hours and a few mega-watts

At least you have to try pretty hard to instigate the issue.

I re-read yougov/yg.lockfile#2 and it does seem to validate the reference to the aforementioned change in 2.2.1.

**Comment by pombredanne** [comment]
The latest code now uses a SCANCODE_DEV_MODE tag file rather than an environment variable.
