### ISSUE TITLE
Dir: Copyright Summary irregular count

### ISSUE THREAD

**Issue by kalagp** [nexB/scancode-toolkit#607]
Hello,

Normally when I select any folder on the repository, the copyright summary tab gives the '#files' that doesn't have the copyright information. But looks like its counting the sub folders while giving the count.

For Example:

Lets say 'file1' doesn't have the copyright info and its placed in the following path, now the copyright tab shows '4' files that doesn't have the info. But in general sense there is only one file that doesn't have the info.

Dir1/Dir2/Dir3/file1       

![test](https://cloud.githubusercontent.com/assets/25748390/25456989/a878c8ce-2aa2-11e7-8ec2-5f87bb646075.JPG)

**Comment by pombredanne** [comment]
Thanks for the report. This smells like a bug indeed where the count reported is the number of "resources" as in either file or directories but is displayed as a file count. What would you prefer? see only files counted? or renamed "Total files Scanned" to something like "Total files and directories Scanned" ?

**Comment by kalagp** [comment]
@pombredanne 

I prefer to update the No Copyright Found: (# ) , this should give you the accurate files that were there in any folder.

**Comment by pombredanne** [comment]
Hum, I am willing to fix this, but on the other hand @jdaguil upcoming should support this and much more: https://github.com/nexB/aboutcode-manager
@jdaguil what's your take on this?

**Comment by pombredanne** [comment]
@jdaguil ping?

**Comment by jdaguil** [comment]
I agree this is a bug. Definitely for license and copyright there is no reason to count directories as missing license or copyright respectively because we only expect files to have license or copyright. This is still the case in AboutCode Manager. I can add an issue to fix it for AboutCode Manager.

**Comment by pombredanne** [comment]
@jdaguil What if we were to report the count of files and dir separately? There are some side effects in ScanCode as some plugin may filter out some files that were scanned but have no findings so I would like to report these as the number of scanned files and dirs (which may not be the number of reported files and dirs). Note that there will be eventually mechanically summarized license and origin data reported at a directory level

**Comment by pombredanne** [comment]
The latest code post #885 merge now has correct counts... these could then be used to fix this.

**Comment by majurg** [comment]
@pombredanne This issue is fixed in AboutCode-Manager. See: https://github.com/nexB/aboutcode-manager/issues/183

**Comment by pombredanne** [comment]
OK, so closing.
