### ISSUE TITLE
Copyright notice should be detected as `other-permissive`

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#609]
[`Xin Calendar 2`](http://www.yxscripts.com/tools/xc2/index.html) and [`Chained Selects`](http://www.yxscripts.com/tools/cs/index.html) (as well as other scripts by Xin Yang) contain the notice "This script is free as long as the copyright notice remains intact.". ScanCode should detect this as `other-permissive`.

**Comment by pombredanne** [comment]
This has been fixed and merged in develop. Thanks!
