### ISSUE TITLE
Bogus ANSI sequence present if --verbose output is redirected to file

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#614]
Using ScanCode version 2.0.0.rc2.post258.8559b54c and scanning its own `bin` directory like

    bin/scancode --verbose bin > a.txt 2>&1

results in `a.txt` to contain

    Scanning files for: licenses, copyrights, packages with 1 process(es)...
    Building license detection index...Done.
    Scanning files...
    Scanned: python2.7
    Scanned: easy_install
    Scanned: easy_install-2.7
    Scanned: pip
    Scanned: pip2
    Scanned: pip2.7
    Scanned: wheel
    Scanned: activate
    Scanned: activate.fish
    Scanned: activate_this.py
    Scanned: activate.csh
    Scanned: python-config
    Scanned: calc-prorate
    Scanned: pygmentize
    Scanned: latin2ascii.py
    Scanned: pdf2txt.py
    Scanned: dumppdf.py
    Scanned: chardetect
    Scanned: rdf2dot
    Scanned: csv2rdf
    Scanned: rdfpipe
    Scanned: rdfs2dot
    Scanned: rdfgraphisomorphism
    Scanned: scancode
    Scanned: extractcode
    Scanned: pytest
    Scanned: py.test
    Scanned: bumpversion
    ^[[?25h
    Scanning done.
    Scan statistics: 28 files scanned in 35s.
    Scan options:    licenses, copyrights, packages with 1 process(es).
    Scanning speed:  0.83 files per sec.
    Scanning time:   33s.
    Indexing time:   2s.
    Saving results.

Note the bonus `^[[?25h` ANSI sequence. While only a cosmetic issue, I'd not expect that sequence to be present.

**Comment by pombredanne** [comment]
This has been fixed and merged in develop. Thanks!
