### ISSUE TITLE
Document the structure of ScanCode's JSON output

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#617]
There should be documentation for the ScanCode structure in the JSON output. Sometimes it's difficult to know what the data types are for the output.

For example, when the value is `null` or an empty array:
```
"date": null,
"mime_type": null,
"scan_errors": [],
"copyrights": [
        {
          "statements": [
            "Copyright (c) 2002-2004 Dmitriy Anisimkov"
          ],
          "holders": [
            "Dmitriy Anisimkov"
          ],
          "authors": [],
          "start_line": 4,
          "end_line": 4
        }
```

**Comment by pombredanne** [comment]
I generated some JSON schema from schematics for ScanCode... I will commit this later though jet me paste these





[json-schemas.zip](https://github.com/nexB/scancode-toolkit/files/1029754/json-schemas.zip)






 here.

**Comment by pombredanne** [comment]
https://github.com/nexB/scancode-toolkit/tree/develop/etc/scripts/sch2js now contains a script and generated JSON schema for the Package models.
