### ISSUE TITLE
Scanning malformed POMs makes ScanCode show scan errors

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#621]
If `--package` scanning is enabled and malformed POMs are scanned, like deliberately invalid test files in the [byte-buddy-maven-plugin](https://github.com/raphw/byte-buddy/tree/master/byte-buddy-maven-plugin), I get

    Some files failed to scan properly. See scan for details:
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/suffix.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/test.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/live.allowed.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/empty.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/illegal.apply.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/entry.illegal.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/entry.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/entry.illegal.transform.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/illegal.pom.xml
      byte-buddy-maven-plugin/src/test/resources/net/bytebuddy/test/live.pom.xml

My understanding is that with `--package`, in *addition* to treating a POM file as a generic file and scanning its content like any other file, ScanCode *also* tries to interpret the structure of the file to gather additional / optional meta data. If only the latter fails for whatever reason, my feeling is that we should not report this as a failure like we currently do. After all, the file was properly scanned (in the sense that it could be accessed, read, and was not too big to be scanned in time), and only getting the additional / optional meta-data failed. I'm not sure how to report this to the user, if at all, but I think it should be treated differently than more general errors like those causes I've mentioned before.

**Comment by pombredanne** [comment]
@sschuberth this make sense. It is difficult to distinguish a bona fide manifest (e.g. a wel formed pom) from a test one. A couple ways:
1. detect that this is a test file somehow and ignore errors. Eventually do not even scan in this case
2. do not make manifest parsing errors a "failure"  but a warning instead. 
3. silence manifest parsing errors entirely, unless other scans failed too

**Comment by sschuberth** [comment]
I agree with your list of potential solutions. Some thoughts:

I believe 1. is not feasible to implement. Of course you could do something like checking whether the path to the scanned file contains "test" and use that as an indicator to ignore a failed package scan. But even with more sophisticated checks you'll have false positives, and the process of when errors get ignored is untransparent to the user. Proposal 3. basically has the same issue. Thus I'd vote for 2., eventually combined with a command line option to ignore / suppress warnings.

**Comment by sschuberth** [comment]
FYI, the JSON result shows the following error for all of these files:

> ERROR: packages: sequence item 0: expected string, NoneType found

**Comment by pombredanne** [comment]
Fixed in develop
