### ISSUE TITLE
tree view license summary update no longer works.

### ISSUE THREAD

**Issue by rickfoosusa** [nexB/scancode-toolkit#629]
In 1.6.0, selecting a file or directory updated the license summary.

This no longer works in 2.0.0rc2, or current tree.

Many more licenses are found in the current version, however it would be nice to be able to drill down as in the past.

**Comment by pombredanne** [comment]
@rickfoosusa Let dig in all this... Note that eventually there are several upcoming changes  happening in this area:
1. all output are being moved to plugins
2. the html-app may become deprecated and all the visualization (and review/editing) of scans will be handled by the new https://github.com/nexB/aboutcode-manager

**Comment by pombredanne** [comment]
@rickfoosusa The latest develop should be fixed. Thanks for catching this! Can you test the latest develop and tell me if this works for you?

**Comment by pombredanne** [comment]
@rickfoosusa this is has been fixed. This in 2.0.0rc3 I am closing

**Comment by rickfoosusa** [comment]
Thank you!
