### ISSUE TITLE
gpl-2.0 detected from non-license text.

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#632]
```
// 
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF 
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A 
// PARTICULAR PURPOSE. 
// 
```
The above notice is detected as under ```"key":"gpl-2.0","score":23.94,```

Although the score is not high to conclude the license, imo, scancode should not return any license match for the above text.

**Comment by chinyeungli** [comment]
See https://code.msdn.microsoft.com/How-to-use-WIF-to-def0de33/sourcecode?fileId=132720&pathId=1518241965


this is just  warranty disclaimer. The question is whether it gives any usage and redist right

**Comment by pombredanne** [comment]
@chinyeungli Thank you. I guess I might create a new license just for bare warranty disclaimers that do not look like they are providing any specific usage rights as this one (which has been mostly copied from a GPL, hence the match)

**Comment by pombredanne** [comment]
@chinyeungli I pushed a branch for this with 5efb274ba73834791adf9375cf301abac2d8715a . @mjherzog @DennisClark your opinion is welcomed

**Comment by pombredanne** [comment]
this has been merged. Thanks!
