### ISSUE TITLE
Timeout when scanning boost's vector200.h

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#641]
Running ScanCode 2.0.0.rc2.post331.8a314d95 on Boost's [vector200.hpp](https://raw.githubusercontent.com/boostorg/typeof/develop/include/boost/typeof/vector200.hpp) (which is 2.13 MiB in size) results in a timeout:

```
$ scancode ./libs/typeof/include/boost/typeof/vector200.hpp
Scanning files for: licenses, copyrights, packages with 1 process(es)...
Building license detection index...Done.
Scanning files...
[####################] 1
Scanning done.
Some files failed to scan properly. Use the --diag option for additional details:
 vector200.hpp
Scan statistics: 1 files scanned in 125s.
Scan options:    licenses, copyrights, packages with 1 process(es).
Scanning speed:  0.01 files per sec.
Scanning time:   120s.
Indexing time:   5s.
Saving results.
{"scancode_notice":"Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.","scancode_version":"2.0.0.rc2.post331.8a314d95","scancode_options":{"--copyright":true,"--license":true,"--package":true,"--license-score":0,"--ignore":[],"--format":"json"},"files_count":1,"files":[{"path":"typeof/vector200.hpp","scan_errors":["ERROR: Processing interrupted: timeout after 120 seconds."]}]}
```

I've tried this on multiple machines (from VMs to beefy bare metal ones) with up to 6 processes (I know, that does not make a difference if scanning a single file, just mentioning it for completeness) and the timeout increased to 600 s, but still no luck. Given how common of a library Boost is, I guess ScanCode should be able to handle such files. Granted, 2.13 MiB of code is a lot of text, but nothing that's impossible to process in a few minutes these days.

I haven't looked at how exactly ScanCode performs the pattern matching, but could it be that there is some room for improvement to do some cheap checks first, and only dig deeper if these yield some results? Or use some native code library for pattern matching, like something PCRE-v2-based like [Git recently did](https://public-inbox.org/git/20170408132506.5415-13-avarab@gmail.com/)?

**Comment by pombredanne** [comment]
@sschuberth The root cause is a combo of different problems:

- On the license side, each line contains the word mpl repeated several 100 times. Each of these result in a match to a bare `mpl` license (with a very low score). All of these are actually `mpl::int`
- One the copyrights side, this highlights another issue in the multistage detection which is first to isolate possible candidate lines that may contain copyrights. And any line with a two-digit number between 01 and 99 is considered as a possible year-like looking line and included in the copyright detection.

So yes, both of these could be optimized, but the fix is not about that. The fix is to avoid computing so many matches both on the license and copyright side

**Comment by pombredanne** [comment]
@sschuberth this latest commit fixes both the copyright and license detection issue: this should also fix a large number of potentially related copyright detection issues!
Thanks ++!

**Comment by sschuberth** [comment]
> this should also fix a large number of potentially related copyright detection issues!

Wow, that'd be great. This timeout issue with Boost actually was a quite arbitrary example, we see this happening a lot with other large text files (CSV, JSON, NMEA) which I'm not able to share, so I'll update and check whether we see these fixed, too. Thanks a lot again for the fast action!

**Comment by pombredanne** [comment]
@sschuberth yes, this will likely solve several related in data files that look like they may contain a lot of copyrights but do not after all.
