### ISSUE TITLE
Support grouping CLI options in CLI help

### ISSUE THREAD

**Issue by yashdsaraf** [nexB/scancode-toolkit#643]
Extension of #552 
See `pytest -h`

**Comment by yashdsaraf** [comment]
@pombredanne How should the groups look like? 
I mean would there be just two groups, `normal` options and `plugin` options? Or `normal` options would be divided even further? 

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pombredanne** [comment]
@yashdsaraf Good point and this needs some thinking indeed!
There are a couple considerations:
- some options are part of the "core": `--help`, `--verbose`, `--diag`, `--processes` etc.  and are best shown in a group, but not the first group. Inside this group there is a preferred order that we want, probably from most common to least common.
- most of the other options are about which scans to run (e.g. `--copyright`, `--license`, etc.). They should be in a group together at the top and if several options come from the same plugin (e.g. license detection), they should be grouped together and have an order that is set (`--license` comes before `--license-text` ... etc)
- the `--format` option should come after the "scans" top group and before the "core" , built-in options.
- we may need new option groups for plugins and options that control:
  -  "what to scan", e.g. that are executed before the a scan, but in terms of group position would not come before in the UI. 
  - "post scan" summarizations (we do not have yet any of these)

In recap something along these lines:
 - `scans` groups that comes at the top.
 - `--format` and related options
 - `pre-scan` group of options (for now only `--ignore`)
 - `post-scan` group of options (nothing yet for now)
 - `misc` options
 - `core` options 

And if we look at the current set of options and how these could be re-ordered an broken in groups... we may get something like this, more or less:


```
Options:
```
### `scans` group of options at the top
```
  -c, --copyright          Scan <input> for copyrights. [default]
  -l, --license            Scan <input> for licenses. [default]
  --license-score INTEGER  Do not return license matches with scores lower
                           than this score. A number between 0 and 100.
                           [default: 0]
  --license-text           Include the detected licenses matched text. Has no
                           effect unless --license is requested.
  -p, --package            Scan <input> for packages. [default]
  -e, --email              Scan <input> for emails.
  -u, --url                Scan <input> for urls.
  -i, --info               Include information such as size, type, etc.
```



### `format` and "output control"-related group of options. Plugins only contribute new formats and not new options in this group for now.
```
  -f, --format <style>     Set <output_file> format <style> to one of the
                           standard formats: json or json-pp or html or html-
                           app or spdx-tv or spdx-rdf or the path to a custom
                           template  [default: json]
  --only-findings          Only return files or directories with findings for
                           the requested scans. Files without findings are
                           omitted.
  --strip-root             Strip the root directory segment of all paths. The
                           default is to always include the last directory
                           segment of the scanned path such that all paths
                           have a common root directory. This cannot be
                           combined with `--full-root` option.
  --full-root              Report full, absolute paths. The default is to
                           always include the last directory segment of the
                           scanned path such that all paths have a common root
                           directory. This cannot be combined with the
                           `--strip-root` option.
  --verbose                Print verbose file-by-file progress messages.
  --quiet                  Do not print summary or progress messages.
```


### `pre-scan` and "input control"-related group of options
```
  --ignore <pattern>       Ignore files matching <pattern>.
```

### `post-scan` group of options
```
NONE YET
```


### miscellaneous, secondary options, possibly contributed by plugins.
```
  --reindex-licenses       Force a check and possible reindexing of the cached
                           license index.
```

### `core` built-in options at the bottom
```
  --diag                   Include additional diagnostic information such as
                           error messages or result details.
  -n, --processes INTEGER  Scan <input> using n parallel processes.  [default:
                           1]
  --timeout FLOAT          Stop scanning a file if scanning takes longer than
                           a timeout in seconds.  [default: 120]
  -h, --help               Show this message and exit.
  --examples               Show command examples and exit.
  --about                  Show information about ScanCode and licensing and
                           exit.
  --version                Show the version and exit.
```

**Comment by yashdsaraf** [comment]
@pombredanne Can new groups be added dynamically? i.e using plugins?

**Comment by pombredanne** [comment]
@yashdsaraf 
> Can new groups be added dynamically? i.e using plugins?

IMHO not yet for now. Eventually yes... but this is TBD when we get there. Start small and simple for now

**Comment by pombredanne** [comment]
This has all been merged in develop. Thanks!!
