### ISSUE TITLE
--package option should collect homepage URL from registry.npmjs.org for Node modules

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#645]
Many `package.json` files in NPM packages do not contain the homepage URL of the package. These could be collected by having ScanCode query [registry.npmjs.org](registry.npmjs.org) with the package name. 

@pombredanne Should querying [registry.npmjs.org](registry.npmjs.org) be done by ScanCode or is it better off as a stand-alone script or (when it's complete) a ScanCode plugin?

**Comment by pombredanne** [comment]
@JonoYang for scancode, I would be more in favor of a plain string operation to infer a download URL and not have a network dependencies. Later plugins that have such a network dep would be OK, but at least for now, I am pretty sure that you can come with a recipe to infer a download URL from an NPM name and version, could you?

**Comment by JonoYang** [comment]
The download URLs are within the `package.json` files fairly consistently. The problem is with the homepage URLs to the package. The homepage URLs to these packages could vary from a GitHub repo, a website, or it doesn't exist at all. An easy way would just have the homepage URL be npmjs.org/<package name>, but not all packages exist on the NPM repo.

**Comment by pombredanne** [comment]
So this would be a package homepage of sorts, that would be filled in the package page for a package such as https://www.npmjs.com/package/sqlite3 .... which is something that might be relatively universal, would it?

**Comment by pombredanne** [comment]
This is merged in develop and fixed with https://github.com/nexB/scancode-toolkit/commit/927273b159eb573610638600e94dcbb136e425ca but really only available in results since v2.9.4 and this commit https://github.com/nexB/scancode-toolkit/commit/eaa46a68fda091a5d91a68345d38b44ae2e21a37
