### ISSUE TITLE
RPM information is not collected

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#660]
I use ftp://ftp.ntua.gr/pub/linux/fedora/linux/updates/25/SRPMS/z/zookeeper-3.4.9-1.fc25.src.rpm as a sample:
the `scancode -p` only returns "type":"RPM", other fields are null.

However, there are many data which are not present and should: name, version, release, summary, description, distribution, vendor, license etc...

**Comment by pombredanne** [comment]
@chinyeungli Thanks... this is a bug! the code is there but somehow is not being called on RPMs alright
