### ISSUE TITLE
Issue with reporting certain file  (with space and parens in their name) in the html-app output

### ISSUE THREAD

**Issue by jarnugirdhar** [nexB/scancode-toolkit#666]
While scanning a directory, a particular file with name " parser (copy).js " is scanned (path shown in data.json) but not shown in Total Scanned files. (value = 0)

**Comment by pombredanne** [comment]
@jarnugirdhar this is in the html-app right?

**Comment by jarnugirdhar** [comment]
@pombredanne Yes.

**Comment by pombredanne** [comment]
Eventually the html-app will be deprecated and https://github.com/nexB/aboutcode-manager should be used for visualization of scans instead
I would like to close this. @jdaguil I assume this is not an issue that exists in AboutCode manager, correct?

**Comment by pombredanne** [comment]
@jarnugirdhar the html-app is deprecated ... Please check out the shiny new GUI  https://github.com/nexB/scancode-workbench instead... Much better!
@majurg I assume this is not an issue there, correct?

**Comment by majurg** [comment]
@pombredanne scancode-workbench displays this information correctly, yes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pombredanne** [comment]
Thank you! closing then
