### ISSUE TITLE
Do not use gpl and lgpl bare license keys

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#668]
Instead use `lgpl-2.0-plus` for bare LGPL and `gpl-1.0-plus` for bare GPL. The rationale is that these licenses state that no version means any version can be used and lgpl-2.0-plus and gpl-1.0-plus are the earliest "or later" versions. This makes this simpler to sync up with external license list for #41 and #481 

There are a few more candidates such as a bare `mpl` and a bare `gfdl`. There is no such thing as choosing any version of the MPL, but all versions are "or later" by definition and therefore picking up the MPL 1.0 should be OK. For the GFDL the terms needs to be reviewed but are likely the same as the other FSF GNU licenses.

**Comment by pombredanne** [comment]
This is fixed and merged.

**Comment by jonassmedegaard** [comment]
I am not convinced that this simplification is correct:

SPDX defines in their ontology that license tag implies any version.  Consequently statements expressed using SPDX can correctly be simplified like this.

I believe, however, that statements expressed in _other_ ways originally - including statements _referenced_ using SPDX by someone else than the copyright holder - can *not* be simplified like this.

Example of a simplification that I believe is wrong:
  * tests/ScanCode/src/licensedcode/data/rules/pypi_gnu_free_documentation_license.RULE

**Comment by jonassmedegaard** [comment]
I therefore believe that this simplification can be done *only* when a) parsed from SPDX format, *and* b) it is certain that the parsed SPDX statement originates without intermediary reasoning from the copyright holder.
