### ISSUE TITLE
copyright: 'Author's missed

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#669]
Copyright statements that do not contain the word 'copyright' such as

```
/*
 * iplink_vlan.c        VLAN device support
 *
 *              This program is free software; you can redistribute it and/or
 *              modify it under the terms of the GNU General Public License
 *              as published by the Free Software Foundation; either version
 *              2 of the License, or (at your option) any later version.
 *
 * Authors:     Patrick McHardy <kaber@trash.net>
 */
```

(from iproute2)

are missed by ScanCode.

**Comment by pombredanne** [comment]
@armijnhemel which branch or release are you using? I added a test and it works in develop and should be the same for master

**Comment by pombredanne** [comment]
@armijnhemel my bad... this is detected as as an author and these authors are NOT reported!!!

**Comment by pombredanne** [comment]
let me fix quick

**Comment by armijnhemel** [comment]
Yeah, this is on 'develop'.

**Comment by pombredanne** [comment]
@armijnhemel This should be fixed in develop now. Thank++ for the report!

**Comment by armijnhemel** [comment]
"authors": [
            "Authors Patrick McHardy <kaber@trash.net>"
          ],

Should 'Authors' be there or is it directly copied from the source code (and if so, why is the : missing? )

**Comment by pombredanne** [comment]
> Should 'Authors' be there or is it directly copied from the source code (and if so, why is the : missing? )

Authors is taken from the code, but eventually this should go away. And this would make the missing colon moot.

**Comment by pombredanne** [comment]
@armijnhemel this latest commit cleans junk prefixes from the returned authors.

**Comment by pombredanne** [comment]
The Authors part has been cleaned alright and had been fixed a while back.
I added a new test though. Close if this works for you!

**Comment by pombredanne** [comment]
I am doing some cleanup and review as a prep for the 3.0 release... and since this is fixed in develop, I am closing this!
