### ISSUE TITLE
pygments version does not resolve correctly 

### ISSUE THREAD

**Issue by pkajaba** [nexB/scancode-toolkit#670]
Hello, after recent version bump scancode does not work.
```
Could not find a version that satisfies the requirement pygments<3.0.0,>=2.2.0 (from scancode-toolkit==2.1.0->-r /tmp/scancode-toolkit/etc/conf/base.txt (line 10)) (from versions: 2.0.1)
No matching distribution found for pygments<3.0.0,>=2.2.0 (from scancode-toolkit==2.1.0->-r /tmp/scancode-toolkit/etc/conf/base.txt (line 10))
```

**Comment by pombredanne** [comment]
Ah! my bad in bumping the versions!!!! I blame `bumpversion` for this!
Thanks++ for catching this

**Comment by pkajaba** [comment]
You are welcome :+1: I created PR, which reverts it back to working version, so you can take a look and merge if it's OK.

**Comment by pombredanne** [comment]
@pkajaba Thanks++ there were actually a few more damages created by my run of bumpversion. Great catch and kudos for tracking the latest develop! I committed a fix before I saw your PR though!

**Comment by pombredanne** [comment]
Note to self @pombredanne : NEVER COMMIT direct to `develop`. Use and hang on to the branches, Luke! they are there to avoid falling. ;)

**Comment by pombredanne** [comment]
Fixed in develop.
