### ISSUE TITLE
improvement e-mail/URL: filter bogus entries

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#672]
In the Linux kernel there is a document kernel/Documentation/SubmittingPatches which has a few mail addresses. ScanCode extracts those correctly, but they are basically bogus:

        {
          "email": "random@developer.example.org",
          "start_line": 337,
          "end_line": 337
        },
        {
          "email": "lucky@maintainer.example.org",
          "start_line": 359,
          "end_line": 359
        }

It would be nice if it would be possible to keep some blacklist with patterns, to declutter results.

**Comment by pombredanne** [comment]
@armijnhemel there is such a list in there: https://github.com/nexB/scancode-toolkit/blob/ff7752576e5d220cfdb00a1234bbc8cbef68752d/src/cluecode/finder_data.py .... we should also filter when `example.org` is used with subdomains

**Comment by pombredanne** [comment]
The latest commit above (in a branch) has the fix for the specific issue you raised.

**Comment by armijnhemel** [comment]
Actually, test.com is a valid domain of a company :-)

https://tools.ietf.org/html/rfc2606#page-2

and

https://tools.ietf.org/html/rfc6761

are relevant (start with the latter).

**Comment by pombredanne** [comment]
@armijnhemel Thanks! test.com is a valid company with what seems an invalid domain per the RFCs....

**Comment by armijnhemel** [comment]
No, not at all. The top level domain .test is reserved, but whenever there is 'test' in a domain name it is fine

**Comment by pombredanne** [comment]
So you reckon I should return test.com domains and emails? they are unfortunately often used as jusnk examples.

**Comment by armijnhemel** [comment]
If you want to follow the RFCs it would be the correct approach although I agree with you that they are often used as junk examples.

I would also recommend filtering out localhost and 127.0.0.1 and the IPv6 equivalent.

**Comment by pombredanne** [comment]
@armijnhemel I added some extra tests for sanity ... The private IPs are detected here:
https://github.com/nexB/scancode-toolkit/blob/3a3fd333742e6b798f71caf2401e9515fa7373f6/src/cluecode/finder.py#L412 and any localhost-like is caught here: https://github.com/nexB/scancode-toolkit/blob/3a3fd333742e6b798f71caf2401e9515fa7373f6/src/cluecode/finder.py#L455 (where the logic is simply to detect if there is a `.` or not in the a non-IP host name which works very well in practice for localhost and other local, private domain names)

**Comment by pombredanne** [comment]
Thanks again... Merged #675 and closing now.
