### ISSUE TITLE
Add CSV format plugin

### ISSUE THREAD

**Issue by yashdsaraf** [nexB/scancode-toolkit#674]
Add /etc/scripts/json2csv.py as a plugin to save ABCD output as CSV

**Comment by yashdsaraf** [comment]
@pombredanne the `/etc/scripts/json2csv.py` checks whether the input is in `json` or `html-app` format. Since all the plugin formats will be receiving the `json` data directly, should I remove the code specific to `html-app` from the plugin?

**Comment by pombredanne** [comment]
@yashdsaraf yes you can. The old code in /etc/scripts/json2csv.py can stay there if needed anyway

**Comment by yashdsaraf** [comment]
@pombredanne I've noticed `prefix_path` in json2csv.py, which tells it whether or not to prefix the paths supplied with **/code**. I'm not able to understand the significane of this, none of the other plugins do this either.

**Comment by pombredanne** [comment]
Just ignore this in porting to and creating a CSV plugin. That's some optional odd customization that's no longer need I am sure.

**Comment by yashdsaraf** [comment]
@pombredanne Can we close this?

**Comment by pombredanne** [comment]
@yashdsaraf when this is merged and only then ;P

**Comment by pombredanne** [comment]
This has been merged
