### ISSUE TITLE
Add license rule for bsd-simplified

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#678]
```
/* Copyright 2014, Kenneth MacKay. Licensed under the BSD 2-clause license. */
```

No license is currently detected for the above statement.
It should return `bsd-simplified`

**Comment by pombredanne** [comment]
@chinyeungli Thanks!

**Comment by pombredanne** [comment]
Fixed and merged in develop. Thanks again for the report!
