### ISSUE TITLE
Add Summary Feature

### ISSUE THREAD

**Issue by ottokruse-sd** [nexB/scancode-toolkit#68]
In many cases the html file has hundreds and sometimes thousands of line items.  It will be convenient to have the tool provide a summary list of licenses in a particular package.  The user can then examined the detailed html file only if needed.

**Comment by pombredanne** [comment]
@ottokruse-sd this would be great indeed.
One thing that is a tad difficult when doing summaries is decide at which level to summarize....
- a simple approach is to provide a top level summary for the whole scan, which is straightforward and concise in most cases for licenses, but can be a tad long if you were to do the same on bare copyrights (and this would be better on to do on copyright holders only, ignoring years and such).
- a more involved approach would to provide smarter summaries at various level of the scanned code tree hierarchy.
 - a natural summary point is when we detect a package such as an RPM, a tarball, JAR, NPM, etc (which is a new feature under development in the develop branch)
 - or find or infer summary point in the tree based on actual scan results. For instance if all files in a directory share the same license and copyright holders, that directory becomes a good summary point.

So what would be your take on this?

**Comment by ottokruse-sd** [comment]
I do not think we need a summary of copyrights, what we need is a top level summary of license contained in the package scanned.

OTTO KRUSE
Engineering Program Manager
ARRIS

o: +1 858-404-2429
c: +1 858-342-3623
e: Otto.Kruse@arris.com<mailto:Otto.Kruse@arris.com>  <-- Note Change

This electronic transmission (and any attached document) is for the sole use of the individual or entity to whom it is addressed.  It is confidential and may be attorney-client privileged.  In any event the Sender reserves, to the fullest extent, any "legal advice privilege".  Any further distribution or copying of this message is strictly prohibited.  If you received this message in error, please notify the Sender immediately and destroy the attached message (and all attached documents).

**Comment by pombredanne** [comment]
good, that is the easier one for a start...

**Comment by pombredanne** [comment]
@jdaguil I think you made some progress on this, correct?

**Comment by jdaguil** [comment]
@pombredanne yes, I didn't see this ticket progress has been referenced in #114

**Comment by jdaguil** [comment]
@ottokruse-sd @pombredanne this has been implemented in #114 and is available in the latest release
