### ISSUE TITLE
Incorrect GPL detection

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#683]
```
This file is licensed under the terms of your license agreement(s) with ABC convering this file. Redistribution, except as permitted by the terms of your license agreement(s) with ABC, is strictly prohibited.
```
ScanCode detects the above statement as `gpl-2.0` with `score: 75`. Although the score is not 100, I think it's still a bug to return such a high score

**Comment by pombredanne** [comment]
Fixed and merged in develop. Thanks again for the report!
