### ISSUE TITLE
Dual BSD-GPL not detected

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#684]
```
/*-
--
  | * Copyright (c) 2002-2005 Sam Leffler, Errno Consulting
  | * All rights reserved.
  | *
  | * Redistribution and use in source and binary forms, with or without
  | * modification, are permitted provided that the following conditions
  | * are met:
  | * 1. Redistributions of source code must retain the above copyright
  | *    notice, this list of conditions and the following disclaimer,
  | *    without modification.
  | * 2. Redistributions in binary form must reproduce at minimum a disclaimer
  | *    similar to the "NO WARRANTY" disclaimer below ("Disclaimer") and any
  | *    redistribution must be conditioned upon including a substantially
  | *    similar Disclaimer requirement for further binary redistribution.
  | * 3. Neither the names of the above-listed copyright holders nor the names
  | *    of any contributors may be used to endorse or promote products derived
  | *    from this software without specific prior written permission.
  | *
  | * Alternatively, this software may be distributed under the terms of the
  | * GNU General Public License ("GPL") version 2 as published by the Free
  | * Software Foundation.
  | *
  | * NO WARRANTY
  | * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  | * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  | * LIMITED TO, THE IMPLIED WARRANTIES OF NONINFRINGEMENT, MERCHANTIBILITY
  | * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
  | * THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR SPECIAL, EXEMPLARY,
  | * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  | * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  | * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
  | * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  | * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
  | * THE POSSIBILITY OF SUCH DAMAGES.
  | *
  | * $Id$
  | */
```

Scancode detects the above license as under `gpl-2.0` and `intel-bsd-special` with both score = 100.

In my opinion, shouldn't the above text be Dual BSD-GPL ?

**Comment by pombredanne** [comment]
Hum... The detected rule is this one https://github.com/nexB/scancode-toolkit/blob/23d835ff2ad0587eedef4f9eebef87ee1ff0fe48/src/licensedcode/data/rules/gpl-2.0_or_intel-bsd-special.RULE 

But if I remove the middle lines about the GPL alternative e.g. these lines :
```
  | * Alternatively, this software may be distributed under the terms of the
  | * GNU General Public License ("GPL") version 2 as published by the Free
  | * Software Foundation.
```
... then I get this detected exactly: https://github.com/nexB/scancode-toolkit/blob/23d835ff2ad0587eedef4f9eebef87ee1ff0fe48/src/licensedcode/data/licenses/intel-bsd.LICENSE

And there is also this otherr license https://github.com/nexB/scancode-toolkit/blob/23d835ff2ad0587eedef4f9eebef87ee1ff0fe48/src/licensedcode/data/licenses/intel-bsd-special.LICENSE which is very similar and also contains the GPL alternative.

So in a nutshell: there is something incorrect in the detection. This is definitely not a standard BSD but one of the Intel variants either `intel-bsd-special.LICENSE` or the `intel-bsd.LICENSE` ... There is definitely a GPL alternative .... but what is returned here (and the licenses for the detected rule) may not be entirely right.


The diffs show this (ignoring punctuation and formatting) where `test` is your test file

```
$ diff  intel-bsd.LICENSE test 
15a16,19
> Alternatively, this software may be distributed under the terms of the
> GNU General Public License ("GPL") version 2 as published by the Free
> Software Foundation.
> 
```
... so your test file is really the same as intel-bsd.LICENSE plus an extra GPL alternative

```
$ diff  intel-bsd-special.LICENSE test 
8c8
<    substantially similar to the "NO WARRANTY" disclaimer below
---
>    similar to the "NO WARRANTY" disclaimer below
23c23
< LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTIBILITY
---
> LIMITED TO, THE IMPLIED WARRANTIES OF NONINFRINGEMENT, MERCHANTIBILITY

```
... so your test file is really the same as intel-bsd-special.LICENSE using the intel-bsd.LICENSE variation for the BSD portion


And this shows that the BSD portions of intel-bsd.LICENSE and intel-bsd-special.LICENSE are essentially the same with the addition of two words: `substantially` and `NONINFRINGEMENT`

```
$ diff  intel-bsd.LICENSE intel-bsd-special.LICENSE 
8c8
<    similar to the "NO WARRANTY" disclaimer below
---
>    substantially similar to the "NO WARRANTY" disclaimer below
15a16,19
> Alternatively, this software may be distributed under the terms of the
> GNU General Public License ("GPL") version 2 as published by the Free
> Software Foundation.
> 
19c23
< LIMITED TO, THE IMPLIED WARRANTIES OF NONINFRINGEMENT, MERCHANTIBILITY
---
> LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTIBILITY
```


I will come up with a proper way to reconcile this. Possibly treating the intel-bsd-special.LICENSE as a composite license. In all cases this will not be a standard BSD.

**Comment by pombredanne** [comment]
Fixed and merged in develop. The intel-bsdd-special is no longer detected in the short term until #522 is implemented... Instead you have an intel-bsd and a gpl choice detected.
Thanks again for the report!
