### ISSUE TITLE
How to see actual files with the shown licenses

### ISSUE THREAD

**Issue by chinchang** [nexB/scancode-toolkit#693]
After I have generated report, I see this:

![screenshot 2017-07-19 11 00 09](https://user-images.githubusercontent.com/379918/28352029-91079baa-6c71-11e7-8b3a-675b24b48f41.png)

I see I have 3 GPL licenses files. But how do I know which exact files? Nothing happens on clicking the numbers.

**Comment by pombredanne** [comment]
@chinchang if you go to the Clues tab, you can then search for GPL to see which files have this. Or you can sort by the "What" column too to see where licenses are detected.
Note that each license is reported alone for now, even if we detected a choice (as is common for JavaScript/jQuery code where the license is a choice of MIT or GPL)

**Comment by pombredanne** [comment]
@chinchang does my answer work for you?

**Comment by pombredanne** [comment]
Closing now since yu did not reply. Feel free to reopen!
