### ISSUE TITLE
Timeout for large XML file from JTS 1.13 library

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#694]
Using ScanCode version 2.0.0.rc3.post9.32d87ece with `--copyright --license --info --diag --only-findings --strip-root`, scanning `testxml/stmlf/stmlf-cases-20061018_int.xml` from [JTS 1.13](https://sourceforge.net/projects/jts-topo-suite/files/jts/1.13/) times out after 600s:

    Some files failed to scan properly:
    Path: testxml/stmlf/stmlf-cases-20061018_int.xml
      ERROR: Processing interrupted: timeout after 600 seconds.

    Scan statistics: 1241 files scanned in 676s.
    Scan options:    infos, licenses, copyrights with 6 process(es).
    Scanning speed:  1.84 files per sec.
    Scanning time:   675s.
    Indexing time:   1s.
    Saving results.

Sure, that XML file is large with its 13MB, but then again it should not take 3 minutes these days, esp. as we're *not* using `--package` (that could try to interpret this as a POM file or so). So I wonder whether this particular case points us at some obvious performance improvement that could be made.

**Comment by pombredanne** [comment]
@sschuberth thanks! let me check what triggers this

**Comment by pombredanne** [comment]
Sounds like the issue is similar to #641

**Comment by pombredanne** [comment]
this should fix it!. Thanks again.
