### ISSUE TITLE
Pre scan plugins for plugin architecture

### ISSUE THREAD

**Issue by yashdsaraf** [nexB/scancode-toolkit#697]
#552, #14

**Comment by pombredanne** [comment]
It might best to explain you design here than in #719 

And after #719 is merged we will need to create a sample new plugin that would skip files based on their size and filetype data (which comes from the info, and therefore makes things a tad more complicated than the simpler, path-based filter)

**Comment by yashdsaraf** [comment]
Every pre-scan plugins has to extend the AbstractFactory class
In it the get_option_attrs method will be called to get the attributes for the plugin's cmdline option, so plugin doesn't handle the creation of click options directly.
The process_resources method will be called in resource_paths function for plugins which require to make changes before the paths are supplied for scanning (e.g like --ignore), for plugins which do not need this method can simply call the super method which returns the resources back.

I chose this approach pre-scan plugins can't be plugged in a single spot, so AbstractFactory can add more method signatures in the future which can be called at different stages in cli.py

**Comment by yashdsaraf** [comment]
Also `get_option_attrs` is a staticmethod since it gets called before a plugin class is initialized,
later if user supplied the cmdline option corresponding to that plugin, then the option's input is passed to that plugin's `get_instance` which is a classmethod.

**Comment by pombredanne** [comment]
ok, this is a tad complex for my taste. Could there be a simpler way?

**Comment by yashdsaraf** [comment]
Well, we can't plug-in pre-scan plugins in a single spot, like post-scan plugins.
And we can't assume attributes for click options for these plugins.

**Comment by yashdsaraf** [comment]
How about having different hooks for different functions?
e.g
- for processing the `resources` i.e function which returns all the absolute paths of files to be scanned we could have a separate plugin marker (this can handle the --ignore part)
- for adding new scans or deleting them a different marker

This is something like `output` and `post-scan` are different markers

**Comment by yashdsaraf** [comment]
@pombredanne I'm now using a normal class `PreScanPlugin` which needs to be extended by all `pre-scan` plugins.
It has an attribute `option_attrs` which defined click option attributes for the corresponding plugin. Click option name is taken from the entry point and help text from its docstring.
For now, it has `process_resources` method which is called when files to be scanned are decided.
We can add more methods to this class which can represent different hooks, say to add or delete a scan we might have a method called `process_scan`.
If a plugin's option was passed by the user, then the plugin class is instantiated with the user input and its above mentioned methods are called.
This way a plugin need not override all methods.

**Comment by pombredanne** [comment]
The core has been merged in develop. Further work is taking place with #736 
@yashdsaraf Thanks++
