### ISSUE TITLE
Post scan plugins for plugin architecture

### ISSUE THREAD

**Issue by yashdsaraf** [nexB/scancode-toolkit#699]
#552, #377 
For now at a simpler level, the plugin is supposed to return at a directory level if all or the majority of a directory files are source code.
The goal is to set the `is_source` flag to True for a directory if and only if the majority (~90%) of the files under a directory have `is_source` set to True.
The flow would be that the plugin accepts `scanned_files` iterable, does its job and returns an iterable/yields updated results.
These results should then be updated in the cache (not by the plugin)
Each plugin for now should be defined by a single new option (one for each such plugin) and all such options should be grouped together in the CLI help (#643).

**Comment by pombredanne** [comment]
Can you elaborate a bit on the your design here?

**Comment by pombredanne** [comment]
This now complete in the post #885 merge
