### ISSUE TITLE
Package.download_urls should be a single value, not a list

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#716]
Have multiple download URLs does not make sense. There should be only one canonical download URL for a given package... Other URLs would be eventually mirrors, secondary URLs handled elsewhere. Tracking multiple URLs at the Package definition level is bad design.

**Comment by yash-nisar** [comment]
We already keep track of only the first URL as mentioned [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/formattedcode/format_csv.py#L210-L212), or are we planning to change the data-type from a list to a string in the [parent class itself](https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/models.py#L717) ?

Is there any example/case where we have multiple download URLs @pombredanne ?

**Comment by pombredanne** [comment]
@yash-nisar I fixed this as part of #275 in the #883 branch I think

**Comment by pombredanne** [comment]
This is fixed. Closing
