### ISSUE TITLE
scan a ziped archive

### ISSUE THREAD

**Issue by zhou-jg** [nexB/scancode-toolkit#72]
Can scancode scan a zipped archive like .jar or .zip and output the result like it is unziped?
If it can, how?

**Comment by pombredanne** [comment]
@zhou-jg yes, though this is using a separate command:
you need to first run the `extractcode` command to extract your codetree in-place and any Jar, tar, rar, compressed file, etc, will be extracted recursively first.

Then you can run `scancode` afterwards.

There is also a planned enhancement #14 to include this step transparently in the scan itself such that scancode calls the extractcode extraction function first before scanning.
Help is welcomed.
