### ISSUE TITLE
UTF handling bug

### ISSUE THREAD

**Issue by yahalom5776** [nexB/scancode-toolkit#725]
Hi @pombredanne ,

Scan Code version 2.0.1 on Windows 7 x64 with Python 2.7 gives me the following error. Stops at the file "ethiopic" from kbd package 2.0.3. I removed some other files from this directory in the archive that broke the scan as a quick fix but I think this needs a permanent fix. Extraction was done via extractcode.

Affected files are under kbd-2.0.3.tar.gz\kbd-2.0.3.tar\kbd-2.0.3\docs\doc\utf\

Archive: https://www.kernel.org/pub/linux/utils/kbd/kbd-2.0.3.tar.gz

Could this be connected to #688?

Thanks.

> (scancode-cp) C:\scancode\scancode-cp>scancode -l -n 2 --full-root --only-findings c:\TMP\snip_RootFS.zip-extract snip4.4.json
> Scanning files for: licenses with 2 process(es)...
> Building license detection index...Done.
> Scanning files...
> [------------#-------] 38597 Scanned: ethiopic
> Traceback (most recent call last):
>   File "C:\scancode\scancode-cp\bin\scancode-script.py", line 11, in <module>
>     load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
>   File "c:\scancode\scancode-cp\lib\site-packages\click\core.py", line 722, in _
> _call__
>     return self.main(*args, **kwargs)
>   File "c:\scancode\scancode-cp\src\scancode\utils.py", line 76, in main
>     standalone_mode=standalone_mode, **extra)
>   File "c:\scancode\scancode-cp\lib\site-packages\click\core.py", line 697, in m
> ain
>     rv = self.invoke(ctx)
>   File "c:\scancode\scancode-cp\lib\site-packages\click\core.py", line 895, in i
> nvoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\scancode\scancode-cp\lib\site-packages\click\core.py", line 535, in i
> nvoke
>     return callback(*args, **kwargs)
>   File "c:\scancode\scancode-cp\lib\site-packages\click\decorators.py", line 17,
>  in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "c:\scancode\scancode-cp\src\scancode\cli.py", line 402, in scancode
>     ignore=user_ignore)
>   File "c:\scancode\scancode-cp\src\scancode\cli.py", line 515, in scan
>     result = scanned.next()
>   File "c:\scancode\scancode-cp\lib\site-packages\click\_termui_impl.py", line 2
> 66, in next
>     self.update(1)
>   File "c:\scancode\scancode-cp\lib\site-packages\click\_termui_impl.py", line 2
> 48, in update
>     self.render_progress()
>   File "c:\scancode\scancode-cp\src\scancode\utils.py", line 85, in render_progr
> ess
>     return super(EnhancedProgressBar, self).render_progress()
>   File "c:\scancode\scancode-cp\lib\site-packages\click\_termui_impl.py", line 2
> 30, in render_progress
>     echo(line, file=self.file, color=self.color, nl=nl)
>   File "c:\scancode\scancode-cp\lib\site-packages\click\utils.py", line 259, in
> echo
>     file.write(message)
>   File "c:\scancode\scancode-cp\lib\site-packages\click\_compat.py", line 577, i
> n _safe_write
>     return _write(s)
>   File "c:\scancode\scancode-cp\lib\site-packages\colorama\ansitowin32.py", line
>  36, in write
>     self.__convertor.write(text)
>   File "c:\scancode\scancode-cp\lib\site-packages\colorama\ansitowin32.py", line
>  133, in write
>     self.write_and_convert(text)
>   File "c:\scancode\scancode-cp\lib\site-packages\colorama\ansitowin32.py", line
>  158, in write_and_convert
>     self.write_plain_text(text, cursor, start)
>   File "c:\scancode\scancode-cp\lib\site-packages\colorama\ansitowin32.py", line
>  166, in write_plain_text
>     self.wrapped.write(text[start:end])
>   File "c:\scancode\scancode-cp\lib\encodings\cp437.py", line 12, in encode
>     return codecs.charmap_encode(input,errors,encoding_map)
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: cha
> racter maps to <undefined>
> (scancode-cp) C:\scancode\scancode-cp>
>

**Comment by pombredanne** [comment]
@yahalom5776 Thanks for the report. This does not seem to be related to #688 but rather some output format issue.

**Comment by pombredanne** [comment]
This may be related to colorama
https://github.com/tartley/colorama/issues/36

**Comment by pombredanne** [comment]
@yahalom5776 can you do a test with this branch https://github.com/nexB/scancode-toolkit/tree/725-unicode-windows-error ? I bumped colorama and added an extra forced conversion to ASCII

**Comment by yahalom5776** [comment]
@pombredanne,  yes I will test it latest on Monday and report back

**Comment by yahalom5776** [comment]
@pombredanne 
I could already test if - this branch fixes the issue in kbd! Thank you.

**Comment by pombredanne** [comment]
@yahalom5776 It is not a guaranteed fix but there a good chance it does work. Terminal ANSI escape sequences are a tad arcane topic, so for now upgrading colorama and forcing ASCII on terminal outputs sounds like a practical likely fix.

**Comment by yahalom5776** [comment]
@pombredanne The fix works, I think you can merge  it when convenient. Thanks.

**Comment by pombredanne** [comment]
@yahalom5776 Thanks ++ for testing this (and reporting it in the first place)!
