### ISSUE TITLE
false positive for GPL

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#730]
https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/CONTRIBUTING.md

is recognized as GPL, while there is no GPL at all in there. The following seems to be triggering it:

you provide is on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS
FOR A PARTICULAR PURPOSE.

**Comment by armijnhemel** [comment]
There are more files in that repository that trigger the GPL rule:

https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Src/Newtonsoft.Json/Utilities/LinqBridge.cs

**Comment by pombredanne** [comment]
@armijnhemel Thanks! Sounds like they reused the GPL warranty disclaimer in their CLA and their BSD notice. 

The funny side effect is that 
- their code includes BSD-licensed code at https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Src/Newtonsoft.Json/Utilities/LinqBridge.cs and does not even include a proper BSD license
- is overall per MIT-licensed https://github.com/JamesNK/Newtonsoft.Json/blob/master/LICENSE.md

@JamesNK are you aware of these small discrepancies in your licensing?

Now the resolution in ScanCode is going to be:
- add a new license for @JamesNK CLA which is kinda unique at the bottom of https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/CONTRIBUTING.md
- add new license detection rules for the BSD notice (which looks like a  GPL)  for https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Src/Newtonsoft.Json/Utilities/LinqBridge.cs which is from @albahari and @atifaziz 
- add a test for safety for the MIT in https://github.com/JamesNK/Newtonsoft.Json/blob/master/LICENSE.md


@armijnhemel have you spotted any other discrepancies in the license detection?

**Comment by atifaziz** [comment]
> Sounds like they reused the GPL warranty disclaimer in…their BSD notice.

@pombredanne Are you saying the following [disclaimer at the top of `LinqBridge.cs` file](https://github.com/JamesNK/Newtonsoft.Json/blob/98366a4b88be7c0a0cd8674127cc2c7a17c6b70d/Src/Newtonsoft.Json/Utilities/LinqBridge.cs#L13-L27) is from GPL?

```c#
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
// PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

As far as I can tell, it's the same as at the bottom of the [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause).

**Comment by pombredanne** [comment]
@atifaziz good catch! I stated this wrong:
The warranty disclaimer is perfectly ok, only the notice on top of it is mildly looking like a GPL/FSF notice https://github.com/JamesNK/Newtonsoft.Json/blob/98366a4b88be7c0a0cd8674127cc2c7a17c6b70d/Src/Newtonsoft.Json/Utilities/LinqBridge.cs#L13

**Comment by pombredanne** [comment]
@atifaziz nothing to be worried about on your side... a tad unsual but it will be detected alright. The detection eventually performs comprehensive pair-wise multiple sequence alignments hence the false positive here. Thanks for chiming in!

**Comment by pombredanne** [comment]
Fixed! Sorry it took so long as this was trivial!

**Comment by pombredanne** [comment]
I am doing some cleanup and review as a prep for the 3.0 release... and since this is fixed in develop, I am closing this!
