### ISSUE TITLE
Improved debugging and tracing without multiprocessing

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#731]
multiprocessing has this peculiar way to hide some exception by truncating the trace back.
The idea would be to have a simple way to run scans without multiprocessing and without threading to ease debugging.
For this I would use the `--processes` flag with a value of zero. And when we have a scan with "0" processes, then we would bypass the multiprocessing pool usage (using a plain `imap`) and bypass threading (and disable --timeout support)

**Comment by armijnhemel** [comment]
so what happens if I say "n = 1"? Is it conceptually different from n = 0?

I would actually argue that n = 0 should mean "use all CPUs", as that is conceptually more in sync with the Python behaviour:

https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.multiprocessing.Pool

     If processes is None then the number returned by cpu_count() is used.

**Comment by pombredanne** [comment]
@armijnhemel The behavior of `-n 0` was unspecified (and was actually crashing) so I am using it for this debugging feature where no threading or multiprocessing is used at all. I get your point that -n0 could mean use all CPUs but in practice since there are a lot of I/O involved in the scans it can sometimes be best to use more processes than there are CPUs.
And the behavior of `-n 1` is to use one process but under the control of  threading and multiprocessing 

Now thinking about it more you have a good point... we would have -n0 which use up to cpu_count(), -n1 which use a single process without  threading and multiprocessing  and other values which use  threading and multiprocessing and whatever you specified?

**Comment by armijnhemel** [comment]
That is indeed what I would suggest, if possible. I think we can agree that n=0 is somewhat weird no matter what :)

**Comment by pombredanne** [comment]
@armijnhemel the new commit https://github.com/nexB/scancode-toolkit/commit/f8f22209d7a98e3880fbec0bdb7b2b44e101ec6d does this:

 * No longer accepts `--processes=0` as an option value
 * With `processes=1`, run without multiprocessing
 * With `timeout=0`, run without timeout threaded guard

**Comment by pombredanne** [comment]
@armijnhemel  the new commit f8f2220 really does not work at all.  I will try to see if there is an easy fix, but I may stay with the simple `--processes=0` to disable both multiprocessing and the timeout threaded guard at once.

**Comment by pombredanne** [comment]
@armijnhemel unless you have an objection I am inclined to trash the last commit f8f2220 and stay as things are in develop at this stage

**Comment by armijnhemel** [comment]
fine with me :)

**Comment by pombredanne** [comment]
So I am closing this. The final behavior for now is:
 - `-n0` disables multi-processing and threading and ignores timeout. Valuable for debugging only
 - `-n1` use single processing with threading and timeout (the default(
 - `-n 2 or more` use multi-processing with threading and timeout
