### ISSUE TITLE
false positive: ScanSoft Public License

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#734]
https://github.com/OData/odata.net/blob/master/src/AssemblyInfo/AssemblyInfoCommon.cs

is recognized as ScanSoft Public License. The 'License.txt' file they refer to actually contains MIT

**Comment by pombredanne** [comment]
Thanks!
This is what is detected with ` ./scancode -l -f json-pp --diag --license-text`:

```
 "files": [
    {
      "path": "scancode-toolkit/t",
      "scan_errors": [],
      "licenses": [
        {
          "key": "scansoft-1.2",
          "score": 46.67,
          "short_name": "ScanSoft Public License 1.2",
          "category": "Permissive",
          "owner": "Nuance Communications",
          "homepage_url": "http://www.speech.cs.cmu.edu/openvxi/OpenVXI_3.0/OpenSpeech_Browser_PIK/doc/License.txt",
          "text_url": "http://www.speech.cs.cmu.edu/openvxi/OpenVXI_3.0/OpenSpeech_Browser_PIK/doc/License.txt",
          "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:scansoft-1.2",
          "spdx_license_key": "",
          "spdx_url": "",
          "start_line": 31,
          "end_line": 31,
          "matched_rule": {
            "identifier": "scansoft-1.2_4.RULE",
            "license_choice": false,
            "licenses": [
              "scansoft-1.2"
            ],
            "matcher": "3-seq",
            "rule_length": 58,
            "matched_length": 7,
            "match_coverage": 12.07,
            "rule_relevance": 100
          },
          "matched_text": "registered trademarks or trademarks of [Microsoft] [Corporation] [in] [the] [U].[S]. [and]/[or] other countries"
        }
      ]
    }
  ]
```

The detection trigger is this:
`[assembly: AssemblyTrademark("Microsoft and Windows are either registered trademarks or trademarks of Microsoft Corporation in the U.S. and/or other countries.")]`

This could be returned as its own license like a "trademark notice" of sorts or ignored entirely as this is not really a license statement at all.

The second item is the  `See License.txt in the project root for license information.` mention. This is not enough to detect a MIT license for now short of having a license inference capability as described in #377 and is not reported either yet (this is a known thing until we have a proper #377 ) 
So I suggest to return this as an unknown license for now.

What do you think for these two?

**Comment by armijnhemel** [comment]
But that is not even a license statement. That seems to be some templating code when the code is used to generate a .NET assembly and put into the generated code (I think). So it doesn't apply to the current file at all.

**Comment by pombredanne** [comment]
This is fixed in develop

**Comment by pombredanne** [comment]
And available also in the latest released tags ! thanks
