### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#746]
$ ./scancode --full-root -f json-pp -n 4 ~/tmp/linux-4.10.1/fs/dcookies.c

gives me the following in the JSON output:

"path": "/home/armijn/tmp/linux-4.10.1/fs/dcookies.c/dcookies.c"

which is wrong, as it should be:

"path": "/home/armijn/tmp/linux-4.10.1/fs/dcookies.c"

$ git log | head -n 1
commit b80257d022fa95c281266a1a96b7edde1f83aa72

**Comment by armijnhemel** [comment]
Doesn't happen when scanning a directory, just when scanning single files

**Comment by pombredanne** [comment]
Thanks! Good catch..
