### ISSUE TITLE
false positives for e-mails from iOS Contents.json files

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#751]
Example:

https://github.com/xamarin/XamarinComponents/blob/master/iOS/JZMultiChoicesCircleButton/samples/JZMultiChoicesCircleButtonSample/Resources/Images.xcassets/Success.imageset/Contents.json

When scanning for e-mails this will report:

          "emails": [
        {
          "email": "Shape@3x.png",
          "start_line": 15,
          "end_line": 15

**Comment by pombredanne** [comment]
@armijnhemel Thanks. Good catch. We should be able to catch these because `.png` and more is not a top level domain most likely using this https://github.com/pombredanne/python-publicsuffix2 which is already bundled in ScanCode but not yet used.

**Comment by armijnhemel** [comment]
Not just that: it seems to be a fixed format and the files are always called "Contents.json", so it should also be possible to parse the JSON and do a few sanity checks and then tag the file.

**Comment by pombredanne** [comment]
This could work too

**Comment by pombredanne** [comment]
Fixed at last! For your review

**Comment by pombredanne** [comment]
I am doing some cleanup and review as a prep for the 3.0 release... and since this is fixed in develop, I am closing this!
