### ISSUE TITLE
py.test

### ISSUE THREAD

**Issue by jimjag** [nexB/scancode-toolkit#756]
The contribution page mentions using 'py.test' to test local changes. Installation of 'pytest' via pip should be documented.

**Comment by pombredanne** [comment]
@jimjag the `py.test` script is installed when `pytest` is installed (which is bundled with a scancode checkout and installed when you run `./configure`).

If you are running from a fresh git clone, and you run `./configure` and then `source bin/activate` the `py.test` will be available then. Alternatively if you have already configured but are not in an activate "virtualenv" `py.test` is available under `<root of your checkout>/bin/py.test`

(Note: this is for POSIX, but mostly the same applies for Windows)

**Comment by pombredanne** [comment]
Note that if you have a multiprocessor machine you might want to run the tests in parallel (and faster)
For instance: `py.test -n4` runs the tests on 4 CPUs.
I typically run the tests in verbose mode with `py.test -vvs -n4`

You can also run a subset of the test suite as shown in the CI configs https://github.com/nexB/scancode-toolkit/blob/develop/appveyor.yml#L6 e,g, `py.test -n 2 -vvs tests/scancode` runs only the tests in the `tests/scancode` directory. (You can pass a path to a test script there too)

See also https://docs.pytest.org or use `py.test -h` show the many other options available... 

One useful option is to run a select subset of the test functions matching a pattern with the `-k` option for instance: `py.test -vvs -k tcpdump` would only run test functions that contain the string "tcpdump" in their name or their class name or module name .

Another useful option after a test run with some failures is to rerun only the failed tests  with the `--lf` option for instance: `py.test -vvs --lf` would only run only test functions that failed in the previous run.

**Comment by pombredanne** [comment]
@jimjag Since the doc was obviously confusing I added a new section in https://github.com/nexB/scancode-toolkit/wiki/Development#running-tests
Please tell me if this works better for you!

**Comment by jimjag** [comment]
Perfect. Thx!
