### ISSUE TITLE
Add license reference URL template

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#759]
The "dejacode_url" field for a license currently points only to the public instance of DejaCode at https://enterprise.dejacode.com/urn/.  This field should be renamed to "reference_url" with a parameter for a ScanCode user to substitute a URL template where you can reference the license information with the the URL template value concatenated with the ScanCode license "key" field value.

**Comment by pombredanne** [comment]
@mjherzog Looking all good to me.

**Comment by pombredanne** [comment]
I suggest that we use this syntax:
```
./scancode --license-url-template="https://myhost.com/urn/urn:dje:license:{}"
```
with a default to this : https://github.com/nexB/scancode-toolkit/blob/00a078e358036d06a3a361949799383599a0df5b/src/scancode/api.py#L100

This needs to be added as a new CLI option

**Comment by pombredanne** [comment]
This has been in develop and 2.2.1 for a long while
