### ISSUE TITLE
GPLv2+ code recognized as GPL-1.0+

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#770]
Some of the code from extensions from Semantic Media Wiki code (example: SQLStore/TableBuilder.php ) has the following header:

/**
 * @private
 *
 * Provides generic creation and updating function for database tables. A builder
 * that implements this interface is expected to define Database specific
 * operations and allowing it to be executed on a specific RDBMS back-end.
 *
 * @license GNU GPL v2+
 * @since 2.5
 *
 * @author mwjames
 */

and ScanCode says:

    {
      "path": SQLStore/TableBuilder.php",
      "scan_errors": [],
      "licenses": [
        {
          "key": "gpl-1.0-plus",
          "score": 15.0,
          "short_name": "GPL 1.0 or later",
          "category": "Copyleft",
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
          "text_url": "http://www.gnu.org/licenses/old-licenses/gpl-1.0-standalone.html",
          "dejacode_url": "https://enterprise.dejacode.com/urn/urn:dje:license:gpl-1.0-plus",
          "spdx_license_key": "GPL-1.0+",
          "spdx_url": "https://spdx.org/licenses/GPL-1.0",
          "start_line": 15,
          "end_line": 15,
          "matched_rule": {
            "identifier": "gpl_89.RULE",
            "license_choice": false,
            "licenses": [
              "gpl-1.0-plus"
            ]
          }
        }

**Comment by pombredanne** [comment]
@armijnhemel Thanks. A fix is on the way

**Comment by pombredanne** [comment]
and this is fixed in develop
