### ISSUE TITLE
Escaping non UTF-8 in license file paths

### ISSUE THREAD

**Issue by FHantke** [nexB/scancode-toolkit#773]
Hello,

I am using my own script to create new license files and rules.
There always an error occoured, while reloading the license files, due to non UTF-8 charachters in the license path names.
At the moment I'm escaping some UTF-8 characters in my license create script, but will it be possible, to use non UTF-8 charachters in license paths?

Tested with scancode version 2.1.0 with python 2.7 at the moment.

Thanks.

> D:\scancode\scancode-toolkit-2.1.0>scancode --reindex-licenses
> Checking and rebuilding the license index...
> Traceback (most recent call last):
>   File "D:\scancode\scancode-toolkit-2.1.0\bin\scancode-script.py", line 11, in <module>
>     load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
>   File "d:\scancode\scancode-toolkit-2.1.0\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "d:\scancode\scancode-toolkit-2.1.0\src\scancode\utils.py", line 74, in main
>     standalone_mode=standalone_mode, **extra)
>   File "d:\scancode\scancode-toolkit-2.1.0\lib\site-packages\click\core.py", line 696, in main
>     with self.make_context(prog_name, args, **extra) as ctx:
>   File "d:\scancode\scancode-toolkit-2.1.0\lib\site-packages\click\core.py", line 621, in make_context
>     self.parse_args(ctx, args)
>   File "d:\scancode\scancode-toolkit-2.1.0\lib\site-packages\click\core.py", line 880, in parse_args
>     value, args = param.handle_parse_result(ctx, opts, args)
>   File "d:\scancode\scancode-toolkit-2.1.0\lib\site-packages\click\core.py", line 1404, in handle_parse_result
>     self.callback, ctx, self, value)
>   File "d:\scancode\scancode-toolkit-2.1.0\lib\site-packages\click\core.py", line 78, in invoke_param_callback
>     return callback(ctx, param, value)
>   File "d:\scancode\scancode-toolkit-2.1.0\src\scancode\cli.py", line 224, in reindex_licenses
>     cache.reindex()
>   File "d:\scancode\scancode-toolkit-2.1.0\src\licensedcode\cache.py", line 134, in get_or_build_index_through_cache
>     current_checksum = tree_checksum(tree_base_dir=_tree_base_dir)
>   File "d:\scancode\scancode-toolkit-2.1.0\src\licensedcode\cache.py", line 75, in tree_checksum
>     return md5(''.join(sorted(hashable))).hexdigest()
>   File "d:\scancode\scancode-toolkit-2.1.0\src\licensedcode\cache.py", line 73, in <genexpr>
>     hashable = (pth + str(getmtime(pth)) + str(getsize(pth))
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileutils.py", line 474, in resource_iter
>     for top, dirs, files in walk(location, ignored):
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileutils.py", line 427, in walk
>     for tripple in walk(os.path.join(location, dr), ignored):
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileutils.py", line 427, in walk
>     for tripple in walk(os.path.join(location, dr), ignored):
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileutils.py", line 427, in walk
>     for tripple in walk(os.path.join(location, dr), ignored):
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileutils.py", line 414, in walk
>     if filetype.is_special(loc) or ignored(loc):
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\ignore.py", line 47, in is_ignored
>     return fileset.match(location, includes=ignores, excludes=unignores)
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileset.py", line 105, in match
>     included = _match(path, includes)
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileset.py", line 126, in _match
>     path = fileutils.as_posixpath(path).lower()
>   File "d:\scancode\scancode-toolkit-2.1.0\src\commoncode\fileutils.py", line 264, in as_posixpath
>     return location.replace(WIN_PATH_SEP, POSIX_PATH_SEP)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 84: ordinal not in range(128)

**Comment by FHantke** [comment]
My bad, I recognized your key rules here, I forgot about...
https://github.com/nexB/scancode-toolkit/wiki/FAQ#how-to-add-a-new-license-for-detection

Nevertheless, it would be great, if you were able to add more specified keys.

Thanks.

**Comment by pombredanne** [comment]
@FHantke are you trying to create license rules or license with a key that is not ASCII?

**Comment by FHantke** [comment]
Yes, I have licens names with e.g. ä,ö,ü and tried to use the name as key.
Now I'm using the SHA256 of the license text.

**Comment by pombredanne** [comment]
@FHantke OK, only ASCII letter and numbers, dash, dot and underscore are supported for keys for now: this is the only sane way I know off to have portable filenames across OSes (e.g. Windows and POSIX) 

Just out of curiosity what are these licenses?
