### ISSUE TITLE
ScanCode is not recognizing the Python programming_language for .whl files

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#778]
I'm running scancode-toolkit-2.1.0 on Mac OS.  I ran a scan using these parameters: 
```./scancode --format json -c -l -p -e -u -i  /scancode-toolkit-src-2.1.0/thirdparty```
and then converted the .json output to .csv.  
The programming_language field is empty for all  of the .whl files.  Since that is a standard format for Python packages, it seems that it ought to recognize Python.  

See https://www.python.org/dev/peps/pep-0427/  for additional reference.

**Comment by pombredanne** [comment]
@DennisClark Thanks. We should report a wheel as a package alright.

**Comment by DennisClark** [comment]
This has been addressed.  Closing.
