### ISSUE TITLE
ScanCode reports a license key of "unicode-data-software" rather than "unicode"

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#780]
I'm running scancode-toolkit-2.1.0 on Mac OS. I ran a scan using these parameters:
./scancode --format json -c -l -p -e -u -i /scancode-toolkit-src-2.1.0/thirdparty
and then converted the .json output to .csv.

For the component "idna" one of the license keys reported is "unicode-data-software".  This should simply be "unicode". 

Here is the complete text of the idna.NOTICE file:

```
License
-------

Copyright (c) 2013-2017, Kim Davies. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

#. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

#. Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials provided with
   the distribution.

#. Neither the name of the copyright holder nor the names of the 
   contributors may be used to endorse or promote products derived 
   from this software without specific prior written permission.

#. THIS SOFTWARE IS PROVIDED BY THE CONTRIBUTORS "AS IS" AND ANY
   EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
   PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR 
   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
   USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
   DAMAGE.

Portions of the codec implementation and unit tests are derived from the
Python standard library, which carries the `Python Software Foundation
License <https://docs.python.org/2/license.html>`_:

   Copyright (c) 2001-2014 Python Software Foundation; All Rights Reserved

Portions of the unit tests are derived from the Unicode standard, which 
is subject to the Unicode, Inc. License Agreement:

   Copyright (c) 1991-2014 Unicode, Inc. All rights reserved.
   Distributed under the Terms of Use in 
   <http://www.unicode.org/copyright.html>.

   Permission is hereby granted, free of charge, to any person obtaining
   a copy of the Unicode data files and any associated documentation
   (the "Data Files") or Unicode software and any associated documentation
   (the "Software") to deal in the Data Files or Software
   without restriction, including without limitation the rights to use,
   copy, modify, merge, publish, distribute, and/or sell copies of
   the Data Files or Software, and to permit persons to whom the Data Files
   or Software are furnished to do so, provided that
   
   (a) this copyright and permission notice appear with all copies 
   of the Data Files or Software,

   (b) this copyright and permission notice appear in associated 
   documentation, and

   (c) there is clear notice in each modified Data File or in the Software
   as well as in the documentation associated with the Data File(s) or
   Software that the data or software has been modified.

   THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
   ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
   WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
   NONINFRINGEMENT OF THIRD PARTY RIGHTS.
   IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
   NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
   DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
   DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
   TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
   PERFORMANCE OF THE DATA FILES OR SOFTWARE.

   Except as contained in this notice, the name of a copyright holder
   shall not be used in advertising or otherwise to promote the sale,
   use or other dealings in these Data Files or Software without prior
   written authorization of the copyright holder.
```

**Comment by pombredanne** [comment]
@DennisClark Thanks! I had documented what I thought were the proper licenses in https://github.com/nexB/scancode-toolkit/blob/develop/thirdparty/base/idna.ABOUT and https://github.com/nexB/scancode-toolkit/blob/develop/thirdparty/base/unicode-data-software.LICENSE

The section in the NOTICE you reference is matched exactly to https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/unicode-data-software.RULE .

This is a tad messy area indeed!

First we have these two **not mapped to SPDX** licenses:

- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode.LICENSE and https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode.yml

- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-data-software.LICENSE and - https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-data-software.yml  (2015 version)

And doing a diff between these two shows indeed that there only minute differences: header links and copyrights and some minor wording differences: https://gist.github.com/pombredanne/ff11946eb2821e31ddd4170ab065085e/revisions#diff-8ab3b19e134f01fbaf94b8e15f3df090

We also have these two **mapped to SPDX** ids:
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-dfs-2015.LICENSE and https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-dfs-2015.yml
 
- https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-dfs-2016.LICENSE and https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-dfs-2016.yml

The diff between these two SPDX is here:
https://gist.github.com/pombredanne/442c0c0380bbdeb2aaa6e87d4b888a38/revisions#diff-718779752b851ac0dc6281a8c8d77e7e


We should make this simpler alright!

**Comment by pombredanne** [comment]
Fix and merged in develop
