### ISSUE TITLE
Add streamable json output format

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#781]
A format such as one of http://ndjson.org/ or http://jsonlines.org/ or https://tools.ietf.org/html/rfc7464 allows to stream write and stream read possibly large JSON data/files without the need to load it all in memory. This would be a valuable text format for data interchange with AboutCode manager and other tools.

**Comment by JonoYang** [comment]
After a discussion with @pombredanne, we will use JSON Lines to create a new format plugin. 

The first line of output would be the header. This would be a JSON object whose key is `header` and value is a JSON object that contains `scancode_notice`, `scancode_version`, `scancode_options`, and `file_count`.

The subsequent lines would be a JSON object whose key is `files` and value is a list containing a single file object. Each line would be a separate file. This is done for consistency with the current JSON output.

**Comment by pombredanne** [comment]
See also https://github.com/nexB/aboutcode/issues/7 about the header

**Comment by JonoYang** [comment]
Merged
