### ISSUE TITLE
Incorrect copyright holders detected

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#795]
ScanCode Version: 2.2.1
Package scanned: [gnutls-3.5.8](https://www.gnupg.org/ftp/gcrypt/gnutls/v3.5/gnutls-3.5.8.tar.xz)

Several copyright holders contain copyright dates. For example, the following copyright holders were detected. 

| Copyright Statement  | Copyright Holder|
|---|---|
| COPYRIGHT Copyright \ co 2001-2017 Free Software Foundation, Inc., and others.  | \ co 2001-2017 Free Software Foundation, Inc., and others.  
|  Copyright (c) 2000-2017 Free Software Foundation, and others | 2000-2017 Free Software Foundation, and others | 
|  COPYRIGHT Copyright \ co 2014-2017 Free Software Foundation, Inc., and others. | \ co 2014-2017 Free Software Foundation, Inc., and others.  |

**Comment by pombredanne** [comment]
@jdaguil Thanks for the report! what is the holder that you expect to get in these cases?

**Comment by jdaguil** [comment]
@pombredanne  I would expect:

| Copyright Statement | Copyright Holder |
|---------------------|------------------|
| COPYRIGHT Copyright \ co 2001-2017 Free Software Foundation, Inc., and others. | Free Software Foundation, Inc., and others |
| Copyright (c) 2000-2017 Free Software Foundation, and others | Free Software Foundation, and others |
| COPYRIGHT Copyright \ co 2014-2017 Free Software Foundation, Inc., and others. | Free Software Foundation, Inc., and others |

**Comment by pombredanne** [comment]
@jdaguil this has been fixed and merged in develop. Thank you for report!
