### ISSUE TITLE
Always return minimal type information with a scanned file

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#802]
AboutCode Manager and other tools need to know if a path is a file or directory at the minimum.
This information is only returned with the `--info` option atm. We should provide this all the times IMHO whether or not detailed file information was requested otherwise proper downstream processing of  scan results  may not be possible.

**Comment by yash-nisar** [comment]
I'm taking this one !

**Comment by pombredanne** [comment]
I have second thoughts on this: let me review and thank you for the commit!

**Comment by yash-nisar** [comment]
@pombredanne What did you finally decide ?

**Comment by pombredanne** [comment]
@yash-nisar I want this alright! so if you can update based on the latest develop I will merge

**Comment by mjherzog** [comment]
Also time to reconsider naming file or directory fields as "resource" fields.

**Comment by pombredanne** [comment]
@mjherzog sure thing, but that would be in another ticket
