### ISSUE TITLE
Weird URL detected

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#803]
The following URL was detected with v2.2.0

`"url": "http://www.w3.org/XML/1998/namespace%00%00%00%00xmlns%00%00%00http:/www.w3.org/2000/xmlns/%00%00%00ixmlElement_setTagName%00%00ixmlElement_findAttributeNode%00%00%00#document\u0000\u0000\u0000#text\u0000\u0000\u0000#cdata-section\u0000\u0000nnMap"`

I do not think this is a useful URL. At minimum, it should probably be two URLs.

**Comment by pombredanne** [comment]
@jdaguil which file was this detected in?

**Comment by pombredanne** [comment]
I was able to verify that this is not longer a problem. Closing.
