### ISSUE TITLE
ScanCode expects failure when scanning patchelf.pdf

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#806]
I just realized that ScanCode [expects a failure](https://github.com/nexB/scancode-toolkit/blob/develop/tests/scancode/data/failing/patchelf.expected.json) when scanning its very own `tests/scancode/data/failing/patchelf.pdf`.

I believe that failure actually is a bug in pdfminer(.six) that should get fixed there. But before I report this as a bug to upstream, I wanted to check with @pombredanne whether you actually agree, as it would also require changes on your side if you upgraded to a pdfminer(.six) version that fixed this issue.

**Comment by pombredanne** [comment]
@sschuberth there is a bug upstream with possible fixes afaik: https://github.com/euske/pdfminer/issues/96 Eventually this would be needed in pdfminer.six as pdfminer proper seems like a flatliner

**Comment by sschuberth** [comment]
Do you think my blindly typed https://github.com/pdfminer/pdfminer.six/pull/96 would fix the issue (please add any review comments over there)?

**Comment by pombredanne** [comment]
@sschuberth It certainly works and sounds good defensive programming to me!

**Comment by pombredanne** [comment]
For reference see also 
- #289
- https://stackoverflow.com/questions/40158637/struct-error-unpack-requires-a-string-argument-of-length-16/40325490#40325490
- https://github.com/euske/pdfminer/issues/144 and https://github.com/euske/pdfminer/issues/96

**Comment by pombredanne** [comment]
@sschuberth if we do not get a merged and release in the next few days, I will create a build of pdfminer.six off your patches ;)

**Comment by pombredanne** [comment]
Fixed and merged in develop
