### ISSUE TITLE
Update README with new screenshot(s) of ScanCode workbench

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#811]
This is much better looking and more usable for scan reviews than the HTML app... that will be deprecated soon enough!

**Comment by pombredanne** [comment]
@jdaguil could this be something you could look at? Thanks!

**Comment by sk9331657** [comment]
@pombredanne  Claiming this .

**Comment by pombredanne** [comment]
@sk9331657 let me defer this to @dmclark and @sesser:  do you guys mind chiming in this?
I had removed the screen shot we had in the past. Do we want one in the README? your call

**Comment by majurg** [comment]
@pombredanne We have some already in the `scancode-workbench` README and Wiki. We could probably get away with just linking to one of those. That way we have one source of screenshots and would not need to keep it updated on the `scancode-toolkit` side.

**Comment by AyanSinhaMahapatra** [comment]
Since this [page](https://aboutcode.readthedocs.io/en/latest/scancode-toolkit/tutorials/how_to_visualize_scan_results.html) was added and the new getting started section has links to this page and then to ScanCode Workbench, should this be closed?

**Comment by majurg** [comment]
https://aboutcode.readthedocs.io/en/latest/scancode-toolkit/tutorials/how_to_visualize_scan_results.html contains updated scancode-workbench screenshots.

Closing this.
