### ISSUE TITLE
Include Version Number of ScanCode Toolkit in Reports

### ISSUE THREAD

**Issue by sharonlcorbett** [nexB/scancode-toolkit#814]
It would be extremely helpful if the report could indicate which version of ScanCode was used.

This could be included in the footer or as an html comment.  Additionally including it in the json report would be useful if not already included.

Thanks!

**Comment by pombredanne** [comment]
@sharonlcorbett sure thing: It is included in the JSON outputs as data and the SPDX outputs as comments.
There is no straightforward way to include it in the CSV output but I find one.
Which output do you use?

**Comment by eclipsewebmaster** [comment]
We use the JSON outputs, as well as the HTML outputs. Having the version in the HTML would be great.

**Comment by pombredanne** [comment]
@eclipsewebmaster that's an easy one. Note also that there is plans to get multiple outputs from a single scan run #789

**Comment by eclipsewebmaster** [comment]
I've subscribed to #789. That would be very helpful for us today, as we invoke Scancode twice.

**Comment by pombredanne** [comment]
@sharonlcorbett @eclipsewebmaster I just pushed a `814-scancode-version-in-html` branch adding the version details to the html outputs. 
You can give it a try with a git checkout or with this download: https://github.com/nexB/scancode-toolkit/archive/814-scancode-version-in-html.tar.gz

Thanks++ for the report. Much welcomed!

Side note: you might want to check out https://github.com/nexB/aboutcode-manager which is a Gui to review a scan (it takes its input from a scan in JSON format)

**Comment by eclipsewebmaster** [comment]
Verified in 814. Thank you!

**Comment by pombredanne** [comment]
@eclipsewebmaster Thank you for testing this! I am merging then.
