### ISSUE TITLE
Add Makehuman license exception?

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#816]
See http://www.makehuman.org/license.php and  http://www.makehuman.org/license_explanation.php

> As a special and limited exception, the copyright holders of the MakeHuman assets grants the option 
to use CC0 1.0 Universal as published by the Creative Commons, either version 1.0 of the License, or (at your option) any later version, as a license for the MakeHuman characters exported under the conditions that a) The assets were bundled in an export that was made using the file export functionality inside an OFFICIAL and UNMODIFIED version of MakeHuman and/or b) the asset solely consists of a 2D binary image in PNG, BMP or JPG format.

**Comment by SaravananOffl** [comment]
@pombredanne I can try working on this! .Could you guide me ?

**Comment by SaravananOffl** [comment]
@pombredanne I've found the way to add this license in  project's wiki. http://www.makehuman.org/license.php The link has got four parts 
A. The MakeHuman Source code and data
B. Other MakeHuman Application Code
C. Optional use of CC0 for output
D. CC0 1.0 Universal
I'm supposed to put all these texts into make-human.LICENSE right?

**Comment by pombredanne** [comment]
I think that you should focus on only creating a new .LICENSE for the exception text

**Comment by pombredanne** [comment]
eg this:
```
C. MakeHuman output GPL exception

==================================

As a special and limited exception, the copyright holders of the MakeHuman assets grants the option to use CC0 1.0 Universal as published by the Creative Commons, either version 1.0 of the License, or (at your option) any later version, as a license for the MakeHuman characters exported under the conditions that a) The assets were bundled in an export that was made using the file export functionality inside an OFFICIAL and UNMODIFIED version of MakeHuman and/or b) the asset solely consists of a 2D binary image in PNG, BMP or JPG format.

The short version of CC0 is as follows:

The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.

See also long version of CC0 (section D)

For an elaboration and clarification on our intention and interpretation of these license terms see the License Explanation: http://www.makehuman.org/content/license_explanation.html
```

and you can create tests to ensure that everything at http://www.makehuman.org/license.php is properly detected (and if the tests do not pass, add new license detection rules .RULE)

**Comment by SaravananOffl** [comment]
@pombredanne I've added LICENSE file for that exception . Could you tell me the procedure to run tests?

**Comment by pombredanne** [comment]
See https://github.com/nexB/scancode-toolkit/wiki/Development#running-tests
