### ISSUE TITLE
Review 'unicode' filetype unit test - wrong/incomplete test

### ISSUE THREAD

**Issue by supragya** [nexB/scancode-toolkit#824]
The unicode filetype test `test_filetype_file_on_unicode_file_name2` as given in `tests/typecode/test_contenttype.py` is either incomplete or wrong.

A run of command: `py.test -n 2 -vvs tests/typecode -k unicode --capture=sys` reveals this.

**Required**: Refactoring/Rewritting the function. Successfully extract zip file `unicode2.zip` as done in `test_filetype_file_on_unicode_file_name()` to assert `test_file` existence.

**Comment by supragya** [comment]
Unit Test passes, check https://github.com/nexB/scancode-toolkit/pull/825/commits/41f0b3522390f8849bda878ce57cbf0664390c07. @pombredanne , kindly check and if satisfied, close the ticket.

**Comment by pombredanne** [comment]
Thanks! I posted some comments in the #825 PR

**Comment by pombredanne** [comment]
Merged and closed with 5f99388
