### ISSUE TITLE
Change "or" to "on" in README.rst

### ISSUE THREAD

**Issue by susg** [nexB/scancode-toolkit#826]
In the third paragraph of the topic: [Build and tests status](https://github.com/nexB/scancode-toolkit/blob/develop/README.rst#build-and-tests-status) in [README.rst](https://github.com/nexB/scancode-toolkit/blob/develop/README.rst#build-and-tests-status), there is line

> AboutCode Manager is a desktop application available or Linux, OSX or Windows

Change the first "or" to "on".

**Comment by mjherzog** [comment]
Corrected - thank you for the correction
