### ISSUE TITLE
Allow skipping license building procedure (* Building license index...) during source configure

### ISSUE THREAD

**Issue by supragya** [nexB/scancode-toolkit#827]
While building from source, ScanCode unnecessarily takes a long amount of time building license index (at the end of procedure of `source configure` under `* Building license index...`). Needed is a system which only does this in case there is a change occurring with relation to licenses, otherwise it may be skipped and last built license index be used. Something on lines of `make` is expected.

**Comment by pombredanne** [comment]
@supragya can you check the #885  branch ? there are some changes in that area.

**Comment by pombredanne** [comment]
This has been fixed with #885
