### ISSUE TITLE
Adding "stats" to "results" in ScanCode output

### ISSUE THREAD

**Issue by supragya** [nexB/scancode-toolkit#828]
A TODO at: https://github.com/nexB/scancode-toolkit/blob/bd9a0c3e801d916a54ec77228ce1d0801cf7d374/src/scancode/cli.py#L656

Needed to add stats to result outputs. @pombredanne , can you be more specific on requirements of this? Thanks

**Comment by pombredanne** [comment]
I think this is about #211 It might be best to close this ticket as a dupe of #211, copy the details from here to there and carry on #211 . @DennisClark may be able to help there too, since this is his ticket

**Comment by supragya** [comment]
@pombredanne , As far as I understand here, we are required to add these stats to output file, like displaying these stats in an HTML output or so, not separate log files. Are you sure it is https://github.com/nexB/scancode-toolkit/issues/211?

**Comment by pombredanne** [comment]
yes, this is #211 .... not as a log file but as data returned first and foremost in the data structure of a scan and then in the JSON. Adding them to html is not critical and could be bypassed for now.
See also the all important https://github.com/nexB/aboutcode/issues/7 referenced in #211

**Comment by supragya** [comment]
Close, marking redup of #211
