### ISSUE TITLE
RFC: Should the next version be 3.0 or 2.3?

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#832]
I am working on a major refactoring of the **packages** models/data structure in #275 and in #805 .... there are also changes to **copyright** data structure planned with #618 , the addition of **licenses expressions** in #74 and changing the way we report **header-level** scan/stats  info in #211 ....

This is eventually quite a bit of data structure changes that will impact directly the primary JSON output (even though I have not considered anything in the Package as stable/API-like yet)

So in light of these: Should the next version be a major 3.0 or a minor 2.3? 
To keep true with a semver'ish version scheme this should be a 3.0... but I am not too concerned with being strict there. 
I do not think this is also worth keeping older models around and would be rather complicated.

CC: @sschuberth @eclipsewebmaster @jpopelka @jdaguil @linexb  @mjherzog  @armijnhemel

**Comment by armijnhemel** [comment]
I will support whatever you choose. If you think 3.0 is more appropriate, then call it 3.0.

**Comment by sschuberth** [comment]
If the primary JSON output is affected, I'd vote for a 3.0.

**Comment by jdaguil** [comment]
I would vote for 3.0 as well since there will be significant data structure changes.

**Comment by pombredanne** [comment]
OK, thanks for chiming inj. That's enough: next version will be a 3.0 :)
