### ISSUE TITLE
--only-findings should not omit scan_errors from JSON output

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#840]
When running ScanCode 2.2.1 with `--only-findings` and a scan error like exceeding a given `--timeout` occurs, that error is not written to the JSON output. Instead, the file is treated as if no findings occurred and is completely omitted from the output due to `--only-findings`.

I believe scan errors should be included in the JSON output despite `--only-findings` being specified because if there are errors we in fact do not know for sure if there were findings or not, hence it's unsafe to exclude those files when `--only-findings` is given.

**Comment by sschuberth** [comment]
I believe having both would be beneficial: We need the per-file `scan_errors` so we know for *which* files errors occurred, but also having a top-level `error_summary` (?) which basically just is a de-duplicated set of all `scan_errors` for all files would be nice to have to get a quick overview of what *type* of errors occurred. For example, if that `error_summary` only contains `"ERROR: Processing interrupted: timeout after X seconds.` we might chose to ignore these errors since we're in control of `X` and have chosen its value as a compromise between scanning speed and scanning completeness.

**Comment by pombredanne** [comment]
Excellent point again :+1:

**Comment by sschuberth** [comment]
The main issue has been fixed via https://github.com/nexB/scancode-toolkit/pull/848, thanks @haikoschol! The additional idea that came up of having an `error_summary` (?) should be dealt with as part of #211. So I'm closing this.
