### ISSUE TITLE
Create .ABOUT files from a scan as a new output

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#845]
It would be great to support creating .ABOUT file https://github.com/nexB/aboutcode-toolkit as a scan output.

**Comment by SaravananOffl** [comment]
@pombredanne I'm interested to work on this!. Could you tell what exactly should be done?

**Comment by pombredanne** [comment]
Check what an .ABOUT file looks like in the thirdparty directory 
Then check out https://github.com/nexB/aboutcode-toolkit and in particular https://github.com/nexB/aboutcode-toolkit/blob/develop/SPECIFICATION.rst

This ticket is to create an output (or a post scan plugin? may be?) that creates .ABOUT files based on the detected packages.

**Comment by SaravananOffl** [comment]
I think I've understood what this issue is! I'll try and submit​ my patches !

**Comment by pombredanne** [comment]
@SaravananOffl do not hesistate to ask @chinyeungli for help: he is the maintainer for AboutCode-toolkit

**Comment by SaravananOffl** [comment]
@pombredanne I'm done with the setup for about files. I have to write the plugin code now.Could you guide me with step by step process ? . I'll grasp it! . I guess @chinyeungli can also help me!

**Comment by pombredanne** [comment]
@SaravananOffl See the example plugins in formattedcode

**Comment by yash-nisar** [comment]
@SaravananOffl Are you still working on this ? If not, can I proceed with this ticket ?

**Comment by pombredanne** [comment]
After thinking more about this, this is a feature for AboutCode toolkit `gen` command and not for ScanCode. Closing

**Comment by mjherzog** [comment]
I do not quite understand how it makes sense to reroute this to AboutCode Toolkit.

**Comment by pombredanne** [comment]
@mjherzog AboutCode toolkit `gen` command to generate .ABOUT files can load data from various sources including a ScanCode scan in JSON format.
Therefore this is not a feature for ScanCode... but rather for AboutCode that uses a scan to create ABOUT files
