### ISSUE TITLE
Add Copyheart license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#851]
The text is not really well defined... http://copyheart.org/ but I stumbled on an instance of it in the wild: https://github.com/CottageLabs/esprit/issues/12

` ♡ Copying is an act of love. Love is not subject to law.Please copy and share.`

**Comment by starlord1311** [comment]
can i take up this issue?

**Comment by pombredanne** [comment]
great, thanks!

**Comment by starlord1311** [comment]
can you tell what am i supposed to do?

**Comment by starlord1311** [comment]
@pombredanne can you tell how to add a license to the code? or where can i learn this

**Comment by starlord1311** [comment]
am i supoosed to change © Copyright 2010 by Author/Artist. All Rights Reserved. to ♡2010 by Author/Artist. Copying is an act of love. Please copy. everywhere in the whole code?

**Comment by pombredanne** [comment]
@starlord1311 there is a FAQ on adding new licenses rules https://github.com/nexB/scancode-toolkit/wiki/How-to:-Add-new-license-rules-for-enhanced-detection and new licenses follow the same principles

**Comment by yash-nisar** [comment]
@starlord1311 Are you still working on this one ?

**Comment by yash-nisar** [comment]
@pombredanne I'm taking this one too because the assignee is inactive.

**Comment by pombredanne** [comment]
@yash-nisar sure, but please see the PRs https://github.com/nexB/scancode-toolkit/pull/868 and https://github.com/nexB/scancode-toolkit/pull/862
@starlord1311 are yo0u OK with this?

**Comment by yash-nisar** [comment]
Roger that @pombredanne  😄
