### ISSUE TITLE
Dejacode API Toolkit

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#864]
We do have multiple projects using same code to access dejacode data.
For instance, there is code for fetching license in scancode-toolkit, aboutcode-toolkit, and possible spat as well:
https://github.com/nexB/scancode-toolkit/blob/develop/etc/scripts/synclic.py#L459

It may be a good idea to create a DejaCode API toolkit for consistency

**Comment by pombredanne** [comment]
@chinyeungli this is a great idea, but this should be started as a new project in its own repository. Closing.
