### ISSUE TITLE
Add license detection rule for Ingo R. Homann Disclaimer

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-toolkit#87]
The following disclaimer should be added as rule and detected:
```
Disclaimer:
 Copyright by Ingo R. Homann (ingo.homann@uni-bielefeld.de)
 Nicht f<FC>r kommerzielle Zwecke gedacht.
 Keine Garantie auf irgendwas.
 usw...
```

**Comment by balusarakesh** [comment]
@jdaguil please let me know what's the license to be detected in the above disclaimer. If possible post a URL.

**Comment by balusarakesh** [comment]
@DennisClark  do you have any idea what's the license for the above disclaimer?

**Comment by balusarakesh** [comment]
issue fixed
