### ISSUE TITLE
Add new Apache exception for LLVM

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#871]
See https://lists.spdx.org/pipermail/spdx-legal/2017-December/002421.html

**Comment by grubdragon** [comment]
Hey @pombredanne I'm kinda new around here. Where can I start?

**Comment by pombredanne** [comment]
@grubdragon Welcome! As you can see, there is a PR that references this ticket: #872 
.... this means that this is mostly taken care of ;) If you want to chip in, you can review exactly what @SaravananOffl has been doing there to add a new license as an example.

Otherwise, there are plenty of good tickets that need love beyond this one!
You can also ask on the https://gitter.im/aboutcode-org/discuss chat for help.
