### ISSUE TITLE
Need summary file type

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#873]
We currently have several "file type" fields returned from a scan:
- Type: either File or Directory
- MIME Type
- File Type
- Binary
- Text File
- Archive File
- Media File
- Source File
- Script File
- Package Type

For this topic, I will ignore Type since this just covers File vs Directory and focus on files only.  We need some simpler way to identify the file type in one field to facilitate filtering in AboutCode Manager and other tools.  MIME Type and File Type each have pros and cons. 

-In many cases MIME Type seems more useful because it summarizes the type a bit more - e.g. "text/x-shellscript" is probably more useful than corresponding File Types like "Bourne-Again shell script, ASCII text executable" and "POSIX shell script, ASCII text executable" because I primarily want to find all of the script files (which often do not have an extension).
- On the other hand MIME Type seems to use "application/octet-stream" as a catch-all The "octet-stream" subtype is used to indicate that a body contains arbitrary binary data.) is not very helpful .

It may be the case that we could get the best result with a new Summary File Type field where the possible values are:  Binary, Archive, Text, Media, Source or Script, but I am not sure whether a scanning will resolve to only one of these values (presumably we have multiple fields today because of some overlap).

The primary use case is that I want to easily filter for Binary and Source code files which are the primary targets for analysis. The secondary use case is to easily filter for chunks like Script or Media files. This will also be important for filtering DeltaCode results to set up alerts/warnings for code files, but ignore or lower the priority of changes to Script or Media files.

**Comment by mjherzog** [comment]
I reviewed some scans and noticed many shell script files show up as Text rather than Script so the current identification of Script: true/false is not going to help much.

**Comment by pombredanne** [comment]
I have merged this in #426
