### ISSUE TITLE
Update `CONTRIBUTING.rst` with crucial links from `README.rst`

### ISSUE THREAD

**Issue by yash-nisar** [nexB/scancode-toolkit#876]
While going through [this link](https://github.com/nexB/scancode-toolkit/blob/master/CONTRIBUTING.rst#chat-with-other-developers), I could neither find the IM (gitter channel) link nor the mailing list as included [here](https://github.com/nexB/scancode-toolkit#support). It would be great if we could update `CONTRIBUTING.rst`'s `chat-with-other-developers` section to contain all the crucial support links from `README.rst`.

@pombredanne Can I start working on this one 😛

**Comment by pombredanne** [comment]
Thanks! yes, please go ahead and send a PR

**Comment by yash-nisar** [comment]
I'm closing the issue, since the PR has been merged and the commit is [here](https://github.com/nexB/scancode-toolkit/commit/1a51a12239978d91846b1d6222936c86136639e2).
