### ISSUE TITLE
Include "Syncing local repo with the remote repo" in `CONTRIBUTING.rst`

### ISSUE THREAD

**Issue by yash-nisar** [nexB/scancode-toolkit#877]
A lot of people seem to struggle with the process of updating the fork. Since, we've almost included some crucial git commands, it would be a cherry over the cake to include the syncing of the fork.

**Comment by pombredanne** [comment]
That's fine, that sounds like basic git thing to me, so it would be best to have on the wiki IMHO

**Comment by yash-nisar** [comment]
Roger that. Should I create a PR here and move it on the wiki once it is acknowledged  @pombredanne ?

**Comment by pombredanne** [comment]
@yash-nisar You can paste your text here and add that to thw wiki afterwards. There are no PRs for this

**Comment by pombredanne** [comment]
Ok, I am closing now. Note sure we have a wiki entry but I am not sure either we should document basic Git usage.
