### ISSUE TITLE
Detected License reported line numbers are incorrect for Perl script

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#88]
OS: windows 7 64 bit
I've updated my scancode to the latest version available.
file : `automake-1.6`
`scancode` output :
```
Path	                What	  Start Line End Line	Info
C:/****/automake-1.6	License	    12	   238		FSF-MIT
```
The above give line numbers do `not match the license text line numbers` available in the attached file.
[automake2.pl.txt](https://github.com/nexB/scancode-toolkit/files/553387/automake2.pl.txt)

**Comment by balusarakesh** [comment]
fixed

**Comment by pombredanne** [comment]
@rakeshbalusa what do you mean by fixed? what fixed this?

**Comment by balusarakesh** [comment]
@pombredanne I'm not sure what fixed this, but I just scanned the text and the license numbers are correct with the latest scancode
