### ISSUE TITLE
ScanCode getting killed on Travis CI during license indexing

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#884]
We see ScanCode 2.2.1 getting killed as part of running functional tests for [ORT](https://github.com/heremaps/oss-review-toolkit) on Travis CI. `stderr` shows:

    Scanning files for: infos, licenses, copyrights with 1 process(es)...
    Building license detection index...
    /home/travis/build/heremaps/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/scancode: line 114:  5332 Killed $SCANCODE_ROOT_DIR/bin/scancode "$@"

My hunch is this only happens if the system is low on memory.

Any idea how to further debug or work around this?

/cc @mnonnenmacher

**Comment by pombredanne** [comment]
@sschuberth Thanks for this report. I think a special test script run could be made that checks memory before and after. I never saw this OOM on scancode Travis runs proper so it could have to do with using a container or a VM for a travis job too.

**Comment by sschuberth** [comment]
We now also see a core dump due to memory corruption in a similar szenario:

> /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/scancode: line 114: 272 Aborted (core dumped) $SCANCODE_ROOT_DIR/bin/scancode "$@"

    *** Error in `/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/bin/python2.7': malloc(): memory corruption: 0x00007f2afc7026b0 ***
    ======= Backtrace: =========
    /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f2b150317e5]
    /lib/x86_64-linux-gnu/libc.so.6(+0x8213e)[0x7f2b1503c13e]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f2b1503e184]
    /lib/x86_64-linux-gnu/libc.so.6(_IO_str_overflow+0x87)[0x7f2b15036d07]
    /lib/x86_64-linux-gnu/libc.so.6(_IO_default_xsputn+0x80)[0x7f2b150356b0]
    /lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x139b)[0x7f2b1500850b]
    /lib/x86_64-linux-gnu/libc.so.6(__vasprintf_chk+0xb5)[0x7f2b150d2975]
    /lib/x86_64-linux-gnu/libc.so.6(__asprintf_chk+0x82)[0x7f2b150d28b2]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x11910)[0x7f2b0f0b4910]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x119f7)[0x7f2b0f0b49f7]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x15f6b)[0x7f2b0f0b8f6b]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x11ddb)[0x7f2b0f0b4ddb]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x5746)[0x7f2b0f0a8746]

**Comment by pombredanne** [comment]
@sschuberth there have been several updates and improvements since this ticket and I never saw this issue. If you do not experience it anymore, feel free to close this. Thanks!

**Comment by sschuberth** [comment]
I also haven't seen it in quite a while!
