### ISSUE TITLE
Incorrect id for summary and clues in help_template.html

### ISSUE THREAD

**Issue by techytushar** [nexB/scancode-toolkit#892]
In the `help_template.html` file the `id` attribute of the h3 is not properly defined.
Example: It should be `<h3 id="summary">Scan Summaries</h3>` instead of `<h3 id="#summary">Scan Summaries</h3>`

**Comment by pombredanne** [comment]
Thanks! and thank you for proposing a fix too.!

**Comment by yash-nisar** [comment]
@pombredanne Since this has been solved, can this be closed ?

**Comment by pombredanne** [comment]
good point. Thanks!
