### ISSUE TITLE
Add alternatives for email and url under "How To: Set what will be detected in a scan"

### ISSUE THREAD

**Issue by inishchith** [nexB/scancode-toolkit#896]
In the "Syntax option" table , there's -p for packages . we can add -u and -e in too to that section 
 for email and url , so as to follow the convention .

Link to the wiki : [here](https://github.com/nexB/scancode-toolkit/wiki/How-To:-Set-what-will-be-detected-in-a-scan)

@pombredanne once approved by you . is it okay if i make the changes to this section of wiki ?

**Comment by pombredanne** [comment]
@inishchith sure thaings. Go for it. Thanks!

**Comment by inishchith** [comment]
Done !.
