### ISSUE TITLE
ScanCode should highlight Facebook patent grant

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#897]
While e.g. past [version v15.0.0 of react](https://github.com/facebook/react/tree/v15.0.0) is basically BSD-licensed, it comes with an additional patent grant in the [PATENTS file](https://github.com/facebook/react/blob/v15.0.0/PATENTS). As that's a rather important amendment to the license, it would be nice if ScanCode would take this into account and not just report the license as

          "key": "bsd-new",
          "score": 99.53,
          "short_name": "BSD-Modified",

but maybe use a new / dedicated identifier for this special case.

**Comment by sschuberth** [comment]
Sorry, I was seeing this when explicitly telling ScanCode to only scan the `LICENSE` file. For the `PATENTS` file ScanCode already reports

          "key": "facebook-patent-rights-2",
          "score": 99.67,
          "short_name": "Facebook Patent Rights 2",

So all 👍

**Comment by pombredanne** [comment]
Note that I recently pushed a few new rules for react. I have also in the #885 branch a few enhancements that should speed things up

**Comment by pombredanne** [comment]
re :

> Sorry, I was seeing this when explicitly telling ScanCode to only scan the LICENSE file. For the PATENTS file ScanCode already reports

FWIW, I have been thinking to add a "shallow scan" option similar to GH Licensee that would only scan a few top levle files

**Comment by sschuberth** [comment]
Or maybe only all files in the root directory, without recursing into sub-directories. Or more generically a `--directory-depth` argument. Yes, that could make sense.
