### ISSUE TITLE
license detected from a single line

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#90]
OS: windows 7 64 bit
I've updated my scancode to the latest version available.
file : [magic.txt](https://github.com/nexB/scancode-toolkit/files/15752/magic.txt)

scancode output :
```
Path	                               What	Start Line	End Line		Info
C:/doc/temporary/issue_files/magic	License	    3717	3717		LZMA SDK Original
```
A license is detected from a single line which is `# URL:  http://www.7-zip.org/sdk.html` from the file attached.

**Comment by balusarakesh** [comment]
issue fixed in the latest version of scancode
