### ISSUE TITLE
Unused function `find_and_filter(...)` in finder.py

### ISSUE THREAD

**Issue by yash-nisar** [nexB/scancode-toolkit#905]
The function `find_and_filter(...)` defined [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/cluecode/finder.py#L72-L79) seems to be redundant. Should we remove it @pombredanne ?

**Comment by vivonk** [comment]
I think it's useful for further uses in case showing more derived results, however it's not implemented yet.

**Comment by aviral1701** [comment]
May I ask how did you come up with this? @yash-nisar

**Comment by yash-nisar** [comment]
What exactly do you want to know about the issue @aviral1701 ?

**Comment by aviral1701** [comment]
I just wanted to how you found this issue? @yash-nisar

**Comment by pombredanne** [comment]
Well that's the thing that may be useful in the future and is not used... so it should likely be removed alright.

**Comment by yash-nisar** [comment]
Okay, I'll create a PR and ping you for review 👍
