### ISSUE TITLE
Core dump during scan due to memory corruption in libmagic

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#907]
We see a core dump with ScanCode 2.2.1 in CI due to memory corruption:

> /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/scancode: line 114: 272 Aborted (core dumped) $SCANCODE_ROOT_DIR/bin/scancode "$@"

    *** Error in `/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/bin/python2.7': malloc(): memory corruption: 0x00007f2afc7026b0 ***
    ======= Backtrace: =========
    /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f2b150317e5]
    /lib/x86_64-linux-gnu/libc.so.6(+0x8213e)[0x7f2b1503c13e]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f2b1503e184]
    /lib/x86_64-linux-gnu/libc.so.6(_IO_str_overflow+0x87)[0x7f2b15036d07]
    /lib/x86_64-linux-gnu/libc.so.6(_IO_default_xsputn+0x80)[0x7f2b150356b0]
    /lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0x139b)[0x7f2b1500850b]
    /lib/x86_64-linux-gnu/libc.so.6(__vasprintf_chk+0xb5)[0x7f2b150d2975]
    /lib/x86_64-linux-gnu/libc.so.6(__asprintf_chk+0x82)[0x7f2b150d28b2]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x11910)[0x7f2b0f0b4910]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x119f7)[0x7f2b0f0b49f7]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x15f6b)[0x7f2b0f0b8f6b]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x11ddb)[0x7f2b0f0b4ddb]
    /workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/typecode/bin/linux-64/lib/libmagic.so(+0x5746)[0x7f2b0f0a8746]

@haikoschol has reproduced this locally. The issue is with `libmagic` and updating it to a newer version makes the issue go away.

**Comment by haikoschol** [comment]
@pombredanne I just confirmed that the version available in Debian 9 works:
```
# apt search libmagic1
Sorting... Done
Full Text Search... Done
libmagic1/stable,stable,now 1:5.30-1+deb9u1 amd64 [installed]
  Recognize the type of data in a file using "magic" numbers - library
```

**Comment by pombredanne** [comment]
so, what would be need to fix this? a libmagic rebuild ? note also that #469 should help there (and is closely related)

**Comment by sschuberth** [comment]
> a libmagic rebuild ?

Exactly. As I understood @haikoschol this is preferably done by you due to the non-trivial "vendored"-logic you're (currently) using. The latter is where #469 would help.

**Comment by pombredanne** [comment]
ok, let me spin a rebuild with the latest libmagic and magic db then !

**Comment by sschuberth** [comment]
@pombredanne Any updates on this?

**Comment by pombredanne** [comment]
@sschuberth I did not come down to this yet. Were you able to get a l;ocal build that works for you in the meantime?

**Comment by sschuberth** [comment]
Yes, but I just wanted to get rid of that work-around 😉

**Comment by pombredanne** [comment]
@sschuberth yes this needs to be worked out for sure. At least you have a short term workaround so this is tad less critical

**Comment by pombredanne** [comment]
So with #469 we have an improved way to reference pre-built binaries... We should still update the pre-built of libmagic for the 3.0 release,

**Comment by pombredanne** [comment]
I am facing some issues with the mac and windows builds. So I am pushing this to 3.1 instead

**Comment by pombredanne** [comment]
We have completely transformed the way we handle the pre-built binaries  and this should be a non-issue now.
