### ISSUE TITLE
Update codecov version to the latest version (2.0.15)

### ISSUE THREAD

**Issue by yash-nisar** [nexB/scancode-toolkit#911]
Update codecov to the latest version (i.e 2.0.15 at the time of opening this issue). Originated from the discussion [here](https://gitter.im/aboutcode-org/discuss?at=5a734d0fb3c4a0d376cae27a).

**Comment by pombredanne** [comment]
Thanks!

**Comment by yash-nisar** [comment]
Closing this, since this issue has been resolved and merged in develop. See commit 19159a538d69fbe858c6180150ab30d882172882
