### ISSUE TITLE
Scancode Configuring for First Use Issue on Mac with "/Volumes/Macintosh HD" as the root disk

### ISSUE THREAD

**Issue by kramsram** [nexB/scancode-toolkit#912]
When I download and attempt to run scancode the first invocation gets me this error - becasue my Volume name where the Users folder lives has a space in it like so - "Macintosh HD"

MacMini:scancode-toolkit-develop krams$ ./scancode
* Configuring ScanCode for first use...
* Activating ...
/bin/sh: /Volumes/Macintosh HD/Users/krams/Downloads/scancode-toolkit-develop/bin/pip: "/Volumes/Macintosh: bad interpreter: No such file or directory

Failed to execute command:
pip install --no-allow-external --use-wheel --no-index --no-cache-dir --quiet --find-links="/Volumes/Macintosh HD/Users/krams/Downloads/scancode-toolkit-develop/thirdparty/dev" --find-links="/Volumes/Macintosh HD/Users/krams/Downloads/scancode-toolkit-develop/thirdparty/base" --find-links="/Volumes/Macintosh HD/Users/krams/Downloads/scancode-toolkit-develop/thirdparty/prod" -r "/Volumes/Macintosh HD/Users/krams/Downloads/scancode-toolkit-develop/etc/conf/base.txt". Aborting...
/Volumes/Macintosh HD/Users/krams/Downloads/scancode-toolkit-develop/configure: line 28: /Volumes/Macintosh: No such file or directory
./scancode: line 114: /Volumes/Macintosh HD/Users/krams/Downloads/scancode-toolkit-develop/bin/scancode: No such file or directory

**Comment by pombredanne** [comment]
@kramsram Thank you for the report!
This sounds like even pip cannot handle this properly. So the only way around is to use volume names without spaces I guess.... can you give it a try?
But there might be a fix possible in the configure script too.

**Comment by kramsram** [comment]
I did rename my hard drive volume and got it working. 

The process of renaming the volume is not too crazy. First need to update the home dirs of all users involved. Then rename the hard drive and boot. If you forget to the rename the home folders you will have to login as guest and change it via the System Preference->Accounts->Advanced Options UI.

The biggest impact is on Timemachine backups which cannot be continued in the same backup. Not sure what will happen to the abandoned backup file. 

The other issue which is minor is that all the Recently used lists that apps show for opening last used files will be invalid. I have not seen any more issues beyond these two thus far. 

I also have my boot drive in a separate disk so that minimized the issues from renaming the hard drive volume.

**Comment by pombredanne** [comment]
@kramsram I wish I could do something but even the standard Python tools are lost with this. Your workaround is super valuable for anyone that would be faced with the same issue. Do you think we can close this now? 

And thank for the kudos! much appreciated!

**Comment by kramsram** [comment]
Just thought of something ... Could the configure script create links to overcome this path naming issue? Or setting the value in a variable safely and then using that to pass it around? 


not sure if this is the place to put the effort in but as the script is touched for other things, perhaps?
