### ISSUE TITLE
Provide the ability to maintain a custom license collection separate from the standard ScanCode licenses

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#913]
A business may discover multiple commercial and other proprietary licenses in its product code, or in third-party products that it is evaluating for usage. These notices often appear as proprietary copyright and/or license notices in source file headers. Since the information in those license notices might be sensitive, it would be very useful to: 

Collect these notices+detection rules in a custom directory path, which could then be used in addition to the standard ScanCode licenses by a runtime option.  

Designating a custom directory path outside of the standard ScanCode directory would help to manage this custom collection and help to protect it from getting wiped out by a ScanCode upgrade.

**Comment by pombredanne** [comment]
@DennisClark Thanks!
if you think this is the same as https://github.com/nexB/scancode-toolkit/issues/480 it may make sense to merge that in this ticket

**Comment by DennisClark** [comment]
Closing as duplicate of #480
