### ISSUE TITLE
Allow to load a codebase from an existing JSON scan

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#919]
This would be a way to reprocess a codebase though plugins (including outputs) but not through scanners.

**Comment by vivonk** [comment]
@pombredanne is you are trying to say `backtracing`? or making a sample codebase from the json output of our report.

**Comment by pombredanne** [comment]
@vivonk yes. @JonoYang also is onto something, and this may be a dupe of this ticket :P worth asking!

**Comment by pombredanne** [comment]
This has been implemented and merged and is available in the latest tags. Thanks @JonoYang !
