### ISSUE TITLE
./scancode --help dumps stack trace on Debian 

### ISSUE THREAD

**Issue by jeremiah** [nexB/scancode-toolkit#920]
Using scancode-toolkit from git, version 54b9a2 I get  the following;
```
$ ./scancode --help
Traceback (most recent call last):
  File "/home/jeremiah/GitHub/scancode-toolkit/bin/scancode", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/jeremiah/GitHub/scancode-toolkit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 74, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/jeremiah/GitHub/scancode-toolkit/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

As I say I pulled the code from git so I'm not sure why its telling me to install 'packaging.requirements' or even what that package is.

**Comment by jeremiah** [comment]
I note that downloading version 2.2.1 and running scancode --help produces expected output.

**Comment by majurg** [comment]
@jeremiah Just to confirm, have you ran `source configure` while in the scancode-toolkit directory?

**Comment by pombredanne** [comment]
Thank you for the report. That's kinda weird. Which version of Debian do you run? which Python?
Could you try this after each git pull/fetch:
`./configure --clean`

**Comment by pombredanne** [comment]
This is the likely issue IMHO.

**Comment by jeremiah** [comment]
- Python 2.7.14+ (default, Dec  5 2017, 15:17:02) 
- Debian Buster/Sid

Running ./configure --clean worked. Thanks!

**Comment by pombredanne** [comment]
excellent! Thanks you for using ScanCode!
Note that we will likely participate to the GSoC 2018 again. If you have ideas of things you would need in ScanCode please create a ticket. Also I did not yet document the new plugin architecture, but this allows to create very quickly new addons.
See also GSoC  ideas at https://github.com/nexB/aboutcode/wiki/GSOC-2018
