### ISSUE TITLE
Setting correct import of files from different folders/modules

### ISSUE THREAD

**Issue by vivonk** [nexB/scancode-toolkit#921]
I seen that, in many of the files/modules, import errors are raising because the correct path is not inserted
for example
```
import scancode
import licensecode
```
will raise
```
No Module name found licensecode
```
It's because the module `licensecode` exists in `src/` directory and the using file exists in some other directory like `etc\conf`. So for correct working, we have to use relative path concept, as described [here](https://stackoverflow.com/questions/4383571/importing-files-from-different-folder)
Another [reference](https://stackoverflow.com/questions/4383571/importing-files-from-different-folder) for more clarification

**Comment by vivonk** [comment]
@majurg @pombredanne  does the configure script runs well? as in the `base.py`,
 direct ```import licensecode``` is used and the `licensecode` module is in another path

**Comment by majurg** [comment]
@vivonk I am unclear. The correct way to setup scancode is as follows:

**Comment by majurg** [comment]
@vivonk I am unclear. The correct way to setup scancode is as follows:
```
# clone scancode
$ git clone git@github.com:nexB/scancode-toolkit.git

$ cd scancode-toolkit
$ ../configure

# You are now configured to use scancode
$ (scancode-toolkit) py.test
```

**Comment by vivonk** [comment]
@majurg 
see, for example [here](https://github.com/nexB/scancode-toolkit/blob/develop/etc/conf/dev/base.py#L24). 
```
from scancode_config import scancode_root_dir
from commoncode.fileutils import create_dir
from commoncode.fileutils import copyfile
```
In this ```commoncode``` module exists in some other directory, that is `/home/vivonk/gc/aboutcode/scancode-toolkit/src` and the directory of `base.py` is `develop/etc/conf/dev`. To load the module, we have to append the path of appropriate module/modules.

**Comment by majurg** [comment]
@vivonk I understand; those imports exist in various files in our repo. My question is, what is the issue you are running into? 

Currently, all these lines of code pass our testing suite and there are certainly no import errors in a properly configured development environment.

**Comment by vivonk** [comment]
@majurg I did not seen the `__init__.py` files inside modules. Thanks to teach me a good point. It was a noobie mistake to understand. let me close the isse

**Comment by pombredanne** [comment]
`No Module name found licensecode` is because you have a typo in your import!
`import licensedcode` will work alright.
