### ISSUE TITLE
Improve tests with mutation or property-based testing

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#922]
It would great to try what we get with mutation testing ( https://pypi.python.org/pypi?%3Aaction=search&submit=search&term=mutation%20testing ) or property testing with hypothesis https://pypi.python.org/pypi/hypothesis

**Comment by vivonk** [comment]
@pombredanne  I would like to work on this so can you tell me like what kind of testing is already in our project and how the improvement is expected?

**Comment by pombredanne** [comment]
@vivonk Thanks. You can start by running the tests suite and see what type of tests we run. Most everything is under tests/ (except for a few doctests) . We use a lot of data driven tests

**Comment by pombredanne** [comment]
This is best closed at this stage. There are a few more higher priority than this and we have overall a fairly decent test suite so far.
