### ISSUE TITLE
add time stamp of scan to ScanCode output

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#925]
when running scancode it would be good to record a timestamp of when the scan started, ended or perhaps both (duration?). This makes it easier to later on identify a particular run of scancode.

**Comment by vivonk** [comment]
@pombredanne is it not implemented already? as I read something like this in the repository, in before.

**Comment by armijnhemel** [comment]
I just verified, it is not in the scancode that I am running ( 2.2.1.post241.68ea2eac0 ) with default options.

**Comment by pombredanne** [comment]
@vivonk nope, not yet implemented. This is now available in the Codebase object but not yet saved to JSON

**Comment by pombredanne** [comment]
@armijnhemel Thanks for the ticket btw :)

**Comment by pombredanne** [comment]
This has long been merged and available.
@techytushar Thanks++
