### ISSUE TITLE
Use ScanCode 'core' for other ABC data tools

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#926]
When decoupled from ScanCode-specific functions, ScanCode's new architecture would provide a good basis for future tools that deal with ABC data.

**Comment by pombredanne** [comment]
we would need ideally to make `commoncode` its own lib and likely more `scancode.resource` there and possibly a few other base `scancode` utilities

**Comment by pombredanne** [comment]
Commoncode has been spun as its own project. Beyond this it would be hard to splita core further.
