### ISSUE TITLE
Add SMAIL GPL

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#928]
See https://gitweb.gentoo.org/repo/gentoo.git/plain/licenses/SMAIL

**Comment by techytushar** [comment]
i would like to work on this ...

**Comment by pombredanne** [comment]
@techytushar Thanks!

**Comment by techytushar** [comment]
@pombredanne please close this as this is done :smile:

**Comment by pombredanne** [comment]
Indeed! all set. Thanks again.
