### ISSUE TITLE
license text for GPL is ignored in the comments section

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#93]
OS: windows 7 64 bit
I've updated my scancode to the latest version available.
file : [hashtable.txt](https://github.com/nexB/scancode-toolkit/files/15761/hashtable.txt)

For the file attached no license is detected from lines 6 to 24. The license text belongs to `GPL 3.0 or Later`

**Comment by rakeshbalusa** [comment]
I am assuming that these lines are ignored because the license text is placed line by line using `single line comments`

**Comment by rakeshbalusa** [comment]
@pombredanne  yes, the license text is placed line by line using single line comments

**Comment by pombredanne** [comment]
Fixed
