### ISSUE TITLE
Put together the list of non-SPDX licenses detected in the Linux Kernel

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#931]
This is based on a discussion with the SPDX legal team. That would be a good start to eventually add all or most scancode licenses to SPDX.

The task consist in scanning a Linux kernel 4.15 and collect all license keys that are detected and do not have an SPDX id.

**Comment by techytushar** [comment]
@pombredanne so i scanned the `linux-4.15.7` using the command `./scancode -l -n 20 --only-findings linux-4.15.7 --json-pp linux` and after running that i extracted the licenses which did not have the SPDX key. Here is the list: 

[keys.txt](https://github.com/nexB/scancode-toolkit/files/1790959/keys.txt)

Hope this is what you were looking for....

**Comment by pombredanne** [comment]
@techytushar I had somehow missed your message. Yes this is exactly what we need. Since so much time has goe by, this likely needs to be re done though.... my apologies.

**Comment by pombredanne** [comment]
This is no longer needed now that Scancode was used to detect and help normalize all the Linux kernel licenses.
