### ISSUE TITLE
Add support for "deprecated" SPDX ids

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#935]
Some widely used SPDX keys such as GPL-2.0 and GPL-2.0+ have been recently deprecated in the v3 of the licenses list.
Somehow we still need to be able to track and detect these keys as correct keys. This likely means updating the License model used for the .LICENSE YAML files to handle more than one SPDX key for a given license. One approach could be to tag each key with an SPDX list version. Another approach could be to keep a list of keys and the first one is the current most recent key (this might be simpler)

**Comment by mjherzog** [comment]
I recommend the simpler list unless we want to start working on the domain idea for licenses. We would want to document the relationship to SPDX License List version somewhere.

**Comment by pombredanne** [comment]
We use a simple list for old license+exception combos and an `other_spdx_license_keys:` attribute for ids that were renamed (such as the + vs or-later)
With these we can detect and support old and new ids without problems.

See:

- https://github.com/nexB/scancode-toolkit/blob/2148aedc3158ab9d0eec98ff2fe72e489c3de5e0/src/licensedcode/models.py#L117
- https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/gpl-1.0-plus.yml#L8
- https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/match_spdx_lid.py#L308
This works fine and is available in the latest tags.
