### ISSUE TITLE
GPL license text ignored in the file "gfortran"

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#94]
OS: windows 7 64 bit
I've updated my scancode to the latest version available.
file : [gfortran.txt](https://github.com/nexB/scancode-toolkit/files/15767/gfortran.txt) (original file is not `.txt` format)

In the attached file there is license text  in the line 896 which is not detected.
license text:

```
GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING
```

**Comment by balusarakesh** [comment]
@pombredanne  is using template for this license text a good practice?

**Comment by pombredanne** [comment]
why would you need one? also what more about the GPL version can you understand from gfortran

**Comment by balusarakesh** [comment]
@pombredanne 
```
{{GNU Fortran}} comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of {{GNU Fortran}}
under the terms of the GNU General Public License.
```
GNU Fortran seems to be a package name so, I think it would be a good idea to use a template, 
I'm still not sure about what you mean by ` also what more about the GPL version can you understand from gfortran` ?

**Comment by balusarakesh** [comment]
issue fixed
