### ISSUE TITLE
TypeError: attr() got an unexpected keyword argument 'converter'

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#941]
With the latest version from `develop` we're getting:

    15:15:09 Exception in thread "main" java.io.IOException: Running '/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/scancode --version' in directory '/workspace/oss-review-toolkit' failed with exit code 1:
    15:15:09 Traceback (most recent call last):
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/bin/scancode", line 11, in <module>
    15:15:09     load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    15:15:09     return get_distribution(dist).load_entry_point(group, name)
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    15:15:09     return ep.load()
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
    15:15:09     return self.resolve()
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    15:15:09     module = __import__(self.module_name, fromlist=['__name__'], level=0)
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/scancode/cli.py", line 60, in <module>
    15:15:09     from plugincode import output
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/plugincode/output.py", line 37, in <module>
    15:15:09     from scancode.resource import Resource
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/scancode/resource.py", line 689, in <module>
    15:15:09     class Resource(object):
    15:15:09   File "/workspace/oss-review-toolkit/scanner/src/funTest/assets/scanners/scancode-toolkit/src/scancode/resource.py", line 706, in Resource
    15:15:09     name = attr.attrib(converter=to_native_path)
    15:15:09 TypeError: attr() got an unexpected keyword argument 'converter'
This happens despite doing `./configure clean` after updating our local Git tree from tag `v2.2.1` to the current `develop` branch. However, when doing a `git clean -fdx` instead, it works. So it seems `./configure clean` is not cleaning enough?

**Comment by pombredanne** [comment]
@sschuberth `./configure clean` does nothing and should report an error. `./configure --clean` is the actual way to get a clean. It may be the reason?

**Comment by pombredanne** [comment]
I just pushed some fixes to avoid possible mishap there

**Comment by sschuberth** [comment]
> `./configure clean` does nothing and should report an error.

Actually it doesn't report an error (at least not on Windows):

    C:\Dev\oss-review-toolkit\scanner\src\funTest\assets\scanners\scancode-toolkit>configure.bat clean
    * Activating ...
    * Installing components ...
    * Configuring ...
    * Configuration completed.

But still, my bad, I should have watched the output more closely as it didn't say

    * Cleaning ...

Sorry, I'm closing this as invalid.

**Comment by pombredanne** [comment]
this was not invalid :) And I fixed it.

**Comment by sschuberth** [comment]
Well, it's invalid because I cannot expect `configure` to clean anything if I call it with `clean` instead of `--clean`. The fact that no error is printed when I pass `clean` accidentally is a different issue 😉

**Comment by pombredanne** [comment]
well it should not let you shoot yourself in the foot silently....  🗡👣 ... so this is a bona fide bug i my book :) have a great week-end!

**Comment by sschuberth** [comment]
> have a great week-end!

You too!
