### ISSUE TITLE
Error when saving the output other than the current directory

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#949]
I got an error when trying to save the output
```
./scancode -n2 -lceupi --json=~/inventory/scancode-result.json <project>
Error: Invalid value for "--json": Could not open file: ~/inventory/scancode-result.json
```

Note that saving the result in the `current` directory run fine:
./scancode -n2 -lceupi --json=arm-devel-scancode-result.json <project>

**Comment by pombredanne** [comment]
Thanks! that should be an easy fix. We should resolve the path including expanding user home and possible variables.

**Comment by pombredanne** [comment]
@chinyeungli this seems to be fixed and no longer an issue. Closing now. Please reopen if you still this issue
