### ISSUE TITLE
no license detected for the available GFDL license notice

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#95]
OS: windows 7 64 bit
I've updated my scancode to the latest version available.
file : [NEWS.txt](https://github.com/nexB/scancode-toolkit/files/15769/NEWS.txt)

In line 6 of the attached file a small notice is given regarding the license for the file but there were no results by scancode.
notice : 
```
- license of manual now GFDL 1.2 or later, with no invariant sections.
```

**Comment by pombredanne** [comment]
@rakeshbalusa attaching the file is useful, but providing the URL to that file would be much better
Merged. Thank you!
