### ISSUE TITLE
Add plugin to extract "winexe" metadata from DLLs and similar

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#954]
DLLs, EXEs and other Windows-specific binary files have important package metadata that is very useful for analysis of a Windows platform codebase.  The fields we have previously extracted with nexB-Toolkit include:
- winexe_apiversion 
- winexe_assembly_version 
- winexe_builddate 
- winexe_buildversion 
- winexe_comments 
- winexe_company
- winexe_companyname
- winexe_filedescription
- winexe_fileversion
- winexe_full_version
- winexe_internalname
- winexe_legalcopyright
- winexe_legaltrademarks
- winexe_legaltrademarks1
- winexe_legaltrademarks2
- winexe_license
- winexe_originalfilename
- winexe_productname
- winexe_productversion
- winexe_www

We need to add a new feature to handle this data as a ScanCode plugin and eventually include a subset as a type of Package in AbC Manager.

**Comment by mjherzog** [comment]
There seem to be two different aspects to this issue:
1. We need to confirm that ScanCode detects and reports metadata from "winexe" Packages, but that will only be a subset of these metadata columns.
2. We may need to keep a version of this utility separate from ScanCode when we need all the fields.
Both aspects are similar to RPM metadata.

**Comment by pombredanne** [comment]
At this stage we have the base code for collecting data from Windows DLLs but we do not have yet a plugin for that https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/win_pe.py

**Comment by pombredanne** [comment]
@maxhbr ping

**Comment by pombredanne** [comment]
This has been integrated in scancode BUT does not work yet

**Comment by pombredanne** [comment]
This is integrated and works now with #2526
