### ISSUE TITLE
ScanCode 2.9.0b1 hangs on sqlite3.c

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#964]
ScanCode 2.9.0b1 hangs on `sqlite-autoconf-3220000/sqlite3.c` from https://www.sqlite.org/2018/sqlite-autoconf-3220000.tar.gz

The error message is `"ERROR: for scanner: copyrights:\nERROR: Processing interrupted: timeout after 120 seconds."`

**Comment by pombredanne** [comment]
@JonoYang thanks!. This is especially relevant because there have been quite a few refinements in copyright detection

**Comment by pombredanne** [comment]
@ThorstenHarter Thanks. FWIW I am working on dealing with larger files in a better way that would not force to increase the timeout. Some of it is tracked in #695

**Comment by joaocfernandes** [comment]
I am also able to replicate this

**Comment by pombredanne** [comment]
@joaocfernandes Thanks. That's a pain indeed

**Comment by JonoYang** [comment]
The head of the develop branch is able to scan sqlite3.c with no problems now. Closing
