### ISSUE TITLE
CSS to fix HTML report scrolling problems

### ISSUE THREAD

**Issue by davisford** [nexB/scancode-toolkit#966]
Don't have time to dig through code and find the spot to suggest a proper PR right now, so I'm just dropping this here -- use if you wish.

When you generate an HTML report there are two panes.  In the left, you have the file directory structure and as you select a file or directory, it shows the licenses it finds in the right pane.

For very large projects, I found it to be very annoying that as you scroll down in the left pane, the right pane scrolls as well, and each click on the left pane requires you to scroll back up in the right pane to see the results as you select new areas in the left pane.  

Drop this in the `<head>` section of the output html to resolve -- and better yet someone can maybe make a PR or resolve the issue in a better way.  

```html
<style type="text/css">
        #tree {
            max-height: 70vh;
        }
</style>
```

**Comment by pombredanne** [comment]
@davisford Thanks! that should be enough to fix. Note that FWIW this html-app will eventually be deprecated and dropped as there is a new and shiny much improved way to visualize scans with the AboutCode Manager app: https://github.com/nexB/aboutcode-manager
This should not much of the issues of a static html app and has many more ways to search and view the scans.

**Comment by davisford** [comment]
Oh nice!  Can I use that now?

**Comment by mjherzog** [comment]
Yes - Note that AbC Manager and ScanCode Toolkit are under very active development so you will want to use the latest versions in tandem.

**Comment by pombredanne** [comment]
This has been applied and merged long ago. Thanks again. Closing.
