### ISSUE TITLE
No detection for the new added licenses.

### ISSUE THREAD

**Issue by muzsielod** [nexB/scancode-toolkit#968]
Hello,
I'm using the scancode 2.2.1. I added a few licenses as is stated in the FAQ. The name.LICENSE file and the name.yml files and tried even the Rules, but when I scan my test files, it doesn't identifies the licenses.
What should I do to get things working. 
Thank you.

**Comment by techytushar** [comment]
@muzsielod make sure you have the same file name all over the place i.e in the data and also in the test.
Have a look at this [PR](https://github.com/nexB/scancode-toolkit/pull/943/files)

**Comment by pombredanne** [comment]
@muzsielod Thanks for the report!
do you use a development git checkout or this is a release archive instead?
The most likely case is that you are using a release archive and there may be some extra step needed (that may not be documented properly, sorry for this) to ensure that new added licenses are picked

**Comment by muzsielod** [comment]
Yes that was the case. I used the released package. With the developer package it's working well. Thank you all for your help 👍

**Comment by pombredanne** [comment]
@muzsielod the missing part is to run `scancode --reindex-licenses` once after you add a new license or rules so they can be added on the index (it was done automatically before, but that was rather slow, so this is a separate option to invoke now)

**Comment by muzsielod** [comment]
@pombredanne ohh, that's even better. 
Thank you for your fast response.

**Comment by pombredanne** [comment]
@muzsielod sure thing. Feel free to close if you consider this issue close. Just out of curiosity, could this be a license that could be worthy of addition to the public dataset? or is this instead a private license? Would it be easier for you if there were a way to add extra, private licenses in a separate directory?

**Comment by muzsielod** [comment]
Hi @pombredanne . It was about a private license I created, but the scancode --reindex-licenses did the trick. I will close the issue. 👍
