### ISSUE TITLE
wrong license detected and the correct license text is ignored

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#97]
OS: windows 7 64 bit
I've updated my scancode to the latest version available.
file : [dhash.txt](https://github.com/nexB/scancode-toolkit/files/15779/dhash.txt)

scancode output :
```
Path	                             What	Start Line	End Line		Info
C:/doc/temporary/issue_files/dhash.h	License	   6	6		Public Domain
```
In the above file the correct license text seems to be from line 11 to 22 which is `LGPL 3.0 or Later` but the license `public domain` is detected and the `LGPL 3.0 or Later` license text is ignored.

file : [dhash_example.txt](https://github.com/nexB/scancode-toolkit/files/15780/dhash_example.txt)
In the above file license text for `LGPL 3.0 or Later` is available from lines 7 to 18 but there were no results from scancode.

**Comment by balusarakesh** [comment]
issue fixed in the latest version of scancode
