### ISSUE TITLE
add support for author metadata in scancode

### ISSUE THREAD

**Issue by rakeshbalusa** [nexB/scancode-toolkit#98]
Please provide support in scancode to extract the metadata of an author for a given component. When scancode is used to scan a codebase there is no metadata extracted for an author. It is good to have this metadata as author plays a key role in the origin of the  codebase.

**Comment by pombredanne** [comment]
Authors are collected already internally by the copyrights scan.

**Comment by rakesh8015** [comment]
@pombredanne  You asked me to post a ticket for this. Because nexb-toolkit has this feature and you said scancode must have this feature.

**Comment by pombredanne** [comment]
Authors, maintainers and more are now collected OK as part of a package scan. Closing
