### ISSUE TITLE
Initial license index creation on first run is too long

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#988]
The time to create the license index on the first run has been growing quite a bit with the number of license rules and licenses. And because of the way the detection works, the more we have of these, the faster the license detection runs, so we want more of these.
We could two things:
- Include a pre-built index in the release archives (compressed with GZ, that's an extra ~ 20 MB and with xz which is super slow on the compression size, that would be an extra ~8MB). Both should be rather acceptable
- profile and optimize index creation to speed it up

In all cases, the index check when in development would stay the same (and eventually require frequent index rebuilds for consistency). Note that these checks could be also tuned: today we consider any change anywhere in the code or data as the condition to invalidate and rebuild the index. We could limit this check to the `licensedcode` module code and data only for a small speedup and less frequent index rebuilds with a minimal risk of index inconsistencies

**Comment by mjherzog** [comment]
I am not clear about what "any change in code or data" means here. Can we restrict the trigger to changes in the license data (perhaps another reason to move that database to its own repo?)

**Comment by pombredanne** [comment]
@mjherzog "any change in code or data"  means really any change. The check is done there https://github.com/nexB/scancode-toolkit/blob/fea65d35a475553368db17a1d196e61a92974a74/src/licensedcode/cache.py#L180 it it triggered if any time stamp, filepath or size has changed in the whole scancode code tree. Now this applies only in `development mode` (e.g. working from a checkout) where code changes are expected to be frequent and we cannot easily distinguish from the outside if a code change may impact the license index and require a rebuild or not. 

In a user install from a release archive, no such checks are made and the index is created only once on the first run and not checked nor rebuilt ever for that given version of ScanCode (unless you use `scancode --reindex-license` command. )

**Comment by pombredanne** [comment]
FWIW, that is not really related nor impacted by moving the license data in their own repo: this would just make things a tad more complicated, but having checks or not and when they are needed would still apply

**Comment by pombredanne** [comment]
We could consider adding the prebuilt index to the release archives... after all a full index is about only 12MB when compressed with xz

**Comment by mjherzog** [comment]
This would be nice to get people started quicker with their first scan, but we would need to be clear about when and how to rebuild since the indexing would be less visible to a new user.

**Comment by pombredanne** [comment]
The resolution is to going  bundle the pre-built index in the release archives

**Comment by pombredanne** [comment]
We now bundle a pre-built index making this a solved problem.
