### ISSUE TITLE
handle lzip compressed file

### ISSUE THREAD

**Issue by pkunz** [nexB/scancode-toolkit#989]
Scancode can not extract a lzip file.   Not wired to interface

**Comment by pkunz** [comment]
try http://ftp.gnu.org/gnu/ddrescue/ddrescue-1.23.tar.lz

**Comment by armijnhemel** [comment]
http://www.nongnu.org/lzip/lzip.html might be easier (smaller)

**Comment by pombredanne** [comment]
@pkunz thanks for the report and @armijnhemel thanks for the pointer!
I did a quick test and the internal code of extractcode can extract this alright (though libarchive) so this is just a matter of wiring this in for archive recognition and add a few tests.

**Comment by armijnhemel** [comment]
Same as #245

**Comment by pombredanne** [comment]
Closing in favor of #245
