### ISSUE TITLE
Returned data from package scan (-p option) doesn't match with the Package Identification from DejaCode

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#993]
I've a codebase which have a brunch of JARs.
However, the scancode package scan (-p option) doesn't return any information, but using https://enterprise.dejacode.com/identification/ return me something.

I expect the package scan from scancode return the same result as "Package identification" from https://enterprise.dejacode.com/identification/

**Comment by pombredanne** [comment]
@chinyeungli This is not a problem with ScanCode. Closing.
