### ISSUE TITLE
add H2 license

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#994]
https://repository.jboss.org/licenses/h2.txt

This is an older license, as the developers of H2 now seem to have moved away to MPL/EPL:

http://www.h2database.com/html/license.html

However, it might still pop up in older versions of the software.

**Comment by pombredanne** [comment]
@armijnhemel Thanks for the report. This is seems heavily based on the MPL alrigh: another franken-license I guess and worth tracking: h2 is rather common

**Comment by pombredanne** [comment]
Fixed in develop.

**Comment by pombredanne** [comment]
I am doing some cleanup and review as a prep for the 3.0 release... and since this is fixed in develop, I am closing this!
