### ISSUE TITLE
Filter more junk emails

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#997]
For instance:
testUser@gmail.com
some@other.com

**Comment by durgeshra** [comment]
Hi! I think I can do this. Which file in your repo should I made the changes?

**Comment by pujanm** [comment]
@pombredanne I would like to solve this issue as I have seen this type of problem where users tend to type in such junk emails. Can you elaborate on this issue further?

**Comment by Gaupeng** [comment]
@pombredanne May I take this up? Also, would you suggest hardcoding common spam words/strings to ignore these emails?

**Comment by pombredanne** [comment]
@Gaupeng re:
> May I take this up?

Sure. Thanks!

> Also, would you suggest hardcoding common spam words/strings to ignore these emails?

yes, that's an acceptable way.

**Comment by dakshaladia** [comment]
Hi I wish to contribute to this issue. Is still available?
